### ISSUE TITLE
[ec2] CfnTransitGatewayAttachment Update Failures

### ISSUE THREAD

**Issue by ten-lac** [aws/aws-cdk#10045]
When updates are made to the same TransitGatewayAttachment object, it fails when the `subnetIds` are not in the same order.

### Reproduction Steps

Run this first time

``` javascript
new CfnTransitGatewayAttachment(this, `tga-${vpcId}`, {
                transitGatewayId: transitGateway.ref,
                vpcId,
                subnetIds: ['subnet-1','subnet-2']
            });
```

Then run this the second time.

``` javascript
new CfnTransitGatewayAttachment(this, `tga-${vpcId}`, {
                transitGatewayId: transitGateway.ref,
                vpcId,
                subnetIds: ['subnet-2','subnet-1']
            });
```

### What did you expect to happen?

The update to succeed.

### What actually happened?

Failed with:

```
4:18:41 PM | UPDATE_FAILED        | AWS::EC2::TransitGatewayAttachment | tga-vpc-09e3ab35c65ee58e8
tgw-010a740596c4114b9 has non-deleted Transit Gateway Attachments with same VPC ID. (Service: AmazonEC2; Status Code: 400; Err
or Code: DuplicateTransitGatewayAttachment; Request ID: a122a2be-b06a-42ef-a59c-fed1e541cd7e; Proxy: null)
4:18:41 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack         | Tenna-Network-Hub-test
The following resource(s) failed to update: [tgavpc09e3ab35c65ee58e8].
```

### Environment

- `node@12`
- `cdk@1.61.1`
- macOS

### Other

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @ten-lac!

Thanks for reporting this. This is not unexpected behavior however. As you can see both [here](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_physical_names), and [here for Cloudformation](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-custom-name/). Because this is an L1 construct (directly utilizes Cloudformation without any frills on top), it has to comply with the Cfn requirements, and if a resource has a physical id (`transitGatewayId`), it must be replaced to update, updating internal values only will not work.

To have this update succeed, you will have to delete and rebuild the stack.

I hope this helped answer your question. Let me know if you have any further questions on this behavior!

😸 😷

**Comment by tommydongaws** [comment]
Hi, I get the reasoning behind that but its not very intuitive that we need to delete the stack. Is it possible to add it to the error message, that we may need to delete the stack?
