### ISSUE TITLE
Debugging AWS-CDK deployment using the NodeJS Debugger

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#10052]
The NodeJS Debugger is a powerful tool that allows inspecting stack traces, breakpoints, etc and especially its tight integration with Run/Build configurations of popular IDEs like WebStorm, PHPStorm, VSCode.

It would be great if we could take advantage of all this while deploying a complex AWS CDK application, that consists of many stack and constructs and libraries (stacks or constructs coming from third parties).

### Proposed Solution
Provide NodeJS specific instructions on how to enable the debugger from the AWS CLI or through an IDE integration.

I've tried digging deeper into what the global "cdk" command does and all it does is to start a NodeJS process for the following script:
`node inspect /Users/my-user/.nvm/versions/node/v13.11.0/lib/node_modules/aws-cdk/bin/cdk.js
`

So my natural first attempt was to run `node inspect somescript.js` like so:
`node inspect /Users/dzhuneytahmed/.nvm/versions/node/v13.11.0/lib/node_modules/aws-cdk/bin/cdk.js deploy '*'`

This lead to some positive results like dropping me into the NodeJS debugger command line, where I am able to run NodeJS debug commands like "cont" (for "continue"). However, this is far from "easy to use" as the IDE built-in debugger functionality, which looks something like this:
![image](https://user-images.githubusercontent.com/1754428/91631033-ead41300-e9de-11ea-9e83-946c32221367.png)

* [X] :wave: I may be able to implement this feature request, given some guidance
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by evgenyka** [comment]
Isn't this covered in https://devopstar.com/2020/02/04/cdk-debugging-in-vscode/?

**Comment by anentropic** [comment]
I think the latter two comments achieve something different to what the OP (and I) are trying to do

it's easy to get a breakpoint into your own stack code via the usual means (e.g. in Python I can just add a `breakpoint()` call somewhere)

The part I think OP is trying to address is how to get a breakpoint into the CDK internals e.g. when you get some obscure CloudFormation error and need to find more details

Or perhaps it's different for JS/TS projects, but in Python projects a breakpoint in your stack code is not very helpful for many of these cases because all the deployment logic happens across a process boundary in the nodejs engine that runs the `cdk deploy` command

**Comment by pahud** [comment]
Just FYR I have made a video for this
https://www.youtube.com/watch?v=wWVoR0KFV6U
