### ISSUE TITLE
[ecs] Can't import existing Fargate cluster

### ISSUE THREAD

**Issue by benjie23** [aws/aws-cdk#10063]
### The Question

I'm trying to import an existing Fargate cluster into my cdk app.

Ive tried to use `Cluster.from_cluster_attributes` static function, but it **requires** both VPC & Security groups that are attached to the required cluster.

Ive created my Fargate cluster without VPC (as its **optional**) and now I cant find a way to import it to my stack. 

### Environment

  - **CDK CLI Version:** 1.6.0
  - **Module Version:** 6.9.0
  - **Node.js Version:** v10.16.3
  - **OS:** Windows 10 
  - **Language (Version):** Python (3.8.3)

**Comment by ihorfito** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

List of resources that support import.

**Comment by benjie23** [comment]
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
> 
> List of resources that support import.

ECS CLuster is on that list.

**Comment by ihorfito** [comment]
This article might help you:

https://medium.com/@visya/how-to-import-existing-aws-resources-into-cdk-stack-f1cea491e9

**Comment by NGL321** [comment]
Hey @benjie23,

Unfortunately, from what I can tell, there is no way at the moment to import a Fargate cluster without a VPC (@uttarasridhar please correct me if I am incorrect). The guidance shared by @ihorfito is how you might use Cloudformation tricks to import an existing resource, and that is likely your best option for import at the moment.

If you would like to see a more generalized import added as a feature, you can convert this issue into a feature request (copy the template from a new "feature request" issue into the body of this one, and make sure you provide all indicated information) and someone from the ECS group will consider it when they can.
Otherwise, let me know and I can close out this issue.

Sorry I dont have a better answer for you at the moment.

😸 😷

**Comment by cal5barton** [comment]
@NGL321 @uttarasridhar is there an underlying reason why when importing the cluster it requires clusterName, vpc, and securityGroups? It would be nice to just be able to import it by ARN if there isn't something technical blocking this.

Also noticed when creating an `ApplicationLoadBalancedFargateService` it requires you to pass the ICluster construct even though, from what I can tell, just requires the cluster name. If that is correct then it would alleviate the need to import the cluster all together and could just support the string value instead of requiring the full construct. Thoughts?
