### ISSUE TITLE
[aws-eks] Allow multiple EKS clusters in the same stack

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#10073]
Currently, we only allow a single EKS cluster to be defined within a CDK stack (the custom resource provider is a stack-singleton).

**Comment by iliapolo** [comment]
We are putting this on the back burner for now as the naive implementation will require cluster replacement. We might find creative solutions later on if this is needed.

**Comment by itajaja** [comment]
sharing my use case for multiple clusters, even though I am pretty sure it wouldn't be too hard too imagine many more. I have a vpc with two separate subnets, and a cluster in each subnet. the two clusters have very different purposes, have very different nodes, and run very different workloads, but they share some resources (eg s3 buckets) that are defined in the cdk stack. splitting them would be possible but it's definitely not optimal.

I am still unclear about the root problem, @iliapolo you mentioned that "having multiple clusters in the same stack would force those clusters to have a publicly accessible endpoint" but I don't understand why is that the case, and what part of the system forces that. I doubt it's EKS itself, so what is it?

**Comment by iliapolo** [comment]
@itajaja The problem is that the `KubectlProvider` (the lambda that runs `kubectl` commands against the cluster) is currently a stack singleton, and is defined when the first cluster is declared. 

When its defined, it is also configured with subnets and security groups that match the cluster, so if you define a second cluster, the handler will not get its network configuration and hence will not be able to run `kubectl` commands against it. 

For the handler to be able to run commands against both clusters, those clusters will need to have a publicly accessible endpoint, since in that case the handler isn't configured with any cluster specific network configuration.

The limitation is indeed a CDK thing, not an EKS, and is rooted in how the current module is structured. (sorry, i thought you meant is it solvable purely by aws-cdk **users** in your comment [here](https://github.com/aws/aws-cdk/pull/9802#issuecomment-692577146), which to that the answer is no, but can definitely be solved by changing the construct code itself).

Changing this structure so that a handler will be created **per cluster, and not per stack** will unfortunately require replacement of existing clusters, which is why opted not to do that currently. 

You mentioned that:

> but they share some resources (eg s3 buckets) that are defined in the cdk stack. splitting them would be possible but it's definitely not optimal.

Can you explain why you consider this to be non optimal? Do you mean as far as the code structure or because it has some deployment implications? It actually seems to me that if the clusters serve two different purposes, they would benefit from being in different stacks because their deployment would be decoupled (you can destroy and deploy each of them separately, and each will not be affected by a rollback due to a failed initial deployment of other resources in that stack).

**Comment by itajaja** [comment]
thanks for the explanation, it makes sense now. the problem then is not even whether is hard or not to implement, but that it's not going to be implemented because it will cause a replacement; I see how you'd want to avoid this.

> It actually seems to me that if the clusters serve two different purposes, they would benefit from being in different stacks because their deployment would be decoupled

this is a fair point, as I sometimes feel my stack is too large and coupled. but in general, if a resource needs to be referenced by two stacks, in one of the two stacks I'd have to get a reference to it by ARN, which is not optimal, right? or am I missing something?

**Comment by iliapolo** [comment]
@itajaja 

You can pass constructs between stacks just like you would pass constructs inside the same stack.

Let me propose a structure based on what you described and tell me what you think:

Split your big stack into 3 smaller ones:

1. `SharedResourcesStack` - Would contain the VPC, the subnets, and the s3 bucket - will expose those constructs as public stack fields.
2. `Cluster1Stack` - Stack for purpose 1 cluster - will accept the resources it needs from the shared stack.
3. `Cluster2Stack` - Stack for purpose 2 cluster - will accept the resources it needs from the shared stack. 

And your app would look something like this:

```typescript
const sharedStack = new SharedResourcesStack(...);
const cluster1Stack = new Cluster1Stack(app, 'Cluster1Stack', {
  // lets say you need to pass a bucket from the shared stack
  bucket: sharedStack.bucket
})
const cluster2Stack = new Cluster2Stack(this, 'Cluster2Stack', {
  // lets say you need to pass a VPC from the shared stack
  vpc: sharedStack.vpc
})
```

The CDK will automatically create and wire the necessary references using stack parameters and outputs.
In addition, cdk will auto-deploy the shared stack when you deploy any of the cluster stacks. If something in `Cluster1Stack` changes, you can just deploy that (`cdk deploy Cluster1Stack`). If anything in the shared stack changes, cdk will redeploy the dependent stacks as well. 

Would that be a reasonable setup for you?

**Comment by itajaja** [comment]
@iliapolo thanks, that looks great. I'll actually apply this pattern even further so that I can split my giant CFN template into smaller units. thanks, this is really helpful!

**Comment by iliapolo** [comment]
@itajaja Awesome, glad this helps :)

There is one disadvantage in the setup I described though. 
 
If `sharedStack.bucket` changes (say is renamed), the deployment will fail with:

*Export ... cannot be deleted as it is in use by Cluster1Stack*

This is because it will attempt to delete a bucket who's name is being exported and used by other stacks.

To perform such a change, you'd need to create a **new** bucket, pass that bucket to the cluster stack, deploy, and then remove the old bucket from `SharedStack` and deploy again. 

Was that clear enough?

**Comment by itajaja** [comment]
yep that's clear. I already had to deal with similar two-step upgrades in the past 👍

**Comment by iliapolo** [comment]
Removed this from the current [milestone](https://github.com/aws/aws-cdk/milestone/6) because it was initially for a situation that requires cluster replacement, since we decided not to pursue this, we are currently sticking with this limitation.

Will be re-evaluated if we see enough use cases the justify adding such capabilities, at which point we would need to think of creating solutions to implement it without cluster replacement, a few options:

- Connect the `KubectlProvider` to multiple networks and security groups
- Extract `KubectlProvider` to a nested stack **per cluster**, and override logical id's for the "first" cluster.

**Comment by itajaja** [comment]
@iliapolo apologies if I hijack this issue a little, but I have a question for splitting the stacks. it's not considered a good practice to modify constructs created with stack A in the constructor of stack B, right? for example:

```ts
// ... inside class StackB
constructor(scope, id, stuffFromStackA) {
	super(scope, id);
 	stuffFromStackA.postgresSecurityGroup.addIngressRule(...);
}
```

this is counterintuitive because it's inside the StackB constructor, but it actually is part of stackA and that change is deployed with stackA. the problem is more apparent when eg you do

```
stuffFromStackA.postgresSecurityGroup.addIngressRule(securityGroupInStackB);
```

because this would generate a cyrcular dependency. Is the right solution to do:

```
const postgresSecurityGroup = SecurityGroup.fromSecurityGroupId(
    scope,
    'postgres-security-group',
    stuffFromStackA.postgresSecurityGroup.securityGroupId,
  );
stuffFromStackA.postgresSecurityGroup.addIngressRule(...);
```

that is, only use the ids that are coming from stack A but never the constructs themselves?

Thanks!

**Comment by eladb** [comment]
@iliapolo I am wondering if we need to add a note to the EKS README about this limitation and also refer to some docs around multi-stack apps?

**Comment by iliapolo** [comment]
@itajaja 

> that is, only use the ids that are coming from stack A but never the constructs themselves?

Circular dependencies are formed when stacks depend on each other via references. So if you pass an id from a resource within stackA to stackB, you make stackB depend on stackA, regardless of whether the resource itself is being passed. 

You'd have to do some juggling with the stacks to circumvent potential issues, and like @eladb mentioned, we should and will add some general guidance for working with multi-stack apps. 

Specifically in your case,  i'm not sure why a circular dependency would be created. The ingress rule can be created in either of the stacks, and it should only create a one way dependency. Perhaps there are other parts of the stack that actually create the two way dependency?

**Comment by itajaja** [comment]
> Specifically in your case, i'm not sure why a circular dependency would be created. The ingress rule can be created in either of the stacks, and it should only create a one way dependency. Perhaps there are other parts of the stack that actually create the two way dependency?

the security group is part of stack A, but then you add to it a rule that depends on stack b, hence the circular dep. this is solvable by referencing that same security group from stack b via id as I described above

**Comment by iliapolo** [comment]
@itajaja 

> (stack B already depends on other parts of stack A)

Yeap, that makes sense. 

> if you instead redefine the same security group with the fromId and then call addIngressRule, that will be part of stack B, potentially solving dependency issues

You're right that using `fromXXX` gives you the ability to essentially redefine the scope of a construct, and avoid potential circular deps. I would still like for CDK to better handle these potential issues as this "solution" is quite involved.

**Comment by pgollucci** [comment]
I do not have this use case.
