### ISSUE TITLE
[ecs-patterns] Use listenerPort as target?

### ISSUE THREAD

**Issue by anticlockwise** [aws/aws-cdk#10106]
https://github.com/aws/aws-cdk/blob/f2d77d16d62e80d23c200ea94e4181660d953ca2/packages/%40aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts#L285

This line here assumes that the target will be listening on port 80, but assuming that the target container does E2E encryption, then wouldn't it listen on a different port like 443 instead? Can we use the value of `listenerPort` instead?

**Comment by hoegertn** [comment]
This should only be the default port. The task definition provides the containerPort that is used as target.

**Comment by anticlockwise** [comment]
@hoegertn can you elaborate a bit? Because the `containerPort` is the port opened and listened on for the container. The port 80 here is the port for the TargetGroup.

**Comment by hoegertn** [comment]
The targetProps define the default port of the TargetGroup. But the service then registers IP target with their own ports which should be the port of the container. But I am not 100% sure if this applies to NLBs also.
Did you try to deploy the application and it failed? The target group should have a default port but each target should have its own port definition.

**Comment by anticlockwise** [comment]
I see, so you're saying that the port on the TargetGroup is just a default, the real port used is the `containerPort`? It's a little confusing to me since we have three separate ports: `listenerPort` for NLB, a port for TargetGroup, `containerPort` for the container/task definition.

**Comment by matwerber1** [comment]
Running into same confusion. 

I have: 

```
const ecsApp = new ecs_patterns.NetworkLoadBalancedFargateService(this, "MyFargateService", {
      [...other properties omitted for brevity...]
      listenerPort: 5000,
      taskImageOptions: {
        [...other properties omitted for brevity...]
        containerPort: 5000,
      },
    });
```

This creates an NLB with a listener for port 5000, as well as an ECS service with containers listening on port 5000. So far, so good. 

However, the bridge between the NLB listener and the container is the target group...and the CDK creates a target group with a specified port of 80 with no way to override this. 

![image](https://user-images.githubusercontent.com/28939541/92298468-074fde00-eefe-11ea-8818-edcde166cfb3.png)

The logic is request (port 5000) -> NLB Listener (port 5000) -> Target Group (port 80) ---Fails to send, port mismatch--> Fargate container (port 5000).

However, I noticed that the targets (containers) registered to the target group by ECS do show port 5000 in the target group description:

![image](https://user-images.githubusercontent.com/28939541/92298489-2c445100-eefe-11ea-804b-22fd6fa09258.png)

I would have thought this wouldn't even be allowed, but it is. So, searched docs, and suspicion confirmed: 

> By default, a load balancer routes requests to its targets using the protocol and port number that you specified when you created the target group. **Alternatively, you can override the port used for routing traffic to a target** when you register it with the target group.

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#target-group-routing-configuration

What this means is that ECS is overriding the target group configuration when it registers the tasks.

I think this means there's no actual problem, apart from the fact that things "appear" wrong. I still think it would be worthwhile to change the CDK construct to create the default target group with a port that matches the specified container port in the task options...

Disclaimer, I haven't been able to actually test this, since I think I have an error somewhere that is causing my containers to fail their health check. But that's a different story - the docs above appear to confirm there's no technical blocker.

**Comment by Seven2Nine** [comment]
For Python

```python
cfn_resource = service.target_group.node.find_child("Resource")  # type: CfnTargetGroup
cfn_resource.add_property_override("Port", <YOUR_ACTUAL_PORT>)
```

> If you dislike - like me - that the port looks incorrect:
> 
> ```js
> const cfnTargetGroup = service.targetGroup.node.findChild('Resource') as CfnTargetGroup
> cfnTargetGroup.addPropertyOverride('Port', <YOUR_ACTUAL_PORT>)
> ```
