### ISSUE TITLE
[codebuild] Code example update in aws-codebuild ReadMe doc

### ISSUE THREAD

**Issue by aijunpeng** [aws/aws-cdk#10114]
I followed the CodeCommitSource code example in aws-codebuild readme doc to create a codebuild project and got the following error:

```console
Argument of type '{ repo1: codecommit.Repository; }' is not assignable to parameter of type 'CodeCommitSourceProps'.
  Object literal may only specify known properties, and 'repo1' does not exist in type 'CodeCommitSourceProps'.
```

The code should be updated as follows:

Current:
```ts
const repository = new codecommit.Repository(this, 'MyRepo', { repositoryName: 'foo' });
new codebuild.Project(this, 'MyFirstCodeCommitProject', {
  source: codebuild.Source.codeCommit({ repository }),
```
New:
```ts
const repository = new codecommit.Repository(this, 'MyRepo', { repositoryName: 'foo' });
new codebuild.Project(this, 'MyFirstCodeCommitProject', {
  source: codebuild.Source.codeCommit({ repository:  repository}),
});
```

### Reproduction Steps
Run MatchSnapshot test with the following code. The code is written following the CodeCommitSource code example in the aws-codebuild readme doc. The only difference is that "repository" in the readme code example is replaced with "repo1".
```ts
const repo1 = new codecommit.Repository(this, 'MyRepo', { repositoryName: 'foo' });
new codebuild.Project(this, 'MyFirstCodeCommitProject', {
  source: codebuild.Source.codeCommit({ repo1 }),
```
### What did you expect to happen?
Expect test to be successful

### What actually happened?
Test failed with the following error: 
```console
Argument of type '{ repo1: codecommit.Repository; }' is not assignable to parameter of type 'CodeCommitSourceProps'.
  Object literal may only specify known properties, and 'repo1' does not exist in type 'CodeCommitSourceProps'.
```
### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @aijunpeng, thanks for opening an issue! The [CodeCommitSourceProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.CodeCommitSourceProps.html#properties) repository property is named "repository" so because of javascript's object property shorthand if you set the property's value to also be "repository" you don't have to say it twice `{ repository }`. But in your case since you set it to "repo1" then you do have to say `{ repository: repo1 }`.

Here's a [resource](https://alligator.io/js/object-property-shorthand-es6/#:~:text=New%20in%20JavaScript%20with%20ES6,simply%20pass%20the%20key%20name) explaining that javascript concept.

Hope this helps. Let us know if you have more questions.
