### ISSUE TITLE
[aws-ecs-patterns] ApplicationLoadBalancedFargateServiceProps : Use numeric literal union type

### ISSUE THREAD

**Issue by rcollette** [aws/aws-cdk#10168]
Provide better parameter validation by adding numeric literal union types to `cpu` and `memoryLimitMiB` properties.

### Use Case

In the IDE I want the ability to select known values.
I want to be able to apply the literal union type to my own configuration objects whose values are copied to construct properties, I don't want to have to keep documentation in sync with future changes.

### Proposed Solution

Create two exported types (don't take the type names literally here, I'm sure they need to be "designed")
```typescript
export type cpuType= 256|5121024|2048|4096|undefined;
// With a little help from Excel :)
export type memoryLimitMiBType = 512|1024|2048|3072|4096|5120|6144|7168|8192|9216|10240|11264|12288|13312|14336|15360|16384|17408|18432|19456|20480|21504|22528|23552|24576|25600|26624|27648|28672|29696|30720
```
Apply the types to the existing properties.

```typescript
readonly cpu?: cpuType;
readonly memoryLimitMiB?: memoryLimitMiBType;
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by Chriscbr** [comment]
I see how this could make the API a lot easier to use! However one caution I'd give is that we can't really use TypeScript union types in construct APIs because many of the other languages the CDK gets transpiled to do not support this feature (see the [design guidelines](https://github.com/aws/aws-cdk/blob/master/DESIGN_GUIDELINES.md#unions)).

One possible workaround might be to create a class with different static methods which acts like a union - but I'm not sure if this might just make the code more awkward to use.

**Comment by SoManyHs** [comment]
Hi @rcollette,

As mentioned, we don't support type unions but this is possible through a union-like class (see this example in the lambda module: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Code.html)

In your proposed solution, would you want to include a validation for valid cpu and memory combinations?

(Also noting that the proposed solution would be a breaking change).

**Comment by rcollette** [comment]
I suppose if there is no meta information that can drive the code generation for this then perhaps we should close the issue.   It would be a never ending battle trying to keep it up to date.
