### ISSUE TITLE
[stepfunctions-tasks] Cannot read property 'selectSubnets' of undefined

### ISSUE THREAD

**Issue by metgrahamr** [aws/aws-cdk#10282]
## :question: General Issue
I am importing an existing vpc using `Vpc.fromLookup` and would like to specify the private subnets to use when running an ECS Fargate Step Function task. However, I get the error `Cannot read property 'selectSubnets' of undefined` when I try to reference the imported vpc.

### The Question
I would like to define a cluster that uses FARGATE_SPOT by default and so have this;
```python
cluster = ecs.CfnCluster(
    self, 'cluster',
    capacity_providers=['FARGATE_SPOT'],
    default_capacity_provider_strategy=[
        {
            'capacityProvider': 'FARGATE_SPOT',
            'weight': 1,
            'base': 0
        }
    ]
)
```
I have an imported vpc;
```python
vpc = ec2.Vpc.from_lookup(self, 'vpc', vpc_name='Existing VPC')
```
I want to create a Fargate task in a Step Function;
```python
ecs_task = sfn_tasks.EcsRunTask(
    self, 'Run task',
    cluster=cluster,
    launch_target=sfn_tasks.EcsFargateLaunchTarget(
        platform_version=ecs.FargatePlatformVersion.LATEST
    ),
    integration_pattern=sfn.IntegrationPattern.RUN_JOB,
    task_definition=task,
    subnets=ec2.SubnetSelection(
        subnets=vpc.private_subnets
    )
)
```
How do I avoid the undefined error?

### Environment

  - **CDK CLI Version:** 1.62.0 (build 8c2d7fc)
  - **Module Version:** 1.62.0
  - **Node.js Version:** v10.20.1
  - **OS:** Ubuntu
  - **Language (Version):** Python (3.7.4)

### Other information
```
jsii.errors.JSIIError: Cannot read property 'selectSubnets' of undefined
```

**Comment by michaelwiles** [comment]
I'm under the impression that you have no control over the subnet when running tasks with fargate so don't think this is going to work in any case.

**Comment by metgrahamr** [comment]
> I'm under the impression that you have no control over the subnet when running tasks with fargate so don't think this is going to work in any case.

If I try to run a Fargate task through the ECS console then I have the option of choosing a VPC and selecting which subnets to run the task in. If I don't include `subnets` option in the above ` sfn_tasks.EcsRunTask` call then I get the same undefined error. It would seem strange to have the option but for it not to be used (unless I am not using correctly).
What I find a little strange is that if I use the `Cluster` construct rather than `CfnCluster` then I can specify a VPC.
I guess my actual question should be how do I define a cluster that uses Fargate spot by default and then have a stepfunction task that runs an ECS task in that cluster.

**Comment by metgrahamr** [comment]
It would be really helpful to have this issue resolved as, unless I am doing something wrong, it is not possible to use CDK directly to create a cluster that runs on Fargate Spot.

Looking a little into the code (which I am really not familiar with!), I'm wondering whether it is [this](https://github.com/aws/aws-cdk/blob/c908c7b1fbc904200102cc3d12000883f0c0ea26/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-task.ts#L296) part that is throwing the undefined error mentioned above. If you use the high-level `Cluster` construct then it has a vpc property, whereas the `CfnCluster` construct does not.

Is it possible to add a `vpc` property to `CfnCluster` (or would it then not match [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html)) or could the `EcsRunTask` construct have a `vpc` property?

**Comment by shivlaks** [comment]
hey @metgrahamr - I'll need to go through the repro steps so I can go digging.

Aside: I'm curious why you're not using the L2 construct for [`ecs.Cluster`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html). Is there a capability or property that's not available through the higher level construct that needs dropping down to the `CfnCluster` resource?

**Comment by metgrahamr** [comment]
> Aside: I'm curious why you're not using the L2 construct for [`ecs.Cluster`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html). Is there a capability or property that's not available through the higher level construct that needs dropping down to the `CfnCluster` resource?

I would like to set the default cluster provider to be Fargate Spot but I cannot see how to do that using `Cluster` - happy to be enlightened!

**Comment by shivlaks** [comment]
@metgrahamr good to know, I haven't touched this area too much myself, but I'll start with triaging your issue first and then get to that :)

**Comment by shamelesscookie** [comment]
I think this is a problem where CDK doesn't really know about the details of VPCs imported via `vpc.from_lookup` until you populate them into the context. So basically, if you `cdk context --clear`, your script will fail on first run because the context has no subnets to select from during synthesis of the `ec2.SubnetSelection` method.

I ran into this issue as well (although with a slightly different use case).

My solution was to create a dummy stack whose only content is the `vpc.from_lookup` call. I then `cdk synth` this dummy stack (and only the dummy stack, so comment out the stack that is broken.).  This will populate the context with your VPC so that future attempts to lookup subnets do not fail.  You don't need to deploy the dummy stack, just synthesize it and then delete it or comment it out. Hacky, I know, but it solved my problem.

**Comment by PierreKiwi** [comment]
The problem is similar for `EcsTask` (one of the CW Events targets) -> cf. [here](https://github.com/aws/aws-cdk/blob/98ab29206903a235331a9a0b4b38a5e6ad6d89dc/packages/%40aws-cdk/aws-events-targets/lib/ecs-task.ts#L170).

The workaround is to create the CfnCluster in a separate stack and to do a lookup using `from_cluster_attributes` (where you specify the VPC via a `vpc` parameter). Then you have a Cluster object compatible with `EcsRunTask` (or `EcsTask` in my case).

But by specifying the SubnetSelection, the construct should be able to resolve the associated `vpc` if not resolvable via the `cluster` parameter.

**Comment by peterwoodworth** [comment]
> I would like to set the default cluster provider to be Fargate Spot but I cannot see how to do that using `Cluster` - happy to be enlightened!

Unfortunately, this currently isn't possible, open up a feature request if you'd like to see this! https://github.com/aws/aws-cdk/blob/c647e389bd279b34e91110c9418885fe904739c3/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L1106-L1110

Aside from that, Shamelesscookie's response gave appropriate guidance here, thank you!
