### ISSUE TITLE
[aws-eks] CfnFargateProfile is missing within the eks library for the resource AWS::EKS::FargateProfile

### ISSUE THREAD

**Issue by com-tr-sitzman-lyle** [aws/aws-cdk#10368]
A low level construct for "AWS::EKS::FargateProfile" appears to be missing
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-fargateprofile.html

### Reproduction Steps

Try to construct CfnFargateProfile or look in the eks-1.63.0.jar and see it is missing.

### What did you expect to happen?

As per https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_lib I would expect CfnFargateProfile to exist, due to "CFN Resources are periodically generated from the AWS CloudFormation Resource Specification"

### What actually happened?

There is no CfnFargateProfile

### Environment

  - **Framework Version:** 1.63.0
  - **Language (Version):** Java

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @com-tr-sitzman-lyle 

The [`AWS::EKS::FargateProfile`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-fargateprofile.html) resource was added to CDK just recently in this [PR](https://github.com/aws/aws-cdk/pull/10385). The `CfnFargateProfile` construct will be available in the next release.

Note however that we already have an L2 for a [`FargateProfile`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.FargateProfile.html) that is implemented with a custom resource under the hood.

If there are some capabilities of `CfnFargateProfile` that are missing from the L2 you can create a feature request.
I've also created this [issue](https://github.com/aws/aws-cdk/issues/10427) to consider using `CfnFargateProfile` instead of the custom resource.

Thanks
