### ISSUE TITLE
[gitpod] Cant do full build in Gitpod

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#10375]
Gitpod can't do a complete `yarn build` of the CDK. It appears Docker is not set up correctly.

### Reproduction Steps

1. Launch Gitpod from this repo https://gitpod.io/#https://github.com/aws/aws-cdk
2. `yarn build`

### What did you expect to happen?

Full build of the CDK.

### What actually happened?

Numerous log lines, then failure with the following message.

```
Checking if docker is running... Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Yes, it's a know Gitpod limitation: https://github.com/gitpod-io/gitpod/issues/52 .

You need to pass the `--skip-prereqs` switch to `yarn build`, like it's done [here](https://github.com/aws/aws-cdk/blob/25256d09aa39b11f49bcb0479fbe2ec2bc1e145d/.gitpod.yml#L3-L3).

But also, don't do a full build in Gitpod, it's a waste of time 😉. Everything should be built already when you open a new workspace. If you ned to update things because a long time has passed in your workspace, just create a new one 🙂. If you _really_ need to update things, do a partial build: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#partial-build .

Hope this is enough info! Let me know if you need anything else for this issue.

Thanks,
Adam

**Comment by Jerry-AWS** [comment]
I'll update the Contributing doc to reflect the new state of things.
