### ISSUE TITLE
[pipelines] Separating pipeline and application code

### ISSUE THREAD

**Issue by lindakung** [aws/aws-cdk#10395]
## :question: General Issue

Any suggestion on how we can separate pipeline code from application code, particularly in different repos? I currently have a pipeline stack, stage and application stack (lambdas, apigateway etc) all in one repo but would love to know if there's a good practice for separating that code. 

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language (Version):** Python (3.7.3)

**Comment by rix0rrr** [comment]
We are trying to do the opposite, bringing the application and pipeline code together.

If you want to separate it out, you can create 2 CDK applications, one for the application and one for the pipeline. If you want to use CDK Pipelines, you will have to import your application definition (as a library) into the pipeline definition.

Otherwise, you can use the underlying AWS CodePipeline primitives.
