### ISSUE TITLE
[ec2] increase cloudformation init timeout for windows machine

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#10429]
## :question: General Issue

Windows based EC2 instances, take longer to spin up in general. The current timeout in the cloudformation init is set to 5 min by default.

### The Question

Can we increase the timeout for cloudformation init on EC2 instances if the EC2 instance is using a windows AMI?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by rix0rrr** [comment]
Please read this: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#configuring-instances-using-cloudformation-init-cfn-init

**Comment by abelmokadem** [comment]
I have read that, but it took me some time to get to that page. It was not the first thing that came to my mind when my deployment was failing. I'm trying to suggest something to make CDK a bit more developer-friendly. A warning could also have been helpful. If you don't agree just close the issue.

**Comment by NGL321** [comment]
Hey @abelmokadem,

Sorry it was problematic to find information on the timeout. The default is unfortunately shared between all instance types, so it doesn't make sense to just change it because it doesn't work with Windows.

That said, if you have suggestions on how this could be made more clear in docs so we can avoid this kind of unnecessary frustration moving forward, we would love to hear them!

Thank you for reporting this, please let us know if you find anything else!

😸 😷

**Comment by abelmokadem** [comment]
@NGL321 thanks. Maybe this is just an issue if you haven't worked with CloudFormation init for a while 🤔  I think a warning would be nice in case of a failure, but to be honest I also think that would just mess up the cdk cli output logs. Let's just close this.
