### ISSUE TITLE
[aws-eks] Upgrading CDK to 1.62.0 Changes Trusted Entities 

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#10564]
I'm not sure if  it's a bug or feature (I couldn't find any information on the web). Upgrading CDK from 1.61.1 to 1.62.0 will change the `AssumeRolePolicyDocument` property of `CreationRole`:
```
┌───┬─────────────────────────────────────────────────────────────────────────────┬────────┬────────────────┬─────────────────────────────────────────────────────────────────────────────┬───────────┐
│   │ Resource                                                                    │ Effect │ Action         │ Principal                                                                   │ Condition │
├───┼─────────────────────────────────────────────────────────────────────────────┼────────┼────────────────┼─────────────────────────────────────────────────────────────────────────────┼───────────┤
│ - │ ${EksCluster/Resource/CreationRole.Arn}                                     │ Allow  │ sts:AssumeRole │ AWS:${@aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-e │           │
│   │                                                                             │        │                │ ks.ClusterResourceProvider.NestedStackResource.Outputs.ProdInfraClusterawsc │           │
│   │                                                                             │        │                │ dkawseksClusterResourceProviderIsCompleteHandlerServiceRole9480182BArn}     │           │
│   │                                                                             │        │                │ AWS:${@aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-e │           │
│   │                                                                             │        │                │ ks.ClusterResourceProvider.NestedStackResource.Outputs.ProdInfraClusterawsc │           │
│   │                                                                             │        │                │ dkawseksClusterResourceProviderOnEventHandlerServiceRole0B5D6944Arn}        │           │
│ - │ ${EksCluster/Resource/CreationRole.Arn}                                     │ Allow  │ sts:AssumeRole │ AWS:${@aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.Kubec │           │
│   │                                                                             │        │                │ tlProvider.NestedStackResource.Outputs.ProdInfraClusterawscdkawseksKubectlP │           │
│   │                                                                             │        │                │ roviderHandlerServiceRole4E00F050Arn}                                       │           │
├───┼─────────────────────────────────────────────────────────────────────────────┼────────┼────────────────┼─────────────────────────────────────────────────────────────────────────────┼───────────┤
│ + │ ${EksCluster/Resource/CreationRole.Arn}                                     │ Allow  │ sts:AssumeRole │ AWS:arn:${AWS::Partition}:iam::123456789012:root                            │           │
└───┴─────────────────────────────────────────────────────────────────────────────┴────────┴────────────────┴─────────────────────────────────────────────────────────────────────────────┴───────────┘
```
Is this expected? Thanks.

### Environment

  - **CLI Version      :** aws-cli/2.0.24 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev28
  - **Framework Version:** 1.62.0
  - **Node.js Version:** v14.5.0
  - **OS               :** Mac OS X 10.15.6
  - **Language (Version):** typescript ~3.7.2

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @akefirad - Yes, this change was intentional.

At cluster creation, the `CreationRole` is later also used as the `kubectlRole` of the cluster:

https://github.com/aws/aws-cdk/blob/07d14aeb6a18e61be19047442e2058e2c7e5578a/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L952-L954

In version `1.62.0` we introduced the capability of applying manifests on existing clusters, this required us to expose `kubectlRole` as a configuration option when importing clusters. The `KubectlProvider` needs to be able to assume this role, but since the provider handler role is created dynamically, its ARN is not known beforehand, therefore the `kubectlRole` can no longer explicitly declare which roles can assume it. Instead, we reversed the permission direction, requiring the `kubectlRole` be assumable from any role with permissions to assume it. (i.e `AccountRootPrincipal`)

This allowed us to add a policy to the `KubectlProvider` that grants it permission to assume the `kubectlRole`, without having to mutate an externally provided role. 

https://github.com/aws/aws-cdk/blob/07d14aeb6a18e61be19047442e2058e2c7e5578a/packages/%40aws-cdk/aws-eks/lib/kubectl-provider.ts#L89-L90

Specifically, at cluster creation time, the `kubectlRole` isn't provided in the configuration, but we decided to align it with the "imported" cluster scenario, simplifying the permission direction and dependencies.
