### ISSUE TITLE
[aws-codepipelines-actions] BitBucketSourceAction missing OutputArtifactFormat property

### ISSUE THREAD

**Issue by denisdifazio** [aws/aws-cdk#10629]
I have a CodePipeline created with AWS CDK that retrieves the source code from a Bitbucket repository. I noticed it stopped working recently and it gets stuck on the "Source" stage at the status "In Progress". After doing some research I noticed it is missing the property OutputArtifactFormat:

![image](https://user-images.githubusercontent.com/11673757/94816653-7d971180-03d2-11eb-9f92-462c87fe6e99.png)

If I go to AWS Console, click `Edit stage` on "Source" stage, open the edit form and press `Done` without changing any information, the OutputArtifactFormat appears:

![image](https://user-images.githubusercontent.com/11673757/94817216-2c3b5200-03d3-11eb-824b-5f6b1a8a093d.png)

### What did you expect to happen?

Pipeline should work

### What actually happened?

Pipeline get stuck on "In Progress" status

### Environment

  - **Framework Version:** 1.64.1
  - **Node.js Version:**  12
  - **OS               :** Windows 10
  - **Language (Version):**  Typescript 4

**Comment by skinny85** [comment]
Hey @denisdifazio ,

thanks for reporting the issue. I just tried it, and it works fine for a CodePipeline I just created.

In the CodePipeline documentation for CodeStar conenctions: https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodestarConnectionSource.html , it pretty clearly says that field is optional, and `CODE_ZIP` is the default.

If the problem persists, I would suggest opening an issue through support to the CodePipeline team, to see what could be the root cause of the problems.

Thanks,
Adam
