### ISSUE TITLE
[apigateway] race condition between Stage and CfnAccount 

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#10722]
_Originally reported by @jcrugzz @ #10377_

Stages in RestApi can be configured to have logs enabled.
These logs are sent to CloudWatch Logs using the IAM role
configured in `AWS::ApiGateway::Account` (via `CfnAccount`
construct). When this IAM role is not configured on the
account, stage creation will fail.

Since there is no implicit dependency between the `Stage`
construct and `CfnAccount` construct, CloudFormation may
deploy this in the wrong order and fail the deployment.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Fix in progress https://github.com/aws/aws-cdk/pull/10377

**Comment by rantoniuk** [comment]
Simple replication use case:
```
    const apiGateway = new RestApi(this, 'apigw', {
      endpointConfiguration: {
        types: [EndpointType.REGIONAL]
      },
      apiKeySourceType: ApiKeySourceType.HEADER,
      deployOptions: {
        loggingLevel: MethodLoggingLevel.INFO,
        metricsEnabled: true
      }
    });
```

By default the above will not work and will yield `"CloudWatch Logs role ARN must be set in account settings to enable logging (Service: ApiGateway, Status Code: 400`.

However, if you 1) comment out the `deployOptions` section, then 2) deploy, and then 3) re-add it, and 4) deploy again, it will work fine - because the cloudwatch logs role will have been autocreated during 2).

**Comment by OGoodness** [comment]
https://github.com/aws/aws-cdk/issues/10878
