### ISSUE TITLE
[custom-resources] (design) Custom resource to poll an API

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#10832]
There are things I'd like to do in CDK that go as follows:

- Make API call to initiate something
- Wait until that thing is done, polling a Describe* api to check for status
- Return details one status is done

One example is a construct that builds python lambda layers and publishes them for me:
- Create project with buildspec that installs packages to the layer (package names/versions are a parameter)
- Whenever those packages are updated in the CDK code, the custom resource would update
  - Start a new build using the buildspec, to install all the packages (minus removed/plus added packages)
  - Monitor build status
  - Return failure if the build fails, or the build details if they succeeded
- Make the layer from the artifacts

However this relies on making periodic codebuild:ListBuildsForProject api calls to check that the build is done, before the layer actually gets used. Right now there is no way I know of to do that without writing a totally custom resource.

### The Question
Is a construct like this (say, `AwsSdkPoll`) something that could be added to CDK? Any concerns about usefulness or it being to brittle?

### Environment

  - **CDK CLI Version:** all
  - **Module Version:** all
  - **Node.js Version:** all
  - **OS:** all
  - **Language (Version):** all

### Other information
The construct should be general-purpose, working with many API calls. I could foresee this being used to monitor the status of an item in dynamodb, or the existence of a file in S3.

**Comment by rix0rrr** [comment]
There is a custom resource provider framework (somewhere) that's been built by Elad to do exactly this.

Does that not meet your needs?

**Comment by flemjame-at-amazon** [comment]
This seems like the sort of thing that should go into the core CDK library. It's AwsCustomResource, but for asynchronous calls.

I understand the desire to keep complexity down. Do you know offhand what too much complexity might look like?

**Comment by rix0rrr** [comment]
I'd rather not add too many custom-resource based things to core (although that ship has sailed, somewhat).

Although I think something like a `poller` or `stabilizer` (or whatever the correct term is) could be added to `AwsCustomResource` at not too much cost. What do you reckon? Where should this live?

**Comment by jogold** [comment]
Can we maybe reopen #7979 for this? It's general enough (?) to be included the CDK and allows to easily (?) build more complex custom resources for long polling operations.

Will be even easier if we have a `AwsApi` task in `aws-stepfunctions-tasks` like we have a `AwsApi` target in `aws-events-targets`.

**Comment by rix0rrr** [comment]
I would feel very uneasy bringing SFN into this.

But I see your point, the wait duration may exceed the timeout of a single Lambda in which case we can't implement it in AwsCustomResource after all.

An alternative is a layer on top of Elad's custom-resource-with-waiter provider framework, to add AwsCustomResource-like capabilities there.

**Comment by jogold** [comment]
> I would feel very uneasy bringing SFN into this as a core dependency.

It doesn't bring SFN as a core dependency in `@aws-cdk/custom-resources` since everything is written using `CfnResource`s to avoid this problem. The same way it's done for the custom-resource-with-waiter provider framework (which indeed already uses SFN without bringing it as a dependency).

It can been seen as an alternative framework for long polling operations. You have Elad's framework but it only works with Lambda functions. This one provides a more general approach the main use case I had when I implemented it was to be able to launch Fargate tasks in a custom resource in order to do database operations.

**Comment by flemjame-at-amazon** [comment]
With a Lambda function the timeout would be 15 minutes. Arbitrarily that seems like a reasonable amount of time for any AWS resource to be created, unless the user is doing something like starting an ETL job or a big code build.

**Comment by rix0rrr** [comment]
Closing this as the discussion seems to have stalled.

**Comment by Rizxcviii** [comment]
Hi, is this still being looked into? We have the same issue at the moment as well. We're using a custom resource using the Provider framework, but it seems to be a bit too much boiler plate for a simple API call, is there a suggestion to possibly reuse the `WaiterStateMachine` here, but instead of requiring `isCompleteHandler`, instead a `CallAwsService` from sfn-tasks?
