### ISSUE TITLE
[aws-ecs] On MacOS the fromImage filled the trash with content recursively and lock those files in Trash

### ISSUE THREAD

**Issue by olivier-schmitt** [aws/aws-cdk#10858]
I tried to use aws_ecs.ContainerImage.from_asset('..') function to build a Docker image and to use it in a Fargate cluster.

At first, I failed to use this because the path was not correct and I had errors about paths and names being too long.

I fixed the path and went on.

Later on when I tried to empty the trash of my MacOS, I noticed I was not able to do so.

I found out that cdk assets were in the trash and I was not able to delete them.
I tried to remove all docker images related to the CDK and I noticed that the files in Trash seem to be a recursive tree:

![image](https://user-images.githubusercontent.com/524039/95950365-b08acd80-0df4-11eb-9ee5-1b9c26179c2b.png)

### Reproduction Steps

Probably by using a bad path in fromImage function.

### What did you expect to happen?

Not to have such problem with the trash.

### What actually happened?

- the trash says the files are used and I'm not able to delete them using the vairous UI techniques
- recursive tree of files which does not exists in my codebase

### Environment

  - **CLI Version :** (node:906) ExperimentalWarning: The fs.promises API is experimental
1.67.0 (build 2b4dd71)
  - **Framework Version:**
  - **Node.js Version:** v10.16.3 
  - **OS               :** MacOs 10.15.7
  - **Language (Version):** Python 3.8
### Other

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
hey @olivier-schmitt, when using `fromAsset` it's best to use `path.resolve(__dirname, ...)` when pointing to a file relative to your cdk source. Otherwise the path will be relative to the working directory where synth was run from. You may have discovered this already.

This occurs when you point to a Dockerfile that is in a directory that is a parent of the CDK app. There is a ticket for this [here](https://github.com/aws/aws-cdk/issues/3899). I'm gonna close in favor of that one.

I reproduced and was able to remove the generated output by running `rm -r cdk.out`.
