### ISSUE TITLE
cli compatibility: read 'region' from credentials file

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1087]
Right now we only read `region` from `~/.aws/config`. Some people have configured their region in `~/.aws/credentials`, which apparently the AWS CLI accepts. However, in CDK the following happens:

```
Error: Need to perform AWS calls for account unknown-account, but no credentials found. Tried: default credentials.
```

Because just before that the following happens:

```
Setting "aws:cdk:toolkit:default-region" context to undefined
Resolving default credentials
Unable to determine the default AWS account (did you configure "aws configure"?): { AccessDenied: Access denied
```

We might want to improve compatibility here. Better yet, kick this up to the JS SDK.

**Comment by Doug-AWS** [comment]
We should not read region (or output format) from ~/.aws/credentials. The AWS CLI docs, https://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html, state:

"In order to separate credentials from less sensitive options, region and output format are stored in a separate file named config in the same folder."

It then goes on to say:

"The AWS CLI will also read credentials from the config file. If you want to keep all of your profile settings in a single file, you can. If there are ever credentials in both locations for a profile (say you used aws configure to update the profile's keys), the keys in the credentials file will take precedence.

If you use one of the SDKs in addition to the AWS CLI, you may notice additional warnings if credentials are not stored in their own file."

I got a Chime message from the JS SDK folks yesterday. They are working on changes to the credentials chain, which may impact where you get a default region.
