### ISSUE TITLE
[aws-ecs] Default Task ExecutionRole not set to the Task Role as stated in Documentation

### ISSUE THREAD

**Issue by gandroz** [aws/aws-cdk#10962]
As stated in the AWS-ECS [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-task-definition.html) related to the Task Definitions (creating a task definition of EC2 launch type), 

> For Task execution role, choose an IAM role that provides permissions for containers in your task to make calls to AWS APIs on your behalf. For tasks that use the EC2 launch type, these permissions are usually granted by the Amazon ECS Container Instance IAM role, which is specified earlier as the Task Role. There is no need to specify a task execution role

However, when instantiating a task definition with sample code

```
const taskDefinition = new ecs.Ec2TaskDefinition(this, `MyTaskDef`, {
            networkMode: ecs.NetworkMode.AWS_VPC,
            taskRole: props.MyTaskRole
        });
```

the task execution role is set to a generic default one, the construct does not take the role of the task role.

--- 

This is :bug: Bug Report

**Comment by dizzler** [comment]
This 🐛  needs ❤️ 
This is a pretty glaring issue. Human babies have been conceived, grown and delivered since this bug was reported...

As a workaround, you can:

1. create the Ec2TaskDefinition
2. use the obtain_execution_role() method to get the IRole
3. use the "grant_principal" attribute of the IRole to grant additional permissions to the task execution role

Something like an example in python:
`...
taskDefinition = ecs.Ec2TaskDefinition(this, "id",
   ...  ## don't set task/exec role here
)
exec_role = taskDefinition.obtain_execution_role()
some_asset.grant_read(exec_role.grant_principal)`

**Comment by MrArnoldPalmer** [comment]
So taskRole is correctly referencing the prop as far as I can tell, and passing it to the underlying taskDefinition. 

Relevant code: [here](https://github.com/aws/aws-cdk/blob/v2.62.1/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L434) and [here](https://github.com/aws/aws-cdk/blob/v2.62.1/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L458)

Are you thinking of the execution role?

Closing this but reopen if I'm missing something here.
