### ISSUE TITLE
[cli] Caller should be able to override created changeset name

### ISSUE THREAD

**Issue by muja** [aws/aws-cdk#11075]
When invoking `cdk deploy` with the `--no-execute` flag, CDK will create a changeset whose name is completely random. Usually this might be okay, but in automated environments this is unacceptable. As such, it should be possible to provide a name which CDK will use when creating a changeset (e.g. using a `--change-set-name <string>` flag).

### Use Case

Our CI/CD environment runs on top of CodePipeline in combination with CodeBuild (and very extensive use of CDK). Naturally, our initial approach was to simply do a `cdk deploy` inside our CodeBuild containers. However, the stack creation/update itself often takes several minutes with the computing instance just waiting for the stack create to finish. This is not very cost-efficient.
So, to save resources and costs, the CodeBuild containers should not execute the changeset, only create it so that CodePipeline's [CloudFormationExecuteChangeSetAction](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codepipeline_actions/CloudFormationExecuteChangeSetAction.html) can take over. However, this specific deploy action needs the changeset name which must be known at create time (the [Fn::GetParam](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-parameter-override-functions.html#w2ab1c21c20b9) function unfortunately only works for `TemplateOverrides`, tried that already).

### Proposed Solution

I believe the solution is simple: the CLI should accept a `--change-set-name <string>` option, and pass this optional parameter to the [deployStack](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/deploy-stack.ts#L233) function. This one should use the parameter, if provided, or fallback to the existing `uuid.v4()` method. This can also be used in combination with `--execute`, but there it will be significantly less interesting.

### Other

For our use case... we tried going with `cdk synth` and `CreateStackAction` shenanigans, but this leads to many more problems:
- we have lots of assets which will not get uploaded in `cdk synth`, so we'd have to do it all manually or introduce the [cdk-assets](https://github.com/aws/aws-cdk/tree/master/packages/cdk-assets) package.
- CodePipeline uses some other role for the stack than CDK (which is hard to override without diving into CDK internals) and since we have KMS encrypted S3 buckets, this approach led to many hard-to-debug S3 API errors.
- you cannot provide `NotificationArns` with this approach which are also used by us

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
We could add this. Out of curiosity: have you considered using [CDK Pipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html)?

**Comment by markus7811** [comment]
I would like to see this feature. I want to continue using gitlabci and don't want to switch :-)

**Comment by swar8080** [comment]
The CDK automatically deletes empty change sets, so I'm wondering if an additional flag is needed to retain empty change sets. Otherwise, use cases for externally executing the change set would need to check for its existence before executing to avoid errors.

For @muja's case with the CodePipeline Cloudformation action, the action fails if the change set with the provided name doesn't exist. I'm not very familiar with Codepipeline, but didn't see a straight-forward way to conditionally skip that Cloudformation action. The action is successful when the change set is empty, so retaining it would solve the problem.

**Comment by Wenzil** [comment]
I believe this issue was closed because the use case is taken care of by https://github.com/aws/aws-cdk/pull/12683. 

However the  proposed solution solves at least one other use case (described in https://github.com/aws/aws-cdk/pull/12683#issuecomment-778465771). I would like to suggest reopening this issue until the proposed solution is implemented. See PR https://github.com/aws/aws-cdk/pull/13024
