### ISSUE TITLE
[CodeArtifact] add L2 

### ISSUE THREAD

**Issue by jstandish** [aws/aws-cdk#11090]
Better ergonomics for using `CodeArtifact`

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jstandish** [comment]
PR is ready for review

**Comment by jstandish** [comment]
PR is ready for review with updated changes.

**Comment by straygar** [comment]
Hey! What's the state of this issue? :)

**Comment by just-boris** [comment]
The request is still relevant, can this be reopened?

**Comment by jlosito** [comment]
@SomayaB can this issue be re-opened? I'm currently in need of an L2 construct for CodeArtifactory. There still isn't an L2 construct since this issue was originally raised.

My scenario is I have an existing CodeArtifactory repository which already is provisioned in the account. I need to configure an upstream on the repository, but the L1 construct is lacking. Typically, L2 constructs have a method named along the lines of `fromArn` which I'm looking for as well as a `addUpstream` method that I'm looking for.

**Comment by hoegertn** [comment]
I am working on L2 and L3 for CodeArtifact for the https://github.com/open-constructs/aws-cdk-library

Let me know if you have any special requirements or design ideas.
