### ISSUE TITLE
[@aws-cdk/pipelines] - Can't get the Commit SHA

### ISSUE THREAD

**Issue by arpowers** [aws/aws-cdk#11178]
When using `GitHubSourceAction` we should be able to get the "sha" of the commit that triggered the action. The TypeScript shows that it should be available under `variables.commitId`. 

However, in my pipeline, it's just giving me a template variable (or something like that): `#{Source_GitHub_NS.CommitId}`

### Reproduction Steps

The code looks like this: 

```ts
const sourceAction = new cpa.GitHubSourceAction({
      actionName: "GitHub",
      output: sourceArtifact,
      oauthToken: cdk.SecretValue.secretsManager("github-repo-token"),
      owner: "github-username",
      repo: "the-repo",
      branch: "dev",
    })

    const sha = sourceAction.variables.commitId // returns #{Source_GitHub_NS.CommitId}
```

How can we get the actual SHA in this scenario? 

--- 

This is :bug: Bug Report

**Comment by gisleyt-fremtind** [comment]
I have the same issue. Have tried both CDK version 1.69 and 1.71.

**Comment by skinny85** [comment]
Hey @arpowers ,

thanks for opening the issue. The commit is only available during Pipeline execution, as it changes each time you push something to your repository. That's why it's available as this ` #{Source_GitHub_NS.CommitId}` expression. You can pass it to a different thing in your pipeline - for example, the environment variables of your CodeBuild Project:

```ts
new CodeBuildAction({
  // ...
  environmentVariables: {
    COMMIT_ID: sourceAction.variables.commitId,
  },
});
```

And then read the `COMMIT_ID` environment variable when executing the build.

Hope this clears this up!

Thanks,
Adam

**Comment by arpowers** [comment]
Ah makes sense. However, the issue in that case is that there is no way to add `environmentalVariables` to `SimpleSynthAction` command. Here is how I'm using the sha: 

<img width="640" alt="Screen Shot 2020-11-02 at 12 50 39 PM" src="https://user-images.githubusercontent.com/308134/97917951-26a29600-1d0a-11eb-9967-abdaf69d6c76.png">

**Comment by arpowers** [comment]
Ah! Didn't realize we could pass in environment variables to the `SimpleSynthAction` command. Thanks!

**Comment by mh-love** [comment]
@skinny85 

Not sure if I should open up a ticket, but I'm noticing that if I'm using a CdkPipeline with a ShellScriptAction, I am not able to get the commit id as it comes through as `#{Source_GitHub_NS.CommitId}`:

```
stage.addActions(new ShellScriptAction({
     actionName: 'PullRequest',
     additionalArtifacts: [sourceArtifact],
     commands: [`cd $CODEBUILD_SRC_DIR && make commit_id=${sourceAction.variables.commitId} pr`]
}));
```

**Comment by skinny85** [comment]
@mh-love that's just a peculiarity of how CodePipeline Variables work. You can only use them in a few places, and `commands` is unfortunately not one of them. You can pass the `sourceAction.variables.commitId` expression as an environment variable to `environment` in `ShellScriptAction`:

```ts
stage.addActions(new ShellScriptAction({
     actionName: 'PullRequest',
     additionalArtifacts: [sourceArtifact],
     environment: {
       COMMIT_ID: { value: sourceAction.variables.commitId },
     },
     commands: ['cd $CODEBUILD_SRC_DIR && make commit_id=$COMMIT_ID pr'],
}));
```

(BTW, you're in `$CODEBUILD_SRC_DIR` by default, no need to `cd` into it)

**Comment by mh-love** [comment]
@skinny85 I'm seeing conflicting info with 1.82.0 version. 

1) For a ShellScriptAction, `environment` seems to allude to the environment, not environment variables, and that doesn't compile! 

     `Type '{ COMMIT_ID: { value: string; }; }' is not assignable to type 'BuildEnvironment'.`

2) In my CdkPipeline, passing the variable below still shows `commit_id` as `#{Source_GitHub_NS.CommitId}`:

```
const pipeline = new CdkPipeline(this, 'FXSCdkPipeline', {
      pipelineName: this.node.tryGetContext('pipeline_stack_name'),
      cloudAssemblyArtifact,
      sourceAction,
      synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        environmentVariables: {
          commit_id: { value: sourceAction.variables.commitId }
        },
        installCommand: 'make install',
        buildCommand: 'make tests',
        synthCommand: 'make deploy'
      })
    });
    ```

**Comment by skinny85** [comment]
1. Yes, you're right. `environmentVariables` is a property of `environment`, I've updated my code.
2. Of course it is that in your template! That's because the commit ID depends on a particular execution of the pipeline. At runtime (like in one of the `*Command` properties), accessing `$commit_id` will resolve to the current ID of the commit flowing through the Pipeline.

**Comment by mh-love** [comment]
@skinny85 Ah! I am beginning to see the light. Thank you!

**Comment by mh-love** [comment]
@skinny85 

Ok, so I've tested this a few different ways, and in a `ShellScriptAction` I do not see the `COMMIT_ID` come through at runtime if I `printenv`, **but** I do see it at runtime in the *Command properties scripts. Is this a bug?

```
stage.addActions(new ShellScriptAction({
     actionName: 'PullRequest',
     additionalArtifacts: [sourceArtifact],
     environment: {
       environmentVariables: {
         COMMIT_ID: { value: sourceAction.variables.commitId }
       },
     },
     commands: ['printenv'],
}));
```

In the CodeBuild logs this looks like: `COMMIT_ID=#{Source_GitHub_NS.CommitId}`

**Comment by arpowers** [comment]
Same here! didn't work for me

**Comment by skinny85** [comment]
OK. I know what is happening here 🙂.

There are two ways of setting the environment variables of a CodeBuild action in a CodePipeline:

1. You can set the variables when creating the Project itself.
2. You can set the variables when creating the `CodeBuildAction`.

Now, the problem is that CodePipeline Variables **only work with option 2**.

And so that's why `ShellScriptAction` doesn't work with CodePipeline Variables: [because it passes the `environment` (where the env variables for a Project are defined) to the Project constructor](https://github.com/aws/aws-cdk/blob/6d9a0f1ea0c05e7902ccca4d0fc4040e688846e5/packages/%40aws-cdk/pipelines/lib/validation/shell-script-action.ts#L187). And the [`SimpleSynthAction` does the same](https://github.com/aws/aws-cdk/blob/6d9a0f1ea0c05e7902ccca4d0fc4040e688846e5/packages/%40aws-cdk/pipelines/lib/synths/simple-synth-action.ts#L333).

Let's re-open this ticket, and use it to track fixing this in CDK Pipelines.
