### ISSUE TITLE
[aws-eks] The controllplane securitygroup of the cluster should be accessible outside the eks cluster construct

### ISSUE THREAD

**Issue by markussiebert** [aws/aws-cdk#11233]
### Use Case

I am using custom networking with eks. For this, i have to allow access from the pod securitygroup to the controllplane securitygroup. Because i have to apply some manifests and patches too, i have to pass the eks cluster to my CustomNetworking cunstruct. Because i cannot access the securitygroup of the controllplane via the cluster construct, i have to create a new securitygroup for the controllplane (the same way the cluster construct would create it) and pass it to my CustomNetworking construct too.

Both steps, passing it separately and creating the securitygroup is unnecessary.

In addition: It is not possible to change se controllplane securitygroup after you created the cluster. So you have to recreate it to use your own securitygroup. Only because i want to add an ingress to the controllplane securitygroup.

### Proposed Solution

change the following code

https://github.com/aws/aws-cdk/blob/55e6130503d2e7346eec81d01ef37098708d0196/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L885

```
const securityGroup = props.securityGroup || new ec2.SecurityGroup(this, 'ControlPlaneSecurityGroup', {
   vpc: this.vpc,
   description: 'EKS Control Plane Security Group',
});
```

to

```
public abstract readonly controllPlaneSecurityGroup?: ec2.ISecurityGroup;
...

this.controllPlaneSecurityGroup = props.securityGroup || new ec2.SecurityGroup(this, 'ControlPlaneSecurityGroup', {
   vpc: this.vpc,
   description: 'EKS Control Plane Security Group',
});

...

resourcesVpcConfig: {
        securityGroupIds: [this.controllPlaneSecurityGroup.securityGroupId],
        subnetIds,
      },

i think there are no more references 
```

### Other
I don't think this will cause any problems and think i would be able to implement this 

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@markus7811 

As a workaround, you can access the security group via the connections property:

```ts
const controlPlaneSecurityGroup = cluster.connections.securityGroups.filter(s => s.node.id === 'ControlPlaneSecurityGroup')[0];
```

You can also just create the security group once from the outside, and pass it to both the `CustomNetworking` and the `Cluster` construct.

Also, are you sure you need access specifically the control plane security group and not the [cluster security group](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html#cluster-sg)?

You can use 

```
const clusterSecurityGroup = ec2.SecurityGroup.fromSecurityGroupId(this, 'ClusterSecurityGroup', cluster.clusterSecurityGroupId);
```

Adding rules to this group will apply to the control plane as well as the nodes.

**Comment by iliapolo** [comment]
Marking as `needs-discussion` since we might want to deprecate this property in favor of passing an array of `additionalSecurityGroups`.

**Comment by markus7811** [comment]
Ok, maybe I misunderstood some things ...

I create private cluster: 

```endpointAccess: eks.EndpointAccess.PRIVATE,```

that creates cluster i cannot access from the outside, because i looked up the endpoint adress the cdk output told me end ended up with network interfaces with the cluster securitygorup assigned. I had to open Port 443 for my "Client"-CIDR.

I only want this ingress applied to the controlplane network interfaces, not the nodegroup nodes.

**Comment by iliapolo** [comment]
@markus7811 You are correct in your analysis. The reason I say we might deprecate this property is because we'd like to support passing an array of control plane security groups. Just like the [SDK offers](https://docs.aws.amazon.com/eks/latest/APIReference/API_VpcConfigRequest.html#AmazonEKS-Type-VpcConfigRequest-securityGroupIds). 

Once this array is introduced, it would be confusing to have both a single security group and an array of security groups as inputs.

So combining your suggestion, i think maybe `controlPlaneSecurityGroups` will be the most clear and flexible. 

> I think there should be an option adding ingress rules to the controlplane - apart from using workarounds...

So the way to configure ingress for the control plane would be by simply passing in your desired security groups.

```ts
new eks.Cluster(this, 'Cluster', {
  ...,
  controlPlaneSecurityGroups: [...]
})
```

And this is equivalent to the situation today where you would need to pass in the single security group:

```ts
const controlPlaneSecurityGroup = new ec2.SecurityGroup(...)
// do whatever you need with this sg

new eks.Cluster(this, 'Cluster', {
  ...,
  securityGroup: controlPlaneSecurityGroup
})
```

Are there any capabilities that the default control plane security group offers that you'd like to re-use?

**Comment by markus7811** [comment]
I think your suggested solution with array of securitygroups is fine. Because I create the securitygroup on my own, I won't miss any capabilites.

Do you plan to make the prop controlPlaneSecurityGroup optional? So the default securityGroup will be created in the future, or do you plan to remove the autocreation if none is specified?

**Comment by iliapolo** [comment]
@markus7811 The `controlPlaneSecurityGroups` property will definitely be optional. 

Since we don't want to introduce breaking changes, we will deprecate `securityGroup` and likely validate that only one of `controlPlaneSecurityGroups` or `securityGroup` is used. For the same reason, I'm also leaning towards keeping the auto-creation in case none is specified. 

We will be finalizing this soon.
