### ISSUE TITLE
[aws-elasticloadbalancingv2] cross-account `logAccessLogs()` triggers SecurityHub warning

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#11351]
_Note: Issue reported in internal ticket_

When `logAccessLogs` is passed a bucket in a different account SecurityHub warns about permissions. This is because the [SecurityHub best-practice](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-6) is to not grant `s3:PutObjectAcl` to other AWS Accounts in bucket policies, but as we see here:

https://github.com/aws/aws-cdk/blob/d946a9590122031528596b83942cfa2327881b64/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts#L181

the policies are being granted with `grantPut()` which grants permissions based on a set of constants in `perms.ts` as you can see here:

https://github.com/aws/aws-cdk/blob/d946a9590122031528596b83942cfa2327881b64/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L595

https://github.com/aws/aws-cdk/blob/d946a9590122031528596b83942cfa2327881b64/packages/%40aws-cdk/aws-s3/lib/perms.ts#L7-L10

This means that rather than granting the [minimum permissions](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-logging-bucket-permissions) of `s3:PutObject` and `s3:GetBucketAcl` it is granting `s3:PutObject*` which includes the denied actions.

### Reproduction Steps

1. Get bucket reference from ACCOUNT_1: `buck`
2. Run `logAccessLogs(buck, ...)` to enable logging for load balancer with logs being recorded to said bucket
3. See SecurityHub alert 

### Resolution Steps
I can see two possible options for resolution:
1. Revert the logic in `logAccessLogs` to before [this PR](https://github.com/aws/aws-cdk/pull/2221/files#diff-adac2b2781fa96225ee619e4c737b622R146) (looks like this is how it is configured [for `NetworkLoadBalancer`](https://github.com/aws/aws-cdk/blob/9444399b08825b4d1c5dce58e3c396c9941724c4/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L121:L139)
2. _(Recommended)_ Add additional public method to `S3.Bucket` to grant `S3:PutObject` without the wildcard (maybe `grantPutLimited()`). This could potentially apply to both the `ApplicationLoadBalancer` and `NetworkLoadBalancer` implementations

### Environment

  - **CDK CLI Version  :** 1.71.0
  - **Framework Version:** 1.71.0
  - **Node.js Version:**  12.16.2
  - **OS               :** OSX10.15.7
  - **Language (Version):**  Typescript 4.0.5

- [x] 👋  I can fix this
- [x] ❗ Will introduce breaking change

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@NGL321 Yes I think it makes sense to add this capability to `bucket`. Let's add the `grantPutLimited` method.

You mention this will incur a breaking change. Do you mean because `base-load-balancer` will no longer grant some permissions? 

----------------

As a side issue, the [docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-logging-bucket-permissions) you linked mention that `GetObejctAcl` is also needed, as is evident the `NetworkLoadBalancer` as well:

https://github.com/aws/aws-cdk/blob/58a48617c4fcd040a2a6fba22cf10b4eb0c71f64/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L153-L159

The `grantPut` method doesn't grant that, and I also see that it wasn't part of the original [implementation](https://github.com/aws/aws-cdk/pull/2221/files#). 

Does it work without it? Can you verify?

**Comment by fknittel** [comment]
This issue is affecting us too.

AFAIUI, the SecurityHub warning is triggered for _any_ ELB setup that uses `logAccessLogs()`, not only complex ELB setups involving multiple accounts: The "predefined" ELB AWS account is always separate from the regular account in which the S3 bucket is created.

> As a side issue, the docs you linked mention that GetObejctAcl is also needed [...]
> Does it work without it? Can you verify?

Our ELB logs get written to the S3 bucket just fine. I'm not sure why the docs say to additionally grant `s3:PutObject` and `s3:GetBucketAcl` to the `delivery.logs.amazonaws.com` service. The currently granted `s3:PutObject` on the ELB AWS account appears to suffice. OTOH, it might not hurt to conform to the recommended set of permissions?

**Comment by corymhall** [comment]
Closing this since the default behavior is now to not grant `PubObjectAcl`.
