### ISSUE TITLE
[aws-events] "Rule" support input roleArn 

### ISSUE THREAD

**Issue by guan840912** [aws/aws-cdk#11410]
aws event L2 Rule support input exist `roleArn`.
### Use Case
see https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.CfnRule.html
can input `roleArn` you want .
But L2 library `Rule` do not support input exist `roleArn`
see https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.IRule.html 
### Proposed Solution
Wish `Rule` can add Properties like `role` to add exist role to `Rule`. 
```ts
   const rule = new events.CfnRule(this, 'RdsExporterCfnRule', {
      description: 'Export snapshots from GP RDS to S3 at 2:30 am every day',
      name: 'exporter',
      scheduleExpression: 'cron(30 2 * * ? *)',
      roleArn: 'arn:aws:iam::012345678912:role/Exsit_Event_Role',
    });
```

example for L2 `Rule` add role  properties
```ts
    const rule = new events.Rule(this, 'RdsExporterRule', {
      description: 'Export snapshots from GP RDS to S3 at 2:30 am every day',
      ruleName: 'GP_exporter',
      schedule: events.Schedule.expression('cron(30 2 * * ? *)'),
      role: Exsit_Event_Role,
    });
```
### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by wulfmann** [comment]
You can also set the role arn on the actual `events.Target`.

In the meantime you can override the rule's rolearn with:

```typescript
const role = new iam.Role(this, `Role`, {
    assumedBy: new iam.ServicePrincipal('events.amazonaws.com')
})
const rule = new events.Rule(this, ``, {
    ...
});
const cfnRule = rule.node.defaultChild as events.CfnRule;
cfnRule.addPropertyOverride('RoleArn', role.roleArn)
```

**Comment by guan840912** [comment]
thanks @wulfmann  , `cfnRule.addPropertyOverride('RoleArn', role.roleArn)` is a good way to solve this problem.
but I think this is not the easy way for the normal user who use the L2 Constructs Library.

hi  @shivlaks  ☺️ 
any idea about this

**Comment by shivlaks** [comment]
@guan840912 

The L1 constructs (prefixed `Cfn*`) expose properties that map directly with CloudFormation.

The goal of L2 constructs is to enable all capabilities that the service allows with a higher level of abstraction and to be more intent based. The typical usage of a rule is:

1. create the rule
2. add [targets](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-readme.html#event-targets) to the rule (by calling the `addTarget()` API 

Some of the targets create a role that is a `singleton` event role - meaning a single role for all rules of that target. 
I believe we have a gap where not every target takes in a role as a property. 

i..e The [`CodeBuild`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events-targets.CodeBuildProjectProps.html), `CodePipeline`, `Kinesis`, `ECS`, ... event targets accepts a role (or creates one)

There are event targets where this property is not exposed and perhaps that's the gap that we need to address rather than make role a property on the top level `Rule` class.

There's also a chance I'm missing something and that there's a use case where rules are being used without targets. 
What's the use case where you're in need of a role but are using it without a target (sample code would be wonderful!)

**Comment by guan840912** [comment]
Hi @shivlaks 😊
The situation is  we have a pre-define role created by system admin (aws admin permission). and I only have  AWS events auth and pass iam role.  so I have assign the  pre-defined role to the event.
if I use L1 CfnRule I can pass pre-define role  I have like this and add targets later ...
```ts
   const rule = new events.CfnRule(this, 'RdsExporterCfnRule', {
      description: 'Export snapshots from GP RDS to S3 at 2:30 am every day',
      name: 'exporter',
      scheduleExpression: 'cron(30 2 * * ? *)',
      roleArn: 'arn:aws:iam::012345678912:role/Exsit_Event_Role',
    });
```  
so I have to assign the  pre-defined role to the event.
