### ISSUE TITLE
[aws-eks] Private Cluster not getting created after specifying subnets public SubnetIDs

### ISSUE THREAD

**Issue by shrivastavshubham34** [aws/aws-cdk#11471]
### Reproduction Steps
- Running the following section in CDK returns  
```bash
Lambda Functions in a public subnet can NOT access the internet. If you are aware of this limitation and would still like to place the function int a public subnet, set `allowPublicSubnet` to true
```
- Python script
```py
        vpc = ec2.Vpc.from_lookup(self, "VPC",
            vpc_id = "vpc-12345678"
        )
​
        eks_cluster = eks.Cluster(self, "EKS_Cluster",
            endpoint_access=eks.EndpointAccess.PRIVATE,
            default_capacity=0,
            version=eks.KubernetesVersion.V1_17,
            cluster_name="micro-k8s-dev",
            vpc=vpc,
            vpc_subnets=[ec2.SubnetSelection(subnets=[
                ec2.Subnet.from_subnet_id(self, 'nonprod-vm-pub-a', 'subnet-2jh3j2h34jh234jhjh')],
                ec2.Subnet.from_subnet_id(self, 'nonprod-vm-pub-b', 'subnet-2jh3j2h34jh234jhjh'),
                ec2.Subnet.from_subnet_id(self, 'nonprod-k8s-pri-a', 'subnet-2jh3j2h34jh234jhjh'),
                ec2.Subnet.from_subnet_id(self, 'nonprod-k8s-pri-b', 'subnet-2jh3j2h34jh234jhjh')],
]]
            )
```

### What did you expect to happen?

Cluster is created successfully

### What actually happened?
Following error
```bash
Lambda Functions in a public subnet can NOT access the internet. If you are aware of this limitation and would still like to place the function int a public subnet, set `allowPublicSubnet` to true
```

### Environment

  - **CDK CLI Version  :** 1.73.0
  - **OS               :** MacOS Catalina
  - **Language (Version):**  Python (3.8.2)

--- 

This is :bug: Bug Report

**Comment by shrivastavshubham34** [comment]
Guys this a bug right? or is something wrong from my side?

**Comment by iliapolo** [comment]
@shrivastavshubham34 Apologies for the delayed response. Yes, this is a bug. Thanks for reporting it.

Let me also offer a detailed explanation to whats happening for posterity and to make sure we are aligned. 

When the cluster is configured to use `eks.EndpointAccess.PRIVATE`, the lambda function that runs `kubectl` commands (i.e `KubectlProvider`) needs to be connected to the cluster subnets so it can access the EKS control plane.

At the time the [endpoint access customization](https://github.com/aws/aws-cdk/pull/9095) was introduced, there was a strict requirement that lambda functions not be placed in public subnets, since they would not be able to access the internet.

https://github.com/CurtisEppel/aws-cdk/blob/43feaebfd746e03fea9c8bacc49428f1a702c1b7/packages/%40aws-cdk/aws-lambda/lib/function.ts#L829-L831

This means that the EKS cluster needed to select only the private subnets, which is done [here](https://github.com/aws/aws-cdk/blob/d7ca5ca0fb714a716a269ecb2c69b85824253136/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1353).

The bug is that this selection is buggy, and in some cases (like yours) can mistakenly select a public subnet. This subnet is then detected in the lambda code which eventually throws an error, which is now out of context.

I've created a [fix](https://github.com/aws/aws-cdk/pull/11620) and it should not properly filter out the public subnets. 

In addition, since then, we've [relaxed](https://github.com/aws/aws-cdk/pull/9468) the requirement on public subnets for lambda functions, and now allow it by specifying the `allowPublicSubnet` property, which is the error you are seeing.

Thanks again.

**Comment by shrivastavshubham34** [comment]
Great, by when will the fix be available to us?

**Comment by iliapolo** [comment]
@shrivastavshubham34 should be available in the next release or two.

In the meantime, I can offer this workaround:

```python
vpc = ec2.Vpc.from_lookup(self, "VPC", vpc_id = "vpc-12345678")
vpc_subnets=[*vpc.private_subnets, *vpc.public_subnets]
```

Basically bypassing the `equals` problem by reusing the same objects that the VPC uses, instead of creating new objects.
If you don't need/want all of the subnets, you can filter them out, but the key is to reuse `vpc.private_subnets` and `vpc.public_subnets`.

Could that work for you?

**Comment by shrivastavshubham34** [comment]
@iliapolo I'm sorry but I'm not sure how I'll be able to filter out the subnets based on subnet IDs by reusing private_subnets

**Comment by iliapolo** [comment]
@shrivastavshubham34 something like this:

```python
vpc = ec2.Vpc.from_lookup(self, 'Default', vpc_id='vpc-id')

private_subnets = ['private1', 'private2']
public_subnets = ['public1', 'public2']

eks.Cluster(self, 'Cluster',
            version=eks.KubernetesVersion.V1_18,
            vpc=vpc,
            vpc_subnets=[
              ec2.SubnetSelection(subnets=[s for s in vpc.private_subnets if s.subnet_id in private_subnets]),
              ec2.SubnetSelection(subnets=[s for s in vpc.public_subnets if s.subnet_id in public_subnets]),
            ])
```

**Comment by shrivastavshubham34** [comment]
@iliapolo CDK ran into subnet tagging issues after adding the above code.
It asks me to add Tag('kubernetes.io/cluster/cluster_name', 'shared') to all subnets.
After I add them manually to the subnets I want to include, and run the CDK deployment it still throws errors.
```error
Subnets are not tagged with the required tag. Please tag all subnets with Key: kubernetes.io/cluster/zzzzz-k8s-zzz Value: shared
(Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: zzzzzzz; Proxy: null)
```

After checking the subnets now, I see that the cluster_name tags I added have been removed which indicates that during rollback, the K8s cluster deleted these lines from subnets automatically.

So do I need to tag all subnets, even though I'm using only 3 of them? That may lead to unneeded pathways to my cluster

**Comment by iliapolo** [comment]
@shrivastavshubham34

> So do I need to tag all subnets, even though I'm using only 3 of them? That may lead to unneeded pathways to my cluster

No, that shouldn't be a requirement.

There are a couple of things that might be happening here.

1. Are you sure the filtering is done correctly? Did you check the template to make sure only the subnets you expect appear? look for a `resourcesVpcConfig` key in the template.

2. You might be encountering the issue described [here](https://github.com/aws/aws-cdk/issues/10312), where the default node group mistakenly uses all the subnets in the vpc instead of the ones selected. If so, the issue also provides a workaround.

**Comment by shrivastavshubham34** [comment]
Hey, you were right I was encountering the 2nd issue, the fix mentioned solved it!

**Comment by shrivastavshubham34** [comment]
@iliapolo not related to this issue but I was wondering if it's possible to do "kubectl apply -k folder_url" using AWS EKS CDK construct?

**Comment by iliapolo** [comment]
@shrivastavshubham34 no but that sounds like an interesting use case. You mean that you would like to apply local folders you have in your project?

**Comment by shrivastavshubham34** [comment]
@iliapolo  Yea. I'm trying to add **TargetGroupBinding** custom resource definitions for EKS ALB Ingress controller in cdk stack 
```shell
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
```

**Comment by iliapolo** [comment]
> @iliapolo not related to this issue but I was wondering if it's possible to do "kubectl apply -k folder_url" using AWS EKS CDK construct?

@shrivastavshubham34 Can you create a feature request? 

Thanks

**Comment by shrivastavshubham34** [comment]
@iliapolo Sure! BTW can I also add a feature request to attach validate flag to KubernetesManifest class. I need to achieve something like this:
```shell
kubectl apply --validate=false -f cert-manager.yaml
```

**Comment by iliapolo** [comment]
@shrivastavshubham34 of course :)
