### ISSUE TITLE
[DynamoDb]: Add support DynamoDb Contributer Insights

### ISSUE THREAD

**Issue by pathik9** [aws/aws-cdk#11626]
Currently there is no option to enable Contributer Insightes on DynamoDB table via Code (CDK).  Please provide support for the same

**Comment by skinny85** [comment]
Hello @pathik9 ,

thanks for opening the issue. Is the ability to enable Contributor Insights on Dynamo DB available through CloudFormation currently?

Thanks,
Adam

**Comment by pathik9** [comment]
Hi @skinny85 

Dynamodb Contributor insights are not available via cloudformation.

**Comment by skinny85** [comment]
Thanks @pathik9. That means we need to either wait for CloudFormation support before implementing this in CDK, or use a CFN Custom Resource. Since this seems like a small feature (a boolean flag I think?), a Custom Resource might be overkill (as it involves creating an additional Lambda function in your Stack).

Adding the `needs-cfn` label.

**Comment by jonny-rimek** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/708

this is the issue to track it in the dynamodb repo

**Comment by jonny-rimek** [comment]
@skinny85 @pathik9 cfn support was added on the 22/2 =)

**Comment by skinny85** [comment]
It's here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-contributorinsightsspecification

Looks like a pretty small boolean flag. [Contributions are very welcome](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)! 😊.
