### ISSUE TITLE
[pipelines] Synth should check for synth errors of deployable stacks

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#11631]
Right now metadata synth errors are ignored, as they are normally checked during `cdk deploy` which does not happen in CDK pipelines.

Would prevent https://github.com/aws/aws-cdk/issues/11576

--- 

This is :bug: Bug Report

**Comment by mrpackethead** [comment]
Is there a practical work around for this problem at the moment?  Urgh. this just became a brick wall for me.

**Comment by stlserverless** [comment]
Thanks @rix0rrr for catching my duplicate issue in #12200. I searched all over for something related to "aspects" but never came across this one. Even if I had I'm not sure I would have recognized it as a duplicate. Because it yields incorrect results in CDK Pipelines, I hope it gets resolved before pipelines comes out of Developer Preview.

**Comment by mrpackethead** [comment]
@stlserverless .. yes, its gotta be resolved before GA, because otherwise its makes pipelines very limited.

**Comment by rix0rrr** [comment]
Duplicate of #9226 even.
