### ISSUE TITLE
Support for Metadata(Stack level metadata)

### ISSUE THREAD

**Issue by naveenkumarhm** [aws/aws-cdk#11653]
I am looking for guidance on how to manage top-level Metadata with the CDK.  Specifically, I am trying to deploy a template containing a Serverless Application Repository app that requires the AWS::ServerlessRepo::Application Metadata to be added to the template.  Scouring the web for ways to do this, I was looking for an "escape hatch" method using the Cfn* entities; however, it does not appear that there is any CfnMetadata entity on which I could hang the necessary data elements in the template.

**Comment by naveenkumarhm** [comment]
Any update on this?


I was thinking for this solution.

stack.node.defaultResource will give the [CfnStack](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnStack.html) associated with a [Stack](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html) construct. Then can I write cfnStack.addMetadata('AWS::ServerlessRepoApplication', {...})

**Comment by NGL321** [comment]
Hey @naveenkoppula,

So sorry about the delay. The main problem with what you are trying to do is the difference between Cfn Templates and SAM templates. Because the end-result of a CDK application will always be a Cloudformation template (not a SAM template), the SAM features are largely limited to what Cloudformation allows (and from what I can tell, Cfn doesnt support SAM Application Metadata).

So, at the moment, I am not certain this is possible. However, @njlynch is currently our SAM guy, so he may have more thoughts.
