### ISSUE TITLE
aws-rds: fromDatabaseInstanceAttributes static method missing 

### ISSUE THREAD

**Issue by cynicaljoy** [aws/aws-cdk#11817]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstance.html

The `fromDatabaseInstanceAttributes` method is missing from the generated documentation. 

---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
Thanks for opening the issue @cynicaljoy . I think that's because the `fromDatabaseInstanceAttributes()` method is actually incorrectly [defined in the `DatabaseInstanceBase` class](https://github.com/aws/aws-cdk/blob/80e5d90c0cf7a5ed8f8bb1c37768be34efb32e01/packages/%40aws-cdk/aws-rds/lib/instance.ts#L117-L133), instead of the `DatabaseInstance` class (and it's available in `DatabaseInstance` only because of JavaScript's/TypeScript's quirkiness).

A PR fixing this would be greatly appreciated 🙂.
