### ISSUE TITLE
(eks): Why is creating managed node groups for imported clusters allowed, but not for clusters crossing the stackborder

### ISSUE THREAD

**Issue by markus7811** [aws/aws-cdk#11810]
## :question: General Issue

Creating managed nodegroups is somehow strange:

1. Creating a managed nodegroup with the cluster in the same stack works like a charm ...
2. Creating a managed nodegroup in another stack with passing the cluster doesn't work ... (https://github.com/markus7811/aws-cdk/blob/48e0d950ef0d52117608c5ca37fcb5a57e9324df/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L315)
3. Creating a managed nodegroup in another stack with using the ICluster interface ... no problem

```typescript

export class EksClusterStack extends cdk.Stack {
  readonly cluster: eks.Cluster;
  readonly nodegroup: eks.Nodegroup;

  constructor() {
    this.cluster = new eks.Cluster() ...

    /* Works! */
    this.nodegroup = new eks.nodegroup(... {
      cluster: this.cluster,
      ... 
   }
  }
}

/* wont work */

export class NodegroupWontWork extends cdk.Stack {
  
  constructor( ... props) {
      new eks.nodegroup(... {
        cluster: props.cluster,
        /* in this case cluster from EksClusterStack is passed as "real" eks.Cluster */
      ... 
   }
  }
}

/* works */

export class NodegroupWorks extends cdk.Stack {
  
  constructor( ... props) {
      new eks.nodegroup(... {
        cluster: eks.fromClusterAttributes(  /* in this case I reconstruct the cluster form stack 1 */),
        ... 
   }
  }
}
```

### The Question

Why do you prohibit 2 and allow 3. For sure, it has something to do with the auth configmap?!
I have to say, that i didn't run deep tests on what would happen if I rewrite the configmap with cdk after the nodegroup was added ... that's the only thing, I could imagine that can go wrong....

So is it a real problem (cdk will edit the configmap after nodegroup was attached)?

Shouldn't it be forbidden or allowed for "both" cluster and icluster?

### Environment
not relevant...

**Comment by iliapolo** [comment]
@markus7811 Just to make sure I don't make any unwanted assumptions, could you please attach small code snippets for the 3 scenarios you described?

**Comment by markus7811** [comment]
I added some "pseudocode" to clarify my intentions... as I linked, that is the line, causing NodegroupWontWork stack to not deploy.

**Comment by iliapolo** [comment]
@markus7811 Thanks for providing the code.

In scenario 2, are you referring to this type of error?

```console
NodeGroupStack/NodeGroup/NodeGroupRole should be defined in the scope of the ClusterStack stack to prevent circular dependencies
```

If so, this is indeed somewhat surprising. Hopefully this can provide some clarifications: https://github.com/aws/aws-cdk/pull/9701#issue-467963627

**Comment by markus7811** [comment]
Yes, that was the error i got!

**Comment by markus7811** [comment]
I totally understand, why I get the error - and the main problem for me is, that handling with a configmap for auth is real pain. Would like to see https://github.com/kubernetes-sigs/aws-iam-authenticator#crd-alpha soon on eks - but think it won't happen son :-( even if it would solve many problems i think (the handling the auth configmap is a problem we solved internally by creating our own crd / operator).
So maybe I didn't understand you - but I think what you linked won't solve my problem. At the moment I would like to create several nodegroups in several stacks. And it works fine (with IClusters) ... eks is handling the configmap on its own ... 

I won't consider this behaviour to be a bug - but I wanted to understand why things are like this and now I think I got it (and don't like it;-)

I think it would be really nice to allow nodes to be added across the stack border ...

**Comment by markus7811** [comment]
Ok, tested it ... will be overwritten if changes to the configmap occur so the bootstrappers will be gone :-)

**Comment by iliapolo** [comment]
@markus7811 As I understand, the problem with using:

```ts
constructor( ... props) {
    new eks.nodegroup(... {
      cluster: eks.fromClusterAttributes(  /* in this case I reconstruct the cluster form stack 1 */),
      ... 
 }
```

Is that because the resulting cluster is an `ICluster`, the node group will not configure the `aws-auth` config map, as shown in the line you linked to:

https://github.com/aws/aws-cdk/blob/3dcd1a8345a20caad5100f810517f8e742bd65e8/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L315-L324

Now that I think of it, it might be that this condition is no longer necessary. Previously, we had to do this because we couldn't apply manifests on `ICluster`, which means we couldn't expose `cluster.awsAuth` on `ICluster`.

We since then added this ability, and it should now be possible, but i still need to do some due-diligence.

Would this solve the issue? You'd still need to do `fromClusterAttributes`, but the resulting cluster will have an `awsAuth` property attached to it so that the node group can configure it.

**Comment by markus7811** [comment]
Is it possible that more than one Stack can have awsAuth? The implementation looks like there can only one stack holding this Resource. But I create the user/role mappings in the stack the cluster is created in. The nodegroups are several stacks. Is this possible - i don't hink so.

Maybe it would help to create several scenarios how nodegroups could be used?

**Comment by iliapolo** [comment]
@markus7811 Yeah we cannot expose `aws-auth` on `ICluster` because it would potentially overwrite existing configuration in imported clusters.

For now, the way to configure node groups in another stack would have to be by creating the `nodeRole` in the cluster stack as well, as you've already mentioned [here](https://github.com/aws/aws-cdk/issues/11987#issuecomment-743323486).
