### ISSUE TITLE
(eks): separate definition of eks cluster from its worker nodes

### ISSUE THREAD

**Issue by nicolaracco** [aws/aws-cdk#11987]
I'm trying to figure if there's a pattern or a best practice to separate the definition of an eks cluster from its worker nodes.

My current scenario is the following: I have a cdk stack which provisions an EKS cluster, its roles, its nodegroups, etc. This is a pretty big cluster and I'm hitting the hard limit of 200 resources in a cloudformation stack. I would like to start segregating some resources.

If I try to create the EKS Cluster in Stack A provision a Nodegroup in Stack B, I receive the following error from CDK: `StackB/NodeGroup/NodeGroupRole should be defined in the scope of the StackA stack to prevent circular dependencies`.

I thought I could follow this approach: StackA provisions the NodeGroupRole, then StackB receives the cluster ref and the role ref, and provisions the nodegroup. But looking at the source code I found the following snipped in the Nodegroup resource:

```
// managed nodegroups update the `aws-auth` on creation, but we still need to track
// its state for consistency.
if (this.cluster instanceof Cluster) {
  // see https://docs.aws.amazon.com/en_us/eks/latest/userguide/add-user-role.html
  this.cluster.awsAuth.addRoleMapping(this.role, {
    username: 'system:node:{{EC2PrivateDNSName}}',
    groups: [
      'system:bootstrappers',
      'system:nodes',
    ],
  });
}
```

So, even if the NodeGroupRole is received from the outside, the nodegroup constructor alters the awsAuth, creaing a weird side effect (synth of StackB alters the synth of StackA).

Is there another approach I could follow to segregate resources creation and reduce the size of my stack?

**Comment by markus7811** [comment]
Maybe i don't understand exactly what you do. I create one "noderole" because all nodes are equal when it comes to the role (using iam4serviceaccounts for all pods). 
You will allways have on stack holding the awsAuth resource, because it is a config map written by a kubernetes manifest, so it can't be spread over several stacks.
https://github.com/aws/aws-cdk/blob/6fb34483432b5cdcc485bbf6bfdb7bbb74f4b895/packages/%40aws-cdk/aws-eks/lib/aws-auth.ts#L40

In my opinion, the right way would be to use crd's instead of one configmap for the auth mapping. So i hop aws will enable this feature (https://github.com/kubernetes-sigs/aws-iam-authenticator#crd-alpha) then it will be possible to create auth mappings in the stack the resource that needs the mapping was created in.

At the moment you have to ensure that only one stack has the "truth" of authmappings and it's not overwritten unintentionally...

**Comment by nicolaracco** [comment]
I see why you're doing the mapping, but could the awsAuth mapping be applied only when nodegroup and autoscalinggroup roles are not explicit? I try to explain it with an example.

Say that in aws-eks/managed-nodegroup.ts the addRoleMapping on awsAuth is done only when the role is not explicit:
```
if (!props.nodeRole && this.cluster instanceof Cluster) {
  // see https://docs.aws.amazon.com/en_us/eks/latest/userguide/add-user-role.html
  this.cluster.awsAuth.addRoleMapping(this.role, {
    username: 'system:node:{{EC2PrivateDNSName}}',
    groups: [
      'system:bootstrappers',
      'system:nodes',
    ],
  });
}
```

And that aws-eks/cluster.ts contains the following method:

```
public createNodegroupRole(id: string): iam.Role {
  const role = new Role(this, id, {
    assumedBy: new iam.ServicePrincipal('ec2.amazonaws.com'),
  })
  role.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonEKSWorkerNodePolicy'));
  role.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonEKS_CNI_Policy'));
  role.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonEC2ContainerRegistryReadOnly'));
  this.awsAuth.addRoleMapping(role, {
    username: 'system:node:{{EC2PrivateDNSName}}',
    groups: [
      'system:bootstrappers',
      'system:nodes',
    ],
  });
  return role;
}
```

Now if I write the following code:
```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as eks from '@aws-cdk/aws-eks';
import * as iam from '@aws-cdk/aws-iam';

interface StackAProps extends cdk.StackProps {
  vpc: ec2.IVpc;
}

export class StackA extends cdk.Stack {
  readonly cluster: eks.ICluster;
  readonly ngRole: iam.IRole;

  constructor(scope: cdk.Construct, id: string, props: StackAProps) {
    super(scope, id, props);

    const cluster = new eks.Cluster(this, 'EKS', {
      version: eks.KubernetesVersion.V1_18,
      vpc: props.vpc,
    })
    this.cluster = cluster;

    this.ngRole = cluster.createNodegroupRole('MyRole');
  }
}

interface StackBProps extends cdk.StackProps {
  cluster: eks.ICluster;
  role: iam.IRole;
}

export class StackB extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: StackBProps) {
    super(scope, id, props);

    const ng = new eks.Nodegroup(this, 'NG', {
      cluster: props.cluster,
      nodeRole: props.role,
    })
  }
}

const app = new cdk.App();
const stackA = new StackA(app, 'StackA', { vpc: myVPC });
const stackB = new StackB(app, 'StackB', { cluster: stackA.cluster, role: stackA.ngRole });
```

I'm explicitly creating a nodegroupRole to be used across my nodegroups and I can separate the resources definition without having StackB altering StackA synth.

Could this be a valid approach? If you want I could try to do a PR with this change

**Comment by iliapolo** [comment]
@nicolaracco the problem with `if !props.nodeRole` is that we don't really have a way to validate the role was created using this helper `createNodegroupRole` function, which may result in some unexpected behavior. 

We could potentially change the [`nodeRole`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.NodegroupProps.html#noderolespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) property to accept a special new `EKSNodeRole` construct, but that would be a breaking change.

I think the best approach here is to create the node role in the cluster stack like you mentioned. In this scenario, you wrote: 

> So, even if the NodeGroupRole is received from the outside, the nodegroup constructor alters the awsAuth, creaing a weird side effect (synth of StackB alters the synth of StackA).

I agree its a little strange, but i'm wondering what are your specific concerns with this? I'm not sure it actually creates a practical problem. As you also noted, the reason you separate the stacks is because of resource limits, and not a functional consideration. In that sense, you can think of it as: 

*one **resource** affecting the synth of another **resource***

which is reasonable. 

Having said that, I do think its worth exposing that helper function you mentioned so that users won't have to duplicate that logic. So it would look something like this:

```ts
const cluster = new eks.Cluster(this, 'Cluster', ...);
const nodeRole = eks.createNodegroupRole(this, 'NodeRole');

new NodegroupStack(..., { cluster, nodeRole });
```

**Comment by nicolaracco** [comment]
Thank you for your support. I'll follow this pattern then
