### ISSUE TITLE
(eks): can not synthesize cdk app with eks to support multiple partitions/regions

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#12018]
`kubectl` is using lambda layer published via serverless application repository. It depends on the `region` to check the partition which requires giving certain region when synthesizing cdk.

https://github.com/aws/aws-cdk/blob/6fb34483432b5cdcc485bbf6bfdb7bbb74f4b895/packages/%40aws-cdk/aws-eks/lib/kubectl-layer.ts#L86-L89

Might introduce a context parameter(such as `@aws-cdk/eks:targetRegion=cn-north-1`) to help choose the correct application id.

### Reproduction Steps

1. create a cdk app with eks cluster
2. run `npx cdk synth -c @aws-cdk/core:newStyleStackSynthesis=true` to generate the cloudformation template
3. deploy the template to AWS china, the stack failed on using lambda layer in `aws` partition

### Environment

  - **CDK CLI Version  :** 1.74.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by zxkane** [comment]
Might using `CfnMapping` to select the layer by `core.Aws.Partition`

For example,

```ts
const layerMapping = new cdk.CfnMapping(this, 'LayerMapping', {
      mapping: {
        aws: {
          // see https://github.com/aws/aws-cdk/blob/60c782fe173449ebf912f509de7db6df89985915/packages/%40aws-cdk/aws-eks/lib/kubectl-layer.ts
          kubectlAppid: 'arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-kubectl',
        },
        'aws-cn': {
          kubectlAppid: 'arn:aws-cn:serverlessrepo:cn-north-1:487369736442:applications/lambda-layer-kubectl',
        },
      }
    });
```

**Comment by iliapolo** [comment]
@zxkane Apologies for the delayed response.

We recently removed the dependency on the SAR app, and instead we are bundling the necessary lambda layers inside the module, meaning it can be deployed without a problem to every region as it utilizes the normal asset mechanism. 

See https://github.com/aws/aws-cdk/pull/12129

I'm going to go ahead and close this issue since i believe it no longer poses a problem. Feel free to re-open in case needed.

Thanks
