### ISSUE TITLE
(ec2): Ability to lookup the default subnets

### ISSUE THREAD

**Issue by acomagu** [aws/aws-cdk#12047]
Currently there is no way to get/identify the default subnets. This proposes the feature to do it.

### Use Case

We can deploy resources to the default VPC&subnets easily.

### Proposed Solution

I'm not sure how it should be implemented yet, but I guess it'll be similar with the way to get the default VPC(`ec2.Vpc.fromLookup(..., { default: true })`).

I think the API will be

```typescript
vpc.selectSubnets({ default: true });
```

or something like

```typescript
ec2.lookupDefaultSubnets();
```

?

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Sorry, what are default subnets?

**Comment by rix0rrr** [comment]
Better yet, tell me what you are trying to achieve please.

**Comment by acomagu** [comment]
@rix0rrr Thank you. I didn't know that.

The use-case is deploying EC2 instance or other resource to default VPC&subnet. I mean the case that I don't want to create new subnet for the resources.

It can be achieved already, by specifying the default subnet ID(`ec2.Subnet.fromSubnetId`). But I think the way to get default subnet without the ID is still useful in case that we don't want to use fixed ID or we don't know the ID when we writing the code yet.

We can get default VPC without the ID but don't for default subnet. I don't have any idea why.

**Comment by rix0rrr** [comment]
I'm not sure why you are so focused on subnets.

Most L2 classes have you pass in a `vpc` property, and don't need any subnet objects.

You would use them like this:

```ts
const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });
new ec2.Instance(this, 'Instance', {
  vpc
});
```

And that will use your default VPC. If that VPC has only "default" (public) subnets, then it will use those, otherwise you may also need to pass in a `subnetSelection` object to pick the set of subnets in that VPC you want to deploy to.

If you need the subnetIds directly to pass into an L1 you go:

```ts
const subnetIds = vpc.selectSubnets().subnetIds;
```

I think you can probably get by without looking up the default subnets. If not, I'd recommend you write a script to look them up, write that information to a `.json` file and read it in your CDK app.

**Comment by dennisvang** [comment]
>I'm not sure why you are so focused on subnets.
>
>Most L2 classes have you pass in a vpc property, and don't need any subnet objects.

@rix0rrr For example, [aws_elasticbeanstalk][1] only has L1 constructs, and if I specify `VPCId` in [CfnEnvironment.optionSettings][2], I also need to specify `Subnets`, as in

```typescript
...
{
  namespace: 'aws:ec2:vpc',
  optionName: 'VPCId',
  value: vpc.vpcId,
},
{
  namespace: 'aws:ec2:vpc',
  optionName: 'Subnets',
  value: subnetIds.toString(),
},
...
```


[1]: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticbeanstalk-readme.html
[2]: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-ec2vpc
