### ISSUE TITLE
(eks): AwsAuth not updated, kubectl commands failing in CustomResources

### ISSUE THREAD

**Issue by robbierolin** [aws/aws-cdk#12149]
Our cdk cluster recently started experiencing failures where our CustomResources are not authorized to call `kubectl` All kubectl commands result in the error `error: You must be logged in to the server (Unauthorized). `

### Reproduction Steps

 Create an AdminRole
```
const clusterAdmin = new Role(this, 'AdminRole', {
  roleName: 'EKSClusterAdmin',
  assumedBy: new AccountRootPrincipal(),
});
```
Create cluster, pass AdminRole to mastersRole parameter
```
const cluster = new Cluster(this, 'EKSCluster', {
  version: KubernetesVersion.V1_18,
  vpc: props.vpc,
  clusterName: 'EKSCluster',
  mastersRole: clusterAdmin,
  secretsEncryptionKey: secretsKey,
  defaultCapacity: 0,
  endpointAccess: EndpointAccess.PUBLIC_AND_PRIVATE,
});
```
Create a lambda with a kubectl layer
```
const lambda = new lambda.Function(this, id, {
  code: props.lambdaCode,
  functionName: props.lambdaFunctionName,
  handler: props.handler,
  runtime: lambda.Runtime.PYTHON_3_7,
  layers: [props.layerVersion],
  timeout: Duration.minutes(15),
  memorySize: 256,
  vpc: props.vpc,
  securityGroups: props.securityGroups,
});
```
4. Give lambda permission to assume the AdminRole
```
lambda.role.addToPolicy(
      PolicyStatement.fromJson({
        Effect: 'Allow',
        Action: ['sts:AssumeRole'],
        Resource: props.mastersRole.roleArn,
      })
    );
```
5. In a custom resource in this lambda, login using the admin role
```
aws eks update-kubeconfig --name EKSCluster --role-arn <AdminRoleArn> --kubeconfig /tmp/kubeconfig
```
Outputs `Added new context arn:aws:eks:us-west-2:XXXXXXXXXXXX:cluster/EKSCluster to /tmp/kubeconfig`

6. Make a kubectl call
e.g. `kubectl get psp --kubeconfig /tmp/kubeconfig`

### What did you expect to happen?
kubectl command succeeds

### What actually happened?

`error: You must be logged in to the server (Unauthorized)`

### Environment

  - **CDK CLI Version  :** 1.68.0

**Comment by iliapolo** [comment]
@robbierolin I'm not sure I understand. Are you creating your own lambda function that runs `kubectl` commands? In addition to the one provided by the `eks.Cluster`? Also - has this started happening due to a version upgrade you did? 

Please also mention the `@aws-cdk/aws-eks` module version you are using.

**Comment by robbierolin** [comment]
Yes we are creating our own lambda functions that runs `kubectl` commands. We are using the latest versions and it was working a couple weeks ago so it could be due to version upgrade.

@aws-cdk/aws-eks version 1.79.0

**Comment by iliapolo** [comment]
@robbierolin I'm not sure why it would start failing all of the sudden, but do you have proper retries for you `kubectl` command? What happens is that the `aws-auth` config map is updated asynchronously with `kubectl apply`. So it might take a little time for it to take affect.

**Comment by robbierolin** [comment]
Yes we have retries, but we started to hit lambda timeouts from retrying too much. Is there a way to add a dependency on aws-auth being created?

**Comment by iliapolo** [comment]
@robbierolin not trivially. The `aws-auth` config map exists, but we need to specifically wait for it to be fully updated with the role. Usually retries is a good enough mechanism. 

> but we started to hit lambda timeouts from retrying too much

Do you mean you are hitting the full 15 minutes of execution with retries?

**Comment by robbierolin** [comment]
Ya exactly. 

We ended up standing up our cluster in two stages (i.e. two calls to `cdk deploy`). The first stage creates the cluster and this lambda, and the second stage runs various kubectl + helm commands from the lambda in CustomResources. `aws-auth` was updated properly after the first stage completed

**Comment by iliapolo** [comment]
Interesting. This means it just takes longer than 15 minutes for the role mapping to be fully updated sometimes. 

> We ended up standing up our cluster in two stages 

Thats ok. But I can offer two alternative approaches:

1. Use `cluster.kubectlRole` inside your lambda instead of a custom admin role. The default `kubectlRole` is not susceptible to this issue because it is the role that created the cluster, which is inherently mapped to `systems:master` by EKS.

2. Use an [Asynchronous Provider](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#asynchronous-providers-iscomplete) that supports longer execution times. 

P.S - can you share why exactly are you using a custom lambda for this purpose? is the built in provider not sufficient?

**Comment by robbierolin** [comment]
I think the built in provider didn't exist when we first built our cluster or we just didn't know about it. Seems like it would be a good option to switch to using it.
