### ISSUE TITLE
Does SimpleSynthAction allow using cloudAssemblyArtifact in custom actions?

### ISSUE THREAD

**Issue by OperationalFallacy** [aws/aws-cdk#12254]
I'm pondering about using generated CDK templates from SimpleSynthAction in some custom CloudFormationCreateUpdateStackAction and other similar actions

## Given  SimpleSynthAction

If I used SimpleSynthAction like this

```
      synthAction: SimpleSynthAction.standardYarnSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        environment: {
          privileged: true
        }
      })
```

### Access to cloudAssemblyArtifact templates?

Is it possible to get synthesized template location from the cloudAssemblyArtifact?
 
```
    const CreateCfAction = new codepipeline_actions.CloudFormationCreateUpdateStackAction({
      actionName: 'Deploy',
      // it looks like this when cdk adds standard actions with addApplication()
      // Artifact_Build_Synth::assembly-xxx-Pipeline-CreateDevzzz/{squashed_namings}1EBADCF8.template.json
      templatePath: cloudAssemblyArtifact.atPath(???),
      stackName: 'StackCloud',
      adminPermissions: true,
      variablesNamespace: 'SomeNamespace'
    });
```

### Environment
  - **CDK CLI Version:** 1.78.0

I guess the answer is to create a custom build action? Or there is a way to use cloudAssemblyArtifact, I've looked at source code and there is some magic for directory names.

**Comment by OperationalFallacy** [comment]
It looks like `TemplateFile` is what I was looking for. Is there a way to get it from `Stage` class, when app stages declared?
 
```
import { Construct, Stage, StageProps, CfnOutput } from '@aws-cdk/core';
import { Stack, stackSettings } from './mystack';

export class PipelineStage extends Stage {
  public readonly TemplateFile: string;

  constructor(scope: Construct, id: string, props: StageProps, stackconfig: stackSettings) {
    super(scope, id, props);

    const service = new Stack(this, 'Stack-' + stackconfig.stacksettings?.environment, {
      env: {
        region : 'us-east-1',
      }
   },
   stackconfig,
   );
    // Expose file name
    this.TemplateFile = service.templateFile;
  }
}
```

and then in the pipeline for deployment action
where `devapp` declared as new Stage... 
```
    const CreateAppAction = new CloudFormationCreateUpdateStackAction({
      actionName: 'CreateStack',
      templatePath: cloudAssemblyArtifact.atPath([devapp.assetOutdir, devapp.artifactId, devapp.TemplateFile].join('/')),
      stackName: 'DeployApp',
      variablesNamespace: 'ServiceA'
    });
```

**Comment by NGL321** [comment]
Hey @OperationalFallacy,
I apologize for this VERY late response, it seems like I overlooked your question due to the quick self-response. While the standard format of our Pipelines library has changed since its General Availability, adding arbitrary CodePipeline actions has not, so confirming your answer seems useful even in retrospect.

Your solution as written of passing the `TemplateFile` up through the stage is the standard approach with this styling of the Pipelines library. I would write it exactly as such (perhaps with the exception of using the `path` js library to join the asset directory). There is no better passthrough structure within `Stage` and the construct itself does not have a `TemplateFile` path because it can naturally consist of a number of stacks with separate template files (even if that number is one, because of the possibility for multiple stacks contained within, a single file path could not be returned).

I am setting this issue to autoclose, however if there are any lingering questions, feel free to comment and keep the issue open.

😸 😷
