### ISSUE TITLE
How to Push and Deploy CDK based Project to several Environments

### ISSUE THREAD

**Issue by vikrantsundriyal** [aws/aws-cdk#12445]
## :question: General Issue

Simplifying the issue statement....
I think it was leading to wrong response... 

<<How can i give a custom dynamic name to Cloudformation Stack.>>
Seems it always takes the name derived from the Directory name where i initialise the cdk application. How can this be overridden.
If in a region i wish to create dev and qa using cdk, after pushing code to SCM when i redeploy the app, it finds the same Cloudformation Stack name hence creates the changeset. How to handle this situation. I can dynamically name resources inside application, but because Stack name is same it considers as update for Old Cloudformation Stack.
Note: I don't want to initialise every time and change code during deployment for every environment (giving new app name). 
Please assist.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by FavorWedge** [comment]
@vikrantsundriyal this is the pattern I use to deploy to multiply environments.

https://taimos.de/blog/create-a-cicd-pipeline-for-your-cdk-app

**Comment by vikrantsundriyal** [comment]
@FavorWedge , thanks.. My query was slightly different, not to setup pipelines across accounts. 
I have rephrased the issue statement. 
I want to get an idea on how CloudFormation Stacks launched via CDK can be dynamically named, rest pipeline creation and giving dynamic names to resources inside app/stack is in my control.

**Comment by peterwoodworth** [comment]
Hey @vikrantsundriyal,

The name of the stack deployed to CloudFormation is not restricted to the name of your directory, it is declared in code exactly like the stack resources. You can change the name of the stack deployed to CloudFormation where you declare the stack in your code, like here:
```ts
import Stack from '../lib/stack'
const app = new cdk.App();
new Stack(app, 'DECLARE_STACKNAME_HERE');
```
You can also create runtime variables when deploying your application. Run `cdk deploy --context stackname=STACKNAME` to pass in a variable, like the name of your stack. You can access this context variable in your code by using the `tryGetContext` method, like here:

```ts
let environment = this.node.tryGetContext('env');
​
switch(environment) {
	case('TEST'):
		new Stack(app, TEST_STACK_NAME, {
			env: { account: XXXXXX, region: XXXXXXX }
		};
	case('PROD'):
		new Stack(app, PROD_STACK_NAME, {
			env: { account: YYYYYYYY, region: YYYYYYY }
		};
```

I'd also like to note that once a stack has been deployed under a certain name, you cannot update that name. In order to change the name of an existing stack you must first destroy the existing stack and then recreate the stack using a new name.

Let me know if this properly answers your question!
