### ISSUE TITLE
A way to create "linked" stacks

### ISSUE THREAD

**Issue by mimozell** [aws/aws-cdk#12485]
I have a main stack that stores some essential information such as vpcId, loadBalancerArn, ecsClusterName etc in SSM Parameter Store. In other completely separate stacks, I would like to read these values from SSM and deploy new things on top of the VPC, ECS etc via those params, but I haven't found a good way to do it. 

Generally, if I try to use the `fromAttributes` functions of the different modules to get the resources the first stack created, I get very ridiculous requirements to be able to fetch a resource. For example, when I want to fetch a VPC with a VPC ID, I get asked to also provide subnets and AZs (logged bug [here](https://github.com/aws/aws-cdk/issues/12470)) and I see the same with pretty much all the other resources I have tried so far. If I try to use the `fromLookup` functions - that actually return a resource when provided its unique identifier - using values from SSM that are only resolved at deploy time, I get this error: `All arguments to look up a load balancer must be concrete (no Tokens)`.

What's the best approach to solve this issue? Or are we not meant to link stacks like this with CDK?

**Comment by mimozell** [comment]
My current approach to solving this problem is using the SDK to fetch the parameters from SSM and then using those `concrete` values with `fromLookup` to get the resources created by other stacks. It would be good if the same could be achieved with just CDK though.

**Comment by peterwoodworth** [comment]
Hi @mimozell,

You can link stacks by passing props through the constructors of the stacks. Check out [this link](https://stackoverflow.com/questions/61579756/aws-cdk-how-do-i-reference-cross-stack-resources-in-same-app) to get a good idea of how to accomplish this. Let me know if this answers your question or if you need any additional help with this!

**Comment by mimozell** [comment]
Hi @peterwoodworth, 

thanks but this doesn't help me. The stacks are completely separate, they belong to different applications, different code bases. There doesn't seem to be a good way of solving this problem with cdk only in my short experience with it. I've switched to using the sdk for this purpose everywhere now.

**Comment by peterwoodworth** [comment]
If the resources you want to use are part of completely different applications and you only want to use the CDK you're going to have to use the [`fromLookup()` function.](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#static-fromwbrlookupscope-id-options) This link explains why tokens cannot be used in this function as well

You can see the properties you need to fill out for this [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.VpcLookupOptions.html). Take note of this when filling out your attributes `The combination of properties must specify filter down to exactly one non-default VPC, otherwise an error is raised.`

You can check your AWS console for the information you need to provide to use your VPC, you don't have to use secrets. Do you have a requirement of using secrets rather than another method of using the existing values?

**Comment by mimozell** [comment]
Hi again @peterwoodworth,
I understand all this, but do you see how this is terrible for automation? In order to make automation possible I use sdk so I don't have to go to the console to know what parameters to pass to and from my ever-changing stacks. I guess this whole post has boiled down to the following question:
Is it possible to automate the creation of stacks on top of other stacks with cdk only, i.e. without using the sdk?

**Comment by peterwoodworth** [comment]
Yes! Instead of using SSM I would suggest using [CloudFormation Exports](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html) in your main stack. You can produce outputs with the CDK using [`core.CfnOutput()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnOutput.html).

In your other stacks where you use infrastructure from the above stack you will use `fromXyz()` (`fromVpcAttributes` instead of `fromLookup()`) and inside that function use [`Fn::ImportValue`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html). The CDK ImportValue is part of the [`core.Fn class`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Fn.html#static-importwbrvaluesharedvaluetoimport). 

You will still have to export the subnet IDs, but I'm not sure there's another good way to do this. Hopefully this helps you out

**Comment by mimozell** [comment]
Okay, basically there are no better ways of doing this than I have already mentioned in the question. So I'm closing this issue for now.

**Comment by mimozell** [comment]
Okay, basically there are no better ways of doing this than I have already mentioned in the question. So I'm closing this issue for now.
