### ISSUE TITLE
(cloudfront): add SingletonEdgeFunction

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk#12498]
There is a `SingletonFunction` construct which wraps a `Function`, ensuring there's a single instance of that Lambda in the stack. There should be the same mechanism for an EdgeFunction.

### Use Case

I would like to use the same Lambda@Edge function to authenticate multiple distributions.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the feature request (and sorry for the delay in response)!

This is actually something we discussed when the `EdgeFunction` construct was first being created. More broadly, I'd like users to be able to use _any_ of the `Function` extensions (singleton, python, node). This is a larger request and would involve more closely integrating the `EdgeFunction` features into `Function` directly, or providing a way to tell the higher-level constructs to create an `EdgeFunction` instead of a `Function`. 

The work for just `SingletonEdgeFunction` though, would be considerably simpler. Pull requests welcome!

**Comment by njlynch** [comment]
related #12671
