### ISSUE TITLE
(pipelines): Unable to deploy specific stack in stage when target stack has dependency stack in another account

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#12510]
## :question: General Issue

Trying to deploy a specific stack from a specific assembly is not proceeding without first deploying the depdendent stacks.

I have a stage (core.Stage) and there are two stacks. Each of the stacks are cross-account deployment using the env dictionary with account key to specify the account number.

The stacks must be deployed in a specific order. So I use ```add_dependency```. Each stack deploys to a different account.

Error
```
Including dependency stacks: 
SOMEIDENTIFIER
SOMEIDENTIFIER (other-stack-name)
SOMEIDENTIFIER (other-stack-name): deploying...
[0%] start: Publishing ID:123456789123-us-east-1
[100%] fail: Need to perform AWS calls for account 123456789123, but the current credentials are for 111122223333

 ❌  SOMEIDENTIFIER (stack-name) failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/usr/local/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at CloudFormationDeployments.publishStackAssets (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:262:7)
    at CloudFormationDeployments.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:154:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:201:9)
Failed to publish one or more assets. See the error messages above for more information.
```

### The Question

How can I deploy each specific stack though to a different account? I currently have to locally temporarily comment out the ``add_dependency```, re-run the ```cdk synth```, then I can deploy each stack.

### Environment

  - **CDK CLI Version:** 
   1.82.0 (build c445b89)

  - **Module Version:** 
  1.82.0

  - **Node.js Version:** 
  v15.3.0

  - **OS:** 
  macOS

  - **Language (Version):** 
  Python 3.9

**Comment by rix0rrr** [comment]
The problem here is that to deploy 2 stacks to 2 different accounts in one invocation, the CDK needs to be able to assume credentials for both. The solution is that you need to use an authentication mechanism that allows it to get different credentials for different accounts.

* It cannot be environment variables or `--profile`, since you can only have one of those.
* It *could* be authentication plugins, however there aren't many available and this isn't a well-trodden path.
* It *should* be modern bootstrapping + modern stack synthesis, however that is currently blocked on a bug that would be resolved by https://github.com/aws/aws-cdk/pull/11952.

The easiest way to unblock yourself currently is to use the `--exclusively`/`-e` flag when calling `cdk deploy` and deploying both stacks individually.

Not a very satisfying answer, I know, but it will have to do until the modern stack synthesis bugs are fixed.
