### ISSUE TITLE
(cloudfront): amend existing resources

### ISSUE THREAD

**Issue by maraisr** [aws/aws-cdk#12524]
With a progressive adoption scenario, and existing CloudFront distributions im asking for an ability to add origins and in tern behaviors to existing distributions. 
 
### Use Case

We have an existing distribution for our fronting CF service. We have opted to progressive adopt CDK to manage our cloud resources, so bringing CF into CDK is out of scope for now. Never-the-less we need to now add a _new_ behavior to that. Which there is currently no ability to do.

### Proposed Solution

One solution could look like:

```ts
CloudFrontWebDistribution
    .fromDistributionAttributes(stack, 'global-cf', {
	distributionId: Fn.importValue('example-a'),
	domainName: Fn.importValue('example-b'),
    })
    .addOrigin(...)
    .addBehviour(...);
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Generally, this is behavior -- as described -- is not supported by CloudFormation. We can't "adopt" a resource created elsewhere and then alter its properties. The only way to go about this would be to write a CloudFormation custom resource Lambda function which receives the input parameters and converts it into appropriate CloudFront API calls. This sort of approach has drawbacks, including the effort involved and issues keeping the CDK and the custom resource in sync. 

The one recommendation I do have is that if you're incrementally moving from CloudFormation to CDK, consider using the [cloudformation-include](https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html) module to include -- and manipulate! -- existing CloudFormation templates. This would allow you to "import" a Distribution already created in a CloudFormation template and make edits to it as you've described (albeit not with the exact same API).

I'm going to resolve this as at this time, this isn't a feature request I think we would consider for the "core" CDK; of course, you're free to build it and publish it as a custom construct. (Let me know if you do!)

**Comment by godacre** [comment]
Hey @njlynch, I've spent the best part of today developing 99% of a custom resource to handle the scenario of updating a CloudFront distribution in place and unfortunately despite overcoming hurdles, I've reached an impasse.

To update a CloudFront distribution to include a Lambda@Edge integration via Lambda & SDK, [it is required to configure the role trust-relationships](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-permissions.html) of service principals: ["lambda.amazonaws.com","edgelambda.amazonaws.com"].

The issue here is that the [CustomResourceProvider](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CustomResourceProvider.html) construct only allows you to add identity-based policy statements to the Lambda function and not make any amendments to the trust-relationships. https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CustomResourceProvider.html#policystatements

I'm not sure if you have any sight over whether this functionality is part of any CDK or custom resource roadmap but unfortunately I'm going to have to abandon CDK in this use case for something else for now.

Thanks in advance

**Comment by grutt** [comment]
So, looping in here with the same problem.

I was hopeful that behaviors would be treated similar to a record for Root53 (i.e. an ARecord) In this case, the ARecord belongs to the sub-stack. Unfortunately there is no equivalent construct for Behavior or Origin on CloudFront.

Am I correct that this established design pattern would not work for CloudFront since Origin and Behaviors are not referenceable resources or is there a way we can hack this together?
