### ISSUE TITLE
Create L2 for SSM

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#1257]
There is currently no L2 constructs for SSM.

**Comment by akkaash** [comment]
In case this isn't being actively worked upon, I can possibly take a stab at this over the weekend.

**Comment by rix0rrr** [comment]
No one is working on this as far as I know.

**Comment by eladb** [comment]
That will be awesome @akkaash 

Make sure you read our [guidelines](https://awslabs.github.io/aws-cdk/writing-constructs.html) if you haven't already :-)

**Comment by akkaash** [comment]
Making progress here. I wanted to understand what's the stance on doing validation inside Constructs? Like for example, since TS only supports `number` which is floating point value and CFN spec expects an `Integer` type, is it safe to make these checks in the L2 constructs? I had the same concern in my PR #1221 

I assume below (from guideline) applies in this case, need someone to confirm this though:
> Good: Runtime check everything the type checker can’t enforce and fail early (error in the constructor).

**Comment by eladb** [comment]
Yes, you can add runtime checks in your L2s as you see fit, but I wouldn't over do it. For example, we usually don't verify that a `number` passed is an integer. The names of properties should be sufficiently clear for people not to make such mistakes, and if they do, they might get an error during deployment.

But generally, yes! runtime checks are good!
