### ISSUE TITLE
(events) please add an example for every supported target type

### ISSUE THREAD

**Issue by hugomallet** [aws/aws-cdk#12619]
Here is the current documentation :
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-readme.html
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-targets-readme.html
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events-targets.LambdaFunction.html

Add more examples... Or are we supposed to guess how to use every targets ?

I try to use rest api target which is available in event rules but it's not documented in cdk neither in cloudformation.
I give up... Now I try to use lambda target, hope I will guess properly how it works...

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
I've taken this FR to mean "please give more examples", as per your original title and request.

----------

However, adding more examples will not solve your original intent of:

> I try to use rest api target

Because as far as I can tell, we don't have an integration class for that, and I didn't know it was even possible.

If you would like to also file a feature request for that, please do so in a NEW ticket and add a link to the EventBridge documentation mentioning this even was a possibility.

**Comment by hugomallet** [comment]
Hi @rix0rrr ,

Thanks for correcting my english !
I was a bit lost in the aws documentation maze.

I misunderstood the AwsApi class. I though that it was for API Gateway (as described in cfn).
But in the end I found in the code source that it was a helper to call aws sdk functions.

Giving a short description and an example for every target would really help.

**Comment by hugomallet** [comment]
(the feature request: #12708)
