### ISSUE TITLE
(aws_cdk.cloudformation_include): add aws-cdk dependencies from "install_requires" as "extras_require"

### ISSUE THREAD

**Issue by vincentclaes** [aws/aws-cdk#12647]
as defined in a SO thread i authored: https://stackoverflow.com/questions/65815693/limit-the-installation-of-dependencies-defined-in-setup-py?noredirect=1#comment116390805_65815693 

if you add `aws_cdk.cloudformation_include` as a depency of your project, you will install all aws-cdk services libraries which results in a huge package with a lot of depencies that you do not use. 

### Use Case

for example when i only need to import a cloudformation that is composed of stepfunctions i only need the `aws-cdk.aws-stepfunctions` as dependency. all the rest of the aws-cdk libraries can be discarded, like this we end up with a slimmer package. 

### Proposed Solution

is it possible to make the installation of the aws-cdk depencies optional? 
For example we can include the core depencies in the setup.py in `install_requires`  and all the aws-cdk depencies in `extras_require`

like this we can do;
```
pip install aws-cdk.cloudformation-include[aws-cdk.aws-stepfunctions]
```
to just install the depencies that we need.

* [ v] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hi @vincentclaes ,

thanks for opening the issue. Unfortunately, we can't make the dependencies optional, because whether we need them or not depends on the contents of the template that is being included. So there's not much we can do here to alleviate this particular pain.

I'll note that we're currently working on releasing V2 of the CDK, which will change the modules. Instead of shipping many smaller modules separately, we will ship a single monolithic package containing all CDK libraries (including cloudformation-include). See [here for details](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0006-monolothic-packaging.md#summary).

Hopefully, that will make it less painful to use cloudformation-include in the future!

Thanks,
Adam
