### ISSUE TITLE
(aws-apigateway): Importing existing usage plan causes cfn update error

### ISSUE THREAD

**Issue by Ranjith072** [aws/aws-cdk#12686]
### Reproduction Steps
if you already have a apikey and usage plan in place for the api and with the(1.86.0)it will modify the usage plan a bit and while updating the cloudformation we will get the error as shown below:
![image](https://user-images.githubusercontent.com/57263575/105702252-cfc4eb00-5f0b-11eb-8817-b4b8d72cbaeb.png)
![image](https://user-images.githubusercontent.com/57263575/105702253-cfc4eb00-5f0b-11eb-9aa1-62198da13b18.png)

### What did you expect to happen?
it should not create any problem if i update the cloudforamtion as there were no breaing changes mentioned in the release for api gateway.

### What actually happened?

deployment fails with the error as mentioned above.

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :windows 10 
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hi @Ranjith072,

This took a minute to understand, in the future, please make sure that you follow the issue template guidelines for required information and issue title so that we can properly investigate.

As for the issue itself, there isnt enough information here for us to understand your problem. Could you please provide the code that is failing, and if possible, the actual error message from the CDK CLI.

At first glance, it appears you are trying to create two copies of the same resource in your stack

😸 😷
