### ISSUE TITLE
(aws-lambda) Layers older versions disappear when deploy a new version

### ISSUE THREAD

**Issue by jncheung** [aws/aws-cdk#12718]
When I try to update a new lambda layer version, the old version disappear

### Reproduction Steps

```
    const layer = new lambda.LayerVersion( stack, "my_layer", {
        code: lambda.Code.fromAsset(path.join(__dirname, "./path/to/lib/nodejs.zip")),
        compatibleRuntimes: [lambda.Runtime.NODEJS_12_X]
    });
    const lambda = new lambda.Function( stack, "my_lambda", { 
        runtime: lambda.Runtime.NODEJS_12_X,
        code: lambda.Code.fromAsset(`lambda_dir`),
        handler: "index.handler",
        environment: {
            some: env,
        },
        layers: [layer]        
    });
```

### What did you expect to happen?

I have versions 1 - n available to me in this layer

### What actually happened?

Only the recent deployed version available
![Screenshot 2021-01-27 at 11 22 25 AM](https://user-images.githubusercontent.com/30644696/105938208-17757f00-6092-11eb-868a-36f966c2de2d.png)

### Environment

  - **CDK CLI Version  :*1.86.0*
  - **Framework Version:**
  - **Node.js Version:** 12.19.0 -->
  - **OS               :*mac 10.15.7*
  - **Language (Version):**TypeScript (4.0.5) -->

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @jncheung,

From what I can tell, `LayerVersion` does not actually create a new version on each creation unless the `RemovalPolicy` is set to `RETAIN`. From what I can see, this is doable [with the L1 construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.CfnLayerVersion.html#applywbrremovalwbrpolicypolicy-options), but is not implemented in the L2.

Since this is expected behavior, but a pretty big gap, I tend to think this should be treated as a high-priority feature request. @nija-at, thoughts?

In the interim, your best workaround is to create an escape-hatch solution to expose `DeletionPolicy` for your layers, try something like this:

```ts
export class LayerVersionRetain extends LayerVersion {
  constructor(scope: cdk.Construct, id: string, props: LayerVersionProps) {
    super(scope, id, props);

    const ver = this.node.defaultChild as CfnLayerVersion;
    ver.applyRemovalPolicy(RemovalPolicy.RETAIN);
  }
}
```

Lmk if that helps for now!

😸 😷

**Comment by jncheung** [comment]
@NGL321 I did some similar thing using `s3-asset` ytd but ur workaround is way more simpler and efficient.

I decided to follow your recommendation. thanks.
