### ISSUE TITLE
(cli): deploy stack with --parameters option specifying stack is ignored (MyStack:Parameter="Value")

### ISSUE THREAD

**Issue by markussiebert** [aws/aws-cdk#12759]
When using the cdk deploy option ```cdk deploy '*' --parameters MyStack:MyParam=MyValue``` the parameter will be ignored.

### Reproduction Steps

1. Create a multi stack application, where you use a parameter in only one of the multiple stacks.
2. Use the option ```cdk deploy '*' --parameters MyParam=MyValue``` will fail, because only one stack needs the parameter:
```Parameters: [MyParam] do not exist in the template```
3. Use the option ```cdk deploy '*' --parameters MyStack:MyParam=MyValue``` will fail, because the stack needing the parameter says: 
```The following CloudFormation Parameters are missing a value: MyParam```

### What did you expect to happen?

I expected that cdk can handle passing a parameter to only one stack. This behaviour is described here: https://docs.aws.amazon.com/cdk/latest/guide/parameters.html

### What actually happened?

you can only pass parameters to all, or no stack

### Environment

  - **CDK CLI Version  : 1.79.0**
  - **Framework Version: 1.79.0**
  - **Node.js Version: 12.18.4**
  - **OS               : mac**
  - **Language (Version): TypeScript** 
--- 

This is :bug: Bug Report

**Comment by Jerry-AWS** [comment]
To me, this feels like it should be a warning instead of an error.

**Comment by master7811** [comment]
Huh? For me I think it should work as described in the documentation. Even nowing parameters are somehow deprecated, it is the only way getting secrets into custom resources.
So I consider this as a bug.

**Comment by mitchboulay** [comment]
Hi, I'm getting this also. I am building a parameters argument and passing it to the CLI in Github actions. I get the error "CdkStack failed: Error: The following CloudFormation Parameters are missing a value: uploadbucketname"

**Comment by markussiebert** [comment]
still not fixed?

**Comment by tdluk** [comment]
Any updates on this? I'm having the same problem.

**Comment by nickyshankar** [comment]
Any updates on this? I'm having the same problem.

**Comment by SankyRed** [comment]
It appears that the reported issue has been resolved. The version in use, which is v1, is deprecated. I conducted tests on the feature utilizing version [v2.138.0](https://github.com/aws/aws-cdk/tree/v2.138.0). During testing, I replicated the scenario by creating multiple stacks, with only one stack necessitating parameters. Subsequently, I executed the deployment of all stacks using the command `cdk deploy --all --parameters StackWithParameter:BucketName=uploadbucket3456`, and the deployment proceeded successfully. As a result, I am closing the issue. If you have any further inquiries or concerns, please feel free to reach out.

**Comment by SankyRed** [comment]
I have recreated a similar scenario comprising multiple stacks, with one stack necessitating parameters that can be passed on during the deployment.

Steps taken to check if the issue works:
```
> cdk ls // listing stacks
- MultiStackCdkAppStack
- StackWithoutParameter
- StackWithParameter
```
Of the list of the stacks displayed above  `StackWithParameter` requires `bucketName` as the parameter and if not passed on while deploying we have a `default` set as well.

Running `cdk deploy --all` or `cdk deploy '*'`. Deploys all the three stacks with the default bucket name.

Running `cdk deploy '*' --parameters StackWithParameter:BucketName=uploadbucket3456` deploys the stacks successfully.
![Screenshot 2024-05-03 at 1 17 12 PM](https://github.com/aws/aws-cdk/assets/121981451/a80f0b4b-7863-4a93-ae85-b57d05857ef8)
![Screenshot 2024-05-03 at 1 57 53 PM](https://github.com/aws/aws-cdk/assets/121981451/47d31143-1503-4060-9b9e-0cf051e3ee6c)

Also, tested the feature with hierarchal structure and works successfully.

Steps taken to check if it works:
```
> cdk ls // listing stacks
- MultiStackCdkAppStack
- MultiStackCdkAppStack/StackWithoutParameter
- MultiStackCdkAppStack/StackWithParameter
```
Running `cdk deploy --all` or `cdk deploy '**'`. Deploys all the three stacks.

Running `cdk deploy '*' --parameters MultiStackCdkAppStack/StackWithoutParameter:BucketName=uploadbucket3456` deploys the stacks successfully.

Also tested it using the `--all` flag instead of `'*'` and that works as well.

As per the request it seems like we can deploy all stacks passing in parameters for specific stacks.

Environment
CDK CLI Version : 2.138.0
Node.js Version: 18.19.1
OS : mac
Language (Version): TypeScript

@markussiebert Can you please specify if the issue exists on your end?

**Comment by SankyRed** [comment]
@nickyshankar @tdluk Hello, I'm checking to see if the issue still persists on your end? Can anyone please confirm if the issue persists and also if you could please specify the environment it would be helpful.

**Comment by tdluk** [comment]
> @nickyshankar @tdluk Hello, I'm checking to see if the issue still persists on your end? Can anyone please confirm if the issue persists and also if you could please specify the environment it would be helpful.

Works fine for me. My problem was I was using the stack's construct ID instead of the stack name. This comment made things clear for me -> https://github.com/aws/aws-cdk/issues/12759#issuecomment-1481397047

**Comment by evzzk** [comment]
We've updated our documentation to provide clarification on this issue. For more information, see [Deploying with parameters](https://docs.aws.amazon.com/cdk/v2/guide/parameters.html#parameters_deploy) in the *AWS CDK Developer Guide*.
