### ISSUE TITLE
(aws-ec2): SubnetSelection not available in TypeScript

### ISSUE THREAD

**Issue by maria-jackson** [aws/aws-cdk#12848]
@AjkayAlan and I worked on this together.

[SubnetSelection](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.SubnetSelection.html) is usable in Python, but does not even show up as an option in TypeScript. I believe this was originally reported in https://github.com/aws/aws-cdk/issues/10484, which was closed with no resolution listed and a no workaround documented.

### Reproduction Steps

```TypeScript
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';

export class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpcName = 'vpc-123';
    const subnetGroupNameTag = 'tag-123';
    const subnetGroupName = 'tag-value-123';

    const vpc = ec2.Vpc.fromLookup(this, 'vpc', {
      vpcName: vpcName,
      subnetGroupNameTag: subnetGroupNameTag,
    });

    // Not completely sure of syntax, but there is no SubnetSelection even available.
    // was able to synth correctly with ec2.Vpc.fromLookup()
    const subnets = ec2.SubnetSelection({ subnetGroupName: subnetGroupName });
  }
}
```

### What did you expect to happen?

I expect that documented interfaces are available and that Python and TypeScript have the same functionality.

### What actually happened?

Can use other things from @aws-cdk.aws-ec2 in the same class, but @aws-cdk.aws-ec2.SubnetSelection doesn't appear to exist.
"Property 'SubnetSelection' does not exist on type 'typeof import("c:/mypath/node_modules/@aws-cdk/aws-ec2/lib/index")"

### Environment

  - **CDK CLI Version  :** 1.87.1
  - **Framework Version:** TypeScript??
  - **Node.js Version:** v12.18.3
  - **OS               :** Windows 10
  - **Language (Version):** TypeScript (4.1.3)

### Other

Combining https://github.com/aws/aws-cdk/issues/12047 and https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#selectwbrsubnetsselection, we believe this workaround meets our needs.

```
    const vpc = ec2.Vpc.fromLookup(this, 'vpc', {
      vpcName: vpcName,
      subnetGroupNameTag: subnetGroupNameTag,
    });
    const subnets = vpc.selectSubnets({
      subnetGroupName: subnetGroupName,
    });
```

--- 

This is :bug: Bug Report

**Comment by AjkayAlan** [comment]
For reference, this is the Python which actually works (using SubnetSelection, which doesn't work in TypeScript)

```python
from aws_cdk import aws_ec2

vpc = aws_ec2.Vpc.from_lookup(self, "vpc", vpc_name="vpc-123", subnet_group_name_tag="tag-123")
vpc_subnets = aws_ec2.SubnetSelection(subnet_group_name="tag-value-123")
```

**Comment by MatthewMooreZA** [comment]
`SubnetSelection` is an interface not a class.  I presume that jsii is converting the interface into a concrete type in Python, which is why it is a valid Python class (since Python uses duck typing rather than explicit interfaces.)

You can instantiate an object in Typescript that conforms to the SubnetSelection interface as follows:

```typescript
    const selection : ec2.SubnetSelection = {
      subnetGroupName: "xxxxx"
    };
```

**Comment by rix0rrr** [comment]
☝️ Thanks @MatthewMooreZA for explaining, exactly that.

Or leave out the variable and type declaration and just pass the value between braces `{ ... }` directly into the function.

TypeScript can do type derivations here (and automatically tell you which properties are required and which aren't from context), but Python requires that we construct a value from a constructor, so that we can check your types (etc) in the constructor call.
