### ISSUE TITLE
(s3): Cannot bundle CDK by Webpack due to embeded Lambda code for Custom Resource

### ISSUE THREAD

**Issue by yerzhan7** [aws/aws-cdk#12897]
Hi,

You know that CDK NPM package is too large for some environments (around 150MB overall).

I have to use Webpack in order to bundle/minimize/strip/nameMangle the library. (Minimizes to 6MB for my usecase)

However, some modules (e.g. resource notification handler for S3) have embedded raw NodeJS code inside. Those 
Lambdas often import `aws-sdk` from Lambda runtime. And webpack will mangle the import names, and put them somewhere else. This results in smth like `var r = new __webpack_require__(1234).S3()` instead of `const s3 = new (require('aws-sdk').S3)();`, which will obviously fail during deployment inside Custom Resource.

Example Lambda handler: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts

### Use Case

Be able to minimize CDK in tight environments.

### Proposed Solution

Make CDK bundlable by webpack. Make Lambda code as a raw string instead of code during build process.

I've tried various `exclude` options in webpack without any lack. If I turn of minimization, then everything is fine, but the bundle is too large for me.

### Other

Example `webpack.config.js`:

```
 module.exports = {
	   mode: 'production',
	   entry: './src/index.ts',
	   resolve: {
	     extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
	   },
	   output: {
	     libraryTarget: 'commonjs',
	     path: path.join(__dirname, 'build'),
	     filename: 'index.js',
	   },
	   target: 'node',
	   module: {
	     rules: [
	       {
	         test: /\.(ts|js)x?$/,
	         exclude: /node_modules/,
	         use: ['babel-loader'],
	       },
	     ],
	   },
	   externals: {
	     'aws-sdk': 'aws-sdk', // Used in CDK's internal CF Custom Resource Lambda handlers. No need to bundle.
	   },
	 };
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@yerzhan7 What if we just move that embedded code to a separate file and use `Code.fromAsset` instead of `Code.fromInline`? We wouldn't have to sacrifice dev experience that way. I would be all for that.

Apart from that, I'm not sure I fully follow the use-case. Are you trying to bundle your own library that depends on cdk packages, or are you trying to bundle the entire CDK? 

Also, what kind of breaking change did you imagine this change would incur?

**Comment by yerzhan7** [comment]
> @yerzhan7 What if we just move that embedded code to a separate file and use Code.fromAsset instead of Code.fromInline? We wouldn't have to sacrifice dev experience that way. I would be all for that.

Need to test that. Ideally, would be nice to embed code string inline during build process.

> Apart from that, I'm not sure I fully follow the use-case. Are you trying to bundle your own library that depends on cdk packages, or are you trying to bundle the entire CDK?

Yeah - something like CDK-As-A-Service Lambda that generates, deploys, and manages stacks based on some config.

**Comment by iliapolo** [comment]
> Ideally, would be nice to embed code string inline during build process.

You mean so we don't have to use assets? I don't mind embedding small snippets, but having an entire handler function would really hurt the development experience. btw - is webpack mangling the imports because they are inside the function body?  

> Yeah - something like CDK-As-A-Service Lambda that generates, deploys, and manages stacks based on some config.

Cool, I wonder though how did you get to 6MB, we have lambda layers in that are 30MB alone. Do you just not depend on those modules (`aws-s3-deployment`, `aws-eks`).

**Comment by iliapolo** [comment]
dont close

**Comment by suspiration** [comment]
@iliapolo I'm also running into this issue.  I tried turning minimization off, but is still erroring.  Do you mind sharing your webpack configuration which got it working?  I do not mind the large bundle size.
