### ISSUE TITLE
Add nodejs14 support for lambda functions

### ISSUE THREAD

**Issue by ihorfito** [aws/aws-cdk#12938]
https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/

**Comment by martzcodes** [comment]
This was added in https://github.com/aws/aws-cdk/releases/tag/v1.89.0

Which was released 3 hours after your issue (Pretty quick turnaround 😁) but closed by PR #12861 6 days before this issue

**Comment by NGL321** [comment]
Thanks for the report @ihorfito, we always welcome these kinds of notes! In the future, if you mark it as `feature-request`, that will be a better indicator of a desired addition.

As for this in specific, @martzcodes nailed it! (thank you for the assist 🥇 ) I'm closing this out since support has been added.

😸 😷
