### ISSUE TITLE
(step-functions): Bug with `payloadResponseOnly` attribute of `LambdaInvoke`

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#12935]
There is an issue with `payloadResponseOnly` attribute of `LambdaInvoke` class.

### Reproduction Steps

```ts
const getRDSInstanceStatus = new tasks.LambdaInvoke(this, GET_RDS_INSTANCE_STATUS, {
            comment: 'Gets RDS Instance Status for FRS',
            lambdaFunction: rdsProvisioningHandler,
            payloadResponseOnly: true,
            resultPath: '$.output.FrsAfe3SetupStateMachine.GetRDSInstanceStatus',
            payload: sfn.TaskInput.fromJsonPathAt('$.input.FrsAfe3SetupStateMachine.ProvisionRDSInstance')
        });

```

### What did you expect to happen?

Expected: When this property is set to `true` it should only copy the response payload to the output instead of adding response metadata.

### What actually happened?

Actual: When this property is set to true, it distorts the function parameters defined in state machine.

Generated step function definition by CDK:

```json
"GetRDSInstanceStatus": {
      "Next": "Is RDS Instance Available?",
      "Retry": [
        {
          "ErrorEquals": [
            "Lambda.ServiceException",
            "Lambda.AWSLambdaException",
            "Lambda.SdkClientException"
          ],
          "IntervalSeconds": 2,
          "MaxAttempts": 6,
          "BackoffRate": 2
        }
      ],
      "Type": "Task",
      "Comment": "Gets RDS Instance Status for FRS",
      "ResultPath": "$.output.FrsAfe3SetupStateMachine.GetRDSInstanceStatus",
      "Resource": "arn:aws:lambda:us-east-1:711291995544:function:FrsRDSProvisioningHandler",
      "Parameters": {
        "0": "$",
        "1": "{",
        "2": "T",
        "3": "o",
        "4": "k",
        "5": "e",
        "6": "n",
        "7": "[",
        "8": "i",
        "9": "n",
        "10": "p",
        "11": "u",
        "12": "t",
        "13": ".",
        "14": "F",
        "15": "r",
        "16": "s",
        "17": "A",
        "18": "f",
        "19": "e",
        "20": "3",
        "21": "S",
        "22": "e",
        "23": "t",
        "24": "u",
        "25": "p",
        "26": "S",
        "27": "t",
        "28": "a",
        "29": "t",
        "30": "e",
        "31": "M",
        "32": "a",
        "33": "c",
        "34": "h",
        "35": "i",
        "36": "n",
        "37": "e",
        "38": ".",
        "39": "G",
        "40": "e",
        "41": "t",
        "42": "R",
        "43": "D",
        "44": "S",
        "45": "I",
        "46": "n",
        "47": "s",
        "48": "t",
        "49": "a",
        "50": "n",
        "51": "c",
        "52": "e",
        "53": "S",
        "54": "t",
        "55": "a",
        "56": "t",
        "57": "u",
        "58": "s",
        "59": ".",
        "60": "1",
        "61": "7",
        "62": "6",
        "63": "1",
        "64": "]",
        "65": "}"
      }
    }

```

### Environment

  - **CDK CLI Version  :**  ?
  - **Framework Version:** ?
  - **Node.js Version:** ?
  - **OS               :** ?
  - **Language (Version):** ?

### Other

Internal reference: V315985769

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
when `payloadResponseOnly` is used, the older implementation of Lambda invocations in Step Functions is instrumented under the hood. It does not allow the usage of Json path directly into the payload. We should add some validation to warn users when they attempt to use a path with `payloadResponseOnly`

The more recent implementation leverages the [service integration pattern](https://docs.aws.amazon.com/step-functions/latest/dg/connect-lambda.html) (which supports callbacks by waiting for task token) uses a resource of `arn:aws:states:::lambda:invoke` and allows the usage of Json Path in the payload.


The service integration pattern embeds the Lambda's response into a field called `Payload`. If you want to achieve the same result, rather than set the `payloadResponseOnly` to `true`, you can work around it by by setting `outputPath`: `$.Payload`

```ts
const getRDSInstanceStatus = new tasks.LambdaInvoke(this, GET_RDS_INSTANCE_STATUS, {
            comment: 'Gets RDS Instance Status for FRS',
            lambdaFunction: rdsProvisioningHandler,
            resultPath: '$.output.FrsAfe3SetupStateMachine.GetRDSInstanceStatus',
            payload: sfn.TaskInput.fromJsonPathAt('$.input.FrsAfe3SetupStateMachine.ProvisionRDSInstance')
            outputPath: `$.Payload`
        });
```

**Comment by marciocarmona** [comment]
The problem is not only happening with JSON path, it also happens with `TaskInput.fromText`.

e.g.:
```
        const test = new LambdaInvoke(stack, "Some Function", {
            lambdaFunction: new Function(stack, "Echo", {
                runtime: Runtime.NODEJS_12_X,
                handler: 'index.handler',
                code: Code.fromInline(
                    `
                    exports.handler = function(event, ctx, callback) {
                        callback(null, event);
                    }
                    `
                )
            }),
            payloadResponseOnly: true,
            payload: TaskInput.fromText('Hello world!')
        });

        console.log(test.toStateJson())
```
Generates this:
```
{
  End: true,
  Retry: [
    {
      ErrorEquals: [Array],
      IntervalSeconds: 2,
      MaxAttempts: 6,
      BackoffRate: 2
    }
  ],
  Catch: undefined,
  Type: 'Task',
  Comment: undefined,
  TimeoutSeconds: undefined,
  HeartbeatSeconds: undefined,
  InputPath: undefined,
  OutputPath: undefined,
  ResultPath: undefined,
  Resource: '${Token[TOKEN.863]}',
  Parameters: {
    '0': 'H',
    '1': 'e',
    '2': 'l',
    '3': 'l',
    '4': 'o',
    '5': ' ',
    '6': 'w',
    '7': 'o',
    '8': 'r',
    '9': 'l',
    '10': 'd',
    '11': '!'
  }
}
```

The problem is in the call to `FieldUtils.renderObject(this.props.payload.value)` here:
https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/@aws-cdk/aws-stepfunctions-tasks/lib/lambda/invoke.ts#L145-L150

`FieldUtils.renderObject` doesn't check if the value sent in is actually an object or not and just calls `recurseObject`:
https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-stepfunctions/lib/json-path.ts#L35-L42

`recurseObject` then iterates over that object, which in the case of a string `key` will be the index, and `value` the character:
https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-stepfunctions/lib/json-path.ts#L84-L110

At line 92 above it's creating a new object, so the whole thing ends mapped into an object.

**Comment by marciocarmona** [comment]
By the way, I also noticed the documentation for the InputType.TEXT mentions it can also be a JSON-encoded string:
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-stepfunctions/lib/input.ts#L72-L80

However that doesn't seem to work as expected too.

e.g.:
```
        const test = new LambdaInvoke(stack, "Some Function", {
            lambdaFunction: new Function(stack, "Echo", {
                runtime: Runtime.NODEJS_12_X,
                handler: 'index.handler',
                code: Code.fromInline(
                    `
                    exports.handler = function(event, ctx, callback) {
                        callback(null, event);
                    }
                    `
                )
            }),
            payload: TaskInput.fromText('{"json": "encoded"}')
        });

        console.log(test.toStateJson())
```
Output:
```
{
  End: true,
  Retry: [
    {
      ErrorEquals: [Array],
      IntervalSeconds: 2,
      MaxAttempts: 6,
      BackoffRate: 2
    }
  ],
  Catch: undefined,
  Type: 'Task',
  Comment: undefined,
  TimeoutSeconds: undefined,
  HeartbeatSeconds: undefined,
  InputPath: undefined,
  OutputPath: undefined,
  ResultPath: undefined,
  Resource: 'arn:${Token[AWS.Partition.8]}:states:::lambda:invoke',
  Parameters: {
    FunctionName: '${Token[TOKEN.860]}',
    Payload: '{"json": "encoded"}'
  }
}
```

Am I missing something or should I cut another bug for that?

**Comment by avbluisosorio** [comment]
I noticed something after getting a `null` as a response despite I was returning an object, and logging it to the std output with `console.log` to verify it was actually an object.

When the handler was synchronous, i.e. `export function handler() { return "foobar"; }`, I got `null` instead with `payloadResponseOnly=true` but, if I changed the function to be async, I got the expected string response.

In case that helps someone.
