### ISSUE TITLE
(certificatemanager): Certificate not been issue when dns name is passed by props

### ISSUE THREAD

**Issue by icaroNZ** [aws/aws-cdk#12951]
When passing a dnsName using props Certificate Manager fail

### Reproduction Steps

On this simple example the Certificate fails to be issued:

```
const domainNameApex = 'mydomain.xzy';

const app = new cdk.App();

const { hostedZone, certificate } = new SimpleAppStackDns(
  app,
  'SimpleAppStackDns',
  {
    env: { region: 'us-east-1' },
    dnsName: domainNameApex,
  }
);

import { Certificate, CertificateValidation, ICertificate} from '@aws-cdk/aws-certificatemanager';
import { IPublicHostedZone, PublicHostedZone } from '@aws-cdk/aws-route53';
import * as cdk from '@aws-cdk/core';

interface SimpleAppStackDnsProps extends cdk.StackProps {
  dnsName: string;
}

export class SimpleAppStackDns extends cdk.Stack {
  public readonly hostedZone: IPublicHostedZone;
  public readonly certificate: ICertificate;
  constructor(scope: cdk.Construct, id: string, props: SimpleAppStackDnsProps) {
    super(scope, id, props);
    const { dnsName } = props;
    this.hostedZone = new PublicHostedZone(this, 'SimpleAppHostedZone', {
      zoneName: dnsName, //<- here, if change to string work
    });
    this.certificate = new Certificate(this, 'SimpleAppCertificateManager', {
      domainName: dnsName, //<- here, if change to string work
      validation: CertificateValidation.fromDns(this.hostedZone),
    });
  }
}
```

However, as soon as I change from using the props to use the actual string, it works fine.

### What did you expect to happen?
If the Certificate and the PublicHostedZone the PublicHostedZone uses the props for the dns name:

`DNS Record Set is not available. Certificate is in FAILED status.`

If the Certificate is using a hardcoded string but not the PublicHostedZone uses the props for the dns name

`RRSet with DNS name _b5f97db91ab10b160679e5f0f653f4fc.mydomain.xyz. is
not permitted in zone mydomain.xzy.] (Service: AmazonRoute53; Status Cod
e: 400; Error Code: InvalidChangeBatch; Request ID: 31b3afde-7a20-4f70-8083-3
8e6ac8fe4ed; Proxy: null)`

### What actually happened?

I can see that the Route53 zone is created but not the CnameRecord, for the certificate manager, I also can see that the certificate is created but fail.
If instead the props I hardcode the dnsName (as indicate on the code) the route53 zone and the CnameRegister is created and the certificate is issued

### Others

After further investigation, it seems to be a general problem with the CDK, I try to create other services using a string props and they all fail, eg. CloudFront, Route53 and Certificate manager 

### Environment

  - **CDK CLI Version  :** 1.88.0 (build f65009b)
  - **Framework Version:**1.88.0
  - **Node.js Version:** v15.4.0
  - **OS               :** Mac 11.2 (20D64)
  - **Language (Version):** TypeScript 4.1.3

This is :bug: Bug Report

**Comment by njlynch** [comment]
I've edited the issue description to be slightly more readable. Posting the entire history of the CloudFormation deployment is typically not a necessary diagnostic tool.

Regarding using a hard-coded string versus passing in a hard-coded string as a property, I can't imagine what would cause an issue (nor can I reproduce). When you are passing in a property, are you doing it as shown above, or doing something like reading the property from a file, or as the output from another construct? Could you share the Route53 and ACM section(s) of the generated CloudFormation template from each approach? I am wondering if there is some kind of weird encoding issue impacting you here.

Is your domain registrar Route53, or some 3rd party? In general, I would recommend first creating/deploying the hosted zone, updating your name server(s), and then adding in the certificate. The certificate will fail to validate if your domain does not publicly resolve to the hosted zone, which can take a few hours after you've configured your name servers. That may be what's causing the validation to (initially) fail here, rather than the way the props are being handled.

> it seems to be a general problem with the CDK, I try to create other services using a string props and they all fail, eg. CloudFront, Route53 and Certificate manager.

Can you post another example? An S3 bucket is the classic "simple" construct. Can you post an example of what the full code looks like before/after using "string props" and what the synthesis looks like?

> RRSet with DNS name _b5f97db91ab10b160679e5f0f653f4fc.mydomain.xyz. is not permitted in zone mydomain.xzy.

I'm guessing this was just a typo when you anonymized the results, but I'll point out above that mydomain.**xyz** does not belong in a hosted zone of mydomain.**xzy**. If that part of the error message is accurate, it would certainly point to an issue.

**Comment by icaroNZ** [comment]
Hi Nick, the whole code is as per the code above, the props value comes from a constant `const domainNameApex = 'mydomain.xzy';` than I just use it as `const { dnsName } = props;`.
It is funny because the Route53 is creating with the correct value, so I would expect the dnsName to have the correct string
Also, I'm fully deleting the whole stack before each redeploys.

The CloudFormation template looks the same for both cases:
```
    "SimpleAppHostedZoneE74C3330": {
      "Type": "AWS::Route53::HostedZone",
      "Properties": {
        "Name": "mydomain.xzy."
      },
      "Metadata": {
        "aws:cdk:path": "SimpleAppStackDns/SimpleAppHostedZone/Resource"
      }
    },
    "SimpleAppCertificateManagerD5D830E8": {
      "Type": "AWS::CertificateManager::Certificate",
      "Properties": {
        "DomainName": "mydomain.xzy",
        "DomainValidationOptions": [
          {
            "DomainName": "mydomain.xzy",
            "HostedZoneId": {
              "Ref": "SimpleAppHostedZoneE74C3330"
            }
          }
        ],
        "ValidationMethod": "DNS"
      },
      "Metadata": {
        "aws:cdk:path": "SimpleAppStackDns/SimpleAppCertificateManager/Resource"
      }
    },
```
However, when I pass the props I never see the CName been created in Route53,  and the certificate manager fails instantly, while if instead of this `const { dnsName } = props;` I do this `const dnsName = 'mydomina.xyz;` I can see that the CName creates and the certificate stays in pending until I update the DNS records on name cheap.
About this, you are right was just a typo:
|>I'm guessing this was just a typo when you anonymized the results, but I'll point out above that mydomain.xyz does not belong in a hosted zone of mydomain.xzy. If that part of the error message is accurate, it would certainly point to an issue.

**Comment by icaroNZ** [comment]
I create a simple sample on my [GitHub account](https://github.com/icaroNZ/cdk-route52-with-certificate), if you look at the commit history the first commit where I have the string hardcode inside the class CdkRoute52WithCertificateStack it works fine, the second commit I pass via props and it fail as per above.

**Comment by njlynch** [comment]
You have the same typo in your GitHub example as you did above:

'icarolavrador.**xzy**':
https://github.com/icaroNZ/cdk-route52-with-certificate/commit/597943791d09241793f8d993fbdab941b1f1617a#diff-7af1c98b1dc52f8b651e67d5c6fb283d4da77b0fdd881070a3ce1d8e6daab7b0R7

'icarolavrador.**xyz**':
https://github.com/icaroNZ/cdk-route52-with-certificate/commit/597943791d09241793f8d993fbdab941b1f1617a#diff-9b79ad22424c61c9ca671613b55a01a53d4be9749978ced9ded2ed504358a28fR22

If the above is the code that you used, it explains why it worked the first time by not the second.

**Comment by icaroNZ** [comment]
Hi Nick, I see it now, I'm so sorry to waste your time as it was clearly my mistake. I'll close this issue. Thank you for all the help
