### ISSUE TITLE
@aws-cdk/aws-appsync: Cannot attach @cognito Directives with no groups specified

### ISSUE THREAD

**Issue by pfried** [aws/aws-cdk#12981]
When attaching a Directive to the GraphQL Schema using the code-first approach the `Directive.cognito()` requires one to attach at least one group:

    Cognito authorization requires at least one Cognito group to be supplied. Received: 0

But this should not be the case. `@aws_cognito_user_pools directive` does not require a group. If no group is specified it means allow all users authorized through cognito.

### Reproduction Steps

        import {
            Directive,
            ResolvableField
        } from "@aws-cdk/aws-appsync";

        api.graphqlAPI.addMutation('setStatus', new ResolvableField({
            args: StatusInput.definition,
            returnType: StatusType.attribute(),
            dataSource: setStatusDataSource,
            directives: [
                Directive.iam(),
                Directive.cognito()
            ]
        }));

### What did you expect to happen?

That the schema attaches the `@aws_cognito_user_pools directive` directive.

### What actually happened?

The `cdk deploy` returned the error:

    Cognito authorization requires at least one Cognito group to be supplied. Received: 0

### Environment

  - **CDK CLI Version**  : 1.89.0
  - **Framework Version:** : 1.89.0
  - **Node.js Version:**  v12.16.1
  - **OS               :** Windows 10
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by pfried** [comment]
For everyone struggling with this, adding a custom directive like

`directives: [Directive.iam(), Directive.custom('@aws_cognito_user_pools')],`

will attach the correct directive statement anyways.

@MrArnoldPalmer I tried to fix this in the code. But it is somehow a mess caused by this whole `@aws_auth` against `@aws_cognito_user_pools` when multiple are present mess. A quick fix would be to remove the error beeing thrown when 0 groups are passed, but this error is valid and needs to be checked in case it is the only directive when using `@aws_auth`. Also the whole string replacement is ugly. The statement can only be created in the `toString()` method as only there is enough information to build the correct statement.

IMHO The statements should be created by a more sophisticated function like `createStatement(modes)` and Authorization Directives and Subscription Directives should be put in their own Subclass which does not need to be public.

Any thoughts on that?

**Comment by MrArnoldPalmer** [comment]
@pfried I think I'm with you on this. We need a much smarter and sophisticated system for managing directive statements instead of this basic string interpolation. Separating authorization and subscription directives also makes sense with some common `BaseDirective` ancestor or something.

**Comment by BryanPan342** [comment]
Yeah I totally agree. I've been trying to implement a validator for the code-first approach and also ran into some problems with Directives. I remember writing the code for Directives and noting to myself that I would go back and add more to it, but then forgot to go back to working on it haha.

Originally, I implemented the string replacement because I wanted it to be easy for people to add the `cognito` directive without having to learn the difference between `@aws_auth` and `@aws_cognito_user_pool`.

I think instead of statically creating the statements, we should do it on runtime through the `toString()` and these statements can be called through a private `createStatements` function.

We would need something like

```ts
export class DirectiveBase {
  constructor(name: string, args: {[key: string]: number[] | string[] | boolean[] | number | string | boolean})
}
```

But even this isn't that robust...

I think we might need something that defines [argument definitions](https://spec.graphql.org/draft/#ArgumentsDefinition), but it would be for creating custom directives s.t. CDK also handles creating the declaration.

**Comment by BryanPan342** [comment]
Also i wonder if it would be okay to just only use `@aws_cognito_user_pool` as it offers everything an appsync developer might need?
