### ISSUE TITLE
(aws-stepfunction-tasks): EcsRunTask supports ecs.ITaskDefinition

### ISSUE THREAD

**Issue by kuwa0224** [aws/aws-cdk#13003]
`EcsRunTask` requires `ecs.TaskDefinition`  not `ecs.ITaskDefinition` as a property in props.
I would like to make it be acceptable `ecs.ITaskDefinition`.

### Use Case

I create and manage some ECS TaskDefinitions outside CDK.
I would like to create a StateMachine that run an ECS Task with this TaskDefinition, and manage that StateMachine by CDK.

However, `ECSRunTask` requires `ecs.TaskDefinition` as a property in props.
This means that TaskDefinition must be managed by CDK.

Therefore, I can't create a StateMachine by CDK.

This constraint is described on EcsRunTaskProps:

https://github.com/aws/aws-cdk/blob/f48ece421a2d105c4ee85cd832d8df221c602335/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-task.ts#L19-L26

Specifically, the following requires to be TaskDefinition:
- Check if defaultContainer exists ([here](https://github.com/aws/aws-cdk/blob/bfa1f18c32051cd0e90a003bbbe3e806063c2b8c/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-task.ts#L249))
- Check networkMode ([here](https://github.com/aws/aws-cdk/blob/bfa1f18c32051cd0e90a003bbbe3e806063c2b8c/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-task.ts#L253))
- Get family name ([here](https://github.com/aws/aws-cdk/blob/bfa1f18c32051cd0e90a003bbbe3e806063c2b8c/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-task.ts#L282))
- Make policyStatements from taskrole and taskExecutionRole ([here](https://github.com/aws/aws-cdk/blob/bfa1f18c32051cd0e90a003bbbe3e806063c2b8c/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/ecs/run-task.ts#L371-L374))

In my usecase, above does not have to be done, or `ITaskDefinition` is sufficient.

- Already checked if defaultContainer exists by myself.
- NetworkMode is fixed at `awsvpc`. beacause using Fargate
- Can get family name from parsing `ecs.ITaskIDefinition`'s taskDefinitionArn
- Not needs makePolicyStatements. i set my own role when instantiates stateMachine ([here](https://github.com/aws/aws-cdk/blob/f48ece421a2d105c4ee85cd832d8df221c602335/packages/%40aws-cdk/aws-stepfunctions/lib/state-machine.ts#L96-L101))

### Proposed Solution

`ECSRunTaskProps` must accept `ecs.ITaskDefinition`. Or create another Construct class.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@kuwa0224 - moving to accept `ITaskDefinition` would be a breaking change. The reason it was made `TaskDefinition` is because of the checks you've linked.

Some of them don't apply to the use case you've alluded to, but it does seem to be contingent on several pre-requisites, such as Fargate, using your own policy statements, etc. It's a sign that it's not a solution that can be universally applied.

I'm marking this issue as a `p2` as I think it's a valid request, but I'm not sure that there's enough friction with `TaskDefinition` as an input parameter. It is however dissimilar to our other constructs, and that bit is still jarring.

What do you envision another construct class would look like? Would users be responsible for all of the constraints themselves?
