### ISSUE TITLE
aws_lambda: when deploying the cdk there should be a way of not updating the lambda code.

### ISSUE THREAD

**Issue by dfonnegra** [aws/aws-cdk#13020]
Adding lambdas to a stack becomes a headache because the lambda Function requires the code a prior. CDK is supposed to be a language to write the infrastructure configuration and not what is going to be inside. It is like if to deploy an EC2 instance, it was required to have a server implemented. 

#### CodeBuild and CodeDeploy
1. Let's say I want to use CodeDeploy to smoothly deploy lambda functions. Well, if these lambda functions are defined inside the same stack, they will be deployed as soon as the CDK synthesizes the stack making CodeDeploy useless.
2. Same as before but with CodeBuild.
#### Speed
3. As every time that lambdas are deployed it requires to install deps, then the infrastructure deployment starts becoming slower and slower even if I just want to change one parameter of a service that has nothing to do with lambdas.
#### Easier to implement and understand.
4. As the infrastructure and the code are isolated, I can now deploy infrastructure, front-end, and backend independently. Think of the headache that causes knowing that your infrastructure changes might change your currently working code.

**Note.** Of course these all items could be solved with the resources available right now in AWS but the only thing I can think of right now is creating a different stack for the lambdas and connect it with the infrastructure stacks through the outputs. 

### Proposed Solution
Well, as I see that Code is a required cloud formation parameter, I would think about implementing a custom resource called DelayedFunction or EmptyFunction that ON_CREATE, creates a lambda function with a default empty code (Or just a hello world), then ON_UPDATE, updates all of the parameters and keeps the Code unchanged.

I'm not an expert in nodejs so I hope there is someone who is willing to work on this. If no, but you still consider that this is a good idea, I can go for it.

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @dfonnegra ,

thanks for opening the issue. This actually already exists, and is called `Code.fromCfnParameters()`: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Code.html#static-fromwbrcfnwbrparametersprops

> Let's say I want to use CodeDeploy to smoothly deploy lambda functions. Well, if these lambda functions are defined inside the same stack, they will be deployed as soon as the CDK synthesizes the stack making CodeDeploy useless.

No, that's not how it works (there will be a blue-green deployment performed, everything will work as you expect).

> Same as before but with CodeBuild.

This I don't understand, what do you want to do with CodeBuild?

> Well, as I see that Code is a required cloud formation parameter, I would think about implementing a custom resource called DelayedFunction or EmptyFunction that ON_CREATE, creates a lambda function with a default empty code (Or just a hello world), then ON_UPDATE, updates all of the parameters and keeps the Code unchanged.

You can do that yourself, today (pass the code to use an inline "Hello World!" when you first deploy the stack, then change it to be the actual code later, whenever you're ready). There's no reason to build a separate feature in the CDK for that I don't think.

**Comment by dfonnegra** [comment]
The main problem for me is that from my point of view I don't want to deploy my code when I deploy the infrastructure, and vice-versa... They should be independent.

And of course what you say about the "Hello world" might work... But imagine that I have 100 lambdas... Then every time I want to deploy a new environment, I have to set this in 100 lambdas and then restart.
Besides, that "Write a hello world and then remove it" would need to become part of the documentation, and only the developers that know the code will know how to do it.

Repeating myself a little bit. Imagine that to deploy an EC2 instance it was required to give a source code. Of course, there would be a way around it, but wouldn't it be a headache? Is it really necessary to deploy the code every time the infrastructure is deployed?

**Comment by skinny85** [comment]
> The main problem for me is that from my point of view I don't want to deploy my code when I deploy the infrastructure, and vice-versa... They should be independent.

This is philosophical discussion, and you'll find that the CDK has some very strong opinions on this matter. As do I 🙂. In fact, I would say that deploying infrastructure + runtime code together is the only safe way to operate your application.

Simple example: you add a new SQS queue that your existing Lambda now starts publishing message to. Now, if you deploy your runtime code first, your Lambda will try to publish to a non-existing queue, and it will fail - you've just taken down your service!

You have now introduces a very insidious and difficult to track assumption into your service - that the infrastructure deployment that adds the queue has to happen before your application code deployment. And what if there's a bug in the that infrastructure change, and it needs to be rolled back (after the application code has already been submited)? Again, you'll take down your service.

For those reasons, CDK strongly, strongly recommends deploying your infrastructure code and your application code together.

> Repeating myself a little bit. Imagine that to deploy an EC2 instance it was required to give a source code. Of course, there would be a way around it, but wouldn't it be a headache? Is it really necessary to deploy the code every time the infrastructure is deployed?

It's the Lambda service that requires your function to have code defined - it's not something the CDK is forcing on you. I think you're trying to fight against the way that service is designed to be used, and that's why you're running into friction.

**Comment by peterwoodworth** [comment]
Closing because Adam has appropriately responded to the issue and no further discussion has taken place
