### ISSUE TITLE
AWS CLI CONFIGURE

### ISSUE THREAD

**Issue by usmanbinnaeem** [aws/aws-cdk#13030]
Hi, Hope You all are doing well, need little help, I have created my IAM user and configured every thing fine, but still getting this error, **"Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment"** any body can help to know what I am doing wrong.
Regards: usman Naeem.

**Comment by peterwoodworth** [comment]
Hi @usmanbinnaeem,

Have you looked through the [prerequisites](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html#getting_started_prerequisites) to using the CDK?  Make sure you have `.aws/config` and `.aws/credentials` set up properly. 

Let me know if you have already done this and I will investigate further.

**Comment by usmanbinnaeem** [comment]
@peterwoodworth  thanks for your response, yes I have already done this configuration.

**Comment by peterwoodworth** [comment]
Hey @usmanbinnaeem,

After some looking it looks like there is already an open issue on the same topic [here.](https://github.com/aws/aws-cdk/issues/1656) Since this is a duplicate, I'll be closing this issue soon. Be sure to look through the issue I linked to see if any solutions there help you out, and if you still need additional help feel free to comment on that issue!
