### ISSUE TITLE
(lambda): fail on updating lambda code from image to zip

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#13037]
The deployment failed due to updating an existing lambda using container image as code to zip code. See below error in cloudformation event,

```
Please don't provide Handler or Runtime or Layer when the intended function PackageType is Image. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 580bca76-65b4-4085-8606-42b9fe7f0a58; Proxy: null)
```

### Reproduction Steps

1. create a lambda with container image as code
2. deploy the stack
3. update the existing lambda to use zip code(such as `PythonFunction`)
4. deploy the stack again

### What did you expect to happen?

The deployment with updated lambda success.

### What actually happened?

The deployment failed with error(see above for detail error).

### Environment

  - **CDK CLI Version  :** 1.88.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
I've tried this out and am seeing the same error message. This problem is not coming from the CDK, but rather either from CloudFormation or the Lambda service.

It seems like a limitation that a code based lambda function cannot be converted into an image based lambda function and vice versa.

You will need to contact the Lambda service team to get more details on this.

**Comment by nija-at** [comment]
I have been informed that this is a known limitation of Lambda. It does not allow changing package types.
