### ISSUE TITLE
(ec2): some Cfn class documentation missing synopsis

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#13065]
Issue reported by a customer at https://github.com/awsdocs/aws-cdk-guide/issues/311

These don't have synopses, but should.

https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-ec2/cfnvpnconnection.html

https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-ec2/cfnclientvpnendpoint.html

---

This is a 📕 documentation issue

**Comment by hyogyunbang** [comment]
Another one.
https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-elasticloadbalancingv2/cfnloadbalancer.html#aws_elasticloadbalancingv2_CfnLoadBalancer

**Comment by rix0rrr** [comment]
Honestly I think this is true for all `Cfn*` classes, OR for most of them because it depends on ordering.

It's because the tool we're using to generate the TypeScript docs gets confused when there's a `class` and a `namespace` with the same name.

I'm going to close this issue because it's a duplicate (though I'm too lazy to look up the original ticket right now), and also unlikely we'll address it. Our plan is to drop the TypeScript docs completely, since they also don't deal well with our plans for v2.
