### ISSUE TITLE
(core): Cfnmapping does not work with string assignments

### ISSUE THREAD

**Issue by adarsh-chauhan** [aws/aws-cdk#13098]
## :question: General Issue

[Cfnmapping](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnMapping.html) Does not work with environement argumemt for [Lambda](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#environment) or [Container](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinition.html#environment) Definition

### The Question

```
import core = require('monocdk');
import lambda = require('monocdk/aws-lambda');
import sqs = require('monocdk/aws-sqs');
import fs = require('fs');


export class LambdaCronStack extends core.Stack {
    constructor(app: core.App, id: string) {
      super(app, id);

      const common_file_dlq = new sqs.Queue(this, 'commonFileDLQ', {
        queueName: 'CommonFileDLQ',
        encryption: sqs.QueueEncryption.KMS_MANAGED,
        retentionPeriod: core.Duration.days(14)
    })

      const arun_map = new core.CfnMapping(this, 'ArunsMap',{
        mapping:{
            'us-east-1': {
                'source_queue': common_file_dlq.queueUrl
            }
        }
    })

      const lambdaFn = new lambda.Function(this, 'Singleton', {
        code: new lambda.InlineCode(fs.readFileSync('lambda-handler.py', { encoding: 'utf-8' })),
        handler: 'index.main',
        timeout: core.Duration.seconds(300),
        runtime: lambda.Runtime.PYTHON_3_6,
        environment: {
            temp: `${core.Fn.findInMap(arun_map,'us-east-1','source_queue').toString()}`
        }
      });
    };
}
  
const app = new core.App();
new LambdaCronStack(app, 'LambdaCronExample');
app.synth();
```
-->

### Error
```
learn.ts:31:40 - error TS2345: Argument of type 'CfnMapping' is not assignable to parameter of type 'string'.

31             temp: core.Fn.findInMap(arun_map,'us-east-1','source_queue')
```
 
### Environment

  - **CDK CLI Version:** 1.89.0 (build df7253c)
  - **Node.js Version:** v12.18.0
  - **OS:** macOS Catalina 
  - **Language (Version):** TypeScript (4.1.2)

### Other information
Found other issues as well which i think are related but not sure.
[issue1](https://github.com/aws/aws-cdk/issues/1756)
[issue2](https://github.com/aws/aws-cdk/issues/10228)

**Comment by peterwoodworth** [comment]
Hey @adarsh-chauhan,

The `findInMap` function takes in three strings as its parameters as you can see [here.](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Fn.html#static-findwbrinwbrmapmapname-toplevelkey-secondlevelkey). You can `cdk synth` and check the `Mappings` section to see what you'll be able to return with the `findInMap` function. So instead of using the variable `arun_map` you will want to use the logical name you gave it: `ArunsMap`. Also, you won't have to `.toString()` the `findInMap` function because it already returns a string.

Another thing to note: mappings attributes can only contain alphanumeric characters, so you'll have to rename `source_queue` because of the underscore.

Hope this helps! Let me know if you run into any more issues.

**Comment by adarsh-chauhan** [comment]
@peterwoodworth Thank you peter. I guess i wasn't paying attention. 
It works like you said or i could have just done

```
arun_map.findInMap('us-east-1','sourcequeue')
```
