### ISSUE TITLE
(elasticloadbalancingv2): adding a new certificate to a multi-certificate listener will lose old extra ceritifactes

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#13150]
If you try to add a new certificate to a listener that has already at least one extra certificate (i.e. one in addition to the main certificate), the old extract certificate will be lost by the end of update operation.

### Reproduction Steps

(In my case, it happened like this:)
1. Create an HTTPS listener with two certificates; `foo.com` (main one) and `bar.com` (additional one) stack and deploy it.
2. Change the code and add a new certificate; `baz.com` to the list and deploy it.

### What did you expect to happen?

The listener should keep one main certificate and two extra certificates.

### What actually happened?

The old extra certificate (`bar.com`) is gone.

### Environment

  - **CLI Version      :** 1.89.0
  - **Framework Version:** 1.89.0 (build df7253c)
  - **Node.js Version:** v15.5.1
  - **OS               :** Mac OS X 11.2
  - **Language (Version):** typescript ~3.8.2

### Other

Please note that, according to my findings from AWS support, this seems to be a bug/feature of CloudFormation. Interestingly, even though the `Certificates` field is of type `Array`, the documentation says: _You can specify one certificate per resource._
If my understanding is correct, CDK should not put all additional certificates into one `AWS::ElasticLoadBalancingV2::ListenerCertificate` resource. It should be one `AWS::ElasticLoadBalancingV2::ListenerCertificate` resource per each additional certificate.

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report -- and for including the response from support!

I suspect the answer is to alter the below code block:
https://github.com/aws/aws-cdk/blob/96630934942b437f2cad1371c8a01bdb2e92cf38/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L266-L271

Rather than creating one `ApplicationListenerCertificate` for the remainder certificates, it appears one `ApplicationListenerCertificate` needs to be created **per** certificate.

This should be a relatively straightforward change; PRs welcome if anyone has the time to go after it!

**Comment by andreialecu** [comment]
@njlynch: I attempted to fix this in #13332
