### ISSUE TITLE
(aws-ecr-assets): DockerImageAsset.repository is not really a repository (e.g. grants result in a no-op)

### ISSUE THREAD

**Issue by JFox** [aws/aws-cdk#13327]
When adding pull permissions as stated in the [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecr-assets-readme.html#pull-permissions), the result is a no-op

### Reproduction Steps

```javascript
const myAsset = new DockerImageAsset(this, "MyAsset", {
  directory: path.join(process.cwd(), "docker", "my-asset"),
});
myAsset.repository.addToResourcePolicy(
  new PolicyStatement({
    principals: [
      new AccountPrincipal("123123123"),
      new AccountPrincipal("78667867"),
    ],
    actions: [
      "ecr:GetDownloadUrlForLayer",
      "ecr:BatchCheckLayerAvailability",
      "ecr:BatchGetImage",
    ],
  }),
);
```

### What did you expect to happen?

ECR repo's permissions policy gets updated according to the code

### What actually happened?

Nothing

### Environment

  - **CDK CLI Version  :*1.86.0*
  - **Framework Version: *1.86.0*
  - **Node.js Version: *v13.8.0*
  - **OS               :*MacOS Catalina*
  - **Language (Version): *TypeScript (3.9.6)*

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@JFox thanks for describing your use case.

I believe this use case can be addressed using the proposed [ECR deployment](https://github.com/aws/aws-cdk/issues/12597) feature, which will allow you to define a separate ECR repository (which you can fully control) and deploy docker image assets to it. If that's the case, please +1 that issue so we can prioritize it (copy @ericzbeard).

The new bootstrapping mechanism (which will be the default in 2.0), all docker image assets will use the same ECR repository, which is created during `cdk bootstrap`. To that end, it won't be possible to modify the asset repository's permissions directly, which is why `addToResourcePolicy` doesn't work in this case.

I think we should remove the `repository` property from `DockerImageAsset` because it may send the wrong signal about what you can do with that repository (like granting permissions).

**Comment by JFox** [comment]
Thanks for the clarification. I may add that the grants and permissions reference to the assets repository are removed as well.

**Comment by eladb** [comment]
Reopening this to track the deprecation of the `repository` property from `DockerImageAsset`.
