### ISSUE TITLE
codebuild: package dependencies are not found

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#13339]
The install command `npm ci` results in the following errors for a lot of modules:

`node_modules/@aws-cdk/aws-apigateway/lib/api-definition.d.ts(2,28): error TS2307: Cannot find module '@aws-cdk/aws-s3-assets' or its corresponding type declarations.`

This happens for every dependency, f. ex.: `constructs` or `@aws-cdk/aws-elasticloadbalancingv2`

### Reproduction Steps

Setup a simple pipeline project and try to run the pipeline. 

### What did you expect to happen?

`npm ci` works

### What actually happened?

error TS2307

### Environment

  - **CDK CLI Version  :*1.91.0*
  - **Framework Version:*1.91.0*
  - **Node.js Version:** v13.8.0
  - **OS               :*macos 11*
  - **Language (Version):** TypeScript (4.2.2)

### Other

As a workaround an update of the install command solves the issue:

`npm i -g npm && npm ci`

But it would be better to have an official solution

--- 

This is :bug: Bug Report

**Comment by erudisch** [comment]
Hello

I think the problem is that i upgraded npm locally to version 7.6.0 which creates the `package-lock.json` with the `lockfileVersion> 2` instead of `lockfileVersion: 1`. that's why the dependencies could not be found

Are there plans to update it in cdk too?

**Comment by skinny85** [comment]
Hey @erudisch ,

I think the problem is that the `npm` you're using in CodeBuild and locally are different. I think until CodeBuild releases an image that has `npm` in version 7 installed, your solution of going `npm install -g npm` looks good to me.

**Comment by g-wozniak** [comment]
I've used yarn and npm (the precise same version used to build package.lock in both envs) and yarn.lock and the issue still occurs. 

The behaviour is different for `npm` and `yarn` but in both cases there are missing binaries in `node_modules/.bin`. `npm` seems not installing all the packages (installed 360 instead of 1200). 

When I took the artifact generated by the CodeBuild I wasn't able to build it on my local with the same error as in the pipeline. When retried `yarn install` (or `npm install` for a different installation) it worked brilliantly.
