### ISSUE TITLE
aws-lambda: Any way to add reservedConcurrentExecutions parameter conditionally

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#13349]
I have one requirement where we have to add reservedConcurrentExecutions on lambda based on environment(dev/test/prod).
I am reading environment name from *CfnParameter*
Is there any way in CDK to achieve this ?

### Environment

  - **CDK CLI Version:** 1.67
  - **Module Version:** 
  - **Node.js Version:** 12
  - **OS:** 
  - **Language (Version):**

**Comment by devendra-kumar1** [comment]
@nija-at any comment on this ?

**Comment by devendra-kumar1** [comment]
@nija-at could you please update on this ?

**Comment by devendra-kumar1** [comment]
@skinny85  can you please help me here. I tried using cfnFunction props but saw **reservedConcurrentExecutions** has not of type **IResolvable** so not able to apply intrinsic function.
Sample code i used :

**Comment by skinny85** [comment]
You need the [`Token.asNumber()` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Token.html#static-aswbrnumbervalue):

```ts
        const condition = new cdk.CfnCondition(this, 'ReservedConcurrencyCondition', {
            expression: cdk.Fn.conditionEquals('envName', 'test'),
        });
        const cfnFunction = func.node.defaultChild as lambda.CfnFunction;
        cfnFunction.reservedConcurrentExecutions = cdk.Token.asNumber(cdk.Fn.conditionIf(condition.logicalId, cdk.Aws.NO_VALUE, 20));
```

(I assume you wanted to use `Aws.NO_VALUE`, not `undefined`, as the latter would result in literally nothing being output in the template, which would result in an invalid template (`Fn::If` with 2 arguments instead of 3))

**Comment by devendra-kumar1** [comment]
Thanks a lot @skinny85. It is working fine :)
