### ISSUE TITLE
(aws-lambda-event-sources) there is no ALB as Event Source

### ISSUE THREAD

**Issue by mkaracullu** [aws/aws-cdk#13395]
Even if I can add ALB as trigger to any lambda function, I couldn't find ALB on aws-lambda-event-sources.

There is a workaround posted in [stackoweflow](https://stackoverflow.com/questions/60031722/alb-trigger-lamda-function-missing-permission-cdk) however, I don't see ALB attached as trigger to my Lambda Function.

Is there any way to add ALB as trigger to Lambda Function with CDK?

Thanks.

**Comment by msimpsonnz** [comment]
ALB is able to trigger Lambda directly without the need for Event Source Mapping which is why it is not supported here or in CloudFormation.
The posted link is not a workaround, the supported way is to use ALB targets, see “Using Lambda as Target” section from here
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-elasticloadbalancingv2-readme.html

**Comment by nija-at** [comment]
Closing this issue thanks to @msimpsonnz response.
