### ISSUE TITLE
(aws-ecs): Open all UDP ports

### ISSUE THREAD

**Issue by mostafafarzaneh** [aws/aws-cdk#13396]
I have an application that sends and receives video over Webrtc. 
my application is running on Fargate. Since Fargate only supports `awsvpc` network type and does not support `host, I need to port map all UDP ports(or at least a huge range of UDP ports). Is it a good practice to do so? Is there any other alternative?

One alternative that I can think of, is to use EC2 instead of Fargate. But because my application is in Appmesh, the network type must be `awsvpc`.

**Comment by mostafafarzaneh** [comment]
I just tried to map port range 20000:25000 and got the following error:
`Invalid request provided: Create TaskDefinition: Actual length: '293371'. Max allowed length is '65536' bytes.`

**Comment by peterwoodworth** [comment]
I'm sorry no one has replied to this yet @mostafafarzaneh,

You seem to be struggling to work around what [CloudFormation provides](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-networkmode), which is what the CDK uses under the hood. I'm not very familiar with your specific requirements, or using these services. Since nothing in your question is CDK specific - I recommend reading through ECS documentation, or looking for support from ECS experts 🙂
