### ISSUE TITLE
(cdk-dynamoDB): DynamoDB Table - Cannot set region explicitly, Region inherited from CDK Stack Region

### ISSUE THREAD

**Issue by antawad** [aws/aws-cdk#13478]
Hello,

This is a suggestion to improve our cdk documentation for DynamoDB. I think it is worth mentioning on this page (https://docs.aws.amazon.com/cdk/api/latest/docs/aws-dynamodb-readme.html) that the cdk provisions the dynamo table based on the **cdk stack region**, and it is different from the replicationRegions property. 

In other words, you can't explicitly set the region for a table, it is inferred from the cdk stack region. 

I found this information on an external blog. Are you able to confirm this info? I can also help with a PR if you point me in the right direction.

Thank you!

---

This is a 📕 documentation issue

**Comment by RomainMuller** [comment]
Hey @antawad - the region locality of resources is a property of our provisioning engine (CloudFormation).

I see there could be some potential for confusion with respects to `replicationRegions` - is the problem here that you'd have mis-interpreted it as including *all* regions the table is present in (including the deploying stack's)?

Anyhow - the documentation for `replicationRegion` is specified here:
https://github.com/aws/aws-cdk/blob/77a6268d696dc0f33fbce4c973f45df29da7aef5/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L214-L220

And the README.md source is there: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-dynamodb/README.md

If you have ideas how the documentation could be phrased better - feel free to have a stab at it!

**Comment by antawad** [comment]
Hi @RomainMuller, 

Thanks for the response, it makes total sense. 

It was a misinterpretation for the "replicationRegions" property on my side. I thought it was the target deployment regions including the region for the deployment stack.

To be honest reading the documentation again after 2 weeks, it makes perfect sense.

Closing this for now.
