### ISSUE TITLE
(all of them): The docs are broken yo!

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-cdk#13495]
The Typescript docs from the 1.92.0 release package do not work.

![screenshot](https://i.imgur.com/qCx3Bs2.png)

This was discovered by @webdog. I don't read the docs, I just complain in the Issues.

---

This is a 📕 documentation issue

**Comment by peterwoodworth** [comment]
Hmmm the typescript docs seem to be working for me, which link are you using? I'm using this link: https://docs.aws.amazon.com/cdk/api/latest/typescript/api/index.html

**Comment by richardhboyd** [comment]
>from the 1.92.0 release package

https://github.com/aws/aws-cdk/releases/tag/v1.92.0

**Comment by peterwoodworth** [comment]
You're right, thank you for letting us know. 

I went back to see if this affected any other releases, and found that you will get this same behavior on the 1.0.0 release package! 

I'll pass this along to the right person so that Typescript docs of previous releases are easier to navigate in the future. In the meantime you can look through the files in the /api folder to look at individual pages, or the link I posted above works great for the latest version.

**Comment by peterwoodworth** [comment]
Update: We have plans to take care of this issue, however we have no time in the near future to take care of it. You can use one of the workarounds I described above before a solution is implemented. Thank you again for bringing this to attention!

**Comment by kellertk** [comment]
@peterwoodworth this looks like it might be because of dotnet/docfx#4077. Installing docfx and serving up the documentation with `docfx serve` renders the TOC correctly in at least the 1.92.0 release package.
