### ISSUE TITLE
(aws-ecs): Fargate does not need port map

### ISSUE THREAD

**Issue by mostafafarzaneh** [aws/aws-cdk#13524]
I run [iperf](https://iperf.fr/) on an ECS Fargate service that listens to port 9000.
The task has a public IP.
The task definition **does not** have any port map!!
The task security group allows inbound port 9000 and all outbound traffics.

I expected that I would have to map port 9000 in the task definition but it seems it does not need to map ports in `awsvpc` on Fargate.

**Comment by SoManyHs** [comment]
Hi @mostafafarzaneh, 
Correct, you do not need to specify a host port when using Fargate/awsvpc networking (See: [Port Mapping](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html))

This doesn't appear to be a bug report -- could you clarify your question/problem? Does your Fargate service have the expected ingress?

**Comment by mostafafarzaneh** [comment]
Thanks, @SoManyHs 
I saw the link you provided. From what I understand, it says that you need to do a port map but do not need to specify a host port and just need to specify a container port.
What I did was I did not write any sort of port map regardless of container port or host port AND I can connect to my service without any port map whatsoever. The only thing I did was open ingress ports in the service security group.

**Comment by dror-g** [comment]
This issue still exists, and it's a problem.
You can specify `containerPort`, but it seems ANY container port is mapped to the host, very much like Docker host networking `--net=host`.  

Any container can reach any other container in same task on `localhost:<any-port>`, 
All ports are **exposed to world** if public-IP is assigned and Sec Group allows them.
Essentially, there is no isolation.

Why specify a `containerPort` at all even...

**Comment by pahud** [comment]
Looking and validating now.

**Comment by pahud** [comment]
@dror-g 

OK let me explain a little bit.

When an ECS service with fargate task is running with awsvpc mode with an Nginx container running and binding on tcp:80, the following will be happening:

1. An elastic network interface (ENI) with a private IP address within your VPC will be assigned to that task. Let's assume the IP is `172.31.12.152`.  That nginx would be listening on localhost:80 as well as 172.31.12.152:80.
2. In `awsvpc` mode, a dynamic assigned host port will be mapping to that ENI on port `80`.
3. OK, now it's where a Security Group comes in:

Let's consider the following scenarios:

1. If your fargate service is `internal VPC facing` only:
   a. do not specify [assignPublicIp](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateService.html#assignpublicip) when you create the FargateService so no public IP would be assigned to your fargate task.
  b. Your fagate task should be placed in the private subnets instead of the public subnets so there's no inbound traffic from internet could access that task.
  c. You still need a security group to protect your task on `172.31.12.152:80`.  Generally you can configure to allow all VPC CIDR to access that TCP:80 but of course you may scope down the source if you like.
  
2. Now if your fargate service is external facing:
   a. The best practice is still disabling  `assignPublicIp` and leave the fargate tasks in the private subnet. This ensures no traffic from internet could directly access your ENI on `172.31.12.152:80`.
  b. You still need `awsvpc` and `portMapping`. This ensures a dynamic host port would be generated and exposed that maps to ENI:80.
  c. Now we need a security group that allows all traffic from an Elastic Load Balancer(generally ALB or NLB) to access that fargate task ENI. The source would be the load balancer while the target would be any port of that ENI. This ensures only external traffic ingesting through the load balancer could access that fargate task. The traffic flow would be like:
  
  [external] --> [ALB:80 or 443 with Security Group] --> [fargate task awsvpc mode dynamic host port] --> [ENI:80] --> Nginx
  


I will add some CDK sample for your reference later.

**Comment by dror-g** [comment]
Ok please note though:
1. In the sample I provided, nginx portMapping is set to port `5000`, and yet I am able to reach it on port `80`, as nginx is set to listen on 80 by default in `nginx.conf`.  I did not set a portMapping for port 80, and yet... 
According to your explanation the host port 80 should **not** be mapped to the ENI, and indeed if you look in port mappings, it's not listed. Still reachable though (from world AND from other containers in task).

2. I am reaching the unbound port 80 using the public IP assigned. 

3. Running a task without public IP blocks all internet access. Inbound and outbound. That's not an option, as we usually query APIs, download packages, or host Nginx web servers. 
They should be exposed on bound port only. Not every port the app happens to listen on.

(There's probably a way to use Internet Gateway or something to route traffic to internal AWS IPs, I'm sure. But ain't nobody got time for that, it costs extra (a lot of extra), and we'll end up in the same spot probably if all ports are reachable regardless of binding).

Please don't bother with CDK examples. I suggest you run the task example I pasted above and we try to understand why port 80, which is not mapped, not bound to ENI - is reachable on public IP if not blocked by sec group.

**Comment by pahud** [comment]
@dror-g 


Let me rephrase it.

In `awsvpc` with EC2 mode, to avoid host port conflict when we define portMapping with container port:5000, a dynamic host port would be assigned to map that ENI:5000.

However, in `awsvpc` with Fargate, as each fargate has its own ENI and there would no host port conflict, when you assign container port:5000 there would be a 5000:5000 mapping created. No dynamic port would be assigned.

>1. In the sample I provided, nginx portMapping is set to port 5000, and yet I am able to reach it on port 80, as nginx is set to listen on 80 by default in nginx.conf. I did not set a portMapping for port 80, and yet...
According to your explanation the host port 80 should not be mapped to the ENI, and indeed if you look in port mappings, it's not listed. Still reachable though (from world AND from other containers in task).

In fargate task with awsvpc mode, if your container is binding 0.0.0.0:80 (nginx in your case):
- it would be exposed to the ENI private IP at port 80, regardless the portmapping. ENI:80 would always be exposed.
- now if you configure containerPort: 5000 in your portMapping, as this is a fargate task, per my description above an additional 5000:5000 PortBindings should be created. But as your nginx is actually NOT listening on TCP:5000, that PortBind would not ingress any traffic to your nginx container. But bear in mind that ENI:80 is still exposed there and you still need a security group to protect that.

>2. I am reaching the unbound port 80 using the public IP assigned.
>Running a task without public IP blocks all internet access. Inbound and outbound. That's not an option, as we usually query APIs, download packages, or host Nginx web servers.
>They should be exposed on bound port only. Not every port the app happens to listen on.

Running a task without public IP behind the load balancer is still the best practice or option. As it resides in the private subnets with NAT, it has egress to access internet or any other destination so "query external APIs" should not be a problem. Downloading packages is absolutely supported as it's in the private subnet with NAT egress. Hosting nginx web services? Your fargate tasks are running behind ALB or NLB with great protection and you could enable AWS WAF on your ALB if you like plus ECS service auto scaling capabilities while running a single public IP exposed fargate task in the public subnet would not give you any scalability or projection like that.

**Comment by dror-g** [comment]
> I guess when you define `EXPOSE 80` in the Dockerfile, it would essentially expose on ENI:80 regardless your portmapping configuration and you would always need a scoped security group to protect that.

Thanks @pahud , this might be the reason a port not defined in portMapping is available. Nginx is also capable of listening on multiple ports so one might not even realise the issue exists as defined portmap will also work.

And while I for one do use SGs (and route traffic through ALB + WAF) - there might be a security vulnerability here if a user uses public IP and is unaware of a container exposing a port.
This is actually very likely with multi-stage Docker builds and starting `FROM` an un-inspected image.
(I didn't even know nginx img did this is as I use `nginx- otel` image builds `FROM nginx:%%NGINX_VERSION%%`, and has no `EXPOSE` of its own !)

I'd recommend looking into this, though I'd agree that disabling `EXPOSE` directives is also destructive, but there might be ways to mitigate, and the scope of network access for a container might be wider than most users believe.

Cheers

**Comment by pahud** [comment]
Thank you @dror-g for bringing this up to our attention.

I believe the best practice is always scope down your security group as a guardrail for any docker images either built from internal or external and always place your ecs tasks in private subnets with `assignPublicIp` disabled behind a load balancer with yet another scoped SG on that LB. You probably can't control the Dockerfile from the images you use or inherit in the multi-stage image building but the SG is something you have the full control. When you explicitly only allow one specific port in your SG from a very scoped source, you would not really worry about how those `EXPOSE` statements would bother you. So I would callout the importance of the security group here.
