### ISSUE TITLE
CLI and Framework compatibility - confusing error message (don't know npm)

### ISSUE THREAD

**Issue by macdrorepo** [aws/aws-cdk#13528]
Hello.

I'm getting following error:

    `This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version. (Cloud assembly schema version mismatch: Maximum schema version supported is 8.0.0, but found 9.0.0)` after issuing cdk diff command.

I did run `npm install -g aws-cdk@latest` which successfully installed all npm "stuff" . After that I've run `pip install -r requirements.txt` and new versions of packages installed ok: `Successfully installed aws-cdk.assets-1.92.0 aws-cdk.aws-apigateway-1.92.0 aws-cdk.aws-apigatewayv2-1.92.0 ... etc.`

However after typing cdk --version I'm still getting 1.85.0 (build 5f44668).

My part of setup.py is as follows:

    install_requires=[
    "aws-cdk.core==1.92.0",
    "aws-cdk.aws-ec2==1.92.0",
    "aws-cdk.aws_ecs==1.92.0",
    "aws-cdk.aws_elasticloadbalancingv2==1.92.0"
],

Can't understand what to do now, as all solutions provided are: run this `npm install -g aws-cdk@latest` or similar commands which is not solving my issue.

**Comment by macdrorepo** [comment]
So I've fixed it but was to chaotic to describe steps. 
Generally seems like problem with symlink which was poiting to 1.85.0 version not to updated one, 1.92.0. 
I've removed aws-cdk from node_modules, installed it again, removed symlink `/usr/local/bin/cdk` and recreated it manually with `ln -s /usr/lib/node_modules/aws-cdk/bin/cdk /usr/local/bin/cdk`.

Can someone from AWS explain why after 1.92.0 installation, symlink was still referring to 1.85.0 version ??? (Ubuntu 20.04)

**Comment by rix0rrr** [comment]
> Can someone from AWS explain why after 1.92.0 installation, symlink was still referring to 1.85.0 version ??? (Ubuntu 20.04)

Unfortunately, not really. That depends on how you installed CDK previously. I don't think `npm install -g` installs into `/usr/local/bin` (though I might be wrong), so it's probably not an `npm install` that put CDK on your PATH in the first place.

Before recreating it, you should have checked where it was pointing, that should probably give you a hint as to how it got there in the first place.

This issue seems like something local to your setup, and is not really related to anything under our control. Closing.
