### ISSUE TITLE
(RDS): deploy-time value can't be used for nr of instances in Cluster

### ISSUE THREAD

**Issue by TLadd** [aws/aws-cdk#13558]
I'm attempting to store some configuration variables in parameter store for my RDS cluster but am running into [this validation error](https://github.com/aws/aws-cdk/blob/6c5b1f42fb73a132d47945b529bab73557f2b9d8/packages/%40aws-cdk/aws-docdb/lib/cluster.ts#L370) about instance size needing to be at least 1. It's comparing the token's value, which is a big negative number. 

### Reproduction Steps

```typescript
import * as rds from "@aws-cdk/aws-rds";
import * as ec2 from "@aws-cdk/aws-ec2";
import * as ssm from "@aws-cdk/aws-ssm";


class DbStack extends Stack {
    vpc: ec2.Vpc;

    constructor(scope: Construct, id: string, props?: StackProps) {
      this.vpc = new ec2.Vpc(this, "GrowMeVpc", {
        maxAzs: 3,
        enableDnsSupport: true,
        enableDnsHostnames: true,
      });

      const RDS_INSTANCES = Token.asNumber(getSsmStringParam("RDS_INSTANCES"));

        new rds.DatabaseCluster(this, "DbCluster", {
          engine: rds.DatabaseClusterEngine.auroraPostgres({
            version: rds.AuroraPostgresEngineVersion.of("12.4", "12", {
              s3Import: true,
              s3Export: true,
            }),
          }),
          defaultDatabaseName: "db",
          instances: RDS_INSTANCES,
          instanceProps: {
            instanceType: ec2.InstanceType.of(
             "t3",
             "medium"
            ),
            vpcSubnets: {
              subnetType: ec2.SubnetType.PRIVATE,
            },
            vpc: this.vpc,
          },
      });
  }
    
```

### What did you expect to happen?

I would expect the validation to run after the token has resolved only

### What actually happened?

Validation ran on the token's value itself

### Environment

  - **CDK CLI Version  :** 1.92.0
  - **Framework Version:** 1.92.0
  - **Node.js Version:** 14.16.0
  - **OS               :** Max OS
  - **Language (Version):** TypeScript 4.2.2

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @TLadd ,

thanks for opening the issue. Unfortunately, what you're trying to do is not possible. Since every instance is a separate resource that the `DatabaseCluster` Construct has to create, it's not possible to do it with a value only available at deploy time, like with the `getSsmStringParam("RDS_INSTANCES")` value.

I agree that the error message could be better here though! Keeping this open to fix that ([PR are welcome, as always!](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#linking-against-this-repository)).

BTW. We have a constant for the `12.4` version of the Aurora PostgreSQL [defined here](https://github.com/aws/aws-cdk/blob/78b265cba23b438cb53655dee40b286852b9b3b7/packages/%40aws-cdk/aws-rds/lib/cluster-engine.ts#L458-L459), so no need to use the `of` method in your code.

Thanks,
Adam

**Comment by BLasan** [comment]
@skinny85 Will work on this
