### ISSUE TITLE
(module name): short issue description

### ISSUE THREAD

**Issue by Z11** [aws/aws-cdk#13574]
A cdk solution for AWS Lex would be amazing.

### Use Case

CDK doesn't have support for AWS Lex.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Hey @Z11 thank you for the suggestion! Could you please update your title to accurately describe the issue?

We typically don't implement constructs not yet added to Cloud Formation due to the increased workload, so this probably won't be able to be implemented until Lex is supported by Cloud Formation

**Comment by robertd** [comment]
https://github.com/aws/aws-cdk/pull/17955 addressed this partially. L1 only... no L2 yet.

**Comment by peterwoodworth** [comment]
With that, I'm going to close this issue out 🙂
