### ISSUE TITLE
(aws-apigatewayv2-authorizers): Authorizer is not deleted from the stack.

### ISSUE THREAD

**Issue by apoorvmote** [aws/aws-cdk#13711]
### description of the bug:

I had made mistake with cognito user pool but user pool authorizer dependens on user pool so I deleted both then deployed stack. And created user pool then deployed the stack its success.

Then used the new user pool and created authorizer and I get following error

`Authorizer name must be unique. Authorizer UserPoolAuthorizer already exists in this RestApi.`

1. Looks like old authorizer has not been deleted
1. There is no way to specify name for user pool authorizer 

### Reproduction Steps

1. Create user pool
1. Create user pool authorizer 
1. delete user pool authoriser
1. delete user pool
1. create user pool in same stack
1. create user pool authorizer and lambda integration in same stack

### What did you expect to happen?

I should be able to create authorizer without deleting the whole stack.

### What actually happened?

I get the following error
`Authorizer name must be unique. Authorizer UserPoolAuthorizer already exists in this RestApi.`

### Environment

  - **CDK CLI Version  :** v1.94.1
  - **Framework Version:**
  - **Node.js Version:**  v 14.16.0
  - **OS               :** Ubuntu 20.04 on Windows WSL
  - **Language (Version):**  Typescript ~3.9.7

### Other

At the moment I am deleting everything from the stack and creating brand new stack. But this is nightmare.

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Hi @apoorvmote, I can't seem to reproduce this issue. I can create a user pool and authorizer, then remove them from the stack and the authorizer should be deleted. Upon creating them again everything works fine for me following your process. How exactly are you deleting your pool and authorizer?

You mention that there is no way to specify a name for a user pool authorizer, but [there is.](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2-authorizers.UserPoolAuthorizerProps.html#authorizernamespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) (Note that the default name is `UserPoolAuthorizer`) This example here will create a user pool authorizer with the name `MyAuthorizer`.
```ts
const authorizer = new apigwAuths.HttpUserPoolAuthorizer({
      userPool: pool,
      userPoolClient: poolClient,
      authorizerName: "MyAuthorizer"
});
```

**Comment by apoorvmote** [comment]
@peterwoodworth I can't belive I missed that. I was looking to set `id` for the authorizer. 

Also I made mistake about recreating the issue. Authorizer is not deployed until you attach it to the api gateway route. And the autogenerated ID is combination of api gateway name and authorizer default name `UserPoolAuthorizer` like you said. 

I give my api human redable name for easy tracking.

```ts
const api = new HttpApi(this, 'myWebsiteApiEndpoint', {
      apiName: 'myWebsiteAPI',
})
```
Or it may have been combination of `id` for api and default `UserPoolAuthorizer`. 

When I deleted my api and gave it new `id` and new name then the authorizer started working with default `UserPoolAuthorizer` name. I didn't have to delete the whole stack. There are few things in stack I was avoiding to delete at all cost. Maybe I need to organize my stacks better next time. 

Also I want to point out this is not first time it has happend. Updating stack has too many corner cases. Many times I cannot update the stack. I have to delete the whole stack and create fresh stack and everything works fine. I was fed up of doing that so I made issue this time. 

Now I know I don't even need to delete the api and just change `authorizerName`. So feel free to close this issue.

**Comment by peterwoodworth** [comment]
I'm glad that this helped with your issue!

However I'm not sure what exactly you're referring to when you say the autogenerated ID is a combination of apigw name and authorizer default name? There are a couple IDs you could be referring to, but neither physical nor logical IDs of the authorizer is determined by the apigw name. The Logical ID in Cloudformation `UserPoolAuthorizerXXXXXXXX` is only used by CloudFormation, and the name is whatever you define `authorizerName` as, (or `UserPoolAuthorizer` as default of course) plus a randomly generated string at the end. This string at the end is randomly generated, because of this and because the logical ID is only used for CloudFormation you shouldn't have to worry about the logical names.

The biggest reason I bring this up is because you are now specifying your `apiName`. Best CDK practices discourage giving your resources your own physical names. This is because you can only have one unique physical name on your AWS account, so you can frequently run into issues deploying because of duplicate names. A common place where this might happen is if you make any changes to immutable properties. Read the docs [here](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_physical_names) for more info on physical resource names and their limitations.

Now given the last paragraph, that contradicts your experience here. You shouldn't have to specify the `authorizerName` to *avoid* this issue. I found when reproducing this issue that trying to attach two authorizers to a route, they will both try and use the default name `UserPoolAuthorizer` and this will fail. Because of this I'm going to leave this issue open to look into this further.

**Comment by apoorvmote** [comment]
It shouldn't be a problem now. Before HTTP API were relatively new and I had to go to console to find the right api and see what has happened. Now I rarely go to api gateway console. So auto generated api gateway name would be fine.

> However I'm not sure what exactly you're referring to when you say the autogenerated ID is a combination of apigw name and authorizer default name?

So here is what happened. I removed authorizer from api route and updated user pool. Then tried to add authorizer to api route with new user pool and I got error listed above that authorizer already exists. 

Then I deleted the api & gave it new `id` and new apigw name. And I was able to successfully attach new authorizer to api route. In both cases I was using the default name `UserPoolAuthorizer` becuase I didn't know you could change it.

So my guess is that changing apigw name and `id` has something to do with successfully deploying authorizer.
