### ISSUE TITLE
(ecs-service-extensions): Make available for all languages

### ISSUE THREAD

**Issue by hannseman** [aws/aws-cdk#13717]
I might be missing something here but I fail to find a way to install the `ecs-service-extensions` package on Python. Can’t find it available for any other languages than Typescript. It looks really cool and I’d love to be able to use it!

**Comment by polothy** [comment]
Yes please! Seems like this is advertised as the way forward for ECS patterns but not available in Python.

**Comment by kaizen3031593** [comment]
Excited to announce that we have a v2 of `@aws-cdk-containers/ecs-service-extensions` that is CDK v2 compatible and has multi-language support!

  - the new version lives in cdklabs [here](https://github.com/cdklabs/cdk-ecs-service-extensions) and this is where we’ll continue to support it.
  - because v2 is jsii compatible, it can be found on construct hub [here](https://constructs.dev/packages/@aws-cdk-containers/ecs-service-extensions/v/2.0.0-alpha.7?lang=typescript)
  - because of legacy reasons, the js/ts module is still called `@aws-cdk-containers/ecs-service-extensions` while the other languages will have a name similar to `cdk_ecs_service_extensions`. 
  - we have a quick and painless migration [guide](https://github.com/cdklabs/cdk-ecs-service-extensions/blob/main/MIGRATING.md) from v1 to v2 because there are only minimal API changes (if you were using the v1 in TypeScript before).
  - in the short term, we’ve marked the construct as `experimental` but plan to quickly stabilize it once we know people have downloaded it and can use it successfully.
