### ISSUE TITLE
(aws-fis): L2 Construct for FIS ExperimentTemplate

### ISSUE THREAD

**Issue by yattoni** [aws/aws-cdk#13744]
AWS-FIS launched last week and I would like L2 constructs for their ExperimentTemplate.

They have CFN types but I'm not sure if those have yet been imported into the CDK either.

https://aws.amazon.com/fis/

https://docs.aws.amazon.com/fis/latest/userguide/what-is.html

https://docs.aws.amazon.com/AWSCloudFormation/latest//UserGuide/AWS_FIS.html

### Use Case

Create experiments without having to deal with hassle of L1 constructs.

AWS FIS also requires a special role to be created to execute the experiments and I would like that to be created for me when I create an experiment template. https://docs.aws.amazon.com/fis/latest/userguide/getting-started-iam.html

### Proposed Solution

TBD

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hey @yattoni!

Thanks for the request! Due to the large volume of requests and relatively small dev team, this will take quite a while before it bubbles up to the top of priority. If you would like to see this feature implemented sooner, your best bet is to increase engagement on this ticket or coordinate contributing it yourself.

If a request has a significant number of upvotes or comments it will get pushed up the priority list, so if you know of others who are interested in this feature, send them to the issue.

If you would like to contribute yourself, read the `CONTRIBUTING.md` guide in the root of the repo, then let me know here so we can preemptively coordinate.

I hope that helps!
😸 😷

**Comment by yattoni** [comment]
@NGL321 when will the L1 constructs be available? Do they get added automatically on some schedule?

**Comment by NGL321** [comment]
The L1 will almost certainly get added in the next release if it is in the cfn resource spec. This is not on a fixed timeline, but will likely be within the week.
