### ISSUE TITLE
(aws-glue): Create Glue table based on DynamoDB ARN

### ISSUE THREAD

**Issue by mileswatson90** [aws/aws-cdk#13775]
Create Glue table based on DynamoDB ARN

### Use Case

My team has a use case of copying Dynamo data to S3 via a Glue job. This requires creating a Glue table which represents the schema of the Dynamo table so that the Glue job may scan/query it.

Note: Our Dynamo table was not created with CDK.

### Proposed Solution

CDK to add the ability to create a Glue table based on an existing Dynamo ARN. 

---

This is a :rocket: Feature Request

**Comment by RomainMuller** [comment]
Hey @mileswatson90

I cannot talk too much about the Glue part of it (I'm not familiar enough with it at this point).

It looks like however in order to implement this, we would need the full DynamoDB table schema to be inspected (possibly including attributes that are not typically part of the table definition), which isn't something that can be easily achieved in CloudFormation (and context providers may not be a great fit for this particular use-case, as DynamoDB table schemas are partially mutable).

My instinct (but @iliapolo might know better) is that this feature might actually be better implemented as a custom resource, as it might provide more flexibility... I also feel like this feature may not _need_ to be part of the core CDK framework (but then again - I'm not familiar enough with Glue to be all too confident about that), and could be implemented as a third-party module.

**Comment by mileswatson90** [comment]
That makes sense. In CF we were able to at least implement a Dynamo-backed Glue table by specifying the location of the table as the DDB ARN, and the schema like this:

> 

ExperimentsExportDynamoTable:
    Condition: IsSourceStack
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref ExperimentsExportDatabase
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: 'experiments_export_dynamo'
        TableType: 'EXTERNAL_TABLE'
        Parameters:
          classification: 'dynamodb'
          hashKey: 'experimentId'
          compressionType: 'none'
          typeOfData: 'table'
        StorageDescriptor:
          Location: { 'Fn::Sub': 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/experiments' }
          Columns:
            - Type: 'string'
              Name: 'userdata'
            - Type: 'string'
              Name: 'experimentid'
> 

Being able to do that in CDK would satisfy our use case as well. Would that be possible?

**Comment by iliapolo** [comment]
@mileswatson90 I believe it should be possible to start of with supporting the static use-case as you mentioned, basically allowing you to do the same thing as CloudFormation. Later on we can consider expanding the capabilities and address what @RomainMuller mentioned. 👍

**Comment by mileswatson90** [comment]
Anyone able to pick this up?
