### ISSUE TITLE
cdk:  get local issuer certificate (with out proxy)

### ISSUE THREAD

**Issue by oappicgi** [aws/aws-cdk#13880]
running cdk deploy <stack> results in unable to get local issuer certificate error
![image](https://user-images.githubusercontent.com/20458699/112996676-0bcb3500-9175-11eb-8596-cf7be85d40f5.png)

I did update my operating system to newer version, which is just about only real difference that could have caused this. Running npm updates and upgrades did not seem to help. 

Seems that OS update requirement to downgrade nodejs to what is in repository caused this

### Reproduction Steps

it seems to require lambda function to be uploaded during deployment. so at least lambda function has to be present

### What did you expect to happen?

I expected cdk to be able to generate diff and push update to AWS 

update cdk stack.
It seemed that the issue was on lambda functions though. Simple them existing in the code even with out change causes this issue

### What actually happened?

![image](https://user-images.githubusercontent.com/20458699/112996676-0bcb3500-9175-11eb-8596-cf7be85d40f5.png)
❌  X-dev-ci failed: Error: Failed to publish one or more assets. See the error messages above for more information.
Failed to publish one or more assets. See the error messages above for more information.

cdk failed to push updates because of certificate.  I do not use proxy

### Environment
aws --version
aws-cli/2.0.16 Python/3.7.3 Linux/5.4.0-70-generic botocore/2.0.0dev20

cdk version:
1.95.1 (build ed2bbe6)
npm --version  7.7.6
nodejs 10.x

### Other

Would be nice if there was bit clearer explanation what is required. Preferably also have minimum nodejs version in installation instructions as someone could easily have old nodejs installed 

--- 

I guess it is not a bug, but I clearer explanation is needed.

**Comment by rix0rrr** [comment]
I'm having problems parsing this bug report.

> Seems that OS update requirement to downgrade nodejs to what is in repository caused this

There is no requirement from us to downgrade your Node.js. It might be that an upgrade of your OS (which you didn't tell us from what to what you upgraded) changed something about the CA store so that Node.js can no longer find the appropriate certificates.

Although it's a bit confusing because if that were true `npm install` also wouldn't work anymore, and you mentioned you did npm updates.

> It seemed that the issue was on lambda functions though. Simple them existing in the code even with out change causes this issue

If you run again with `-v` you'll see it's trying to upload files to S3.

The error indicates there's "something" wrong with TLS certificates--the errors are always pretty obtuse.

I'm sorry but I'm not sure how I can remotely help you debug a TLS certificate misconfiguration issue that seems to depend on the combination of your OS and your Node.js version.
