### ISSUE TITLE
(aws-elasticsearch): Execute code after Elasticsearch domain is created

### ISSUE THREAD

**Issue by jakubgruber** [aws/aws-cdk#13935]
### Execute custom code after elasticsearch.CfDomain is created

I am trying to install EFK stack through CDK according to the [eksworkshop](https://www.eksworkshop.com/intermediate/230_logging/config_es/). 

During one step, they are waiting for ES cluster to be fully created to `curl`-it and register IAM role for fluent-bit.

```
# We need to retrieve the Fluent Bit Role ARN
export FLUENTBIT_ROLE=$(eksctl get iamserviceaccount --cluster eksworkshop-eksctl --namespace logging -o json | jq '.[].status.roleARN' -r) 

# Get the Elasticsearch Endpoint
export ES_ENDPOINT=$(aws es describe-elasticsearch-domain --domain-name ${ES_DOMAIN_NAME} --output text --query "DomainStatus.Endpoint")

# Update the Elasticsearch internal database
curl -sS -u "${ES_DOMAIN_USER}:${ES_DOMAIN_PASSWORD}" \
    -X PATCH \
    https://${ES_ENDPOINT}/_opendistro/_security/api/rolesmapping/all_access?pretty \
    -H 'Content-Type: application/json' \
    -d'
[
  {
    "op": "add", "path": "/backend_roles", "value": ["'${FLUENTBIT_ROLE}'"]
  }
]
'
```

Is there any workaround to wait in CDK for ES cluster to run and then automatically execute custom code? My IaaC codebase is in Typescript, but I assume it is rather a general question.

**Comment by iliapolo** [comment]
@jakubgruber 

> Is there any workaround to wait in CDK for ES cluster to run and then automatically execute custom code? My IaaC codebase is in Typescript, but I assume it is rather a general question.

Yeap, you can use [custom-resources](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html). In fact, we have this exact example as part of our own implementation for the L2 Domain construct. 

See https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticsearch/lib/elasticsearch-access-policy.ts

This code configures access policies after the domain has been created, since it runs an `aws-sdk` call, it uses a predefined version of a custom resource that handles AWS SDK Calls, but you can run any code you like.

In addition, we have an RFC in progress to specifically address this exact use case, called [Deployment Triggers](https://github.com/aws/aws-cdk-rfcs/issues/71), you are welcome to join the discussion :)
