### ISSUE TITLE
(module name): @aws-cdk/aws-dynamodb

### ISSUE THREAD

**Issue by raosrikanth** [aws/aws-cdk#13992]
### The Question
I'd like to import the existing dynamo db table and enable auto scaling through CDK. When i import the table it returns the Itable object and it doesn't implemented autoScaleReadCapacity and autoScalewriteCapacity methods. How can we enable austoscaling for existing DDB table.

**Comment by peterwoodworth** [comment]
By design, existing resources that are imported cannot be modified. [Read Here]() to learn more about importing existing resources. Note this section: 

```Although you can use an imported resource anywhere, you cannot modify the imported resource. For example, calling addToResourcePolicy (Python: add_to_resource_policy) on an imported s3.Bucket does nothing.```

I'm not sure exactly what your use case is, but there should certainly be a workaround. Let me know if you need any help with figuring out a workaround!
