### ISSUE TITLE
(aws-cdk core): specifying a deployment order for resources in a code change

### ISSUE THREAD

**Issue by girotomas** [aws/aws-cdk#13999]
Let’s say resource C depends on resource B and they are on different stacks.
We want to delete B because it’s no longer needed.
We deploy a change deleting B and modifying C to C’ such that C no longer depends on B.
I think that what happens is that the deployment fails: The cdk will first try deleting B before modifying C to C’ because C depends on B. It will throw an error saying that B cannot be deleted because C (which is not yet modified) depends on B.

### Use Case

This feature is particularly important to work with CI/CD Pipelines. Without this, teams are forced to first make a first deployment wave deleting the dependencies, and then a second one deleting the unused resources.
This is bad in many ways:
- it feels very hacky it seems that CDK is "unadapted" to work with CI/CD
- it forces developers to split code changes (code reviews) which make sense together but don't seem right separately. Ideally each code change should make conceptual sense.
- it wastes developers time as developers face errors in deployment

### Proposed Solution

There should be a way to either specify by hand how the deployment order should be handled for a specific change. Or an automatic way to deal with these situations. Making changes first and finally deleting resources also seems like a solution to this.
Maybe a two round deployment of stacks a first one implementing changes and a second one deleting resources could solve the problem.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
This is a constraint imposed on us by the underlying tools. Especially in a CI/CD system where we have to establish global order between stacks, given that our pipeline infrastructure has to reflect this structure independently of the changes that are actually deployed to any stage (because we cannot inspect those), and given that our deployment mechanism is a desired-state system which could have any number of logical changes rolled up into any single deployment operation. 

As to the last point: maybe you removed your `C->B` link, but someone else at the same time introduced a `C2->B2` link. Now still deploying in reverse would not be good enough.

For every single edge case we solve by doing automatic magic, people will just find another edge case that won't work properly.

The [stack.exportValue](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#exportwbrvalueexportedvalue-options) method will help you break links between stacks. 

Yes, it requires two commits leading to deployments:

* First one to break the link
* Second one to clean up the unused resource

This is true because the second commit cannot happen until the first commit has completely passed through the pipeline.
