### ISSUE TITLE
(lambda-event-sources): ManagedKafkaEventSource mandatorily requires secret parameter

### ISSUE THREAD

**Issue by ambasta** [aws/aws-cdk#14038]
When trying to configure ManagedKafkaEventSource as a trigger to lambda, secret parameter is mandatory for Cdk. However, this is only requierd for MSK if we're accessing it publicly over SSL instead of via vpc security groups.

### Reproduction Steps
```python
msk = aws_msk.Cluster.from_cluster_arn(self, "kafka", "<cluster_arn>")
fn = aws_lambda_python.PythonFunction(...)

msk_source = aws_lambda_event_sources.ManagedKafkaEventSource(
    cluster=msk,
    topic="SomeTopic",
    batch_size=100,
    starting_position=aws_lambda.StartingPosition.LATEST
)
fn.add_event_source(msk_source)
```

### What did you expect to happen?

cdk deploy should complete successfully

### What actually happened?

cdk deploy fails with 
```
TypeError: __init__() missing 1 required keyword-only argument: 'secret'
```

### Environment

  - **CDK CLI Version  : 1.97.0**
  - **Framework Version: 1.97.0**
  - **Node.js Version: 15.11.0**
  - **OS               : gentoo**
  - **Language (Version): Python (3.9.4)**

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
@bracki - do you know if this is correct? 

@ambasta - I'm not initimately familiar with the kafka event source. How do you configure (via CloudFormation) that the access should be via vpc and not public?

**Comment by pchot** [comment]
@nija-at You don't need to use Secret in order to create event source mapping. Here's link to documentation on how to do it form AWS CLI https://docs.aws.amazon.com/lambda/latest/dg/services-msk-topic-add.html#services-msk-aws-cli 

This comes down to specifying ARN for cluster, topic, starting point and function name. Like in the example from documentation:
 
`aws lambda create-event-source-mapping --event-source-arn arn:aws:kafka:us-west-2:arn:aws:kafka:us-west-2:111111111111:cluster/my-cluster/fc2f5bdf-fd1b-45ad-85dd-15b4a5a6247e-2 --topics AWSKafkaTopic --starting-position LATEST --function-name my-kafka-function`

**Comment by nija-at** [comment]
Thanks for the update @pchot.

I am marking this issue as p2, which means that we are unable to work on this immediately.
We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. 

You can also submit a PR to make this change if you would like to see this fixed sooner.

**Comment by bracki** [comment]
Yes, this is correct. It never occurred to me when implementing. Basically, the secret could be made optional.

**Comment by pchot** [comment]
@ambasta I've found a nice workaround that works for me. Instead of using `ManagedKafkaEventSource` you can directly create event source mapping using [`EventSourceMapping`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.EventSourceMapping.html) construct. See example below:

```javascript
import {NodejsFunction} from "@aws-cdk/aws-lambda-nodejs";
import {Effect, ManagedPolicy, PolicyStatement} from "@aws-cdk/aws-iam";
import {EventSourceMapping, Runtime, StartingPosition} from "@aws-cdk/aws-lambda";

let consumer = new NodejsFunction(this, "consumer ", {...});

//TODO: tighten the security
consumer.addToRolePolicy(new PolicyStatement({
    effect: Effect.ALLOW,
    actions: ['kafka:*'],
    resources: [kafkaCluster.ref]
}));
consumer.role?.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName("service-role/AWSLambdaMSKExecutionRole"))

new EventSourceMapping(this, "KafkaLambdaEventSourceMapping", {
    eventSourceArn: kafkaCluster.ref,
    target: consumer,
    kafkaTopic: topicName,
    startingPosition: StartingPosition.LATEST
});
```

You have to remember to allow network traffic between lambda's security group and Kafka cluster's security group as well as allow internal network traffic within Kafka cluster's security group. You can find more information in [this workshop](https://amazonmsk-labs.workshop.aws/en/msklambda/gsrschemareg/overview.html). Here's how to easily enable communication:
```javascript
kafkaSecurityGroup.connections.allowFrom(this.lambdaSecurityGroup, ec2.Port.allTraffic(), "allowAllFromLambdaToKafka");
kafkaSecurityGroup.connections.allowFrom(this.kafkaSecurityGroup, ec2.Port.tcp(9092), "allowInternalOn9092");
kafkaSecurityGroup.connections.allowFrom(this.kafkaSecurityGroup, ec2.Port.tcp(9094), "allowInternalOn9092");
lambdaSecurityGroup.connections.allowFrom(this.kafkaSecurityGroup, ec2.Port.allTraffic(), "allowFromKafkaToLambda");
```
You can probably tighten rules in first and last line to limit allowed ports.

Hope that helps.

**Comment by therockstorm** [comment]
@nija-at @bracki We're looking to use MSK event sources in production and need this fix before we can automate it. Is there anything else I need to do with my PR? It says it's waiting for approval, https://github.com/aws/aws-cdk/pull/14804. Thanks!
