### ISSUE TITLE
(cdk cli): hangs for 15 minutes when environment creds are expired

### ISSUE THREAD

**Issue by kristianpaul** [aws/aws-cdk#14109]
## :question: General Issue

When using temporary credentials from AWS SSO,  `cdk deploy` takes more than 15 minutes to break and display on screen that the credentials are not valid, this is quite annoying ! 

### Environment

  - **CDK CLI Version:** 1.97.0 (build c52c2dc)
  - **Module Version:** 
  - **Node.js Version:** v10.19.0
  - **OS:** Ubuntu  20.04
  - **Language (Version):** Python3.8.5

### Other information

I set temp credentials from AWS SSO looks like:

```
export AWS_ACCESS_KEY_ID="AAAAAAAAAAAAAAAAA"
export AWS_SECRET_ACCESS_KEY="xxxxxxxxxxxxxxxxxxxxxx"
export AWS_SESSION_TOKEN="AAAAAbbbbccccc0000000="

```

cdk stalled forever and then error message displated...

```
❯ cdk deploy



The security token included in the request is expired

```

**Comment by rix0rrr** [comment]
This is an artifact of the underlying JavaScript SDK (it does not properly detect that trying to refresh environment credentials is not a useful operation).

Presumably a quick and pragmatic fix would be to have a much lower retry count when doing STS operations (our retry count is pretty high right now for dealing with low CloudFormation TPS quotas)

**Comment by ssypi** [comment]
Even a simple console message saying that it is attempting to retry would help. Now I'm just left wondering if I did something wrong or if my code is broken since seemingly nothing is happening for 15 minutes..

**Comment by Dzhuneyt** [comment]
Let me share a different perspective which occurs for me daily and is also quite annoying. It's tightly related to this issue and the fix for this would also solve my use case.

I use aws-vault as the CLI wrapper for `cdk deploy` commands. aws-vault basically does the heavy lifting of calling AWS STS under the hood, setting the temporary credentials as env vars in the bash, and invoking the `cdk deploy` command (or any other command I provide).

The thing is, I also configured "mfa_serial" in my ~/.aws/config file, which means that I regularly get asked for an MFA token. Occasionally, when I'm doing CDK deployments close to the time where my MFA confirmation will expire (e.g. on the 59th minute and the MFA confirmation will expire at the 60th minute) - the CDK CLI deployment successfully starts deploying stuff, but at some point - just hangs and I eventually get an error message along the lines of "Invalid token". I assume it's because the CLI is internally trying to poll CloudFormation for changes to the stack and waits for it to succeed. However, I expect this failure to happen much quicker and I shouldn't wait for 15 minutes for some hard timeout to kick in.

**Comment by Dzhuneyt** [comment]
Still occurring.

**Comment by Kishore-Periassamy** [comment]
This is still annoying, especially for someone new to CDK. A fail fast approach is much appreciated.
