### ISSUE TITLE
CDK Survey - Open until 5/5/2021

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#14178]
Hello CDK community! 
We are conducting a survey to get your feedback on the CDK. It will take about 10 minutes to answer just a few questions. We look forward to hearing from you! 
[Take the survey here](https://amazonmr.au1.qualtrics.com/jfe/form/SV_cHJeiokPMsScdV4)

**Comment by vahdet** [comment]
As a casual survey-hater, I did not hate this survey. Take it as a compliment 😄 Still a couple of things:

- Towards the end, there was a question asking for language**s**, but it allowed me for only one (and thus, the next became to select one from a list of one language) .
- And it is presumably by design, but let me point out anyway: there was no _back_  button for revisiting previous answers.

**Comment by kjpgit** [comment]
I'm surprised there wasn't a question about if you prefer to use the same CDK language as your "main" language.  For me, even though I use $snake-like-language for the app, I'm much happier using TS for CDK.

Also, entering free form comments in a single line = not fun.

**Comment by ccfife** [comment]
Thanks for the feedback on how we can improve the survey, these are all good suggestions!

**Comment by iRoachie** [comment]
Missed this in the survey, but it would be awesome if the Reference Documentation had a search

**Comment by pistazie** [comment]
The question seems to contain a typo: The question mentions pipeline but none of the answers are about pipelines.
![image](https://user-images.githubusercontent.com/1391179/116774835-854d9000-aa5f-11eb-83f7-183277620592.png)

**Comment by ccfife** [comment]
The survey is now closed.
