### ISSUE TITLE
(iam) Role policies are frequently exceeding 10kB

### ISSUE THREAD

**Issue by Larkenx** [aws/aws-cdk#14261]
https://github.com/aws/aws-cdk/blob/e7f09cb5159fbfad3a5c5fcbbc1fa8eab3d711dd/packages/%40aws-cdk/aws-iam/lib/role.ts#L300-L302

In order to support better flexibility when cleaning up the inline policy statements after creating large AWS CDK Stacks with several inline IAM policies, we'd like to be able to have read access on these fields so that we can de-dupe action & resource in line policies that are the same, but repeated numerous times.

We're frequently exceeding the 10kb policy limit size, and looking for ways to improve this.

**Comment by rix0rrr** [comment]
I don't think giving you more access to mess around in CDK internals is the right solution.

It makes sense to me for example to combine resources from otherwise identical policy statements, that's an optimization we can do.

How is this happening for you, what would you personally be doing about this?

As a temporary workaround, you can make your own subclass of `Role` which implements your optimizations, or pass `role.withoutPolicyUpdates()` to constructs and just provide the complete policy document yourself.

**Comment by Larkenx** [comment]
@rix0rrr  I agree after tinkering with this for a few days.

We ended up combining our IAM policy statements using Aspects to reduce the size of our inline policy down to below the character quota instead of trying to patch/exclude grants on the IAM Role along the way
