### ISSUE TITLE
(aws-ecs-patterns): X-Ray support

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#14284]
Please make it trivial to add the xray side-car for aws-ecs-patterns/ApplicationLoadBalancedFargateService etc.

### Use Case

I want to encourage my developers to use X-Ray, to do this, I want to make it stupid easy to deploy X-Ray enables services.

### Proposed Solution

```
    const service = new ecsp.ApplicationLoadBalancedFargateService(this, 'service', {
       ...
       xraySidecar: true
    };
```

Where that runs something like
https://github.com/aws-samples/one-observability-demo/blob/d11387bba7640f97dc42b01bb07f0d53cd98c8d7/PetAdoptions/cdk/pet_stack/lib/services/ecs-service.ts#L157

```
    // Enable xray side-car
    service.taskDefinition
      .addContainer('xraydemon', {
        image: ecs.ContainerImage.fromRegistry('public.ecr.aws/xray/aws-xray-daemon:latest'),
        memoryLimitMiB: 256,
        cpu: 256,
      })
      .addPortMappings({
        containerPort: 2000,
        protocol: ecs.Protocol.UDP,
      });
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
Hi @ahammond !

Have you checked out the ECS [Service Extensions](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk-containers/ecs-service-extensions)? We have support for x-ray and other sidecars/add-ons there, and this is our recommended way of using X-ray. Thanks!

**Comment by ahammond** [comment]
@SoManyHs while that's cool and very relevant, I don't see how to write the necessary plumbing to get my ApplicationLoadBalancedFargateService to have xray support using the referenced ServiceExtensions. The point of this issues is to make xray easy with the aws-ecs-patterns library.

**Comment by SoManyHs** [comment]
@ahammond Yeah, I get that it would be nice to be able to plug in an x-ray sidecar into the existing pattern, unfortunately this module is intended for simplified pattern.  For more advanced usage we really do encourage folks to use the service extensions, since that does help simplify things like resolving various configuration dependencies for you. We also definitely encourage folks to submit examples of different patterns like the one you have though!

**Comment by ahammond** [comment]
@SoManyHs I see your point. From my perspective x-ray support is an implementation detail and what I'm trying to do is run a container in fargate. The same way that adding x-ray support to a lambda is a one-liner, https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#lambda-with-x-ray-tracing it seems to me that adding x-ray support to an ECS Service ought to be a one-liner.

**Comment by 24601** [comment]
> Hi @ahammond !
> 
> Have you checked out the ECS [Service Extensions](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk-containers/ecs-service-extensions)? We have support for x-ray and other sidecars/add-ons there, and this is our recommended way of using X-ray. Thanks!

What am I (and @ahammond ) missing here? The API for extensions seems to rely on creating a ServiceDescription then manually creating the service, the whole point of ecs_patterns is to provide higher-level, best-practice, secure, well-designed patterns so using the lower-level API extensions seems to require isn't needed.

Do we need to choose between using the (very good and highly favorable for scalable, maintainable development) ecs_patterns and extensions? It appears they are mutually exclusive. Why? Can we make them live in harmony instead of further fragmenting the IaaC toolset (the CDK seemed to be invented to actually address this problem, but we seem to be making it worse), or are we missing something in how to use extensions alongside ecs_patterns?

**Comment by AndrewGuenther** [comment]
@SoManyHs I would push back on X-ray being considered advanced usage. It is a very common pattern across CDK constructs to have a boolean "Tracing enabled" option. Yes, I know that this isn't a checkbox option with ECS, but I think it is still a fair consideration. Tracing is considered a well-architected best practice and should be made as easy as possible. I really think including it in ecs-patterns should be reconsidered. If ecs-patterns won't follow well-architected practices out of the box, then I'd strongly encourage the entire module be deprecated in favor of Service Extensions.

**Comment by SamStephens** [comment]
@SoManyHs I second what @AndrewGuenther says. It's quite infuriating to have started using ecs-patterns in good faith, and then discover that we're hamstrung in our capabilities because of our use of it, and have to migrate away.

I think you need to either:

* Add very clear caveats about the limits of ecs-patterns to the documentation;
* Deprecate ecs-patterns entirely;
* Or extend ecs-patterns with support for Service Extensions.

**Comment by SamStephens** [comment]
[Looks like ecs-patterns V2 is how this will be dealt with](https://github.com/aws/aws-cdk/issues/14625).

**Comment by 24601** [comment]
Beware the "it'll be better next time" candy going on here. AWS has a
history of being very, very fragmented (any organization their size has
this problem, but theirs is VERY extreme). Tons of competing groups
internally who not only don't talk, but have active disincentives at times
to coöperate, so it is not surprising this is happening and will continue
to happen.

AWS' dev tooling/SDKs are not unified at the org/leadership level and a
"v2" isn't going to fix this problem no matter how good the intentions.
Run. Away.
