### ISSUE TITLE
(@aws-cdk/aws-cognito): import 'punycode/'

### ISSUE THREAD

**Issue by ams671** [aws/aws-cdk#14290]
### The Question

about "@aws-cdk/aws-cognito/lib/user-pool.ts".
I don't think punycode's trailing slash is necessary.

##### current code
```
import { toASCII as punycodeEncode } from 'punycode/';
```

##### expected code
```
import { toASCII as punycodeEncode } from 'punycode';
```

### Environment

  - **CDK CLI Version: v1.100.0** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):** 

### Other information

An error occurred when importing '@aws-cdk/aws-cognito' in the Lambda function handler.

##### Lambda Runtime Error
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'punycode/'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    ...
}
```

**Comment by nija-at** [comment]
>  I don't think punycode's trailing slash is necessary.

Actually, the trailing slash is crucial. See https://github.com/aws/aws-cdk/pull/11099#discussion_r513405043

**Comment by ams671** [comment]
I understand.
Thank you for the information.

I solved my issue by creating Lambda Layer for punycode module.

## information

I was tring to deploy CDK's stack from within Lambda function handler.

#### sample code (Lambda function handler)
```typescript
import { App, Stack } from '@aws-cdk/core'
import { UserPool } from '@aws-cdk/aws-cognito'
import { SdkProvider } from 'aws-cdk/lib/api/aws-auth'
import { CloudFormationDeployments } from 'aws-cdk/lib/api/cloudformation-deployments'

exports.handler = async (event: any) => {
    const app = new App()
    const stack = new Stack(app, 'SampleStack')

    new UserPool(stack, 'SampleUserPool')

    const deployer = new CloudFormationDeployments({
        sdkProvider: await SdkProvider.withAwsCliCompatibleDefaults()
    })

    await deployer.deployStack({
        stack: app.synth().stacks[0],
        quiet: true
    })

    return {
        statusCode: 200,
        body: 'ok'
    }
}
```

It remains ```require("punycode/")``` when processed this code by esbuild,
it causes "Error: Cannot find module 'punycode/'".

#### esbuild result
```javascript
...
 var punycode_1 = require("punycode/");
...
```

I understood that ```punycode/``` isn't core module, 
so I solved by creating Lambda Layer for punycode module

**Comment by danielholmes** [comment]
I had this error as well and was able to fix it through some code changes. For me it was an error in my code organisation.

In my case it was to do with mixing devDependencies/cdk code with my runtime lambda code.

e.g. I had some files similar to:

`package.json`
```json
{
 ...
  "devDependencies": {
    "@aws-cdk/aws-lambda-nodejs": "^1.114.0",
    "@aws-cdk/aws-cognito": "^1.114.0",
    ...
  }
}
```

`users/index.ts`
```typescript
export { default as Construct } from "./construct";
export { default as getViewerResolver } from "./getViewerResolver";
```

`users/construct.ts`
```typescript
import { UserPool } "@aws-cdk/aws-cognito"
// ...
```

`api/construct.ts`
```typescript
// ...
class ApiConstruct extends Construct {
  constructor() {
    //...
    const defaultResolverLambda = new NodejsFunction(
      this,
      "DefaultGraphQlResolver",
      {
        runtime: Runtime.NODEJS_14_X,
        entry: path.join(__dirname, "..", "users", "index.ts"),
        handler: "getViewerResolver"
      }
    );
  }
}
```

including that `users/index.ts` file as an entry therefore included the `users/construct.ts` which tried to include some cdk cognito code which wasn't part of my runtime dependencies.

So the fix was to make sure my construct/cdk code was completely separate from my runtime lambda code.

**Comment by gorjusborg** [comment]
Thanks for posting this @danielholmes, I had the same issue.

We had some Custom::Trigger that would run to populate user data on deploy. Unfortunately, the lambda handler was thrown in the same module as some CDK code that was loosely related. This caused esbuild to bundle `aws-cdk-lib/aws-cognito` in the lambda, which declares a 'bundledDependency' on 'punycode/', but apparently it isn't bundled in the cdk v2 library (hence the require). 

This popped up on upgrade to CDK v2 after working with CDK v1.

The answer for me was to isolate the lambda code so that NO CDK code was referenced (even transitively) by module imports.
