### ISSUE TITLE
(@aws-cdk/aws-cloudfront): associate existing Cloudfront Distribution with `EdgeFunction` create by cdk

### ISSUE THREAD

**Issue by afenton90** [aws/aws-cdk#14326]
### The Question

At the moment it doesn't seem possible to associate a `cloudfront.experimental.EdgeFunction` with a pre-existing Cloudfront Distribution. I've tried looking at the documentation and several Stackoverflow issues and none have provided any guidance on this.

Is it currently possible to do something like the stack below or is that not a thing?

```ts
import { Stack, Construct, StackProps } from '@aws-cdk/core';
import * as cloudfront from '@aws-cdk/aws-cloudfront';
import * as lambda from '@aws-cdk/aws-lambda';
import path from 'path';

export class Website extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const myFunc = new cloudfront.experimental.EdgeFunction(this, 'EdgeFunctionForApp', {
      runtime: lambda.Runtime.NODEJS_12_X,
      functionName: 'theFunction',
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../lambdas/EdgeFunctionForApp')),
    });

    const existingDistribution = cloudfront.Distribution.fromDistributionAttributes(this, 'ExistingDistribution', {
      distributionId: 'arn:------',
      domainName: 'the-domain'
    })

    existingDistribution.addBehavior('*', {
      edgeLambdas: [
        {
          functionVersion: myFunc.currentVersion,
          eventType: cloudfront.LambdaEdgeEventType.VIEWER_REQUEST,
        },
      ],
    })
  }
}
```

### Environment

  - **CDK CLI Version:** 1.100.0 (build d996c6d)
  - **Module Version:** 1.100.0
  - **Node.js Version:** v12.19.0
  - **OS:** all
  - **Language (Version):** TypeScript (3.8.3)

**Comment by njlynch** [comment]
No, this is not currently possible.

This is due to the way a Distribution is modeled in CloudFormation. The whole distribution, including origins, behaviors, and Lambda@Edge functions, is modeled as a single CloudFormation resource; we can't modify an existing resource as-is in the CDK. This differs from many other `add*` methods in the CDK, where we are able to create entirely new resources that merely reference an existing resource.

One work-around would be to create a Custom Resource that reads the existing Distribution config (`GetDistribution`) adds the Lambda@Edge config, and then updates the Distribution (`UpdateDistribution`).

Closing this out as this isn't currently supported; feel free to mention me if you have any follow-ups.

**Comment by afenton90** [comment]
Thanks for the prompt reply @njlynch I'll take a look at that workaround
