### ISSUE TITLE
(imagebuilder): CfnImagePipeline is allowed in CDK without a container or image arn but fails during cloudformation

### ISSUE THREAD

**Issue by ssypi** [aws/aws-cdk#14486]
### The Question

This is pretty much only a minor typing/validation issue with CfnImagePipelineProps supplied to CfnImagePipeline constructor, not a serious issue.

Both imageRecipeArn and containerRecipeArn are set as optional in CfnImagePipelineProps and the deploy is allowed without either of them, but it will fail in cloudformation. 

Yes this is minor and a silly mistake to make, because obviously you need to supply the pipeline with something to build, but still I managed to make it (whoops) since I was just using IDE to autofill required fields and even the error from cloudformation was a bit cryptic.
"Resource handler returned message: "Model validation failed (#: #: only 1 subschema matches out of 2)"

CfnImagePipeline should require one of them in the ts typing and/or during validation(?).

### Environment

  - **CDK CLI Version:1.101.0 (build 149f0fc)** 
  - **Module Version:1.101.0** 
  - **Node.js Version:15.14** 
  - **OS:all** 
  - **Language (Version):TypeScript**

**Comment by peterwoodworth** [comment]
Hey @ssypi, thank you for this submission!

Our L1 constructs (constructs that start with Cfn) are auto-generated from the [CfnSpec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html), which includes whether resources are required or not in the specification. Looking at the [ImagePipeline docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagepipeline.html) on Cfn, it looks like neither of these are required.

Because our L1 constructs are autogenerated from Cfn, there isn't anything we can do to fix this on our end. We could cut a ticket with Cfn to handle this though, as there is precedence for [resources being conditionally required](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html#aws-resource-apigatewayv2-api-properties). Is this something you'd like us to do?
