### ISSUE TITLE
@aws-solutions-constructs/aws-lambda-sqs: Can't subscribe imported lambda to SQS Queue

### ISSUE THREAD

**Issue by retka** [aws/aws-cdk#14532]
### The Question
Hey there, I'm trying to subscribe a lambda function to an SQS queue using the SqsToLambda construct, or other methods. The Queue is created in the stack I'm trying to create the subscription in, but the lambda is created in another stack, written in Java, and imported via arn. I get an error about the execution role not having SQS ReceiveMessage permissions.

### Environment

  - **CDK CLI Version:** 1.96.0
  - **Module Version:** 1.96.0
  - **Node.js Version:** v14.16.1
  - **OS:** Mac OS HighSierra 10.13.6
  - **Language (Version):** TypeScript (3.9.7)

### Other information
The error: 
```
11:38:22 AM | CREATE_FAILED        | AWS::Lambda::EventSourceMapping | TestLam...ue96E91DC79FABBFAF
Resource handler returned message: "Invalid request provided: The provided execution role does not have permissions
to call ReceiveMessage on SQS (Service: Lambda, Status Code: 400, Request ID: ...,
Extended Request ID: null)" (RequestToken: ..., HandlerErrorCode: InvalidRequest)
```
Code to import lambda function and create subscription/give permissions: 

```
var importedLambda = <lambda.Function> lambda.Function.fromFunctionAttributes(this, "ImportedLambda", {
  functionArn: [myFunctionArnHere],
  role: <iam.Role> Role.fromRoleArn(this, "LambdaRole", [myRoleArnHere])
});

new SqsToLambda(this, 'EmailQueueToEmailLambda', {
  existingLambdaObj: importedLambda,
  existingQueueObj: mySqsQueue
});
```

We've also tried, alternatively, creating the permissions and subscription like so: 

```
mySqsQueue.grantConsumeMessages(importedLambda);
importedLambda.addEventSource(new SqsEventSource(mySqsQueue));
```

That version, where we call `mySqsQueue.grantConsumeMessages` and `importedLambda.addEventSource` will actually work, but only if we deploy first with only the `grantConfumeMessages`, and then add the `addEventSource` line and deploy again. If we do both at once from scratch, we get an error.

We've also confirmed that if we create a lambda function in our stack, rather than importing it, none of these issues occur: 

```
let testLambda = new lambda.Function(this, 'testLambda', {
  runtime: lambda.Runtime.NODEJS_14_X,
  handler: 'index.handler',
  code: lambda.Code.fromAsset('my-stack/lambda/batching')
});
```

**Comment by krazykhris875** [comment]
We've been able to get it working like so: 

```
const importedLambdaConsumeQueuePermissions = mySqsQueue.grantConsumeMessages(importedLambda);
importedLambda.addEventSourceMapping("LambdaTriggerFromQueue", {
  eventSourceArn: mySqsQueue.queueArn
}).node.addDependency(importedLambdaConsumeQueuePermissions);
```

We tried that yesterday but frankly just didn't do it quite correctly.

I'm wondering, how come `lambda.Function.addEventSource` returns void rather than returning the construct, like `.addEventSourceMapping` does? Perhaps there's a good case to change that?

Similarly, the SqsToLambda construct could be easily modified to utilize this `.addEventSourceMapping` method, with a dependency, so that it would work in these situations, too. I would be interested in putting in a pull request for either of these things, if they're agreed as good actions to take.

I'm also generally very curious why this doesn't happen with lambdas that are actually _created_ within the stack, rather than imported. I'm guessing it's something to do with CloudFormation caching the state of the lambda function, ie its permissions, rather than reading it every time? And then it "can tell" that it needs to do things in the correct order? I'm far from an expert and at this point it doesn't exactly matter, I'm just really wondering!

**Comment by MrArnoldPalmer** [comment]
So from what I'm understanding, this looks like an issue where permissions aren't correctly granted to the lambda role, which is defined in another stack. Resources imported from other stacks can't be mutated, so if this involves changing the policy of an imported role, that won't work because then the stack defining the role no longer knows about changes to the state of a resource it owns.

I believe the reason why your second solution works is that an event source mapping is a new resource, and `mySqsQueue.grantConsumeMessages` adds to the queue resource policy and doesn't touch the imported lambda or lambda role.

Does that answer your question? There may be changes that we could make on the L2 level to allow this to work but it would require some investigation.

**Comment by krazykhris875** [comment]
Hey, thanks for your response!

> Resources imported from other stacks can't be mutated, so if this involves changing the policy of an imported role, that won't work because then the stack defining the role no longer knows about changes to the state of a resource it owns.
> 
> I believe the reason why your second solution works is that an event source mapping is a new resource, and mySqsQueue.grantConsumeMessages adds to the queue resource policy and doesn't touch the imported lambda or lambda role.

This does not seem to be correct. Although yes, you are understanding the _problem_ correctly. Having deployed the above solution, I can see that it's not just the SQS Queue/policy that has been modified, but the imported lambda's IAM role has been changed as well, which is what we intended. 

And we've even done the reverse of this in another situation: imported a queue and created a subscription to it from a lambda that was not imported, and that worked as well.

**Comment by MrArnoldPalmer** [comment]
hmm alright, I need to investigate this some more. If you spot a solution feel free to make a PR in the meantime. TY!

**Comment by kevin-mitchell** [comment]
FYI I ran into this same issue today. Originally I thought I had failed because I had used `Function.fromArn(...` which didn't carry the role info, but I attempted to use `fromFunctionAttributes` to include the `Role` and still ended up with the same result.

I using the solution @retka mentioned also resolved the issue for me, or at least resulted in a successful deployment.
