### ISSUE TITLE
Docs should not recommend installing cdk with -g (globally)

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#14540]
https://docs.aws.amazon.com/cdk/latest/guide/work-with.html#work-with-prerequisites recommends installing cdk and typescript with -g.

As someone who cares about reproducible builds and knows little about node.js, I found this page 100x more useful than the official docs: 

https://www.endoflineblog.com/cdk-tips-01-how-to-use-local-cdk-commands

That says to use `npx` to init a new project, and `npm run cdk` afterwards.  (And `npm ci` to reinstall cdk for an existing project)

I made myself this shell alias and it has raised my productivity immensely:
    
    alias ncdk='npm run cdk --'
   
I think the default README.md generated by new projects should also say `npm run cdk` instead of `cdk`. 

It makes no sense to recommend global cdk installs especially when you are releasing an incompatible major version 2 as we speak.  Global tooling installs is also a violation of 12factor.net (point 2).

**Comment by Jerry-AWS** [comment]
Installing the CDK Toolkit (the `aws-cdk` Node package a.k.a. "the CLI") globally is fine since it's not actually a dependency of CDK apps, but rather a tool used to work with them. Newer versions are backward compatible with old ones, so you'll always be able to synth and deploy with the latest version of the Toolkit. There's no reason to have a duplicate copy of the `cdk` command in every CDK project.

There's also a bit of a chicken-and-egg situation with using a local `aws-cdk` in a new project... you need to install the `aws-cdk` package so you can initialize the project, but `cdk init` requires an empty directory, and there's `node-modules` in it already. Of course, you can make CDK projects without `cdk init` if you want (or we could change the CDK Toolkit to count a directory that contains only `node-modules` as empty, of course).

The point about v2 is valid, though. The v2 CLI will synth and deploy v1 apps without any difficulty, but initializing a new project will assume the v2 library structure in both `package.json` and the actual code, which is problematic if you're actually trying to create a v1 project.  We should probably add some templates for initializing v1 apps with v2 CLI. I'll make a separate issue for this.

**Comment by kjpgit** [comment]
I ran into this earlier:

    This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
    (Cloud assembly schema version mismatch: Maximum schema version supported is 5.0.0, but found 10.0.0)

This is completely avoided by using `npm ci` to install the cdk in node_modules.  It shouldn't take two steps and guesswork to deploy an app you just downloaded.

If people were capable of guaranteeing compatibility, the 12factor guideline wouldn't exist.

**Comment by skinny85** [comment]
<img width="1054" alt="Screen Shot 2021-05-11 at 1 40 20 PM" src="https://user-images.githubusercontent.com/460937/117881735-75535e80-b25e-11eb-85c6-1a54b6595619.png">

**Comment by skinny85** [comment]
> @skinny85 If TypeScript is not installed globally, there's no `tsc` command, and the `scripts` defined in the default `package.json` break. We could of course change `package.json`...

@Jerry-AWS that's not how `package.json` files work. They do not use global commands - they use commands that are found in the `node_modules/.bin` directory, which gets automatically added to the PATH when executing a script from them.

More information: https://docs.npmjs.com/cli/v7/using-npm/scripts#path

So, as long as there is a dependency in the `package.json` file on the `typescript` package (which our init templates do add), the `tsc` command will be available from there.

**Comment by Jerry-AWS** [comment]
@skinny85 Hm, learned something new today! In that case, since we're already installing a local copy of `typescript` in every TS project, there's no reason at all to install it globally. There are some places where `tsc` is used in the dev guide, but those are easily replaced with `npm run build`.

I see `aws-cdk` is in there too, so you can already use `npm run cdk` in place of `cdk`... but only in TS/JS projects. I can add a section about that in the "Working with the CDK" topics. I don't necessarily like having two sets of commands (one for for TS/JS, one for other languages), though. Maybe the guide needs to suggest a `cdk` alias for TS/JS developers.

**Comment by skinny85** [comment]
> Maybe the guide needs to suggest a cdk alias for TS/JS developers.

Sure. That makes sense.

**Comment by Jerry-AWS** [comment]
My intended approach is:

* No longer recommend installing TypeScript globally since it is already a dependency. Change TypeScript build instructions to use `npm run build`. CDK v2 topic says you need a particular version of TypeScript which at least needs a note that you only need to worry about that if you're using a globally-installed TypeScript, which you shouldn't.
* In the "Working with the CDK in TypeScript" and "...JavaScript" topics, note that you'll need a global install of the CDK Toolkit to initialize projects, but that you should use `npm run cdk` to use the local copy with individual projects.

**Comment by hoegertn** [comment]
If you use `npx cdk` it will use the locally installed one and if non is existent it will temporarily install a global one for this call, which is perfect for `cdk init`.

Regarding `tsc`: It is not needed at all for CDK projects as the cdk.json runs the app with ts-node
