### ISSUE TITLE
cdk.Include: support passing in parameters to included template

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1454]
Users expect to be able to pass in parameters to the included template

**Comment by arvindshekar07** [comment]
I too have a similar issue.

**Comment by piotrkubisa** [comment]
I guess it relates to #1237

**Comment by jeshan** [comment]
I found a simple workaround (Python only):

```python
from cfn_tools import load_yaml # or load_json
template = load_yaml(open('templates/your-template.yaml').read())
```
From there, you can manipulate the template as you please, e.g set the default value to the desired value:

```python
template['Parameters']['YourParam']['Default'] = 'YourValue'
```

It leverages AWS's cfn-flip library: `pip install cfn_flip`

**Comment by ilepadatu-pentalog** [comment]
We need this feature. The problem inherent with Default is that in Cloud Formation the value of the Default field cannot reference the output of another template. 
That is, if I want to pass to a cfn template parameter the output of of another template, I am unable to, due to CloudFormation limitations.
The work-around is to modify the template, that is remove all the parameters declarations that should accept references and replace the statements where they are assigned with the references from another stack by loading the template into a variable, pretty much as @jeshan described (I used json instead). But the template will never work as it was edited...
I find this very useful in case one wants to embed already existing cfn templates in their cdk code and leave the templates clean to have a way of passing outputs from cdk stack as input parameters to an already existing template without modifying it.

**Comment by skinny85** [comment]
This is now possible with the new [cfn-include module](https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html#parameters).

Resolving, please let us know if there's anything else we can do for this issue.
