### ISSUE TITLE
aws-cdk-lib: can `constructs` types be exported for typescript

### ISSUE THREAD

**Issue by codyfyi** [aws/aws-cdk#14704]
Using AWS CDK V2 with Typescript, I found that types from the `constructs` module must be individually imported.

**Example**
```typescript
import * as cdk from 'aws-cdk-lib'
import { Construct } from 'constructs';  // why can't these be exported from `aws-cdk-lib`?

class RootStack extends cdk.Stack {
  constructor(parent: Construct, name: string, props?: cdk.StackProps) {
    super(parent, name, props)
  }
}
```

### Use Case

A great benefit of CDK V2 is that it consolidates the AWS Construct Library into a single package. This should also apply to the types. I'm totally fine with keeping `constructs` as its own module, but would love the simplicity of just importing `aws-cdk-lib` and having everything I need.

### Proposed Solution

**Example**
```typescript
import * as cdk from 'aws-cdk-lib'

class RootStack extends cdk.Stack {
  constructor(parent: cdk.Construct, name: string, props?: cdk.StackProps) {
    super(parent, name, props)
  }
}
```

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
This was an intentional design decision we made in order to develop the `construct` model separately from the AWS CDK. There are a number reasons for this decision, one of them is allowing the development of other "CDK", such as [`cdk8s`](https://cdk8s.io/), [terraform-cdk](https://github.com/hashicorp/terraform-cdk).
