### ISSUE TITLE
(aws-cdk): How to upgrade cdk to new versions in general?

### ISSUE THREAD

**Issue by shubham391** [aws/aws-cdk#14710]
### The Question
I'd like to know the procedure to upgrade cdk to newer versions when they are released. I started working with cdk version `1.94.1` in a java project with both, the cdk cli and cdk dependencies (version in pom.xml), set to `1.94.1`. Then I upgraded to version `1.98.0` in the following manner:
- Updated cdk cli to 1.98.0 (by reinstalling cdk using npm)
- Updated version in pom.xml (maven)
- Running `cdk diff` on the project to ensure the new version is working fine. This shows some changes in S3 bucket descriptions (which are created by cdk itself) but my stack remains unchanged.

Following above steps I've been updating the versions regularly and was on `1.102.0` when `1.103.0` got released. I followed the same steps but this time doing `cdk diff` showed the following error:
```
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0)
```

I waited for another cdk version to come out. With `1.104.0` released, I updated the cli to this version and updated the version in cdk dependencies (maven), and got the same error (with different schema version message).

As a workaround, I uninstalled cdk as well as node and deleted all the local files (.npm and .cdk). Installed node and cdk again, this resolved the problem. But I'm not sure what the root cause of the issue is, and whether the steps I've been following to update are right.

It will be very helpful if you could guide me on the right way to update. A few other users (on cdk slack) had also faced this issue so it will help the cdk community in general.

Thank you!

### Environment

  - **CDK CLI Version:** 1.103.0 (build bc13a66), 1.104.0 (build 44d3383)
  - **Module Version:** aws-cdk
  - **Node.js Version:** v16.1.0
  - **OS:** macOS Big Sur
  - **Language (Version):** Java (8)

**Comment by gshpychka** [comment]
This happens to me as well after every CDK upgrade. My CDK CLI is always the latest version (matching the constructs version), and reinstalling the CDK CLI helps.

**Comment by peterwoodworth** [comment]
Hey @shubham391, sorry for the long response time. I hope the other threads ([here](https://github.com/aws/aws-cdk/issues/14738) and [here](https://github.com/npm/cli/issues/3196)have been able to help you for this specific issue regarding the version mismatch error, especially with determining the root cause of this particular issue. Npm took ownership of this issue and fixed the bug which created this issue: 

> If a node was included in a shrinkwrap, _but_ that shrinkwrap lacked
resolved and integrity fields, then updating the shrinkwrapping node
would not properly diff the children, treating any updates to them as a
`null` action, even if the version changed.

In general, the process I use for upgrading the CDK version is to `npm uninstall -g aws-cdk` then `npm install -g aws-cdk@latest`. If you want to upgrade an existing project, delete the necessary files (`node_modules` folder and `package-lock.json` for typescript projects) and update the version numbers in the configuration file (`package.json` for typescript). Then I run `npm install` to install the updated packages for my project.

Ping me if you need any more help with this!

**Comment by shubham391** [comment]
@peterwoodworth Thanks for your response. I ended up installing CDK via Homebrew rather than directly via npm. Upgrades happen just fine with Homebrew.
