### ISSUE TITLE
Deprecate the runtime values library (@aws-cdk/rtv)

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1473]
We have steered away from recommending that people will use SSM to pass in parameters to things like Lambda function and ECS (environment variables are a better choice). If we are looking for a generic solution we need to redesign it.

**Comment by mipearson** [comment]
Is the current recommendation to pass ENV vars via the CLI, and let people manage their secrets outside of CDK?

This is what we *sometimes* do, but usually because it's a thing that doesn't have AWS access (eg, Heroku). eg via https://github.com/Shopify/ejson2env

Any thoughts on management of secrets that are too secret to put in a CFN template generated by CDK? eg - I'd be fine with putting a private gist url or slack api endpoint in a template, but less so with (say) database passwords or a Braintree API key
