### ISSUE TITLE
(aws-ecs): Can't enable both Fargate and ASG capacity providers

### ISSUE THREAD

**Issue by hnrc** [aws/aws-cdk#14730]
According to [the ECS Cluster Capacity Providers docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-capacity-providers.html) it should be possible to have both Fargate and ASG powered capacity providers associated with a ECS cluster.

> _**A cluster may contain a mix of both Auto Scaling group capacity providers and Fargate capacity providers**, however a capacity provider strategy may only contain one or the other but not both._

This seem to not be the case with CDK. Cloudformation fails with a "The cluster already contains capacity provider associations" message when trying to provision a cluster that have both `enableFargateCapacityProviders` set to `true` and an ASG provided through `addAsgCapacityProvider(...)`.

### Reproduction Steps

```ts
const cluster = new Cluster(this, 'EcsCluster', {
  vpc,
  clusterName: props.clusterName,
  enableFargateCapacityProviders: true,
});

const autoScalingGroup = new AutoScalingGroup(this, 'Asg', {
  vpc,
  machineImage: EcsOptimizedImage.amazonLinux2(),
  instanceType: new InstanceType('t3.micro'),
  minCapacity: 1,
  maxCapacity: 100,
});

const capacityProvider = new AsgCapacityProvider(
  this,
  'AsgCapacityProvider',
  {
    autoScalingGroup,
    capacityProviderName: props.clusterName,
  },
);
cluster.addAsgCapacityProvider(capacityProvider);
```

### What did you expect to happen?

The CF stack to finish successfully and for the cluster to be associated with both Fargate and ASG capacity providers, thus allowing for a service to decide if it should run on EC2 or Fargate, in the same ECS cluster.

### What actually happened?

```
Resource handler returned message: "The cluster already contains capacity provider associations" (RequestToken: 5c5f5982-c7d4-37ae-535a-92833ee7bef6, HandlerErrorCode: AlreadyExists)
```

### Environment

  - **CDK CLI Version:** 1.104.0
  - **Framework Version:** 1.104.0
  - **Node.js Version:** 14.16.1
  - **OS:** MacOS 10.15.7
  - **Language (Version):** Typescript 4.2.4

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
The issue here is that we are specifying the FARGATE and FARGATE_SPOT capacity providers as a member of the Cluster resource, but creating [ClusterCapacityProviderAssociations](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-clustercapacityproviderassociations.html) for the ASG capacity providers. In order for this to work with cloudformation, all of the capacity providers need to be specified either in the [Cluster.CapacityProviders](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-capacityproviders) field OR on the [ClusterCapacityProviderAssocitations.CapacityProvider](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-clustercapacityproviderassociations.html#cfn-ecs-clustercapacityproviderassociations-capacityproviders) field. Working on a fix!
