### ISSUE TITLE
stepfunctions-tasks: StepFunctionsStartExecution should add AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID

### ISSUE THREAD

**Issue by iOnline247** [aws/aws-cdk#14778]
It'd be nice to have a property that'll add the `AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID` to the input payload.

### Use Case

This will make it easy to add the `AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID` to the input payload.

### Proposed Solution

```js
    const finalTransformExecution = new StepFunctionsStartExecution(
        scope,
        'Final Transform',
        {
            stateMachine: finalTransformSfn,
            integrationPattern: IntegrationPattern.RUN_JOB,
            // Proposed property, but horrible name. ;)
            addStartedById: true,
            outputPath: '$.Output',
        },
    );
```

### Other

This would assist in removing some of the workarounds I've implemented to get this to work. https://github.com/aws/aws-cdk/issues/14777

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@iOnline247 thanks for adding this feature request. I agree it would be useful to have native support for it.

**Comment by hassanazharkhan** [comment]
@shivlaks Can I pick this up?

**Comment by BenChaimberg** [comment]
@hassanazharkhan yes, please feel free to open a PR for this feature. I think an appropriate name for the property would be `associateWithParent` and it should default to `true`

**Comment by kaizen3031593** [comment]
I could be way off base here as I'm trying to understand stepfunctions as a whole still, but it seems odd to have both an `input` property and the proposed `associateWithParent` property on `StepFunctionsStartExecutionProps`. It also seems nontrivial to implement, since `associateWithParent` would then be tasked with modifying the `input` property (which may or may not exist).

Instead, would it make more sense to add a new static method in `JsonPath` like what we do for `taskToken()`? 

https://github.com/aws/aws-cdk/blob/3e9f04dbbd7aadb8ab4394fefd6281f1d6d30fe0/packages/%40aws-cdk/aws-stepfunctions/lib/fields.ts#L67-L69

Something like:

```ts
public static get executionId(): string {
  return new JsonPathToken('$$.Execution.Id').toString();
}
```

Then the interface would look like this:

```ts
const task = new StepFunctionsStartExecution(this, 'Task', {
  stateMachine,
  input: sfn.TaskInput.fromObject({
    AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID: sfn.JsonPath.executionId,
    token: sfn.JsonPath.taskToken, // this is how taskToken is used in the tests
  }),
}
```

Tasktoken seems to be one of the other keys modeled in the `input` property so I figure it makes sense to follow the implementation for that. Am I missing anything here? Happy to take on this issue since I've already invested time in researching this. @BenChaimberg can you take a look?

**Comment by BenChaimberg** [comment]
I agree this is nontrivial, but I still think possible. We have information about whether `TaskInput` is from a constructed object or directly taken from a JSON path. This means we can decide whether or not to support `associateWithParent` based on what is passed in for `input`. Something like:

```ts
class StepFunctionsStartExecution {
  constructor(...) {
    // ...
    if (this.props.associateWithParent && this.props.input.type !== sfn.InputType.OBJECT) {
      throw new Error('Could not associate child execution with parent execution because input is taken directly from a JSON path. Use `sfn.TaskInput.fromObject` instead');
    }
  }

  _renderTask(): any {
    const associateWithParentEntry = this.props.associateWithParent ? {
      AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID: sfn.JsonPath.stringAt('$$.Execution.Id'),
    } : {};
    const input = this.props.input ? { ...this.props.input, ...associateWithParentEntry } : associateWithParentEntry;
    return {
      // ...
      Parameters: {
        Input: input,
        // ...,
     };
  }
}
```

I think a `executionId` static property of `JsonPath` is a great idea too! Just not a good replacement for this feature IMO

**Comment by kaizen3031593** [comment]
I can do that too! I was wary about `associateWithParent` along with a non Object `input` but throwing an error there makes so much sense.
