### ISSUE TITLE
(aws-cdk): Roadmap or Timeline for AppRunner Support

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#14779]
### The Question

I'd like to raise the issue of App Runner support https://aws.amazon.com/apprunner/ in CDK. Terraform already has support for this, and I'd love to see it available in CDK. Is there a roadmap or timeline which has not been made public for adding support for this very cool AWS service?

### Environment

  - **CDK CLI Version:** n/a
  - **Module Version:** n/a
  - **Node.js Version:** n/a
  - **OS:** all
  - **Language (Version):** all

**Comment by peterwoodworth** [comment]
Hey @shellscape,

The CDK works by synthesizing code to a CloudFormation document. Since [CloudFormation doesn't support AppRunner yet](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html), this is out of our hands. I encourage you to take this issue to the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap) and submit a request there (on a quick glance I couldn't find any requests for it yet). Hope this helps!

**Comment by shellscape** [comment]
Will do, thank you for the follow up. Out of curiosity, how far behind new CF features does CDK typically run?

**Comment by peterwoodworth** [comment]
Our L1 constructs are automatically generated by the [Cfn Resource Spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). So whenever Cfn implements these we would lag behind by a week at most, depending on merging the new resource spec and when the new CDK version gets released

**Comment by shellscape** [comment]
Outstanding. Thank you

**Comment by nmduarteus** [comment]
Hi @peterwoodworth - this would be a great addition.

Seems that CFN already supports AppRunner - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html 

thanks!
