### ISSUE TITLE
(apigatewayv2): Change `defaultStage` to an `IHttpStage`

### ISSUE THREAD

**Issue by hffmnn** [aws/aws-cdk#14787]
### The Question

Via https://github.com/aws/aws-cdk/pull/14541 the `metricXXX` method moved from `IStage` to `IHttpStage`. The `defaultStage` of a `HttpApi` returns a `IStage`, so the methods are not available.

Question: How to access the methods of the default stage?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** `> 1.103.0`
  - **Node.js Version:** v12.19.0
  - **OS:** macOS BigSur
  - **Language (Version):** TypeScript (4.2.4)

### Other information

When casting `api.defaultStage! as IHttpStage;` and calling the `metricXXX` methods generate the expected code, so I guess the `defaultStage` could return `IHttpStage` directly?

**Comment by peterwoodworth** [comment]
I don't think there's currently any way to access the `methodXXX` functions on property `defaultStage` when using an `HttpApi`.

https://github.com/aws/aws-cdk/blob/ae24d8a700b280bc90d2b681a6c7480d7833aaa2/packages/%40aws-cdk/aws-apigatewayv2/lib/http/api.ts#L430-L435

This is where the CDK creates the default `HttpStage`. However, since the property is declared as an `IStage `https://github.com/aws/aws-cdk/blob/ae24d8a700b280bc90d2b681a6c7480d7833aaa2/packages/%40aws-cdk/aws-apigatewayv2/lib/http/api.ts#L368 that is the only part of the `HttpStage` which prevents you from being able to access the methods.

I don't see why the property can't directly return the `IHttpStage`, @nija-at was it intentional to remove the methods here? Seems like the change was only related to the WebSocket

**Comment by peterwoodworth** [comment]
I'll be closing this now because the workaround I posted above is pretty simple. If anyone would like to revisit changing the `defaultStage` prop to an `IHttpStage` ping me and let me know 😄

**Comment by hffmnn** [comment]
@peterwoodworth Personally I would not close it and label it as `good first issue` instead.

**Comment by peterwoodworth** [comment]
you're right, relabeled as a feature request
