### ISSUE TITLE
(aws-iam): deploy AWS services at separate AWS account

### ISSUE THREAD

**Issue by mandel-drink** [aws/aws-cdk#14807]
Hi, 

I have a general question about deploying AWS services (like DynamoDB) at a separate account by using CDK (please see image). Could you please share some guidance or directions on how to achieve this? Thank you.

![image](https://user-images.githubusercontent.com/78983350/119043673-941dc780-b9b9-11eb-8ad1-487ec5e5b9aa.png)

**Comment by rix0rrr** [comment]
Define a `Stack` with a different `account` parameter.

The next question is how to get proper permissions. [Modern bootstrapping](https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html) (using `--trust`) and the `DefaultStackSynthesizer` will provide you with roles so that you can `cdk deploy` directly into both accounts.

Otherwise, you will have to assume credentials to both accounts separately and use `cdk deploy -e` one by one.
