### ISSUE TITLE
(aws-quicksight): CfnDataSource.RedshiftParametersProperty will not accept dynamic references for "port"

### ISSUE THREAD

**Issue by akuma12** [aws/aws-cdk#14824]
When trying to create a Quicksight Redshift CfnDataSource resource, we have our Redshift connection information stored in SecretsManager, including endpoint, port, database name, username and password. When we try to use CDK's SecretsManager.secretValueFromJson(), it generates a CloudFormation {{resolve:secretsmanager}} dynamic reference. However, when CDK tries to synthesize the template, the CfnDataSource.DataSourceParameters.RedshiftParameters class requires port to be an Int, while the {{resolve}} string is a string, and it will fail synthesis with `port: "{{resolve:secretsmanager:arn:aws:secretsmanager:us-west-2:123456789012:secret:dummy-ABC123:SecretString:port::}}" should be a number.`

### Reproduction Steps

Create a Quicksight CfnDataSource and use SecretsManager to fill in the parameters:

```python
        quicksight.CfnDataSource(
            self,
            'redshiftDatasource-id',
            aws_account_id = core.Aws.ACCOUNT_ID,
            data_source_id = 'redshift',
            name = 'redshift-datasource',
            type = 'REDSHIFT',
            data_source_parameters=quicksight.CfnDataSource.DataSourceParametersProperty(
                redshift_parameters=quicksight.CfnDataSource.RedshiftParametersProperty(
                    host=redshift_secret.secret_value_from_json("endpoint").to_string(),
                    database=redshift_secret.secret_value_from_json("database").to_string(),
                    port=core.Token.as_number(redshift_secret.secret_value_from_json("database")),
                )
            ),
            credentials=quicksight.CfnDataSource.DataSourceCredentialsProperty(
                credential_pair=quicksight.CfnDataSource.CredentialPairProperty(
                    username=redshift_secret.secret_value_from_json("username").to_string(),
                    password=redshift_secret.secret_value_from_json("password").to_string()
                )
            )
        )
```

### What did you expect to happen?

The port field would accept a dynamic reference as well as a number.

### What actually happened?

Synthesis failed with `port: "{{resolve:secretsmanager:arn:aws:secretsmanager:us-west-2:123456789012:secret:dummy-ABC123:SecretString:port::}}" should be a number.`

### Environment

  - **CDK CLI Version  :** 1.103.0
  - **Framework Version:** 1.102.0
  - **Node.js Version:** 14.16.0
  - **OS               :** MacOS 11.2.3
  - **Language (Version):** Python 3.8.5

--- 

This is :bug: Bug Report

**Comment by akuma12** [comment]
I tested this with CDK CLI version 1.105.0 and Framework version 1.105.0 as well with the same result.

**Comment by peterwoodworth** [comment]
Hey @akuma12, 

Our L1 constructs (`CfnXxx`) are automatically generated from the [CloudFormation Resource Spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). The [`DatasourceRedshiftParameters::Port`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-datasource-redshiftparameters.html#cfn-quicksight-datasource-redshiftparameters-port) property in CloudFormation requires inputting a number, so we can't also have it accept a dynamic reference because 

It looks like you're calling "database" instead of "port". Did you mean to do this? You say you have the port in your secrets manager, and since you're calling Token.as_number it should be synthesizing as a number. 

Either way, this isn't a bug and you'll have to find some way to get just the port number here. Let me know if you need help with this!

**Comment by peterwoodworth** [comment]
Hey @akuma12, this might actually be an issue on our end, apologies for the earlier guidance. I believe you're getting your secret using the `from_secret_complete_arn()` method since we were able to reproduce the issue you gave with that method. A quick workaround will get you up and running in the meantime while we research the root cause of this issue:

```
redshift_secret = secretsmanager.Secret.from_secret_complete_arn(self, 'RedshiftSecret',
    f'arn:{core.Aws.PARTITION}:secretsmanager:us-west-2:123456789012:secret:dummy-ABC123')
```

**Comment by akuma12** [comment]
> Hey @akuma12, this might actually be an issue on our end, apologies for the earlier guidance. I believe you're getting your secret using the `from_secret_complete_arn()` method since we were able to reproduce the issue you gave with that method. A quick workaround will get you up and running in the meantime while we research the root cause of this issue:
> 
> ```
> redshift_secret = secretsmanager.Secret.from_secret_complete_arn(self, 'RedshiftSecret',
>     f'arn:{core.Aws.PARTITION}:secretsmanager:us-west-2:123456789012:secret:dummy-ABC123')
> ```

@peterwoodworth Yeah sorry, I should have mentioned how I was getting the secret. I'm using Secret.from_secret_attributes, but passing in the `secret_complete_arn` along with the `encryption_key` as we used a custom KMS key for encryption. Thanks very much for looking into this! It seemed odd as I've been able to use `core.Token.as_number()` for other constructs that required number inputs.

**Comment by skinny85** [comment]
Yes, because this is a bug 🙂 https://github.com/aws/aws-cdk/pull/14913
