### ISSUE TITLE
(aws-elasticloadbalancingv2): Getting error when binding a Lambda Target to an imported ALB TargetGroup.

### ISSUE THREAD

**Issue by pravin0999** [aws/aws-cdk#14827]
I'm getting error when I bind a Lambda Target to an **imported** ALB TargetGroup when building through CDK.
```
throw new Error('Cannot add a non-self registering target to an imported TargetGroup. Create a new TargetGroup instead.');
```

### Reproduction Steps

```
export interface SampleLambdaProps{
    deploymentEnv: DeploymentEnvironment;
    envStage: string;
}

export class SampleLambdaStack extends DeploymentStack {
    public readonly function: LambdaFunction;

    constructor(scope: Construct, id: string, lambdaFunctionProps: SampleLambdaProps) {
        super(scope, id, {
            softwareType: SoftwareType.INFRASTRUCTURE,
            env: lambdaFunctionProps.deploymentEnv,
        });

        var sample_function = new LambdaFunction(
            this,
            `sampleLambda-${lambdaFunctionProps.envStage}`,
            {
                functionName: 'SampleLambda',
                handler: 'com.amazon.samplelambda.lambda.LambdaRequestHandlerWrapper::handleRequest',
                code: `SampleLambda-1.0`,
                componentName: 'SampleLambda',
                }),
                role: Role.fromRoleArn(
                    this,
                    `${id}-SampleLambdaIAMArn`,
                    `arn:aws:iam::000000000:role/SampleLambdaRole`,
                ),
                memorySize: 1024,
                runtime: Runtime.JAVA_11,
                timeout: Duration.minutes(1)
            },
        );

        const albTargetGroup = ApplicationTargetGroup.fromTargetGroupAttributes(
            scope,
            `${id}SampleAlbTargetGroup`,
            {
                targetGroupArn: 'sampleAlbTargetGroupArn',
            },
        );

        // Adding Gateway lambda to the ALB TargetGroup.
        const lambdaTarget = new LambdaTarget(sample_function);
        albTargetGroup.addTarget(lambdaTarget)

    }
}
```

### What did you expect to happen?

I expect to bind the Lambda to the imported ALB.

### What actually happened?

Getting error - 

```
throw new Error('Cannot add a non-self registering target to an imported TargetGroup. Create a new TargetGroup instead.');
```

### Environment

  - **OS:** - OSX
  - **Framework Version:** - `"aws-cdk": "2.0"`
  - **Node.js Version:** 
  - **Language (Version):** 
```
  "devDependencies": {
    "@types/node": "*",
    "@types/jest": "24.0.23",
    "@typescript-eslint/eslint-plugin": "^4.15.0",
    "@typescript-eslint/eslint-plugin-tslint": "^4.15.0",
    "@typescript-eslint/parser": "^4.15.0",
    "babel-jest": "24.9.0",
    "eslint": "6.7.2",
    "eslint-config-prettier": "6.7.0",
    "jest": "24.9.0",
    "jest-resolve": "24.9.0",
    "prettier": "1.19.1",
    "ts-jest": "24.2.0",
    "ts-node": "8.1.0",
    "tslint": "5.20.1",
    "typescript": "~4.0.5"
  },
```

### Other

We tried the same operation of binding the ALB TargetGroup with the Lambda at the AWS CLI using - 

```
aws elbv2 register-targets \ 
    --target-group-arn [sample target group's ARN] \ 
    --targets Id=[sample Lambda function's ARN]
```

and the operation was successful. 

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Sorry for the delay in response here.

The error here reflects a general limitation of CloudFormation, and by extension, the CDK. We generally cannot edit the definitions of existing, imported resources (without resorting to creating CloudFormation custom resources which make SDK calls). Adding a Lambda function to an app target group is accomplished by updating the [`targets`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-targets) property of the TargetGroup, but we can't edit the TargetGroup because it's imported and there is no resulting YAML/JSON in the template to update. This is what the error message is communicating.

One suggestion (if the ALB and Function are in separate stacks) is to flip the direction; pass the Function arn to the ALB stack, and attach an imported Function.
