### ISSUE TITLE
(aws-sqs): Granting "send message" doesn't grant SendMessageBatch privileges

### ISSUE THREAD

**Issue by troyaws** [aws/aws-cdk#14830]
Granting "send message" doesn't grant sqs:SendMessageBatch privileges.

### Reproduction Steps

```
queue = sqs.Queue(
    self, "items",
    visibility_timeout=core.Duration.seconds(300),
)
queue.grant_send_messages(lambdaFunction)
```

### What did you expect to happen?

I expected that all SQS API actions for sending messages would be included in the inline policy attached to the Lambda function's role.

### What actually happened?

Only sqs:SendMessage, sqs:GetQueueAttributes, and sqs:GetQueueUrl were granted to the Lambda function.
```
       {
            "Action": [
                "sqs:SendMessage",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl"
            ],
            "Resource": "arn:aws:sqs:us-east-1:489466759351:whatsnew-app-items07D08F4B-L3JMVWUZHL4G",
            "Effect": "Allow"
        }
```

### Environment

  - **CDK CLI Version  :** 1.104.0 (build 44d3383)
  - **Framework Version:**
  - **Node.js Version:**  v16.1.0
  - **OS               :** MacOS
  - **Language (Version):**  Python 3.7

### Other

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
I can see your point but I don't know if that is actually the expected behavior. I think the question is more do most users who are calling `grantSendMessages` explicitly want `SendMessageBatch`? Maybe we need to add another method that is `grantSendBatch` so it is more explicit that `grantSend` doesn't include it, or add an optional property to `grantSendMessages` that allows users to specify including batch.

If this weren't a stable module I would probably say lets add it but my main concern is existing users who are expecting least permissions will have this show up in their apps and not want it.

**Comment by troyaws** [comment]
I don't think the ability to send one message per API call or 10 messages per API call is a privilege difference. I wouldn't expect that to be an issue for a "least privilege" approach. 

If you buy that argument, then I think the module should take the approach that makes it easiest on the developer and just grant all of the API actions that allow `SendMessage`. The other approaches you proposed are more complicated for users of the batch API. If you chose to take the approach of `grantSendBatch`, the `GetQueueUrl` and `GetQueueAttributes` actions should be included in the resultant policy.

**Comment by MrArnoldPalmer** [comment]
I agree with you mostly the thing that worries me is some edge case architectures that users may currently be employing.

For example, if I have a stack with a queue, and I don't control the producers and I may be explicitly not allowing batch send as a way to control the rate of message input. This is bad (really bad) architecture I'd argue but its still something to think about.

That being said I think we should just deprecate `grantSendMessages` and create `grantSend` that by default includes `SendMessageBatch`. This feels safest.

**Comment by ABevier** [comment]
I hit this issue with `DeleteMessageBatch` as well.  If I implement this is it cool if I also deprecate `grantConsumeMessages` and make `grantConsume` and `grantConsumeBatch` ?

**Comment by naveenthontepu** [comment]
The method name is confusing as `grantSendMessages` method name is plural then an implicit meaning of all permission related to sending messages have been provided which includes the `SendMessageBatch`. If the method name was just `grantSendMessage`(singular) then developers would not expect the batch permission to be given. 

Its better to have a crystal clear API instead of a confusing one.
