### ISSUE TITLE
(@aws-cdk/aws-s3module) Resource handler returned message: "Uploaded file must be  a non-empty zip"

### ISSUE THREAD

**Issue by max258-new** [aws/aws-cdk#14843]
### The Question

Hi I had tried few node versions mentioned below still appearing the same issue 
anyone can help me ? 

### Environment

  - **CDK CLI Version:** 1.59.0,1.85,1.70,1.105.0
  - **Node.js Version:** node 14.2.0,14.3.0,14.15.0,14.15.1,14.15.2,14.15.3,14.16.1,14.15.4,14.17.0,15.5.1,16.2.0
  - **OS:** Windows 10
  - **Language (Version):** TypeScript (4.2.4)

### Other information
 new S3Deployment.BucketDeployment(this, 'Deployment', {
      sources: [S3Deployment.Source.asset('.path')],
      destinationBucket: bucket
    });

**Comment by peterwoodworth** [comment]
Hey @max258-new, I see that you're inputting `.path` as your Source.asset. Do you have a local directory named `path` in your project? If so, you should input `S3Deployment.Source.asset('./path')` to the `sources` property.

What do you have in your `path` directory? What are you trying to use as the source?

**Comment by vw2408** [comment]
Hey @peterwoodworth  Thanks for your response
in that line I have 
```
sources: [S3Deployment.Source.asset('./src/script/')]
```
this path.

**Comment by max258-new** [comment]
Hey @peterwoodworth Thanks for your response
in that line I have
```
sources: [S3Deployment.Source.asset('./src/script/')]
```
this path.

**Comment by peterwoodworth** [comment]
Did you also do these two things?

> Delete the cached asset in the cdk.out/ directory. You could safely delete the entire directory, and the correct assets and templates will be re-generated during the next run of cdk synth or cdk deploy

> Delete the previously uploaded asset from the staging bucket. The S3 key of the asset will be prefixed with asset/ and have the hash of the asset. The hash of the asset can be found in your application's CloudFormation template.
The staging bucket can be obtained by running the following command -
 aws cloudformation describe-stack-resources --stack-name CDKToolkit --logical-resource-id StagingBucket  --query 'StackResources[].PhysicalResourceId'

**Comment by severn-everett** [comment]
This might be unrelated, but I am seeing this issue as well when using Node 16. Here are the contents of the Node-zipped lambdas:

Node 14.17.0:
![AWS_Lambda_Node_14_17_0](https://user-images.githubusercontent.com/12528881/120667968-4bbcda00-c48e-11eb-8264-6ac8a105fb69.png)

Node 16.2.0:
![AWS_Lambda_Node_16_2_0](https://user-images.githubusercontent.com/12528881/120668016-5aa38c80-c48e-11eb-90dc-eba3b55fa17d.png)

Node 16.3.0:
![AWS_Lambda_Node_16_3_0](https://user-images.githubusercontent.com/12528881/120668046-61ca9a80-c48e-11eb-8f86-a608eb096ca8.png)

Only the lambda in the archive created through Node 14.17.0 is accepted when I attempt to deploy via AWS CDK; the other archives are rejected with the same message that @max258-new posted. I suspect that this might be due to the changes that are at the base of the Node issue [here](https://github.com/nodejs/node/issues/37027); if this is the case, then the Node-based CDK code might need to be updated for use with Node 16 at some point.

**Comment by severn-everett** [comment]
Turns out the workaround for my issue is [this](https://github.com/serverless/serverless/issues/8772#issuecomment-825698908). The underlying dependency has already been fixed and upgraded; it would be good to incorporate the updated `archiver` dependency in CDK's `package.json` once the version bumps make their way up the chain.

**Comment by peterwoodworth** [comment]
> Check out [this thread](https://github.com/aws/aws-cdk/issues/12536) for more info

Thanks for your research and input into this @severn-everett, did you check the thread I linked above too? That has a bunch of good info in it, [including the solution you found](https://github.com/aws/aws-cdk/issues/12536#issuecomment-774678334). I know you've already fixed the issue, but I'm linking it in case you're curious and want to see more info :p

@max258-new are you still dealing with this issue?

**Comment by peterwoodworth** [comment]
Please ping me if you're still encountering this issue, thanks!
