### ISSUE TITLE
All: Strong Name Sign CDK Assemblies for .NET

### ISSUE THREAD

**Issue by philasmar** [aws/aws-cdk#14854]
### The Question

Hello,

We are trying to strong name sign our assemblies and we are facing an issue with the projects that are referencing the CDK.

"Referenced assembly 'Amazon.CDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name."

Can you please strong name sign your .NET assemblies?

Thanks

### Environment

  - **CDK CLI Version:** 1.102.0 (build a75d52f)
  - **Module Version:** All
  - **Node.js Version:** v14.16.1
  - **OS:** all
  - **Language (Version):** .NET

**Comment by peterwoodworth** [comment]
Hey @philasmar, sorry for the delayed response.

[We've decided to not use strong names](https://github.com/aws/aws-cdk/pull/12632). Microsoft doesn't recommend doing this anymore, so unfortunately this isn't something we'll be looking to add to the CDK. Apologies for the roadblocks you experience due to this decision
