### ISSUE TITLE
(aws-cdk/aws-ec2): unexpected behaviour passing AZs to vpc.selectSubnets

### ISSUE THREAD

**Issue by plumdog** [aws/aws-cdk#14888]
Selecting subnets by AZ appears not to work as I would expect. Selecting with
```typescript
vpc.selectSubnets({
    availabilityZones: [vpc.availabilityZones[0]],
})
```
works, but selecting with
```typescript
vpc.selectSubnets({
    availabilityZones: [this.availabilityZones[0]],
})
```
returns no subnets.
### Reproduction Steps

See https://github.com/plumdog/cdk-vpc-subnets-by-az-bug

Running `./get_outputs.sh` in that codebase prints the cloudformation outputs from the synth-ed template. The outputs using the former have a ref of a subnet, the outputs using the latter are empty.

### What did you expect to happen?

Selecting subnets by availability zone should work using AZs from `vpc.availabilityZones` and from `this.availabilityZones` just the same.

### What actually happened?

Using AZs from `vpc.availabilityZones` to do the subnet-selecting works. Using AZs from `this.availabilityZones` always selects zero subnets.

### Environment

  - **CDK CLI Version: 1.106.0**
  - **Framework Version: 1.106.0**
  - **Node.js Version: 14.16.1**
  - **OS: Linux**
  - **Language (Version): TypeScript 3.9**

### Other

I suspect this is something odd going on when comparing tokens. I have not been able to identify a change that might have caused this. I'm willing to attempt some bisecting on CDK versions to try to track such a change down.

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
This works if the stack isn't environment-agnostic (e.g., the AZs are looked up by context). It doesn't work in environment-agnostic stacks because the value of `Stack.availabilityZones` isn't memoized; each time you call it, you'll get back new tokens representing the `Fn::Select` and `Fn::GetAZs` function calls. So `vpc.availabilityZones` is set to _a_ call to `stack.availabilityZones`, and your call to `this.availabilityZones` returns a new set of tokens.

It's possible we can memoize the function call, which would enable this use case; a bit of a dive is probably necessary to determine if there would be any negative impact of that. Out of curiosity, what's the use case here? Is this actually blocking anything?

**Comment by plumdog** [comment]
@njlynch Thanks for your response. No, this is not blocking me as my workaround is achieving what I need.

I hit this because I have a VPC using 2 AZs, and an EKS cluster, and when I tried to deploy a nodegroup into the private subnets in each AZ I was told that I had passed no subnets, which surprised me, and chased it back to the simple example above.
