### ISSUE TITLE
Inconsistent member initialisation 

### ISSUE THREAD

**Issue by mooperd** [aws/aws-cdk#14925]
Hello,

I am struggling to understand why these enumerators are behaving so differently. I cant find any documentation that explains why. Please can I have some guidance.

Thanks,

Andrew

```
>>> ec2.SubnetType("ISOLATED")
<SubnetType.ISOLATED: 'ISOLATED'>
>>> 
>>> 
>>> rds.MysqlEngineVersion("VER_5_7_30")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrew/devops-542/cdk/venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: MysqlEngineVersion() takes no arguments
```

**Comment by peterwoodworth** [comment]
`MysqlEngineVersion` is a class and not an enum like [SubnetType is](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.SubnetType.html), so that's certainly a reason it's behaving differently.

You'll want to use the [`of()` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.MysqlEngineVersion.html#static-ofmysqlfullversion-mysqlmajorversion) for the `MysqlEngineVersion` class. Example here:

```ts
const version = rds.MysqlEngineVersion.of('5.7.30', '5.7')
console.log(version)
```
will output:
```
MysqlEngineVersion {
  mysqlFullVersion: '5.7.30',
  mysqlMajorVersion: '5.7'
}
```

Hope this helps!
