### ISSUE TITLE
aws-codepipeline-actions: Feature: allow use of deploy keys for GitHubSourceAction

### ISSUE THREAD

**Issue by chtpl** [aws/aws-cdk#14936]
Currently the Github Action can be configured this way:

```ts
// Read the secret from Secrets Manager
const sourceOutput = new codepipeline.Artifact();
const sourceAction = new codepipeline_actions.GitHubSourceAction({
  actionName: 'GitHub_Source',
  owner: 'awslabs',
  repo: 'aws-cdk',
  oauthToken: cdk.SecretValue.secretsManager('my-github-token'),
  output: sourceOutput,
  branch: 'develop', // default: 'master'
});
pipeline.addStage({
  stageName: 'Source',
  actions: [sourceAction],
});
```

I want to be able to use Github deploy keys instead of the OAuthToken

### Use Case

Due to compliance requirements we can't give AWS the permission to read all repos from Github which would be the case with an OAuth Token as far as I understoof

### Proposed Solution
Allow to specifiy deploy keys

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @chtpl,

I would try to provide CodePipeline with the deploy keys instead of the personal access token, and see if that possibly works.

Alternatively, you can use the [`CodeStarConnectionsSourceAction` class](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CodeStarConnectionsSourceAction.html) instead, and see if that works. If it doesn't, I'm worried there's not much we can do here - this is more of a CodePipeline limitation than anything the CDK can do here.

Thanks,
Adam

**Comment by peterwoodworth** [comment]
Closing this issue because the bot missed it and there's not much the CDK can do here. Please ping me if you have any additional concerns with this issue 😄
