### ISSUE TITLE
s3 setBucketAccelerateConfiguration Access Denied

### ISSUE THREAD

**Issue by pachicoo** [aws/aws-cdk#14973]
In existing accounts, I have enabled S3 Transfer Acceleration using Escape hatches, and it works perfectly.
A new account was created, and now I'm getting the Access Denied error only on that account.
The rest of the infrastructure was created without error.

### Reproduction Steps

        self.copyamicrossregions_bucket = s3.Bucket(self, "copyamicrossregionsBucket",
                                                    removal_policy=core.RemovalPolicy.RETAIN,)
        Cfncopyamicrossregions_bucket = self.copyamicrossregions_bucket.node.default_child
        Cfncopyamicrossregions_bucket.add_property_override(
            'AccelerateConfiguration.AccelerationStatus', 'Enabled')

### What actually happened?

UPDATE_FAILED        | AWS::S3::Bucket    | copyamicrossregionsBucket (copyamicrossregionsBucket3CD22D81) API: s3:setBucketAccelerateConfiguration Access Denied

### Environment

  - **CDK CLI Version  :*1.107.0 (build 52c4434)*
  - **Framework Version:*1.107.0*
  - **Node.js Version:*v16.2.0* 
  - **OS               :*Ubuntu 20.04.2 LTS*
  - **Language (Version):*Python 3.9.5* 

### Other

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @pachicoo,

Thank you for reporting this! I have not yet reproduced, but considering the limited scope of this bug, I am marking it as lower priority. If you disagree and think this has a wider impact, OR you find the root cause/a fix yourself, we can reevaluate escalating priority.

That said, someone will take a look at fixing this when able. Unfortunately, without more information on how you configured your new account, our ability to investigate is limited and slowed, so any additional info you come across while figuring this out for your system would be immensely helpful.

😸 😷

**Comment by pachicoo** [comment]
Here are more details:

Existing accounts are created, then enrolled in Control Tower.
The new account is created by Account Factory.
Even though CDK accesses all accounts through  AWSReservedSSO_AWSAdministratorAccess

The S3 Bucket created by CDK is owned by the same account.
Surprisingly, the rest of the stakes are deployed without issue.

**Comment by pachicoo** [comment]
New findings:
aws s3api put-bucket-accelerate-configuration
put_bucket_accelerate_configuration (Boto3 )

Both commands emit the same error - Access Denied

**Comment by otaviomacedo** [comment]
@pachicoo can you please make sure that the IAM role or user that you are using to set the acceleration configuration has the `s3:PutAccelerateConfiguration` permission? For more information, see [Configuring Transfer Acceleration](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html).

**Comment by pachicoo** [comment]
This is an account level security issue, nothing to do with CDK. Thank you all for your time and efforts.
