### ISSUE TITLE
(apigateway): fromRestApiAttributes always takes account and region from stack

### ISSUE THREAD

**Issue by thantos** [aws/aws-cdk#15021]
Policy created by `CallApiGatewayRestApiEndpoint` for cross account Apis is created for a reason in the current account, not the target account.

### Reproduction Steps

```ts
const myImportedApi = RestApi.fromRestApiId(this, "importedApi", "apiId");

const callFactStore = new CallApiGatewayRestApiEndpoint(this, "myApiCall", {
    api: myImportedApi,
    method: HttpMethod.POST,
    stageName: "prod",
    apiPath: "/path",
    authType: AuthType.IAM_ROLE,
    ...
  }
);
```

### What did you expect to happen?

Create a valid role which allows step functions to make a call to API Gateway,

```json
{
    "Action": "execute-api:Invoke",
    "Resource": "arn:aws:execute-api:[target region]:[target account]:some id/prod/POST/path",
    "Effect": "Allow"
}
```

### What actually happened?

A role is created, assuming the api gateway endpoint is in the current account, not the target account.

```json
{
    "Action": "execute-api:Invoke",
    "Resource": "arn:aws:execute-api:[source region]:[source account]:some id/prod/POST/path",
    "Effect": "Allow"
}
```

### Environment

  - **CDK CLI Version  :** 1.1.02.0
  - **Framework Version:** 1.102.0
  - **Node.js Version:**  12
  - **OS               :** WSL 2 - Ubuntu
  - **Language (Version):**  TS 4

### Other

The issue is actually in the imported Api Gateway, however it is possible for CallApiGatewayRestApiEndpoint to fix this by finding another way to create the `Arn` than relying on the Api Gateway helpers.

This is my current hack for anyone stuck. 

Note: I wish this task was more pluggable, no way to provide additional policies or override the default behavior easily due to readonly and private fields (see the ts-ignore).

```ts
export interface CallApiGatewayRestApiEndpointV2Props extends CallApiGatewayRestApiEndpointProps {
  apiAccount?: string;
}

export class CallApiGatewayRestApiEndpointV2 extends CallApiGatewayRestApiEndpoint {
  constructor(
    scope: Construct,
    id: string,
    private _props: CallApiGatewayRestApiEndpointV2Props
  ) {
    super(scope, id, _props);

    // The current construct will create a policy which is on resource within the current account
    // Not the account of the account of the api gateway target.
    // @ts-ignore
    this.taskPolicies =
      _props.apiAccount && _props.authType !== AuthType.NO_AUTH
        ? [
            new PolicyStatement({
              resources: [
                Stack.of(this).formatArn({
                  ...Arn.parse(this.arnForExecuteApi),
                  account: this._props.apiAccount,
                }),
              ],
              actions: ["execute-api:Invoke"],
            }),
          ]
        : this.createPolicyStatements();
  }
}
```

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
As you point out, this is an issue with API Gateway, not with Step Functions. The solution will be to add `account` and `region` to [RestApiAttributes](https://github.com/aws/aws-cdk/blob/9718b393b6bb0f50ee4595591f6499f44800eafe/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L639) so that they can be provided to the [constructor of `Import`](https://github.com/aws/aws-cdk/blob/9718b393b6bb0f50ee4595591f6499f44800eafe/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L689), which will in turn set the account/region in the [resource's ResourceEnvironment](https://github.com/aws/aws-cdk/blob/9718b393b6bb0f50ee4595591f6499f44800eafe/packages/%40aws-cdk/core/lib/resource.ts#L119). Then, when [constructing the `execute-api` ARN](https://github.com/aws/aws-cdk/blob/9718b393b6bb0f50ee4595591f6499f44800eafe/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L363), the account and region should be passed in.

**Comment by BenChaimberg** [comment]
A more generic workaround than what is provided above would be to subclass RestApiBase like so:
```
class Import extends RestApiBase {
  public readonly restApiId = attrs.restApiId;
  public readonly restApiRootResourceId = attrs.rootResourceId;
  public readonly root: IResource = new RootResource(this, {}, this.restApiRootResourceId);
  public readonly env = {
    account: importAccount,
    region: importRegion,
  };
}
```
