### ISSUE TITLE
addToRolePolicy will silently do nothing

### ISSUE THREAD

**Issue by brianfoody** [aws/aws-cdk#1504]
Stumbled across this code when investigating whether CDK was adding the Lambda permissions I requested. Shouldn't CDK be throwing an error here if no role exists instead of silently not adding the permission?

https://github.com/awslabs/aws-cdk/blob/fb22a328f8a0dc9f1a97644990ed61314971e05c/packages/%40aws-cdk/aws-lambda/lib/lambda-ref.ts#L218

**Comment by eladb** [comment]
Yes, the current behavior is not the desired one. Our original idea was to issue a warning during synthesis that tells you that a permission could not be added. What do you think?

**Comment by brianfoody** [comment]
Hey @eladb . To be honest I would probably miss any warning as the CDK output can be pretty verbose and with CI deployments it becomes even less likely to see. 

I think an error is the correct course of action, maybe also adding an "hasRole" method to check first so you can do logic like;

    // if hasRole
        // addToRolePolicy
    // else 
        // createRole

I'm guessing introducing this would be a breaking change for a lot of users though?

**Comment by eladb** [comment]
@rix0rrr what do you think?

**Comment by rix0rrr** [comment]
Can you even recall in what situations we allowed the principal to be undefined?

**Comment by eladb** [comment]
Yes, imported resources like a lambda.Function would have it's `role` property undefined.

**Comment by rix0rrr** [comment]
Really, is that the reason? Okay, let's improve that then. I know what to do.

**Comment by eladb** [comment]
Of course, your favorite identity functions! You are absolutely right.

**Comment by eladb** [comment]
And it will issue a permission notice to the toolkit, right?

**Comment by rix0rrr** [comment]
Yes.

**Comment by rix0rrr** [comment]
![magic](https://img.scryfall.com/cards/large/en/wth/154.jpg?1517813031)

**Comment by rix0rrr** [comment]
Actually I wonder if we should be changing the API surface slightly.

Today:

```ts
class Function {
  public role?: IRole;
}
```

The `role?` property exists as far as I know mostly so that we can do (I think it's hardly being used for anything else):

```ts
resource.grantRead(lambda.role);
```

This works, but the full surface area of an `IRole` is actually way too large, and not everything is used. For our null-object we only need the parts that are going to be used by `grantRead()` (conveniently encoded as an interface: `IPrincipal`) which is `addToPolicy(statement)`.

I *can* make the `ImportedResourceRole` class and make the interface throw on everything that's not in `IPrincipal`, but a slight redesign might be more appropriate:

```ts
class Function {
  public role?: IRole;  // Keep this or get rid of it
  public principal: IPrincipal;
}

// to be used as
resource.grantRead(lambda.principal);
```

We can pull this thread slightly further and turn this into the curiously-recurring-property-pattern (similar to `IConnectable`) and do it as such:

```
class Function implements IGrantable {
  public principal: IPrincipal;
}

// to be used as
resource.grantRead(lambda);
```

**Comment by eladb** [comment]
Sounds great! I like it a lot. And if a resource has more than one role those could be used as props. We should also make IRole grantable

**Comment by skinny85** [comment]
On a tangential note, when I saw the Null Rod picture in my work inbox, I was a little bit freaked out 😱

**Comment by rix0rrr** [comment]
I believe this issue has been solved by recent changes to the permissions model. Please reopen if you find that I closed this issue in error.
