### ISSUE TITLE
Windows template version parsing failing to detect modern template

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#15066]
When running `cdk bootstrap` attempting to combine the flags `--template` and `--cloudformation-execution-policies` I receive the following error.

```
C:\Users\mccownbm\sandbox>cdk bootstrap --template bootstrap-template.yaml --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://012345678912/us-east-1
Using bootstrapping template from bootstrap-template.yaml
 ⏳  Bootstrapping environment aws://012345678912/us-east-1...
 ❌  Environment aws://012345678912/us-east-1 failed bootstrapping: Error: --cloudformation-execution-policies can only be passed for the modern bootstrap experience.
    at Bootstrapper.legacyBootstrap (C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\bootstrap\bootstrap-environment.ts:51:13)
    at Bootstrapper.customBootstrap (C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\bootstrap\bootstrap-environment.ts:162:19)
    at C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:362:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:359:5)
    at initCommandLine (C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:210:9)
--cloudformation-execution-policies can only be passed for the modern bootstrap experience.
```

Flag reference

```
--template   Use the template from the given file instead of the built-in one (use --show-template to obtain an example) [string]
--cloudformation-execution-policies   The Managed Policy ARNs that should be attached to the role performing deployments into this environment (may be repeated, modern bootstrapping only) [array] [default: []]
```

I am using the template from https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml

When attempting this from a Linux shell it works fine.

When removing the --template flag, since the customBootstrap function (link below) is not called, the CDK_NEW_BOOTSTRAP env var will be honored and things will work appropriately.

https://github.com/aws/aws-cdk/blob/f66f4b80da22b4d24d4419acc3984b56d5690b2e/packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts#L153

The issue is that the customBootstrap function calls bootstrapVersionFromTemplate (link below) and I am guessing has some sort of parsing issue related to Windows specifically so it reverts to legacyBootstrap which shouldn't be the case.

https://github.com/aws/aws-cdk/blob/f66f4b80da22b4d24d4419acc3984b56d5690b2e/packages/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts#L104

**Steps to reproduce**

From windows shell
1. Download template file locally for test purposes
2. Pass in a cloudformation execution policy along with the template (shown below)

```
cdk bootstrap --template bootstrap-template.yaml --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://012345678912/us-east-1
```

**Comment by ben-mccown** [comment]
Also relevant:

https://github.com/aws/aws-cdk/blob/0d00e50743074e31b40bcb46e6d4e0869a11419b/packages/aws-cdk/bin/cdk.ts#L364

**Comment by rix0rrr** [comment]
Tried reproducing on Windows but works fine for me:

![image](https://user-images.githubusercontent.com/524162/122056851-51011980-cdea-11eb-8a5c-089161124ab8.png)


Please double-check that `bootstrap-template.yaml` actually contains the v2 template.

**Comment by rix0rrr** [comment]
Same for CDK v1 btw:

![image](https://user-images.githubusercontent.com/524162/122057147-9a516900-cdea-11eb-87da-45ebb4775dff.png)

**Comment by ben-mccown** [comment]
I am using the template from https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml

I will attach it here as well.

I see you're getting an error relating to credentials needing to be configured. Are you sure the bootstrapVersionFromTemplate function will run even with credentials not being configured? I would expect it to fail due to lack of credentials before reaching the bootstrapVersionFromTemplate logic.

[bootstrap-template.zip](https://github.com/aws/aws-cdk/files/6658308/bootstrap-template.zip)

**Comment by ben-mccown** [comment]
Also failing for me with the boostrap-template.yaml from master.

https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml

[bootstrap-template.zip](https://github.com/aws/aws-cdk/files/6663959/bootstrap-template.zip)

Maybe worthy of note is that CDK_NEW_BOOTSTRAP is set to 1, although I'm not sure that would matter.

```cmd
C:\Users\mccownbm\sandbox>echo %CDK_NEW_BOOTSTRAP%
1

C:\Users\mccownbm\sandbox>cdk bootstrap --template bootstrap-template.yaml --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://012345678912/us-east-1
Using bootstrapping template from bootstrap-template.yaml
 ⏳  Bootstrapping environment aws://012345678912/us-east-1...
 ❌  Environment aws://012345678912/us-east-1 failed bootstrapping: Error: --cloudformation-execution-policies can only be passed for the modern bootstrap experience.
    at Bootstrapper.legacyBootstrap (C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\bootstrap\bootstrap-environment.ts:51:13)
    at Bootstrapper.customBootstrap (C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\bootstrap\bootstrap-environment.ts:162:19)
    at C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:362:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:359:5)
    at initCommandLine (C:\Users\mccownbm\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:210:9)
--cloudformation-execution-policies can only be passed for the modern bootstrap experience.
```

**Comment by peterwoodworth** [comment]
I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by kellertk** [comment]
I was able to reproduce this on Linux using the template attached to this issue (bootstrap-template.zip)

![image](https://user-images.githubusercontent.com/1083460/122811674-a2dfee80-d285-11eb-8447-954051cf0995.png)

It looks like this is because the template isn't being parsed as valid yaml by [loadStructuredFile](https://github.com/aws/aws-cdk/blob/f66f4b80da22b4d24d4419acc3984b56d5690b2e/packages/aws-cdk/lib/serialize.ts#L37), which means we aren't able to detect the bootstrap version from the template file. That means it's detected as a legacy bootstrap file, even though it isn't. I noticed there were some odd characters in the beginning of the template file. This is throwing off the yaml parser.

![image](https://user-images.githubusercontent.com/1083460/122812043-0a963980-d286-11eb-8308-1347758f4ece.png)

Downloading the file fresh from https://raw.githubusercontent.com/aws/aws-cdk/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml fixed this for me. Maybe there's some kind of odd characters in your template @ben-mccown that's throwing you off?

**Comment by ben-mccown** [comment]
Thank you @kellertk for reproducing the issue. This led me to check again and it still didn't work for me with the exact same template file.

I then noticed in VS Code that the file encoding was set to UTF-16 LE. Set to UTF-8 and the issue was resolved. VS Code defaults to UTF-8 encoding so I was a bit confused as to how I ended up with UTF-16 LE set. That's when I remembered that the original yaml file was generated with the following command.

```
cdk bootstrap --show-template > bootstrap-template.yaml
```

I had then pasted in different file contents but always kept the same file, so encoding stayed the same.

Guessing this is due to the redirect operator in Windows and how it handles default encoding.

**Comment by kellertk** [comment]
Turns out, this is due to the way that PowerShell handles redirection to files with the `>` and `>>` operators. The files are created with UTF-16LE instead of your normal UTF-8. See the [PowerShell docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.1#character-encoding-in-windows-powershell). 

This breaks the yaml parser. If you download the file right from the repository, it should work. @rix0rrr maybe we can have some better error messages when we expect a yaml or json file but instead we get something unparseable?
