### ISSUE TITLE
aws-cognito: support token revokation

### ISSUE THREAD

**Issue by vincent-dm** [aws/aws-cdk#15126]
Cognito [recently introduced token revocation](https://aws.amazon.com/about-aws/whats-new/2021/06/amazon-cognito-now-supports-targeted-sign-out-through-refresh-token-revocation/), which needs to be enabled at the user pool level, but is apparently not yet supported by CDK.

### Use Case

To revoke tokens; same reason as why Cognito introduced it.

### Proposed Solution

[According to the Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/token-revocation.html), the `EnableTokenRevocation` parameter needs to be set for the user pool. Thus, the builders of `UserPool`, `UserPoolClient` and `UserPoolResourceServer` probably need such a parameter.

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
> Thus, the builders of `UserPool`, `UserPoolClient` and `UserPoolResourceServer` probably need such a parameter.

This is a feature of user pool client, and will need to only be supported there.

**Comment by apoorvmote** [comment]
Can someone explain me how do you access refresh token from other device?

In order to revoke refresh token you actually need to pass that token.

Only way I see this working is when user signs in on new device then first I would run global sign out to revoke all tokens and login again to generate new token. This is double login and we never used revoke token api at all.
