### ISSUE TITLE
(CDK Pipeline): How to build and deploy another CDK project in CDK Pipeline

### ISSUE THREAD

**Issue by JoeShi** [aws/aws-cdk#15194]
### The Question
I am tring to use the CDK Pipeline to build and deploy multiple CDK projects. One CDK Project contains the Pipeline itself and rest CDK projects contains applications. I cannot write all the applicaitons in just one CDK project, because it will make the project super huge. The CDKPipeline only allow one source acition and one synthAction. How can I use it to build two or more CDK projects. 
```ts
    const pipeline = new CdkPipeline(this, 'Pipeline', {
      // The pipeline name
      pipelineName: 'LastMilePipeline',
      cloudAssemblyArtifact,

      // Where the source can be found
      sourceAction: new codepipeline_actions.CodeCommitSourceAction({
        actionName: 'Pipeline.Source',
        repository: pipelineRepo,
        branch: 'develop',
        output: sourceArtifact,
      }),

      // How it will be built and synthesized
      synthAction: SimpleSynthAction.standardNpmSynth({
        actionName: 'Pipeline.Synth',
        sourceArtifact,
        cloudAssemblyArtifact,
        environment: {
          privileged: true
        }
      }),
    });
```

I have a workaroud to add more SourceAction to the CodePipeline by:
```ts
    const docsSourceArtifact = new codepipeline.Artifact('DocsSourceArtifact');
    const docsSourceAction = new codepipeline_actions.CodeCommitSourceAction({
      branch: 'develop',
      repository: docsRepo,
      output: docsSourceArtifact,
      actionName: 'Docs.Source'
    })
    pipeline.codePipeline.stages[0].addAction(docsSourceAction);
```

However, How can I deploy it? Any examples of one CDK Pipeline to support multiple CDK projects? I am it is a very common case that a project can use multiple repos.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by ryparker** [comment]
Hey @JoeShi 👋🏻 

If you'd like a single pipeline to source and deploy CDK code from multiple locations then I recommend using the [`Pipeline` from `@aws-cdk/aws-codepipeline`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.Pipeline.html). The `CdkPipeline` abstracts away a lot of the Pipeline code needed to stand up a basic self mutating CDK pipeline. However this can be a drawback when you're interested in configuring something more custom like you are describing.

_Side note:  The [`CdkPipeline`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CdkPipeline.html) has been replaced with the newer [`CodePipeline`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CodePipeline.html). If you wish to continue using the `@aws-cdk/pipelines` package then I recommend upgrading to `CodePipeline` in order to take advantage of new API as they are developed._

You may also want to consider creating a pipeline per source/project/application, rather than one monolithic pipeline that deploys from many sources. This is usually easier to manage.
