### ISSUE TITLE
Go CfnJson example.

### ISSUE THREAD

**Issue by phenri00** [aws/aws-cdk#15253]
Trying to use CfnJson, but it doesn't seem to work properly. Could someone please post an working example for Golang?

	foo := awscdk.NewCfnJson(stack, aws.String("test"), &awscdk.CfnJsonProps{
		Value: cluster.ClusterOpenIdConnectIssuer(),
	})

```
panic: "Resolution error: Resolution error: Resolution error: \"${Token[TOKEN.372]}\" is used as the key in a map so must resolve to a string, but it resolves to: {\"Fn::Join\":[\"\",[{\"Fn::GetAtt\":[\"EKSCluster676AE7D7\",\"OpenIdConnectIssuer\"]}]]}. Consider using \"CfnJson\" to delay resolution to deployment-time.\nObject creation stack:\n  at stack traces disabled.."
```

**Comment by peterwoodworth** [comment]
Hey @phenri00,

Go still doesn't have great documentation unfortunately since it's so new as an option for the CDK, but we're working on having better support for the language. Sorry about the lack of documentation and for your experience here.

As for your issue, I'm not very familiar with Go but it looks to me like you did everything right here. Have you since found a working solution? @MrArnoldPalmer could this be a JSII issue?

**Comment by phenri00** [comment]
I think I was using the types wrongly. 

This should work:

```
foo := awscdk.NewCfnJson(stack, aws.String("test"), &awscdk.CfnJsonProps{
		Value: cluster.ClusterOpenIdConnectIssuer(), 
})

bar := map[string]interface{}{"StringEquals": foo}

principal := awsiam.NewOpenIdConnectPrincipal(awsiam.NewOpenIdConnectProvider(stack, aws.String("testPrincipal"), &awsiam.OpenIdConnectProviderProps{
		Url: cluster.ClusterOpenIdConnectIssuerUrl(),
}), &bar)

```
