### ISSUE TITLE
v2.0.0 rc.9 release page links to a non-existent changelog 

### ISSUE THREAD

**Issue by dan-lind** [aws/aws-cdk#15295]
The v2.0.0-rc.9 [release page](https://github.com/aws/aws-cdk/releases/tag/v2.0.0-rc.9) contains a link to a CHANGELOG

However this link is dead
https://github.com/aws/aws-cdk/blob/bump/2.0.0-rc.9/CHANGELOG.md

---

This is a 📕 documentation issue

**Comment by dan-lind** [comment]
The same is true for v2.0.0-rc.10 which points to
https://github.com/aws/aws-cdk/blob/bump/2.0.0-rc.10/CHANGELOG.md

**Comment by nija-at** [comment]
Assigning to @skinny85 who is working in this area and CDKv2.

**Comment by skinny85** [comment]
Thanks for reporting @dan-lind, but this only happens for empty releases (that don't have any changes). This happens when our merge jobs to the V2 branch are blocked because of conflicts.

Since this doesn't happen for releases with any changes (which are the only releases that really make sense, to be honest), I'll close this one as not worth to fix.

Thanks,
Adam
