### ISSUE TITLE
How can I get the IntegrationId when I create a route?

### ISSUE THREAD

**Issue by mikeshi80** [aws/aws-cdk#15338]
https://github.com/aws/aws-cdk/blob/32f00eb26486b18619f4cf6ca497759c46aa7c8a/packages/%40aws-cdk/aws-apigatewayv2/lib/http/route.ts#L157

I read the source, and I found the integrationid only can be get from HttpIntegration class, but it seems not be designed for developers, but for internal usage. The HttpIntegration instance is created in HttpRoute  construct function, but I cannot access it from the HttpRoute instance.

Is it possible to get the IntegrationId in CDK? Now I only can get it by AWS Cli command.

**Comment by peterwoodworth** [comment]
I'm not sure I understand exactly what you're asking for. Can you post an example of what you'd like to accomplish?

**Comment by mikeshi80** [comment]
Thank you for your reply and sorry for my poor English. I am going to setup a CICD pipeline for the project which is built by lambda + api gateway, and I want to update the Http Integration from one lambda alias arn to another lambda alias arn when I updated my lambda, and I try to do it by aws cli ([`aws apigatewayv2 update-integration`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigatewayv2/update-integration.html)), but I found the `--api-id` and `--integration-id` arguments are required for this operation. I used CDK to construct my environment, and I can get the `api-id` by `apigatewayv2.HttpApi.apiId`. I stored it to SSM parameterStore, `apigw-api-id` as its key, so I can get its value by aws cli command `aws ssm get-parameter --name apigw-api-id`, but when I try to get integration id and store it to parameter store, I cannot find any method to get the integration id value.

```typescript
    const integration = new integrations.LambdaProxyIntegration({
      handler: latest_alias,  // latest_alias is the alias for lambda
    });
    const routes = httpapi.addRoutes({  // httpapi is the instance of apigatewayv2.HttpApi
      path: '/api',
      methods: [apigw.HttpMethod.POST],
      integration: integration,
    })
```

This is my CDK code snippet, `integration` , which is the instance of `LambdaProxyIntegration`, has no integrationId property, only class `HttpIntegration` has it, but `HttpIntegraion` is only used internally, I cannot access it directly (maybe it's wrong, but I really have tried a lot of ways, none is workable). I also tried to create an instance of `HttpIntegration`, and I did find the integration in 
 the console, and I can attach it to some route, however, in CDK, the instance cannot attach to a route because of incompatable type ( One is `IHttpIntegration` and the other is `IHttpRouteIntegration`).

**Comment by peterwoodworth** [comment]
No worries @mikeshi80, thank you for providing all this detail. I understand the problem now. I'll research this and get back to you

**Comment by peterwoodworth** [comment]
Since the integration created by the route construct isn't publicly exposed, there's no easy way to access it. But there is a way to do it, you can access the integration because you can access the route's _children_. The `_addIntegration` method will create an L2 Integration, and this will be a child of the route. You can access constructs' children through the `.node` property. You can use the [`tryFindChild()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.ConstructNode.html#trywbrfindwbrchildid) method if you know the child's id, but in all honesty I'm not too sure exactly which id this function wants. So in this example, I'll show you by just getting the specific child I want: `const myIntegration = route.node.children[1] as HttpIntegration` I know to use index of 1 because `console.log(route.node.children)` will list HttpIntegration as the second child. If you can figure out how to make `tryFindChild()` work then using that is probably better practice. Anyway, here's a full example which works successfully:

```ts
const integration = new integrations.LambdaProxyIntegration({
  handler: fn, 
});

const routes = httpapi.addRoutes({ 
  path: '/api',
  methods: [apigw.HttpMethod.POST],
  integration: integration,
})

routes.forEach(route => {
  const myIntegration = route.node.children[1] as HttpIntegration
  new cdk.CfnOutput(this, "IntegrationId", {
    value: myIntegration.integrationId
  })
})
```

Let me know if you have any more questions @mikeshi80 😄 

@nija-at is exposing the Integration (or at least some of its properties) created by the `HttpRoute` construct something we'd want to do? Seems like it would make things convenient for some users

**Comment by mikeshi80** [comment]
Thank you, I think if the index 1 is fixed, and it will not be changed in the future, it is the feasible way to get integration id from CDK directly. Of course, I hope there will be an easier way to get it in the future.
