### ISSUE TITLE
(cloudwatch): IDashboard and addWidgets method

### ISSUE THREAD

**Issue by mark-ship-it** [aws/aws-cdk#15334]
Most AWS resources have an interface that extends `IResources` as well as static methods to import existing resources, returning an interface to a resource of that type.  

Cloudwatch Dashboards do not have a corresponding `IDashboard` interface.  Also, Cloudwatch Dashboards do not have static methods to import existing resources created by either the CDK or an existing resource.

For example, a Dynamodb Table has an `ITable` interface.  Using `Table.fromTable*` methods, one can return an `ITable` object, which provides a number of methods also available to a `Table` object.  

This feature request is to provide an `IDashboard` interface providing an `addWidgets` function, as well as static methods to support importing existing Cloudwatch Dashboards.

### Use Case

This would allow those using `aws-cdk` to look up an existing cloudwatch dashboard, and add additional resources to it.  This would greatly improve observability for resources spread out across different stacks and would provide better support for having a single dashboard with different resource types.

### Proposed Solution

Note that this pattern could be used across different nested stacks while maintaining a single dashboard
```
import * as cw from `@aws-cdk/aws-cloudwatch`


const exampleDashboard: cw.IDashboard = cw.Dashboard.fromDashboardName(this, 'existingServiceDashboard', 'service')
exampleDashboard.addWidgets(...)
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by madeline-k** [comment]
Hi @mark-ship-it thanks for opening this feature request! I am triaging it as a p2, which means that the CDK team will not be prioritizing this in the near future. But, we always welcome contributions!

**Comment by madeline-k** [comment]
To get this feature into the CDK faster, anyone from the community is welcome to implement it and submit a PR. See the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for details on how to contribute.

You can also add your 👍 vote to the issue to help us prioritize it higher!

**Comment by hoegertn** [comment]
As the configuration of the widgets is done in the DashboardBody of the dashboard resource (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-dashboard.html) and a widget is not a standalone resource, I think this is not possible.

It would need to modify the body of the imported dashboard but only one stack can "own" a resource. So imported resources can only be used as ARNs, names etc in the resulting CFN template and not modify the resource itself.

**Comment by mark-ship-it** [comment]
> As the configuration of the widgets is done in the DashboardBody of the dashboard resource (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-dashboard.html) and a widget is not a standalone resource, I think this is not possible.
> 
> It would need to modify the body of the imported dashboard but only one stack can "own" a resource. So imported resources can only be used as ARNs, names etc in the resulting CFN template and not modify the resource itself.

Thanks for the feedback @hoegertn!  Do you have any suggestions as to how one could create a single dashboard for a app/service that spans multiple stacks?  It seems like it should be possible.   Having multiple dashboards for a service (one per stack) leaves a lot to be desired.

It is possible to look up resource ARNs across stacks via SSM Parameter Store, but this creates issues because we can only lookup the IResource (eg. ILambda, ITable) and not the resource itself.  This means we can't take advantage of some properties like ILambda's duration property as a timeout for a CloudWatch Alarm.  

The ARN lookup method works in some cases, but is not ideal as it requires extra code to store and lookup resources.  One resource type that is quite difficult to add to a dashboard with this approach is API Gateway. 

Thanks for recommendations and suggestions as to how I can solve the problem of creating one dashboard per app/service.

**Comment by madeline-k** [comment]
@hoegertn, you are right, thank you for point that out!  Implementing fromDashboard() methods would only allow you to reference the ARN of the dashboard, it would not allow you to modify the existing Dashboard. There is no way to modify existing resources that are deployed manually or by another cloudformation stack with cloudformation (with a very few number of exceptions). So this feature request might not actually make much sense. 

@mark-ship-it are your different stacks within the same CDK app or same codebase? One way to satisfy your use case would be to pass around the Dashboard object from one stack to another. The stack that creates the Dashboard would need to have a public property containing the Dashboard that you could then pass in to the constructor of your other stacks.

**Comment by mark-ship-it** [comment]
I tried another approach where I create a DashboardStack containing a Dashboard.  I then pass this resource into other stacks so they can add the resources they have into the Dashboard.  Unfortunately, this approach doesn't work either.  For every resource that gets added to the Dashboard we will have an export.  The exports prevent us from modifying any of the underlying stacks.

Thanks for suggestions and/or a more loosely coupled way of keeping one Dashboard per set of stacks.

**Comment by brettswift** [comment]
@mark-ship-it I have tried both approaches as well, with no luck. 

1. passing the dashboard into other stacks creates exports, and the only recourse is to delete the dashboard stack on every deploy. 
2. keeping the metrics/alarms/widgets in the dashboard stack requires  (for me) ALB ARN's,  ASG 'FullName' and Target Group 'FullName'.      If i try to put these values into SSM on the API stack, and then pull them out of SSM on the Dashboard stack, I was hoping CDK would not create the export/import. 

The second option doesn't work however, because I can't seem to get the  physical ID's of the values,  but only Tokens.

`ssm.StringParameter.fromStringParameterName(this, 'arn', 'MyALB')` ends up being a Token. 

If there is a way for Stack1 to publish `alb.loadbalancerArn` as the physical value, then this would work.  

I understand this is likely not something CDK could do, as it is a cloudformation limitation.     

Possibly a custom resource / Physical ID resolver is what is needed?

**Comment by antimonad** [comment]
Just to add a not-purely-technical anecdote to this: 
after a significant push for cdk-usage instead of CF in our dev teams, which allowed for "easier" creation of metrics, widgets and dashboards, we ended up with several one-widget-dashboards... there were obviously other issues at play too ("Murphy's law"), but missing this feature is part of the "issue".

The additional costs per dashboard are almost neglectable but not having a way to extend existing dashboard by cdk-stacks still creates other and unexpected "issues" for us.
