### ISSUE TITLE
(cdk-bootstrap): add flags to personalize deployed stack

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#15340]
In the current project we are deploying a ServerLess app via CodePipeline that is using only Lambdas and a frontend.
We're not using docker images so the ECR repository is not needed.
Currently [it's only possible to output the template](https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-custom-synth) and play with it manually to exclude ECR deployment.

It would be great if the would be flags possible like `cdk bootstrap --disable-ecr-repository` or something similar, to only deploy the components of the stack that we need.

**Comment by njlynch** [comment]
Thanks for the feature request.

ECR registries [only charge for storage and usage](https://aws.amazon.com/ecr/pricing/), not for the creation of the registry itself, so having an empty registry will not increase costs. Bootstrapping a region without the registry will cause any future updates which necessitate the registry to fail on deployment, potentially with misleading or hard-to-diagnose errors, which is why we've included it by default.

As you've noted, you can customize the bootstrapping template to remove the registry if needed. I realize this isn't as easy as a flag to the CLI, but it does provide a workaround. I'm marking this as a `p2`, as I think this isn't yet a strong enough use case to prioritize. We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by Alexx-G** [comment]
This is quite important for us too, since some accounts are given quite granular permissions and creating ECRs isn't granted usually.
Changing the behavior via custom bootstrap template doesn't scale well.
