### ISSUE TITLE
(lambda-layer-awscli/lambda-layer-kubectl): unable to set kube config context for kubectl operations

### ISSUE THREAD

**Issue by karthiksubramanians** [aws/aws-cdk#15369]
### The Question

I am trying to connect to Kubernetes cluster using kubectl and aws cli. I deployed a Lambda function with Python 3.7 and Lambda Layers lambda-layer-awscli and lambda-layer-kubectl.
I have added the IAM role to kube config from my local system

When I query the kubernetes cluster using **['/opt/awscli/aws','eks','describe-cluster','--name','<cluster-name>']**
I am able to see the details of the cluster

When I try to create context for the kubernetes cluster, I am facing following write permission errors.

**['/opt/awscli/aws', 'eks', 'update-kubeconfig', '--role-arn', 'arn:aws:iam::<account>:role/<role>', '--name', '<cluster-name>']** --> Can't open kubeconfig for writing: [Errno 30] Read-only file system

**['/opt/kubectl/kubectl' , 'config' , 'set-context' , 'gce' , '--cluster=arn:aws:eks:us-east-1:<account>:cluster/<cluster-name>']** --> error: mkdir .kube: read-only file system

I tried the update-kubeconfig with a file in my lambda function and it is still throwing errors.
I am looking to use kubectl to modify worker nodes, deploy services etc.
Please assist in solving this issue.

### Environment

  - **CDK CLI Version:**  1.110.1
  - **Module Version:**  1.110.1
  - **Node.js Version:**  14.x
  - **OS:**  AWSLinux (AWS Lambda)
  - **Language (Version):**  Python 3.7

**Comment by eladb** [comment]
It seems like the problem is that the default location of `kubeconfig` is the user's home directory and this directory is read-only in Lambda handlers.

Basically you'll want to invoke the AWS CLI with `--kubeconfig /tmp/kubeconfig` or something like that.

Check out [this example](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/apply/__init__.py) of how to use kubectl from a handler.
