### ISSUE TITLE
(aws-ecs): FargateService creates new SecurityGroup instead of using VPC default

### ISSUE THREAD

**Issue by bmacher** [aws/aws-cdk#15365]
According to the [documentation of the FargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateService.html#securitygroups) the default SecurityGroup of the VPC is being used when no group is defined. However it seems to be implemented differently if you look at:

https://github.com/aws/aws-cdk/blob/daa5d66bce204df437bdc28844d7c5944710954b/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L804

A new SecurityGroup is created instead of using the default one of the VPC.

**Comment by peterwoodworth** [comment]
You seem to be right about this, relabelling as a bug. Thanks for catching this @bmacher!

**Comment by bmacher** [comment]
Do you mind if I give it try?

**Comment by peterwoodworth** [comment]
I'm not sure if we want to keep the current implementation and update the docs, or if we want to update the CDK to make the docs accurate. @SoManyHs @madeline-k what do you think?

**Comment by madeline-k** [comment]
I think we should keep the current implementation and update the docs. It seems like the intention here was to create a new security group, since the docs actually say that in one place here: "default: A new security group is created." and that is what has been implemented. 

Changing this to use the default security group might cause some unexpected changes for customers already using the default here. 

@bmacher, do you have a use case where you want to use the default security group of the VPC? You can always pass in that security group to this property, or we could consider adding another initialization prop for using the default security group.

**Comment by bmacher** [comment]
I don't really have an use case because I just found the issue while looking for something different. Anyways thanks for helping out.
