### ISSUE TITLE
(custom-resources): AwsCustomResource leaks assumed role to other custom resources

### ISSUE THREAD

**Issue by nicolai-shape** [aws/aws-cdk#15425]
The runtime handler of the `AwsCustomResource` does not correctly reset the credentials after executing when given a `assumedRoleArn` in any of the `AwsSdkCall` objects.

This means if you have two `AwsCustomResource` constructs in the same stack, and the first one that is deployed supplies a `assumedRoleArn` then the second one will fail to deploy if it executes any commands that are not covered by the policy of the assumed role of the first custom resource.

This obviously only happens if the execution context of the Lambda is reused, which is quite likely if you have a dependency between the custom resources so they're not executed concurrently.

### Reproduction Steps

```typescript
import * as cdk from '@aws-cdk/core'
import * as iam from '@aws-cdk/aws-iam'
import * as customResources from '@aws-cdk/custom-resources'

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    const fooRole = new iam.Role(this, 'FooRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com')
    })
    fooRole.addToPolicy(
      new iam.PolicyStatement({
        actions: ['s3:CreateBucket'],
        resources: ['arn:aws:s3:::Foo']
      })
    )

    // We specify an explicit role that is only allowed to create a bucket called 'Foo'
    new customResources.AwsCustomResource(this, 'Foo', {
      onCreate: {
        service: 'S3',
        action: 'createBucket',
        parameters: {
          Bucket: 'Foo'
        },
        assumedRoleArn: fooRole.roleArn,
        physicalResourceId: customResources.PhysicalResourceId.fromResponse('Bucket.Id')
      },
      installLatestAwsSdk: false,
      policy: customResources.AwsCustomResourcePolicy.fromSdkCalls({
        resources: customResources.AwsCustomResourcePolicy.ANY_RESOURCE
      })
    })

    // We do not explicitly assume a role and expect the custom resource policy to grant permission to CreateBucket
    new customResources.AwsCustomResource(this, 'Bar', {
      onCreate: {
        service: 'S3',
        action: 'createBucket',
        parameters: {
          Bucket: 'Bar'
        },
        physicalResourceId: customResources.PhysicalResourceId.fromResponse('Bucket.Id')
      },
      installLatestAwsSdk: false,
      policy: customResources.AwsCustomResourcePolicy.fromSdkCalls({
        resources: customResources.AwsCustomResourcePolicy.ANY_RESOURCE
      })
    })
  }
}
```

### What did you expect to happen?

Deployment of both resources should succeed.

### What actually happened?

The deployment of the second custom resource fails due to insufficient permissions of the role that was specified for the first custom resource.

### Environment

  - **CDK CLI Version  :** 1.109.0
  - **Framework Version:** 1.109.0
  - **Node.js Version:** v15.14.0
  - **OS               :** MacOS 11.2.3
  - **Language (Version):** TypeScript (3.9.7)

### Other

The issue is located here https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts#L134. I propose to replace lines 134-143 with the following:
```typescript
let credentials: AWS.Credentials | undefined

if (call.assumedRoleArn) {
  const timestamp = new Date().getTime()

  const params = {
    RoleArn: call.assumedRoleArn,
    RoleSessionName: `${physicalResourceId}-${timestamp}`
  }

  credentials = new AWS.ChainableTemporaryCredentials({
    params: params
  })
}

const awsService = new (AWS as any)[call.service]({
  apiVersion: call.apiVersion,
  region: call.region,
  credentials: credentials
})
```
Instead of modifying the global AWS SDK config, we only apply it to the temporary service client.

--- 

This is :bug: Bug Report

**Comment by theipster** [comment]
I've been trialling @nicolai-shape's suggestion above for roughly a week now, with great success. 👍

While the fix itself seems pretty straightforward, I guess the complication is how to test it. I've prepared some failing tests to describe the scenario, which then starts passing once the above fix gets applied: theipster/aws-cdk#1.

Does this look useful / worthy of submitting a formal PR?

**Comment by lebetz** [comment]
@theipster , for me it looks very useful and this bug is a showstopper for me and also a security issue. So it would be great if you can submit a formal PR.

**Comment by julienbonastre** [comment]
Hey @mattvanstone . So just to confirm, is the target assumeRoleArn the same each time or does it switch between different account ID's?

I have a pattern which uses AWS Custom Resources in this fashion too for manipulating remote/spoke account Route53ResolverRule associations via SDK API, however what I found is that this was due to the singleton lambda trying to reissue the API call with the role it had assumed and cached for a different account in its context.

As my pattern issues hundreds of calls to the AWSCustomResource within seconds it appeared as though the Lambda wouldn't re-claim a new STS role assumption to the provided target ARN role in the given spoke account each time and would seemingly "reuse" whatever it last used.

Given this pattern performs these 100+ lambda calls within a few seconds across dozen+ accounts it would ALWAYS hit this same error

**Workaround?**
I simply used nested stacks from my root/parent stack which was based on a per-account basis and initiated their own AWSCustomeResource. This ensured that even if the AWSCR lambda was reused it still had the required/appropriate IAM roleAssumption in its context and not trying to switch to another target account.

As per AWS Doco, each AWSCustomResource is a singleton lambda only per stack in which it is generated, all other instantiations are indeed simply invocation calls to the lambda function during CFN operations.

LMK what you think

**Comment by mattvanstone** [comment]
@julienbonastre In my scenario the target assumeRoleArn is always the same arn, so you would think it would work, but if I trigger an onCreate and then immediately update the stack and trigger an onUpdate or onDelete the lambda is executed again, but the second time it already has the role from the onCreate and then it is passed the assumedRoleArn parameter again and tries to assume it, but the lambad is already assuming it, so it errors if the permissions on that role doesn't allow it to assume itself.

Before I solved my issue I looked at the workaround you mentioned but since I'm trying to run different SDK calls on the same resource it wouldn't work for me. 

Seems like two different issues, but with the same root cause.

**Comment by Lewenhaupt** [comment]
This is still an issue

**Comment by systematicguy** [comment]
Note to self: open an issue about 2 sdk custom resources in quick succession: the warm lambda is too fast and even though he IAM policy gets attached, the lambda fails due to not being authorized to perform the action. 
Letting it install the newest sdk version slows it down enough such that it doesn't fail.

**Comment by julienbonastre** [comment]
> Note to self: open an issue about 2 sdk custom resources in quick succession: the warm lambda is too fast and even though he IAM policy gets attached, the lambda fails due to not being authorized to perform the action. 
> Letting it install the newest sdk version slows it down enough such that it doesn't fail.

Yes,  has been this way for many years. 

Only way I solved was to move the custom resource into the nested stacks I was using which isolated it to use the same iam cross acct role to perform actions in the target account. 

Basically it was just ensuring that the lambda invocation was only going to be used for a single account per call, instead of the custon resources being within the parent stack whereupon they seem to face this recurring issue of unreliable sts role assumption.

![image-20220110-004744.png](https://github.com/user-attachments/assets/73ab5a56-b452-48b7-a6c6-b29d6f0fed71)

It is odd though for sure,  one would think when you carry out an explicit invocation with specific sdk sts assumeRole api call one wouldn't expect this overlap. But alas.


Have since decommed all foundational cdk apps and migrated to Terraform/Terragrunt though🚀🚀.  No dirty little nodejs custom lambdas anymore 😂
