### ISSUE TITLE
aws-elasticloadbalancingv2: ApplicationLoadBalancer from_lookups return dummy arn

### ISSUE THREAD

**Issue by keirwhitlock** [aws/aws-cdk#15473]
Hi

Trying to lookup an existing alb, in order to get/use its ARN, using the `from_lookup` class method, and providing the load_balancer_tags.

When I print the arn, the one returned looks like a placeholder/dummy arn:

`arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/application/my-load-balancer/50dc6c495c0c9188`

So passing that into the ApplicationListener.from_lookup class method fails.

Interestingly if I hardcode the correct ARN in the ApplicationListener.from_lookup method, and print its returned ARN, it too, has a dummy ARN:

`arn:aws:elasticloadbalancing:us-west-2:123456789012:listener/application/my-load-balancer/50dc6c495c0c9188/f2f7dc8efc522ab2`

Not sure if I'm using the above wrong. Seems strange if it is. Perhaps those need to be a token, rather than a dummy url? Not sure.

### Reproduction Steps

```
        lb = aws_elasticloadbalancingv2.ApplicationLoadBalancer.from_lookup(self, id="alb", load_balancer_tags={"name":"mytestalb"})
        print(lb.load_balancer_arn)

arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/application/my-load-balancer/50dc6c495c0c9188

```

### What did you expect to happen?

Both the ApplicationLoadBalancer.from_lookup & ApplicationListener.from_lookup should return the actual ARN of the resource in AWS that the lookup parameters refer too.

### What actually happened?

Receive back an example ARN which cannot be used further on in the code.

### Environment

  - **CDK CLI Version  :1.111.0 (build 556ca93)** 
  - **Framework Version:1.111.0** 
  - **Node.js Version:v15.4.0** 
  - **OS               :mac 11.2.2 (20D80)** 
  - **Language (Version): Python 3.6.8** 

### Other

--- 

This is :bug: Bug Report

**Comment by keirwhitlock** [comment]
```
lb = aws_elasticloadbalancingv2.ApplicationLoadBalancer.from_lookup(self, id="alb", load_balancer_tags={"name":"mytestalb"})

listener = aws_elasticloadbalancingv2.ApplicationListener.from_lookup(
    self,
    id="listener",
    load_balancer_arn=lb.load_balancer_arn,
    listener_protocol=alb.ApplicationProtocol.HTTPS,
)

print(lb.load_balancer_arn)
print(listener.listener_arn)

arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/application/my-load-balancer/50dc6c495c0c9188
arn:aws:elasticloadbalancing:us-west-2:123456789012:listener/application/my-load-balancer/50dc6c495c0c9188/f2f7dc8efc522ab2
```

**Comment by madeline-k** [comment]
@keirwhitlock Why are you trying to print out the load balancer ARN? I think if you just pass in `lb.loadBalancerArn` to subsequent resource creation calls, it should work fine. I just tested this myself and a `CfnOutput` using `lb.loadBalancerArn` has the correct ARN, even though the dummy value is printed out during the early stages of synthesis. 

I am doing a little bit more investigation to see if there is a way to force the dummy value to resolve into the real value earlier. But I don't believe this is a bug. 

Also after the first time you synthesize a template that does the `fromLookup()` call, you should commit to your source control the `cdk.context.json` file this file will store the ARN of the load balancer so that it doesn't need to be retrieved from your AWS account each time.

**Comment by peterwoodworth** [comment]
Closing because the question has been answered and there's been 2 weeks without a response
