### ISSUE TITLE
CDK Pipelines: Cross regions where CodePipeline is not available fails

### ISSUE THREAD

**Issue by cesarpball** [aws/aws-cdk#15650]
### Reproduction Steps

Just execute cdk deploy

### What did you expect to happen?

cdk deploy executed sucesfully

### What actually happened?

The region af-south-1 specified in 'pipeline.artifactStores' is not a valid AWS Region. (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: 0a05260c-0219-0219-0219
-ee3480a05260c; Proxy: null)

### Environment

  - **CDK CLI Version  :1.114.0 (build 7e41b6b)**
  - **Node.js Version:** v16.0.0
  - **OS :** MacOS
  - **Language (Version):**  Java (8)

### Other

--- 

This is :bug: Bug Report

**Comment by alexpulver** [comment]
I tried to move a stage I have to `af-south-1` region, and see what changed in the resulting pipeline template (diff below). The AWS CloudFormation template now includes the artifact store in `af-south-1`. 

I think you get the error because the artifact store is part of the AWS CodePipeline definition, and as you mentioned CodePipeline is not available in `af-south-1`. Per [AWS CodePipeline Now Supports Cross-Region Actions](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-codepipeline-now-supports-cross-region-actions/) release announcement: *"Cross-region actions are available everywhere CodePipeline is available."*

![Screen Shot 2021-07-20 at 11 18 20](https://user-images.githubusercontent.com/4362270/126287435-6fc56ea4-3d2a-4f69-b9bb-444597a8ea4a.png)

**Comment by rix0rrr** [comment]
Thanks Alex!
