### ISSUE TITLE
(aws_events): Can't make a SSM Run Command my target

### ISSUE THREAD

**Issue by PatricioAvila** [aws/aws-cdk#15662]
## :question: General Issue

Hi,

I've been trying to set up a Rule construct that has as a target a SSM Run Command that runs a script in an Auto Scaling Group. Manually you can do this by this image:
![image](https://user-images.githubusercontent.com/38267979/126242363-15b95bed-e549-4376-bd72-a94cfb6f8825.png)

But, in the CDK documentation, I don't see the IRuleTarget implemented by a class in the SSM module. 
![image](https://user-images.githubusercontent.com/38267979/126337180-15634781-3640-4ced-a7de-47d759c9e4e6.png)

### The Question

Is there any way to natively implement a Rule in aws_events that allow to run a script in an auto scaling group? If there is not, how could I implement it?

### Environment

  - **CDK CLI Version:** 1.106.1
  - **Module Version:**  1.106.1
  - **Node.js Version:**  v14.15.0
  - **OS:**  Linux Mint 20 
  - **Language (Version):** Python 3.8.5

**Comment by peterwoodworth** [comment]
The [L1 CfnRule](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.CfnRule.html) allows you to directly modify the settings for the target, which would allow you to configure SSM Run Command as the target by setting the 

If you'd like to be able to use the L2 construct instead of using the CfnRule, feel free to submit a feature request for an `events-targets` class for SSM use cases 😄

**Comment by peterwoodworth** [comment]
Actually, I'm not sure if you're able to configure SSM with cloudformation. [Here are the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html), can you take a look and see if what you want is configurable here?
