### ISSUE TITLE
aws_cdk.aws_lambda.LayerVersion: Unable to Sign a layer but can Code Sign Lambda

### ISSUE THREAD

**Issue by evanerwee01** [aws/aws-cdk#15731]
### The Question

Lambda functions can be Code Signed, See: [AWS Lambda Construct Library — AWS Cloud Development Kit 1.115.0 documentation (amazon.com)](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/README.html#code-signing) 
Section: Code Signing

I cannot find any way to Code Sign a layer in AWS CDK. Therefore, it appears that,  AWS CDK cannot deploy AWS Functions and Layers where the function is code signed. The only possible way is to remove all layers from the CDK. Signed the Layers using AWS Signer and manually add them to the Lambda Function. 

Is there a way to automated both the signing for Lambda Functions and Layers ?

We have many functions and this is holding us back.

### Environment

  - **CDK CLI Version:** Output of `cdk version` 114
  - **Module Version:** Version of the module in question 114
  - **Node.js Version:** Version of Node.js (run the command `node -v`) v16.5.0
  - **OS:** Windows 10 | Ubuntu | etc... ]
  - **Language (Version):** [Python (3.9.x)]

**Comment by peterwoodworth** [comment]
I don't think it's possible to code sign layers with CDK. The CDK is able to code sign functions because [Cloudformation supports it](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html) through their `Function` and `CodeSigningConfig` resources. However, the `LayerVersion` resource doesn't come with any properties that support this functionality
