### ISSUE TITLE
(codeartifact): repo dependent on domain name creates before domain

### ISSUE THREAD

**Issue by Andrapyre** [aws/aws-cdk#15746]
A CfnRepository dependent on domain name from a CfnDomain tries to create before the domain is finished creating. It then results in the following error: "Domain not found. Domain 'artifactory' owned by account '123456789' does not exist'.

### Reproduction Steps

Deploy the following stack:

    import { Stack, Construct, StackProps } from "@aws-cdk/core"
    import { CfnDomain, CfnRepository } from "@aws-cdk/aws-codeartifact"
    
    export class ArtifactoryStack extends Stack {
      constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props)
    
        const domain = new CfnDomain(this, "artifactory-domain", {
          domainName: "artifactory",
        })
    
        new CfnRepository(this, "main-repository", {
          domainName: domain.domainName,
          repositoryName: "main",
        })
      }
    }

### What did you expect to happen?

I expected to be able to deploy a code artifact domain and a code artifact repository with the domain name of the code artifact domain.

### What actually happened?

I received a domain not found error because cloud formation tried to create the repository and the domain at the same time.

### Environment

  - **CDK CLI Version  :** 1.115.0
  - **Framework Version:**
  - **Node.js Version:** v.14.16.0
  - **OS**               : WSL 2
  - **Language (Version):** Typescript 4.3.2

### Other
![Bug image](https://user-images.githubusercontent.com/42009361/126872586-04a2dd7e-8902-4ae8-b638-1c69e154d540.PNG)

--- 

This is :bug: Bug Report

**Comment by Andrapyre** [comment]
As an update, having found [this guide](https://github.com/aws-samples/aws-cdk-developing-application-patterns-blog/blob/137c9f264009f9f8a6782211428c8ca890f9bee3/prerequisites/lib/CodeArtifactResources.ts), I now understand how to set this up. But the setup is very unclear for newcomers and the virtually non-existent documentation doesn't help.

**Comment by njlynch** [comment]
I'm glad you found the solution.

We have this documented somewhat in the [Developer Guide](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_tree)

> Where one resource must be created before another, AWS CloudFormation or the AWS Construct Library will _**generally infer**_ the dependency and make sure the resources are created in the right order. You can also add an explicit dependency between two nodes using node.addDependency(); see [Dependencies](https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#dependencies) in the AWS CDK API Reference.

Our L1s are at the mercy of the default CloudFormation logic. In this case, there's nothing for CloudFormation (or CDK) to explicitly understand the link between these two L1s. This can be fixed in another way besides `addDependency` though. If you use the "attribute" version of the domain name, it will generate a CloudFormation reference between the two constructs.

```ts
    new CfnRepository(this, "main-repository", {
      domainName: domain.attrName, // Use attrName instead of domainName
      repositoryName: "main",
    })
```

I'm going to feed this feedback on our L1 usage back to our doc owners. In the meantime, closing this out as the immediate issue is resolved. Feel free to comment and mention me if you have any follow-ups.

Thanks!
