### ISSUE TITLE
(custom-resources): Expose IsCompleteHandler in AwsCustomResource

### ISSUE THREAD

**Issue by McDoit** [aws/aws-cdk#15794]
Would be nice to expose the `IsCompleteHandler `in some way in the `AwsCustomResource`
Maybe with type `AwsSdkCall `and what value to look at in which path

### Use Case

Currently working with TransitGateway and certain attachment operations have states, but the command returns before they reach "ready" states

For example the EC2 `acceptTransitGatewayVpcAttachment `call leaves it in `pending` state until it reaches `available`  

With this addition you can then specify a call to `describeTransitGatewayVpcAttachments` and when it reaches state `available`  return true in the `IsCompleteHandler` and continue CloudFormation execution 

### Proposed Solution

A bit psuedo but something like this:

Propterty: 
`IsCompleteCheck`
with 
`CheckCall` : AwsSdkCall
`CheckPath` : string
`CheckFor` : string

But don't know how straightforward it would be to hook into the 'caller' of the "normal" CustomResource provider for this

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ryparker** [comment]
Hey @McDoit 👋🏻 

Thanks for the feature request.

I'm marking this issue as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
🙏

**Comment by rix0rrr** [comment]
Unfortunately the `AwsCustomResource` is too simple to wait for long-lived resource creation, and because of a max timeout of 15 minutes Lambda is not the best platform for adding a wait either.

For now, the custom resource provider framework is your best bet, although I agree it's right away a bit more of a heavy-handed hammer. A combination of the two might be a good fit.

I wonder if you would not be best served by prototyping a solution, publishing it to the internet, and having it show up on https://constructs.dev/ and have other people use it. We will consider integrating a proven superior solution into the CDK framework in the future.
