### ISSUE TITLE
(module name): short issue description

### ISSUE THREAD

**Issue by krishansubudhi** [aws/aws-cdk#15818]
According to this https://github.com/aws/aws-cdk/issues/10348#issuecomment-692685610 we can import existing bucket if the bucket is created in the same cdk app. 

```
const sourcebucket = s3.Bucket.fromBucketAttributes(this, 'SourceBucket', {
      bucketArn : 'arn:aws:s3:::test-bucket'
    }
    );
const cfnBucket = sourcebucket.node.defaultChild as s3.CfnBucket;
```
```cfnBucket.replicationConfiguration``` is still giving me Cannot set property 'replicationConfiguration' of undefined error. 

This ```test-bucket ``` is being created in the same cdk app.

Use Case:

I have 2 stack. One i am using to create bucket and another is to add replication configuration. 

Please let me know if there is another way to do this.

**Comment by jumic** [comment]
`s3.Bucket.fromBucketAttributes` doesn't create a new S3 bucket. It only imports an existing bucket. Hence it doesn't contain a CfnBucket (which would create a new bucket).

However, you could pass the bucket object from the first to the second stack. In this case, you could split the definition of the S3 bucket and the replication configuration into to CDK stacks in a CDK app.

Example of both stacks:
```ts
export class BucketStack extends cdk.Stack {
  bucket: s3.Bucket;
  destinationBucket: s3.Bucket;

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.bucket = new s3.Bucket(this, 'MyBucket');
    this.destinationBucket = new s3.Bucket(this, 'DestinationBucket');

  }
}

interface ImportStackProps extends cdk.StackProps {
  bucket: s3.Bucket;
  destinationBucket: s3.Bucket;
}

export class ImportStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: ImportStackProps) {
    super(scope, id, props);

    const cfnBucket = props.bucket.node.defaultChild as s3.CfnBucket;
    cfnBucket.replicationConfiguration = {
      role: 'myrole',
      rules:[
        {
          destination:{
            bucket: props.destinationBucket.bucketName
          },
          prefix: "target_prefix",
          status: "Enabled",
          filter: {
            prefix: "source_prefix"
          },
        },
      ],
    };
    
  }
}
```

In the app, pass the buckets to the second stack:
```ts
const app = new cdk.App();
const bucketStack = new BucketStack(app, 'BucketStack');
new ImportStack(app, 'ImportStack', {
  bucket: bucketStack.bucket,
  destinationBucket: bucketStack.destinationBucket,
});
```

Note:
- This example doesn't show how to setup everything to use the replication. It's only an example which demonstrates how to setup property `replicationConfiguration` in a second stack.
- Please check the generated CloudFormation templates in folder `cdk.out`. In the CloudFormation templates that are generated by CDK, the bucket and the replicationConfiguration will be moved to the first stack. This is correct because all properties have to be merged into a single CloudFormation resource (`AWS::S3::Bucket`).

**Comment by peterwoodworth** [comment]
Thanks for the reply @jumic, saved me some time here. This is a great solution to the question asked!

@krishansubudhi imported buckets will work the same way regardless if the bucket was originally created in the same CDK app or not. That is; they will return an [IBucket](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.IBucket.html) which as jumic explained, doesn't contain a CfnBucket. 

The comment you linked was saying that:

- You cannot set replication configuration on an imported bucket (unless you use a custom resource)
- The only way to set replication configuration with the CDK is to use the [Bucket construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html) and use an escape hatch, or simply use the [CfnBucket construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.CfnBucket.html)

**Comment by krishansubudhi** [comment]
Thanks for the response. My use case is that i will have to create bucket in different region and then set up replication configuration. As far as my understanding i can't create bucket for different region from one stack. Please let me know if my understanding is wrong here.

**Comment by peterwoodworth** [comment]
You're correct, according to the [Cfn Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html):

> The AWS::S3::Bucket resource creates an Amazon S3 bucket in the same AWS Region where you create the AWS CloudFormation stack.
