### ISSUE TITLE
Guidance on setting up cross account access to ECR for multi account CDK pipeline

### ISSUE THREAD

**Issue by jmjava** [aws/aws-cdk#15822]
It was suggested that I post an issue for Guidance on setting up Multi Account Pipeline in the CDK.   

We are looking to store our ECR images in the "shared services account" referenced in the CDK best practices blog post.  

![best_practice](https://user-images.githubusercontent.com/591751/127522425-d0ee56b1-1d42-46e0-8648-7da7ddee6edd.jpg)

https://aws.amazon.com/blogs/devops/best-practices-for-developing-cloud-applications-with-aws-cdk/

We have been looking, but there are not any guides that specifically address this use case of an EKS cluster in a target account accessing ECR images in the Shared Services Account.   

Would it be possible to get some guidance on this?

John

**Comment by madeline-k** [comment]
Hello, John! Sorry for the delay in responding to your guidance request. Pulling ECR images from one account to another and then using them in your EKS cluster is definitely possible. Please take a look at these docs: 
- https://aws.amazon.com/premiumsupport/knowledge-center/secondary-account-access-ecr/
- https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecr-readme.html#authorization-token 

Hopefully this is enough info to get you started! If you run into issues, please post your CDK code and any permissions errors that you get so that we can help you in more detail.
