### ISSUE TITLE
aws-cdk aspect : cannot use cdk library to centralize cdk aspect for other application

### ISSUE THREAD

**Issue by jbellavance34** [aws/aws-cdk#15895]
description of the bug:
I am trying to use aws cdk aspects ( https://docs.aws.amazon.com/cdk/latest/guide/aspects.html ) to create a centralized cdk library and it does not work.

What does work : 
Aspect class locally in an cdk application.
Exported aspect class in an other file in the application /lib directory 

What does not work :
Exported aspect class in an other file in an other cdk library /lib directory 

### Reproduction Steps

- create cdk application
`mkdir main_app`
`cd main_app`
`cdk init app --language typescript `
- install aws-cdk/aws-s3 library
`npm i @aws-cdk/aws-s3`
- overwrite lib/main_app-stack.ts with the following
```typescript 
import * as cdk from '@aws-cdk/core';
import * as s3 from '@aws-cdk/aws-s3';

export class S3AspectsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const Bucket = new s3.Bucket(this, "MyBucket", {});
  }
}

export class EnforceBucketLogging implements cdk.IAspect {
  public visit(node: cdk.IConstruct): void {
    // See that we're dealing with a CfnBucket
    if (node instanceof s3.CfnBucket) {

      // Check for logging property
      if (!node.loggingConfiguration) {
        node.loggingConfiguration = {
          destinationBucketName: 'loggingbucket',
          logFilePrefix: 'myprefix'
        }
      }
    }
  }
}
```
- overwrite bin/main_app.ts with the following ( local aspect class WORKS ) 
```typescript 
import { App, Aspects, IConstruct, IAspect } from '@aws-cdk/core';
import { S3AspectsStack } from '../lib/main_app-stack';

import * as s3 from '@aws-cdk/aws-s3';

const app = new App();
new S3AspectsStack(app, 'S3AspectsStack');

/* works locally*/
class EnforceBucketLogging implements IAspect {
  public visit(node: IConstruct): void {
    // See that we're dealing with a CfnBucket
    if (node instanceof s3.CfnBucket) {

      // Check for logging property
      if (!node.loggingConfiguration) {
        node.loggingConfiguration = {
          destinationBucketName: 'loggingbucket',
          logFilePrefix: 'myprefix'
        }
      }
    }
  }
}

// Later, apply to the stack
Aspects.of(app).add(new EnforceBucketLogging());
```
- test the result (WORKS) 
`cdk synth`
- look at the S3 Bucket Resource, it has the LoggingConfiguration set by the Aspect 
```bash
cdk synth
Resources:
  MyBucketF68F3FF0:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName: loggingbucket
        LogFilePrefix: myprefix
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: S3AspectsStack/MyBucket/Resource
```

- overwrite bin/main_app.ts with the following ( exported aspect class from lib/ WORKS ) 
```typescript
import { App, Aspects, IConstruct, IAspect } from '@aws-cdk/core';
import { S3AspectsStack } from '../lib/main_app-stack';
/* works from lib/ directory */
import { EnforceBucketLogging } from '../lib/main_app-stack';


import * as s3 from '@aws-cdk/aws-s3';

const app = new App();
new S3AspectsStack(app, 'S3AspectsStack');

// Later, apply to the stack
Aspects.of(app).add(new EnforceBucketLogging());
```

- test the result (WORKS) 
`cdk synth`
- look at the S3 Bucket Resource, it has the LoggingConfiguration set by the Aspect 
```bash
cdk synth
Resources:
  MyBucketF68F3FF0:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName: loggingbucket
        LogFilePrefix: myprefix
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: S3AspectsStack/MyBucket/Resource
```
- move up a directory 
` cd .. `
- create cdk library
`mkdir other_lib`
`cd other_lib`
`cdk init lib --language typescript `
 - install aws-cdk/aws-s3 library
`npm i @aws-cdk/aws-s3`
- overwrite lib/index.ts with the same content that is in the../main_app/lib/main_app-stack.ts file 
- delete the test file to ensure it compiles
`rm test/other_lib.test.ts`
- go back to the cdk application
`cd ../main_app/`
- overwrite bin/main_app.ts with the following ( exported aspect class from other aws cdk lib/  DOES NOT WORK ) 
```typescript
import { App, Aspects, IConstruct, IAspect } from '@aws-cdk/core';
import { S3AspectsStack } from '../lib/main_app-stack';

/* does not work with other cdk lib with the same class content */
import { EnforceBucketLogging } from '../../other_lib/lib/index';

import * as s3 from '@aws-cdk/aws-s3';

const app = new App();
new S3AspectsStack(app, 'S3AspectsStack');

// Later, apply to the stack
Aspects.of(app).add(new EnforceBucketLogging());
```
- test the result (DOES NOT WORK )  
`cdk synth`
- look at the S3 Bucket Resource, it has the LoggingConfiguration set by the Aspect 
```bash
cdk synth
Resources:
  MyBucketF68F3FF0:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: S3AspectsStack/MyBucket/Resource
```

### What did you expect to happen?

the cdk synth to produce a CloudFormation template with the Aspect being applied.

### What actually happened?

the cdk synth command does not put out any error but the Aspect is not being applied.

### Environment

  - **CDK CLI Version  :** 1.115.0
  - **Framework Version:** 1.115.0
  - **Node.js Version:** v10.19.0
  - **OS               :** microsoft-standard-WSL2 ( ubuntu 20.04 ) 
  - **Language (Version):** typescript 3.9.7

### Other

I am fairly new to aws-cdk and typescript so I might have miss something.

I am trying to replicate something like cdk-nag but with other purposes than security checks.

I expected to be able to create a centralized cdk library with cdk aspect and be able to use them with cdk application.

It is relevent because I am trying to compose a centralized set of conformance, gouvernance, etc.. aspects for all my AWS resource that are being created with aws-cdk.

If this does not work the only other option I have is to copy every cdk aspect class file to every aws cdk application that will be created. This is not viable with large deployments.

Also, I wanted to centralized the cdk aspect to be able to shared easily with other team members/ product teams.

If it is not a bug, please tell me if what I am trying to acheive is possible.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Because of the way NodeJS works, the following is likely to fail:

```ts
    // See that we're dealing with a CfnBucket
    if (node instanceof s3.CfnBucket) {
```

This is because in your setup, where you have two libraries, the files on your disk probably look like this:

```
/path/to/main_app/node_modules/@aws-cdk/aws-s3/lib/s3.generated.js

        class CfnBucket {
           // ...
        }
   
/path/to/other_lib/node_modules/@aws-cdk/aws-s3/lib/s3.generated.js

        class CfnBucket {
           // ...
        }
```

* Because both your application and your library install a copy of the CDK, the same file with the same contents is on your disk two times, in different locations.
* NodeJS does not have the concept of libraries, only of *files*. 
* Since these are 2 different files, the *classes* inside them are also 2 different classes. I'll call them `CfnBucket¹` and `CfnBucket²`.
* When your Aspect code does `node instanceof CfnBucket`, that actually means `node instanceof CfnBucket²`.
* The application will have instantiated a `CfnBucket¹`. If that construct is given to the aspect, the `instanceof` check will fail (because it's not an instance of the *right* `CfnBucket`).

----------

You need to do 2 things to make this work:

* In the `package.json` of your `other_lib`, put your CDK dependencies under `devDependencies` and `peerDependencies` (both), instead of under `dependencies` (see [here](https://github.com/aws/aws-cdk/wiki/NPM-Library-Versioning#libraries)).

In principle this is enough to make it all work (it will make sure only 1 copy of CDK gets installed, so there is only 1 `CfnBucket` and the `instanceof` confusion can't happen anymore). 

However, it will only properly work if `other_lib` is being installed directly from npmjs.com, and if you're consuming it as such (doing `import { MyAspect } from 'other_lib'`, **not** `import { MyAspect } from '../../other_lib'`).

If you're working locally, it *might* work correctly if you use [`npm link`](https://docs.npmjs.com/cli/v7/commands/npm-link). Otherwise, I'd recommend you use a monorepo-aware workspace manager, like Yarn workspaces, NPM7 workspaces, Lerna (although development on Lerna has stopped and as such I can't recommend it anymore) or a similar tool.

**Comment by jbellavance34** [comment]
@rix0rrr 

Thank you a lot for the information given. 

So it is not a bug but a lack from understanding on my end about the typescript/nodeJS dependencie system.

I will take a look into the proposed solution.

**Comment by jugarpeupv** [comment]
Hello, in case someone from the future steps into this problem i have a video explaining how to solve it

https://www.youtube.com/watch?v=JwwNsSiHECE
