### ISSUE TITLE
(aws-apigateway v1): Support for multi-level paths in BasePathMapping

### ISSUE THREAD

**Issue by stefanopallicca-imagicle** [aws/aws-cdk#15904]
I would like to have the possibility to add a multi-level path in BasePathMapping for Api gateway v1, as already stated in #14822 (but closed in favour of a new feature request like this)

### Use Case
The specific case I'm trying to cover is:
- edge optimized domain name
- edge REST api endpoint
- multi-level path mapping

We are using apigateway v1

### Proposed Solution
I tried a couple of workarounds:

Tried to use v1 `BasePathMapping` but got this error:

`Mapping API Gateway V1 doesn't support the slash character (/) in base path mappings. To create a multi-level base path mapping, use API Gateway V2.`

Tried to switch to v2 with `CfnApiMapping` and got this error:

`Mapping Only REGIONAL domain names can be managed through the API Gateway V2 API. For EDGE domain names, please use the API Gateway V1 API. Also note that only REST APIs can be attached to EDGE domain names.`

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by mtimbs** [comment]
Any update on this. Is this an underlying issue with CloudFormation or simply a change required to CDK? Currently it is impossible to version APIs without manually going to the console which is just not feasible for large, multi-gateway, multi-region and multi-environment scenarios.

**Comment by JonBlauvelt** [comment]
>In the AWS console, I was able to change base path from foo-bar to foo/bar. Therefore, I would say that it is supported by API Gateway v1. However, CloudFormation does not support it at the moment.

This isn't quite right.  Here's what's supported by APIGateway for RestAPI - you can create a multi-part mapping if the following conditions are met:
1. You have a REGIONAL endpoint (this is t[he default configuration with DomainName Construct](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apigateway.DomainName.html#endpointtype)
2. You have TLS 1.2 ([this is non-default](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apigateway.DomainName.html#securitypolicy))
3. You use [ApiMapping from api-gatewayv2](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apigatewayv2.CfnApiMapping.html)

This error message:
```
API Gateway V1 doesn't support the slash character (/) in base path mappings.
To create a multi-level base path mapping, use API Gateway V2.
(Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException;
Request ID: a32ebc67-9e1a-44bb-af38-011820b127b1; Proxy: null)
```
Is an indication that condition 3 is not met.  That is, you are trying to add a multipart mapping via apigateway v1's base path mapping, which is not supported.  The reason that adding the mapping from the console succeeds is because it is adding an apigatewayv2 apiMapping to your RestApi(apigatewayv1), which is supported, though this is not transparent.

So assuming other conditions are met, you can attach a multipart apigatewayv2 api mapping to your restApi/domainname.  However, you will need to use the L1 (Cfn) constructs or roll your own adapter since the L2 constructs for apigateway and apigatewayv2 are not interoperable here.

It seems like it may make sense to build support for this use case in the L2 constructs.  Some possible approaches:
1. apigatewayv1 DomainName constructor to support creating apigatewayv2 ApiMappings either explicitly through an additional config or implicitly for multipart use case
2. apigatewayv1 `DomainName.addBasePathMapping` to support creating apigatewayv2 ApiMappings either explicitly through an additional config or implicitly for multipart use case
3. new method on apigatewayv1 DomainName i.e. `DomainName.addApiMapping` to support adding v2 mapping to v1 api+domainname
4. apigatewayv2.ApiMapping constructor to support passing V1 DomainName and api

However, the original feature request looks to be about specifically allowing for multipart mappings for edge api/domain which is a limitation of ApiGateway, not a limitation of CDK or CFN, so I don't think that can be solved here.

**Comment by ilazakis** [comment]
+1 on supporting this on v1.

**Comment by ilazakis** [comment]
Thanks for implementing this @corymhall! 

I'm facing difficulties using `addApiMapping` in `Golang`.

Grabbing an existing `DomainName` via its attributes, returns an `IDomainName`, not a `DomainName`:
```go
domainNameAttributes := &awsapigateway.DomainNameAttributes{
		DomainName:                  jsii.String(environment.API.Domain),
		DomainNameAliasHostedZoneId: jsii.String(""),
		DomainNameAliasTarget:       jsii.String(""),
	}
domainName := awsapigateway.DomainName_FromDomainNameAttributes(stack, jsii.String("AppDomainName"), domainNameAttributes)
```

Attempting to call `addApiMapping` on that `domainName`:
```go
domainName.AddApiMapping(api, &awsapigateway.ApiMappingOptions{
		BasePath: jsii.String("my/path/example/"),
})
```

Produces an error, because `addApiMapping` is not exposed on `IDomainName`, only on `DomainName`. Here's the error:
```go
domainName.AddApiMapping undefined (type awsapigateway.IDomainName has no field or method AddApiMapping)
```
Does the method need to also be explicitly added on `IDomainName` or am I (most likely) missing something else?

**Comment by peterwoodworth** [comment]
`addApiMapping` can only be used on a `Domain` because it requires information that is only tracked by the real `Domain` construct. Specifically, we keep track of information on the base paths already used to validate that the new mapping is valid.

If you don't care about this check, you can achieve the same functionality by creating a CfnApiMapping

```
    new apigwv2.CfnApiMapping(this, id, {
      apiId: targetStage.restApi.restApiId,
      stage: targetStage.stageName,
      domainName: iDomain.domainName,
      apiMappingKey: options.basePath,
    });
```

**Comment by ilazakis** [comment]
Thank you for the suggestion @peterwoodworth! 

We moved some base path mappings to the repo/stack where the domain name is being setup — which is something we wanted to do at some point anyway — to gain access to `DomainName`. If that does not seem to met our needs, I'll be giving your approach a go 👍
