### ISSUE TITLE
@aws-cdk/aws-ecs: Handling Blue Green Deployment in cdk

### ISSUE THREAD

**Issue by akshayp-vwits** [aws/aws-cdk#15902]
### The Question
Hi all, I am new to aws-cdk and i wanted to do ecs blue green deployments via aws cdk, I checked a lot but could not find any suitable articles. My question is how can we handle ecs blue green deployments in cdk. As on the aws console we simply choose the deployment type during service creation, is there some feature available in cdk to do same thing?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 1.116.0 
  - **Node.js Version:** v14.15.0
  - **OS:** 
  - **Language (Version):** Typescript

**Comment by peterwoodworth** [comment]
Hey @akshayp-vwits,

This is really tricky for the CDK to support due to limitations with CloudFormation. So we don't currently have support for this unfortunately, see this issue for more information: #1559 We would love to have this feature, and plan to support it in the future

Ping me if you have any additional questions, sorry we don't currently support this!
