### ISSUE TITLE
Apply conditions on constructs

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#1591]
There are some cases where users need to be able to condition the creation of an entire construct subtree to a CloudFormation Condition reference. A similar approach to what was used for generalizing construct dependencies (#1583) could be used there (`construct.node.addCondition(cfnCondition)`).

**Comment by rix0rrr** [comment]
We can use aspects when it lands, would be perfect for this

**Comment by kevin-lindsay-1** [comment]
I see that aspects appear to be in progress, have there been any updates on this particular use case?

Right now I'm creating different templates because I couldn't find a preferred/documented way to conditionally create constructs, would be much more preferable to just do an if statement (or equivalent) on the whole subtree rather than creating entirely different templates.

**Comment by srischard** [comment]
For CDK v2 I need to replace
```
    this.node.applyAspect(new ConditionAspect(new core.CfnCondition(this, "XisY", {
      expression: core.Fn.conditionEquals("x", "y")
    })));
```
with
```
        Aspects.of(this).add(new ConditionAspect(/** CfnCondition */ ));
```
