### ISSUE TITLE
(DatabaseInstance ): fromDatabaseInstanceAttributes missing in doc

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#16064]
### Reproduction Steps

Trying to import a DB instance tthat way : 
```ts
    const DatabaseInstance = rds.DatabaseInstance.fromDatabaseInstanceAttributes(this, '', {
      instanceEndpointAddress: 'toto.eu-west-1.rds.amazonaws.com',
      instanceIdentifier:'toto',
      port: 1521,
      securityGroups: [SecurityGroupRdsInstanceOracle]
    });
```

Cant' find that method in the doc : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstance.html

And after doing that, can't add user rotation >
`DatabaseInstance.addRotationSingleUser({automaticallyAfter: cdk.Duration.days(90)});`

is throwing the error : 
`Property 'addRotationSingleUser' does not exist on type 'IDatabaseInstance'`

Same for "addRotationMultiUser"

### What did you expect to happen?

`fromDatabaseInstanceAttributes `in the doc.
And be able to use "addRotationSingleUser" & "addRotationMultiUser".

### Environment

  - **CDK CLI Version  : *1.118.0*
  - **Node.js Version: *v16.0.0* 
  - **OS               : *Linux*
  - **Language (Version): *TS* 

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @Cloudrage :wave:

Thanks for opening a bug report.

It looks like you are having 2 problems that this report is trying to solve.

---

__1. Docs do not show `fromDatabaseInstanceAttributes` as a method of [DatabaseInstance](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstance.html)__

This method is not in our docs for `DatabaseInstance` however [it is in our docs for `DatabaseInstanceBase`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstanceBase.html#static-fromwbrdatabasewbrinstancewbrattributesscope-id-attrs) which is the base class for `DatabaseInstance`.

---
__2. Unable to call `addRotationSingleUser` after looking up the database instance using `rds.DatabaseInstance.fromDatabaseInstanceAttributes`__

This is actually by design.

> Although you can use an imported resource anywhere, you cannot modify the imported resource. For example, calling addToResourcePolicy (Python: add_to_resource_policy) on an imported s3.Bucket does nothing.

See [docs on imported resources](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_importing) for more info on why.

 It is not possible to use CDK code to modify an imported resource. You'll notice in the documentation for [`fromDatabaseInstanceAttributes`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstanceBase.html#static-fromwbrdatabasewbrinstancewbrattributesscope-id-attrs) that it returns [`IDatabaseInstace`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.IDatabaseInstance.html) which does not have all of the same methods/props as [`DatabaseInstance`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstance.html)

**Comment by Cloudrage** [comment]
Hi @ryparker !

Many thanks for your time & reply.
Understood, in that case I'll use `aws-secretsmanager "addRotationSchedule"` to do that.

Thanks again !
