### ISSUE TITLE
(codebuild): CloudFormation Property Types are not documented correctly for non-TypeScript languages

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#16089]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.CfnProject.ProjectCacheProperty.html

The type name for TypeScript has the correct hierarchy.
Language | Type name
-- | --
TypeScript | @aws-cdk/aws-codebuild » CfnProject » ProjectCacheProperty

The type name for other languages doesn't have the `CfnProject` class in the hierarchy. It breaks the auto-completion flow in IDE.
Language | Type name
-- | --
.NET | Amazon.CDK.AWS.CodeBuild.ProjectCacheProperty
Java | software.amazon.awscdk.services.codebuild.ProjectCacheProperty
Python | aws_cdk.aws_codebuild.ProjectCacheProperty

Additionally, all language links are broken. For an example, a link for Python points to https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codebuild/ProjectCacheProperty.html instead of https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codebuild/CfnProject.html#projectcacheproperty

The above led me to spend about an hour to implement an escape hatch for CodeBuild project to add a cache configuration:
```python
project = codebuild.Project(...)
cfn_project: codebuild.CfnProject = project.node.default_child
cfn_project.cache = codebuild.CfnProject.ProjectCacheProperty(type="LOCAL", modes=["LOCAL_SOURCE_CACHE"])
```

---

This is a 📕 documentation issue

**Comment by ryparker** [comment]
Hey @alexpulver 👋🏻 

Thanks for the bringing this to our attention. I'm going to relabel this as a bug since you're reporting broken links.

A dev will pick up this bug in order of priority. This is marked as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

**Comment by alexpulver** [comment]
I checked the links above, and it seems the issue was resolved elsewhere, as things are working now.
