### ISSUE TITLE
(secretsmanager): rotation function name exceed 64 chars

### ISSUE THREAD

**Issue by wchaws** [aws/aws-cdk#16108]
CDK fails to deploy the rotation application stack successfully. This bug is similar to #7885.

A workaround is to give `rdsSecret.addRotationSchedule` id a shorter name.

![image](https://user-images.githubusercontent.com/68052927/129842319-20509860-9f46-4484-9c8a-87f05499d049.png)

### Reproduction Steps

```ts
import {Credentials, DatabaseSecret} from "@aws-cdk/aws-rds";
// ...
const rdsSecret = new DatabaseSecret(
    this,
    'rdsSecret',
    {
        username: props.adminUserName,
        secretName: props.rdsSecretName
    }
);
rdsSecret.addRotationSchedule('RotationSchedule', {
    hostedRotation: secretsmanager.HostedRotation.mysqlSingleUser(),
    automaticallyAfter: cdk.Duration.days(90)
});
```

### What did you expect to happen?

Deploy stack successfully.

### What actually happened?

Deploy Failed.

### Environment

  - **CDK CLI Version  :** 1.115.0 (build f0ca40f)
  - **Framework Version:** 1.115.0 (build f0ca40f)
  - **Node.js Version:** v14.17.0 
  - **OS               :** macOS 10.15.7 (19H1323) Darwin 19.6.0
  - **Language (Version):** TypeScript 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report!

With no name provided, CloudFormation will autogenerate a name based on the logical ID of the resource; in this case, with longer ID names (due to long stack/construct IDs), the autogenerated name will fail. We could detect that no name is provided, and in that case generate a name (and trim it down to size). Ideally, this would be done in such a way that it was backwards-compatible (no name change for existing stacks).

Given there's an easy-enough workaround now (providing a name to `mysqlSingleUser()`), I'm going to mark this as a p2. 
We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
