### ISSUE TITLE
(bootstrap): add diff option to cdk bootstrap

### ISSUE THREAD

**Issue by eriklztiqqe** [aws/aws-cdk#16129]
We can run cdk diff to see changes in the stacks we develop.
It would be beneficial to be able to do the same with the CDK bootstrap stack as well, to be able to get more insight
into what an update would include.

### Use Case

To have a better insight into what changes are included in a new bootstrap version and any potential effects that may have.
It is a bit of a black box now.

It is of course possible to dump out the template and create your own changeset based on that to get the diff, but that is a bit cumbersome.

### Proposed Solution

Add a --diff option to cdk bootstrap command, which will perform a diff instead of applying the update.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ryparker** [comment]
Hey @eriklztiqqe :wave:

Thanks for suggesting this feature. For workarounds we do have a way of printing the bootstrap template using `cdk bootstrap --show-template` and we do document the important high level changes in the bootstrap docs. Which also includes a history of template changes listed at the bottom. I understand this is not the same as showing a diff. I could see it being especially useful if you are using a custom bootstrap. Which is why I believe this is a great feature request.

I am marking this issue as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
:pray:
