### ISSUE TITLE
(aws-ecs): Adding circuitBreaker config causes service replacement if deploymentController was not previously set

### ISSUE THREAD

**Issue by madobrien** [aws/aws-cdk#16126]
When adding the circuitBreaker configuration to an ECS service, it automatically sets the `DeploymentController` to `ECS` in the resulting Cloudformation stack. If the `deploymentController` was not specified within the CDK previously, the default value of `ECS` is used when the service is created anyway. 

Unfortunately Cloudformation sees this as a change requiring replacement of the service.

### Reproduction Steps

Pre-existing service:
```
new FargateService(this, "Service", {
  cluster: cluster,
  taskDefinition: taskDefinition
})
```

Adding the circuitBreaker config:
```
new FargateService(this, "Service", {
  cluster: cluster,
  taskDefinition: taskDefinition,
  circuitBreaker: { enabled: true, rollback: true }
})
```
Deploying the above causes service replacement.

### What did you expect to happen?

Expected the `DeploymentController` to be left undefined, since that still results in the default value of `ECS` being used. 

### What actually happened?

Upon deployment the service required replacement, which will have been disruptive due to autoscaled values not carrying across to the new service.

Ended up using escape hatches to set the circuitBreak properties without adding the `DeploymentController` configuration.

### Environment

  - **CDK CLI Version  :** 1.118.0
  - **Framework Version:** 1.118.0
  - **Node.js Version:** v14.15.1 
  - **OS               :** Mac OS 11.5
  - **Language (Version):** Typescript (4.3.3) 

### Other

--- 

This is :bug: Bug Report

**Comment by jamestelfer** [comment]
It seems like the [PR adding circuit breaker support](https://github.com/aws/aws-cdk/pull/12719) also added: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L412-L414

The reasoning was that `DeploymentCircuitBreaker` requires the `ECS` deployment type.

This addition could be removed entirely or (if it was thought valuable) replaced with a warning if a non-ECS deployment type is specified at the same time as the `circuitBreaker` property.

**Comment by rix0rrr** [comment]
> This addition could be removed entirely or (if it was thought valuable) replaced with a warning if a non-ECS deployment type is specified at the same time as the `circuitBreaker` property.

I love it, that's a much better behavior! We would accept a PR that does this.

**Comment by jsunico** [comment]
Hello! Just wanted to +1 on this. Our Fargate service has been deployed with `circuitBreaker` configured since day one. The project is currently at version 1.91.0 and hoping to upgrade to the latest version. However, upgrading will trigger this issue even if you already have circuit breaker deployed way way back.

This 💯 makes sense to me. I just thought that some maybe upgrading their cdk package too and will wonder why it is trying to replace their ECS fargate service even if they haven't change anything else.

**Comment by rgoltz** [comment]
> The [reasoning was that ](https://github.com/aws/aws-cdk/pull/12719#pullrequestreview-604700628) `DeploymentCircuitBreaker` requires the `ECS` deployment type, which is correct, just not necessary to add explicitly.
> 
> This addition could be removed entirely or (if it was thought valuable) replaced with a warning if a non-ECS deployment type is specified at the same time as the `circuitBreaker` property.

Following this idea to remove the `DeploymentController` from CFN output generated by CDK while we are using the `circuitBreaker` functionality would help us to resolve a CFN drift detection issue described via https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1259. As stated before `DeploymentController` of type `ECS` is the default, in case it's not explicitly set in CFN.

**Comment by rgoltz** [comment]
Hi @fergusdixon + @corymhall - Please, let's cross-check & discuss following question/issue: 

From my experience & testing removing the DeploymentController defintion from an existing stack/CFN output/template the Service needs a replacement - I assume that's something people should know, once the update the CDK version, which includes the new/better behaviour from PR #22328 . I've tested this with a pure CFN template: Even you define DeploymentController = ECS (which is also the CFN default, if nothing is defined) and you just remove this part from CFN template, a replacement is triggered.

This replacement becomes critical / will fail, once you define a custom/"static" ServiceName (via CDK/CFN). I assume that in this case a new CDK version with this (btw: good & helpful) fix could cause an stack-update to fail/break.

**Comment by fergusdixon** [comment]
@rgoltz so should we make some sort of notice that old stacks not specifying a deployment controller, should now explicitly set one to avoid replacement?

**Comment by rgoltz** [comment]
@fergusdixon From my understand the old stacks just having circuitBreaker enabled (which means in the "old code", that DeploymentController = ECS getting added silently to CFN) would have issues. 

In case I understood the PR in the right way, CFN output of CDK will no longer contain DeploymentController =ECS , once I just enable circuitBreaker - right? (We dropped this unnecessary conjunction)

So, updates of existing stacks (with circuitBreaker+DeploymentController defined in CFN) would run into a replacement, because the "new code" of CDK do not have DeploymentController = ECS in CFN output. 

Replacement of a Service (because DeploymentController is not part of CFN anymore), would fail, if users define a Service with a own (not auto-generated) ServiceName.

**Comment by fergusdixon** [comment]
@rgoltz correct

**Comment by rgoltz** [comment]
I've tried to create & provide a test-case:
* ECS Service with a ServiceName set
* based on the current CDK with: circuitBreaker silently adding DeploymentController to CFN (step1)
* simulate CFN output without DeploymentController

```typescript
// step1
// Service with circuitBreaker set/enabled + serviceName is set
    const myEcsService = new ecsPatterns.ApplicationLoadBalancedFargateService(this, 'myEcsService', {
      cluster: cluster,
      memoryLimitMiB: 2048,
      desiredCount: 1,
      cpu: 1024,
      taskSubnets: {
        subnets: selectedSubnets.subnets
      },
      loadBalancerName: `alb-${props.environment}`,
      assignPublicIp: false,
      circuitBreaker: {
        rollback: false,  
      },
      taskDefinition: myTaskDefinition,
      domainName: myDomainName,
      targetProtocol: elbv2.ApplicationProtocol.HTTPS,
      sslPolicy: elbv2.SslPolicy.FORWARD_SECRECY_TLS12_RES_GCM,
      redirectHTTP: false,
      publicLoadBalancer: false,
      recordType: ecsPatterns.ApplicationLoadBalancedServiceRecordType.CNAME,
      protocol: elbv2.ApplicationProtocol.HTTPS,
      domainZone: route53.HostedZone.fromLookup(this, 'HostedZone', {
        domainName: hostedZoneDomain,
        vpcId: this.vpc.vpcId,
        privateZone: true, 
      }),
      propagateTags: ecs.PropagatedTagSource.SERVICE,
      enableECSManagedTags: true,
      certificate: myCertificate,
      minHealthyPercent: 0,
      serviceName: serviceName,
      openListener: false,
    });

// step2
// after "inital" deployment of the service / stack (with fixed ServiceName), remove the DeploymentController from CFN output (which seems like #22328)
    const baseService = myEcsService.node.children.find(child => (child as ecs.BaseService).serviceName) as ecs.BaseService;
    (baseService.node.defaultChild! as ecs.CfnService).addPropertyDeletionOverride('DeploymentController');
```

I really like your PR/the fix, but following this test above (please add step2 code after the intial deployment) showning this breaking stack-updated (even "no changes" were made, just a CDK update). I think (at minimum) a warning/information for "circuitBreaker-user" needs to be added.

Since we have this setup (circuitBreaker + fixed ServiceName string), I doesn't have an idea how we should upgrade to a CDK version having this changed CFN output (regarding DeploymentController). Any ideas how to handle this for existing Services, @fergusdixon?

**Comment by fergusdixon** [comment]
@rgoltz my only solution would be explicitly setting the deploymentController directly in your service. In terms of making this backwards compatible, I don't have a solution

**Comment by fergusdixon** [comment]
@corymhall @rgoltz  do you have any suggestions on how to implement this in a backwards compatible way?

**Comment by fergusdixon** [comment]
@rgoltz @corymhall please see backwards-compatible attempt #22467

**Comment by shellscape** [comment]
@madobrien did the association PR with the `disableExplicitDeploymentControllerForCircuitBreaker` flag fix your issue? we're testing it here without success
