### ISSUE TITLE
(CDKPipelines): `Cannot find module` error in code build step when running `npx cdk synth` command

### ISSUE THREAD

**Issue by brochington** [aws/aws-cdk#16135]
description of the bug:

I am attempting to use the CDKPipeline module to create a pipeline for building and deploying a Typescript web application. I am able to create cdk code that creates the pipeline and build step, and successfully runs npm commands to build my application.

The problem is when my build get to the `npx cdk synth` command, I receive some errors  and the build fails. Here is the error:
```bash
[Container] 2021/08/19 16:26:26 Running command npx cdk synth
--
105 | internal/modules/cjs/loader.js:905
106 | throw err;
107 | ^
108 |  
109 | Error: Cannot find module '/root/.npm/_npx/119/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/aws-sdk/scripts/check-node-version.js'
110 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
111 | at Function.Module._load (internal/modules/cjs/loader.js:746:27)
112 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
113 | at internal/main/run_main_module.js:17:47 {
114 | code: 'MODULE_NOT_FOUND',
115 | requireStack: []
116 | }
117 | npm ERR! code ELIFECYCLE
118 | npm ERR! errno 1
119 | npm ERR! aws-sdk@2.950.0 postinstall: `node scripts/check-node-version.js`
120 | npm ERR! Exit status 1
121 | npm ERR!
122 | npm ERR! Failed at the aws-sdk@2.950.0 postinstall script.
123 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
124 |  
125 | npm ERR! A complete log of this run can be found in:
126 | npm ERR!     /root/.npm/_logs/2021-08-19T16_26_32_401Z-debug.log
127 | Install for [ 'cdk@latest' ] failed with code 1
128 |  
129 | [Container] 2021/08/19 16:26:32 Command did not exit successfully npx cdk synth exit status 1
130 | [Container] 2021/08/19 16:26:32 Phase complete: BUILD State: FAILED
131 | [Container] 2021/08/19 16:26:32 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npx cdk synth. Reason: exit status 1
```

### Reproduction Steps

Here is my cdk code: 

```typescript
    const pipeline = new CodePipeline(this, 'PortalsWebDevPipeline', {
      pipelineName: 'PortalsWebDev',
      synth: new ShellStep('Synth', {
        input: CodePipelineSource.connection(
          'Torus-Portals/portals-web-client',
          'develop',
          {
            connectionArn:
              '<omitted>',
          }
        ),
        commands: ['npm ci', 'npm run build:prod', 'npx cdk synth'],
      }),
    });
```

### What did you expect to happen?

For build to complete.

### What actually happened?

Build doesn't complete.

### Environment

  - **CDK CLI Version  :** 119
  - **Framework Version:**
  - **Node.js Version:** Unclear what is running in the build machine
  - **OS               :** unclear
  - **Language (Version):** Typescript (4.3.5)

### Other

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @brochington :wave:

It looks like [we may have seen this error before.](https://github.com/aws/aws-cdk/issues/14658)

Would you mind sharing your package.json?

I would also double check to make sure you have `aws-cdk` in your dependencies.

**Comment by ryparker** [comment]
Marking as p2 until we can confirm this is not related/fixed by https://github.com/aws/aws-cdk/issues/14658

p2 means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
:pray:

**Comment by brochington** [comment]
@ryparker Thank you for following up. 

I am new to using CDKPipelines, so my familiarity with all involved is....low. Thank you for your help in this. 

Is the assumption that the cdk code lives with the code that I'm building and deploying? This is not true in my case. And perhaps my understanding of `npx` is bad, but it should install any dependencies it needs if they are not already found locally, right?

I'm honestly confused why I'm having to run `cdk` code directly in my build step anyways, and why the output of the 'synth' step is a config instead of an artifact which I can then deploy (in my case to S3).

Perhaps I'm using the wrong tool for my needs? Should I be attempting to build/deploy my app through "regular" pipelines?

**Comment by ryparker** [comment]
> Is the assumption that the cdk code lives with the code that I'm building and deploying?

This does not have to be the case. CDK code can live with your code in the same repository or separate.

> perhaps my understanding of npx is bad, but it should install any dependencies it needs if they are not already found locally, right?

From [Node.JS docs](https://nodejs.dev/learn/the-npx-nodejs-package-runner):
> Running npx commandname automatically finds the correct reference of the command inside the node_modules folder of a project, without needing to know the exact path, and without requiring the package to be installed globally and in the user's path.

> npx allows you to run that npm command without installing it first. If the command isn't found, npx will install it into a central cache.

Using `npx cdk synth` will install the `aws-cdk` package however it will not install other dependencies required by your CDK code. You're already doing this correctly by running `npm ci` before hand.

The output of the synth command is the CloudFormation templates generated in `cdk.out`. Unless otherwise configured using the `primaryOutputDirectory` prop.


> Perhaps I'm using the wrong tool for my needs? Should I be attempting to build/deploy my app through "regular" pipelines?

The `CodePipeline` construct from `@aws-cdk/pipelines` is useful if you're looking to create a simple pipeline that deploys your CDK code. It abstracts away a lot of boiler plate code. However if you foresee yourself wanting to implement more custom steps in your pipeline, such as a manual approval process, some tests, etc. I'd recommend using the `Pipeline` construct from the `@aws-cdk/aws-codepipeline` package.

Are you still experiencing this bug with the latest version of CDK?
