### ISSUE TITLE
(pipelines): changeset approval steps

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#16148]
### Use Case

We'd like to be able to add steps in between the `Prepare` and `Deploy` steps of individual stacks, similar to `pre` and `post`.

Biggest challenge: how do we specify WHERE the additional steps should go?

The obviously similar choice to pre and post:

```ts
pipeline.addStage(new MyStage(), {
    intra: [
        new ManualApprovalStep('Pause'),  // <--- WHERE?
    ]
});
```

Won't exactly work, as the only choice is to add between all stacks, but that might not be what's intended.

```
┌────────────┐           ┌────────────┐                                               
│            │    ...    │            │                                               
│ S1.Prepare │───here?──▶│ S1.Deploy  │────┐                                          
│            │    ...    │            │    │    ┌────────────┐          ┌────────────┐
└────────────┘           └────────────┘    │    │            │   ...    │            │
                                           ├───▶│ S3.Prepare │──here?──▶│ S3.Deploy  │
┌────────────┐           ┌────────────┐    │    │            │   ...    │            │
│            │    ...    │            │    │    └────────────┘          └────────────┘
│ S2.Prepare │───here?──▶│ S2.Deploy  │────┘                                          
│            │    ...    │            │                                               
└────────────┘           └────────────┘             
```

Some discussion: https://cdk-dev.slack.com/archives/C01FDB9UFNV/p1626373420181400

---

This is a :rocket: Feature Request

**Comment by kaizen3031593** [comment]
Continuing the discussion here to try to land on a design that makes sense.

I agree that the design should be similar to `pre` and `post` however i don't love `intra`. I feel like the main difficulty here is that `pre` and `post` are both `Stage` level ideas while `intra` is a `Stack` level idea. Is `intra` enough for a user to understand this and its use case? What we want to say (in a verbose way) is "in a stack, this step happens after prepare and before deploy." Perhaps `beforeStackDeploys` or simply `beforeDeploy` works?

Since it is not enough for `beforeDeploy` to take a `Step`, I think it makes sense for `beforeDeploy` to take list of a new `beforeDeployOptions` object.

```ts
class beforeDeployOptions {
      step: Step;
      stacks: Stack[];
}
``` 

```ts
pipeline.addStage(new MyStage(), {
      beforeDeploy: [ {
           step: new ManualApprovalStep('Pause'),
           stacks: [MyStack1, MyStack2],      
     }],
});
```

---  

I am assuming that the use case for this feature goes beyond adding a `ManualApprovalStep` to approve the changeset pre-deploy. That is, one might want to an automated approval step. If not, I think it might make sense to abstract out the `ManualApprovalStep` entirely and instead just ask for the stacks like:

```ts
pipeline.addStage(new MyStage(), {
      manualChangesetApproval: [MyStack1, MyStack2],
});
```

Then create the `ManualApprovalStep` under the hood for the user.

**Comment by kaizen3031593** [comment]
Spoke with @rix0rrr offline and the current design consensus is to add a new `changeSetApproval` property to `pipeline.addStage()`with the same `step` and `stacks` options as described above.
