### ISSUE TITLE
(aws-eks): Cannot access default fargate profile for new FargateCluster

### ISSUE THREAD

**Issue by magoun** [aws/aws-cdk#16149]
It would be useful to have a way to list all fargate profiles associated with a fargate cluster. Currently there isn't a way to access the default profile created by the FargateCluster construct.

### Use Case

My specific case is to allow `new FargateCluster` to create a default fargate profile, then fetch the pod execution role from that profile and reuse it later when adding further profiles (via CI/CD pipeline).

### Proposed Solution

Ideally, the fargate cluster class would have a fargateProfiles property that could be accessed. It was also work to be able to instantiated a FargateProfile class from a profile arn. That would only require the cluster to return the default profile arn as a property, instead of all profiles of the cluster.

A workaround is to explicitly create the default profile and pod execution role, then output the created execution role for use in the pipeline.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by otaviomacedo** [comment]
Hi, @magoun 

Thanks for this feature request. It should be relatively simple to implement, since we already have the object inside `FargateCluster`:

https://github.com/aws/aws-cdk/blob/6a20e61dd2ed8366cbff1451c943a02b79380de2/packages/@aws-cdk/aws-eks/lib/fargate-cluster.ts#L34

It's just a matter of exposing it as a `public readonly` attribute (in addition to unit tests and documentation, of course). We can't work on this immediately, but if you are interested in submitting a PR, I'm happy to review it.

**Comment by readybuilderone** [comment]
Hi @magoun and @otaviomacedo , if you don't mind, I'd like to working on this to solve this issue, I just want to confirm with you.
