### ISSUE TITLE
(cognito): UserPoolClient does not correctly respect authFlows

### ISSUE THREAD

**Issue by kazkansouh** [aws/aws-cdk#16236]
I have a simple definition such as:

```typescript
    const userPoolClient = new UserPoolClient(this, 'MyUserPool', {
      userPool,
      oAuth: {
        callbackUrls: ['http://localhost/callback'],
        flows: {
          authorizationCodeGrant: true,
        },
        scopes: [OAuthScope.OPENID, OAuthScope.PROFILE],
      },
      generateSecret: false,
      authFlows: {
        custom: false,
      },
    });
```

Notice, that it sets the `custom` auth flow to to `false`. However, after deploying this the following is observed in the console:

![Screenshot_20210826_102941](https://user-images.githubusercontent.com/527411/130938777-df64f386-a238-4557-8a62-c3af0510c2df.png)

I.e. both custom and SRP are enabled without me specifying this.

### Cause

I believe the below function is at fault as it only checks if any values are true before setting the CloudFormation property `ExplicitAuthFlows`.

https://github.com/aws/aws-cdk/blob/1d54a456cd5e2ff65251097f9a684e1ac200cc52/packages/%40aws-cdk/aws-cognito/lib/user-pool-client.ts#L410-L428

### Possible Solution

Possibly the following:

https://github.com/aws/aws-cdk/blob/1d54a456cd5e2ff65251097f9a684e1ac200cc52/packages/%40aws-cdk/aws-cognito/lib/user-pool-client.ts#L419-L422

Should be changed to unconditionally push `ALLOW_REFRESH_TOKEN_AUTH` (as the case `props.authFlows` is undefined is already handled). I.e., it should be changed to:

```typescript
authFlows.push('ALLOW_REFRESH_TOKEN_AUTH'); 
```

This would mean when the user provides a `authFlows` property the default behaviour will always be replaced, not only if a true value is provided for one of the options.

**Comment by diego-santacruz** [comment]
I stumbled on this problem today.
As explained above in other words, when all `authFlows` properties are `false`, or no `authFlows` are specified there is no `ExplicitAuthFlows` property in the resulting CloudFormation template. Although not clear in the CloudFormation doc nor the Cognito API, this creates a client with the "default" value for the allowed auth flows, which custom, SRP and refresh token flows enabled as shown above, which is not what the CDK `UserPoolClient` doc indicates.

As proposed above the expected behavior would be achieved by always including `ALLOW_REFRESH_TOKEN_AUTH` in `ExplicitAuthFlows`, as that flow must always be accepted.

I have added `userPoolClient.node.defaultChild.addPropertyOverride('ExplicitAuthFlows', ['ALLOW_REFRESH_TOKEN_AUTH'])` to my code as a workaround.
