### ISSUE TITLE
aws-s3: CDK construct for S3 batch operations

### ISSUE THREAD

**Issue by mansareddy98** [aws/aws-cdk#16275]
There is no mention of any CDK constructs for S3 batch operations [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-readme.html). Are there no such constructs or is it not documented in this.

**Comment by peterwoodworth** [comment]
Hey @mansareddy98,

We have a [`Batch`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-batch-readme.html) module, but I don't think this is what you're looking for. My understanding is that S3 batch operations is a distinct service which S3 takes ownership of.

If my understanding is correct here, then there's currently no construct for S3 batch operations. This is because [CloudFormation doesn't have any support for s3 batch operations](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_S3.html)
