### ISSUE TITLE
(cloudfront): functions not published as live

### ISSUE THREAD

**Issue by jordanmonier** [aws/aws-cdk#16319]
Hi 👋 ,

We are using some Cloudfront Functions for one of our stack but sadly we've encountered a problem recently. We don't know why but sometimes the function are created but the distribution is not associated with it. 
This is a breaking bug because one of our website is not working as intended without the function.

It seems to be random, sometimes it will work, sometimes it won't.

### Reproduction Steps

```ts
new cloudfront.Distribution(this, 'Distribution', {
  errorResponses: [
    {
      httpStatus: 404,
      responseHttpStatus: 200,
      responsePagePath: '/',
    },
  ],
  defaultBehavior: {
    origin: new cloudfrontOrigins.S3Origin(this.webBucket),
    functionAssociations: [{
      function: new cloudfront.Function(this, `StaticSite${this.node.addr}`, {
        comment: 'Static Site provided by @mds-devteam/aws-constructs',
        code: cloudfront.FunctionCode.fromInline(`
          function handler(event) {
            var request = event.request
            var uri = request.uri
                
            if (uri.endsWith('/')) {
              request.uri += 'index.html'
            } else if (!uri.includes('.')) {
              request.uri += '/index.html'
            }

            return request
          }
        `),
      }),
      eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
    }]
  },
})
```

### What did you expect to happen?

The function to be published as live.

### What actually happened?

The function was created but the distribution was not associated to it.

### Environment

  - **CDK CLI Version  :** 1.120.0
  - **Framework Version:** 1.120.0
  - **Node.js Version:** 14
  - **OS               :** macOS
  - **Language (Version):** Typescript 4.2.3

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Very strange!

The `Function` is hard-coded to always set `autoPublish: true`, which should always publish the function to live.

https://github.com/aws/aws-cdk/blob/a534829b2458c5ed54d05fd5cca025cba2ddaaa7/packages/@aws-cdk/aws-cloudfront/lib/function.ts#L165

> We don't know why but sometimes the function are created but the distribution is not associated with it.

Is this happening on brand-new stack creation, or in incremental updates (or both)?
Does the function correctly publish to live, and just not associate with the distribution, or is it left as a draft function?
Are there any differences in the template itself (e.g., `cdk diff`) between when it works and doesn't? Ultimately, if you deploy the same CloudFormation template multiple times, and get multiple results, that would point to a CloudFormation issue, rather than CDK itself. I'd be curious if that's the case.

**Comment by jordanmonier** [comment]
It happens on both cases (brand-new, updates) and it's very strange because sometimes deleting the sack and re-deploying does the work. In one of our project, we use two functions for one distri and we never have both working at the same time.

![Capture d’écran 2021-09-07 à 10 18 58](https://user-images.githubusercontent.com/70213307/132310343-a1791a2a-09d5-4d88-8842-0c0b15d47fac.png)

**Comment by njlynch** [comment]
Ultimately, if the same CloudFormation template is deployed multiple times, and a buggy result is observed some of the time, it sounds like there's a potential race condition on the CloudFormation side.

Given that, I would recommend filing an issue in the AWS forums (either for [CloudFormation](https://forums.aws.amazon.com/forum.jspa?forumID=92) or for [CloudFront](https://forums.aws.amazon.com/forum.jspa?forumID=46)), or if you have AWS support, reaching out to them. I don't think there's anything we can do on the CDK side here to fix this.
