### ISSUE TITLE
(core): Option to separate IAM resources into a single stack and update resources that use them

### ISSUE THREAD

**Issue by maafk** [aws/aws-cdk#16404]
Ability to pull out all IAM resources into a separate Cloudformation stack, and update references to IAM roles, policies and instance profiles using a lookup.

For example:
-  [`iam.Role.fromRoleArn`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.Role.html#static-fromwbrrolewbrarnscope-id-rolearn-options) and set [`mutable`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-iam-readme.html#using-existing-roles) to `false`
- [`iam.ManagedPolicy.fromManagedPolicyName `](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.ManagedPolicy.html#static-fromwbrmanagedwbrpolicywbrnamescope-id-managedpolicyname)

### Use Case

Many enterprises require a separation of duties between deploying IAM resources and deploying other AWS resources.

For example a security team has the permissions to deploy IAM resource, but development teams are only able to use pre-existing IAM roles, policies and instance profiles.

Before a development team is able to deploy their CDK applications, the IAM resources must pre-exists, and be utilized by a lookup since the team doesn't have `iam:*` permissions.

Often Security teams will say "give me all the IAM policies/roles that your application will need". When developers are building with this assumption, their CDK code will look very different than CDK best practices.

### Proposed Solution

synth option to allow to pull out IAM resources to a separate stack

```typescript
import * as cdk from '@aws-cdk/core';
import { MyStack } from '../bin/my-stack';

const app = new cdk.App();

new MyStack(app, 'MyStackWithIamAndResources');

app.synth(
    extractIam: true
);
```

And when a `cdk ls` is run, it would include

```zsh
$ cdk ls
IamStack
MyStackWithIamAndResources
```

Where `IamStack` would include _only_ the IAM resources defined in `MyStack`, and the `MyStackWithIamAndResources` would reference IAM resources created in `IamStack`, assuming another team/person/group had already deployed the `IamStack`

### Other

While it's possible to write CDK with individual enterprise IAM constraints in mind, it becomes difficult to use pre-built CDK L3 constructs, or leverage the [CDK construct library](https://aws.amazon.com/solutions/constructs/patterns/).

Having the ability to write CDK in a "best practices" manner while still being able to comply with enterprise IAM policies would save a lot of time for enterprise users

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by dontirun** [comment]
I often find the same problem with customers and would like a similar feature, but there are some things to consider here.

1. Resource scoping
   * S3 buckets have a global namespace. Names of buckets would have to be known beforehand, which is a problem since that name could be taken by someone else
   * Similar problem for non globally named objects, but this can more easily be mitigated since resource names are local to the account. However this could pose an issue to updates since named resources sometimes have issues with replacement.
      * Ex. AutoScaling Launch Configurations will fail to update if the same name is used and the resource is mutated

**Comment by rix0rrr** [comment]
It's a good idea, but it will not work the way CDK creates resources.

Most CDK-generated policy statements are of the form:

```
    {
      "Effect": "Allow",
      "Action": "s3:GetBucket",
      "Resource": { Ref: BucketInThisTemplate }
    },
```

If we're going to pull all IAM resources out into a separate stack, the name of `BucketInThisTemplate` cannot be known yet, so it cannot be deployed.

The alternative is `Resource: *` but that seems worse.

A workaround for this is forcing all resources to be given a physical name, but that has other downsides in CloudFormation (replacement becomes impossible).

We are sensitive to this issue, and I will leave the ticket open to collect ideas... but simply segregating all IAM resources into a separate stack is not the solution.

**Comment by dontirun** [comment]
This is probably beyond the scope of CDK, but I think the underlying issue is that security teams want to be able to inspect permission granting resources (IAM policies, KMS key policies, Bucket policies) pre-deployment. Theoretically If there was a method to implement a [two-person](https://en.wikipedia.org/wiki/Two-man_rule) rule where

1. Developers  with X permissions stage a change set
2. Security team with Y permissions inspect the change set
3. Developer team and Security team both grant approval
4. X+Y permissions are used to deploy the stack

Much of that isn't currently possible, but would solve the underlying issue.

One possible workaround implementation (not particularly good) could be
1. Create the stack and resources with imported IAM roles with no permissions (so effectively the app doesn't work
2. Synthesize a template after deployment to show what those permissions on those roles should be updated to
3.  The security team uses the template to update the roles
