### ISSUE TITLE
(iam): set up MFA for IAM users

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#16511]
When the CDK stack controls creation of users and those users set up their MFA, CDK (actually CloudFormation) cannot destroy the User resource anymore.

This seems like a missing `purge` feature on CloudFormation side as trying to delete the stack from the console results in the same error. The admin must manually go into the deleted user, remove the MFA device and only then destroy the stack.

### Reproduction steps

- create a stack with the below code to manage creation of users in the account:
```
   new User(this, 'user', {
      userName: 'user',
      password: SecretValue.ssmSecure('/iam/initial-password', '1'),
      passwordResetRequired: true,
    });
```

- deploy the stack
- log in to the created account and set up MFA
- try to do `cdk destroy` 

Result:

```
10:41:32 PM | UPDATE_COMPLETE_CLEA | AWS::CloudFormation::Stack | AStack
10:41:34 PM | DELETE_FAILED        | AWS::IAM::User          | userBF2C4EAF
Cannot delete entity, must delete MFA device first. (Service: AmazonIdentityManagement; Status Code: 409; Error Code: DeleteConflict; Request ID: ...; Proxy: null)
```

The stack hangs in an unrecoverable state:
```
Stack is in UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state and can not be updated
```

### Versions
```
cdk version 1.122.0
```

Let me know in case I should report this directly via the support team and get back here with the reference ID.

**Comment by rix0rrr** [comment]
This behavior is by design in IAM.

It's also by design in CloudFormation and CDK: any changes made outside the IaC management scope are "out of bounds", and not safe to touch (or even not reasonable for the system to know about).

The right way to do this would be to tell CloudFormation about the MFA device, so that it can clean it up again.

* Either add MFA support to CDK
* Or use an L1, I'm assuming `CfnVirtualMfaDevice` (works like https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-virtualmfadevice.html)
* Or, most direct solution: write a Custom Resource that on a `Delete` event lists any MFA devices for a user and deletes them.

Leaving open as feature request
