### ISSUE TITLE
(aws-ecs): fromFargateServiceAttributes() using serviceArn does not return correct serviceName

### ISSUE THREAD

**Issue by qinjie** [aws/aws-cdk#16634]
When I use `fromFargateServiceAttributes()` to import an existing FargateService, its returned object doesn't has correct fargate service name if I use `serviceArn` as attribute, whereas passing `serviceName` attribute to the function returns object with correct service name. 

### Reproduction Steps

```
    const importedFargateService =
      ecs.FargateService.fromFargateServiceAttributes(
        this,
        "imported-fargate-service",
        {
          // serviceArn: cdk.Fn.importValue(
          //   `${this.project_code}-FargateServiceArn`
          // ),
          //serviceName: cdk.Fn.importValue(
          //  `${this.project_code}-FargateServiceName`
          //),
          cluster: importedCluster,
        }
      );

    new cdk.CfnOutput(this, "importedFargateServiceName", {
      value: importedFargateService.serviceName,
    });

    new cdk.CfnOutput(this, "importedFargateServiceArn", {
      value: importedFargateService.serviceArn,
    });

    new cdk.CfnOutput(this, "importedFargateClusterName", {
      value: importedFargateService.cluster.clusterName,
    });

    new cdk.CfnOutput(this, "importedFargateClusterArn", {
      value: importedFargateService.cluster.clusterArn,
    });
```

### What did you expect to happen?

CloudFormation outputs should give correct FargateService name.
![image](https://user-images.githubusercontent.com/5250442/134603712-654220fb-9e3f-4ce6-8746-6774ecd1fee0.png)

### What actually happened?

FargateService name is the same as cluster name.
![image](https://user-images.githubusercontent.com/5250442/134603843-16a0e0db-2ef9-491b-845b-3f96b2c35767.png)

### Environment

  - **CDK CLI Version  : 1.122.0 **
  - **Framework Version: aws-cli/2.2.6 Python/3.8.8 Windows/10 exe/AMD64 prompt/off**
  - **Node.js Version: 14.17.0** 
  - **OS               : Windows 10**
  - **Language (Version): TypeScript (4.3.5) ** 

This is :bug: Bug Report

**Comment by madeline-k** [comment]
Thanks for opening this issue, @qinjie! 

@jumic, I think you have a good idea of the implementation needed to resolve this. Are you willing to implement this and open a PR? Take a look at our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started. Your proposed solution is one option, but I think it would be even better if we could parse the ARN and determine which format it is based on the number of `/` and then do the correct thing. Let me know if you think there is a reason that wouldn't work.

**Comment by jumic** [comment]
@madeline-k Yes, I can implement a fix for this issue.

You're right. Determining the correct logic based on the number of `/` should be the first option.

In case of a tokenized ARN, we can't identify if the old or the new logic should be used. Currently, the old logic is executed. I would propose to change the default behavior for tokenized ARNs to the new format. The change of the default format is a breaking change, therefore I would create a feature flag for it. What do you think?

**Comment by tobytipton** [comment]
@jumic the case of the tokenized ARN happens when creating a new service based on the fact that the [serviceArn is created as a token](https://github.com/aws/aws-cdk/blob/ef8ab7245630f54b5a633925e27b34c31b712abc/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L429-L433).  Using the tokenized ARN has other issues as well like when you are are using the fromFargateServiceAttributes with the tokenized serviceArn it can't determine the region and/or account.  

You can do something like this to set the serviceArn in the stack which is creating the ECS service.
```
const serviceArn = this.formatArn({
  service: 'ecs',
  resource: 'service',
  resourceName: `${cluster.clusterName}/${service.serviceName},
});
```
Which gets past the tokenized ARN being passed into as the serviceArn.

I am wonder if it would it possible to change the serviceArn from being a full token to change the serviceArn in the base-service to be something like this.
```
    this.serviceArn = Stack.of(this).formatArn({
      service: 'ecs',
      resource: 'service',
      resourceName: `${props.cluster.clusterName}/${this.physicalName}`,
    });
```

This would make the ARN still have tokens but the clusterName, serviceName, account, region, partition would be tokens however think this would then let it parse correctly.  I am not sure sure if it has other side effects though.

In theory all new services which are being created at this point should be using the new format, the old format might still exist for services created previously though.  Does there need to be a feature flag to support the new format, since based on https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-account-settings.html#ecs-resource-arn-timeline new services should use the new format?

**Comment by jumic** [comment]
@tobytipton 

> Using the tokenized ARN has other issues as well like when you are are using the fromFargateServiceAttributes with the tokenized serviceArn it can't determine the region and/or account.

Is this issue related to the new ARN format? If not, could you please create a new issue for it to discuss it there? We would try to avoid mixing topics that are not related.

> I am wonder if it would it possible to change the serviceArn from being a full token to change the serviceArn in the base-service to be something like this.

Could you please provide more information to this proposal? I don't understand it yet. Which public method is affected?  What is the result without and after this change? (Again, is it related to the new ARN format or something different?)

> In theory all new services which are being created at this point should be using the new format, the old format might still exist for services created previously though. Does there need to be a feature flag to support the new format, since based on https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-account-settings.html#ecs-resource-arn-timeline new services should use the new format?

From my point of view, we have to handle the change as breaking change because of the semantic versioning. If a customer uses an ECS service in the old format and we change the CDK logic to the new format, it leads to a wrong value. Therefore, we can't change it without feature flag. As long as the correct format can be detected automatically, a feature flag is not necessary. If the ARN is parsed from a token, we need to define a default logic that is executed (old or new format). In my opinion, changing the default logic requires a feature flag.

If you have comments / remarks to my PR, please leave a review comment there. Thanks.
