### ISSUE TITLE
(Glue): How to to grant permission to lambda

### ISSUE THREAD

**Issue by spmacdonald** [aws/aws-cdk#16649]
I have a lambda function that uses `awswrangler` to write datasets to a Glue database.  I create the Glue database in my CDK stack like:

```
        glue_db = glue.Database(self, 'MyGlueDatabase',
            database_name='mydb'
        )
```

Then when I deploy this stack I see the error in the lambda function logs:

```
AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetTable operation: User: arn:aws:sts::foo:assumed-role/<lambda func>/<lambda func> is not authorized to perform: glue:GetTable on resource: arn:aws:glue:us-west-1:foo:catalog
```

How can I grant access to the lambda function?  I was hoping for a `glue_db.grant_read_write(lambda_func)` type of method, but I don't see anything like this?

**Comment by kaizen3031593** [comment]
Hi @spmacdonald! While I might need a bit more context to help you, here are my preliminary thoughts. A database is a collection of tables, and it looks like your error is between your lambda and your table (instead of the whole database). On a glue table, there are a suite of grant methods that you can use to help. It looks like you would want to use `table.grantReadWrite(grantee: iam.IGrantable)` (translated to Python). 

Let me know if that helps! If not, could you provide a reproducible code block so that I can have the full picture?

**Comment by spmacdonald** [comment]
Hey thanks for the fast reply.  Your explanation makes sense, and if I create a table in the CDK code that does indeed solve it.

I am kind of new to this whole Glue world, so maybe I am misunderstanding something, but in my application we choose to use Glue and Athena so we would not have to define the schema for our reports.  We have maybe 100 different types of reports, all CSV files with a stable schema (each CSV file has a different set of columns but they do not change over time).

In my lambda function I use data wrangler like:

```
    # Store the report in AWS Glue Database
    wr.s3.to_parquet(
        df=df,
        path=f's3://{S3_BUCKET}/datasets/{report.s3_path}/',
        dataset=True,
        database=GLUE_DATABASE_NAME,
        table=report.s3_path,
        mode='overwrite_partitions',
        partition_cols=['trading_date']
    )
```

This seems to work well.  Am I missing something?  Are you supposed to explicitly define tables in Glue database?

By the way, I solved my initial question by adding a IAM policy to the Lambda:

```
        # Grant lambda ETL access to Glue database.
        glue_policy = iam.PolicyStatement(
            actions=['glue:*'],
            resources=['*']
        )

        etl_lambda_fn.role.attach_inline_policy(
            iam.Policy(self, 'EtlLambdaPolicy',
                statements=[glue_policy]
            )
        )
```

Appreciate your help, and any comments you have on best practices here.  Still learning. Cheers

**Comment by kaizen3031593** [comment]
Hi @spmacdonald, I'm not an expert on best practices in this area but I would say that in general, you want your IAM policies to adhere to the principle of least privilege (which means its usually not the best idea to give the policy access to all resources via `resources=['*']`). @peterwoodworth is there a permission pattern in Glue for this particular use case?

**Comment by peterwoodworth** [comment]
AWS Glue has some pretty extensive documentation on IAM permissions, check it out [here](https://docs.aws.amazon.com/glue/latest/dg/authentication-and-access-control.html).

Like kaizen said, I want to emphasize that you want to adhere to the principle of _least privilege_. Using the `*` will grant access to _all_ resources.

Feel free to ping me if you have any additional questions @spmacdonald, otherwise any questions regarding best practice for using other services are probably best answered by looking at their documentation.

**Comment by spmacdonald** [comment]
Ok, thanks for the advice.  I guess my question was around granting permission to the lambda access at the database level, rather than having to create Table constructs in the CDK and grant access to each table.

**Comment by peterwoodworth** [comment]
Yes @spmacdonald, the answer to this can be found in the documentation: https://docs.aws.amazon.com/glue/latest/dg/glue-specifying-resource-arns.html#data-catalog-resource-arns

> To enable fine-grained access control, you can use these ARNs in your IAM policies and resource policies to grant and deny access to specific resources. Wildcards are allowed in the policies. For example, the following ARN matches all tables in database default.
> `arn:aws:glue:us-east-1:123456789012:table/default/*`
