### ISSUE TITLE
(python eks): EndpointAccess only_from method cidr parameter be list of string

### ISSUE THREAD

**Issue by ymwdalex** [aws/aws-cdk#16661]
In Python CDK EKS module, EndpointAccess only_from method cidr parameter is string type.
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_eks/EndpointAccess.html?highlight=endpointaccess#endpointaccess

However, it should a list of string.

In typescript CDK code, the parameter seems also be list of string: https://github.com/aws/aws-cdk/blob/83dd318959b1b1e5f94b5a31030d03379638c9ad/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L561

### Reproduction Steps
In python cdk document and code

### What did you expect to happen?
EndpointAccess allow to use list of cidr string as input

### What actually happened?
Only allow on cidr string

### Environment

  - **CDK CLI Version  :*1.124*
  - **Framework Version:**
  - **Node.js Version:** v14.16.0
  - **OS               :** OSX
  - **Language (Version):** python

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @ymwdalex 👋🏻 

Thanks for bringing this to our attention. This seems to be a bug in our docs generation since the type is accurately set to `string[]` in the code you linked.

I'm going to mark this as a p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).) :pray:

**Comment by ymwdalex** [comment]
@ryparker thanks for the feedback. It is pity that the priority of this bug is not high enough to trigger direct action from CDK team, but understood.

Could you please pinpoint some directions (document about cdk docs generation, key files or code snippet) which helps to fix this bug? I can take a look and give a try, since I am really waiting for this bug fix for the product I am building.

**Comment by ymwdalex** [comment]
> Hey @ymwdalex 👋🏻
> 
> Thanks for bringing this to our attention. This seems to be a bug in our docs generation since the type is accurately set to `string[]` in the code you linked.
> 
> I'm going to mark this as a p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

Hi @ryparker , I think it is not only a bug in the document. Maybe my issue description is not clear. The code in the python package aws_cdk.aws_eks is also not correct! The `cidr` parameter of `only_from` should be list of str instead of str!
```
class EndpointAccess(
    metaclass=jsii.JSIIMeta,
    jsii_type="@aws-cdk/aws-eks.EndpointAccess",
):
    '''Endpoint access characteristics.'''

    @jsii.member(jsii_name="onlyFrom")
    def only_from(self, *cidr: builtins.str) -> "EndpointAccess":
        '''Restrict public access to specific CIDR blocks.

        If public access is disabled, this method will result in an error.

        :param cidr: CIDR blocks.
        '''
        return typing.cast("EndpointAccess", jsii.invoke(self, "onlyFrom", [*cidr]))
```

**Comment by shcherbak** [comment]
it is a pity that this error is not fixed

**Comment by rayderua** [comment]
we are still suffering from this error

**Comment by mdanovz** [comment]
Yes. We have the same problem.

**Comment by juehai** [comment]
I think it's required a tuple in Python.

Looked into the typescript code below, it's using a spread operator (in form of ellipsis). It means `onlyFrom(arg1, arg2, arg3)` will be converted to [arg1, arg2, arg3], and each args is a string.

https://github.com/aws/aws-cdk/blob/585f9caf1f0e277f6cdc9428e10ef8efc1e8cdf2/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L697

In Python it's a Tuple instead of a List, I don't have a Python code to verify this, but you could try the following way, it should resolve the issue.

```
cidrs = ['0.0.0.0/0', '127.0.0.1/32']
onlyFrom(*cidrs)
```

**Comment by shcherbak** [comment]
@juehai thank you for great workaround

**Comment by nilroy** [comment]
@juehai Thank you. It works for me as well

**Comment by TheRealAmazonKendra** [comment]
The fix for this needs to be done in jsii. An issue has been opened there, as linked above, so this is now just serving as a duplicate issue. I'm going to go ahead and close it in favor of the one in the jsii repo.
