### ISSUE TITLE
aws-ecs-patterns: Default value for `healthCheckGracePeriod` is not long enough, causes delays in ECS deployments

### ISSUE THREAD

**Issue by sahilpalvia** [aws/aws-cdk#16675]
The default `healthCheckGracePeriod` of 60 seconds for `NetworkLoadBalancedEc2Service` is not long enough. It causes the hosts to potentially bounce between `initial` and `draining` states. According to the [NLB documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html): `It can take a few minutes for the registration process to complete and health checks to start`. The `healthCheckGraccePeriod` is used by ECS to ignore any `unhealthy` health checks from the NLB. Once a host is registered successfully the first status of the host is `unhealthy`. If registration takes more than 60 seconds, this health causes ECS to put the service into draining state and bring up a new service, causing the host to bounce between `initial` and `draining`. In practice based on registration time and default health check configurations for the NLB, 300+ seconds would be a good value for `healthCheckGracePeriod`.

### Reproduction Steps

Spin up a service using `NetworkLoadBalancedEc2Service` construct.

### What did you expect to happen?

The service to successfully deploy using ECS deploy.

### What actually happened?

As explained in the description, the service kept on bouncing between `initial` and `draining` causing deployments to take multiple hours to stabilize.

### Environment

  - **CDK CLI Version  :*1.122.0 (build ae09c16)*
  - **Framework Version:*1.23.0*
  - **Node.js Version:*v14.16.1*
  - **OS               :*OSX*
  - **Language (Version):*TypeScript (4.4.3)*

### Other

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @sahilpalvia 👋🏻 Thanks for opening the bug report.

The workaround for this is to manually provide an extended duration to the [`healthCheckGracePeriod` prop](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.NetworkLoadBalancedEc2Service.html#healthcheckgraceperiod). Maximum possible value is 2,147,483,647 seconds.

I'm going to mark this as p2 since there is a workaround. p2 means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).) :pray:

I think it is also important to note that the CloudFormation defaults are as follows:

> If your service has a load balancer defined and you don't specify a health check grace period value, the default value of 0 is used.

_[from CloudFormation ELB target group docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-healthcheckgraceperiodseconds)_

With that said, since we are already offering a default value that differs from CloudFormation then it should be acceptable to adjust that value.

@madeline-k do you agree?

**Comment by sahilpalvia** [comment]
Agree there is a work around, and that is what we used. 

> With that said, since we are already offering a default value that differs from CloudFormation then it should be acceptable to adjust that value.

This issue was created more for updating the default values, so that other customers don't have to go digging around for configurations for a basic application.

**Comment by madeline-k** [comment]
Hello @sahilpalvia, thanks for opening this issue, and providing data about why you think the default `healthCheckGracePeriod` should be longer. We unfortunately cannot update this default value from 60 to 300 seconds, because that would be a breaking change. And, users relying on the default would start to see their deployments taking 5x longer to fail when the health checks failing are indicative of a real issue. 

I'd recommend adding some detail to the doc-comment for this property to help other customers more quickly discover what configuration changes they should make if they run into the same scenario.

**Comment by sahilpalvia** [comment]
HI @madeline-k, I think there is a miss in understanding what the property does. Deployment failures or with ECS deployments are configured in the deploy action. This configuration is for allowing new hosts coming up to take up to 5 mins before marking them bad for redeployment.
