### ISSUE TITLE
(lambda): Changes in lambda env not deployed. No changes found. 

### ISSUE THREAD

**Issue by davidlbyrne** [aws/aws-cdk#16759]
### What is the problem?

When I define a lambda with env vars, when the value of the env var changes, the function is not updated with the new value. I am sourcing the value from secrets manager. 

### Reproduction Steps
I apologize for the funky formatting. 

1. fetch a secret value and function like so: 
```typescript

const apikey = Secret.fromSecretPartialArn( this, `secrets-${props.environmentName}-${secret}`,
            `arn:aws:secretsmanager:${props.region}:${Account.SECSECRETS}:secret:${props.app}/${env}`,
             ).secretValueFromJson('apikey');

const fn = new WatchableNodejsFunction(this, 'callout', {
	  	entry: `${__dirname}/../handlers/callout.ts`,
	  	memorySize: 512,
	  	runtime: lambda.Runtime.NODEJS_14_X,
	  	timeout: Duration.seconds(10),
	  	environment: {
	  	           APIGW_HOSTNAME: apigwurl,
                           APIGW_KEY: apikey,
                           APIGW_METHOD: 'GET',
                           APIGW_PATH:  '/v1/users'
	  	},
	  	role: sflRole,
                vpc: commonVpc
                });
 ```
2. `cdk deploy` the function. 
 
3. Go into secret manager and change the value of your secret.  

4.  Do another `cdk deploy` No changes are detected and the value of  APIGW_KEY is not changing. You can confirm this in the lambda UI 
 

### What did you expect to happen?

Lamda function with be updated to reflect the new value. 

### What actually happened?

No changes are detected and the new value is not updated. 

### CDK CLI Version

cdk --version  1.124.0 (build 65761fe)

### Framework Version

1.122.0

### Node.js Version

node --version v16.6.0

### OS

osx

### Language

Typescript

### Other information

The apikey is a secret sourced upstream from secrets manager. The value of the secret is changing but the function is not updating.

**Comment by skinny85** [comment]
Hey @davidlbyrne, this is probably this issue: https://github.com/aws/aws-cdk/issues/16444.

Thanks,
Adam

**Comment by davidlbyrne** [comment]
Possibly, is it enough to say that any change in the lambda env vars "values" should cause a stack update?

**Comment by nija-at** [comment]
@davidlbyrne - can you confirm if you're using the `--hotswap` command or just standard `cdk deploy`.

**Comment by davidlbyrne** [comment]
> @davidlbyrne - can you confirm if you're using the `--hotswap` command or just standard `cdk deploy`.

I am not using `--hotswap` 

If you think this will help I can try it.

**Comment by jogold** [comment]
I think this is the normal CF behavior: your template doesn't change because it references your secret and a key but not value, so there's nothing to deploy.

Event if after updating the secret value, redeploying your template would update the Lambda function this would not guarantee that your Lambda runtime code and secret value are always in sync (just after updating the secret value your Lambda still uses the old value).

Possible workarounds:
1. Fetch (and cache) the secret value in your runtime code
2. Add an env var with a timestamp or a version to trigger a deploy

To ensure runtime code and secret value are always in sync I would go for option 1.
