### ISSUE TITLE
(lightsail): support lightsail instance

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#16852]
### Description

To support the `AWS::Lightsail::Instance`:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-instance.html

### Use Case

allow users to use `Instance` L2 construct.

### Proposed Solution

create a L2 construct class for `Instance`

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Also, since Lightsail doesn't have any L2s yet this might be a good opportunity to use the [RFC process](https://github.com/aws/aws-cdk-rfcs#rfc-process) Before starting work on the implementation.

**Comment by Iazzetta** [comment]
Are you implementing Lightsail in CDK? Is there any progress? I can contribute if needed. I'm not up to date with the situation, but if there's some initial work done, I can continue it.
