### ISSUE TITLE
Unable to create RouteSettings & AccessLogSettings in CfnStage of APIGatewayv2 for .Net

### ISSUE THREAD

**Issue by Manish082007** [aws/aws-cdk#16901]
### General Issue

Not able to create RouteSettings & AccessLogSettings for WebSocket API through .NET CDK APIGatewayv2

### The Question

I am trying to create a WebSocket API using CDK in the .NET C# language. I am using CFN resources to create WebSocket API as Higher level constructs for WebSocket APIs are still in the Experimental stage. 

### Problem with RouteSettings
In CfnStage, When I am specifying RouteSettings like JObject/Dictionary/Class it's not working. In the case of JObject it is showing in the CDK synth template but when I am trying to deploy, it's giving errors like 
```
_"Property validation failure: [Value of property {/RouteSettings/LoggingLevel} does not match type {Object}, Value of property {/RouteSettings/DataTraceEnabled} does not match type {Object}, Value of property {/RouteSettings/ThrottlingBurstLimit} does not match type {Object}, Value of property {/RouteSettings/DetailedMetricsEnabled} does not match type {Object}, Value of property {/RouteSettings/ThrottlingRateLimit} does not match type {Object}]"_
```
```c#
dynamic routeSettings = new JObject();
routeSettings.DataTraceEnabled = true;
routeSettings.DetailedMetricsEnabled = true;
routeSettings.LoggingLevel = "ERROR";
routeSettings.ThrottlingBurstLimit = 10;
routeSettings.ThrottlingRateLimit = 10;
```
**When I give Class or Dictionary CDK template is not getting compiled.**

**I have tried to specify Dictionary of <string key name, object value name>, By creating RouteSettings Class & JObject too. But none of the options seems to work. I have seen the example in typescript but I guess there is some bug with the .NET CDK version. I have specified the same settings in DefaultRouteSettings too but no luck.**

### Problem with AccessLogSettings

In CfnStage, When I am specifying AccessLogSettings like JObject, it is not at all showing in the CDK synth template. I tried everything but it is now showing in the CDK synth template. 

I am specifying AccessLogSettings like below
```c#
dynamic accessLogSettings = new JObject();
            accessLogSettings.DestinationArn = claimsServiceWebSocketApiLogGroup.AttrArn;
            accessLogSettings.Format = "{\"requestId\":\"$context.requestId\",\"ip\":\"$context.identity.sourceIp\",\"caller\":\"$context.identity.caller\",\"user\":\"$context.identity.user\",\"requestTime\":\"$context.requestTime\",\"eventType\":\"$context.eventType\",\"routeKey\":\"$context.routeKey\",\"status\":\"$context.status\",\"connectionId\":\"$context.connectionId\",\"errorMessage\":\"$context.error.message\",\"validationError\":\"$context.error.validationErrorString\"}";


Please dynamic accessLogSettings = new JObject();
            accessLogSettings.DestinationArn = claimsServiceWebSocketApiLogGroup.AttrArn;
            accessLogSettings.Format = "{\"requestId\":\"$context.requestId\",\"ip\":\"$context.identity.sourceIp\",\"caller\":\"$context.identity.caller\",\"user\":\"$context.identity.user\",\"requestTime\":\"$context.requestTime\",\"eventType\":\"$context.eventType\",\"routeKey\":\"$context.routeKey\",\"status\":\"$context.status\",\"connectionId\":\"$context.connectionId\",\"errorMessage\":\"$context.error.message\",\"validationError\":\"$context.error.validationErrorString\"}";
```

I tried to find some examples for .NET on the internet but no luck. Please let me know If I doing anything wrong. I highly doubt that there is some bug with the .NET CDK deployment.

### CDK CLI Version

1.127.0

### Framework Version

.Net Core 3.1

### Node.js Version

v14.17.6

### OS

Windows 10

### Language

.NET

### Language Version

C# 8.0

**Comment by NGL321** [comment]
Hey @Manish082007,

My apologies for delayed response here. From what I can discern, if you are experiencing failures during deploy but not synth, it is likely a problem within Cloudformation rather than CDK (that said, that doesnt disqualify it as a CDK problem as the CDK could be generating an incorrect template).

From the [API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.CfnStage.html) it appears that `routeSettings` SHOULD be passed as JSON, but `accessLogSettings` actually takes an object of type [`AccessLogSettingsProperty`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-stage-accesslogsettings.html) which consists of `DestinationArn` and `Format`. Rather than setting the value as a `JObject` with those fields, you should use an object of [this type](https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.APIGatewayv2.CfnStage.AccessLogSettingsProperty.html).

As for the first error (in `RouteSettings`), it seems that Cloudformation is a little confused as to those settings. I will attempt to reproduce and if I can identify it, I will pass this along as a bug to the Cloudformation team.

I will attempt the repro this afternoon, in either case that will not be a part of this guidance so I will close this once I have a reference for you

**Comment by Manish082007** [comment]
@NGL321 - Thanks for the reply,

I didn't know about the AccessLogSettingsProperty & RouteSettingsProperty classes.
Actually, I tried to create the same replica classes with the same property names but that didn't work.
I am able to generate Access Log Settings & Route Settings data in CDK synth & deploy it to AWS too.

**You can close this issue.** One thing is there I hardly find any documents related to this on the internet. Also on CloudFormation as well as CDK document, there is no mention of these 2 classes.

Thanks.
