### ISSUE TITLE
(ec2): add X2g instance class

### ISSUE THREAD

**Issue by koltysh** [aws/aws-cdk#16948]
### Description

"X2g" instance are available now for cloudformation but not CDK

### Use Case

Deploying database with "X2g" Instance class for performance optimization

### Proposed Solution

Add Member X2g instance in enum InstanceClass typescript .
Link to AWS CDK Api references : https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.InstanceClass.html

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jumic** [comment]
Instance class X2g for RDS was announced in this [article](https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-rds-x2g-mysql-mariadb-postgresql/).

From my point of view, X2g is a special instance class because it is only supported by RDS. The [list of EC2 instance types](https://aws.amazon.com/ec2/instance-types/) does not contain value X2g at the moment.

Can we just add value X2g to enum InstanceClass which is located in the EC2 module? Or should there be a special solution because X2g is only supported for RDS at the moment?
