### ISSUE TITLE
Amazon.CDK.AWS.ECS: Adding a new target to an existing ECS Fargate service causes resource exists error

### ISSUE THREAD

**Issue by sjbthfc2** [aws/aws-cdk#17004]
### General Issue

Cannot add a an existing ECS Fargate Service as a target to a Network Load Balancer Target Group

### The Question

Hi,

We are trying to add a container and port from an existing FargateService to a NetworkLoadBalancer NetworkTargetGroup. This seems fine and the CDK code builds, but during deployment it fails with:

Requested update requires the creation of a new physical resource; hence creating one.
Resource handler returned message: "Resource of type 'AWS::ECS::Service' with identifier 'xxxx' already exists."

The code uses the service container and tries to use a different port (8080) to the one we create when the service construct is created (80):

```
var dashboardTarget = myFargateService.LoadBalancerTarget(new LoadBalancerTargetOptions
            {
                ContainerName = "myFargateServiceContainer",
                ContainerPort = 8080
            });

var dashboardTargetGroup = new NetworkTargetGroup(this, $"dashboardTargetGroup", new NetworkTargetGroupProps
            {
                Vpc = <VPC we look up>,
                Port = 8080,
                TargetType = TargetType.IP,                
                Targets = new INetworkLoadBalancerTarget[] { dashboardTarget }
            });
```

Why can't an ECS Service resource handle being added as a new target? If CFn has to re-create the service construct, how will that work as the name of it won't change and hence the conflict. Is there a way round this or a correct way to add multiple targets to different ports on containers in an existing ECS Fargate service?

Maany tthanks for your help

### CDK CLI Version

1.126.00

### Node.js Version

14.17.6

### OS

Windows

### Language

.NET

### Language Version

.NET 5

**Comment by peterwoodworth** [comment]
Hey @sjbthfc2,

I'm pretty sure what's going on here. When you defined your `service`, did you specify the `serviceName`? This will assign the [physical name](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_physical_names) of your resource to whatever you set. This is not recommended by the CDK, because 

> any changes to deployed resources that require a resource replacement, such as changes to a resource's properties that are immutable after creation, will fail if a resource has a physical name assigned

This happens because when Cloudformation needs to [replace](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement) a resource, it first creates an identical copy of the resource _then_ deletes the old resource.

To fix this, the CDK recommends 

> If you end up in a state like that, the only solution is to delete the AWS CloudFormation stack, then deploy the AWS CDK app again.

But if you don't want to do that, you can either specify a different physical name or not specify a physical name at all and you should be good to go.

Let me know if my assumption was incorrect, thanks!

**Comment by sjbthfc2** [comment]
Hi @peterwoodworth, removing physical names has solved that issue. Many thanks for your help and guidance.
