### ISSUE TITLE
(cli): Hotswapping support for Lambda Versions and Aliases

### ISSUE THREAD

**Issue by comcalvi** [aws/aws-cdk#17043]
### General Issue

How should Lambda Versions and Aliases be hotswapped?

### The Question

The expected behavior when hotswapping Lambda Functions that make use of Versions or Aliases is not clear. Please :+1: this issue and add comments explaining your desired behavior and use cases if you would like to see hotswapping be able to modify Lambda Versions and Aliases.

Versions:
* What should happen when the `currentVersion` property of a particular Function is being used, and that Function is updated? 
* What should happen when a Version construct is present, and the Function it references is updated? 

Aliases:
* Provided that the Function in the `currentVersion` construct use case above is updated, should any Aliases that reference it be updated? 
* Provided that the  Function in the`Version` construct use case above is updated, should any Aliases that reference it be updated? 

Implementation Challenges:
* Because `currentVersion` deletes a resource and creates a new one with a different ID each deployment, hotswapping that change requires matching a deleted resource to a created resource with different IDs. This would require some detector functions to know the results of other detector functions before they finish executing, which is not ideal in the current framework.

### CDK CLI Version

N/A

### Language

Typescript

**Comment by skinny85** [comment]
> What is hotswapping in this context?

@iph it's a CDK feature: https://www.npmjs.com/package/aws-cdk#user-content-hotswap-deployments-for-faster-development

**Comment by iph** [comment]
Thanks!

So, I personally haven't touched the Version resource in like 3 years, but it's a mine-field. Luckily the actual backing "what we are attempting to do" is actually super simple! 

### Summarized thoughts

I think if `currentVersion` is specified, always try a PublishVersion api call, and wherever the Version resource is referenced, update with the new version arn (or the same one idempotently). You will find this to be as close to the desired experience as cfn is today. Even aliases would work surprisingly well with this implementation.

Read more to find out why :)

### Long-winded Details of Version/Alias

Adding some contextual flavor: Surprisingly, PublishVersion **always succeeds**, if you have permission to publish. "Hold up, what?! There is a crap-ton of wiring in the CDK specifically arounds the Version resource!". That's right! See, Cloudformation treats versions as an immutable resource, and because of that, they expect the resource *to change*, otherwise cloudformation updates fail. But really...behind the scenes, `Version` resource is just doing a publish-version and validating that the number changed. If you are on version:5, and publish-version returns "version:5", cfn is like "nothing has changed, but I'm creating a new resource, hence I must fail" -- and explodes on Version replacement. This is what the CDK mechanisms are attempting to prevent and why it's so hamfisted at the moment.

BUT -- if you are just hotswapping and implementing this out of band...well...if a Version resource exists...just publish a version -- whatever that value is...use it everywhere else the version arn is specifically requested. It's either idempotently the same value on update, or it's new and needs updates everywhere it's referenced anyways

What I mean by "everywhere else" is that anywhere a lambda function arn is used, some integrations are configured to be a bit too restrictive. Take EventBus as an example:

```
        const deployer = new lambda.Function(this, 'DeployerLambda', {
            functionName: `${props.tag}-deployer`,
            code: lambda.Code.fromAsset(path.join(__dirname, '..', 'lambdas/deployer.zip')),
            handler: 'deployer',
            runtime: lambda.Runtime.GO_1_X,
        });

        const deployTarget = new targets.LambdaFunction(deployer, {version: true});

        new eventbridge.Rule(this, 'DailyRule', {
            ruleName: `${props.tag}-daily-trigger`,
            schedule: eventbridge.Schedule.cron({minute: '11', hour: '4'}),
            targets: [deployTarget]
        });

```

I made up the "version: true" bit, as you can't specify the version arn in eventbus targets today, a true tragedy (well you can, but the interface is too verbose for an example). The above is slightly broken, as you can't specify a lambda version arn, nor a lambda alias arn -- just the default arn of the function. That's fine, as the first step to publishing a version is updating the code (just slightly sad there is no way to specify without creating a new manual target).

If it was ever supported to plop out the version arn automagically (maybe a prop) to eventbridge rule targets, you would need to also update all targets to point to the new version. For aliases, you don't have to do this (the beauty of the alias in the first place :D) -- but aliases would point to the version anyways, so that update would still be required.

**Comment by iph** [comment]
> do you mean that if any Version exists in the synthesized template (not just in the diff), we should always publish a new Version when hotswapping?

So, two scenarios:

1. Publish version doesn't do anything (you are on version 5, it returns version 5), update calls on all integrations with this arn are idempotent, so you can just "do them" (or store the value beforehand if you want to short circuit)

2. Publish Version produces a new version. Well, gotta update all places this version is referenced (e.g. alias, or possibly some integration attachment).

> we just published, or should we only modify aliases that reference the currentVersion of the function?

I think this is the desired behavior, yes. You only update the alias if it references the version and the version is being modified (but again, read scenario 1 above). Technically, if it's pointing to a function that just had updated code, all paths lead to the alias being updated anyways, IIRC.

**Comment by iamrohitbanga** [comment]
Just want to drop a note about my repro / workaround for this issue.

I followed [the example](https://docs.aws.amazon.com/cdk/latest/guide/serverless_example.html) for setting up a serverless application using CDK. With this simple API Gateway + Lambda App, hotswap feature works as expected.

I additionally created an alias that was associated with this lambda function:

```js
export class WidgetService extends core.Construct {
    constructor(scope: core.Construct, id: string) {
        super(scope, id);

        const bucket = new s3.Bucket(this, "WidgetStore");

        const handler = new lambda.Function(this, "WidgetHandler", {
            runtime: lambda.Runtime.NODEJS_14_X, // So we can use async in widget.js
            code: lambda.Code.fromAsset("resources"),
            description: "generated at " + new Date().toISOString(),                                           
            handler: "widgets.main",
            environment: {
                BUCKET: bucket.bucketName
            }
        });

        bucket.grantReadWrite(handler); // was: handler.role);

        const api = new apigateway.RestApi(this, "widgets-api", {
            restApiName: "Widget Service",
            description: "This service serves widgets."
        });

        const getWidgetsIntegration = new apigateway.LambdaIntegration(handler, {
            requestTemplates: { "application/json": '{ "statusCode": "200" }' }
        });

        new lambda.Alias(this, "LambdaAlias", {
            aliasName: "widget-alias",
            version: new lambda.Version(this, "LambdaVersion-" + new Date().toISOString(), { lambda: handler })
        });

        api.root.addMethod("GET", getWidgetsIntegration); // GET /
    }
}
```

Now hotswapping does not work. It assumes that the function version resource has changed and does a stack update everytime.

Workaround:
1. Upload assets to S3 directly using S3 API.
2. Call `updateFunctionCode` to update the code for the lambda function.
3. Call `publishVersion` to publish a new version using the latest code.
4. Call `updateAlias` API on lambda alias with the following params:

```
alias name = widget-alias
function_name = ...
function_version = version returned by publishVersion API call above.
RoutingConfig: {
    AdditionalVersionWeights: { }
}

```

This helps in hot swapping the function code without updating the stack. This causes drift as expected but this is acceptable for dev / test stacks.

Please note that the speed gains are only available when provisioned concurrency on the lambda function is disabled. With provisioned concurrency enabled, it still takes some time for the `getAlias` API to reflect that all traffic is being routed to the new version.

It would be very helpful to have this workaround as part of CDK hotswap feature.

**Comment by skinny85** [comment]
Hey @iamrohitbanga, I've submitted a PR (https://github.com/aws/aws-cdk/pull/18145) that covers the example you posted. This is the code that I used to test whether everything works:

```ts
import * as cdk from '@aws-cdk/core';
import * as apigateway from '@aws-cdk/aws-apigateway';
import * as lambda from '@aws-cdk/aws-lambda';

export class LambdaVersionsAliasesStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        const handler = new lambda.Function(this, 'Function', {
            code: lambda.Code.fromAsset(`${__dirname}/lambda-code`),
            runtime: lambda.Runtime.NODEJS_14_X,
            handler: 'index.handler',
        });

        const api = new apigateway.RestApi(this, "widgets-api", {
            restApiName: "Widget Service",
            description: "This service serves widgets."
        });

        const getWidgetsIntegration = new apigateway.LambdaIntegration(handler, {
            requestTemplates: { "application/json": '{ "statusCode": "200" }' },
        });

        new lambda.Alias(this, "LambdaAlias", {
            aliasName: "widget-alias",
            version: new lambda.Version(this, "LambdaVersion-" + new Date().toISOString(), { lambda: handler }),
        });

        api.root.addMethod("GET", getWidgetsIntegration); // GET /
    }
}
```

The only difference between this code, and what you posted, is that I don't have the dynamic description (`description: "generated at " + new Date().toISOString()`) in my `Function` that you had. That's required, as hotswapping will fail if it detects a change to the `description` property (as that's not a hotswappable property, at least right now).
