### ISSUE TITLE
(aws-applicationautoscaling): Typo in PredefinedMetric enum

### ISSUE THREAD

**Issue by ivanmarquescepsa** [aws/aws-cdk#17209]
### What is the problem?

`DynamoDBWriteCapacityUtilization` value in PredefinedMetric enum is defined as `DYANMODB_WRITE_CAPACITY_UTILIZATION` and it should be `DYNAMODB_WRITE_CAPACITY_UTILIZATION`

### Reproduction Steps

Create any `TargetTrackingScalingPolicy` with predefined metric `DynamoDBWriteCapacityUtilization`

### What did you expect to happen?

The enum property should be `DYNAMODB_WRITE_CAPACITY_UTILIZATION`

### What actually happened?

The enum property is `DYANMODB_WRITE_CAPACITY_UTILIZATION`

### CDK CLI Version

2.0.0-rc.26

### Framework Version

2.0.0-rc26

### Node.js Version

v16.13.0

### OS

MacOS 11.6

### Language

Python

### Language Version

3.8.9

**Comment by NGL321** [comment]
Hey @keepler-ivanmarques,

I am not sure I am understanding correctly the issue here. The value seems to match the guidance of the [related article](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html). Could you specify what you think is wrong? (You listed the expected value as the same as the given value)

**Comment by keepler-ivanmarques** [comment]
Hi.

Sorry, it's not the same value

DYANMODB_WRITE_CAPACITY_UTILIZATION is not the same as DYNAMODB_WRITE_CAPACITY_UTILIZATION
