### ISSUE TITLE
(core): Disallow override of CDK metadata

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#17319]
### Description

Metadata that CDK generates should not be overridable by a CDK developer.

```typescript
const secret = new Secret(this, 'Secret');
(secret.node.defaultChild as CfnSecret).addOverride('Metadata.aws:cdk:module', 'MyModule');
```

### Use Case

Use external tools to determine if a NestedStack comes from a CDK module.

An example of this is the NestedStack included as part of the `@aws-cdk/aws-eks` module to use `kubectl`.

### Proposed Solution

Implement a validation to disallow override of `aws:cdk:*` metadata.

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
Given that we are executing in JavaScript, where any user code can change anything at any time, any solid guarantees are not achievable in general.

If you are protecting against accidental mistakes, you can institute linter rules to prevent your developers from making mistakes.

If you are trying to protect against abuse... well that's just not possible. 

I'd rather make it clear up front that this is not achievable, rather than try to implement this feature, failing to be watertight, and then dealing with complaints and support requests about how the security can be "exploited".
