### ISSUE TITLE
(aws-eks): Reduce template size when using addCdk8sChart on Cluster with many resources

### ISSUE THREAD

**Issue by chris-bannister-privitar** [aws/aws-cdk#17362]
### What is the problem?

Adding a cdk8s chart to an EKS cluster which has a lot of resources in it causes the resultant template to be over the max template size as the manifest is encoded in the template.

### Reproduction Steps

```java
Cluster cluster = ...
        cluster.addCdk8sChart("kube-promethetheus-stack", new Chart(cdk8sApp, "chart") {
            {
                Helm.Builder.create(this, "kube-prometheus-stack")
                        .chart("kube-prometheus-stack")
                        .releaseName("kube-prometheus-stack")
                        .helmFlags(Collections.singletonList("--repo=https://prometheus-community.github.io/helm-charts"))
                        .build();
            }
        });
```

### What did you expect to happen?

Generate suitably valid CloudFormation template

### What actually happened?

CloudFormation failure `Template may not exceed 1000000 bytes in size.`

### CDK CLI Version

1.130.0

### Node.js Version

v14.18.0

### OS

MacOS

### Language

Java

### Language Version

8

### Other information

When adding a cdk8s chart to the cluster it should be uploaded via s3-assets so that its size does not matter.

**Comment by zhelyan** [comment]
Related - `addCdk8sChart` puts all chart resources in the cluster's CF stack. This isn't great because of the template size issue but also - because it is often better to physically separate resources and put them in their own stacks.

It would be great to have the option to select which scope the chart resources are added to, like with `KubernetesManifest` which `addCdk8sChart` [uses internally
](https://github.com/aws/aws-cdk/blob/721bd4b24de8e410fd9181eff7e5431c13bad208/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L916)
