### ISSUE TITLE
(lambda): Latest cdk -> BucketNotificationsHandler created with nodejs10

### ISSUE THREAD

**Issue by tarnewestcott** [aws/aws-cdk#17397]
### General Issue

"The runtime parameter of nodejs10.x is no longer supported for creating...

### The Question

I have removed + re-installed CDK, cleared node_modules, removed package-lock.json

Produced with a fresh download of:
https://github.com/aws-samples/amazon-textract-serverless-large-scale-document-processing.git

cdk bootstrap
cdk deploy

### CDK CLI Version

1.131.0 (build 7560c79)

### Node.js Version

v14.16.1

### OS

MacOS 11.0.1 (20B50)

### Language

Typescript

**Comment by peterwoodworth** [comment]
I can't figure out where this function is coming from, i'll have to mess around with this

**Comment by jinsoolim** [comment]
Had the same issue and a colleague of mine helped fix this issue by upgrading the versions in `requirements.txt`.

Commit 55549ef9bd7f036203d9150496570b8b568d3066 is the last commit with the issue and 20a2820ee4d022663fcd0928fbc0f61153ae953f is the first commit with the issue fixed. Those commits correspond to published versions v1.90.0 and v1.94.0 respectively. The underlying issue is the lambda deployed by the code in the **file** aws-cdk/packages/@aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts

If you check on https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html you can no longer `create` functions that use the runtime (we are currently in Phase 1). In the above mentioned commits/versions the **file** is still using `"nodejs": 10.x` and in v1.94.0 it is updated to `"nodejs": 14.x`. Most likely the versions in `requirements.txt` that OP is using is one that is before the "fix". When running `cdk bootstrap` or `cdk deploy`, `cdk.out` is created by looking at the `requirements.txt` file. So, even if you're `cdk --version` is `1.131.0` it will not create the "updated" version of `cdk.out`.

**Comment by peterwoodworth** [comment]
Thanks for the reply @jinsoolim, you're correct here. I hadn't checked the package.json, but the project linked in the OP is version `1.27.0`. On my first look I had thought this said `1.127.0` 😅 

Updating the versions in package.json does the trick here. @tarnewestcott I think this would be worth correcting in the original repo

**Comment by tarnewestcott** [comment]
Thank you both @jinsoolim @peterwoodworth - after reading the above from @jinsoolim , specifically looking through `aws-cdk/packages/@aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.js` I realised that there must have been a library clash somewhere. Aside from my new global cdk install, I didn't realise there was a local cdk package within the project too (which was obviously old), and it was picking up the issues from there.

I did wipe and update the packages, but I hit other blockers with my AWS account - was waiting to report back once I had a successful deployment, but I think it's fair to say this is not a cdk issue.

Thanks again.
