### ISSUE TITLE
(stepfunctions-tasks): Cannot use "$" Dynamic Paths in BatchSubmitJob "containerOverrides" when deploying with CDK

### ISSUE THREAD

**Issue by warezWally** [aws/aws-cdk#17427]
### General Issue

Cannot use "$" Dynamic Paths in BatchSubmitJob "containerOverrides" when deploying with CDK

### The Question

Hi,

When trying to build a StepFunction "BatchSubmitJob" Construct we would like to utilise the "containerOverrides" to change the Command and Environment Parameters that are recieved from a preceding Lambda function. These variables are stored at the input path "$.stepResult.Payload.options" & "$.stepResult.Payload.envs" on the incoming step.

If we manually edit the StepFunction definition after deployment to:

```ts
"ContainerOverrides": {
          "Command.$":"$.stepResult.Payload.options",
          "Environment.$": "$.stepResult.Payload.envs"
        }
```

This works fine, however there is no way to do this using the CDK, if I try and do something like:

```ts
"containerOverrides": { "command": "$.stepResult.Payload.options" }
```

we get errors like:
```sh
Resource handler returned message: "Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of VALUE_STRING token at /States/submit-Batch-unified-packager/Parameters
```

Would appreciate any ideas or workarounds to facilitate this.

### CDK CLI Version

1.130.0

### Language

Typescript

**Comment by kaizen3031593** [comment]
Hi @warezWally! Have you tried using [`stepfunctions.JsonPath`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.JsonPath.html)?

I think what you want is `{ "command": sfn.JsonPath.stringAt($.stepResult.Payload.options) }`

I think the documentation around this could be improved but there are a bunch of similar examples [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html) (just search for 'jsonpath'). Let me know if that fixes things!

**Comment by rpmcginty** [comment]
Similar to the issues stemming from using reference paths fir container overrides, you cannot use a reference path for the  job queue field ("`JobQueue`") with the `BatchSubmitJob` task (namely because the job queue arn value is treated as a literal and a role policy is attached to the state machine when building the Cfn stack).     

This should be addressed as it's a major limitation for using `BatchSubmitJob` in a meaningful way in cdk. 

As a workaround, you can use the [sfn.CustomState](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-stepfunctions.CustomState.html) to define a `BatchSubmitJob` task with dynamic inputs (for container overrides, job queues, job definitions etc.) 

Below is a python example (I was too lazy to clean up snippet, it is just my actual code) 

```python
        batch_submit_task = sfn.CustomState(
            self,
            f"Batch Submit Job: {self.name}",
            state_json={
                "Type": "Task",
                "Resource": "arn:aws:states:::batch:submitJob.sync",
                # PrepareSubmitJobArgsResponse
                "Parameters": {
                    "JobName.$": sfn.JsonPath.string_at(f"{prep_submit_job_args_task_name.result_path}.job_name"),
                    "JobDefinition.$": sfn.JsonPath.string_at(f"{prep_submit_job_args_task_name.result_path}.job_definition_arn"),
                    "JobQueue.$": sfn.JsonPath.string_at(f"{prep_submit_job_args_task_name.result_path}.job_queue_arn"),
                    "Parameters.$": sfn.JsonPath.object_at(f"{prep_submit_job_args_task_name.result_path}.parameters"),
                    "ContainerOverrides.$": sfn.JsonPath.object_at(f"{prep_submit_job_args_task_name.result_path}.container_overrides"),
                },
                "ResultPath": self.task_name.result_path
            }    
        )

```

Very important that you add the appropriate batch action policies to your state machine so that you can actually submit a job.
