### ISSUE TITLE
(aws-sagemaker): Adding tags to SageMaker domain requires replacement

### ISSUE THREAD

**Issue by maxispeicher** [aws/aws-cdk#17448]
### General Issue

(aws-sagemaker): Adding tags to SageMaker domain requires replacement

### The Question

Hey,

when using a `CfnDomain` construct from `@aws-cdk/aws-sagemaker` and some tags are added to the domain according to the `cdk diff` output, this would require a resource replacement.

![image](https://user-images.githubusercontent.com/39695405/141091090-c51e3aeb-5220-4375-9b7f-32bbc029242b.png)

On the one hand side this is in line with the [cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-domain.html#cfn-sagemaker-domain-tags), but on the other hand side, this does not really make sense in my eyes, especially when compared to other services and that a change of tags is possible through the AWS console without any interruption.

Do you know if
1. A change in the tags really would result in a replacement (I didn't want to risk it)?
2. This is the intended behavior?

### CDK CLI Version

1.132.0 (build 5c75891)

### Language

Python

### Language Version

3.8.12

**Comment by peterwoodworth** [comment]
Hey @maxispeicher, sorry for the long response time here. 

The CDK uses CloudFormation under the hood - so this really would cause a replacement! I'm not sure _why_ changing tags causes a replacement, but I can guarantee you it's intentional. 

Since the CDK uses CFN under the hood, there isn't a way to work around this. If you need to change the tags of this resource, you will need to replace the resource.

Let me know if you have any additional questions!
