### ISSUE TITLE
(cli): hotswap deployments don't work across accounts

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [aws/aws-cdk#17561]
### What is the problem?

I have a pipeline running with credentials from account A deploying into account B. Account B was bootstrapped to allow deploys from account A. With normal deployments they work but when enabling `--hotswap` it fails with:

```
Need to perform AWS calls for account B, but the current credentials are for A
```

This is because normal deployments assume the `cdk-hnb659fds-deploy-role-....` which then starts the cloudformation stack update, which in turn uses the `cdk-hnb659fds-cfn-exec-role-....`. Apparently `--hotswap` does not use these

### Reproduction Steps

Deploy a stack cross account and then switch to `--hotswap` deployments

### What did you expect to happen?

I expected that (after updating the bootstrap stack) the `cdk-hnb659fds-deploy-role-....` would have permissions to perform  

```
"lambda:UpdateFunctionCode",
"states:UpdateStateMachine",
"ecs:RegisterTaskDefinition",
"ecs:UpdateService",
"ecs:DescribeServices"
```

which are needed for hotswap deployments. Or that a new `cdk-hnb659fds-hotswap-deploy-role-....` with the needed permissions would be created.

### What actually happened?

The `cdk-hnb659fds-deploy-role-....` was not assumed and did not have the given permissions. A new role was also not added.

### CDK CLI Version

1.132.0

### Framework Version

1.132.0

### Node.js Version

16.9.0

### OS

macOS

### Language

Typescript

### Language Version

4.4.3

**Comment by skinny85** [comment]
Hey @matthias-pichler-warrify,

thanks for opening the issue. Unfortunately, the Roles in the bootstrap Stack (those named `cdk-hnb659fds-hotswap-deploy-role-...`) cannot have the permissions needed for hotswapping, because they would have to have them for `"*"`, as there's no way to know in advance what the names of the resources would be. Given that, and the fact that you would have to change the permissions in the bootstrap Stack every time we added a new hotswapped resource (so, you would have to re-run `cdk bootstrap` again).

Instead, what you want to do is have credentials for account B in your console, and then invoke `cdk deploy --hotswap`.

Thanks,
Adam
