### ISSUE TITLE
(ec2): Security Group addition for cross-stack communication best practices

### ISSUE THREAD

**Issue by danw-mpl** [aws/aws-cdk#17562]
### General Issue

Looking for best practices regarding adding rules to a Security Group cross-stack

### The Question

Hello,

Given two stacks Application and Database, does anyone have cool ideas on how to grant the Application access to the Database?

Bit more detail:
- Database has its own Security Group
- Application has its own Security Group
- Would like to allow 3306/tcp from Application to Database.

I'm purposely trying to avoid cross-stack references via Import/ExportValue to avoid potential issues with updating/removing stacks which can operate independently.

### CDK CLI Version

1.132.0 (build 5c75891)

### Node.js Version

14

### OS

Ubuntu 20.04 (WSL2)

### Language

Typescript

**Comment by NGL321** [comment]
Hey @danw-mpl,
Based on my best understanding of what you are trying to do, you should probably import either the security group or database into the stack that will deploy second. Something like below:

``` typescript
export class AppStack {
...
const sg = new ec2.Securitygroup(this, '', {});
new CfnOutput(this, 'SecGroupId', { value: sg.securityGroupId } 
...
}

export class DbStack {
...
const appSg = ec2.SecurityGroup.fromLookupById(Fn.ImportValue('SecGroupId'));
db.connections.allowFrom(appSg, Port.tcp(4321), 'Inbound')
appSg.connections.allowTo(db, Port.tcp(4321), 'Outbound')
...
}
```

The only major problem with this (as you noted) is that it creates a deployment dependency that the latter stack must be deployed after each major deployment of the former. Most times, stack update should maintain the allowances for sgs between deployments, so in-practice this SHOULD only create a stack dependency on the first deployment.

If you are concerned about the interdependency, there are really two alternatives. First is to have a third stack that imports both SGs and adds the connection allowances and is deployed with deployments of either stack. The second option is to conditionally include the above connection allowances in both stacks (ie. `if(importedAppSg != nothing) { SEE_ABOVE_CONNECTIONS }`).

I realize this is not standard guidance, but we dont offer standard guidance on this specific implementation since all approaches have merits.

Let me know if this answers your question or you have any follow-up.

**Comment by danw-mpl** [comment]
No worries, we ended up writing a small class to manage SSM parameters which allows us to 'type' parameters within our CDK project and keep the stacks physically decoupled.  Example:

#### parameter.ts
```typescript
import * as cdk from '@aws-cdk/core';
import * as ssm from '@aws-cdk/aws-ssm';

export enum ParameterType {
    DATABASE_HOST = "database-host",
    DATABASE_SECURITY_GROUP_ID = "database-security-group-id"
}

export class SuperParameter {

    private readonly parameterPrefix: string

    constructor(app: string, env: string) {
        this.parameterPrefix = `/${app}/${env}`
    }

    public set(scope: cdk.Construct, type: ParameterType, value: string) {
        return new ssm.StringParameter(scope, `${type}-Parameter`, {
            parameterName: `${this.parameterPrefix}/${type}`,
            stringValue: value
        });
    }

    public get(scope: cdk.Construct, type: ParameterType) {
        return ssm.StringParameter.valueForStringParameter(scope, `${this.parameterPrefix}/${type}`)
    }

}
```

#### database-stack.ts
```typescript
import { SuperParameter, ParameterType } from './parameter';
...
const sp = new SuperParameter(props.applicationName, props.environmentName);
sp.set(this, ParameterType.DATABASE_HOST, dbFromSnap.clusterEndpoint.hostname);
```

#### app-stack.ts
```typescript
...
sp.get(this, ParameterType.DATABASE_HOST);
...
```
