### ISSUE TITLE
(@aws-cdk/core): When overwriting StackProps.env - region the --verbose is outputting still the wrong Region

### ISSUE THREAD

**Issue by daknhh** [aws/aws-cdk#17659]
### What is the problem?

When overwriting StackProps.env - region the --verbose is outputting still the wrong Region.

### Reproduction Steps

When overwriting the  region in 
```
new CDKSTack(app, "STACKNAME", {
      config,
      env: {
        region: process.env.DEFAULT_REGION,
        account: process.env.DEFAULT_ACCOUNT,
      },
    });
```

and invoking a `cdk deploy --verbose --profile PROFILENAME`

### What did you expect to happen?

`cdk deploy --verbose --profile PROFILENAME` verbose should output the process.env.DEFAULT_REGION 

### What actually happened?

 the verbose is still outputting the PROFILENAMEs Region even if it uses the process.env.DEFAULT_REGION

### CDK CLI Version

1.124.0

### Node.js Version

v14.17.6

### OS

macOS 12.0.1 (21A559)

### Language

Typescript

**Comment by peterwoodworth** [comment]
What exactly is the message that's output here?

**Comment by daknhh** [comment]
the cdk deploy verbose always show the value for CDK_DEFAULT_REGION from the AWS_DEFAULT_REGION from the used AWS Profile even if you overwriting the  CDK_DEFAULT_REGION in you /bin/stack.ts. The deployment is however correct into the CDK_DEFAULT_REGION you set in your /bin/stack.ts. This make it hard to troubleshoot. 

eg verbose output:
```

env: {
  CDK_DEFAULT_REGION: 'eu-central-1',....
```
eg. lib/stack.ts

```
    new Stack(app, "STACK", {
      config,
      env: {
        region: 'us-east-1',
        account: XXXXXXXX,
      },
    });
```

Stack will be deployed the us-east-1 but verbose is showing the AWS_DEFAULT_REGION from AWS Profile

**Comment by rix0rrr** [comment]
I still don't understand what the problem is.

`process.env.CDK_DEFAULT_REGION` is derived  by the CDK CLI from your AWS CLI settings (a combination of `~/.aws/config`, `--profile` and `$AWS_DEFAULT_REGION`).

If you put:

```ts
 env: {
        region: process.env.CDK_DEFAULT_REGION,
        account: process.env.CDK_DEFAULT_ACCOUNT,
      },
```

In your env, you explicitly state that you want your stack to be deployed into whatever the "current" environment is.

If you specify explicit region and account, it goes wherever you declare.

If you don't specify anything (or something that evaluates to `undefined`) you are declaring you don't know yet where the template needs to go, so tells CDK to generate a template that can be deployed anywhere.

I notice in your code above you wrote:

```ts
 env: {
        region: process.env.DEFAULT_REGION,
        account: process.env.DEFAULT_ACCOUNT,
      },
```

so `env.DEFAULT_REGION` instead of `env.CDK_DEFAULT_REGION`. That might be the problem, and makes you fall into the 3rd case (an unset environment variable will evaluate to `undefined`).
