### ISSUE TITLE
aws_lambda: adding dependency to L2 Function node adds dependency to implicit role

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#17855]
### What is the problem?

Adding a dependency to a function's node will also add a dependency to its implicitly created role. This will cause a cyclic dependency if the dependent resource also depends on the role.

Furthermore, if the function has a log retention set, then the CR lambda and role created for that will also have this dependency, which is completely unexpected.

### Reproduction Steps

This is a simplified example to demonstrate the circular dependency issue.

```python
    func = aws_lambda.Function(
        stack,
        'my-func',
        runtime=aws_lambda.Runtime.NODEJS_12_X,
        handler="index.handler",
        code=aws_lambda.Code.from_inline("exports.handler = handler.toString()"),
    )

    param = aws_ssm.StringParameter(
        stack,
        'my-param',
        string_value=func.role.role_id,
    )

    func.node.add_dependency(param)
```

### What did you expect to happen?

The dependency should only be added to the function.

### What actually happened?

As per the CloudFormation template, the dependency was also added to the role, resulting in a cyclic dependency that caused the deployment to fail.

### CDK CLI Version

1.130.0 (build 9c094ae)

### Node.js Version

16.13.0

### OS

Alpine 3.14

### Language

Python

### Language Version

3.9.7

### Other information

As a workaround, we can directly add the dependency to the L1 construct via `func.node.default_child.add_depends_on(param.node.default_child)` but this is very cumbersome and inconsistent.

**Comment by kaizen3031593** [comment]
HI @rittneje! While this seems weird, it is the expected behavior. When we add a dependency, it is like saying that everything in subtreeA depends on everything in subtreeB. In this case, that makes `param` depend on both `func` and the IAM role. Since that is not what you want, you are correct that the workaround is to add the dependency directly to the L1 construct in the way you've described.

By the way, this is because Cloudformation manages the dependencies and has no knowledge of CDK constructs. So our dependencies are done via cfn trees.
