### ISSUE TITLE
VPC Subnet: Error when trying to define VPC with exact Subnet CIDRs

### ISSUE THREAD

**Issue by omriman12** [aws/aws-cdk#17883]
### What is the problem?

The SubnetConfiguration construct only allows to define CIDR mask, but i want to define the exact CIDR.
For that I have used the PublicSubnet construct. It works, but the issue is when I trying to call SubnetSelection construct I receive an error: "There are no 'Private' subnet groups in this VPC. Available types:"

### Reproduction Steps

```py
self.vpc = Vpc(
      self,
      id='Vpc',
      max_azs=1,
      cidr=''10.110.0.0/23'',
      enable_dns_support=True,
      enable_dns_hostnames=True,
      subnet_configuration=[]
  )

i_gateway = CfnInternetGateway(self, id='VpcInternetGateway')
CfnVPCGatewayAttachment(self, id='VpcGatewayAttachment', vpc_id=self.audit_vpc.vpc_id, internet_gateway_id=i_gateway.ref)

public_subnet_1: ISubnet = PublicSubnet(self, id='PublicSubnet1', availability_zone='us-east-1a', cidr_block=''10.110.0.0/25'', vpc_id=self.vpc.vpc_id)

route = CfnRoute(
    self,
    id='PublicSubnet1InternetGatewayRoute',
    route_table_id=public_subnet_1.route_table.route_table_id,
    destination_cidr_block='0.0.0.0/0',
    gateway_id=i_gateway.ref,
)

private_subnet_1: ISubnet = PrivateSubnet(self, id='DataMonitoringPrivateSubnet1',
                                                          availability_zone='us-east-1a', 
                                                          cidr_block='10.110.1.0/25'', vpc_id=self.vpc.vpc_id)

self.audit_vpc.add_interface_endpoint('SqsVpcEndpoint', service=InterfaceVpcEndpointAwsService.SQS,
                                       subnets=SubnetSelection(one_per_az=True), lookup_supported_azs=True)
```

### What did you expect to happen?

vpc deploy with public subnet

### What actually happened?

receive an error: "There are no 'Private' subnet groups in this VPC. Available types:"

### CDK CLI Version

1.133.0 (build 2dea31a)

### Node.js Version

v12.16.0

### OS

MAC

### Language

Python

### Language Version

python 3.8

**Comment by NGL321** [comment]
Hey @omriman12,

It seems that there may be a little confusion here. Your code looks good with the exception of a single missing property. You can see [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.SubnetSelection.html#subnettype) in the docs, that while the `subnetType` prop of `SubnetSelection` is optional, it defaults to private subnets. 
In your given code you only create a public subnet, so it wouldnt appear in said selection.

 Please let me know if I misunderstand or you arent able to resolve the issue.

**Comment by omriman12** [comment]
@NGL321 i forgot to add the entire code, i indeed defined a private subnet, getting the error

**Comment by peterwoodworth** [comment]
When you create a `PrivateSubnet` or `PublicSubnet`, the Vpc object you have created will not recognize that those subnets belong to it. Since you've set `SubnetConfiguration` to [], your Vpc believes that there are 0 subnets in your vpc.

Looking at our Vpc docs on [advanced subnet configuration](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#advanced-subnet-configuration), you can use the `SubnetConfiguration` parameter to specify which subnets the Vpc will create (instead of automatically creating them). The problem is - this parameter doesn't allow you to *choose* the exact Cidr - and even if it did, the highest mask allowed is 28.

So, I think we have to do a bit of a workaround here. I've found something which works: 
Like you've done already, create a new Vpc setting `SubnetConfiguration` to []. Then, create any necessary private or public subnets. with `PrivateSubnet` or `PublicSubnet` constructs.
In another stack - you'll want to import the Vpc you've created. Using this imported Vpc - call `add_interface_endpoint` just like you have above. The CDK will then fetch data from your AWS account and store it in a file called `cdk.context.json`. This file will contain information about the subnets you've created

Let me know if that workaround doesn't work for you @omriman12
