### ISSUE TITLE
(device-farm): Support for device farm constructs

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-cdk#17893]
### Description

The [AWS::DeviceFarm Cloudformation resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_DeviceFarm.html) appear not to be exposed in the CDK at all.

This is a request for L1 constructs for those resources.

### Use Case

To manage Device Farm resources via the CDK.

### Proposed Solution

L1 Device Farm constructs.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by workeitel** [comment]
It looks like the problem is that the AWS CloudFormation resource specification is regional https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html but CDK only imports from us-east-1: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cfnspec/build-tools/update.sh#L60

But AWS DeviceFarm service is only available in us-west-2 and therefore only part of the us-west-2 resource specification file.

**Comment by workeitel** [comment]
By comparing the different regional files it turns out only Device Farm resources are affected:

```
"AWS::DeviceFarm::DevicePool"
"AWS::DeviceFarm::InstanceProfile"
"AWS::DeviceFarm::NetworkProfile"
"AWS::DeviceFarm::Project"
"AWS::DeviceFarm::TestGridProject"
"AWS::DeviceFarm::VPCEConfiguration"
```

All other resources in any other region are also part of the us-east-1 resource specification.

**Comment by SamStephens** [comment]
Oh that's interesting. I guess this reflects an implicit assumption that products launch in us-east-1, and as such it's a framework-wide issue with the CDK. I've lodged https://github.com/aws/aws-cdk/issues/22565 to address this.
