### ISSUE TITLE
(ecs-service-extensions): Make compatible with CDK v2 `aws-cdk-lib`

### ISSUE THREAD

**Issue by bweigel** [aws/aws-cdk#17891]
### Description

@aws-cdk-containers/ecs-service-extensions should be compatible with CDK v2, now that it is GA.

### Use Case

Internally we have build a set of constructs for ECS/Fargate container workloads that rely heavily on @aws-cdk-containers/ecs-service-extensions. I tried upgrading our internal constructs to CDK v2, but noticed that @aws-cdk-containers/ecs-service-extensions depends on CDK v1. 

### Proposed Solution

Make @aws-cdk-containers/ecs-service-extensions compatible with CDK v2. However, currently I have no idea how big of an undertaking this would be ...

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by njlynch** [comment]
Thanks for raising this. We are discussing internally some of the next steps in terms of the right way to handle this module. We absolutely want to be release a V2-compatible version of this library, but have a few minor kinks to work out first. :)

**Comment by flavioleggio** [comment]
We are migrating a huge cdk project (250+ files) from v1.125.0 to v2.7.0 and a couple of production applications use common libraries we upgraded to v2 and `ecs-service-extensions`. We are very interested in this issues as it is blocking our migration to v2.

**Comment by madeline-k** [comment]
https://github.com/aws/aws-cdk/issues/13717

**Comment by kaizen3031593** [comment]
The CDK team is picking this up with the goal of releasing an `ecs-service-extensions` `2.0` that is JSII-compatible and using CDK v2. The current status of this project:

- The v2 version will live in `cdklabs` [here](https://github.com/cdklabs/cdk-ecs-service-extensions)
- Initially, the v2 version will be `experimental`, not `stable`. There are no major API changes from v1, but we're calling it `experimental` until we decide that the project is good to go.
- It is currently published (`v0.0.0`, just a preview really) under the name `cdk-ecs-service-extensions` to all JSII target languages (except Python right now). For example, here is the [npm](https://www.npmjs.com/package/cdk-ecs-service-extensions) package.
- In the future, the goal is to publish this under the same name as v1, `@aws-cdk-containers/ecs-service-extensions`, and make the major version `2.0.0-alpha.X` (though I'm not sure how feasible that is yet). 

Hopefully I'll be back sometime next week with a final update on this project.

**Comment by kaizen3031593** [comment]
Excited to announce that we have a v2 of `@aws-cdk-containers/ecs-service-extensions` that is CDK v2 compatible and has multi-language support!

  - the new version lives in cdklabs [here](https://github.com/cdklabs/cdk-ecs-service-extensions) and this is where we’ll continue to support it.
  - because v2 is jsii compatible, it can be found on construct hub [here](https://constructs.dev/packages/@aws-cdk-containers/ecs-service-extensions/v/2.0.0-alpha.7?lang=typescript)
  - because of legacy reasons, the js/ts module is still called `@aws-cdk-containers/ecs-service-extensions` while the other languages will have a name similar to `cdk_ecs_service_extensions`. 
  - we have a quick and painless migration [guide](https://github.com/cdklabs/cdk-ecs-service-extensions/blob/main/MIGRATING.md) from v1 to v2 because there are only minimal API changes (if you were using the v1 in TypeScript before).
  - in the short term, we’ve marked the construct as `experimental` but plan to quickly stabilize it once we know people have downloaded it and can use it successfully.
