### ISSUE TITLE
Add CORS to Lambda and LambdaRestApi

### ISSUE THREAD

**Issue by sandeepc24** [aws/aws-cdk#17924]
### General Issue

Add CORS to Lambda and LambdaRestApi

### The Question

I have not been able to fix CORS issue with Lambda and LambdaRestApi using dotnet F#. 

Here is my code
<code>
    let apiLambda = 

        Function(this, "apiLambda", FunctionProps(

            Runtime = Runtime.DOTNET_CORE_3_1,

            Code = Code.FromAsset("./src/publish/app"),

            Handler = "Api::Setup+LambdaEntryPoint::FunctionHandlerAsync"

        ))

    let restApi = 
        let corsOptions =
                CorsOptions(
                    AllowOrigins = Cors.ALL_ORIGINS,
                    AllowMethods = Cors.ALL_METHODS,
                    AllowHeaders = Cors.DEFAULT_HEADERS
                )
        let restApi = new LambdaRestApi(this, "apiEndpoint", new LambdaRestApiProps(
            Handler = apiLambda,
            DefaultCorsPreflightOptions = corsOptions
        ))
        lambdaRestApi
</code>

### CDK CLI Version

1.134.0 (build dd5e12d)

### Language

.NET

**Comment by peterwoodworth** [comment]
Can you describe what exactly the "CORS issue" you're running into is @sandeepc24?

**Comment by sandeepc24** [comment]
I have hosted website on S3 and have a Lambda hosting REST endpoints. When I invoke Lambda from Postman I get valid response (HttpStatus 200), but when I call the same endpoint from the app I get `CORS error` as shown in the screenshot.
![image](https://user-images.githubusercontent.com/4897654/145492790-be022cc8-1b37-4346-8672-c1f3f323748b.png)

**Comment by sandeepc24** [comment]
If you can give me a working example even in C# I'll be happy to convert it to F#.

**Comment by peterwoodworth** [comment]
I'm still not exactly sure what's going on - or how I can help. I see that you're using the CDK to generate this infrastructure - are you deploying this successfully? In the CloudFormation template output by your CDK project, does it include CORS configuration for the rest api?

**Comment by sandeepc24** [comment]
The infrastructure is deployed successfully but the CORS is not setup. If you try and create a stack with website served from S3 which calls API hosted by lambda you will see what issues I run into.

**Comment by peterwoodworth** [comment]
Can you verify that your synthesized template (`cdk synth`) includes CORS configuration for the rest api?

**Comment by peterwoodworth** [comment]
I've found [this thread](https://coderedirect.com/questions/229763/xmlhttprequest-error-in-flutter-web-enabling-cors-aws-api-gateway) which includes a solution where you need to add headers on your lambda function. They also note that the allowCredentials option is "Required for cookies, authorization headers with HTTPS"

If your synthesized template includes CORS configuration and you can create this infrastructure without the CDK, then let me know. If not, then you would probably receive more help from boards specifically for services you're using (APIGW, Lambda) since this likely wouldn't be a CDK specific problem
