### ISSUE TITLE
(aws-lambda-event-sources): kafka event source unsupported properties

### ISSUE THREAD

**Issue by BrianHaak** [aws/aws-cdk#17934]
### General Issue

Kafka event source properties includes unsupported properties

### The Question

The SelfManagedKafkaEventSourceProps interface includes properties such as: bisectBatchOnError, retryAttempts, maxBatchingWindow, onFailure, maxRecordAge, and parallelizationFactor however, per API docs ([ref](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-event-source-mapping.html)), these properties are only supported by Kinesis and Dynamo Stream event sources.
This causes confusion during deployment as it appears these features are available, but the deploy fails.

### CDK CLI Version

1.134.0 (build dd5e12d)

### Framework Version

1.134.0

### Node.js Version

v14.18.2

### OS

Debian

### Language

Typescript

### Other information

Attempting to deploy returns an error:
`9:25:56 PM | CREATE_FAILED        | AWS::Lambda::EventSourceMapping | test...B0194DF1
Resource handler returned message: "Invalid request provided: Unsupported 'maximumRetryAttempts' parameter for given event source mapping type. (Service: Lambda, Status Code: 400, Request ID: 2f6..., Ext
ended Request ID: null)" (RequestToken: 324..., HandlerErrorCode: InvalidRequest)`

**Comment by peterwoodworth** [comment]
Thanks for the report @BrianHaak,

This is because under the hood, KafkaEventSourceProps extends StreamEventSourceProps https://github.com/aws/aws-cdk/blob/dd5e12d43231d991971de3121928377569b2dd63/packages/%40aws-cdk/aws-lambda-event-sources/lib/kafka.ts#L16

None of the other non-dynamodb/kineses EventSourceProps extend StreamEventSourceProps, this is isolated to kafka
