### ISSUE TITLE
(cdk bootstrap): causes my terminal to crash

### ISSUE THREAD

**Issue by timjrobinson** [aws/aws-cdk#18005]
### What is the problem?

When I run the command `cdk bootstrap aws://myaccountid/myregion` my terminal closes with no further information. Sending output to a log file gives no output and still crashes. 

When I run with ` strace cdk bootstrap aws://myaccountid/myregion &>./log.txt` to debug it the command works correctly and outputs the strace logs. 

I'm running Ubuntu 20.04 with zsh shell. 

### Reproduction Steps

- Open new terminal
- Run `cdk bootstrap aws://myaccountid/myregion` (with accountid and region)

### What did you expect to happen?

I expect my account to be bootstrapped for cdk correctly

### What actually happened?

The terminal closes with no output

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

v14.17.3

### OS

 Ubuntu 20.04.3 LTS - Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Language

Typescript

### Language Version

4.3.5

### Other information

I can upload the stack trace but I'm not sure if it contains any private/confidential information like my account details. Is it ok to upload it?

**Comment by peterwoodworth** [comment]
Hey @timjrobinson, I'm sorry you're running into this.

I haven't seen anyone report this before, so I'm not too sure that the issue is due to cdk. 

The trace you're able to output is successfully working if I understood your post correctly; so I'm not sure how useful it would be to have if it's working normally (and not crashing your terminal). If you aren't worried about exposing your account details then there would be nothing wrong with posting it

@rix0rrr What do you think about this?

**Comment by trompx** [comment]
Also having this problem running aws-cdk 2.8.0.
It crashes my main terminal (st terminal) on Linux Mint 20.2.
However, when running the command inside the vscode terminal, it executes without errors.

**Comment by timjrobinson** [comment]
I think I'm using st terminal too. As I'm using Regolith as my main GUI.

**Comment by timjrobinson** [comment]
@trompx I found something that may fix the issue: https://wiki.archlinux.org/title/St#Crashes_if_page_contains_emoji_characters

It seems st terminal can crash if emoji's are shown that it doesn't support. I installed the package `fonts-symbola` and launched a new `st` terminal and it works again.
