### ISSUE TITLE
(aws-elasticsearch): imported Domain's `domainEndpoint` is the full URL, not the Endpoint

### ISSUE THREAD

**Issue by joel-aws** [aws/aws-cdk#18017]
### What is the problem?

For ES Domains imported using `fromDomainEndpoint`, the `domainEndpoint` attribute is [meant to return](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#aws-resource-elasticsearch-domain-return-values) something like: `search-mystack-elasti-1ab2cdefghij-ab1c2deckoyb3hofw7wpqa3cm.us-west-1.es.amazonaws.com`. Instead, it returned that, but prepended by `https://`.

I think this happens because `fromDomainEndpoint` requires a valid URL, not a raw endpoint.

### Reproduction Steps

```python
from monocdk import aws_elasticsearch as es, Construct

class ElasticSearch(Construct):
    def __init__(self, scope: Construct):
        super().__init__(scope, id, **kwargs)
        
        domain = "https://search-mystack-elasti-1ab2cdefghij-ab1c2deckoyb3hofw7wpqa3cm.us-west-1.es.amazonaws.com"
        
        # The below would return: `jsii.errors.JSIIError: Invalid URL`
        # domain = "search-mystack-elasti-1ab2cdefghij-ab1c2deckoyb3hofw7wpqa3cm.us-west-1.es.amazonaws.com"
        
        es_domain = es.Domain.from_domain_endpoint(self, "imported-es-domain", domain)
        
        print(es_domain.domain_endpoint)
        
        # > https://search-mystack-elasti-1ab2cdefghij-ab1c2deckoyb3hofw7wpqa3cm.us-west-1.es.amazonaws.com
```

### What did you expect to happen?

The `domainEndpoint` attribute to return the endpoint **not** as a URL.

### What actually happened?

See: "what is the problem"

### CDK CLI Version

1.135.0

### Node.js Version

v16.3.0

### OS

Mac

### Language

Python

**Comment by peterwoodworth** [comment]
Thanks for reporting this @joel-aws, you're right. I've been looking into what the scope of the issue is, here's what I've found:

The issue lies only with the `fromDomainEndpoint` function, since `fromDomainAttributes` doesn't require having a full URL with `https://` for the domainEndpoint. 

`fromDomainEndpoint` will return `fromDomainAttributes` by calling it with the same domainEndpoint which you called `fromDomainEndpoint` with, which is resulting in a full URL being the value for the imported `domainEndpoint`https://github.com/aws/aws-cdk/blob/dd5e12d43231d991971de3121928377569b2dd63/packages/%40aws-cdk/aws-elasticsearch/lib/domain.ts#L1200-L1203

We can do some simple string manipulation here to fix this.

This issue is also present in opensearch:

https://github.com/aws/aws-cdk/blob/dd5e12d43231d991971de3121928377569b2dd63/packages/%40aws-cdk/aws-opensearchservice/lib/domain.ts#L1129-L1132
