### ISSUE TITLE
StepFunction: inputPath, resultPath, outputPath should be nullable

### ISSUE THREAD

**Issue by 0xdevalias** [aws/aws-cdk#1805]
Ref: https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-input-output-processing.html

> * The InputPath field selects a portion of the state's input to pass to the state's task for processing. If you omit the field, it gets the $ value, representing the entire input. If you use null, the input is discarded..
> * If the ResultPath is null, the results of executing the state are discarded and the input is untouched.
> * If the OutputPath is null, JSON text representing an empty object {} is sent to the next state.

Looking at the `TaskProps` (`deploy/node_modules/@aws-cdk/aws-stepfunctions/lib/states/task.d.ts`) it seems these are defined as follows:

```
/**
     * JSONPath expression to select part of the state to be the input to this state.
     *
     * May also be the special value DISCARD, which will cause the effective
     * input to be the empty object {}.
     *
     * @default $
     */
    inputPath?: string;

/**
     * JSONPath expression to select part of the state to be the output to this state.
     *
     * May also be the special value DISCARD, which will cause the effective
     * output to be the empty object {}.
     *
     * @default $
     */
    outputPath?: string;

    /**
     * JSONPath expression to indicate where to inject the state's output
     *
     * May also be the special value DISCARD, which will cause the state's
     * input to become its output.
     *
     * @default $
     */
    resultPath?: string;
```

While obviously, in finding this, I can see that the special value `DISCARD` can be used.. though this doesn't seem obvious compared to all of the standard docs saying these fields can be set to `null`.

If I try to set it to `null`, typescript complains: 
![image](https://user-images.githubusercontent.com/753891/53079015-ddf87880-3538-11e9-86a3-a56db176c946.png)

Since `strictNullChecks` is set in the default TypeScript config, this could be implemented as a Union type such as `string | null` as per https://www.typescriptlang.org/docs/handbook/advanced-types.html#nullable-types

I'm guessing perhaps you chose not to do that though, since an end user could change `strictNullTypes`, at which point it would no longer work as expected..

Maybe some other enum sort of type would be useful here? So that it is obvious from the types that there is a way to make it discard the values (since the defaults are to include everything)

**Comment by zarakay** [comment]
could also define the type of `inputPath`, `resultPath` and `outputPath` to include `DISCARD`, eg:

`type Foo = string | 'DISCARD'`

Might provide some good type hints in the IDE to the special value case

**Comment by rix0rrr** [comment]
Though not obvious, we are constrained by the types of the least expressive type system of all languages that we intend to support. Currently that is a toss-up between Java and Go :).

We made the decision to not do type unions, so the choices are between:

```ts
// Two arguments of different type to represent present path/null path
new Task(..., {
  inputPath: '$.input',  
  outputPathNull: true,
});

// Model using objects that both implement IPath
new Task(..., {
  inputPath: new Path('$.input'),
  outputPath: new NullPath(),
});

// Model using objects but require factory functions
new Task(..., {
  inputPath: Path.path('$.input'),
  outputPath: Path.null(),
});

// Use plain strings and reserve one magic value
new Task(..., {
  inputPath: '$.input',
  outputPath: sfn.MAGIC_VALUE
});

```

**Comment by 0xdevalias** [comment]
Is the argument against union types because of needing to support the least expressive type systems? Or something else?

If the former, could unioning a string with an explicit magic string just boil down to a string in those ‘weaker’ systems, but provide more expressiveness where it can be used (eg. In typescript itself)

**Comment by rix0rrr** [comment]
It's an interesting idea. However, type unions are not usually between a singleton type and another type (you're right, that's not too hard). They could be between arbitrarily complex types, for example `number | string[] | IBananaTree`.

Our problem is, how do we (idiomatically) map a TypeScript function:

```ts
function doTheThing(x: number | string[] | IBananaTree): boolean | Date {
 // ...
}
```

To a language without type unions, no return type type deduction, and in some cases, no overloads? In a way that the developers in those languages are comfortable with? Automatically, with no hand-crafting of annotations?

We'd be forced to translate this:

```ts
console.log(doTheThing(5));
```

into one of:

```java
BooleanDate r = doTheThing(NumberStringListIBananaTree.fromNumber(5));
if (r.isBoolean()) {
  System.out.println(r.getBoolean());
}
if (r.isDate()) {
  System.out.println(r.getDate());
}
```

Or:

```java
// Function for every union, disallow return unions
boolean b = doTheThingNumber(5);

// If we go this route, a function with 2 such arguments becomes:
boolean b = doTheThingNumberIBananaTree(20, myBananaTree);
```

One of the goals of jsii is that code (examples!) written in one language can be read, understood and transliterated more-or-less directly into any other JSII language. We don't want people designing APIs that are a joy to use in one language and very cumbersome in a different one, because they didn't think that far ahead.

We're leveling the playing field on purpose, so everyone has to work within the same constraints and come up with good APIs that work in all environments. It's unfortunate but true that this constraint means sacrificing some expressivity in some languages.

**Comment by rix0rrr** [comment]
Still relevant
