### ISSUE TITLE
(pipelines): allow specifying cross region support bucket retention policy

### ISSUE THREAD

**Issue by joekiller** [aws/aws-cdk#18064]
### Description

As a user I'd like to be able to optionally specify in the [CrossRegionSupportStackProps](https://github.com/aws/aws-cdk/blob/f17f29e94265eb450d8f11bdbdbe719f3e511ea2/packages/%40aws-cdk/aws-codepipeline/lib/private/cross-region-support-stack.ts#L88) the retention policy for the CrossRegionSupportConstruct's [bucket](https://github.com/aws/aws-cdk/blob/f17f29e94265eb450d8f11bdbdbe719f3e511ea2/packages/%40aws-cdk/aws-codepipeline/lib/private/cross-region-support-stack.ts#L76-L80)

### Use Case

I am using our pipelines dynamically. As pull requests come in we create a verification pipeline that is a continuously integrated cdk pipeline. Because our stack names are deterministic, if a PR is reopened and a pipeline is recreated we get an error that the helper bucket already exists. Ideally we could specify the retention policy of any pipeline bucket[s] to allow easier teardown.

### Proposed Solution

Enable specifying a retention policy for the cross region support bucket.

our work around is a big yikes command `aws s3 ls | grep "${STACK_NAME}" | awk '{print $3}' | xargs -I {} aws s3 rb s3://{} --force;`

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
Hey @joekiller,

thanks for opening the issue. Unfortunately, even if we implemented this functionality, it would not help you in this scenario.

The problem is that you can't remove an S3 Bucket in CloudFormation by default if it's non-empty. And that would be the situation in your case. So, even if you set the removal policy of the cross-region Buckets as `DESTROY`, the deletion of the support Stacks containing those Buckets would still fail.

The solution here is passing your own Buckets with the [`crossRegionReplicationBuckets` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.Pipeline.html#crossregionreplicationbuckets) when creating your Pipeline. When you do that, you can set their retention policy as `DESTROY`, and additionally setting the [`autoDeleteObjects` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#autodeleteobjects) on those Buckets. That will add a Custom Resource that will clean up the Bucket before it's deleted, and in this way allows you to delete those Stacks successfully.

Hope this helps!

Thanks,
Adam
