### ISSUE TITLE
aws-ec2: SubnetType obsolete warning for .NET

### ISSUE THREAD

**Issue by nickdodd79** [aws/aws-cdk#18103]
### General Issue

Obsolete SubnetType values

### The Question

We are using the .NET flavour of CDK to deploy our AWS resources, one of which is a VPC. During the build of our CDK app we are getting warnings about some `SubnetType` values being Obsolete.

```
'SubnetType.PRIVATE' is obsolete: 'use `PRIVATE_WITH_NAT`'
'SubnetType.ISOLATED' is obsolete: 'use `SubnetType.PRIVATE_ISOLATED`'
```

However, the new values do not exist. We have noticed these warnings for several months and since version 1.122.0 of the CDK packages.

Are there any plans to update the `SubnetType` enum to have the new values? 

Though they are only warnings and not preventing our CDK app from building/running, we are keen to eliminate them from our build output.

### CDK CLI Version

2.0.0 (build 4b6ce31)

### Framework Version

1.136.0

### Node.js Version

v14.17.6

### OS

Windows

### Language

.NET

### Language Version

.NET Core 3.1

**Comment by peterwoodworth** [comment]
Hey @nickdodd79,

This is a known issue with some of our non-TypeScript languages. The issue is currently being tracked in the JSII repo https://github.com/aws/jsii/issues/2782

I'm not familiar of any ways to suppress warnings - but according to Nick this issue should be fixed in v2 https://github.com/aws/aws-cdk/issues/16443#issuecomment-981597390

**Comment by nickdodd79** [comment]
Thanks @peterwoodworth. I'll keep an eye on that linked issue.
