### ISSUE TITLE
(core): v2.3.0 contains no changes

### ISSUE THREAD

**Issue by kylelaker** [aws/aws-cdk#18138]
### What is the problem?

v2.3.0 contains no commits beyond those in v2.2.0. https://github.com/aws/aws-cdk/commits/v2-release; v1.137.0 contains significant changes since December 15 (v1.136.0/v2.2.0).

### Reproduction Steps

View the commits on the [`v2-release`](https://github.com/aws/aws-cdk/commits/v2-release) branch compared to the [`release`](https://github.com/aws/aws-cdk/commits/release) branch

### What did you expect to happen?

Releases of CDKv2 released at approximately the same time as a release of CDKv1 should contain approximately the same changes. The changelog for a release should not be empty. If there aren't any changes, a release should not be made.

### What actually happened?

CDK v2.3.0 is functionally the same as v2.2.0. It does not contain the same fixes and features found in v1.137.0.

### CDK CLI Version

2.3.0

### Node.js Version

N/A

### OS

N/A

### Language

Typescript

**Comment by iliapolo** [comment]
@kylelaker Thanks for reporting this. 

There is an automated mechanism that forward merges code from v1 to v2. The reason this release is empty is because the latest forward merge PR is currently [failing](https://github.com/aws/aws-cdk/pull/18029). 
We are working on fixing it, and once it is merged, the next release of v2 (2.4.0) will contain all those changes. 

We'll also see how to avoid these empty releases in the future.

Thanks

**Comment by rix0rrr** [comment]
We have put code in place to prevent empty releases in the future

**Comment by jrobbins-LiveData** [comment]
When is CDK v2.4 expected, @rix0rrr?
