### ISSUE TITLE
(CloudWatch): export log data to S3

### ISSUE THREAD

**Issue by lenfree** [aws/aws-cdk#18146]
### Description

[Exporting log data to Amazon S3](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/S3ExportTasks.html) 

### Use Case

It would great to be able to configure this with CDK.

### Proposed Solution

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/S3Export.html for reference.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jashgala** [comment]
How would this configuration work? This seems to be an operation that is triggered in an on-demand manner (i.e. when the user wants to perform an export). There are also other gotchas (e.g. "Log data can take up to 12 hours to become available for export")

Do you mean we should be able to schedule the dumping of logs directly into an S3 path on a periodic basis?

**Comment by peterwoodworth** [comment]
Hey @lenfree, thanks for the feature request! Like @jashgala said, it would be helpful if you could further describe how you'd might like to use this feature in the CDK, since this seems to be more of a command than setting up infrastructure.

Additionally, the CDK uses CloudFormation under the hood, so it's much easier for the CDK to implement higher level features like these if CloudFormation already has the resources. However, I can't find anything about export tasks in [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html)

**Comment by lenfree** [comment]
Sorry for the late response, I was thinking more of a scheduled task of exporting the logs like a CRON job?

**Comment by jashgala** [comment]
@lenfree - I believe what you are looking for is something like a Lambda that periodically invokes the S3 Export command and dumps the Cloudwatch logs into S3. The scheduling can be handled through something like Eventbridge/Cloudwatch events.

From the look of it, this seems like something that should be a part of your application and not necessarily something within the aws-cdk itself. CDK will provide all the tooling required for you (e.g. lambda, events, etc.) but putting it all together should ideally be done outside CDK in your CDK stack.

**Comment by lenfree** [comment]
@jashgala, that's a good idea! I was considering adding a Jenkins pipeline but I might go with a Lambda function. Thanks!
