### ISSUE TITLE
(cloudwatch): Should "dimensions" be "dimensionsMap" in Metric?

### ISSUE THREAD

**Issue by akskos** [aws/aws-cdk#18152]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.Metric.html#dimensions

### Description

Metric lists `dimensions` as one of the props in the reference, but this doesn't seem to work when I'm migrating my code from cdk 1 to cdk 2 (i'm getting a type error saying that `dimensions` doesn't exist). Looks like the same thing is called `dimensionsMap` now?

**Comment by madeline-k** [comment]
When creating a new Metric, the [MetricProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.MetricProps.html) has `dimensionsMap`, not `dimensions` in v2. This property name change occurred because we needed to change the type used for the prop. 

See the v1 version of MetricProps here https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudwatch.MetricProps.html

After your Metric is created, you still reference the dimensions on the instantiated object with the `dimensions` public prop. That name didn't change. - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.Metric.html#dimensions
