### ISSUE TITLE
Getting Error: Cannot get policy fragment of my-stack/my-lambda, resource imported without a role

### ISSUE THREAD

**Issue by Mehdi-Bendriss** [aws/aws-cdk#18160]
### General Issue

Cannot get policy fragment of my-stack/my-lambda, resource imported without a role

### The Question

Hello, 

I am creating an SNS topic and adding an already created Lambda `lambdaFun` as a publisher, as shown in the code below:

```
import * as lambda from '@aws-cdk/aws-lambda';
import {Topic} from '@aws-cdk/aws-sns';


function createSnsTopic() {
    const topic = new Topic(this, topicName, {
        topicName: topicName,
        displayName: topicName,
        fifo: true,
        contentBasedDeduplication: true,
        masterKey: kms.Key.fromLookup(this, 'managed-default-sns-kms-key', {
            aliasName: 'alias/aws/sns'
        })
    });
    
    const lambdaFun = lambda.Function.fromFunctionArn(this, 'my-lambda', cdk.Fn.importValue('my-lambda'));
    
    topic.grantPublish(lambdaFun); // Exception thrown because of this
}
```

And I'm getting the following exception:
```
Cannot get policy fragment of my-stack/my-lambda, resource imported without a role
    at UnknownPrincipal.get policyFragment [as policyFragment] (.../cdk/node_modules/@aws-cdk/aws-iam/lib/unknown-principal.ts:24:11)
    at PolicyStatement.addPrincipals (.../cdk/node_modules/@aws-cdk/aws-iam/lib/policy-statement.ts:121:34)
    at new PolicyStatement (.../cdk/node_modules/@aws-cdk/aws-iam/lib/policy-statement.ts:76:10)
    at Function.addToPrincipalOrResource (.../cdk/node_modules/@aws-cdk/aws-iam/lib/grant.ts:70:23)
    at Topic.grantPublish (.../cdk/node_modules/@aws-cdk/aws-sns/lib/topic-base.ts:85:22)
    at createSnsTopic (.../cdk/lib/constructs/app/my-stack.ts:198:15)
    at .../cdk/lib/constructs/app/my-stack.ts:78:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### CDK CLI Version

2.3.0 (build beaa5b2)

### Language

Typescript

### Language Version

4.5.4

**Comment by peterwoodworth** [comment]
This is because resource imports `fromConstrucXxx()` aren't actually retrieving any data from your AWS account. All the CDK has to work with here at synthesis time is the arn you've provided.

What you will want to do here is use [`fromFunctionAttributes()`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda.Function.html#static-fromwbrfunctionwbrattributesscope-id-attrs) and provide the appropriate role in the `role` prop. Now you'll be able to use methods such as `grantPublish()` on your Lambda function, because the function knows which role to use!

**Comment by Mehdi-Bendriss** [comment]
Thank you, that was very helpful!
