### ISSUE TITLE
(certificatemanager): DnsValidatedCertificate validation property default shows CertificateValidation.fromEmail

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#18181]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate.html#validation

### Describe your issue?

`DnsValidatedCertificate` class uses DNS-based validation with custom resource by default. Probably because the implementation extends `CertificateBase` class, it inherits documentation for properties that are not defined by `DnsValidatedCertificate` class. That's confusing, because one doesn't actually need to specify `validation` property when using this construct, but can be mislead to think that it will default to email for whatever reason.

**Comment by njlynch** [comment]
Add this to the list of things I dislike about the design of `DnsValidatedCertificate`. :)

Ultimately, since `DnsValidatedCertificateProps` extends `CertificateProps`, it does have the property, but obviously it's misleading. However, at this time, I don't believe we have a mechanism to be able to override documentation on subclasses. I can keep this open to track, but don't see a line-of-sight to an improvement in the near-term.

**Comment by alexpulver** [comment]
Thank you for the clarification :) I'll close it then for now - if it will be important, it'll pop up again :)
