### ISSUE TITLE
(aws-apigateway): Unable to add an API Stage to a Usage Plan while creating it

### ISSUE THREAD

**Issue by awsperi2** [aws/aws-cdk#18193]
### What is the problem?

We should be able to add an existing API Stage to a Usage Plan that we are currently creating

### Reproduction Steps

```
const usagePlan = UsagePlan.fromUsagePlanId(...);

// will not compile
usagePlan.addApiStage(...)
```

### What did you expect to happen?

Should have been able to add a stage to a Usage Plan being created. 

### What actually happened?

Compilation failure. 

### CDK CLI Version

latest

### Node.js Version

Unknown

### OS

macOS

### Language

Typescript

**Comment by jumic** [comment]
Method `fromUsagePlanId()` has return type [`IUsagePlan`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.IUsagePlan.html). `addApiStage()` does not exist in `IUsagePlan`. Hence, you will get the compilation failure.

The CloudFormation resource type `UsagePlan` supports adding new API Stages. If you use `fromUsagePlanId()`, the Usage Plan already exists. It cannot be modified from another stack where `fromUsagePlanId()` is used. Therefore, method `addApiStage()` cannot be used on an imported Usage Plan due to this CloudFormation limitation.

**Comment by otaviomacedo** [comment]
Exactly what @jumic said. Closing.
