### ISSUE TITLE
(CLI): show the time it takes for `cdk deploy` (including when running `cdk watch`) to finish

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#18213]
### Description

Let's print out the total time it takes for `cdk deploy` to finish, including when a deployment happens through `cdk watch`.

This will allows us to brag more easily about how quickly hotswapping works 😃.

### Use Case

Showing the speedup hotswap deployments offer.

### Proposed Solution

Print out the time it takes for deployment to finish in the CDK CLI.

### Other information

Print out the total time 

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
I actually feel like this is reinventing the wheel a little bit, specifically for `cdk deploy`. We can easily call `yarn cdk deploy` or `time cdk deploy` to get the same functionality. The only time where we can't do this is for `cdk watch`, since it's not one-shot.

I thought we might just do this for `cdk watch` *only* and add a time stamp wrapper around this:

https://github.com/aws/aws-cdk/blob/dee732d063c0658b768bf7b9f24087b8baed2ed6/packages/aws-cdk/lib/cdk-toolkit.ts#L302

Happy to do it for `cdk deploy` if you feel otherwise but I feel like the use case is only for `cdk watch`.

**Comment by skinny85** [comment]
I agree it's not great if we simply write out the total time. So why don't we spice things up a little bit? 😃

What if we divided the different phases of deploy, and printed out the time for reach of them? For example, the time to `synth` the Cloud Assembly immediately jumps out to me as being interesting.

So, the output would be something like:

```
$ cdk deploy MyExampleStack
Stack MyExampleStack
...

✨  Synthesis time: 3.54s
...

✨  Deployment time: 4.56s
...

✨  Total time: 8.1s
...
```

Thoughts on this idea?

**Comment by misterjoshua** [comment]
In this vein, I'd appreciate a performance tracing mode for synthesis because I find it difficult to tell which parts of my cdk app (probably bundling assets, but which?) are slowing my synth down.
