### ISSUE TITLE
(aws-secretsmanager): Cannot create subscriptions for SNS topics

### ISSUE THREAD

**Issue by sphinx07** [aws/aws-cdk#18354]
### General Issue

Problems in retrieving secrets from secret manager using 'fromSecretNameV2', secret values cannot be added to subscriptions

### The Question

I am using the method 'fromSecretNameV2' to get my secret values stored in secret manager, then add the secret values to subscriptions in SNS topics.Using this method 'fromSecretNameV2' I saw the SNS topic created in the console UI, but there were no subscriptions listed for that topic. Moreover, from CloudFormation I can see the resources have been created in CFN, but in the cloudformation template generated, this serect somehow got a different arn compared to the one I set in secret manager.

Later on, this was solved by using another method 'fromCompleteArn' and this time subscriptions are added successfully in topics. 

I am wondering if it is due to the dynamic referencing in cloudformation since it does not accept partial arn on secrets while 'fromSecretNameV2' can only give you a partial arn? However, I do find some successful examples apply 'fromSecretNameV2' and am trying to understand what caused that problem?

My codes before and after are as below:
Before: use 'fromSecretNameV2' --> no subscription added to SNS topics

```ts
const mysecretvalue = sm.Secret.fromSecretNameV2(scope, id, 'secretName').secretValueFromJson('myKey').toString();
```

After: use 'fromCompleteArn' --> works

```ts
const mysecretvalue = sm.Secret.fromCompleteArn(scope, id, 'arnCopiedFromSecretManager').secretValueFromJson('myKey').toString();
```

All the other codes are the same. The url was added by the following code: 

```ts
scope.myTopic.addSubscription(
  new subscriptions.UrlSubscription(mysecretvalue, {
    protocol: sns.SubscriptionProtocol.HTTPS,
  }),
);
```

I am seeing two similar issues: https://github.com/aws/aws-cdk/issues/17792 and https://github.com/aws/aws-cdk/issues/11526, but I am not sure this is a general issue that we should be aware of and if there is any solution to that, or it is a more specific one? I wonder if I can get help on that. 

Thanks!

### CDK CLI Version

2.1.0

### Language

Go

### Language Version

go1.17.3

**Comment by peterwoodworth** [comment]
Hey @sphinx07, sorry for the delay here. We've had a few issues come in regarding this recently, and I believe [this PR](https://github.com/aws/aws-cdk/pull/18567) is set to fix the issue. Let me know if you don't think that's the case and I'll take a closer look at this 🙂

**Comment by njlynch** [comment]
@sphinx07 ,

Looking at #11526 is certainly potentially relevant. Does your secret name end in a dash and six characters (e.g., `my-secret`, `database-passwd`)? If so, that would be the reason why the above fails; the "partial" ARN that a secret imported by name is given can be confused by various services as a "full" ARN, resulting in a failed lookup. You can see this yourself using the SDK or CLI:

```
aws secretsmanager describe-secret --secret-id arn:aws:secretsmanager:us-east-1:172456244520:secret:database-passwd
```

The above will fail, even if you have a secret named `database-passwd` and have all proper permissions to it. In the case of using `secretValueFromJson`, the partial ARN is being passed to a CloudFormation dynamic resource, which then is going to encounter the same issue as the above.

If your secret name does _not_ have a six-character suffix, then let me know and we can dive deeper.

We _could_ change the logic of `secretValueFromJson` to use either the secretFullArn (if present) or the secretName (if not), and avoid partial ARNs altogether. However, that may cause some existing cross-account use cases to fail and needs a deeper look (and/or feature flag) before we decide to make that change. For what it's worth, I've tested the `sm.Secret.fromSecretNameV2(scope, id, 'secretName').secretValueFromJson('myKey').toString()` as an input to a few constructs, and each seem to work for me, which is why I suspect it's the six-character issue above.

**Comment by sphinx07** [comment]
@njlynch , you are absolutely correct. My secret does have six character suffix and your explanation does make sense. Thanks a lot for your help!!
