### ISSUE TITLE
Ability to pass multiple deployment roles to different stacks on single deployment call

### ISSUE THREAD

**Issue by nomadme** [aws/aws-cdk#18358]
### General Issue

Yes

### The Question

Is there a way to pass role for the parent stack to be invoked as?

just like when invoking a specific stack from the cdk:
`cdk deploy StackA -r <arn>`

My use case is, we need to create a parent stack with different role arn, and the child stack uses another role to be invoked.

Here is the general dependency I have.
```
StackA
StackB
   needs StackA resource arn
```

But, the StackA needs a different role arn to be invoked first, like `cdk deploy StackA -r <arn>`
and I have to invoke the StackB on a separate call like this `cdk deploy StackB`.

Instead, my preferred invocation would look like just only `cdk deploy StackB`, which deploys the StackA first, and deploys the StackB, just like in the dependency above. 

### CDK CLI Version

1.135.0 (build 3825f59)

### Node.js Version

v16.13.1

### OS

Mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @nomadme,

Currently, the only way to set the role which invokes your stack is through the CLI, I'm not aware of any workarounds for this at the moment unfortunately.

I can't promise that we will implement something like this soon, but I'm going to relabel this as a feature request so that it can be tracked 🙂
