### ISSUE TITLE
(CLI): hotswapping should wait for Lambda's `updateFunctionCode` operation to complete

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#18386]
### Description

Right now, when hotswapping Lambda code, we don't wait for the `updateFunctionCode` API call we make to complete.

However, according to [the documentation](https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/), this operation is actually eventually consistent today for Lambda functions that use Docker images, or are present in a VPC, and, even more importantly, this API will become eventually consistent for all Functions starting February 1, 2022.

We need to change our logic to wait for the operation to complete.

While implementing this, we should be cognizant of making sure we wait as effectively as possible, to not affect Lambda hotswap times too adversely. The simplest solution might be to use the standard Lambda waiter, that we use if [we need to publish a new Version](https://github.com/aws/aws-cdk/blob/a9038ae9c7d9b15b89ae24cfa24aefa6012674bc/packages/aws-cdk/lib/api/hotswap/lambda-functions.ts#L221-L228). Perhaps we can use a custom Waiter for this purpose, like we do for [ECS service hotswapping](https://github.com/aws/aws-cdk/blob/a9038ae9c7d9b15b89ae24cfa24aefa6012674bc/packages/aws-cdk/lib/api/hotswap/ecs-services.ts#L131-L173).

Thanks a lot to @tmokmss who figured out all of this while working on [Docker image Function hotswapping](https://github.com/aws/aws-cdk/pull/18319#issuecomment-1010627441).

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
After looking into this, there are some nuances to account for. Here is what I've found.

There are a couple pieces of information that we get from Lambda after updating the function code
### `State`
controls whether we can update the function _and_ whether we can invoke it
- `State=Active`: Function can be invoked _and_ updated
- `State=Pending`: Function cannot be invoked or updated
 
For our purposes the `State` can either be `Active` or `Pending`. When updating a function (not creating) there is only 1 scenario when the State can be `Pending` (when `StateReasonCode=Restoring`) which I describe later on.

### `LastUpdateStatus` 
controls whether the function can be updated
- `LastUpdatedStatus=Complete`: The update is complete and the function can be updated
- `LastUpdateStatus=InProgress`: The update is in progress. If the `State=Active` then the function can still be invoked, but the invoke will happen against the old config. Cannot make updates while the status is `InProgress`

### `StateReasonCode`
 The reason for the current `State`. For our purposes the only value we care about is:
- `StateReasonCode=Restoring`: This will only occur on a VPC function that has been idle for a couple of weeks and Lambda has reclaimed the ENI resources. If you make an update to an idle function the `State` will transition to `Pending` with the `StateReasonCode=Restoring`. During this time the function cannot be invoked or updated.

### Update Time

In my testing I found that the time it took for a function to go from `LastUpdateStatus=Pending` => `Complete` was:

- ~1 second for a zip Function _not_ in a VPC
- ~25 seconds for a container Function _or_ a Function in a VPC
- ~2 minutes to deploy a VPC function (best proxy for `StateReasonCode=Restoring`)

### Proposal

Based on the above I think we have to account for 2-3 different scenarios.

**Scenario 1** - zip function _not_ in a VPC
If the function is a zip function _not_ in a VPC (we get this info back from `updateFunctionCode`) then we can poll (quickly) for `LastUpdateStatus=Complete`. We probably don't want to use Lambda waiters for this since those wait at 5 second intervals.

**Scenario 2**: `StateReasonCode=Restoring`
In this scenario we need to wait until `State=Active` & `LastUpdateStatus=Complete`. I think it makes sense to not complete the hotswap operation until this state is reached since the function cannot be invoked or updated. We can poll more slowly here since we know it will take at least 60 seconds.

**Scenario 3**: container function _or_ function in a VPC
In this scenario we can immediately invoke the function, but cannot make updates (for ~25 seconds). We could try to handle this differently than scenario 2, for example the hotswap operation could complete, but we could block/queue future updates until the `LastUpdateStatus=Complete`. Since this is a hotswap though I would assume that the user would core more about being able to invoke the "new" code so they probably wouldn't consider the hotswap complete until `LastUpdateStatus=Complete`. If this is the case, we would just treat this scenario the same as scenario 2.

**Comment by skinny85** [comment]
Awesome work @corymhall researching this, super thorough! I agree with all of your recommendations 🙂.

Given that, do you have enough information to start working on implementing this?

**Comment by corymhall** [comment]
@skinny85 yep I've already started working on it :)

**Comment by skinny85** [comment]
@corymhall one last question. I understand your comment gives a great summary of the current state.

Do you know how will that description be affected by the changes outlined in the blog post linked in the issue description, that are scheduled to go out on February 1?

**Comment by corymhall** [comment]
@skinny85 my comment describes the state with those changes in place. In the current state the `State` will always be active and the `LastUpdateStatus` will always be `Successful`.
