### ISSUE TITLE
Ec2.ClientVpnEndpoint construct is missing tagSpecifications

### ISSUE THREAD

**Issue by ALxWi** [aws/aws-cdk#18381]
### Description

It is currently not possible to add specific tags to ec2.ClientVpnEndpoint. There is no property in the interface to specify the tagSpecifications. The core Tags functionality (Tags.of(scope)add())does not work with the endpoint.

The CfnClientVpnEndpoint construct accepts tagSpecifications.

### Use Case

I need this to apply the appropriate tags to the endpoint.

### Proposed Solution

include tagSpecifications in the interface ClientVpnEndpointProps

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by cokia** [comment]
https://github.com/cokia/aws-cdk/commit/cccfafceaefb47826600d62d2d52968a1bbafbad

I made a simple modification for this issue.

Please tell me if the issue I understood is what you think.

If correct, I will write a test code, update the readme, and write a PR.

**Comment by njlynch** [comment]
The reason normal tagging conventions don't apply here is because the `ClientVpnEndpoint` structure in CloudFormation is using a non-standard name (`tagSpecification`), rather than just `tags`. The fix above by cokia would be one solution, but wouldn't allow the CDK standard tagging mechanism (e.g., `Tags.of(..).add`) to work.

The correct fix likely lies in fixing our `cfn2ts` code generation tool to generate a `tags` property for this class. However, this will be difficult to do in a backwards-compatible way, so perhaps the above solution is the better short-term approach.

**Comment by landonboyd** [comment]
I just ran into this issue.  It would be great to be able to tag VPN Endpoints using the ClientVpnEndpoint construct, even if it's in a non-standard way (as per the underlying CloudFormation).
