### ISSUE TITLE
(stepfunctions): lazily calculate state machine definition

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#18454]
### What is the problem?

Step functions state machines silently fail to add states after the state machine resource has been created.

### Reproduction Steps

```ts
import { App, Stack } from 'aws-cdk-lib';
import { Parallel, Pass, StateMachine } from 'aws-cdk-lib/aws-stepfunctions';
import { Construct } from 'constructs';

class MyThing extends Construct {
  readonly parallel: Parallel;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.parallel = new Parallel(this, 'Parallel');
    this.parallel.branch(new Pass(this, 'PreventParallelMustHaveAtLeastOneBranchException'));

    new StateMachine(this, 'StateMachine', {
      definition: this.parallel,
    });
  }

  addSomething(id: string) {
    this.parallel.branch(
      new Pass(this, id, {
        parameters: {
          something: id,
        },
      }),
    );
  }
}

const app = new App();
const stack = new Stack(app, 'lazy-sfn');

const myThing = new MyThing(stack, 'MyThing');
// XXX: The following do not add branches and fail silently, as by the time
// MyThing creates the StateMachine, it's already too late to change the
// state graph.
myThing.addSomething('test1');
myThing.addSomething('test2');

app.synth();
```

### What did you expect to happen?

I expected the state machine definition to include the `test1` and `test2` Pass states.

### What actually happened?

The state machine synthesizes a definition that doesn't include the `test1` and `test2` states. It also doesn't throw an error to indicate that I've done something I shouldn't.

### CDK CLI Version

2.8.0

### Framework Version

2.8.0

### Node.js Version

14.18.2

### OS

Linux

### Language

Typescript

### Language Version

TypeScript (4.5.4)

### Other information

Rather than creating the graph json immediately, I'd like StateMachine to defer rendering the state graph until the synthesis phase. https://github.com/aws/aws-cdk/blob/626e6aa1a27feffe7ce60a46a6fdcf26f317eaef/packages/%40aws-cdk/aws-stepfunctions/lib/state-machine.ts#L399

**Comment by peterwoodworth** [comment]
This is expected @misterjoshua, the StateMachine is created with the definition you pass in at the time of creation, so unfortunately this approach won't work. I don't see this explicitly called out in our docs anywhere, but this is the typical behavior of constructs in the CDK. The exceptions are lazy values - an example of a construct that has this is TaskDefinition which will synthesize changes made to these properties after the resource has been created. https://github.com/aws/aws-cdk/blob/9578a49de62e8e32b3aecd26a8c3350f15e15990/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L445-L447

However, if we were to lazily calculate Sfn definition, I believe that would be a breaking change, since escape hatches don't work the same way. @kaizen3031593 is there any path forward here?

**Comment by kaizen3031593** [comment]
We do something similar in `pipelines` to allow for exactly what @misterjoshua is asking for, but I'd argue that the use case for calling `pipelines.addStage()` is far more defined (and natively supported) than what you're trying to do in `stepfunctions` with `myThing.addSomething()`. In general, the pattern I see for `stepfunctions` is to define the `definition` on its own and add it into the `stateMachine` as the last step.

At any rate, I do think it would be a breaking change to lazily produce the definition. I don't think this is something we'd be eager to support.
