### ISSUE TITLE
[cdk deploy] cdk deploy does not take into account the specific bootstrap qualifier 

### ISSUE THREAD

**Issue by VXConsulting** [aws/aws-cdk#18453]
### What is the problem?

I had bootstraped my account with the following qualifier : devops
The synth command synthesizes the stack with the correct values of bootstrap :
`
BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/devops/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
`

### Reproduction Steps

`
cdk bootstrap --qualifier devops aws://xxxx/eu-west-1
`

My stack is:

`InfraBackbonePipelineStack(app, stackName, {
    synthesizer: new DefaultStackSynthesizer({
         qualifier: "devops"})
`

Then I execute : `cdk deploy `

### What did you expect to happen?

Deployment of the stack using the correct bootstrap qualifier 'devops'

### What actually happened?

But the cdk deploy commands is always in error:
` Error [ValidationError]: Unable to fetch parameters [/cdk-bootstrap/hnb659fds/version] from parameter store for this account.
`

### CDK CLI Version

2.8

### Node.js Version

14.17.3

### OS

Ubuntu 20.04

### Language

Typescript

### Language Version

Typescript 4.5.4

**Comment by mrpackethead** [comment]
Have you modifiyed your cdk.json to reflect that you are not using the default qualifier?  

hnb659fds is the default value for a cdk project.

**Comment by VXConsulting** [comment]
Yes I have.
But, I detected that this problem now occurs only on one account.
I will clean the stacks and the bootstrap stack and see if I still have the problem.

**Comment by peterwoodworth** [comment]
Let us know once you have an update here 🙂

**Comment by emccullagh** [comment]
Just hit this issue as well. On an environment that doesn't have the default CDK bootstrap stack deployed (hence no `/cdk-bootstrap/hnb659fds/version` SSM param existed). I've tried setting the qualifier in both the `cdk.json` file and via the `DefaultStackSynthesizer`, but I still get the same ValidationError mentioned above. I'm using CDK v2.8.0, but also got the error with v2.7.0

**Comment by abhisjoshi** [comment]
I also encountered the same issue. It happens when you have deployed a resource and later change the qualifier for the bootstrap. Even even after setting the value of the new qualifier in the app, during the deploy one gets this error. So it seems changing the qualifier impacts any apps that were previously deployed.

Steps to replicate:

cdk bootstrap qualifier --external
Changes to app (cdk.json) to use this qualifier "@aws-cdk/core:bootstrapQualifier": "external"
cdk deploy 
change the qualifier to internal "cdk bootstrap qualifier --internal"
Changes to app (cdk.json)  to use this qualifier "@aws-cdk/core:bootstrapQualifier": "internal"
cdk deploy - this step gives an error:

`MyCdkStack failed: Error [ValidationError]: Unable to fetch parameters [/cdk-bootstrap/external/version] from parameter store for this account.
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-02-02T06:10:04.825Z,
  requestId: '1e8887ad-e555-4ffa-b223-5c5038dd3a4f',
  statusCode: 400,
  retryable: false,
  retryDelay: 343.7898234226937
}
Unable to fetch parameters [/cdk-bootstrap/external/version] from parameter store for this account.`

**Comment by abhisjoshi** [comment]
I was able to resolve it. By default, the AWS CDK retains values of parameters from previous deployments and uses them in subsequent deployments if they are not specified explicitly. 

To resolve the issue, i used the command. And now i am able to deploy.

cdk deploy --no-previous-parameters

**Comment by peterwoodworth** [comment]
Thanks for posting your findings @abhisjoshi, much appreciated 🙂 Hopefully this was the root cause for the others as well

**Comment by VXConsulting** [comment]
Thanks it works :-)

**Comment by rmjwilbur** [comment]
Hi @peterwoodworth - I encountered the same behaviour today with v2.149.0. My thoughts on this are:

- the above describes a workaround to a bug that still remains. The bug should be fixed.
- I overlooked the qualifier when I first deployed a stack without fully understanding that we need to bootstrap for each application / stack set. I mistakenly thought aws://account/region was considered an environment. Perhaps a more intuitive qualifier, such as "myApp" could be used rather than a meaningless value, along with a little clearer documentation on the importance of determining a qualifier before bootstrapping
- as Serverless Framework has changed their pricing model, it looks like there are going to be many of us looking to CDK as a viable alternative. I'm sure there are others with multiple apps requiring separate qualifiers

**Comment by CodeSammich** [comment]
+1 This is still not resolved. Why bother introducing a qualifier for bootstrap if you won't support it for deploy? You're just asking people to stumble on this point.

Even when trying to deploy with `cdk deploy --toolkit-stack-name`, it still defaults to this useless default value. 

This directly inhibits use in certain policies, such as within SCPs.
