### ISSUE TITLE
(stepfunctions): Set state id

### ISSUE THREAD

**Issue by milesgranger** [aws/aws-cdk#18526]
### Description

When attempting to migrate to CDK, I find this will fail with `jsii.errors.JSIIError: There is already a Construct with name 'Step 1' in Stack [MyStack]`

```python
for i in range(2):
    sfn.StateMachine(
        self, f'Machine{i}',
        definition=sfn.Pass(self, 'Step 1')
    )
```

These are two different StateMachine's and should be allowed to have repeated state ids.
I've attempted to set `state_id`, but that is not allowed.

### Use Case

We generate state machines dynamically using SAM with standard CloudFormation templates. All follow a similar, but not exactly the same, structure. As each state with the same Id can invoke a different function/resources between state machines. 

Specifically, this is for data warehouse ETL state machines, among other things an "ETL" state, but that state is attached to different functions or fargate/batch tasks.

Example:
![image](https://user-images.githubusercontent.com/13764397/150115040-6cadc6a6-dfdd-4ca5-a4b9-27b63ad70dea.png)

For consistency, it's much easier hopping from state machine to state machine and seeing the 'common' states with the same Id.

### Proposed Solution

Either add an optional `state_id` parameter to all State objects, or allow setting the state id after construction.
Thus, the updated passing example case would be something more like: 
```python
for i in range(2):
    sfn.StateMachine(
        self, f'Machine{i}',
        definition=sfn.Pass(self, f'Step1-Id-{i}', state_id="Step 1")
    )
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by milesgranger** [comment]
Should also mention, one can get around this by wrapping the state machine creation in its own `Construct`.

**Comment by kaizen3031593** [comment]
Sorry for the delay in getting to you, @milesgranger. I believe the issue here is a confusion between state Ids scoped to your state machine and construct ids scoped to your CDK construct tree. 

In the CDK, there is a concept of a construct tree and each construct in the tree must have a unique ID. I believe that is the error you are seeing, which is separate from the state IDs. 

I have a better solution fro you than wrapping each state machine in its own construct (which also works since they would then belong to separate construct trees). Have you seen the [`StateMachineFragment`](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-stepfunctions#state-machine-fragments) construct? It was built to be a reusable state machine construct, and there is a fancy method you can use called `prefixStates()` that was created to circumvent the issue you are describing.

Hope that helps!

**Comment by milesgranger** [comment]
Thanks @kaizen3031593. Agree, the example doesn't make the distinction between the state ids and the construct ids. Great tip with the `StateMachineFragment`, I appreciate it! :+1: Feel free to close, I'm satisfied with the options to get the desired effect.

**Comment by peterwoodworth** [comment]
feel free to ping us with any additional questions 🙂
