### ISSUE TITLE
Use prefix-list in a call to CfnRoute

### ISSUE THREAD

**Issue by mgolden** [aws/aws-cdk#18543]
This ticket was closed but shouldn't have been:

_Originally posted by @github-actions[bot] in https://github.com/aws/aws-cdk/issues/17468#issuecomment-969073347_

**Comment by peterwoodworth** [comment]
Could you please provide more detail? Looking at the issue, it seems OP's issue has been resolved.

**Comment by mgolden** [comment]
The original post ends with a comment from a bot saying not to close the issue, because the team will not have visibility. That is what prodded me to reopen it. If you're referring to the last comment on the linked coverage roadmap, that is inadequate. Yes, this same result can be accomplished through the use of an AwsCustomResource, and that is in fact what I proceeded to do. But of course, anything can be accomplished that way, but it's a crappy experience. If this is actually on the roadmap, then it would make sense to close this issue.

I am confused about why the bot would make this comment if the team doesn't want the issue reopened..

**Comment by peterwoodworth** [comment]
The bot automatically responds to issues which have already been closed. In this case, the issue was closed because the creator of the issue closed it, as they deemed the response acceptable.

So, thanks for elaborating on why you think the issue should still be open. I agree that this experience is less than ideal. However, there isn't anything that our team can do about this. This is dependent on the CloudFormation team to provide support. According to the linked issue on their roadmap, [they are working on it](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/572) - at least according to their project board. So hopefully this should be available soon

**Comment by mgolden** [comment]
OK, closing it!
