### ISSUE TITLE
CDK accepts Role.fromRoleArn for an ARN that does not exist.

### ISSUE THREAD

**Issue by angelinatquach** [aws/aws-cdk#18579]
### What is the problem?

Calling `fromRoleArn` for an ARN that does not exist actually returns a role.

```
const role = Role.fromRoleArn(scope, id, unexistent_role_arn, {
            mutable: false,
        });
```

This seems like a bug since this provides a false positive for developers. If I am under the impression that a role has been found with the provided role ARN, than I will continue forward with my other code logic and my code will fail somewhere down the line.

Please improve the logic of `fromRoleArn` to return either null/undefined/throws error for a non-existent role ARN.

### Reproduction Steps

```
const role = Role.fromRoleArn(scope, id, unexistent_role_arn, {
            mutable: false,
        });
```

### What did you expect to happen?

throws error or returns NULL or undefined.

### What actually happened?

returns a Role object.

### CDK CLI Version

2.8.0

### Node.js Version

n/a

### OS

n/a

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @angelinatquach,

This is how most of our imports work in CDK. With the exception of the `fromLookup()` method and a [couple others](https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_methods) (none of these are featured on the Role construct), our methods which import resources don't actually communicate with your account or AWS at all. Imported resources in this case are instead mock constructs, which essentially contain just the data you provide. These mock constructs are necessary so that you can pass in either an existing resource or a newly created resource of the same type to another construct. So, since these imported constructs are essentially just another way to pass data to another construct, you'll end up running into the error on deployment if the resource you specify doesn't exist.
