### ISSUE TITLE
(appflow): CfnFlow.ScheduledTriggerPropertiesProperty.firstExecutionFrom property is missing.

### ISSUE THREAD

**Issue by ksharlandjiev** [aws/aws-cdk#18684]
### What is the problem?

[API documentation](https://docs.aws.amazon.com/appflow/1.0/APIReference/API_ScheduledTriggerProperties.html) includes ` firstExecutionFrom ` - Timestamp for the records to import from the connector in the first flow run. 
This field is essential, as it allows customers to instruct AppFlow what data to ingest on the first run. 

### Reproduction Steps

Reported by customer, missing in CDK. 

### What did you expect to happen?

Always. 

### What actually happened?

With CDK, you are unable to create a scheduled Flow using `firstExecutionFrom`

### CDK CLI Version

latest

### Node.js Version

all

### OS

all

### Language

Typescript

**Comment by ryparker** [comment]
Hey @ksharlandjiev 👋🏻 

Thanks for bringing this to our attention. It does indeed look like we're missing that property on the L1. This issue will be prioritized based on 👍🏻 but as always we appreciate any contributing PRs if you'd like to patch it yourself.

For the interim as a workaround you can always expand an L1 construct by using [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html).

**Comment by skinny85** [comment]
Hey @ksharlandjiev,

looks like this is a gap in CloudFormation, and that's why CDK doesn't support it - looks like the [`ScheduledTriggerProperties` type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appflow-flow-scheduledtriggerproperties.html), which is used for [`CfnFlow`'s `triggerConfig` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appflow-flow.html#cfn-appflow-flow-triggerconfig), is missing the `firstExecutionFrom` property.

Given that, I'm marking this one as `needs-cfn`. If there's not an issue for this already, it might be worth it to create one in the [CloudFormation coverage roadmap repository](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap).

Thanks,
Adam

**Comment by peterwoodworth** [comment]
I couldn't find an issue for this on the coverage repo, like Adam said, create an issue there if you'd like to see this. 

Closing because there's no action we can take

**Comment by ksharlandjiev** [comment]
@skinny85
Hi Adam,
ClouFormation support is now available. Please refer to this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appflow-flow-scheduledtriggerproperties.html

**Comment by peterwoodworth** [comment]
This will be automatically fixed after a little bit now that it's fixed in cfn, so i don't think there's much of a point in reopening

**Comment by skinny85** [comment]
Yep, I agree with @peterwoodworth.

@ksharlandjiev CDK picks up these changes automatically from CloudFormation, so they should be available in the next release.
