### ISSUE TITLE
(ec2): VpnGateway should allow passing a VPC for automatic attachment

### ISSUE THREAD

**Issue by jeffb4** [aws/aws-cdk#18701]
### Description

Currently, the L2 object `ec2.VpnGateway()` is not especially useful - you can certainly use it to create a `AWS::EC2::VPNGateway` but it then requires using a L1 object (`CfnVpcGatewayAttachment`) for any practical use. Presumably it is called by `ec2.Vpc.enable_vpn_gateway()` internally.

Allowing a Vpc object to be passed into VpnGateway as a conditional parameter would allow the creation of a VpcGatewayAttachment and more utility.

### Use Case

Creating a VpnGateway and VpcGatewayAttachment without mutating the Vpc object after its creation

### Proposed Solution

Optional named parameter `vpc` to the `VpnGateway` constructor

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Thanks for this feature request.

You are correct that `vpc.enable_vpn_gateway()` uses the `VPNGateway` (and `CfnVPCGatewayAttachment` and `CfnVPNGatewayRoutePropagation`) under the hood. There's some non-trivial logic here around ensuring routes are propagated and that the right subnets exist, which is why I believe today the directionality of this method comes from the vpc.

If you have a VPC object already, is there a particularly strong use case for doing `ec2.VpnGateway(..., vpc)` vs `vpc.enable_vpc_gateway(...)`?

**Comment by jeffb4** [comment]
No, there was no particularly strong use-case, it was more that the object model didn't make a lot of sense without the capability. A note in the source code that `ec2.VpnGateway` should not be used directly might be indicated.
