### ISSUE TITLE
Using IF condition in constructs

### ISSUE THREAD

**Issue by conservative-dude** [aws/aws-cdk#18777]
### General Issue

Can't use IF condition

### The Question

Constructs like `CfnLoadBalancer` or `CfnNodegroup` accepts `subnets`  which is an array of ids of subnets. In CloudFormation I can write conditions like this:
```yaml
      Subnets: !If
        - IsMyCondition
        - - "{{resolve:ssm:MyParamPath1/Id:1}}"
          - "{{resolve:ssm:MyParamPath2/Id:1}}"
          - "{{resolve:ssm:MyParamPath3/Id:1}}"
        - - !ImportValue my-import-value-1
          - !ImportValue my-import-value-2
          - !ImportValue my-import-value-3
```

I can't create same kind of expression via CDK for that `subnets` property because of type mismatch — `Fn.condition_if` returns an Fn condition token, not an array. What are my options then?

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Language

Python

### Language Version

Python 3.8.12

**Comment by peterwoodworth** [comment]
Hey @conservative-dude,

I've responded to a similar question [here](https://github.com/aws/aws-cdk/issues/9297#issuecomment-1002323900). I recommend reading this thread, I think you'll find it relevant.

In short, since the CDK is used in programmatic languages, there's usually no need for something like `CfnCondition` which is used to represent logic in a template. You can set conditions when defining any arbitrary property through your programming language of choice.

Let me know if you have any follow up questions 🙂
