### ISSUE TITLE
(lambda): cross account lambda resolvers can not be created

### ISSUE THREAD

**Issue by vdahlberg** [aws/aws-cdk#18781]
### What is the problem?

Can not create cross account lambda function resolver for an appsync api. It tries to add a permission to lambda but can not.
Worked in CDKv1 but not in CDKv2.

### Reproduction Steps

```ts
import { aws_lambda, Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as appsync from '@aws-cdk/aws-appsync-alpha';

export class GraphqlbugStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const api = new appsync.GraphqlApi(this, 'Api', {
      name: 'demo',
    });

    const myLambda = aws_lambda.Function.fromFunctionArn(this, "function", "arn:aws:lambda:eu-west-1:111222333444:function:MyLambda")
    const demoDS = api.addLambdaDataSource("lambdaDataSource", myLambda)

    demoDS.createResolver({
      typeName: 'Query',
      fieldName: 'getDemos',
    });
    
  }
}
```

Then run `cdk synth`

### What did you expect to happen?

Generates a cloudformation template.

### What actually happened?

```sh
/Users/.../node_modules/aws-cdk-lib/aws-lambda/lib/function-base.ts:212
              throw new Error('Cannot modify permission to lambda function. Function is either imported or $LATEST version. '
                    ^
Error: Cannot modify permission to lambda function. Function is either imported or $LATEST version. If the function is imported from the same account use `fromFunctionAttributes()` API with the `sameEnvironment` flag.
    at Object.addToResourcePolicy (/Users/.../node_modules/aws-cdk-lib/aws-lambda/lib/function-base.ts:212:21)
    at Function.addToPrincipalOrResource (/Users/.../node_modules/aws-cdk-lib/aws-iam/lib/grant.ts:77:45)
    at Import.grantInvoke (/Users/.../node_modules/aws-cdk-lib/aws-lambda/lib/function-base.ts:195:25)
    at new LambdaDataSource (/Users/.../node_modules/@aws-cdk/aws-appsync-alpha/lib/data-source.ts:197:26)
    at GraphqlApi.addLambdaDataSource (/Users/.../node_modules/@aws-cdk/aws-appsync-alpha/lib/graphqlapi-base.ts:106:12)
    at new GraphqlbugStack (/Users/.../lib/graphqlbug-stack.ts:15:24)
    at Object.<anonymous> (/Users/.../bin/graphqlbug.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/Users/.../node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Subprocess exited with error 1
```

### CDK CLI Version

2.9.0

### Node.js Version

v16.13.2

### OS

macOS Catalina

### Language

Typescript

### Language Version

TypeScript (4.5.5)

**Comment by vdahlberg** [comment]
I was confused when it didn't work on cdk v1.143.0 (same error as above). However, when downgrading to cdk v1.130.0, it **does** work.

This is the example synths fine with cdk v1.130.0;
```ts
import * as cdk from '@aws-cdk/core';
import * as appsync from '@aws-cdk/aws-appsync';
import * as lambda from '@aws-cdk/aws-lambda'

export class Appsynccdk1BugStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const api = new appsync.GraphqlApi(this, 'Api', {
      name: 'demo',
    });

    const fn = lambda.Function.fromFunctionArn(this, "mylambda", "arn:aws:lambda:eu-west-1:111222333444:function:MyLambda")

    const dataSource = api.addLambdaDataSource("lambdaDataSource", fn)


    dataSource.createResolver({
      typeName: 'Query',
      fieldName: 'getDemos'
    })

  }
}

```

So somewhere between cdk v1.130.0 and cdk v1.143.0 it stopped working.

**Comment by sseidel16** [comment]
I am also having this issue when upgrading cdk to 1.143.0. Calling `grantInvoke` on a cross-account lambda fails with the above error. Previously, my stacks worked just fine, and calling `grantInvoke` only modified the `iam.IGrantable` identity, which is not a cross-account resource, so this seems like it should work fine. What changed?

I am attempting to roll back slowly, version by version, until I get to one that does not fail.

**Comment by sseidel16** [comment]
It looks like going from version `1.38.2` to `1.39.0` causes the issue.

**Comment by sseidel16** [comment]
@kaizen3031593 thanks for the explanation. This really comes down to the line "we must also add a trust policy on the resource." I assumed `grnatInvoke` only modified the `iam.IGrantable`.

I believe it's not necessarily correct that "the imported lambda did not have the permissions to allow appsync to call it." Cross-account lambdas are often owned by other teams and these permissions are then added separately.

We have a use case currently where the cross-account lambda is owned by somebody else, and they have added the proper permissions to it manually. The only thing needed is to allow the invoke action on our lambda's role. The entire flow worked prior (build, deployment, invoke), and now breaks because it's trying to modify the resource as well (and this has already been done manually).

**Comment by kaizen3031593** [comment]
We seem to have stumbled on a rabbit hole here that was most recently modified here: https://github.com/aws/aws-cdk/pull/11369 (and that PR links to at least 2 others trying to do the same thing).

There are a few attributes you can try from `fromFunctionAttributes()` that are related: `sameEnvironment` and `allowPermissions`. But after hearing the use case you describe, I wonder if these will both still result in deploy time failures (since there is no way to attempt to modify imported resources). Perhaps we need to introduce a property like `skipPermissions` to address this use case.

At any rate, I'm a bit out of my depth and I'll wait for @skinny85 to weigh in.

**Comment by skinny85** [comment]
I agree with everything @kaizen3031593 said 🙂.
