### ISSUE TITLE
(eks): missing access to Kubernetes objects on EKS cluster creation

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#18843]
### General Issue

Missing access to Kubernetes objects on EKS cluster creation

### The Question

We're missing access to Kubernetes objects on EKS cluster creation.

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/31543/152697805-4517f537-5fdf-4cc8-91ca-c33f5e43d969.png">

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/31543/153116866-2679f974-dec8-4811-93bd-154f4cd84d64.png">

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/31543/153117017-eab1af1d-2275-43e5-aa7a-e20a43789864.png">

### CDK CLI Version

2.0.0 (build 4b6ce31)

### Language

Typescript

**Comment by mvs5465** [comment]
I was able to get past this by setting the `mastersRole` property equal to my IAM role. https://docs.aws.amazon.com/cdk/api/v2//docs/aws-cdk-lib.aws_eks-readme.html#masters-role

**Comment by peterwoodworth** [comment]
I'm not too sure what the context is here, was this working before and isn't working anymore? Which constructs are you using?

**Comment by robertd** [comment]
Sorry for being vague with my original post @peterwoodworth. I don't think this ever worked. I'm using `Cluster` construct. I've tried creating a cluster using `eksctl` and I was able to see all the workloads and nodes in the console.

**Comment by robertd** [comment]
@mvs5465 Thanks. I'll give it a try.

**Comment by robertd** [comment]
@mvs5465 What does the default behavior then mean? Will the master role be created by default? If it is... how do we get it? 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/31543/153116700-29b5d753-0823-4826-aae5-2a419c6ae23e.png">

**Comment by pmkuny** [comment]
@robertd Are you using assumed credentials in the CLI and `cdk deploy`, by chance? I've run into something similar that's mentioned here https://github.com/aws/aws-cdk/issues/16888 - my understanding is that cdk deploy is using the deployment role instead of assumed credentials, so the Cluster is created with implicit admin set to that role, instead of any assumed role you're using in the CLI.  In comparison, `eksctl` and Console creation use whatever assumed role you're executing with.

**Comment by robertd** [comment]
@pmkuny Yes. I’m using assumed creds.

**Comment by pmkuny** [comment]
@robertd Additionally, see this latest merge: https://github.com/aws/aws-cdk/pull/18963 - Adds the ability to use a CLI-credential based synthesizer.

**Comment by robertd** [comment]
@pmkuny Sweet. Looking forward to 2.13.0 release.

**Comment by robertd** [comment]
@pmkuny I just tried 2.13.0 release and I'm still getting RBAC issues with my cluster.

```ts
const stack = new Stack(mockApp, 'testingKarpenterFargateEphemeralStack', {
  env,
  synthesizer: new CliCredentialsStackSynthesizer(),
});
```

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/31543/154899865-f671377d-b757-406b-a0ce-9a33d2b37e74.png">

**Comment by pmkuny** [comment]
@robertd - Sorry to hear that. I think leaving this issue open then is appropriate. 

Can I ask *why* you're trying to do administer the EKS cluster with SSO credentials instead of using the vended role that CDK creates during cluster creation (assumable by the account principals)? After some more research, it seems that this behavior of creating a separate role to administer the cluster (and additionally, potentially scoping down the separate role that CDK creates for EKS administration) is a better practice. Just trying to understand what your use case is and how I can help.

**Comment by robertd** [comment]
Hi @pmkuny. I am using cdk to create an EKS cluster after assuming the proper roles, and by default I'm seeing this message... 

`Your current user or role does not have access to Kubernetes objects on this EKS cluster
This may be due to the current user or role not having Kubernetes RBAC permissions to describe cluster resources or not having an entry in the cluster’s auth config map.`

> Can I ask why you're trying to do administer the EKS cluster with SSO credentials instead of using the vended role that CDK creates during cluster creation (assumable by the account principals)?

Our gitlab runners have pre-created IAM roles that allow CDK to create EKS clusters for us. Unfortunately, we are not able to use CDK pipelines yet (not sure if EKS creation using EKS clusters would pick proper roles).

> After some more research, it seems that this behavior of creating a separate role to administer the cluster (and additionally, potentially scoping down the separate role that CDK creates for EKS administration) is a better practice.

Would you mind providing a cdk example on how to do this?

**Comment by NGL321** [comment]
Hey @robertd,

After looking through the comments I am having a hard time pinning down what is going on here. Out of consideration that this may be a problem with our EKS implementation I am going to treat it as a bug for now.

Could you provide an explicit sample of the code that is causing this error? Just a snippet of the resources responsible for this would be sufficient. Then I can dig a little deeper

**Comment by pmkuny** [comment]
Hi @robertd -

1. The reason you're seeing that error message in the Console is because, by default, the CDK uses a [CloudFormation Execution role](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) when deploying. Per the [documentation](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) here:
> When you create an Amazon EKS cluster, the AWS Identity and Access Management (IAM) entity user or role, such as a [federated user](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers.html) that creates the cluster, is automatically granted `system:masters` permissions in the cluster's role-based access control (RBAC) configuration in the Amazon EKS control plane.

That means that the CloudFormation execution role is the one getting administrator permissions to the cluster, not your SSO-vended credentials, which is why you're seeing that error message in the AWS Console saying that you don't have access to the cluster.

To get around this, CDK also creates a role [by default(see `masters_role`)](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_eks/Cluster.html) that is assumable by any principal in the account.  Additionally, a CloudFormation Output is generated that allows you to update your kubectl config with that role assumption (the names might be different, but here's an example):
```
aws eks update-kubeconfig --name InfrastructureCluster6F2DDFD7-e9c3d4982cb5418db407c5af74f892ec --region us-west-2 --role-arn arn:aws:iam::xxxxxxxxxx:role/AppStage-InfrastructureEk-InfrastructureClusterMas-FQ2JEKF3BTEC```

2. For your GitLab runners, you could do a couple things:
a. Role chain - assume the default `masters_role` that CDK creates for you from your GitLab IAM Role - potentially scope down the trust policy here so only the GitLab IAM Role can assume it. By default, the trust policy allows any principal in the same account to assume it.
b. Create an explicit IAM Role using the IAM Construct and pass it to `masters_role` property during cluster creation. Allow only GitLab Runners and cluster administrators the ability to assume this role.

I would actually support the idea that the default implicit role being created be locked down so that ONLY cluster administrators within your organization could access it. I would then follow the instructions [here](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) to add permissions to the cluster RBAC system for your GitLab Runner IAM Roles. In my opinion, using the default administrator role to run your Runners, instead of creating an explicit role for them and adding them to the cluster, is a security risk.

**Comment by robertd** [comment]
Thanks @pmkuny for the detailed overview. 🙌

**Comment by robertd** [comment]
@NGL321  I'm not doing really anything fancy.... Just creating an EKS cluster with a custom nodegroup.

```ts
...
const cluster = new Cluster(stack, 'eks', {
  vpc,
  version: KubernetesVersion.V1_21,
  defaultCapacity: 0,
  vpcSubnets: [{
    subnetType: SubnetType.PRIVATE_WITH_NAT,
  }],
  tags,
});

const nodegroup = new Nodegroup(stack, 'NodeGroup', {
  cluster,
  minSize: 0,
  desiredSize: 1,
  instanceTypes: [
    InstanceType.of(InstanceClass.M5, InstanceSize.LARGE),
  ],
});
```

**Comment by pahud** [comment]
When we deploy the EKS cluster like this:

```ts
const cluster = new eks.Cluster(this, 'EksCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_26,
      kubectlLayer: new KubectlLayer(this, 'KubectlLayer'),
      defaultCapacity: 0,
    });
```

A cluster [masterRole](https://github.com/aws/aws-cdk/blob/b885ece7285ebe8219dbe4d62ae80554bd657632/packages/aws-cdk-lib/aws-eks/lib/cluster.ts#L494) will be created which maps to `system:masters` in the RBAC roles.

When you see the error in the console:
<img width="918" alt="image" src="https://github.com/aws/aws-cdk/assets/278432/18c4ce0d-2164-424c-977c-c6110d096600">

This means your current viewing IAM identity is not listed in the `aws-auth` ConfigMap. 

We have some solutions here:

**Option 1:**

If you are viewing the console with an assumed role, add this role into the `aws-auth` system:masters by:

```ts
cluster.awsAuth.addMastersRole(your_assumed_role)
```

And make sure this role has `eks:*` policies attached.

**Option 2:**

Create a dedicated role only for console browsing that allows all account root principal to assume:

```ts
    const cluster = new eks.Cluster(this, 'EksCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_26,
      kubectlLayer: new KubectlLayer(this, 'KubectlLayer'),
    });

    // create a 2nd readonly master role
    const consoleAdminRole = new iam.Role(this, 'ConsoleReadOnlyRole', {
      assumedBy: new iam.AccountRootPrincipal,
    });
    consoleAdminRole.addToPolicy(new iam.PolicyStatement({
      actions: [
        'eks:AccessKubernetesApi',
        'eks:Describe*',
        'eks:List*',
    ],
      resources: [ cluster.clusterArn ],
    }));
    
    // add this role to system:masters RBAC group
    cluster.awsAuth.addMastersRole(consoleAdminRole)
    new CfnOutput(this, 'ConsoleReadOnlyReole', { value: consoleAdminRole.roleName })
```

Now in your EKS console top right corner drop down menu, click the `Switch Role` button, and enter the `Account`, `Role`, `Display name`. Hit the `Switch Role` button and you are all set!

<img width="562" alt="image" src="https://github.com/aws/aws-cdk/assets/278432/75e2bee6-ca79-4904-8d66-c6a3107257e5">

Make sure to switch back to your original identity when you leave the EKS console.
