### ISSUE TITLE
(cloudfront): V1 cloudfront origins reference in v2 cloudfront docs

### ISSUE THREAD

**Issue by claraberendsen** [aws/aws-cdk#18980]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront-readme.html#creating-a-distribution

### Describe your issue?

In the developer docs for v2 of the cdk it states: 
`Constructs to define origins are in the @aws-cdk/aws-cloudfront-origins module.`
This makes reference to v2 of the API, and has been replaced by it's own module on `aws-cdk-lib`. 
As expected this gives types errors on Typescript due to the mismatch of cdk libraries. 
That line should be removed or modified to point to the correct v2 reference.

**Comment by peterwoodworth** [comment]
There's an issue is that this is just plaintext in the readme of the cloudfront package. So if we change it to `aws-cdk-lib` it would be wrong for the v1 docs.

That said, v2 is the current version so that's what the docs should prioritize. This is a pretty simple issue to fix if you'd like to submit a PR 🙂 Check out [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started

**Comment by romaqo** [comment]
Hi @peterwoodworth  can I take this issue if it's still valid?
