### ISSUE TITLE
CHANGELOG.md to big to render

### ISSUE THREAD

**Issue by azatoth** [aws/aws-cdk#19063]
### General Issue

CHANGELOG.md to big to render

### The Question

The changelog file https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md has now become over 1MB in size, and will thus not longer be rendered by github.

I recommend archiving old entries.

### CDK CLI Version

N/A

### Language

Typescript

**Comment by tim-finnigan** [comment]
This is a rendering limitation on GitHub's end and since V1 is in maintenance mode this likely won't get prioritized. The workaround is to view the raw file from the link on that page. The V2 changelog is rendering and when it starts to approach the size threshold then the team may consider alternative approaches.
