### ISSUE TITLE
(aws-cdk-lib): CfnApi does not provide an apiId

### ISSUE THREAD

**Issue by dansalias** [aws/aws-cdk#19092]
### What is the problem?

As per the CDK v2 documentation, a custom API domain for a v2 API Gateway API can be created using the `CfnApiMapping` construct (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2.CfnApiMapping.html).

However this requires specifying an `apiId`, which is not an available property on a `CfnApi` resource (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2.CfnApi.html).

Thus it is currently impossible to create a v2 API with a custom domain using CDK v2.

### Reproduction Steps

```ts
import {
  aws_apigatewayv2,
} from 'aws-cdk-lib'

const api = new apigatewayv2.CfnApi(this, 'CfnApi', {
  protocolType: 'HTTP',
})
const mapping = new apigatewayv2.CfnApiMapping(this, 'CfnApiMapping', {
  apiId: '', // doesn't exist!
  domainName: 'example.com',
  stage: '$default',
})
```

### What did you expect to happen?

A `CfnApi` resource should provide an `apiId` property to support custom mappings.

### What actually happened?

Currently no `apiId` property exists.

### CDK CLI Version

2.13.0

### Node.js Version

14

### OS

Linux

### Language

Typescript

**Comment by ryparker** [comment]
Hey @dansalias 👋🏻 

After taking a look at the docs for `AWS::ApiGatewayV2::Api` it looks like you can derive the ApiId from the APi's logical id using Ref. So you should be able to do the same using CDK.

i.g.
```ts
const apiId = new CfnRefElement(this, api.logicalId)
```

_[CFN docs: return value of API](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-apimapping.html#aws-resource-apigatewayv2-apimapping-return-values)_
_[CDK docs: CfnRef](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CfnRefElement.html)_
_[CDK docs: `CfnApi`'s `logicalId` prop](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2.CfnApi.html#logicalid)_

I don't believe this is a bug since this is an L1 construct and it seems to match the same implementation as CloudFormation. I'll close this for now but feel free to re-open if you believe otherwise.

**Comment by hoegertn** [comment]
api.ref should do the same
