### ISSUE TITLE
(lambda): Can't use `.grantInvoke` with an iam.Group

### ISSUE THREAD

**Issue by ramblingenzyme** [aws/aws-cdk#19205]
### What is the problem?

![image](https://user-images.githubusercontent.com/5336472/156269499-df84f500-20ad-4f77-ac6f-8479f8bfd1e5.png)

Using the `IFunction` method `.grantInvoke` throws an error when passed a group. Presumably this is attempting to add to the Lambda resource policy as well as the Group policies.

### Reproduction Steps

![image](https://user-images.githubusercontent.com/5336472/156269301-d7b26573-046e-4a4d-bfca-7434f46e4aa9.png)

```ts
const lambdaArn = `arn:aws:lambda:${Aws.REGION}:${Aws.ACCOUNT_ID}:function:${lambdaName}`;
    const lambdaFn = lambda.Function.fromFunctionArn(
      this,
      `${lambdaName}Lookup`,
      lambdaArn
    );

    lambdaFn.grantInvoke(group);
```

### What did you expect to happen?

One of the following:
* A Typescript error that doesn't allow a Group to be passed to `.grantInvoke()`
* or a change to the implementation so a Group is a valid

### What actually happened?

```
Error: Cannot use an IAM Group as the 'Principal' or 'NotPrincipal' in an IAM Policy
    at PolicyStatement.validatePolicyPrincipal (/workspaces/infrastructure/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.ts:180:13)
    at PolicyStatement.addPrincipals (/workspaces/infrastructure/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.ts:151:12)
    at new PolicyStatement (/workspaces/infrastructure/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.ts:86:10)
    at Function.addToPrincipalOrResource (/workspaces/infrastructure/node_modules/aws-cdk-lib/aws-iam/lib/grant.ts:138:23)
    at Import.grantInvoke (/workspaces/infrastructure/node_modules/aws-cdk-lib/aws-lambda/lib/function-base.ts:353:25)
```

### CDK CLI Version

2.13.0 (build b0b744d)

### Node.js Version

v16.14.0

### OS

Linux

### Language

Typescript

### Language Version

typescript@4.5.5

**Comment by austinatchley** [comment]
I tried to follow the same steps (creating an IAM Group, adding `invokeFunction` on the Group permissions, and adding the Group to the Lambda resource policy) through the AWS Console and was met with an error:

```
The provided principal was invalid. Please check the principal and try again
```

Also, the input box asks for "The ARN for an account, user, or role" only, so I'm assuming that using a Group here isn't actually supported. I will look into the former option, throwing a Typescript error that doesn't allow a Group to be passed to `.grantInvoke()`

**Comment by ramblingenzyme** [comment]
@austinatchley is it possible for the implementation of the grantInvoke method to add policies to the Group instead of trying to add it to the Lambda's resource policy? Which is what I'm pretty sure is what I was attempting to do in the first place.

**Comment by austinatchley** [comment]
@ramblingenzyme My understanding is that both actions are necessary. I haven't gotten the time to dive deeper on this yet, but hopefully I will in the coming few weeks and I can give you a better answer

**Comment by kaizencc** [comment]
Welp, this one never got to me because it seems I was unassigned. As @austinatchley mentioned, you cannot add an IAM Group to `grantInvoke`, because lambda doesn't allow this. [Here](https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html) are the allowed IAM entities that can be granted access to your lambda. You're getting an intentional, synth-time error, which is pretty much the best we can do in this scenario. So I don't see any bug here.

Furthermore, the `grantInvoke` method is trying to add the IAM entity to the lambda's resource policy because that is what is necessary for the permissions to work as intended. Unfortunately, this sounds like a situation where what you're trying to do isn't supported. @ramblingenzyme is there something that can be provisioned in a non-CDK way that then cannot be done via CDK? If so, then I can investigate further.
