### ISSUE TITLE
@aws-cdk/core: Support microseconds in Duration

### ISSUE THREAD

**Issue by alicez0626** [aws/aws-cdk#19207]
### Description

The Duration class is missing support for microseconds - https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/duration.ts

### Use Case

We would like to be able to use `Duration.seconds(100).toMicroSeconds()` for example.

### Proposed Solution

In Duration class, implement these two methods:

```
static microseconds(amount: number): Duration;

toMicroSeconds(opts?: TimeConversionOptions): number;
```

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
What service will you be using them for?

**Comment by alicez0626** [comment]
> What service will you be using them for?

For CloudWatch alarm. We have some metrics emitted at microseconds level

**Comment by rix0rrr** [comment]
To be clear: there is no service that expects microsecond granularity input? Instead, you are writing a construct that accepts a `Duration`, and needs to render it out to microseconds, because the values emitted as a metric are emitted in microsecond unit?

Can you tell me why `duration.toMilliseconds() * 1000` isn't good enough?

**Comment by alicez0626** [comment]
@rix0rrr

To be more specific, I want to set up a Cloudwatch alarm with threshold `100000000`. For readability, I can either write it as `100_000_000`, or I would like to write it as `Duration.seconds(100).toMicroSeconds()`.

Using `duration.toMilliseconds() * 1000` seems like only a temporary solution. Is there any reason why Duration shouldn't have microsecond granularity?

**Comment by rix0rrr** [comment]
> Is there any reason why Duration shouldn't have microsecond granularity?

That feels like the wrong way to think about things. Features start out at -100 points, and need to be proven useful to be added. They are not free: they take time to develop, maintain and document. That needs to be weighed against the benefit they bring. In this case, my guess would be that the presence of a `toMicroseconds()` method would only benefit a few people. For this same reason, we don't have `toNanoseconds()`, `toPicoseconds()`, `toCenturies()` methods on them (you could say "well obviously *those* are preposterous!", but what's the difference between those and yours, really?)

Especially since the alternative is this function:

```ts
function toMicroseconds(d: Duration) {
  return d.toMilliseconds() * 1000;
}

# To be used as:
new MyConstruct(this, 'xyz', {
  threshold: toMicroseconds(Duration.seconds(100)),
});
```

Which is equally readable.

Abstractions and helpers don't have to exist in the CDK framework alone, you can make them yourself.
