### ISSUE TITLE
ALB Lambda Target Support

### ISSUE THREAD

**Issue by dbettin** [aws/aws-cdk#1921]
I am perhaps missing something, but I don't see support for Lambdas as an ALB target.

Please let me know if it is currently supported.

**Comment by sam-goodwin** [comment]
[`IFunction`]( https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/function-base.ts#L14) needs to be updated to implement [`IApplicationGroupTarget`](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts#L342)

Good discussion in SAM: https://github.com/awslabs/serverless-application-model/issues/721

**Comment by slipdexic** [comment]
New to the project, I would like to work on this.

**Comment by eladb** [comment]
@slipdexic yey! Feel free. No one is actively working on this.

**Comment by slipdexic** [comment]
Cool, I will start working on this.

**Comment by bweigel** [comment]
@slipdexic are you still working on this?

Also at anyone &rarr; What is the sensible way to do here, concerning the target group:
- add a new `LambdaTargetGroup` (introducing some duplication)
- implement the expected behavior inside `ApplicationTargetGroup`?

Also, since now `vpc` should be optional (or rather conditional) in `BaseTargetGroupProps` and `TargetGroupBase` how would you suggest going about the linting-error that enforces all optional property-Props needing to be optional themselves? Should that be solved with some kind of type-system trickery?

`constructor(scope: Construct, id: string, props: ApplicationTargetGroupProps)` &rarr; `constructor(scope: Construct, id: string, props?: ApplicationTargetGroupProps)`

**Comment by mitchlloyd** [comment]
Was looking at this today. Here are the issues I found:

1. As other noted, the value 'lambda' missing from enum type. Easy to work around with a type assertion.
2. Using `loadbalancerListener.addTargets` doesn't work because adding the target without a `protocol` or `port` will fail CDK validation with "Supply at least one of protocol and port". However adding a protocol or port fails Cfn validation with "Port cannot be specified for target groups with target type 'lambda'".

Here's the code I was using up to the point where I got stuck.

<details>

```ts
import cdk = require("@aws-cdk/core");
import lambda = require("@aws-cdk/aws-lambda");
import elbv2 = require("@aws-cdk/aws-elasticloadbalancingv2");
import ec2 = require("@aws-cdk/aws-ec2");

export class TheStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "Main");

    const fn = new lambda.Function(this, "API", {
      handler: "index",
      runtime: lambda.Runtime.NODEJS_10_X,
      code: new lambda.AssetCode("dist"),
      vpc
    });

    const fnAlias = new lambda.Alias(this, "Live", {
      version: fn.addVersion("1"),
      aliasName: "Live"
    });

    const lb = new elbv2.ApplicationLoadBalancer(this, "LoadBalancer", {
      vpc,
      internetFacing: false
    });

    const listener = lb.addListener("Listener", {
      port: 80,
    });
    listener.addTargets('Targets', {
      targets: [new LambdaALBTarget(fnAlias)]
    });
  }
}

class LambdaALBTarget implements elbv2.IApplicationLoadBalancerTarget {
  private fn: lambda.IFunction;

  constructor(fn: lambda.IFunction) {
    this.fn = fn;
  }

  attachToApplicationTargetGroup(
    targetGroup: elbv2.ApplicationTargetGroup
  ): elbv2.LoadBalancerTargetProps {
    return {
      targetType: "lambda" as elbv2.TargetType,
      targetJson: {
        id: this.fn.functionArn
      }
    };
  }
}
```
</details>

**Comment by hleb-albau** [comment]
Also, it is not possible to enable health-check (no such property, and it is disabled by default for lambda).
