### ISSUE TITLE
(aws_cdk.aws_autoscaling.Schedule): rate classmethod isn't present as it is in aws_applicationautoscaling.Schedule

### ISSUE THREAD

**Issue by nacitar** [aws/aws-cdk#19213]
### What is the problem?

(aws_cdk.aws_autoscaling.Schedule): rate classmethod isn't present as it is in aws_applicationautoscaling.Schedule

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_applicationautoscaling/Schedule.html#aws_cdk.aws_applicationautoscaling.Schedule.rate

The method linked there, from applicationautoscaling.Schedule doesn't have an equivalent in autoscaling.Schedule

You can work around this by using .expression() and passing in a string like "rate(15 minutes)", but using a Duration would be nicer obviously.

This started as a bug report, due to my confusion about both of those schedule classes existing, but this really should be a feature request now.

### Reproduction Steps

pip install aws-cdk.aws-autoscaling
```python
from aws_cdk import aws_autoscaling as autoscaling
autoscaling.Schedule.rate
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
# AttributeError: type object 'Schedule' has no attribute 'rate'
```
You can see that rate is missing.

### What did you expect to happen?

I expected .rate to exist.

### What actually happened?

.rate doesn't exist

### CDK CLI Version

2.1.0 (build e5b301f) but that isn't relevant

### Node.js Version

v14.17.6 but that isn't relevant

### OS

Linux but that isn't relevant

### Language

Python

### Language Version

3.8

**Comment by nacitar** [comment]
I just realized that I was confusing aws_autoscaling.Schedule with aws_applicaitonautoscaling.Schedule, and the method is not actually documented but missing.  The real documentation is here: https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_autoscaling/Schedule.html

And that doesn't mention rate.  So I guess this is effectively a feature request now to bring those to parity.

**Comment by NGL321** [comment]
Hey @nacitar,

Thanks for reaching out. This feels like a reasonable enhancement request, but is a little complicated as on the Cloudformation side, [Application Autoscaling](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationautoscaling-scalabletarget-scheduledaction.html) and [EC2 Autoscaling](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-as-scheduledaction.html) handle this inherently differently.

Since this is a QoL simplification and there is a clear workaround, if you need this feature the best/fastest way to see it would be to create a PR for it yourself.
