### ISSUE TITLE
(aws-iam): cdk deployment adds region to some service trust relationships

### ISSUE THREAD

**Issue by cauger-git** [aws/aws-cdk#19267]
### What is the problem?

We are using the CDK to deploy IAM service roles with trust relationships for AWS services. As we want the roles to be assumable from multiple regions, the trust relationships are therefore region-agnostic in the CDK code. But after deployment, the trust relationships for some of the services have been made region specific. So for example, the CDK code specifies codedeploy.amazonaws.com but after deployment, this has been changed to codedeploy.ca-central-1.amazonaws.com.

For us, two of the services in the trust relationships are affected by this: codedeploy and states

### Reproduction Steps

We are creating a service role with trust relationships for AWS services. For example:

service_role = iam.Role(
                    self, 
                    "ServicerRole", 
                    role_name=service_role_name, 
                    assumed_by=iam.CompositePrincipal(
                            iam.ServicePrincipal("athena.amazonaws.com"),
                            iam.ServicePrincipal("states.amazonaws.com"),
                            iam.ServicePrincipal("codedeploy.amazonaws.com"),
		.    .    .

### What did you expect to happen?

For all services listed in the trust relationships, we expect that they remain region-agnostic after deployment, exactly as they are specified in the CDK code.

### What actually happened?

For some of the services in the trust relationships, they end-up being deployed with region-specific values. For us, this happens for codedeploy and states, which after deployment are changed to:

codedeploy.ca-central-1.amazonaws.com
states.ca-central-1.amazonaws.com

### CDK CLI Version

2.11.0 (build f7148c5)

### Node.js Version

16.13.0

### OS

Windows

### Language

Python

### Language Version

3.10.2

**Comment by Chriscbr** [comment]
My understanding is this isn't a use case the AWS CDK currently supports, since CDK currently assumes the generated principal should be specific to a region where possible. When no region is specified, a "region-agnostic" value is generated in the CloudFormation template which should resolve to the correct one once you deploy to a region -- but this is different from providing the "global" version of a principal.

I _think_ the "global assumable role" use case is not natively supported because in practice many service principals do not have universal names, and it is expected that regional names should be used. (Thus, the CDK would have to provide an ever-changing list of principal names for different services and what regions they are valid in - in addition, without the user providing options, it wouldn't be clear whether they want to also include regions in the AWS GovCloud, etc.) This is my best effort understanding based on the information I've been able to gather. Related pull request: https://github.com/aws/aws-cdk/pull/17984

But for your use case, if the type of policy you want to create is valid CloudFormation, then it should be possible to generate it with the CDK.

The most generic way to do this would be to implement your own `IPrincipal`, though a simpler alternative might be to drop down to a lower level of the APIs, such as using a [CfnRole](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.CfnRole.html), or using escape hatches.

**Comment by rix0rrr** [comment]
The solution would be a `LiteralPrincipal` class, or something, that would escape the translation done by `ServicePrincipal`.

**Comment by polothy** [comment]
Hello - trying to fix this deprecation on `region` in `ServicePrincipal`, this is my code:

```python
    for region in regions:
        role.assume_role_policy.add_statements(
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=["sts:AssumeRole"],
                principals=[
                    iam.ServicePrincipal("codedeploy.amazonaws.com", region=region),
                ],
            )
        )
```

Use case: making a single role that can be used in a specific list of regions.

This seems reasonable based on what I'm seeing in the discussions because it can build the correct principal via region info stuffs.  I think I'll try the workaround and see if I can implement my own `IPrincipal`, but please let me know if I'm setting myself up for failure here.

**Comment by polothy** [comment]
Just incase this helps anyone, this removes the deprecation warning and produced no CloudFormation template changes (as desired):

```python
class RegionalServicePrincipal(iam.PrincipalBase):
    def __init__(self, service: str, region: str) -> None:
        super().__init__()
        self.service = service
        self.region = region

    @property
    def policy_fragment(self) -> iam.PrincipalPolicyFragment:
        # This code comes from ServicePrincipalToken which is defined in:
        # https://github.com/aws/aws-cdk/blame/master/packages/%40aws-cdk/aws-iam/lib/principals.ts
        principal = region_info.RegionInfo.get(self.region).service_principal(
            self.service
        )
        if not principal or principal == "":
            principal = region_info.Default.service_principal(
                self.service, self.region, core.Aws.URL_SUFFIX
            )
        return iam.PrincipalPolicyFragment({"Service": [principal]})

    def to_string(self) -> str:
        return f"ServicePrincipal({self.service})"
```
