### ISSUE TITLE
core: cfn-mapping should allow dashes in attribute name

### ISSUE THREAD

**Issue by alekitto** [aws/aws-cdk#19278]
### What is the problem?

The `Mappings` documentation here (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) states that the attribute key can only contain alphanumeric characters, but the examples show keys with region names with dashes (`eu-west-1`, `us-east-1`, ...)

This is supported by CloudFormation, but the `validateAlphanumeric` method in `CfnMapping` is now throwing an error [here](https://github.com/aws/aws-cdk/blob/a554412f7cebbe4ab1ac13bbdcd4ca9f2bcd10b4/packages/%40aws-cdk/core/lib/cfn-mapping.ts#L122).

### Reproduction Steps

Just try to create 

```ts
new CfnMapping(this, 'example-mapping', {
    lazy: true,
    mapping: {
        "RegionMap" : {
            "us-east-1"      : { "HVM64" : "ami-0ff8a91507f77f867"},
            "us-west-1"      : { "HVM64" : "ami-0bdb828fd58c52235"},
            "eu-west-1"      : { "HVM64" : "ami-047bb4163c506cd98"},
            "ap-southeast-1" : { "HVM64" : "ami-08569b978cc4dfa10"},
            "ap-northeast-1" : { "HVM64" : "ami-06cd52961ce9f0d85"}
        }
    }
})
```

### What did you expect to happen?

No error

### What actually happened?

Error:

```
    Attribute name 'us-east-1' must contain only alphanumeric characters.
```

### CDK CLI Version

2.15.0 (build 151055e)

### Framework Version

2.15.0

### Node.js Version

v14.18.3

### OS

macOS

### Language

Typescript

### Language Version

TypeScript 4.5.5

**Comment by rix0rrr** [comment]
The validation should only be applied to the second level

**Comment by kaizen3031593** [comment]
Hi @alekitto, I looked into this and the validation is only applied to the second level. What is happening is that the example given has an additional `RegionalMap` key that doesn't belong. What you want is:

```ts
new CfnMapping(this, 'example-mapping', {
    lazy: true,
    mapping: {
          "us-east-1"      : { "HVM64" : "ami-0ff8a91507f77f867"},
          "us-west-1"      : { "HVM64" : "ami-0bdb828fd58c52235"},
          "eu-west-1"      : { "HVM64" : "ami-047bb4163c506cd98"},
          "ap-southeast-1" : { "HVM64" : "ami-08569b978cc4dfa10"},
          "ap-northeast-1" : { "HVM64" : "ami-06cd52961ce9f0d85"}
    }
});
```

This will produce a mapping with name `example-mapping`, since the name is derived from the construct ID:

```yaml
Mappings:
  example-mapping:
    us-east-1:
      HVM64: ami-0ff8a91507f77f867
    us-east-2:
      HVM64: ami-0bdb828fd58c52235
    ...
```

For a similar example, see our docs on [Mapping](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/README.md#mappings). I'll think about how we might detect this sort of mistake because I see how it can be confusing.

**Comment by alekitto** [comment]
@kaizen3031593 Maybe I wasn't clear: dashes on second level weren't an error.
I'm trying to create a mapping to deploy lambda functions with different layer versions on different regions.

In my case the mapping is:

```
{
    "php-81": {
        "ca-central-1": "17",
        "eu-central-1": "17",
        "eu-north-1": "17",
        "eu-west-1": "17",
        "eu-west-2": "17",
        "eu-west-3": "17",
        "sa-east-1": "17",
        "us-east-1": "17",
        "us-east-2": "17",
        "us-west-1": "17",
        "us-west-2": "17",
        "ap-east-1": "6",
        "ap-south-1": "16",
        "ap-northeast-1": "16",
        "ap-northeast-2": "16",
        "ap-northeast-3": "6",
        "ap-southeast-1": "16",
        "ap-southeast-2": "16",
        "eu-south-1": "16",
        "af-south-1": "16",
        "me-south-1": "6"
    }
}
```

I've updated from CDK 2.2 (which worked correctly) to 2.15 (which throws an error)

**Comment by kaizen3031593** [comment]
@alekitto Can you share the code you're using, as well as the mapping part of the template? My response is to the example code you shared. That isn't how we expect the mapping to be configured, and I expect it to not work correctly. You are right that between CDK 2.2 and 2.15, we've introduced a validation step to ensure correct mapping configurations (so it would not have a synth time error before). The question now is whether this validation does not match the cloudformation rules it is meant to model.

**Comment by kaizen3031593** [comment]
To achieve the mapping you've shown, I expect the following to work:

```ts
new CfnMapping(this, 'php-81', {
    lazy: true,
    mapping: {
        "ca-central-1": "17",
        "eu-central-1": "17",
        "eu-north-1": "17",
        "eu-west-1": "17",
        "eu-west-2": "17",
        "eu-west-3": "17",
        "sa-east-1": "17",
        "us-east-1": "17",
        "us-east-2": "17",
        "us-west-1": "17",
        "us-west-2": "17",
        "ap-east-1": "6",
        "ap-south-1": "16",
        "ap-northeast-1": "16",
        "ap-northeast-2": "16",
        "ap-northeast-3": "6",
        "ap-southeast-1": "16",
        "ap-southeast-2": "16",
        "eu-south-1": "16",
        "af-south-1": "16",
        "me-south-1": "6"
    }
});
```

**Comment by alekitto** [comment]
I've published a part of the construct into this gist: https://gist.github.com/alekitto/68703e76f7d06ac840cc33c9d7fd599d

**Comment by alekitto** [comment]
@kaizen3031593 There is some proprietary code, so I can't share the whole construct, but I use this mapping to select the correct version of the correct layer for the selected region. It is now working on CloudFormation deploying it with cdk 2.2. Now I'm currently using a modified version of the `CfnMapping` construct to allow dashes.

**Comment by kaizen3031593** [comment]
@alekitto I know what's going on now! The key is that your mapping is "lazy". Lazy mapping will only render a "Mappings"
section in the synthesized CloudFormation template if some `findInMap` call is unable to
immediately return a concrete value due to one or both of the keys being unresolved tokens
(some value only available at deploy-time).

Your code _is_ an invalid mapping according to cloudformation, and when I tried deploying without `lazy:true`, I got a deploy time error from cloudformation: 

```bash
Template format error: Mappings attribute name 'ca-central-1' must contain only alphanumeric characters.
```

However, since you specified `lazy:true`, and none of your values are tokens, the mapping does not actually show up in the synthesized template (since the values are resolved during synthesis). Since it doesn't show up, it also passes `cdk deploy`.

Now comes the synth-time check I added, which breaks you because you aren't really using `CfnMapping` as a cloudformation map but rather just a synth-time, regular, map. You don't need a valid cfn mapping because it isn't showing up in the synthed template.

This isn't a use case I considered. There's two options for remediation. We can validate on non-lazy mappings only. The drawback is that while this fixes your use case, if you did have a lazy value in your map, you would suddenly face a deploy-time cloudformation error. This seems like a bad experience.

Or, we keep it as is. I _think_ you would be fine creating a regular TypeScript map, since this really isn't a "CfnMapping" you're creating. Or you can remake your mapping to conform to the cloudformation requirements. The usual recommendation is to map the "first level" as the region. Something like:

```ts
new CfnMapping(this, 'MyMap', {
    lazy: true,
    mapping: {
        "ca-central-1": {
            "php18": "17",
            "php18fm": "17",
        },
        "eu-central-1": {
            "php18": "17",
            "php18fm": "17",
        },
    }
});
```

I'll update when I figure out the direction we're going to take. My gut tells me that unfortunately we're not going to fix your use case because it relies on a bug that we want to fix for both lazy and non-lazy mappings. But I will double check to make sure.
