### ISSUE TITLE
(lambda): VersionOptions do not apply correctly

### ISSUE THREAD

**Issue by a-farrukh** [aws/aws-cdk#19308]
### What is the problem?

Setting a function's `currentVersionOptions` has no effect in the Java SDK for CDK in the lambdas module.

### Reproduction Steps

```
        return Function.Builder.create( this, functionId )
                               .handler( handler )
                               .code( Code.fromAsset( codeUri ) )
                               .runtime( Runtime.JAVA_11 )
                               .memorySize( 256 )
                               .architecture( Architecture.X86_64 )
                               .timeout( Duration.seconds( 30 ) )
                               .currentVersionOptions( VersionOptions.builder().provisionedConcurrentExecutions( 2 ).build() )
                               .initialPolicy( policyStatements )
                               .environment( env )
                               .build();
```

### What did you expect to happen?

I expect the number of provisioned instances to be 2. for my function.

### What actually happened?

When I check the web interface, and also with `cdk diff`, nothing changes.
However, if I add a description to the function, or change the timeout/memory, that works all well and good and the changes apply.

It is just the `VersionOptions` that has no effect, whether I add a description, or change the number of provisioned concurrent executions to the builder of `VersionOptions`.

### CDK CLI Version

2.15.0 (build 151055e)

### Node.js Version

8.1.0

### OS

Ubuntu 20.04.3 LTS

### Language

Java

### Language Version

openjdk 11.0.12 2021-07-20 OpenJDK Runtime Environment 18.9 (build 11.0.12+7) OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)

**Comment by kaizen3031593** [comment]
Hi @a-farrukh! I think this has to do with understanding how provisioned concurrency works and what `currentVersion` is in CDK context. 

Provisioned concurrency on lambda is tied to a specific version (or alias) of a function, not the function itself ([source](https://aws.amazon.com/blogs/aws/new-provisioned-concurrency-for-lambda-functions/). So we shouldn't expect changing provisioned concurrency to modify the function resource at all (true for all `currentVersionOptions` properties).

`currentVersionOptions` specifies options you can set on the function _version_. `currentVersion` is actually a CDK specific abstraction that allows for you to access the "current version" of the function as a property of the function. You can access it like this (in TS since I'm not strong in java):

```ts
const fn = lambda.Function(this, 'fn', {...});
const myVersion = fn.currentVersion;
```

It is in `fn.currentVersion` that you should find your provisioned concurrency (as well as other `currentVersionOptions` you may set). The `versions` sections of our lambda java [docs](https://docs.aws.amazon.com/cdk/api/v2/java/index.html) should have more java-specific examples.

Let me know if that makes sense and helps, or if you have any follow up questions!

**Comment by a-farrukh** [comment]
All sounds good, thank you.

**Comment by a-farrukh** [comment]
Reopening for label tracking (apologies)

**Comment by kaizen3031593** [comment]
Not sure why this needs reopening :). Closing for now, can reopen if you make me understand what label tracking is.
