### ISSUE TITLE
(assertions): App-wide assertions

### ISSUE THREAD

**Issue by plumdog** [aws/aws-cdk#19389]
### Description

I have an app that contains lots of stacks. I would like to be able to write a test a bit like:
```typescript

import { buildMyApp } from '../src/myApp';

test('forbid public s3 buckets', () => {
    const app: cdk.App = buildMyApp();

    // assert that nowhere in the app are there any s3 buckets that allow public s3 access, ie check that they all have the following:
    // publicAccessBlockConfiguration: {
    //  "blockPublicAcls": true,
    //  "blockPublicPolicy": true,
    //  "ignorePublicAcls": true,
    //  "restrictPublicBuckets": true
    // }
});
```

Also, to test that all S3 buckets have encryption at rest set, for example.

### Use Case

To catch misconfigurations without writing any new tests.

Also, to allow high-level tests for apps, rather than stacks.

### Proposed Solution

My workaround involves recursing through `app.node.children`, finding everything with `cfnResourceType === 'AWS::S3::Bucket'`, and making assertions against those. This works in my case because the value are all static and there's not tokens to worry about.

Either:
- Is there a way of iterating over the `cdk.Stack` objects for a `cdk.App`? I found that `app.synth()` did returns stacks, but not the right kind of stack because they're CloudArtifact stacks
- Is there a different way of generating `Template` objects (https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_assertions.Template.html) from a `cdk.App`?
- Something else?

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
I can see the value in this though our `Assertions` module is pretty stack-specific right now. But I feel like the workaround is there, in exactly what you've described. I don't think we can assert against tokens anyway, since they are deploy-time properties.

You can create a `Template` object 3 ways: `fromStack()`, `fromJSON()`, and `fromString()`. It's totally fine to `synth` first and then create a `Template`; that is actually what `fromStack()` is doing under the hood. In fact, look at what `toTemplate` is doing for inspiration:

https://github.com/aws/aws-cdk/blob/6bd9fe23ddc880e05a00bd0657cb04f59263b100/packages/%40aws-cdk/assertions/lib/template.ts#L232-L244
