### ISSUE TITLE
CfnDeliveryStream.HttpEndpointConfigurationProperty: Requires string access key

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#19412]
### General Issue

Parameter requires secret value declared in plain text

### The Question

The `CfnDeliveryStream.HttpEndpointConfigurationProperty` construct requires a string [access key](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_kinesisfirehose/CfnDeliveryStream.html#aws_cdk.aws_kinesisfirehose.CfnDeliveryStream.HttpEndpointConfigurationProperty.access_key) to passed in. I know there's probably nothing the CDK team can do about it (outside of a custom resource) until the Firehose team allows a Secret Manager secret as a param. But given that this CDK construct won't work until that's added (without jumping through some CFN Param hoops), I figured I'd post the issue. 

### CDK CLI Version

2.15.0

### Language

Python

### Other information

How to fix: Tell the Firehose team to allow a Secret Manager ARN instead of requiring that the access key be passed directly.

**Comment by peterwoodworth** [comment]
Hey @automartin5000,

since this is on the CloudFormation end of things that means we can't do anything about this - this issue would be better suited for the [CloudFormation coverage road map](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues)

Unfortunately I can't transfer issues over to there, so let me know and I can create the issue there for you if you don't want to create it yourself. Just let me know 🙂
