### ISSUE TITLE
Make awslint publicly available

### ISSUE THREAD

**Issue by pgarbe** [aws/aws-cdk#1942]
It would be nice if you could make `awslint` public available as npm package, so that other people who want to publish CDK libraries can also benefit from it and design their libs also according to the [AWS Resource Construct Design Guidelines](https://github.com/awslabs/aws-cdk/blob/master/design/aws-guidelines.md).

**Comment by eladb** [comment]
Sure, that should be fairly easy to do

**Comment by eladb** [comment]
Note: this is taking a bit longer to do because currently awslint is tightly coupled with the CloudFormation model, so there is no real value in running it on anything else. The idea is the move some of the rules so they will apply to *any* construct and then it makes total sense to reuse

**Comment by eladb** [comment]
Still releavnt

**Comment by ddneilson** [comment]
+1 Please do this. My team is working on a Construct library, and we currently have awslint copied into our repo. Would be nice to consume a package instead of having to keep our copy up to date.

**Comment by workeitel** [comment]
I don't see any major blocker from running awslint against another repository anymore. With [CloudFormation registry](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/registry.html) everybody can build CloudFormation resources and build CDK constructs on top.

Some minor changes required:

* [ ] Make it a separate package. I suggest moving it to `packages/awslint` and keep the name? Not scoping it to `@aws-cdk/` namespace
* [ ] The namespace for guessing L1 constructs is hard-coded ([code](https://github.com/aws/aws-cdk/blob/master/tools/awslint/lib/rules/resource.ts#L278)). That me means **all L2 constructs need to be marked with `@resource` annotation**. That was hard-coded before as well but now works since CDK v1.37.0 ([PR](https://github.com/aws/aws-cdk/pull/7736)) generic
* [ ] The module-name linter enforces a module name pattern @aws-cdk/aws-<namespace> ([code](https://github.com/aws/aws-cdk/blob/master/tools/awslint/lib/rules/module.ts#L24)). First of all the namespace `@aws-cdk/` can’t be used by any project. But also the naming for `aws-<namespace>` would not work for all. Not optimal but **the rule can be disabled manually for now when consuming awslint**.
* [ ] The `no-unused-type` linter only runs on @aws-cdk/aws- packages ([code](https://github.com/aws/aws-cdk/blame/master/tools/awslint/lib/rules/no-unused-type.ts#L5-L8)).
