### ISSUE TITLE
Codecommit repository should use default branch 

### ISSUE THREAD

**Issue by foscraig** [aws/aws-cdk#1943]
CodeCommit has a default branch if you get the repository. Right now something like CommonPipelineSourceActionProps has a default branch of `master` but it should be able to reflect the actual default or provide such a facility.

**Comment by skinny85** [comment]
@sam-goodwin is this about the CodePipeline CodeCommit source action, or the CodeCommit repository construct?

**Comment by skinny85** [comment]
Hi @foscraig ,

the issue is that the `branchName` parameter is [required in the CodePipeline configuration for the CodeCommit action](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeCommit.html#action-reference-CodeCommit-config). So, if you're using a default branch other name `master`, you will have to override it in the action. Sorry about that, but there's nothing the CDK can do here (we have no way of discovering a repository's default branch).

Please re-open if there's anything else we can do for you here.

Thanks,
Adam

**Comment by foscraig** [comment]
> we have no way of discovering a repository's default branch

Why not? Shouldn't you be able to know the HEAD of the branch in question or is this because of the difference between the actual resource and token resources CDK creates when synthesizing?

**Comment by skinny85** [comment]
> > we have no way of discovering a repository's default branch
> 
> Why not? Shouldn't you be able to know the HEAD of the package in question or is this because of the difference between the actual resource and token resources CDK creates when synthesizing?

I'm not sure what you mean by "package" here. But the default branch of a CodeCommit repository is not information that is available to the CDK at build time, and templates generated by the CDK should not depend on external information that requires a service call to obtain. Even if we used our context provider mechanism for this, this is a mutable property, meaning somebody can change it on the repo, but we would still use the old, now incorrect, value. So I don't see a good way out of this.

**Comment by foscraig** [comment]
Makes sense. Thanks!
