### ISSUE TITLE
(module name): Update @aws-cdk/aws-timestream to CDK v2

### ISSUE THREAD

**Issue by overheat** [aws/aws-cdk#19485]
### Description

[@aws-cdk/aws-timestream](https://www.npmjs.com/package/@aws-cdk/aws-timestream) is still v1.x.x, which show error in CDK v2 application.

```
this: this
Argument of type 'this' is not assignable to parameter of type 'Construct'.
  Type 'Cdkv2SamLambdaRustStack' is missing the following properties from type 'Construct': onValidate, onPrepare, onSynthesize, validate, and 2 more.
```

Looks those onValidate, onPrepare, onSynthesize are deprecated API for CDK v2.

### Use Case

Time series database.

### Proposed Solution

Upgrade it.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
Hi @overheat. The `@aws-cdk/aws-timestream` module is the v1 module. In v2, we have bundled all stable modules under `aws-cdk-lib`. Since `timestream` only has L1 constructs, you should find that you don't need any additional imports, and instead can find them under:

```ts
import * as ts from 'aws-cdk-lib/aws-timestream';
```

Let me know if that's not the case!
