### ISSUE TITLE
(s3): Misplaced Example in Bucket (construct)

### ISSUE THREAD

**Issue by clifflu** [aws/aws-cdk#19551]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html#example

### Describe your issue?

The first example given in `class Bucket (construct)` ([v1](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-s3.Bucket.html#example), [v2](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html#example)),  seems to be taken from `codebuild` ([doc: codebuild.Overview.Image](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild-readme.html#images), [src: README.md](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-codebuild/README.md?plain=1#L313)) and irrelevant to S3 Bucket.

<img width="867" alt="Screen Shot 2022-03-25 at 11 14 59" src="https://user-images.githubusercontent.com/1589313/160047255-f0c6f2e8-c108-44a1-8ee2-a8416e548c58.png">

**Comment by rix0rrr** [comment]
This happens because the given construct does not have an example associated with it. We have a process that searches for a representative code sample across the code base and includes it.

If you feel the example is not a good one, you can add a better one by adding an `@example` tag to the class' docstring and writing your example there.

**Comment by peterwoodworth** [comment]
Closing as duplicate
