### ISSUE TITLE
(aws-lambda): Function property is possibly undefined - but why

### ISSUE THREAD

**Issue by markussiebert** [aws/aws-cdk#19598]
### What is the problem?

The property role is optional for Functions, but is there any case where it is unset?

```ts
  /**
   * Execution role associated with this function
   */
  public readonly role?: iam.IRole;
```

and initialised in the constructor with

```ts
    this.role = props.role || new iam.Role(this, 'ServiceRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies,
    });
    this.grantPrincipal = this.role;
```

So is there any case where role can be undefined? It is passed to grantPrincipal after assignment or creation... and grantPrincipal is not optional...

If often create lambdas and later on pass Policies to the role and every time I do this, i have to use the ! to access the role, because it's optional and maybe undefined (what never will happen?)

### Reproduction Steps

... not necessary ...

### What did you expect to happen?

the role should not be optional

### What actually happened?

it's optional

### CDK CLI Version

all

### Framework Version

all

### Node.js Version

all

### OS

all

### Language

Typescript

### Language Version

all

**Comment by peterwoodworth** [comment]
This has to be set as optional because the Function construct extends the [FunctionBase class](https://github.com/aws/aws-cdk/blob/431fa03c26677d490aea3a30a02b8ed25274d725/packages/%40aws-cdk/aws-lambda/lib/function-base.ts#L212), which requires `role` to be optional due to the [Lambda Function Import class](https://github.com/aws/aws-cdk/blob/431fa03c26677d490aea3a30a02b8ed25274d725/packages/%40aws-cdk/aws-lambda/lib/function.ts#L476) extending FunctionBase as well.

Hope this helps 🙂

**Comment by mikesmit** [comment]
I (maybe) get that IFunction needs role to be optional, but if you do a search for .role? on actual user code... how much of that is completely unnecessary and confusing code written on the concrete Function class. Is there a reason it needs to be optional on Function?
