### ISSUE TITLE
ElasticBeanstalk: Configuring target groups automatically created

### ISSUE THREAD

**Issue by rnowif** [aws/aws-cdk#1975]
Hi,

I would like to edit the options (specifically the `slowStart`) of a target group that has been automatically  created upon creation of an ElasticBeanstalk environment. Since it has been generated, I don't have the arn in my CDK code so I can't just import it.

Is there an option that I can pass to the EB environment to alter this target group or somehow retrieve a reference to it? I already searched in this doc https://docs.aws.amazon.com//elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkenvironment without success.

Thank you very much for the help!

**Comment by NGL321** [comment]
Hi @rnowif,

I am so sorry no one got back to you on this. I wanted to check in to see if you are still investigating this?

My initial thought is that your best bet is to use the relevant AWS SDK (based on your choice of language) to interface with EB rather than the CDK (most CDK actions happen during generation, especially with our L1 constructs).
However, if you are still unsure, I can investigate this further.

Cheers
😸

**Comment by SomayaB** [comment]
I will close this issue for now since there hasn't been any activity on it for a while. Please feel free to reopen.
