### ISSUE TITLE
cdk: ModuleNotFoundError: No module named 'aws_cdk.aws_s3'

### ISSUE THREAD

**Issue by hank-opalai** [aws/aws-cdk#19809]
### Describe the bug

Duplication process:
```
(.venv) (base) ahande-MBP:aws_cdk ahan_lee$ cdk synth
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from aws_cdk.aws_cdk_stack import AwsCdkStack
  File "/Users/ahan_lee/Desktop/MBA/Career/Intern/OPAL_AI/AWS/aws_cdk/aws_cdk/aws_cdk_stack.py", line 1, in <module>
    import aws_cdk.aws_s3 as s3
ModuleNotFoundError: No module named 'aws_cdk.aws_s3'
```

Version info:
Python 3.8.8
```
(.venv) (base) ahande-MBP:aws_cdk ahan_lee$ cdk --version
1.152.0 (build 9487b39)

(.venv) (base) ahande-MBP:aws_cdk ahan_lee$ pip list|grep aws
aws-cdk.aws-events            1.152.0
aws-cdk.aws-iam               1.152.0
aws-cdk.aws-kms               1.152.0
aws-cdk.aws-s3                1.152.0
aws-cdk.cloud-assembly-schema 1.152.0
aws-cdk.core                  1.152.0
aws-cdk.cx-api                1.152.0
aws-cdk.region-info           1.152.0

(.venv) (base) ahande-MBP:aws_cdk ahan_lee$ npm --version
8.6.0

(.venv) (base) ahande-MBP:aws_cdk ahan_lee$ node -v
v16.14.0
```

file in aws_cdk_stack.py
```python
import aws_cdk.aws_s3 as s3

# For consistency with other languages, `cdk` is the preferred import name for
# the CDK's core module.  The following line also imports it as `core` for use
# with examples from the CDK Developer's Guide, which are in the process of
# being updated to use `cdk`.  You may delete this import if you don't need it.
from aws_cdk import core


class AwsCdkStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # The code that defines your stack goes here

        # example resource
        # queue = sqs.Queue(
        #     self, "AwsCdkQueue",
        #     visibility_timeout=cdk.Duration.seconds(300),
        # )
```

### Expected Behavior

Module is imported 

### Current Behavior
```
ModuleNotFoundError: No module named 'aws_cdk.aws_s3'
```
### Reproduction Steps
```
(.venv) (base) ahande-MBP:aws_cdk ahan_lee$ cdk synth
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from aws_cdk.aws_cdk_stack import AwsCdkStack
  File "/Users/ahan_lee/Desktop/MBA/Career/Intern/OPAL_AI/AWS/aws_cdk/aws_cdk/aws_cdk_stack.py", line 1, in <module>
    import aws_cdk.aws_s3 as s3
ModuleNotFoundError: No module named 'aws_cdk.aws_s3'
```

### CDK CLI Version

1.152.0 (build 9487b39)

### Node.js Version

v16.14.0

### OS

MacOS Big Sur 11.4

### Language

Python

### Language Version

3.8.8

**Comment by NGL321** [comment]
Hey @hank-opalai,

I have verified that this isn't a bug, so you are likely either improperly configuring your python environment, or improperly importing the s3 module. Your import statement looks fine itself, therefore it is probably an environment issue. Based on the provided outputs, it also seems as though you are properly executing synth from your virtual environment.

Since it seems you do not yet have extensive code written, I recommend you try to reinitialize your project environment from scratch and reexecute. If that is not possible, remove all your venv artifacts and reinitialize that alone.

Please let me know if this helps!

**Comment by hank-opalai** [comment]
Hey @NGL321 ,

I've removed all the virtual environment and re-initialized CDK but got the same error below,

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from aws_cdk.aws_cdk_stack import AwsCdkStack
  File "/Users/ahan_lee/Desktop/MBA/Career/Intern/OPAL_AI/AWS/aws_cdk/aws_cdk/aws_cdk_stack.py", line 1, in <module>
    import aws_cdk.aws_s3 as s3
ModuleNotFoundError: No module named 'aws_cdk.aws_s3'

Can you help me through this problem? What additional info do you need?

**Comment by peterwoodworth** [comment]
Hey @hank-opalai, I'm not able to reproduce this error either.

I do suspect this has something to do with mismatching versions. Have you reran `pip install -r requirements.txt` since your last version upgrade?

You say you 're-initialized CDK', what steps did you take to do this?

I suggest a couple things. First, create a brand new project and see if you can reproduce this error. If you can, let me know what steps you took (they should be something pretty similar to what you see in our guide [here](https://cdkworkshop.com/30-python/20-create-project.html)) This will let me know if you're doing something wrong when setting up your project.

If you can't reproduce it, and you *need* your first project specifically to work, I would first recommend clearing your venv again and then reinstalling your packages. And if that doesn't work, I'd recommend to try [migrating to v2 ](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html)where these errors are far less common due to all CDK packages being from the same package `aws-cdk-lib`

Hope any of this helps!

**Comment by hank-opalai** [comment]
Hi @peterwoodworth ,

I mean re-initialized is that I removed all the folders and files and did CDK init again. Also, I created new Python venv but still got import error. Originall, I used CDK 2 but met the same issue. That's why I downgrade version to CDK 1.0

**Comment by hank-opalai** [comment]
Hey I've tried cdk init for typescript and it works. I think it's Python related issue and even I tried Cloud9 and I still got the same issue.

**Comment by peterwoodworth** [comment]
I wasn't able to reproduce this in Python @hank-opalai.

When starting a Python project, what are the steps you're taking when setting up your venv and installing your dependencies?

**Comment by hank-opalai** [comment]
Hey,

I've solved the issue. While I initilized the new python app, the folder created was named "aws_cdk".
When I used "cdk synth", the python link this folder rather the folder in .venv (as they had the same name), and didn't find the right packages. I'm not sure the folder name is by default as "aws_cdk", but after I change the folder name, the issue was resolved.

**Comment by peterwoodworth** [comment]
Ah, that's interesting! Are you creating the project inside a folder called `aws-cdk`? It looks like it based on the info from your first post 🙂 

I don't think there's anything we can do about this on our end - On your end though, creating a project in a folder called `aws-cdk` should be avoided and you'll be fine
