### ISSUE TITLE
cli: Allow changing endpoint to eg. localhost

### ISSUE THREAD

**Issue by MathiasKoch** [aws/aws-cdk#1989]
It would be awesome to be able to target another endpoint using the aws-sdk, in order to support deploying cdk synthesized cloudformation templates to local systems like https://github.com/localstack/localstack

It seems like this would be a fairly trivial change to implement, and i would be happy to provide the PR for this feature.

**Comment by SomayaB** [comment]
Hi @smilykoch, I apologize for the late reply. If you are still interested in this and would like to put in a PR we would absolutely appreciate the assistance and can make sure that gets merged as long as it's not a breaking change.

**Comment by smilykoch** [comment]
Sounds great! 

I will give it a swing, and return with a PR at some point. :+1:

**Comment by dancmeyers** [comment]
This would be great for us as well, so that we could run CDK deploys via [Teleport](https://goteleport.com/), once https://github.com/gravitational/teleport/pull/10025 gets merged in. What's the status of this? I can see there is a draft PR but it doesn't appear to have been touched for a while. Would the expectation be that a similar script to [aws-cdk-local](https://github.com/localstack/aws-cdk-local/) was run for Teleport?

**Comment by s0enke** [comment]
> [MathiasKoch](https://github.com/MathiasKoch) closed this as [completed](https://github.com/aws/aws-cdk/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) on Jun 22, 2023

@MathiasKoch could you point me/us out how this was completed? I can't find a merged PR referencing this issue.
