### ISSUE TITLE
(stepfunctions): log options include_execution_data default value is False

### ISSUE THREAD

**Issue by nichmorgan-loft** [aws/aws-cdk#20040]
### Describe the bug

In the docstring it describes that the include_execution_data argument has a default value of True, but after deploying the StateMachine the configured value is False.

### Expected Behavior

Argument include_execution_data be True when ignored.

### Current Behavior

Argument include_execution_data is False when ignored.

### Reproduction Steps

```python
machine = sfn.StateMachine(
           ...
            logs=sfn.LogOptions(
                ...
                include_execution_data=None,
            ),
        )
```

Check in aws console if Include execution data is equal to **NO**.

### Possible Solution

Fix the docstring of the class stating that the include_execution_data argument defaults to False.

### CDK CLI Version

2.21.0 (build 3f74a81)

### Node.js Version

v16.13.2

### OS

macOS Big Sur (11.6.1)

### Language

Python

### Language Version

Python (3.9.12)

**Comment by peterwoodworth** [comment]
Thanks for reporting this @nichmorgan-loft,

[The language from CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachine-loggingconfiguration.html#cfn-stepfunctions-statemachine-loggingconfiguration-includeexecutiondata) implies that when the field is undefined, then logging data will be included.

However, that's not what happens when this field is empty. By default logging data will be excluded, as both of us have found. I've opened a ticket for them to clear this documentation up. We can also adjust our documentation, all we have to do is change this here 🙂 
https://github.com/aws/aws-cdk/blob/7d90993cc67b5b6eed13cb83b5ab085b427a0005/packages/%40aws-cdk/aws-stepfunctions/lib/state-machine.ts#L68
Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started if you're interested
