### ISSUE TITLE
aws_cloud9: undescriptive error when creating CfnEnvironmentEC2

### ISSUE THREAD

**Issue by entest-hai** [aws/aws-cdk#20058]
### Describe the bug

I am creating a Cloud9 environment by a very simple CDK stack L1, but it failed and shown "client error" in CloudFormation console. I am using CDK **2.18.0**

### Expected Behavior

aws_cloud9 should successfully create a Cloud9 environment 

### Current Behavior

CloudFormation console show 
- CREATE_FAILED and Client Error 

### Reproduction Steps

Here is the simple stack 

```
import { aws_cloud9, Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';

export class Cloud9Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);


    // cloud9 environment
    new aws_cloud9.CfnEnvironmentEC2(
      this,
      'CdkAndAmplifyEnvironment',
      {
        instanceType: 't2.large',
        connectionType: 'CONNECT_SSM',
        automaticStopTimeMinutes: 30,
      }
    )

  }
}

```

### CDK CLI Version

2.18.0

### Framework Version

CDK

### Node.js Version

16.13.0

### OS

Ubuntu 18.04

### Language

Typescript

### Language Version

TypeScript 3.9.7

### Other information

Here is the package.json 
```
{
  "name": "cloud9",
  "version": "0.1.0",
  "bin": {
    "cloud9": "bin/cloud9.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "2.18.0",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-cdk/aws-cloud9": "^1.153.1",
    "aws-cdk-lib": "2.18.0",
    "constructs": "^10.0.0",
    "source-map-support": "^0.5.16"
  }
}

```

**Comment by peterwoodworth** [comment]
Hey @entest-hai,

I think this error is occurring because you are using the `CONNECT_SSM` connection type. I tested this out and found that changing this to `CONNECT_SSH` results in successful deployment.

But of course this doesn't help if you want to use SSM. I believe this error is occurring because due to how CloudFormation handles this under the hood, I'd assume it has the same functionality as it does [here as described in the Cloud 9 docs](https://docs.aws.amazon.com/cloud9/latest/user-guide/ec2-ssm.html#service-role-ssm)

> If you use this option, the `AWSCloud9SSMAccessRole` service role and `AWSCloud9SSMInstanceProfile` aren't automatically created

It then gives instructions on how to create those resources 🙂 

This error message should be better. Since this is a Cfn resource (L1 resource), this means that it is the exact same as the [CloudFormation resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud9-environmentec2.html). So, I'll raise this ticket with the CloudFormation team to give a better error message.

**Comment by entest-hai** [comment]
@peterwoodworth Thank you! I can't figure out why the same stack today works fine. So I would like to close this  issue.
