### ISSUE TITLE
(cli): Notices timeout works but uses the second catch

### ISSUE THREAD

**Issue by Kruspe** [aws/aws-cdk#20069]
### Describe the bug

As written in the comment and error message [here](https://github.com/aws/aws-cdk/blob/fd306ee05cfa7ebaa8d997007500d89d62868897/packages/aws-cdk/lib/notices.ts#L148-L154) we should not see the error but that is exactly what we are seeing.
The request is being terminated and the command does not hang anymore, but the error message says to open an issue, so here I am.

### Expected Behavior

Should not see the error message but instead use the timeout.

### Current Behavior

Forcefully shuts down the request.

### Reproduction Steps

Create a pipeline which uses the SelfMutate option and runs in a private subnet.

### CDK CLI Version

2.21.1
### Node.js Version

16.14.0

### OS

MacOS Monetery 12.3

### Language

Typescript

**Comment by peterwoodworth** [comment]
@rix0rrr bet you'd be interested in this 🙂

**Comment by gjohnson** [comment]
Also running into this _(well a customer is)_... Side note, shouldn't the [failsafe timer here](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/notices.ts#L152-L154) be cleared here via `clearTimeout` when the request is successful? Otherwise it's **always** going to run, no?

**Comment by rix0rrr** [comment]
Let's:

* Get rid of the `on('timeout')` and just rely on the `setTimeout()` timer
* `unref()` the result of `setTimeout()` so that it doesn't unnecessarily keep the CLI alive for 3 seconds.

> Otherwise it's always going to run, no?

Yes, but the only thing it will do is try to reject the `Promise`, which is either unresolved (in which case it should) or it has already resolved (in which case it will be a no-op). The only thing it might do at this point is keep the CLI alive for a bit too long, but we will resolve that by `unref()`fing the timer.
