### ISSUE TITLE
CDK Get Started guide leads to error: "Argument of type 'App' is not assignable to parameter of type 'Construct'."

### ISSUE THREAD

**Issue by kobenauf** [aws/aws-cdk#20161]
### Describe the issue

In [Module Three](https://aws.amazon.com/getting-started/guides/setup-cdk/module-three/) of the Get Started with AWS CDK guide, it has us create a `new App()` and pass it to the new stack we are instantiating:
```
const app = new cdk.App();
new CdkDemoStack(app, 'CdkDemoStack', {
```
This results in the following error:
```
Argument of type 'App' is not assignable to parameter of type 'Construct'.
  Type 'App' is missing the following properties from type 'Construct': onValidate, onPrepare, onSynthesize, validate, and 2 more.
```

### Links

https://aws.amazon.com/getting-started/guides/setup-cdk/module-three/

**Comment by kaizencc** [comment]
hi @kobenauf! Thanks for bringing that to our attention. The set up guide you referenced is outdated and uses CDK v1, while we recommend new users to get started with CDK v2. We actively update the [CDK Workshop](https://cdkworkshop.com/) and I believe you'll find a much better experience getting started with CDK there. Sorry for the confusion!

(the issue you're getting is most likely due to a dependency issue on the module `constructs`. CDK v1 depends on `constructs@3.x` while the latest on npm is `constructs@10.x`. You could pin the dependency to 3.x and that likely would solve your issue. but I 100% recommend following the CDK workshop instead, as that has the most up to date practices on how to CDK!)

**Comment by kobenauf** [comment]
Thank you for such a clear explanation and for pointing me to the CDK Workshop!
