### ISSUE TITLE
(aws-codepipeline-actions): CloudFormationCreateUpdateStackAction unable to update stack with nested stacks inside it

### ISSUE THREAD

**Issue by kieronjmckenna** [aws/aws-cdk#20191]
### Describe the bug

I am trying to set up a CDK Codepipeline for updating the cdk project itself, with the project being under one stack, and having multiple nested stacks in the constructor. The pipeline is in a second stack with the service stack passed in to access the name. I am using CloudFormationCreateUpdateStackAction to update the stack after I have run cdk synth and put the output in an artifact using codebuild.

This is able to update the stack if it is empty, or has some resources directly in it, however if there is a nested stack inside the service stack I get

S3: AccessDenied

for each of the nested stacks inside of the stack.

### Expected Behavior

I expect CloudFormationCreateUpdateStackAction to be able to update NestedStacks that are inside the stack being updated.

### Current Behavior

For each nested stack in the stack attempting to be updated cloudformation gives an error:

S3: AccessDenied

with no further information.

I have also turned on cloud trail for all S3 events, and I couldn't find any mention of an AccessDenied error on an S3 operation.

### Reproduction Steps

https://github.com/kieronjmckenna/cdk-pipeline-nested-stack-problem

Change GitHubSourceAction in lib/pipeline-stack.ts to fit whatever repo attempting to reproduce with, and change to the appropriate oauthtoken.

Push code to whatever repo GitHubSourceAction is using so that pipeline will run when deployed. 

Run

`cdk deploy --all`

Pipeline should run and attempt to update the service stack - creating the S3 Access Denied errors for the example nested stack in cloud formation.

### Possible Solution

If I run "cdk deploy ExampleServiceStackName" from my terminal with admin credentials the nested stacks are created/updated correctly, leading me to believe that there is something wrong with the IAM roles of codebuild or codepipeline here. But I don't know where to start as I have set adminPermissions to true in the CloudFormationCreateUpdateStackAction.

### Additional Information/Context

I have detailed more of what I have tried, and other StackOverflow posts I have read on this issue (and why their solutions haven't helped) in this StackOverflow post: 
https://stackoverflow.com/questions/72078267/cdk-codepipeline-cloudformationcreateupdatestackaction-getting-s3-access-denie?noredirect=1#comment127379830_72078267

### CDK CLI Version

2.22.0

### Framework Version

2.22.0

### Node.js Version

16.13.2

### OS

Mac Monterey

### Language

Typescript

### Language Version

3.9.10

**Comment by skinny85** [comment]
Hey @kieronjmckenna,

thanks for opening the issue. The problem that you're running into is that Nested Stacks are implemented in the CDK with something called [Assets](https://docs.aws.amazon.com/cdk/v2/guide/assets.html). Normally, `cdk deploy` takes care of deploying them for you, but since you're doing a pure CloudFormation deployment with the `CloudFormationCreateUpdateStackAction` here, they do not get deployed, and CloudFormation can't find the files in S3 that point to the contents of your Nested Stack (because they're not there).

The good news is that we have a higher-level module in the CDK, called [CDK Pipelines](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html), that allows you to deploy CDK application in CodePipeline, including with Asset support. Try it out, and it should solve your problem!

Thanks,
Adam

**Comment by kieronjmckenna** [comment]
@skinny85 thanks very much. I had a feeling I was using the wrong tool and much appreciated for pointing me in the right direction.
