### ISSUE TITLE
(stepfunctions): invoke rest api with path from input

### ISSUE THREAD

**Issue by florianbepunkt** [aws/aws-cdk#20252]
### Describe the bug

```ts
const callGetChannelApi = new sfnt.CallApiGatewayRestApiEndpoint(this, "Get channel", {
      api: adminApi,
      method: sfnt.HttpMethod.GET,
      stageName: "production",
      apiPath: sfn.JsonPath.format("/channels/{}", sfn.JsonPath.stringAt("$.channelId")), // << using a static string path works, this doesn't
      authType: sfnt.AuthType.IAM_ROLE,
      resultPath: "$.channel",
});
```

### Expected Behavior

Input path should be resolved.

### Current Behavior

CDK throws an error during deployment.

```
      throw new Error(`"path" must begin with a "/": '${path}'`);
```

### Reproduction Steps

```ts
import * as sfn from "aws-cdk-lib/aws-stepfunctions";
import * as sfnt from "aws-cdk-lib/aws-stepfunctions-tasks";

const callGetChannelApi = new sfnt.CallApiGatewayRestApiEndpoint(this, "Get channel", {
      api: adminApi,
      method: sfnt.HttpMethod.GET,
      stageName: "production",
      apiPath: sfn.JsonPath.format("/channels/{}", sfn.JsonPath.stringAt("$.channelId")),
      authType: sfnt.AuthType.IAM_ROLE,
      resultPath: "$.channel",
});

const processExportSm = new sfn.StateMachine(this, "Process exports SM", {
      definition: callGetChannelApi,
    });
```

### CDK CLI Version

2.23.0 (build 50444aa)

### Node.js Version

v16.10.0

### OS

MacOS X

### Language

Typescript

**Comment by kaizencc** [comment]
Thanks for opening the issue @florianbepunkt! Looks like the offending line is here:

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-stepfunctions-tasks/lib/apigateway/call-rest-api.ts#L60

We're calling `arnForExecuteApi` on the `apigateway.IRestApi` which is not equipped to handle `jsonPath`. Since `apigateway` should not need to know about `jsonPath`s, maybe the best way to fix this would be to recreate the `arnForExecuteApi` inside of `CallApiGatewayRestApiEndpoint` without the synth time checks.

**Comment by tezz-io** [comment]
@kaizencc can you review my PR #20294
