### ISSUE TITLE
(aws_cdk): Tags applied to App not inherited by Stage

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#20383]
### Describe the bug

If I apply a tag to an App, then Stacks that are within Stages within that app don't get tagged.

### Expected Behavior

Tags applied to an App should be applied to _all_ constructs recursively.

### Current Behavior

They aren't.

### Reproduction Steps

```python
    app = aws_cdk.App()
    aws_cdk.Tags.of(app).add('first', 'A')

    env = aws_cdk.Environment(region='us-east-1', account='xxxx')

    stage1 = aws_cdk.Stage(app, 'stage1', env=env)
    aws_cdk.Tags.of(stage1).add('second', '1')

    aws_cdk.Stack(stage1, 'stack1')
    aws_cdk.Stack(stage1, 'stack2')

    stage2 = aws_cdk.Stage(app, 'stage2', env=env)
    aws_cdk.Tags.of(stage2).add('second', '2')

    aws_cdk.Stack(stage2, 'stack1')

    app.synth()    
```

Then run `cdk deploy '**'`.
Go to CloudFormation in the console and note that none of the stacks include the `first` tag.

### CDK CLI Version

2.21.1 (build a6ee543)

### Node.js Version

16.14.2

### OS

Alpine 3.15

### Language

Python

### Language Version

3.9.12

**Comment by rix0rrr** [comment]
This behavior is by design:

![image](https://user-images.githubusercontent.com/524162/169826542-31b2d625-32ab-4fe0-a005-7d9939f1a46c.png)

https://docs.aws.amazon.com/cdk/v2/guide/aspects.html

**Comment by rix0rrr** [comment]
The design rationale is that a `Stage` needs to be fully synthesized and done before another part of the app. This is necessary because of CDK Pipelines: it needs to look at the stacks and everything contained in the Stage, and make decisions like what kinds of CodePipeline actions to generate.

In order to do that, it must not be the expectation that the constructs in the Stage (stacks and everything) can be modified at any point in time -- because if that was the expectation, those changes wouldn't (always) be applied, depending on time.

In order to not raise false expectations, we've said that routines likely to mutate resources at unpredictable times, like Aspects, are not allowed.
