### ISSUE TITLE
aws-lambda-nodejs: log group retention after manually deleting log group

### ISSUE THREAD

**Issue by florianbepunkt** [aws/aws-cdk#20453]
### Describe the bug

I deployed a lambda with a given log retention: `logRetention: logs.RetentionDays.ONE_DAY`After manually deleting the log group via console, and redeploying the cdk stack, the log group does not get recreated with the given retention setting.

Instead the log group is implicitly created when running the lambda, with a log retention of "never expire"

### Expected Behavior

The log group should be re-created with the correct retention settings.

### Current Behavior

The log group is not re-created. A log group is implicitly created, when running the lambda – but with a different retention setting (never expire).

### Reproduction Steps

The bug involves manual steps to be executed via console (see description above), so a self-contained example is not possible..

```ts
import { NodejsFunction } from "aws-cdk-lib/aws-lambda-nodejs";
import * as logs from "aws-cdk-lib/aws-logs";
import path from "path"

// CDK
const exampleFn = new NodejsFunction(this, "processCsvFn", {
  entry: path.resolve(__dirname, "handler.ts"),
  handler: "handler",
  logRetention: logs.RetentionDays.ONE_DAY,
});

// handler.ts
const handler = () => {
    return {body: "hello", status: 200}
}
```

### CDK CLI Version

2.24.1 (build 585f9ca)

### Node.js Version

v16.10.0

### OS

MacOS

### Language

Typescript

### Language Version

4.6.3

**Comment by corymhall** [comment]
@florianbepunkt this is expected behavior from CloudFormation. If you create resources with
CloudFormation you should never make manual changes to those resources because CloudFormation will
not know about those changes. CloudFormation does not keep any state on the current state of your
infrastructure so it will not try to "fix" any manual changes that have been made.

In this specific case the log retention is set via a custom resource so you should be able to
reapply the retention by:

1. Remove the `logRetention` property and deploy.
2. Add back the `logRetention` property and deploy.

**Comment by florianbepunkt** [comment]
@corymhall Thank you. This makes sense.
