### ISSUE TITLE
(assertions): make it possible to write CDK tests (e.g. Template.hasResourceProperties) to check that a DNS-validated certificate has been created

### ISSUE THREAD

**Issue by varnenec** [aws/aws-cdk#20485]
### Describe the feature

For developers who use `acm.DnsValidatedCertificate` in their stacks, provide a way to test for the presence of that certificate when writing unit tests using the CDK assertions library.

For example, if I have a definition like:
```typescript
export class MyStack extends Stack {
   // ... constructor code
   new DnsValidatedCertificate(this, 'DNSCert, props);
   // ... more code
}
```

then in my unit tests for `MyStack`, I should either be able to use:
* `Template.hasResource{Properties}` using a set of documented properties, or 
* `Template.findResource` and check for the presence of documented metadata, or 
* some other method

to confirm that my stack includes the certificate. 

### Use Case

My CDK stacks use `acm.DnsValidatedCertificate`, which is implemented via a custom resource. As a result, there is no good way to write a CDK test (a la `Template.hasResourceProperties`) to verify that my stack deployment will create the cert.

I can't just copy `DnsValidatedCertificate`'s own [unit tests](https://github.com/aws/aws-cdk/blob/v1.157.0/packages/%40aws-cdk/aws-certificatemanager/test/dns-validated-certificate.test.ts), because they effectively rely on implementation details that are not reflected in the public documentation.

### Proposed Solution

I'm not suggesting that the underlying implementation of `DnsValidatedCertificate` move away from using custom resources, but perhaps those custom resources could be annotated with tags or metadata in a publicly documented way, which would allow me to write a unit tests without assuming non-public implementation details.

There's already at least one metadata field in there - the `path` - which may form the basis of a solution:
```
Metadata:
      aws:cdk:path: MyStack/DNSCert/CertificateRequestorResource/Default
```

So maybe add:
```
     aws:cdk:custom-resource:purpose: certificate-requestor
```
?

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.156.1

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by peterwoodworth** [comment]
If I understand correctly, you'd like to add unit tests which verify that your certificate will be created, correct?

Since this is implemented with a custom resource, you want to check that both the custom resource handler (lambda function) and custom resource itself are created.

I think this is moreso a documentation issue rather than something we'd implement in our assertions library. We should be documenting which constructs of ours rely on custom resources, and be giving some key details on those underlying custom resources. I believe if we patch up our documentation, that writing unit tests (as well as some other issues) will become much easier for customers to handle on their own. Do you agree here?

**Comment by madeline-k** [comment]
The `DnsValidatedCertificate` construct has been deprecated and replaced: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.Certificate.html The new construct does not use custom resources. So, I believe this request is no longer needed. If you still have a request for assertions or the new construct after trying it out, please open another issue. Thanks!
