### ISSUE TITLE
python/cdk: cannot add a lifecycle rule to an IRepository object

### ISSUE THREAD

**Issue by saste** [aws/aws-cdk#20635]
### Describe the bug

I have this code:
```
ecr_repository = ecr.Repository.from_repository_name(self, "ecr-repository", ecr_repository_name)
ecr_repository.add_lifecycle_rule(tag_prefix_list=["mainline"], max_image_count=9999)
```

When I try to synth, I get this error:
```
AttributeError: '_RepositoryBaseProxy' object has no attribute 'add_lifecycle_rule'
```

This probably stems from the fact that `from_repository_name` returns an `ecr.IRepository`.

Using latest aws CDK v2.

### Expected Behavior

I would expect that `add_lifecycle_rule` should work.

### Current Behavior

cdk fails to synth.

### Reproduction Steps

Use some code like this:
```
ecr_repository = ecr.Repository.from_repository_name(self, "ecr-repository", ecr_repository_name)
ecr_repository.add_lifecycle_rule(tag_prefix_list=["mainline"], max_image_count=9999)
```

then run `cdk synth`.

### CDK CLI Version

2.24.1 (build 585f9ca

### Node.js Version

16.15.0

### OS

Windows

### Language

Python

### Language Version

3.10.4

**Comment by peterwoodworth** [comment]
You're right that this is because it's an [`IRepository`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ecr.IRepository.html). We only support this method for repositories which are not imported, you can see this because the method is not part of this interface

This is expected, and is actually how most of our import methods work since you cannot modify existing resources with CDK if they are not created in your stack.
