### ISSUE TITLE
aws-s3-notifications: addEventNotification creates new TopicPolicy instead of using the existing one

### ISSUE THREAD

**Issue by iriskraja77** [aws/aws-cdk#20661]
### Describe the bug

When I create an SNS Topic using **TopicPolicy**, calling **bucket.addObjectCreatedNotification(...)** will create a new TopicPolicy instead of using the existing one. Therefore, the existing TopicPolicy is overriden. 

### Expected Behavior

 Two Policy Statements are present in the SNS Topic policy.

### Current Behavior

Only one policy statement (added from S3 Notifications module) is present in the topic statement. 

### Reproduction Steps

Example code to reproduce: 

```
    const bucketName = `${this.account}-example-bucket`;

    const topic = new Topic(this, 'snsTopic', {});
    const topicPolicy = new TopicPolicy(this, 'snsTopicPolicy', {
      topics: [topic]
    });
    // add to the Topic Policy
    topicPolicy.document.addStatements(new PolicyStatement({
      actions: ['sns:Publish'],
      effect: Effect.DENY,
      resources: [topic.topicArn],
      principals: [new AnyPrincipal()],
      conditions: {
        'StringNotEqualsIfExists': {
          'aws:PrincipalServiceName': 's3.amazonaws.com',
        },
      }
    }))
    const bucket = new Bucket(this, 's3bucket', {
      bucketName
    });

    // Overwrites the topic policy instead of adding to it.
    bucket.addObjectCreatedNotification(new SnsDestination(topic));
```

### Additional Information/Context

The compiled CloudFormation template contains two resources for AWS::SNS::TopicPolicy, both linked to the SNS Topic. However the later one will replace the first one. 

### CDK CLI Version

2.23.0

### Node.js Version

14.15.0

### OS

MacOS

### Language

Typescript

**Comment by scanlonp** [comment]
I looked how this would be changed. Exposing `Topic.policy` (in sns/topic-base) and adding a line to the constructor of `TopicPolicy` (in sns/policy) to the effect of `props.topics.map(t => t.setPolicy(this));`. This does not feel clean to me since `addToResourcePolicy` takes care of all of this.

I think this is working as intended since it looks like your use case is covered by our recommended use patterns. Is there a use case that is not covered by `addToResourcePolicy()`? Unless you have any objections, I am going to close this.
