### ISSUE TITLE
(Glue::CfnTable): schemaReference to latest version

### ISSUE THREAD

**Issue by skinofstars** [aws/aws-cdk#20710]
### Describe the issue

Trying to link to a schema for a table is difficult. It's not clear how to link to say, just the latest version. Some doc might be nice.

For example

```js
storageDescriptor: {
  location: "mydb.public.users",
  schemaReference: {
    schemaId: {
      registryName: "default-registry",
      schemaName: "users",
    },
  },
},
```

"One of version number (or) latest version is required."

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_glue.CfnTable.SchemaReferenceProperty.html

**Comment by skinofstars** [comment]
May be related? But I solved this issue by locking my schema version using `scheckpointVersion`, then I coujld use `schemaVersionNumber` to whatever I set there.

ref https://stackoverflow.com/questions/72587700/aws-glue-finding-schema-reference-for-table/72595569

**Comment by kaizencc** [comment]
Hi @skinofstars! Our APIs prefixed `Cfn*` are generated (so is the documentation) and thus we don't have much control over the API. If you are unaware, we do have L2 (hand-written) constructs available for glue, though they are `experimental`. They live [here](https://www.npmjs.com/package/@aws-cdk/aws-glue-alpha) and likely have better documentation because we wrote it :).
