### ISSUE TITLE
aws_cloud9_alpha: Give user ability to specify image ID, and make default to use recommended Amazon Linux 2

### ISSUE THREAD

**Issue by sean-beath** [aws/aws-cdk#20908]
### Describe the feature

Implement a way for users to change the default image ID for their Cloud9 instance.
Further, default the image ID to be Amazon Linux 2 (amazonlinux-2-x86_64) aligning to recommendation from AWS.

This would allow a user to implement the following to specify Amazon Linux 2 as their EC2 image: 

```
cloud9_env = cloud9.Ec2Environment(self, "Cloud9Env",
            vpc=self.vpc,
            subnet_selection=ec2.SubnetSelection(
                        subnet_type=ec2.SubnetType.PUBLIC
            ),
            image_id="amazonlinux-2-x86_64"
)
```

### Use Case

I am not currently able to deploy a Cloud9 environment using the recommended image from AWS.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.25.0a0

### Environment details (OS name and version, etc.)

MacOS Big Sur 11.6.5

**Comment by jumic** [comment]
@corymhall
I've created a pull request to support parameter `imageId`.

Should we also change the default value to Amazon Linux 2 as requested? If yes, can we skip the feature flag because cloud9 is an experimental module? 

Without feature flag, we could just add this line to change the default behaviour.
```ts
imageId: props.imageId ? props.imageId : 'amazonlinux-2-x86_64',
```

I found this note in the [Cloud9 API](https://docs.aws.amazon.com/cloud9/latest/APIReference/API_CreateEnvironmentEC2.html#cloud9-CreateEnvironmentEC2-request-imageId) documentation:
> From July 1, 2022, the parameter for Amazon Linux will no longer be available when you specify an AMI for your instance. Amazon Linux 2 will then become the default AMI, which is used to launch your instance if no parameter is explicity defined.

Will the default value be also changed to Amazon Linux 2 in CloudFormation? In this case, we could close this issue after merging the PR.

**Comment by sean-beath** [comment]
@corymhall 
I created a different pull request incorporating comments from @jumic's PR.

The build is failing as this is a breaking change by making the imageId a mandatory field.

Apologies for the duplicate PR but I wanted to use this for my own learning so hopefully I can keep contributing. Please let me know if there is something I have missed.
