### ISSUE TITLE
(aws-cdk-lib/aws-eks): nodegroup instanceTypes does not accept tokens

### ISSUE THREAD

**Issue by rshad** [aws/aws-cdk#20914]
### Describe the bug

**CDK Version:** 2.20.0 (build 738ef49)

CfnParameter is not interpreted as expected in CDK synth or deploy

### Expected Behavior

The parameter should be interpreted as string.

### Current Behavior

```
<local-project-path>/cdk/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts:476
    throw new Error('Malformed instance type identifier');
          ^
Error: Malformed instance type identifier
    at isGpuInstanceType (<local-project-path>/cdk/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts:476:11)
    at typeToArch (<local-project-path>/cdk/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts:492:12)
    at Array.map (<anonymous>)
    at getPossibleAmiTypes (<local-project-path>/cdk/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts:499:69)
    at new Nodegroup (<local-project-path>/cdk/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts:370:26)
    at <local-project-path>/cdk/lib/stacks/k8s-nodegroup.ts:63:12
    at new K8snodegroups (<local-project-path>/cdk/lib/stacks/k8s-nodegroup.ts:84:8)
    at Object.<anonymous> (<local-project-path>/cdk/bin/cdk.ts:39:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (<local-project-path>/cdk/node_modules/ts-node/src/index.ts:1056:23)
```

When printing the value of the parameter I get:
```
${Token[TOKEN.423]}
```

### Reproduction Steps

I am trying to use a CfnParameter representing the value of an EC2 instance type but I get an error with Malformed instance type, as the CfnParameter is returning a none interpreted Token.

```
const nodeInstanceType = new CfnParameter(this, 'nodegroupInstanceType', {
    type: 'String',
    description: 'Instance Type to be used with nodegroup ng-1',
    default: 't3.small',
});

new ec2.InstanceType(${nodeInstanceType.valueAsString});
```

### CDK CLI Version

2.20.0 (build 738ef49)

### Node.js Version

v18.3.0

### OS

MacOs Monterey 12.4

### Language

Typescript

**Comment by peterwoodworth** [comment]
The value of your parameter will not be known until deploy time - see our [documentation on parameters](https://docs.aws.amazon.com/cdk/v2/guide/parameters.html#parameters_use)

What this means is that you will be able to get use out of the parameter only once its found in the template. If you depend on the value of the parameter for any synth time logic, synth will fail from trying to parse the token as actual data.

In this case, it seems we don't support the case where the machine image passed to a nodegroup is a token. Due to the line here, where it attempts to parse the instance type https://github.com/aws/aws-cdk/blob/0bad87b4b7f70a7a66b8a24bcf9786c429896eb0/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L473

Since this code is put in place to prevent users from mistakes and it depends on knowing the value at synth time, I think we should be able to skip this code if it detects that the instance type supplied is a token

**Comment by peterwoodworth** [comment]
That wouldn't make sense to me - what sort of deploy time failure are you getting? I would expect that that would be a separate error
