### ISSUE TITLE
(iam): principal conditions are not type-checked correctly

### ISSUE THREAD

**Issue by tenjaa** [aws/aws-cdk#20974]
### Describe the bug

When adding a permission to a lambda function, there is an error since CDK 2.30.0.
Adding a PrincipalWithConditions supports less conditions than before.

### Expected Behavior

I expect, that synthing the project still works fine like in the prior version.

### Current Behavior

When synthing the following error appears:
```
Error: PrincipalWithConditions had unsupported conditions for Lambda permission statement: [{"operator":"0","key":"StringEquals"}]. Supported operator/condition pairs: [{"operator":"ArnLike","key":"aws:SourceArn"},{"operator":"StringEquals","key":"aws:SourceAccount"},{"operator":"StringEquals","key":"aws:PrincipalOrgID"}]
```

### Reproduction Steps

```typescript
secretRotationFunction.grantInvoke(new ServicePrincipal('secretsmanager.amazonaws.com', {
      conditions: [
        {
          StringEquals: {
            'aws:SourceAccount': Accounts.MAIN.account,
          }
        }
      ]
    }));
```

### Additional Information/Context

I guess the responsible change is in `packages/@aws-cdk/aws-lambda/lib/function-base.ts` directly below line 596 / 643 in the diff: https://github.com/aws/aws-cdk/compare/v2.29.1...v2.30.0#diff-6cd0e14e946761622244e7c236ddb2c328b1881f050b1638897231ea27e5e62eR645.

### CDK CLI Version

2.30.0

### Node.js Version

18.2.0

### OS

OSX/CodeBuild

### Language

Typescript

**Comment by hutchy2570** [comment]
This problem also occurs when trying to create an API Gateway using the SpecRestApi construct with a Lambda handler.  Was working fine with 2.29.1.

Looks like it was introduced in 2.30.0 with https://github.com/aws/aws-cdk/pull/19975

**Comment by kaizencc** [comment]
Hi @tenjaa + @hutchy2570. Thanks for the report, confirmed the behavior on my end as well. In my mind, your code worked in the past due to a bug, #19975 fixed that bug, and the synth-time error that should have popped up before is now showing up. Let me explain.

Prior to #19975, we incorrectly checked if a principal had conditions: https://github.com/aws/aws-cdk/pull/19975#discussion_r861223519. That means your principal (which had conditions) was not actually passed through the synth-time condition checks at all. #19975 introduced correct logic for `isPrincipalWithConditions`. So now, your code passes synth time checks, of which it is flagged as incorrect. In particular, your value for `conditions` shouldn't have been accepted. `conditions` is typed this way: `conditions?: { [key: string]: any };` and even though arrays are valid objects we are not expecting to handle an array here (and we're expecting to alert you at synth time if the type is not supported).

Workaround is:

```ts
secretRotationFunction.grantInvoke(new ServicePrincipal('secretsmanager.amazonaws.com', {
  conditions: {
    StringEquals: {
      'aws:SourceAccount': Accounts.MAIN.account,
    },
  },
}));
```

While I'm definitely apologetic that fixing an old bug has resulted in breaking your code, I'm not sure that there's anything to do here. This is now the behavior we are looking for. Pinging @rix0rrr for a second pair of eyes, but that's my $0.02.

**Comment by rix0rrr** [comment]
I'm amazed that

```ts
new ServicePrincipal('secretsmanager.amazonaws.com', {
      conditions: [
        {
          StringEquals: {
            'aws:SourceAccount': Accounts.MAIN.account,
          }
        }
      ]
});
```

Even worked. As @kaizencc says, it should always have been:

```ts
new ServicePrincipal('secretsmanager.amazonaws.com', {
      conditions: {
          StringEquals: {
            'aws:SourceAccount': Accounts.MAIN.account,
        }
      }
});
```

Our apologies that we didn't throw an error before.
