### ISSUE TITLE
VPC: VPC for some reason looks at the environment where other services don't

### ISSUE THREAD

**Issue by teuteuguy** [aws/aws-cdk#20975]
### Describe the bug

We deploy our app in 3 different accounts, dev, staging and prod.

We have deployed each of these accounts once, using npx cdk deploy ENV-Dev, or npx cdk deploy ENV-Stg or npx cdk ENV-Prd.

The app has a aws-cdk/pipelines construct to CI/CD on commits to the respective branhces develop/staging and release.

This has been working for months now.

We recently needed to introduce use of VPC so added a VPC to our stack.
Suddenly our pipelines fail on last build step: npx cdk synth.

Indeed when running npx cdk synth on our laptops we get the exact same error:

[Error at /ENV-Prd/V3Stack] Need to perform AWS calls for account 12345678, but the current credentials are for 76567897463524 (fake account numbers).

For some reason VPC construct is playing games with the environment 

### Expected Behavior

None of the other constructs (we have used so far, DDB, Lambda, IAM, IoT, Rules, SNS, SQS, Firehose etc ...) have this issue. Only the VPC construct.

This should not mess around or go try look at the other environments when synth is called

### Current Behavior

If the VPC definition has multiple apps, current behavior is errors on each app:

[Error at /ENV-Prd/V3Stack] Need to perform AWS calls for account 12345678, but the current credentials are for 76567897463524 (fake account numbers).

### Reproduction Steps

Simply create a CDK to deploy in 2 differnt accounts with 2 different environment names, to manage 2 different branch names.

Then simply add a VPC to the CDK.

Won't synth.

### Possible Solution

Current solution seems to be to have to modify the build to be npx cdk synth ID where ID is the environment name. 

Which is not advisable, because requires changing all our pipelines.

### CDK CLI Version

2.30

### Node.js Version

v16.13.2

### OS

Mac

### Language

Typescript

**Comment by teuteuguy** [comment]
Follow up, after working with AWS support who suggested to modify our pipeline to reference the environment, this actually does not work.

Whilst the initial error ([Error at /ENV-Prd/V3Stack] Need to perform AWS calls for account 12345678, but the current credentials are for 76567897463524 (fake account numbers).) is removed.

A new one appears: [Error at /ENV-Dev/V3Stack] You are not authorized to perform this operation.

**Comment by corymhall** [comment]
@teuteuguy this is mostly likely due to the Vpc construct attempting to lookup the availability
zones. The Vpc construct needs to know what availability zones are available in the specified
region. By default it will attempt to lookup that value the first time and then it will store that
imformation in the `cdk.context.json` file. You have two options for getting passed the error
message.

1. Allow read only access locally so that you can run `cdk synth` to query the availability zones.
   The information will be stored in `cdk.context.json` which you then commit to source control.
   When the app is synthesized in the pipeline it will use the values in `cdk.context.json` and will
   not attempt to look them up.
2. You can override the `availabilityZones` method to provide the values yourselves if you know the
   specific availability zones for each region. https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2-readme.html#control-over-availability-zones


Also, if you want to prevent the pipeline from attempting context lookups you can use the
`--no-lookups` CLI flag to have the CLI throw an error if context lookups are attempted.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html#context-lookups
