### ISSUE TITLE
codestarnotifications: Naming conflict on CFN deployment, if the name of the underlying pipeline changes

### ISSUE THREAD

**Issue by straygar** [aws/aws-cdk#20998]
### Describe the bug

When renaming a pipeline that a `NotificationRule` is attached to, without changing its ID, deployment fails, as:
* The pipeline (and hence the `NotificationRule`) has to be recreated
* BUT the notification rule name does not change, as it's based on the pipeline ID

This results in a deployment conflict. I assume this applies to all sources like CodeBuild projects as well.

### Reproduction Steps

1. Create a `CodePipeline`, with an explicit `pipelineName`
2. Create a `NotificationRule` pointing to that pipeline
3. Deploy
4. Change `pipelineName` to something else
5. Deploy

### Expected Behavior

1. New notification rule is created, attached to the new pipeline
2. Old notification rule and pipeline is deleted
3. Deployment succeeds

### Current Behavior

CFN deployment fails with:
```
15:02:52 | UPDATE_FAILED        | AWS::CodeStarNotifications::NotificationRule | PipelineSlackNotifications7DC43D4D
Resource handler returned message: "The notification rule was not created because another notification rule already exists with the same name. Notification rule names must be unique within an AWS account"
```

### Possible Solution

Use a combination of the pipeline name and ID in the notification rule name.

### CDK CLI Version

2.27.0

### Node.js Version

14

### OS

MacOSX

### Language

Typescript

**Comment by peterwoodworth** [comment]
We recommend not explicitly setting names in CloudFormation, as it can result in errors where CloudFormation is unable to create a new resource due to duplicate names. This is called out in both [CDK docs](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_physical_names) and [CFN docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html)

> Assigning physical names to resources has some disadvantages in AWS CloudFormation. Most importantly, any changes to deployed resources that require a resource replacement, such as changes to a resource's properties that are immutable after creation, will fail if a resource has a physical name assigned. If you end up in that state, the only solution is to delete the AWS CloudFormation stack, then deploy the AWS CDK app again.

Since the ID is being used to calculate this, is it possible for you to just rename the pipeline construct here instead of deleting your whole stack?

**Comment by straygar** [comment]
@peterwoodworth Yeah, I understand this best practice. My suggestion is to somehow change the recipe of that auto-generated ID, so it changes when the `pipelineName` changes, otherwise it will result in a conflict.

**Comment by rgoltz** [comment]
> ### Current Behavior
> CFN deployment fails with:
> 
> ```
> 15:02:52 | UPDATE_FAILED        | AWS::CodeStarNotifications::NotificationRule | PipelineSlackNotifications7DC43D4D
> Resource handler returned message: "The notification rule was not created because another notification rule already exists with the same name. Notification rule names must be unique within an AWS account"
> ```

We ran into the same issue. After debugging this on CFN level, I've created the issue with CFN team: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1278 to make them aware on this naming issue (here in case you just change a tag).

**Comment by rgoltz** [comment]
Hi @straygar, @peterwoodworth  - Great news - CloudFormation team has improved AWS::CodeStarNotifications::NotificationRule resource [#1278](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1278). After the above mentioned github issue had been flagged as shipped, I run successfully this two cases (on pure CFN level):
a) change the `Name` of `AWS::CodeStarNotifications::NotificationRule` in an existing stack => Stack-Update was successful. No replacment or failed Update. Change-Set during update reflected this correctly.
b) change the `Tags` of `AWS::CodeStarNotifications::NotificationRule` in an existing stack => Stack-Update was successful. No replacment or failed Update. Change-Set during update reflected this correctly.

Since a change of pipelineName resulting in a change of the Name of the NotificationRule, I assuming the issue reported initially should be gone due to better CloudFormation behaviour - Cloud you please do a cross-check along your use-case (with the same CDK version, since I assume there is no fix on CDK-level needed anymore)?

**Comment by straygar** [comment]
@rgoltz Excellent, thanks for the update!
