### ISSUE TITLE
aws_elasticloadbalancingv2 : LB lookup returns non-existing LB

### ISSUE THREAD

**Issue by spyrosavl** [aws/aws-cdk#21370]
### Describe the bug

I have created an Elastic Beanstalk environment through CDK (with an app load balancer). Then I want to point a domain (A record) to it. To do so, I retrieve the load balancer of the EB environment using `elbv2.ApplicationLoadBalancer.from_lookup`.  Then I create an A record and set the retrieved LB as a target. The stack is successfully deployed. However, when I check the records in Route53, the created A record points to a non-existing LB.

### Expected Behavior

I would expect the created record to point to the correct LB.

### Current Behavior

No errors.

### Reproduction Steps

I retrieve the LB as follows:
`loadbalancer = elbv2.ApplicationLoadBalancer.from_lookup(
            self,
            "ID",
            load_balancer_tags={'Name': self.eb_env.environment_name}
 )`
And then I create the A record:
` 
route53.ARecord(
            self, "domain_ID",
            zone=hosted_zone,
            record_name=RECORD_NAME,
            target=route53.RecordTarget.from_alias(route53_targets.LoadBalancerTarget(loadbalancer))
        )
`
Finally, I checked the created record through Route53 console, and the alias is not pointing to the correct LB. It points to a non-existing one.

This issue is occurring in 2 different stacks. I have also tried to destroy and redeploy them, but the issues persist.

### CDK CLI Version

2.29.1

### Node.js Version

18.3.0

### OS

Mac OS

### Language

Python

**Comment by jumic** [comment]
Did you use the L1 construct `CfnEnvironment` to create the Elastic Beanstalk environment? If yes, please have look at the [return values](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment.html#aws-properties-beanstalk-environment-return-values). Attribute `EndpointURL` contains the URL to the load balancer. You can create a `CNameRecord` using the URL. In this case, you don't need to use the `fromLookup` method.

Now, why does the `fromLookup` method return a non-exsting Load Balancer? I think you are using the `fromLookup` method in the same stack where you have created the Elastic Beanstalk environment. During `cdk synth` cdk can't determine the correct URL because it doesn't exist yet (Elastic Beanstalk environment wasn't deployed at this point in time). Which URL was used in your case? In case of `my-load-balancer-1234567890.us-west-2.elb.amazonaws.com`, it's the dummy URL which will be returned in this case. The `fromLookup` method should be primary used if you want to lookup a value from another stack. Probably you are only using a single stack where a lookup doesn't make sense, because the resources aren't created yet when the lookup will be executed.

**Comment by spyrosavl** [comment]
Thanks for getting back to me @jumic.
Regarding the first one. Yes, I can create a `CNameRecord` and connect the domain in this way. However, I need to access the load balancer for another reason. I would like to protect it behind an AWS Cognito login. And to do that I need to have access to the LB created by EB, to modify the listeners.

Regarding the `fromLookup`. No, I do the lookup from another stack (the "domains stack") and add the EB stack as a dependency.  The URL that is used is not `my-load-balancer-1234567890.us-west-2.elb.amazonaws.com`, it's a "real looking" URL.

**Comment by spyrosavl** [comment]
@corymhall yes the value I can see in Route53 is `dualstack.awseb-awseb-ymx36r1e6h0t-409689561.ap-southeast-2.elb.amazonaws.com`

**Comment by corymhall** [comment]
@spyrosavl does that match your expected url except for the `dualstack` on the front?

**Comment by spyrosavl** [comment]
@corymhall No, it does not. I am searching the LBs in EC2 console, and there is no LB with `ymx36r1e6h0t` in its URL...

**Comment by jumic** [comment]
@spyrosavl Probably this was an LB that was deployed in the past.
Please have a look at file `cdk.context.json` in your CDK project. Is the value cached there?
If yes, please try to reset this cached value, see https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_viewing

**Comment by spyrosavl** [comment]
@jumic the caching in context seems to cause the issue. Thank you both for your time!
