### ISSUE TITLE
(aws_autoscaling): (EC2 volumes are not tagged by default)

### ISSUE THREAD

**Issue by S3ky** [aws/aws-cdk#21537]
### Describe the bug

Hi,

while creating EC2 resource via aws_autoscaling.AutoScalingGroup construct EC2's volume(s) are not tagged, however, when EC2 instance was created from aws_ec2.Instance construct EC2's volume(s) were tagged.

### Expected Behavior

All EC2's volumes to be tagged.

### Current Behavior

No tags for EC2's volumes.

### Reproduction Steps

Minimal snippet:

asg=aws_autoscaling.AutoScalingGroup(scope, id, vpc=vpc,
                                            block_devices=[block_device], associate_public_ip_address=False,
                                            instance_type=aws_ec2.InstanceType.of(aws_ec2.InstanceClass.BURSTABLE3,
                                                                                  aws_ec2.InstanceSize.MEDIUM),
                                            machine_image=aws_ec2.GenericLinuxImage(ami_map=BASTION_AMI_MAP),
                                            require_imdsv2=True, role=role, user_data=user_data,
                                            health_check=aws_autoscaling.HealthCheck.elb(
                                                grace=Duration.seconds(300)),
                                            auto_scaling_group_name='test',
                                            max_capacity=3, max_instance_lifetime=Duration.days(1), min_capacity=1,
                                            desired_capacity=1,
                                            update_policy=UpdatePolicy.rolling_update(min_instances_in_service=1),
                                            vpc_subnets=vpc_subnets, security_group=security_group)

Tags.of(asg).add(key='Test', value='test')

// For all other (not just EC2 related) resources it's tagging properly.

### CDK CLI Version

2.34.2

### Node.js Version

v18.7.0

### OS

Archlinux

### Language

Python

### Language Version

Python (3.9)

**Comment by peterwoodworth** [comment]
The tags aspect will only apply to resources which are taggable - the AutoScalingGroup construct will create the instances and volumes as part of CloudFormation deployment, so since they aren't in the CloudFormation template itself we cannot detect it as taggable. 

Tags for the volume will have to be configured within the launch template https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-tags

**Comment by S3ky** [comment]
@peterwoodworth 

I can't see tags in the high-level construct of AutoScallingGroup (reference: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.AutoScalingGroup.html), so you are suggesting to use Cfn Construct (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.CfnAutoScalingGroup.html) instead? If I do not want to use this Cfn Construct, but still leverage tags, should I create bug/feature request on CloudFormation?

**Comment by peterwoodworth** [comment]
I linked the CloudFormation documentation because the documentation for the `launchTemplate` property states how CloudFormation will allow you to set the tags on volumes. [Here's the page on `LaunchTemplate`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-tagspecifications) which is where you can configure the tags

CDK allows you to [configure the launch template with the ASG construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.AutoScalingGroup.html#launchtemplate). You can create an L2 LaunchTemplate with CDK in our EC2 module, and add the necessary tags with the tags aspect

If you wish to create tags without needing to specify a launch template, I would recommend reaching out to CloudFormation 🙂
