### ISSUE TITLE
AWS CDK: Credential keys in upper-case could not be found on windows.

### ISSUE THREAD

**Issue by vipetrul** [aws/aws-cdk#21562]
### Describe the bug

in `.aws/credentials` file, credentials are specified like so:

```
[default]
AWS_ACCESS_KEY_ID=####
AWS_SECRET_ACCESS_KEY=####
AWS_SESSION_TOKEN=####
```
AWS CLI can read and use these credentials without a problem, but when using cdk following error is displayed:
```
Environment aws://######/us-east-1 failed bootstrapping: Error: Need to perform AWS calls for account ######, but no credentials have been configured
    at SdkProvider.forEnvironment (C:\Users\vipetrul\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\sdk-provider.ts:179:46)
    at Function.lookup (C:\Users\vipetrul\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\bootstrap\deploy-bootstrap.ts:31:18)
    at Bootstrapper.modernBootstrap (C:\Users\vipetrul\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\bootstrap\bootstrap-environment.ts:81:21)
    at C:\Users\vipetrul\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:586:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (C:\Users\vipetrul\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:583:5)
    at initCommandLine (C:\Users\vipetrul\AppData\Roaming\npm\node_modules\aws-cdk\lib\cli.ts:347:12)
```

Changing key names to lower-case solves the problem.
```
aws_access_key_id=####
aws_secret_access_key=####
aws_session_token=####
```

### Expected Behavior

Credential key names in upper-case should be usable by CDK just like the keys in lower-case.

### Current Behavior

Keys are not found.

### Reproduction Steps

Specify keys using key names in upper case. Any CDK operation that needs to connect to AWS account will fail.

### CDK CLI Version

2.37.1 (build f15dee0)

### Node.js Version

v16.16.0

### OS

Windows 10

### Language

Typescript

**Comment by rix0rrr** [comment]
The documentation for the AWS CLI also says that the keys need to be specified in lowercase: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

I don't know why it says that the values need to be lowercase but proceeds to accept uppercase values. This only makes the compatibility contract opaque and hard to implement for other tools, as is the case here.

The CDK CLI is not 100% feature (or bug)-compatible with the AWS CLI. We do our best, but since these are completely different code bases with their own quirks it is an uphill battle.

In this case, since the behavior you are relying on seems to be undocumented and the workaround is pretty simple, I don't think I'm going to accept this as a bug. Sorry.
