### ISSUE TITLE
(cloudtrail): (configuration for IsOrganizationTrail is failed)

### ISSUE THREAD

**Issue by haikoschmidt** [aws/aws-cdk#21578]
### Describe the feature

I miss the fact that I can use boolean to specify an OrganizationTrail as in CloudFormation.

https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-isorganizationtrail

### Use Case

I am currently converting my payer configuration to CDK, at least what is available at all, which unfortunately is still very little at the moment. Using CloudFormation, I can specify whether a trail is an organization trail and whether it is then automatically rolled out throughout the organization.
Unfortunately, this is not yet possible with CDK.

### Proposed Solution

Give an option that you can configure this using boolean, the default should be "false".

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.37.1

### Environment details (OS name and version, etc.)

none

**Comment by kylelaker** [comment]
As a workaround, you should be able to use an [escape hatch](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to override the property:

```ts
import * as cloudtrail from "aws-cdk-lib/aws-cloudtrail";

// Create the L2 Trail resource with the preferred configuration
const trail = new cloudtrail.Trail(stack, "OrganizationTrail");
// Get the underlying AWS::CloudTrail::Trail L1 resource
const l1Trail = trail.node.defaultChild as cloudtrail.CfnTrail;
// Use the escape hatch to set the L1 AWS::CloudTrail::Trail resource's property
l1Trail.addPropertyOverride("IsOrganizationTrail", true);
```

**Comment by peterwoodworth** [comment]
Thanks for the feature request @haikoschmidt,

I am marking this issue as p2, which means that we are unable to work on this immediately.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

Link to code where we declare the CfnTrail https://github.com/aws/aws-cdk/blob/1e57c6cf388c50f35988fe7bdc5f78712085211d/packages/%40aws-cdk/aws-cloudtrail/lib/cloudtrail.ts#L275

**Comment by chinmayv2** [comment]
Hello All,
I was going through the chain since I am interested to contribute to the cdk. I understood the suggestion/ proposed solution is 

> Give an option that you can configure this using boolean, the default should be "false".

Excerpts from [this](https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-isorganizationtrail) link attached in the bug report. 

>  If the trail is an organization trail and this is set to false, the trail will remain in the current AWS account but be deleted from all member accounts in the organization.

1- Do we want any additional validation or user confirmation/intervention if we want to give a good customer experience ?
2- Should we have the default to true ?

**Comment by peterwoodworth** [comment]
Hey @chinmayv2,

The CloudFormation documentation mentions that this prop is set to false by default, so that's what we'd want to do here as well. Someone would have had to explicitly set this to true for the behavior to change, so if we keep the default as false or undefined then that will not affect existing users.

**Comment by TheRealAmazonKendra** [comment]
It may be worth it to point to to CloudFormation that the documentation there is pretty confusing/misleading. I had to re-read it a few times to get what the actual behavior was.
