### ISSUE TITLE
Getting Started example is out of date

### ISSUE THREAD

**Issue by watany-dev** [aws/aws-cdk#21588]
### Describe the issue

The sample in the readme.md placed at the top of the project looks like v1.
Also, reading this text alone, I don't understand how to import the module, so it would be good to add it to the sample, but it seems as if only the classes have been excerpted intentionally, so if it is not necessary, could you please comment?

### Links

readme.md

**Comment by peterwoodworth** [comment]
Hey @watany-dev,

I don't see what about the sample in our readme is v1 specific. This snippet should work on both v1 and v2 - I think that only the imports would differ here (which are omitted as you've noted) 

We have lots of resources which show how to get started with CDK. The README here is intended to be a very brief look at CDK instead of being a comprehensive guide. It links to other more dedicated resources for learning how to use CDK, have you been able to check out our [workshop](https://cdkworkshop.com/) or [developer guide](https://docs.aws.amazon.com/cdk/v2/guide/home.html)?

**Comment by watany-dev** [comment]
@peterwoodworth 

Thanks. I tried it on my end here and it worked. I guess I was mistaken. Sorry, you can close this issue.

**Comment by peterwoodworth** [comment]
No worries @watany-dev, ping me if you have any additional questions or concerns!
