### ISSUE TITLE
(aws-backup): Tags applied within containing stack not applied to BackupVault construct

### ISSUE THREAD

**Issue by C7C8** [aws/aws-cdk#21593]
### Describe the bug

When creating a `BackupVault` or `BackupPlan` instance, tags applied after instance construction and within the same stack are not applied to the deployed AWS Backup Vault. Unusually, tags applied recursively (with `Tags.of(containingStack).add('foo', 'bar')`) are applied.

Unusually the generated CloudFormation templates do not appear to reference *any* tags, despite that the tags showing on the AWS Console are clearly from constructs up higher in the construct hierarchy.

### Expected Behavior

In the code sample under reproduction steps, I would expect that the construct instance `backupVault` would have both tags `foo: bar` and `baz: qux`.

### Current Behavior

For the same code sample, only `baz: qux` is added as a tag key/value combination.

### Reproduction Steps

Code sample:

```typescript
export class MyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

   // ....

    const backupVault = new BackupVault(this, "MyBackupVault", {
        backupVaultName: "MyBackupVault",
        encryptionKey: cmk,
        removalPolicy: RemovalPolicy.RETAIN,
        blockRecoveryPointDeletion: true
      });
      Tags.of(backupVault).add("foo", "bar");
    }
}

// Outside stack, in a containing stack
const myStack = new MyStack(this, "myStack", props);
Tags.of(myStack).add("baz", "qux");
```

### Additional Information/Context

My project makes extensive use of CDK aspects and recursive application of tags, but as written they should not be interfering with one another. I have not been able to reproduce this issue with any other construct than a BackupVault so far.

### CDK CLI Version

2.35.0

### Node.js Version

18.7.0

### OS

Mac OSX Monterey 12.5 (M1)

### Language

Typescript

### Language Version

Typescript (3.9.7)

**Comment by peterwoodworth** [comment]
The Tags aspect only applies to resources which are considered "taggable". A resource is considered taggable when the CloudFormation resource has the `Tags` property. The problem here is occurring because none of the Backup resources have the Tags property https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-backup-backupvault.html

I recommend creating an issue for this on the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) if one doesn't exist already. Without CloudFormation support there's going to be no way for CDK to set these tags, and once Cfn supports this then CDK will support it automatically
