### ISSUE TITLE
How to create Connector CustomPlugin AWS_MSK. Need to retrieve CustomPluginArn?

### ISSUE THREAD

**Issue by dbayonacode** [aws/aws-cdk#21592]
### Describe the issue

I am using CfnConnector to create a MSK connector and it requires a customPluginArn. How am i able to create a custom plugin using the CDK, so i am able to get the CustomPluginArn and the Revision number? There is no any documentation about it. Thanks

### Links

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-kafkaconnect.CfnConnector.html

**Comment by peterwoodworth** [comment]
The kafkaconnect module that we support consists of just L1 resources - meaning that the only support we have for this module is what [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_KafkaConnect.html) directly gives us to work with. 

The CloudFormation documentation here is pretty lacking - which means our documentation is as well. So to answer your question about how to create a plugin with CDK, there doesn't seem to be an easy way to do this because there is no Plugin resource offered by CloudFormation. The only way you would be able to create a Plugin today with CDK is with an [AwsCustomResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html) which makes use of the [CreateCustomPlugin API call](https://docs.aws.amazon.com/MSKC/latest/mskc/API_CreateCustomPlugin.html)
