### ISSUE TITLE
aws-cdk-lib/aws-ec2: InterfaceVpcEndpoint. fromInterfaceVpcEndpointAttributes returns an object that does nothing

### ISSUE THREAD

**Issue by Juholei** [aws/aws-cdk#21636]
### Describe the bug

Calling InterfaceVpcEndpoint.fromInterfaceVpcEndpointAttributes with the minimum required parameters like below can return an endpoint object that seemingly works but if you try to use it to allow connections, nothing happens.
```
const endpoint = InterfaceVpcEndpoint.fromInterfaceVpcEndpointAttributes(
  this,
  "Endpoint",
  {
      vpcEndpointId: "correct-id",
      port: 443,
  }
 );

 fargateService.connections.allowTo(endpoint, Port.tcp(443));
```

cdk diff shows no changes and after the deploy the connection is not allowed. If you add the optional securityGroups parameter to InterfaceVpcEndpointAttributes parameter of the call, then the endpoint works.

Also if the vpcEndpointId is wrong, it works exactly the same as with the correct id with a call such as above.

### Expected Behavior

If an endpoint cannot be found with the given parameters, CDK should give an error like when importing other existing resources.

### Current Behavior

There is no error, endpoint object's connections object can be used but nothing happens.

### Reproduction Steps

1. There is an existing interface endpoint defined outside of CDK.
2. Import it using `const endpoint = InterfaceVpcEndpoint.fromInterfaceVpcEndpointAttributes(
  this,
  "Endpoint",
  {
      vpcEndpointId: "correct-id",
      port: 443,
  }
 );`
3. Grant access to some other resource to the endpoint, for example like ` fargateService.connections.allowTo(endpoint, Port.tcp(443));`
4. Check cdk diff output for the stack, there's no changes.

### CDK CLI Version

2.31.1

### Framework Version

2.37.1

### Node.js Version

v16.10.0

### OS

Mac OS Monterey

### Language

Typescript

### Language Version

4.7.4

**Comment by mascur** [comment]
Thanks for reporting this @Juholei,

`connections` methods operate between constructs which implement the `connections` class. Since you're importing the `InterfaceVpcEndpoint` resource, the connections object that's created for that class will not know which security groups are associated with your endpoint. To allow the FargateService connections to work with your endpoint, you will need to specify the security groups associated with your endpoint when you import it. [You can do this with the `securityGroups` prop.
](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.InterfaceVpcEndpointAttributes.html#securitygroups)

Ping me if you have any other questions or concerns!

**Comment by Juholei** [comment]
@mascur thanks for the explanation. I still think that if the security groups are not given to fromInterfaceVpcEndpointAttributes, then you should get some kind of an error when manipulating the connections object if there's no chance it will do anything in that case.
