### ISSUE TITLE
(aws-cdk): (S3 bucket server access logging not enabled by default, leads to many Security Hub findings)

### ISSUE THREAD

**Issue by dzenana-s** [aws/aws-cdk#21874]
### Describe the bug

We are seeing findings in Security Hub related to the following finding: `S3.9 S3 bucket server access logging should be enabled` on resources that are deployed with the AWS CDK. We would like to remove these by using the CDK easily. 

### Expected Behavior

That S3 buckets deployed through the CDK are compliant with Security Hub compliance packs, including an aspect like bucket server access logging being enabled (potentially by default?) 

### Current Behavior

S3 buckets we are deploying fail the Security Hub compliance checks and lead to findings for many S3 CDK deployed buckets. 

### Reproduction Steps

- Deploy
```
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cdk from 'aws-cdk-lib';

export class CdkStarterStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const s3Bucket = new s3.Bucket(this, 's3-bucket')
  }
}
```
- Go to Security Hub and see an issue created about server access logging not existing on the S3 bucket

### CDK CLI Version

2.35.0

### Node.js Version

v16.15.1

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
You can configure this with the [`serverAccessLogsBucket` prop](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-s3-readme.html#logging-configuration)

This won't be something we support by default due to additional costs incurred, changing functionality for existing users, and because we don't claim to have our defaults be security hub compliant
