### ISSUE TITLE
aws-cdk: CLI cannot parse Unicode in templates

### ISSUE THREAD

**Issue by CaerusKaru** [aws/aws-cdk#21886]
### Describe the bug

When you have a deployed CloudFormation template that contains Unicode characters, any subsequent attempts to use `cdk deploy` to update the template/stack will fail due to YAML failure:

```
YAMLSemanticError: Nested mappings are not allowed in compact mappings
```

### Expected Behavior

YAML parser should handle Unicode characters.

### Current Behavior

YAML parser throws errors.

### Reproduction Steps

1. Create a Lambda function, add environment variables with Unicode characters
2. Run `cdk deploy`, it should succeed.
3. Make any change the template, and run `cdk deploy` again.

### Possible Solution

Some sort of upstream patch to the YAML dependency, or possibly pre-sanitizing the template when retrieving from CloudFormation

### CDK CLI Version

2.40.0

### Node.js Version

16.10.0

### OS

macOS

### Language

Typescript

**Comment by CaerusKaru** [comment]
cc @madeline-k @rix0rrr

**Comment by peterwoodworth** [comment]
What unicode characters are you referring to?

**Comment by CaerusKaru** [comment]
For me, it's `\uD83E\uDD16`

**Comment by rix0rrr** [comment]
We need a little more here I'm afraid. Where is the error occurring? In a diff we are performing? In the deploy? 

I know CloudFormation's `GetStackTemplate` messes up unicode in a way that is non recoverable, and there's nothing we can do about it.

**Comment by CaerusKaru** [comment]
If that's the case, can we have a pre-emptive warning during `cdk deploy` that the template will be put in an unrecoverable state? I think that's a serious enough issue that we should prevent customers from walking through walls without warning.

**Comment by peterwoodworth** [comment]
We still aren't sure when this error is occurring for you @CaerusKaru, or how you are getting these characters in the template in the first place. Being able to reproduce this on our end will allow us to implement the appropriate fix / warning

**Comment by CaerusKaru** [comment]
You can follow the reproduction steps I've listed above. It really is the most minimal implementation I can think of, and is the exact case I encountered.

**Comment by peterwoodworth** [comment]
I'm not able to reproduce it - here's my output when I `cdk diff`:

```
[~] AWS::Lambda::Function fn fn5FF616E3 
 └─ [~] Environment
     └─ [~] .Variables:
         ├─ [~] .RANDOM_CHANGE:
         │   ├─ [-] randomletters
         │   └─ [+] orderedletters
         └─ [~] .UNICODE:
             ├─ [-] ?
             └─ [+] 🤖
```

I didn't actually change the string found in the UNICODE variable, but it shows a diff likely due to the reason Rico posted.

Deploying any changes deploys successfully and works as expected - though the template in the console shows a `?` for the unicode string, the lambda console shows the little Robot

**Comment by elmesb72** [comment]
Any chance of re-opening this? I can replicate this consistently when trying to build QuickSight stacks (CfnDataSource + CfnDataSet + CfnAnalysis + CfnDashboard). Using '&uarr;' ('\u2191') as a CustomLabel value on a CfnAnalysis.TableFieldOptionsProperty, the resulting output will include json templates where:
```
{
  "CustomLabel": "\u2191"
  "FieldId": "..."
}
```

But after `cdk deploy` the first time, the stack's YAML will not wrap the character in double quotes (like it does with string values starting with a `#` character, for example), and will look like this:
```
- CustomLabel: ?
  FieldId: ...
```
Opening the Stack's template in the Designer in the console will return the error messages above but with a pointer to the lines with the unicode characters. Trying to deploy again will result in the same error message in the issue description above. You have to delete the stack.

Workarounds include setting the customLabel value to '# &uarr;' or ' &uarr; ' as those will re-serialize to YAML wrapped in double quotes and will not throw indentation errors. Seems the issue is in the reserialization process for strings starting with non-standard unicode characters during `cdk deploy`.

**Comment by kellertk** [comment]
I'll reopen this so we can take a look. @elmesb72 can you give us a [short example](http://sscce.org/) that will hit this so we can troubleshoot?

**Comment by indrora** [comment]
My wild speculation based on years of sniping unicode gremlins at 100 yards on what's happening here is that the character U+2191 Upwards Arrow is being crunched somewhere into a non-Unicode compliant (e.g. ASCII) encoding. 

My best guess is that it's a shell locale quirk that is being carried on when doing diffs but not when doing the initial deploy. This may be a CloudFormation side thing, but I'm not sure: CloudFormation could well be returning the wrong data back during diff, but how the CDK tells if it needs to be re-deployed initially isn't tree-shaking but some hash. 

So... if U+2191 (UTF-16) is transmogrified into a UTF8 sequence, it's the sequence `[A WITH CIRCUMFLEX][START OF SELECTED AREA][PRIVATE USE 1]` and if misinterpreted as Windows codepage 1512 appears as `â†‘`. 

HOWEVER, if this is then transmogrified back into UTF16 improperly, you get... [a codepoint somewhere in the fourth dimension](https://codepoints.net/U+E28691). 

Unicode Gremlins are everywhere.

**Comment by pahud** [comment]
Hi @elmesb72 as described [above](https://github.com/aws/aws-cdk/issues/21886#issuecomment-1712263843), can you give us a minimal code sample that we can reproduces this issue?
