### ISSUE TITLE
Document minimum IAM permissions required to deploy stack

### ISSUE THREAD

**Issue by yuyokk** [aws/aws-cdk#21977]
### Describe the issue

Hi team,

As continuation to https://github.com/aws/aws-cdk/issues/4039

I think it would be super helpful for people getting started with aws cdk (including myself) to add some info on "minimum iam permissions" to deploy their first stack with aws cdk as right now there is not much info on this topic on official docs.

Thanks 

### Links

https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html#getting_started_prerequisites

**Comment by Naumel** [comment]
Here's some starting points:
* https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html
* https://github.com/aws/aws-cdk/discussions/19715
* https://stackoverflow.com/questions/57118082/what-iam-permissions-are-needed-to-use-cdk-deploy

The ask here is rather vague, can you supply some extra details about what you are trying to accomplish, perhaps there's a more poignant reference to be provided.

**Comment by yuyokk** [comment]
> The ask here is rather vague, can you supply some extra details about what you are trying to accomplish, perhaps there's a more poignant reference to be provided.

Example: there is "Your first AWS CDK app" section https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html
so it would be helpful to have permissions defined per user needed to run/deploy this "Hello World" app.

**Comment by esteban-uo** [comment]
I agree with @yuyokk , best practices are documented but it is somehow contradictory/misleading to follow the least-privilege principle with the actual content <img width="1308" alt="Screenshot 2022-11-09 at 13 50 33" src="https://user-images.githubusercontent.com/444870/200834909-6e305a3c-615f-4f11-bb0d-4ceb632d5633.png"> @Naumel

**Comment by kewur** [comment]
I agree that we shouldnt be using day to day accounts for cli work. We had an incident where someone deleted a real aws resource instead of using the localstack endpoint. We are looking into gibing all devs only readonly access with cli tokens. However, we now need to find the appropriate permisison levels to deploy CDK stacks.

Do we need individual service permissions to be able to deploy particular resources? or is there a way to delegate these permissions to cloudformation
