### ISSUE TITLE
aws-cdk: NotificationArns as a construct prop, rather than read-only 

### ISSUE THREAD

**Issue by dzenana-s** [aws/aws-cdk#21986]
### Describe the feature

We are exploring how we can integrate SNS with our CloudFormation stacks. We noticed that you can supply a [`notificationArns` prop](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.NestedStack.html#construct-props), which can include an SNS topic ARN, but only on the `NestedStack` construct, not [the `Stack` construct](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.Stack.html). 

Is there a reason why this prop cannot be supplied when creating deploying with the CDK without nesting? We are trying to find a way to automate adding SNS, without manually making the update to the stack so that it points notifications to the SNS topic in the console. 

### Use Case

We would like to monitor changes to certain CloudFormation stacks and send notifications through SNS when certain actions are taken on a stack. 

Currently, we would have to deploy via CDK and then manually update the notification settings in the stack, but we would like to do this all via code. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.35.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by kaizencc** [comment]
The _reason_ is that `NestedStack` is built on top of the `CfnStack` cloudformation resource, which has the `notificationArns` property. A CDK `Stack` does not actually create a `CfnStack` afaik, so it doesn't have the opportunity to update the `notificationArns` property. How/why this is the case I'm not entirely sure; I did a little digging but came up with more questions than answers. Maybe @rix0rrr can help with answering that.

**Comment by peterwoodworth** [comment]
You can set the arns of SNS topics to notify on `cdk deploy` with the `--notification-arns` option.

@kaizencc you're right that `Stack` does not actually create a `CfnStack` - the `CloudFormation::Stack` resource is specifically for nested stacks. The way CDK accomplishes setting the notification arns on a non-nested stack is by passing them into the [`CreateChangeSet` operation](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html#API_CreateStack_RequestParameters) which is best [configured through the CLI rather than the `Stack` construct](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/deploy-stack.ts#L318), though I would think it's possible for us to design it such that it's configurable through the stack construct as well

@dzenana-s I hope configuring this through the CLI works for you! 🙂

**Comment by gricey432** [comment]
For people like me who find this in search, see #8581
