### ISSUE TITLE
aws-cdk: does the deploy role assume other roles? 

### ISSUE THREAD

**Issue by ItsJustMagic** [aws/aws-cdk#22015]
### Describe the issue

In the documentation initialising a DefaultStackSynthesizer object, I've noticed that the deploy role assumes the fileAssetPublishingRoles and imageAssetPublishingRoles. 

However, the design docs in the bootstrap resources section, only mention;
This role will be assumable by any principal from the account(s) passed by the --trust option, **and from any principal in the target environment's account.**

I am also unable to replicate this behaviour from the AWS docs. 
The deploy role does not assume any roles, it only passes the cloud formation execution role. 

### Links

https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-custom-synth

https://github.com/aws/aws-cdk/blob/main/design/cdk-bootstrap.md#bootstrap-resources

**Comment by peterwoodworth** [comment]
I'm not super sure, but on a look at cloudtrail it seems like the `fileassetpublishingrole` and `imageassetpublishingrole` roles are both assumed by the current credentials rather than the deploy role. @rix0rrr can you confirm? And @Jerry-AWS pinging for awareness of another potential change needed in the devguide for bootstrapping

**Comment by peterwoodworth** [comment]
Yeah on second review I don't see anything wrong with our documentation that's currently up for v2 on this topic. Though, we may want to look into the design folder of this repository as it could be a bit misleading
