### ISSUE TITLE
CDK aws_apigateway: cannot use imported RestApi with ApiKey because ApiKey references prop only populated on non-imported RestApi

### ISSUE THREAD

**Issue by sempfa** [aws/aws-cdk#22102]
### Describe the bug

When using `RestApi.fromRestApiId`, `deploymentStage` property is not populated.

this effects other areas, such as creating an API Key to add to the RestApi, ie:
```
 const key = new apigw.ApiKey(this, 'tenant-key', {
      apiKeyName: `Tenant-Key`,
      resources: [api]
    });
```
(where `api` is the object created from `.fromRestApiId`)
returns error "Cannot read property 'stageName' of undefined"

### Expected Behavior

`deploymentStage` property populated from `RestApi.fromRestApiId`

### Current Behavior

`deploymentStage` undefined

### Reproduction Steps

1. use .fromRestApiId to reference existing API:
`const api = apigw.RestApi.fromRestApiId(this, "clientApi", 'xxxx123');`

2. create APIKey
```
 const key = new apigw.ApiKey(this, 'tenant-key', {
      apiKeyName: `Tenant-Key`,
      resources: [api]
    });
```

### Possible Solution

1.  populate `deploymentStage` property 

2. implement `.addApiKey` method on object created from `.fromRestApiId`

### Additional Information/Context

Api is created in another stack and is used for a much larger system... the app being created only needs to generate an API Key and a bucket and add them to param store.

### CDK CLI Version

2.41.0 (build 6ad48a3)

### Node.js Version

v16.16.0

### OS

Mac

### Language

Typescript

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
CDK isn't making any calls to your AWS account unless an import method is specifically configured to do that (usually denoted with the name `lookup` being present in the method). See our docs [here](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_referencing) for more info

Usually, if a property on the interface (or proxy) returned by the import method is undefined, then there is a way to define that property through a parameter in `fromXxxAttributes`. However, that's not the case for `RestApi.fromRestApiAttributes` because the deploymentStage prop is of type `Stage`, meaning that if you were to define the `deploymentStage` when importing the `RestApi`, you would need to end up creating a new Stage which doesn't make sense. To support defining the stage on the imported RestApi, we would need to adjust the typing to `IStage`.

Alternatively, in ApiKey we could potentially handle this differently to not require the restApi passed in have the deploymentStage defined, though I'm not sure how we would accomplish this exactly https://github.com/aws/aws-cdk/blob/7d8ef0bad461a05caa41d140678481c5afb9d33e/packages/%40aws-cdk/aws-apigateway/lib/api-key.ts#L193

**Comment by peterwoodworth** [comment]
I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by sempfa** [comment]
If this can't be solved soon,  then what is your recommended approach for creating an api key for an existing api gw?

**Comment by peterwoodworth** [comment]
@sempfa you can use the [CfnApiKey](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.CfnApiKey.html) resource, it's very similar to the [ApiKey](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.ApiKey.html) construct and will create the same resource. 

Something like this:
```ts
    new CfnApiKey(this, 'ApiKey', {
      enabled: true,
      name: 'Tenant-key',
      stageKeys: [
        {
          restApiId: 'restApiId',
          stageName: 'StageName'
        }
      ]
    });
```

Alternatively you can stay on the L2 level. If you do this you would want to not pass in anything to the `resources` parameter, and instead use an escape hatch to modify the generated resource in the template. Here's what you'd want to do:

```ts
    const key = new ApiKey(this, 'ApiKey', {
      apiKeyName: 'Tenant-key'
    });
    const cfnKey = key.node.defaultChild as CfnApiKey;
    cfnKey.addPropertyOverride('StageKeys', [
      {
        RestApiId: 'restApiId',
        StageName: 'StageName'
      }
    ]);
```
