### ISSUE TITLE
aws-apigateway: add resource/proxy/method to RestApi passed in the stack

### ISSUE THREAD

**Issue by Sevi7** [aws/aws-cdk#22139]
### Describe the bug

I have a RestApi created in stack A, I pass the RestApi resource to stack B and I add a resource, proxy or method. The deployment finishes without errors but it is not deploying the new resource/proxy/method.

Workaround: Import the RestApi in stack B instead of passing the resource between stacks.

### Expected Behavior

The new resource/proxy/method to be added to the RestApi.

### Current Behavior

Nothing happens, it is like if that part of the code was not in the deployment. However, in synthesis time it is executed (because it complained about some errors I first wrote).

### Reproduction Steps

1. RestApi created in stack A
2. Pass the RestApi resource to stack B
3. Add a new resource, proxy or method to RestApi in stack B.

### CDK CLI Version

2.40.0

### Node.js Version

v16.17.0

### OS

macOs

### Language

Typescript

**Comment by peterwoodworth** [comment]
The resources will be added to stack A in this case. Are you not finding this to be the case or are you only attempting to deploy Stack B?

**Comment by peterwoodworth** [comment]
If you're still using the actual construct itself, that construct retains its scope from stack 1. Further methods will be added under the scope of the RestApi, which is under the scope of Stack 1. Just because the logic is being ran when Stack B is being created doesn't necessarily mean that Stack B is the scope in which resources will be added

If you wish to create these in stack 2, you will need another object to keep track of that. [Importing a RestApi from its attributes](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.RestApi.html#static-fromwbrrestwbrapiwbrattributesscope-id-attrs) in Stack B should work

**Comment by Sevi7** [comment]
Thanks for your detailed explanation @peterwoodworth. I understand now, I thought you could modify a resource that is passed to another stack because you can use its grant methods (but probably only those). I will be cautious now, thanks!

**Comment by peterwoodworth** [comment]
Well, it's not going to always be clear exactly which stack a resource will be added to. Sometimes the logic may involve the creation of additional resources within the scope of the new stack depending on which methods are used and which constructs are interacted with. Just be sure to use `cdk diff` and check the template to make sure you know where the changes are being applied
