### ISSUE TITLE
aws_rds: Merge DatabaseInstanceFromSnapshot into DatabaseInstance

### ISSUE THREAD

**Issue by ThomasSteinbach** [aws/aws-cdk#22217]
### Describe the feature

The feature request is quite simply: It would be really helpful if in CDK the DatabaseInstanceFromSnapshot would be merged right into the DatabaseInstance class. The "new" DatabaseInstance class would then optionally take the snapshot identifier, when to recover the database from a snapshot.

### Use Case

We have a custom database class derived from the DatabaseInstance class with lots of customizations. When recovering a database from a snapshot we have to duplicate the whole class just because of the snapshot id parameter. All the rest of the configuration and customization remains the same.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.40

### Environment details (OS name and version, etc.)

independent

**Comment by corymhall** [comment]
@ThomasSteinbach we've created separate classes for these because there are some properties that
only apply to one or the other. If we were to merge them we would need to add documentation to each
property explaining in which instances to use that property and we would need to implement
validation logic to validate the properties are used correctly. This would degrade the user
experience.

For your specific use case could you create a super class which takes all the properties, and then
in the constructor you decide which type of instance to create?

```ts
export interface SuperDatabaseProps extends DatabaseInstanceProps, DatabaseInstanceFromSnapshotProps
{}

export class SuperDatabase extends Construct {
  constructor(scope: Construct, id: string, props: SuperDatabaseProps) {
    super(scope, id);
    if (props.snapshotIdentifier) {
      new DatabaseInstanceFromSnapshot(...);
    } else {
      new DatabaseInstance(...);
    }
  }
}
```
