### ISSUE TITLE
Template.fromStack Cannot reference across apps

### ISSUE THREAD

**Issue by Console32** [aws/aws-cdk#22437]
### Describe the bug

I have multiple Stacks, when creating the template the `Template.fromStack` function throws an error when running multiple Tests.
If I run a testcase alone, it is working. If I run all tests - the testcase fails. No Clue what is going on.

Relevant code snipets:
```
    const app = new App();
    const networkStack = new NetworkStack(app, 'networktest', configs);
    const stack = new PgwStack(app, 'test', { ...configs, vpc: networkStack.mainVpc.vpc });
    const template = Template.fromStack(stack);
```

First Test case it working, all other testcases throw the following Error:

```
Error: Cannot reference across apps. Consuming and producing stacks must be defined within the same CDK app.
```

### Expected Behavior

Testcases are working or failing independt if they are exectued alone or together

### Current Behavior

2nd test case should work

### Reproduction Steps

Will try to isolate a testable solution, but not sure this is possible. 

### CDK CLI Version

2.35.0 (build 5c23578)

### Node.js Version

v16.17.1

### OS

Windows 11

### Language

Typescript

**Comment by Console32** [comment]
Had a static resource in the stack which got created only once across testcases 🤦

**Comment by lulala1126** [comment]
> Had a static resource in the stack which got created only once across testcases 🤦

Hi Raphael, I apologize for the sudden comment. I had encountered a similar situation when trying to create a bucket for two tests using the same bucket name. However, after changing the name of one of the buckets, the issue was resolved. I tried to investigate the cause of this problem for the entire day, but could not understand it. Therefore, I was wondering if you could share your understanding of the issue, thanks
