### ISSUE TITLE
support best-effort stack deployment

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#22516]
### Describe the feature

Currently if a stack fails during `cdk deploy` then that stack is reverted and any remaining ones are aborted. Instead, there should be a flag to do a best-effort deployment, meaning that if a stack fails:
1. that stack gets rolled back
2. other stacks that depend on it (directly or indirectly) are skipped
3. all remaining stacks continue to deploy normally
4. the `cdk deploy` command itself still fails at the end

### Use Case

Sometimes `cdk deploy` can fail for arbitrary reasons, like hitting an account limit, or getting throttled. In these situations it would be better to be able to allow the deployment to proceed as much as possible.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.39.1

### Environment details (OS name and version, etc.)

Alpine 3.16, Python 3.10.6

**Comment by indrora** [comment]
The CDK, by design, makes the guarantee that the deployment was completed. A CDK Application is defined as a series of stacks, on purpose, and inherently that means that the CDK Application lifecycle depends on all stacks within an application deploying correctly. 

If you wish to have stacks that may fall out of sync with one another, you can use cross-stack resources and multiple applications.

**Comment by rittneje** [comment]
> If you wish to have stacks that may fall out of sync with one another, you can use cross-stack resources and multiple applications.

Except CDK already lets them "fall out of sync" in a significantly worse way, by unnecessarily aborting the entire deployment halfway through. In other words, the current behavior is not desirable to anyone.
