### ISSUE TITLE
(aws-eks): instanceType is deprecated, use instanceTypes instead

### ISSUE THREAD

**Issue by bora-7** [aws/aws-cdk#22547]
### Describe the bug
There are some integ tests in aws-eks using the deprecated instanceType instead of the instanceTypes and yarn test throws a lot of warnings.

### Expected Behavior

No more warnings for deprecated 'instanceType' properties from 'yarn test'

### Current Behavior

There are warning signs since _instanceType_ is now deprecated and _instanceTypes_ should be used instead

### Reproduction Steps

yarn test on aws-eks

### Possible Solution

Change mentions of instanceType to 'instanceTypes'

### CDK CLI Version

2.44.0

### Node.js Version

v16.13.2

### OS

MacOS

### Language

Typescript

**Comment by MrSyn88** [comment]
Working on it

**Comment by peterwoodworth** [comment]
What's the bug you're describing exactly? We deprecated this prop [two years ago](https://github.com/aws/aws-cdk/pull/11962), so you should only be able to use `instanceType` in v1, and if you do so in v1 you should see this warning message because we want to throw warnings when properties are deprecated.

**Comment by bora-7** [comment]
I've updated the description now to make it more clear
