### ISSUE TITLE
service catalog: Invalid request provided

### ISSUE THREAD

**Issue by lobo1111** [aws/aws-cdk#22557]
### Describe the bug

I'm trying to create a chain of products in the service catalog.
Here is my case:
I have three products in the portfolio:
1) infrastructure
2) application
3) platform
Infrastructure and application products may be provisioned separately. Platform product should provision infrastructure, catch the output and use it as parameters for application product.
Infrastructure and application products work as expected but I can't aggregate them under a third product.

### Expected Behavior

I should be able to provision product called Platform that is an aggregate of products Infrastructure and Application

### Current Behavior

Product provision fails with this cryptic message:
`2:11:28 PM | CREATE_FAILED        | AWS::ServiceCatalog::CloudFormationProvisionedProduct | infrastructure
Resource handler returned message: "Invalid request provided: AWS::ServiceCatalog::CloudFormationProvisionedProduct" (RequestToken: xxxxxxxx, HandlerErrorCode: InvalidRequest)
`

### Reproduction Steps

Piece of code I created:

```
export class MyPlatform extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    servicecatalog.CfnCloudFormationProvisionedProduct.
    const infrastructure = new servicecatalog.CfnCloudFormationProvisionedProduct(this, 'infrastructure', {
        productId: 'prod-xxx',
        provisioningArtifactName: 'v1',
        pathId: "lpv2-xxx",
    })
  }
}

const app = new cdk.App();
new MyPlatform(app, 'prod-prov', {});
```

I tried to execute it directly this way:
`npx cdk deploy prod-prov`

Doesn't work either if I try to synthesize yaml and upload it directly to CloudFormation

*I'm able to provision infrastructure product with no issues.

### CDK CLI Version

2.46.0 (build 5a0595e)

### Node.js Version

v16.18.0

### OS

Ubuntu 22.04.1 LTS

### Language

Typescript

### Language Version

4.8.4

**Comment by peterwoodworth** [comment]
@lobo1111 You're not actually running into any CDK issues here. You're essentially just using CloudFormation since you're using only our L1 resources which are just copies of CloudFormation resources.

Looking at your definition it's impossible to say why this error is occurring. The message is unhelpful - the service isn't throwing an actual error message. I would recommend reaching out to AWS support if you have it to help you figure out why it's throwing this error for you. 

Unfortunately there's not going to be anything else we can help with here since you're not using any of our abstractions and are essentially just using CloudFormation/ServiceCatalog here. If you want help from the community in figuring out how to use this L1 construct I would recommend opening a discussion, or asking the slack channel at [cdk.dev](https://cdk.dev). Thanks!
