### ISSUE TITLE
Unclear sentence under "Design" section in `CONTRIBUTION.md`

### ISSUE THREAD

**Issue by azatoth** [aws/aws-cdk#22601]
### Describe the issue

Currently, for the section "Step 2: Design" (also marked as "optional" in the TOC);
It contains the following paragraphs:

> In some cases, it is useful to seek feedback by iterating on a design document. This is useful when you plan a big change or feature, or you want advice on what would be the best path forward.
>
> In many cases, the GitHub issue is sufficient for such discussions, and can be sufficient to get clarity on what you plan to do. If the changes are significant or intrusive to the existing CDK experience, and especially for a brand new L2 construct implementation, please write an RFC in our [RFC repository](https://github.com/aws/aws-cdk-rfcs) before jumping into the code base. L2 construct implementation pull requests will not be reviewed without linking an approved RFC.

The main issue I see is that the last sentence "L2 construct implementation pull requests will not be reviewed without linking an approved RFC" are:

1. It contradict the rest of the sections, i.e. it makes it a strict requirement instead of a possible suggestion.
2. If we are referring to that RFCs must already exists, then it makes it implausible to create a PR for an already existing L2 construct if it doesn't already have an RFC.
3. If we are meaning that you need to create an RFC for any implementation and have it approved first, then it stifles any community participation, slows everything down to a halt, and makes it a bureaucratic hell.

I would suggest to drop this language altogether.

### Links

https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-2-design

**Comment by peterwoodworth** [comment]
Thanks for letting us know about this section @azatoth, I agree that it's unclear and misleading. 

I'm not sure that the RFC rule is strict about needing a new RFC for every individual new L2 construct. That could be obstructive more than constructive in some cases, like for each new IOT action we can add and other similar constructs. I'd imagine that at the very least for this case we would only need to approve an RFC for an arbitrary action rather than an RFC for every individual action.

Looking at these actions, it doesn't seem there was an RFC at all but rather discussion went on in the [initial reported issue](https://github.com/aws/aws-cdk/issues/17711) with a team member. So I wouldn't be worried about trying to contribute more actions in this case.

We will figure out how to make our requirements much more clear soon and then update the guide 🙂

**Comment by peterwoodworth** [comment]
we'll be updating this soon. Closing now so that this issue doesn't linger unnecessarily, thanks for reporting
