### ISSUE TITLE
IAM Role: Grant cloudformation:SignalResource on Cloud Formation Stack

### ISSUE THREAD

**Issue by qvissak** [aws/aws-cdk#22655]
### Describe the feature

Create a method on IAM roles, namely `props.iamRole.grantSignalResourceOnCloudFormationStack(this)` to grant a stack (`this`) the permissions `cloud formation signal resource/describe stack resource` .

### Use Case

CDK automatically adds this IAM policy to the IAM role created within a stack:

```
        {
            "Action": [
                "cloudformation:DescribeStackResource",
                "cloudformation:SignalResource"
            ],
            "Resource": "<arn-of-stack>",
            "Effect": "Allow"
        }
```

so that the resources created within the CF stack can callback to CF to signal said resource(s) are done mutating.

Without a deep dive, a user of CDK doesn't know this, and everything "just works". However, if a user creates an IAM role in one stack, and passes that IAM role to be used by another stack, they will run into issues where the resources created in that other stack can never communicate back to CF that they are done mutating -- that is, without this policy on the resource that is the second stack.

It doesn't make sense for someone who is passing around an IAM role to have to understand this level of detail. They should be able to grant permission to the resource the same way they would for example a KMS key that is used to encrypt/decrypt files in an S3 bucket.

### Proposed Solution

The `autoScalingGroupProps` should be modified to separate the instance role and the CF role. Just like if an instance role isn't passed, one is created for you -- the same behavior would happen on the CF role. `applyCloudFormationInit` should be invoked on CF Role, not the instance role.

_No response_

### Other Information

I am an SDE at AWS. Please contact me @vissq for more information, or read SIM NADE-15680 for more details.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

AL2

**Comment by qvissak** [comment]
After some discussion with Gonzalo Vallejos, we've concluded this is a bug, not a feature request.

**Comment by qvissak** [comment]
I created https://github.com/aws/aws-cdk/issues/22657 instead

**Comment by vgonzalo** [comment]
I think this can be considered a bug, the problem is in [CfnInit](https://github.com/aws/aws-cdk/blob/v2.47.0/packages/@aws-cdk/aws-ec2/lib/cfn-init.ts#L113-L116) and the [AutoScalingGroup construct](https://github.com/aws/aws-cdk/blob/v2.47.0/packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts#L1587-L1600), they add the cloudformation permissions to the Role principal/default policy, so when the Role comes from another stack the policy statement is added to the Role's stack, hence the StackId pseudo-parameter is resolved to the Role's stack and not the CfnInit/ASG stack.

Since is not possible to add a policy statement to the Role's stack targeting the CfnInit/ASG stack (due to a circular dependency), a new policy should be created in the CfnInit/ASG stack that can reference the IAM role to add this new policy, for example in CfnInit it should be something like this:

```
new iam.Policy(this, 'cloudformation-cfn-init-policy', {
  roles: [attachOptions.instanceRole],
  statements: [
    new iam.PolicyStatement({
      actions: ['cloudformation:DescribeStackResource', 'cloudformation:SignalResource'],
      resources: [Aws.STACK_ID],
    }),
  ],
});
```
