### ISSUE TITLE
custom-resources: Does not conform to CFN's Custom Resource Response Specification

### ISSUE THREAD

**Issue by ianmarmour** [aws/aws-cdk#22696]
### Describe the bug

The current implementation of custom-resources provider-framework does not correctly reflect what handlers are expect to respond with based on [CFN's own resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html). 

Specifically the `Status` parameter of the response object is being ignored by the provider-framework and always returning success even when a Lambda properly returned a formatted failure, this has lead to custom resources that we've created incorrectly returning CREATE_COMPLETE even though there was an error. It's noted in the documentation for the custom-resources provider that `onEvent` handlers are expected to throw in the case of an error however CFN does not expect them to throw and instead expects them to either throw or more ideally return with a formatted error message.

### Expected Behavior

The provider framework should expect that a a valid`Status` of either `'SUCCESS' | 'FAILED'` is return from the customer provider `onEvent` handler. The indication of failure in the case of exceptions being thrown should still be supported to properly bubble up errors to customers that are un-handled.

### Current Behavior

Provider ignores the status returned by an `onEvent` handler and instead just returns `SUCCESS` even in the case of a `FAILED` response. This leads to state bugs in CFN stack resources that are CustomResources back by this framework with a handler that is properly configured per CFN's specification.

### Reproduction Steps

```ts
// Example onEvent handler

const handler = (event) => {
  const response = {
    Status: 'FAILED',
    Reason: "Some valid reason to fail",
    StackId: event.StackId,
    RequestId: event.RequestId,
    response.Data = {
      Response: null
    }
  }

  return response;
}

const provider = new customResource.Provider(this, 'Provider' {
  onEventHandler: handler
});

// Implement some custom resource to manager here.
```

### Possible Solution

There's a few potential solutions to this that are simple,

1. Always expect a valid response to contain a Status outside of exceptions (BREAKING) [Recommended] 
2. Keep existing success behavior unless a Status has been submitted (Non-Breaking maybe?)

### Additional Information/Context

For context anybody using this framework at the moment should be impacted, unless they're using an anti-pattern of just not handling any exceptions and throwing.

### CDK CLI Version

2.49.0

### Node.js Version

v18.4.0

### OS

Mac/Linux

### Language

Typescript

### Language Version

4.8

**Comment by pflorek** [comment]
Great idea! 

Maybe this is because the correct types are not used and not exported by the CDK: https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/custom-resources/lib/provider-framework/types.d.ts#L53

On one point I have a different opinion. The `provider-framework` gives us with `OnEventHandler` and `IsCompleteHandler` a shortcut to create synchron and asynchron resource handlers. Therefore our handler implementations doesn't need to reflect the CFN resource specification. It's the responsibility of the `provider-framework`.

The current `provider-framework` interprets an error thrown in our `OnEventHandler` and `IsCompleteHandler` as FAILURE otherwise SUCCESS. I'm fine with that approach. The error message will be printed in CloudFormation. How should this work now?

**Comment by pflorek** [comment]
@ianmarmour I have created https://github.com/aws/aws-cdk/issues/22702 maybe this helps with the typings

**Comment by ianmarmour** [comment]
> Maybe this is because the correct types are not used and not exported by the CDK: https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/custom-resources/lib/provider-framework/types.d.ts#L53

Totally agreed I can actually pull in correcting the types to accurately reflect CFN's response types in the same fix if you think that would be ideal?. At the end of the day the response types of the provider-framework should match CFN's 1:1. 

> Therefore our handler implementations doesn't need to reflect the CFN resource specification. It's the responsibility of the provider-framework.

I don't know if this abstraction is actually ideal? I would personally be supportive of a BREAKING change here to a new MV that accurately reflects the mandatory CFN response type without the provider framework handling some number of modification to the data prior to CFN processing it. At the moment it is rather opaque to customers as to what is actually going on while the quality of life is there I think the confusion is also very present.

**Comment by pflorek** [comment]
@ianmarmour we have a different understanding what are the correct types and maybe what the `provider-framework` is responsible.

With correct types I mean to use the internal types `OnEventResponse` and `IsCompleteResponse` of the `provider-framework` instead of CloudFormation Custom Resources. The internal types are made available here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/054d48e9f9c36f0ca4d211f7d88a1a4a6ff956da/types/aws-lambda/trigger/cdk-custom-resource.d.ts#L24 (Really never got them in the IDE auto suggested)

The ResponseUrl from the Event should be omitted.


That's the advantage of the `provider-framework` giving us a StepFunction for asynchronous resources and sending back the response to CloudFormation. So we only have to write the handlers 

It's not a library to assist in writing plain CFN custom resources...

https://github.com/aws/aws-cdk/pull/22698#issuecomment-1297637374

The initial idea is great, we somehow need a mini library that helps writing plain CFN custom resources.

**Comment by mrgrain** [comment]
See discussio n on #22698
