### ISSUE TITLE
(cdk-lib/rds): No longer able to create output for DB Parameter Group Name

### ISSUE THREAD

**Issue by mikemill** [aws/aws-cdk#22783]
### Describe the bug

I'm trying to create a stack output with the DbParaemterGroupName for use in a different stack.  I was previously able to do this as of Oct 24.  Now, when I deploy I get an error message.

### Expected Behavior

Creation of a stack output with the resolved parameter group name.

### Current Behavior

When deploying the stack I receive the following error message:
Requested attribute DBParameterGroupName must be a readonly property in schema for AWS::RDS::DBParameterGroup

The stack then rolls back

### Reproduction Steps

This is an example stack that produces the issue.
```ts
import * as cdk from "aws-cdk-lib";
import * as rds from "aws-cdk-lib/aws-rds";

import { Construct } from "constructs";

export class ExampleStack extends cdk.Stack {
  constructor(scope: Construct, name: string, props?: cdk.StackProps) {
    super(scope, name, props)

    const pg = new rds.ParameterGroup(this, "parameterGroup", {
      engine: rds.DatabaseInstanceEngine.mysql({
        version: rds.MysqlEngineVersion.VER_8_0,
      }),
      parameters: {
        time_zone: "US/Pacific",
      },
    });

    pg.bindToInstance({});

    new cdk.CfnOutput(this, 'parameterGroupOutput', {
      value: (pg.node.defaultChild as rds.CfnDBParameterGroup).attrDbParameterGroupName,
    });
  }
}
```

### CDK CLI Version

2.50.0 (build 4c11af6)

### Node.js Version

v16.14.2

### OS

Mac OS

### Language

Typescript

### Language Version

Typescript 4.7.4

**Comment by peterwoodworth** [comment]
Thanks for reporting this issue @mikemill,

It looks like this attribute has been removed and you cannot use it in CloudFormation anymore. It was removed in the most recent [CloudFormation resource spec](https://github.com/aws/aws-cdk/commit/aa19ec05835a7c71e1aa01dcd649a4d933ef1fd8#diff-448833823999f11d01885d768d952386baf95b8d41a7096616d5d96e81acce0d), and also [doesn't appear on CloudFormation documentation as a return value](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbparametergroup.html#aws-resource-rds-dbparametergroup-return-values).

Instead, you can use `.ref` which returns the name as well. It's possible the property you were using has been removed due to redundancy with `ref`.

**Comment by mikemill** [comment]
@peterwoodworth Thank you very much for the information.  I have confirmed that changing `attrDbParameterGroupName` to `ref` works to export the parameter group name.
