### ISSUE TITLE
(cdk-pipelines): fail to deploy support stack for cross region codepipeline

### ISSUE THREAD

**Issue by gabrielcolson** [aws/aws-cdk#22980]
### Describe the bug

I am trying to setup the following pipeline system, which consists of a mix between `cdk-pipelines` and `codepipeline`:

![image](https://user-images.githubusercontent.com/33499903/202772755-493a252d-8328-47dc-9f11-23f4844264f2.png)

The CDK pipeline deploys the ECS clusters to multiple environments (different accounts) and possibly to multiple regions. This pipeline also deploys a `codepipeline.Pipeline` which is responsible for deploying the new versions of the application.

The "Infra Pipeline" fails to deploy the codepipeline cross region setup stack with this error (step `Deploy (6)` from the above schema):

```
The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: VYBDWK51E2J0DRFZ; S3 Extended Request ID: 2bcc7c5BvCYULULqc6We3+AqGbZszKsLdqGua893OXPwqtdWJzlAcqMew5eZakxor08wMbLw4tU=; Proxy: null)
```

### Expected Behavior

The setup stack should be successfully deployed.

### Current Behavior

The CDK Pipeline fails before the CloudFormation deployment.  

### Reproduction Steps

I have created a minimal reproduction repository [here](https://github.com/gabrielcolson/cdk-cross-region-repro). The README contains all the information needed to deploy the app to your accounts and reproduce the error.

### CDK CLI Version

2.50.0 (build 4c11af6)

### Node.js Version

v16.16.0

### OS

macOS Monterey 

### Language

Typescript

**Comment by gabrielcolson** [comment]
If I run `npx cdk deploy cdk-cross-region-repro/app-pipeline/Pipeline --profile <pipeline-account-profile>` the app pipeline is deployed successfully.

The problem definitely comes from the cdk pipeline.

**Comment by rix0rrr** [comment]
Can you dive a little deeper and tell us:

* What resource failed to deploy
* Copy/paste the CloudFormation YAML definition from that resource
* Tell us why you think it should have succeeded

?

**Comment by terokaisti** [comment]
I faced the same error after adding `cloudfront.experimental.EdgeFunction()` to a stack that was deployed to a `eu-west-1` region. The pipeline halted exactly on the same step with `The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access` error message.

In my case, the problem was resolved after I reran `cdk bootstrap` on all accounts and regions (`eu-west-1` and `us-east-1`) with the latest CDK version. There was probably a CDKToolkit stack version conflict between accounts and regions that prevented CDK Pipelines to deploy new stack versions to cross-region accounts.
