### ISSUE TITLE
lambda: logRetention gets overridden

### ISSUE THREAD

**Issue by jabalsad** [aws/aws-cdk#22995]
### Describe the bug

I create a LogGroup for every LambdaFunction so that I can manage the `removalPolicy`:

``` 
    const functionName = cdk.Names.uniqueId(this);
    const logGroup = new logs.LogGroup(this, "Logs", {
      logGroupName: `/aws/lambda/${functionName}`,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      retention: logs.RetentionDays.THREE_MONTHS,
    });

    const props: lambda.FunctionProps = {
      functionName: functionName,
      ...
    };
```

However, it seems that CDK's lambda LogRetention function just overrides the retention period that I am specifying. It is set to `INFINITE` after the stack is deployed.

### Expected Behavior

Expect that LogGroup resource is set to the retention days specified.

### Current Behavior

LogGroup retentionDays is set to infinite.

### Reproduction Steps

See description.

### Possible Solution

Disable CDK LogRetention lambda function

### CDK CLI Version

2.50.0

### Node.js Version

16

### OS

Mac OSx

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this @jabalsad,

This is actually [documented behavior](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#loggroup), due to how the LogRetention construct works & how log groups are created when creating a Lambda. Should work fine when setting the [logRetention](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#logretention) prop
