### ISSUE TITLE
aws-iam: Using same role in multiple stacks can cause existing role policies to be removed

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-cdk#23080]
### Describe the bug

When a role is imported in multiple CDK apps by name via `Role.fromRoleName`, whichever one is deployed last overwrites any default policy that was created before.

### Expected Behavior

Each `Role.fromRoleName` should create its own default policy based on a hash for the position in the stack.

### Current Behavior

Each `Role.fromRoleName` should create its own default policy to avoid overwriting changes.

### Reproduction Steps

Create a role called `DeploymentRole`. Deploy the following two apps (only difference is the id of the stack):

```
const app = new App();
const stack = new Stack(app, "Stack1");
const bucket = new Bucket(stack, "Bucket");

const deploymentRole = Role.fromRoleName(
  this,
  "DeploymentRole",
  "DeploymentRole",
);

bucket.grantWrite(deploymentRole);
```

```
const app = new App();
const stack = new Stack(app, "Stack2");
const bucket = new Bucket(stack, "Bucket");

const deploymentRole = Role.fromRoleName(
  this,
  "DeploymentRole",
  "DeploymentRole",
);

bucket.grantWrite(deploymentRole);
```

Observe that `DeploymentRole` has only write access to the app that was deployed last and that the name of the policy for this is the same in both synthesized templates.

### Possible Solution

Setting a defaultPolicyName based on the uniqueId of the construct solves the issue. As a work around, this can be done manually:
```
const deploymentRole = Role.fromRoleName(
  this,
  "DeploymentRole",
  props.deploymentRoleName,
  { defaultPolicyName: `DeploymentPolicy${Names.uniqueId(this)}` }
);
```

A solution could be to change the [default in ImportedRole](https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-iam/lib/private/imported-role.ts#L46) to be `\`Policy${Names.uniqueId(this)}\`` instead of `Policy` (and move the default into the constructor) so that it is accessible as `this.defaultPolicyName`). Like any bug fix, this is potentially a breaking change, but since `defaultPolicyName` can be set as a prop, it should only affect people who relied on an internal implementation they shouldn't have relied on.

### CDK CLI Version

2.51.1

### Node.js Version

16.14.2

### OS

Windows

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this issue, I'm able to confirm the behavior you're seeing.

To further demonstrate this behavior, I can see the same no matter which grant I am using on any construct

```ts
export class FirstStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: FirstStackProps) {
    super(scope, id, props);

    const bucket = new Bucket(this, 'Bucket', {
      autoDeleteObjects: true,
      removalPolicy: RemovalPolicy.DESTROY
    })
    const roleB = Role.fromRoleName(this, 'RoleB', 'MyRole')
    bucket.grantWrite(roleB)
  }
}

export class SecondStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: SecondStackProps) {
    super(scope, id, props);

    const fn = new Function(this, 'MyFn', ...)
    const roleB = Role.fromRoleName(this, 'RoleB', 'MyRole')
    fn.grantInvoke(roleB)
  }
}
```

The policy from the first stack will no longer be on the role after both stacks are done deploying because the `PolicyName` is rendered the same in both.

The policy seems to be getting generated based off the role, so any policy added this way will run into this issue. I think you're right that the name here should be in part calculated by the stack name or any other context which will prevent this from occurring, this would likely need to be behind a feature flag.

While this is able to be worked around as you mention with the `defaultPolicyName` option, this definitely shouldn't be the default behavior as this is a bit easy to run into if you're using the same role in multiple stacks. Thanks for reporting!

**Comment by dbartholomae** [comment]
I've started working on a PR to solve this:
https://github.com/aws/aws-cdk/pull/23100

**Comment by dbartholomae** [comment]
The PR is mostly finished. Only thing missing is to update the snapshots for the new integration test. I couldn't get them to run locally, unfortunately, and would be happy if someone else could update the snapshots for me.
