### ISSUE TITLE
Case of a missing PR for k8s v1.24

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#23139]
### Describe the bug

I noticed that my PR (https://github.com/aws/aws-cdk/pull/22945) got approved & merged in few days ago, but it never really got merged in back into main and released. 

Any ideas what happened? Did my PR hit an edge case or something?

cc @kaizencc  @rix0rrr @pahud 

### Expected Behavior

My PR should've been merged in properly.

### Current Behavior

My PR is missing from the main brranch.

### Reproduction Steps

N/A

### CDK CLI Version

2.53.0

### Node.js Version

18.2.0

### OS

OSx

### Language

Typescript

**Comment by kaizencc** [comment]
Hi @robertd, the commit is here: https://github.com/aws/aws-cdk/commit/cc957d619c776244b068fdc19bfa15194192fa32

You're probably concerned that our latest releases do not include it. That is because we are only releasing re:invent critical features at the moment. Things should resume as normal next week and your commit should be released then.

**Comment by robertd** [comment]
Ah… code freeze. I forgot about it. That’s makes perfect sense. Thanks @kaizencc.
