### ISSUE TITLE
aws-autoscaling: Use launch templates instead of deprecated launch configurations

### ISSUE THREAD

**Issue by kichik** [aws/aws-cdk#23165]
### Describe the feature

We just got an email from AWS saying launch configurations are deprecated. New accounts won't allow creating launch configurations after December 31st, 2023. No new features or instance types will be available after December 31st, 2022.

Unless given a launch template, [AutoScalingGroup](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.AutoScalingGroup.html) always creates a deprecated launch configuration.

### Use Case

Deploying existing CDK apps that use [AutoScalingGroup](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.AutoScalingGroup.html) without manually specifying a manually created launch template would fail soon. Using new instance types will be impossible without first manually creating a launch template.

### Proposed Solution

It would be great if [AutoScalingGroup](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.AutoScalingGroup.html) could start creating launch templates instead of launch configurations.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.52.0

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
Thanks for the request, this is something we should definitely have on our radar especially as the deprecation date nears at the end of next year

**Comment by kvndng-amz** [comment]
More information on timelines from the email received:

> The following are key dates for launch configuration deprecation:
> 
>     December 31, 2022
>     - No new EC2 features or new EC2 instance types will be added to launch configurations after this date.
> 
>     March 31, 2023
>     - New accounts created after this date will not be able to create new launch configurations via the console. API and CLI access will remain available to support customers with automation use cases.
> 
>     December 31, 2023
>     - New accounts created after this date will not be able to create new launch configurations.

This sounds like a fairly sizable change, but it would be nice if any functionality being deprecated could be replaced with the launch template equivalent before the respective date of deprecation.

**Comment by simonrouse9461** [comment]
@peterwoodworth Any update on this? Our team also received an email notification about the launch configuration deprecation. However, we are having a hard time to migrate because the `LaunchTemplate` construct doesn't support `CloudFormationInit`. We've considered one alternative, which is using `CfnLaunchTemplate` to manually attach `metadata` then manually configure `userData`, but that will make the code way more complicated and error-prone.

**Comment by azatoth** [comment]
@peterwoodworth Any progress on this? We are nearing the second key date and there hasn't been any progress on the issue. What can we do to help?

**Comment by mbp** [comment]
We have the same problem - not able to migrate to launch templates because it is not possible to attach CloudFormationInit to LaunchTemlpate.

**Comment by hervenivon** [comment]
We just received a reminder deprecation notice. `"[Reminder] Ending Amazon EC2 Launch Configurations Console support for new accounts"`

I would love to hear an official voice.

Best,

**Comment by colifran** [comment]
Hi everyone. I wanted to comment to say that this is in progress and is currently being worked on.

**Comment by mbp** [comment]
@colifran 

Sorry for late response.

I tried with the following code:

```
    const launchTemplate = new ec2.LaunchTemplate(this, "LaunchTemplate", {
      role: launchRole,
      requireImdsv2: true,
      securityGroup: launchTemplateSecurityGroup,
      instanceType: instanceType,
      machineImage: machineImage,
      blockDevices: [
        {
          deviceName: "/dev/sda1",
          volume: autoscaling.BlockDeviceVolume.ebs(50, {
            encrypted: true,
          }),
        },
      ],
    });
    
    const appAutoscalingGroup = new autoscaling.AutoScalingGroup(this, "ASG", {
      vpc,
      launchTemplate: launchTemplate,
      allowAllOutbound: true,
      maxCapacity: 2,
      minCapacity: 1,
      init: init,
    });    
```

As you can see - I pass `init` to the AutoScalingGroup.

But it provides the following error: `The provided launch template does not expose its user data.`

Because of this error - I tried to move cloudformation init to LaunchTemplate (without success).

**Comment by abalasky-chronos** [comment]
Hi any update on this? Currently AutoScalingGroup with CDK is still using Launch Config instead of Launch template? At least could you point me to usage for configuring my own Launch Template?

**Comment by colifran** [comment]
@abalasky-chronos I'm close to having a PR ready for review. I have the code done and am just working on getting 6 or so integ tests updated. I should have a PR in soon. In the meantime, this mapping may be able to help you configure an equivalent launch template based on launch configuration properties - https://docs.aws.amazon.com/autoscaling/ec2/userguide/migrate-launch-configurations-with-cloudformation.html#launch-configuration-mapping-reference.

**Comment by colifran** [comment]
@mbp no worries and thanks for your response. I think the issue here is that if no explicit user data is provided with the launch template, then when we try to get the user data to pass to the cfn-init configuration method when creating the auto scaling group an error is thrown since user data would be undefined. We added a feature flag to configure a launch template with default user data based on the provided machine image though. If that is set to true that error should go away. That said, I'm working on addressing this in the launch configuration deprecation since I can see how this would cause confusion.

**Comment by abalasky-chronos** [comment]
@colifran Thank you so much! Appreciate the prompt response.

**Comment by SamuelLordMO** [comment]
Slightly tangential to this issue, but the (python) [docs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_autoscaling/AutoScalingGroup.html) suggest this is already supported, but actually the `launch_template` contructor parameter isn't present. Will this being released effectively solve the discrepancy between the docs and python or should I open a new bug report?

Example output trying to use `launch_template`:

```
line 19, in build
    ...
File "<filepath>", line 73, in __init__
    asg = autoscaling.AutoScalingGroup(self, f"{stack_config.stack_name_prefix}-AutoScalingGroup",
File "\.venv\lib\site-packages\jsii\_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'launch_template'
```

**Comment by colifran** [comment]
@SamuelLordMO this seems like it would be a separate issue. The deprecation of launch configurations will result in the auto scaling group automatically generating a launch template from properties that were previously used to create a launch configuration. So, your new options will be provide a launch template, provide a mixed instances policy, or provide properties that will be used to automatically generate a launch template for you. Providing an explicit launch template is already supported, so this could be a bug. Could you provide a snippet of the code you're using so that we could try to reproduce the issue on our end?

**Comment by SamuelLordMO** [comment]
In putting together a minimal repro I found that my issue was actually an old venv that was out of date being used for synth, but not for docs/autocomplete etc. So I won't raise a bug! Thanks for your quick response, though :)

**Comment by dhanunjayravula** [comment]
> Slightly tangential to this issue, but the (python) [docs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_autoscaling/AutoScalingGroup.html) suggest this is already supported, but actually the `launch_template` contructor parameter isn't present. Will this being released effectively solve the discrepancy between the docs and python or should I open a new bug report?
> 
> Example output trying to use `launch_template`:
> 
> ```
> line 19, in build
>     ...
> File "<filepath>", line 73, in __init__
>     asg = autoscaling.AutoScalingGroup(self, f"{stack_config.stack_name_prefix}-AutoScalingGroup",
> File "\.venv\lib\site-packages\jsii\_runtime.py", line 86, in __call__
>     inst = super().__call__(*args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'launch_template'
> ```

Hi am facing same issue, can you please help me with your hack??
