### ISSUE TITLE
aws-eks: Use launch template when calling add_auto_scaling_group_capacity method

### ISSUE THREAD

**Issue by yo-ga** [aws/aws-cdk#23188]
### Describe the feature

We got the notification from AWS saying that launch configurations are deprecated. After December 31, 2022 no new Amazon Elastic Compute Cloud (Amazon EC2) instance types will be added to launch configurations.

The launch configuration is created automatically when calling `add_auto_scaling_group_capacity`.

### Use Case

Deploying existing CDK app for EKS cluster with minimal change.

### Other Information

This issue is similar with #23165 but for aws-eks module.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0

### Environment details (OS name and version, etc.)

N/A

**Comment by pahud** [comment]
Yes!

According to 

https://github.com/aws/aws-cdk/blob/d13b64af178579ae57ddc6da8d1fb53f26ac9777/packages/%40aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts#L1186

I think we should add prop.launchTemplate to the ASG here:

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1674-L1686

Are you interested to investigate and submit a PR for that?

**Comment by yo-ga** [comment]
Hi @pahud, I'd like to submit a PR for that, but it seems that we also need to adjust the function here:

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1044-L1061

The auto scaling group with the launch configuration is not accepted to attached with a specific security group.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.AutoScalingGroup.html#securitygroup

**Comment by pahud** [comment]
@yo-ga Yes you are right. Looks like we should fix https://github.com/aws/aws-cdk/issues/23165 first.

**Comment by ArneOttenVW** [comment]
Is there any progress on this? End of 2023 is approaching fast and as of now (used cdk 2.93), autoscalinggroups created by eks still use launch configuration and there seems to be no way to manually attach a launch template on it. 

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.AutoScalingGroupCapacityOptions.html
The docs even mention something for example: "launchTemplate and mixedInstancesPolicy must not be specified when this property is specified" but launchTemplate is not even a property of eks.AutoScalingGroupCapacityOptions.

**Comment by yo-ga** [comment]
@pahud  I can't get away for now. If there is someone interested on it, kindly assign the new contributor

**Comment by pahud** [comment]
This issue is still relevant.

Now https://github.com/aws/aws-cdk/issues/23165 was resolved, I think we could add a `launchTemplate` option for [AutoScalingGroupCapacityOptions](https://github.com/aws/aws-cdk/blob/ce7a8d59b9c0351818a26c3dac299d53ca63e8ca/packages/aws-cdk-lib/aws-eks/lib/cluster.ts#L2225) and pass that option to [here](https://github.com/aws/aws-cdk/blob/ce7a8d59b9c0351818a26c3dac299d53ca63e8ca/packages/aws-cdk-lib/aws-eks/lib/cluster.ts#L1900-L1912). We welcome pull requests from the community.

Before we have a PR to fully support that, I think it should be possible to use [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to override the [LaunchTemplate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-autoscalinggroup.html#cfn-autoscaling-autoscalinggroup-launchtemplate) prop of the generated ASG.

**Comment by pahud** [comment]
After some in-depth investigation. I am providing my suggestions here:

1. Amazon EKS NodeGroup L2 construct literally allows you to [specify your own launchTemplate](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Nodegroup.html#launchtemplatespec) and is generally recommended to use rather than baking your own AutoscalingGroup.
2. `addAutoScalingGroupCapacity` is the only solution before Amazon EKS has managed nodegroup support. While it's very flexible, you will need to maintain your own ASG as well as the UserData, SecurityGroup and all the ingress/egress rules, which is generally not recommended.

If you are fully aware of above and you really have to bring your own ASG, consider this sample below:


```ts
export class MyStack extends Stack {
  private version = eks.KubernetesVersion.V1_30;
  private vpc: ec2.IVpc;
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    this.vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });

    // allow all account users to assume this role in order to admin the cluster
    const mastersRole = new iam.Role(this, 'AdminRole', {
      assumedBy: new iam.AccountRootPrincipal(),
    });

    const cluster = new eks.Cluster(this, 'Cluster', {
      vpc: this.vpc,
      mastersRole,
      defaultCapacity: 0,
      ...getClusterVersionConfig(this, this.version),
    });

    const myasg = cluster.addAutoScalingGroupCapacity('ASGNG', {
      instanceType: new ec2.InstanceType('t3.medium'),
      desiredCapacity: 2,
      // launchTemplate: this.getLaunchTemplate('ASGLT'),
    });

    // create my own LT
    const lt = this.getLaunchTemplate('ASGLT');
    // find the L1 LT
    const cfnlt = lt.node.tryFindChild('Resource') as ec2.CfnLaunchTemplate;
    // find the L1 ASG
    const cfnasg = myasg.node.tryFindChild('ASG') as asg.CfnAutoScalingGroup;
    // override the properties
    cfnasg.addPropertyOverride('LaunchTemplate', {
      LaunchTemplateId: lt.launchTemplateId,
      // Version: cfnlt.attrLatestVersionNumber,
      Version: cfnlt.attrDefaultVersionNumber,
    });
    // delete the default LT auto-generated from myasg(we don't need that)
    myasg.node.tryRemoveChild('LaunchTemplate');
  }
  private getLaunchTemplate(id: string): ec2.ILaunchTemplate {
    return new ec2.LaunchTemplate(this, id, {
      instanceType: new ec2.InstanceType('t3.medium'),
      machineImage: new eks.EksOptimizedImage({
        nodeType: eks.NodeType.STANDARD,
        cpuArch: eks.CpuArch.X86_64,
        kubernetesVersion: this.version.version,
      }),
      securityGroup: new ec2.SecurityGroup(this, `${id}SG`, { vpc: this.vpc }),
    });
  }
}

const devEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: process.env.CDK_DEFAULT_REGION,
};

const app = new App({
  context: {
    ['@aws-cdk/aws-autoscaling:generateLaunchTemplateInsteadOfLaunchConfig']: true,
  },
});

new MyStack(app, 'demo-dev', { env: devEnv });

app.synth();
```

What's happening behind the scene:

1. By enabling the [generateLaunchTemplateInsteadOfLaunchConfig](https://github.com/aws/aws-cdk/blob/9bd92da62d8c4594a11f4ab078f07b8c20762329/packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md#aws-cdkaws-autoscalinggeneratelaunchtemplateinsteadoflaunchconfig) feature flag, which was introduced since 2.88.0, when you create a `new AutoscalingGroup()`, a `LaunchTemplate` would be created rather than a `LaunchConfiguration`.
2. You need to bake your own LaunchTemplate and replace the default one with escape hatches.
3. You will be responsible for everything in your own LaunchTemplate.
4. You can optionally remove the build-in LaunchTemplate as shown in the sample above.

Let me know if it works for you.
