### ISSUE TITLE
autoscaling: osType fix not available in 1.181.1 Nuget package

### ISSUE THREAD

**Issue by ahelton-ips** [aws/aws-cdk#23212]
### Describe the bug

Bug has is described in issue [20304](https://github.com/aws/aws-cdk/issues/20304).

The issue was marked as fixed by PR [#20759](https://github.com/aws/aws-cdk/pull/20759)

The fix has not been released to Nuget package for v1.181.1. 

We need the fix to be able to migrate to launch templates from launch configurations by the end of December.

### Expected Behavior

Bug has is described in issue [20304](https://github.com/aws/aws-cdk/issues/20304).

The issue was marked as fixed by PR [#20759](https://github.com/aws/aws-cdk/pull/20759)

### Current Behavior

Bug has is described in issue [20304](https://github.com/aws/aws-cdk/issues/20304).

The issue was marked as fixed by PR [#20759](https://github.com/aws/aws-cdk/pull/20759)

### Reproduction Steps

Bug has is described in issue [20304](https://github.com/aws/aws-cdk/issues/20304).

The issue was marked as fixed by PR [#20759](https://github.com/aws/aws-cdk/pull/20759)

### Possible Solution

The issue was marked as fixed by PR [#20759](https://github.com/aws/aws-cdk/pull/20759)

### CDK CLI Version

1.181.1

### Node.js Version

16.15.1

### OS

Windows

### Language

.NET

**Comment by peterwoodworth** [comment]
We stopped releasing new fixes and features for v1 aside from fixes/features of critical importance. This is because v1 entered maintenance mode earlier this year. See the announcement [here](https://aws.amazon.com/blogs/developer/version-1-of-the-aws-cloud-development-kit-aws-cdk-is-now-in-maintenance-mode/) for more info

Please upgrade to v2 to be able to use the best version of the CDK. Else, you will likely have to resort to escape hatches to get the functionality you desire. Thanks!
