### ISSUE TITLE
(aws-servicecatalogappregistry-alpha): Unable to add nested stack to AppRegistry Application via Application.associateApplicationWithStack 

### ISSUE THREAD

**Issue by jessieweiyi** [aws/aws-cdk#23254]
### Describe the bug

I have a CDK app including a main stack with a few nested stack. I am trying to create an AppRegistry Application for the CDK app.  

The App Registry application is created using Application construct and using the context of main stack. I tried to call associateApplicationWithStack to add the main stack and nested stack. However I am getting the error below when synth the app: 

Error: Nested stack 'TestCdkAppStack/NestStack1' cannot depend on a parent stack 'TestCdkAppStack': undefined
    at Object.addDependency (/Users/jeswei/dev/temp/test-cdk-app/node_modules/aws-cdk-lib/core/lib/deps.js:1:1040)
    at NestedStack.addDependency (/Users/jeswei/dev/temp/test-cdk-app/node_modules/aws-cdk-lib/core/lib/stack.js:1:5409)
    at Application.associateApplicationWithStack (/Users/jeswei/dev/temp/test-cdk-app/node_modules/@aws-cdk/aws-servicecatalogappregistry-alpha/lib/application.ts:150:15)
  
The main stack can be associated with the application.

Using .associateAllStacksInScope will have the same error. 

I would like to keep the app with one main stack only. What is the best way to achieve this?

### Expected Behavior

The nested stack should be able to be associated with the app registry application. 

### Current Behavior

Error in synth when using associateApplicationWithStack to add nested stack:

Error: Nested stack 'TestCdkAppStack/NestStack1' cannot depend on a parent stack 'TestCdkAppStack': undefined
    at Object.addDependency (/Users/jeswei/dev/temp/test-cdk-app/node_modules/aws-cdk-lib/core/lib/deps.js:1:1040)
    at NestedStack.addDependency (/Users/jeswei/dev/temp/test-cdk-app/node_modules/aws-cdk-lib/core/lib/stack.js:1:5409)
    at Application.associateApplicationWithStack (/Users/jeswei/dev/temp/test-cdk-app/node_modules/@aws-cdk/aws-servicecatalogappregistry-alpha/lib/application.ts:150:15)

### Reproduction Steps

https://github.com/jessieweiyi/test-cdk-app-app-registry-error

### CDK CLI Version

2.53.0

### Node.js Version

14

### OS

Mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
I made a slight modification to work around this and successfully deploy an application with both the stack and nested stack being resources associated with it. Here's the modified code:

```
    // appRegistryApp.associateApplicationWithStack(nestedStack1);

    new CfnResourceAssociation(nestedStack1, 'AppRegistryAssociation', {
      application: appRegistryApp.applicationName!,
      resource: nestedStack1.stackId,
      resourceType: 'CFN_STACK'
    })
```

The code here is creating the behavior you are encountering because we are manually adding a dependency from the stack to add to the stack the Application was created in. This doesn't work in this case because a nested stack cannot depend on its parent stack https://github.com/aws/aws-cdk/blob/7690f431da3cd365c5356194ca62168bfeaeea5a/packages/%40aws-cdk/aws-servicecatalogappregistry/lib/application.ts#L140-L153

It makes sense to add this when the stack is not a nested stack. Perhaps we should introduce a new method specifically for NestedStacks, or alternatively we can add a separate functionality to the existing method if it's detected the stack passed in is a nested stack. Thanks for reporting!

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we can try to review a PR 🙂

**Comment by santanugho** [comment]
This issue has now been handled in `v2.55.0-alpha.0`. Please upgrade to this new version and re-test.

**Comment by peterwoodworth** [comment]
Thanks for handling this @santanugho, it's very much appreciated! 😄 

Small nitpick but a request all the same, next time you contribute can you be sure to link the associated issue in the PR? Thanks again!
