### ISSUE TITLE
aws-s3-deployment: Wrong URL in BucketDeployment.deployedBucket.bucketWebsiteUrl

### ISSUE THREAD

**Issue by iwasinnam** [aws/aws-cdk#23354]
### Describe the bug

I deploy a static website using s3 deployment, and print the endpoint from BucketDeployment.deployedBucket.bucketWebsiteUrl. When deploying to Frankfurt region the URL I get http://my-sweet-stack-123456789-xxxxxxxxxx.s3-website-eu-central-1.amazonaws.com/

That is, the URL I received has a **hyphen** before the region name, but the actual endpoint is actually with a **dot** (...s3-website.eu-central-1...)

### Expected Behavior

The actual URL is http://my-sweet-stack-123456789-xxxxxxxxxx.s3-website.eu-central-1.amazonaws.com/

As is indeed documented here: [Amazon S3 website endpoints](https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_endpoints)

### Current Behavior

The URL in BucketDeployment.deployedBucket.bucketWebsiteUrl is wrong and leads nowhere.

### Reproduction Steps

1. Deploy a static website to eu-central-1 region
2. Print .deployedBucket.bucketWebsiteUrl of the bucket you just deployed
3. Compare to the URL that appears in the console of S3 (bucket -> Properties -> Static web hosting)
4. They're different!

### Possible Solution

If had to guess I'd say that either there's a typo in the table that maps regions to static hosting endpoint URL format, or there is no such table.

### CDK CLI Version

2.54.0 (build 9f41881)

### Node.js Version

v12.22.9

### OS

Ubuntu 22.04.1

### Language

Typescript

**Comment by peterwoodworth** [comment]
When we return the `deployedBucket` prop, we are returning the following:

https://github.com/aws/aws-cdk/blob/1485f48c515f81fa585a325e02f1602f56443605/packages/%40aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts#L463-L467

I can't see anywhere else where we are setting `_deployedBucket`, so this should always return an import `Bucket.fromBucketArn`

`fromBucketArn` will call `fromBucketAttributes` under the hood, only supplying the `bucketArn` attribute. You can see here how `fromBucketAttributes` calculates its other properties by default:

https://github.com/aws/aws-cdk/blob/1485f48c515f81fa585a325e02f1602f56443605/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1612-L1624

`websiteDomain` will be set to `${bucketName}.s3-website-${region}.${urlSuffix}` because `newUrlFormat` is disabled by default. Then `bucketWebsiteUrl` will be set to this `websiteDomain`: `http://${websiteDomain}`

We should be able to calculate this ourselves based on the region using the [docs you linked](https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_endpoints). And if not, we should offer a way to override this setting. Thanks for reporting!

**Comment by mrgrain** [comment]
@peterwoodworth I don't think we can calculate this just from the ARN. Unfortunately Bucket ARNs do not contain a region.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-arn-format.html

**Comment by mrgrain** [comment]
#23919 will fix this for scenarios where the destination bucket is in the same region as the stack.
