### ISSUE TITLE
(apigatewayv2): Allow to set Lambda authorizer with authorizer type Cognito and use user pool for CfnApi

### ISSUE THREAD

**Issue by wakeupmh** [aws/aws-cdk#23411]
### Describe the feature

Please allow us to set a Lambda authorizer with a user pool for a WebSocket API using CfnApi.
Currently, we cannot set it because there's no interface.

### Use Case

Restrict access to a WebSocket API by cognito auth using user pool

### Proposed Solution

Setting an authorizer for a WebSocket API is quite simple.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-route.html

Because you can only set authorizer for $connect route and Only REQUEST authorizer type is supported on WEBSOCKET protocol Apis, so when I want to use a authorizer type cognito with userpool I can't create it

So please add the capability to add Cognito as authorizer type and use userpool to authorize it based on token

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.45.0

### Environment details (OS name and version, etc.)

Mac OS Monterey version 12.4

**Comment by peterwoodworth** [comment]
Hey @wakeupmh, it seems that this isn't possible through CloudFormation, which means we will need their support first for us to be able to implement this feature. 

I believe that the use case for using a UserPool with an HttpApi is covered through the `JWT` authorizationType option. However, the documentation doesn't specify that this option is supported for a WebSocketApi. This, or as you mention an option like `COGNITO`, would need to be a valid option for WebSocket APIs created through CloudFormation. 

I'm honestly unsure this is a valid thing to do at all in AWS, given the documentation [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-control-access.html) doesn't mention User Pools at all. If you can verify that this is possible at all, that would be great 🙂 

If it is possible, and since we'd need their support on this, I recommend creating an issue in the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) if one doesn't already exist.
