### ISSUE TITLE
CDK CLI:CDK_DEFAULT_REGION is incorrect

### ISSUE THREAD

**Issue by quintonn** [aws/aws-cdk#23440]
### Describe the bug

When I run `cdk synth --profile profile-name` the wrong values are set in the environment variables **process.env.CDK_DEFAULT_REGION** and **process.env.CDK_DEFAULT_ACCOUNT**  

The profile flag does seem to work for the credentials, because without it the command fails as I did remove the [default] values in the .aws/config and .aws/credentials files.

### Expected Behavior

I expect the region and account to be read from the .aws/config file, but it is not.  

### Current Behavior

An old, incorrect or cached value is set in the process.env.CDK_DEFAULT_REGION and process.env.CDK_DEFAULT_ACCOUNT variables.

### Reproduction Steps

Run `cdk synth --profile profile-name` and also log the process.env.CDK_DEFAULT_REGION variable and see that it is incorrect.  

Set the region in .aws/config to something like eu-west-1 for the named profile

### CDK CLI Version

2.55.1

### Node.js Version

v18.12.1

### OS

Windows 10 - 21H2 19044.2364

### Language

Typescript

**Comment by pahud** [comment]
Hi @quintonn 

I can't reproduce this from my IDE.

This is my ~/.aws/config. Please note the default region is `ap-northeast-1`.
```
[profile demo]
region = ap-northeast-1
output = json
```

And if I print the env vars with console.log in my main.ts

```ts
console.log(process.env.CDK_DEFAULT_ACCOUNT)
console.log(process.env.CDK_DEFAULT_REGION)
```

And run cdk diff like this:

```
npx cdk --profile demo diff
```
I got my account id and default region correctly.
```
<reducted>
ap-northeast-1
```

**Comment by jashgala** [comment]
I tried various iterations of this issue with my global CDK installation (v2.56.0) on my laptop (macOS).

**Attempt 1:** Broken
I tried it with my credentials defined in ~/.aws/credentials
```
[bug]
aws_access_key_id=*************
aws_secret_access_key=*************
```
And my region defined in ~/.aws/config.
```
[bug]
region = ap-northeast-1
```

However, when I ran `cdk diff --profile bug`, it printed the correct AWS account but with the region from my `[default]` profile.

**Attempt 2:** Broken
At first I thought this might be related to credentials and region being split across two files, so I checked if this happens when I have credentials defined in the config file ~/.aws/config:
```
[bug]
aws_access_key_id=*************
aws_secret_access_key=*************
region=ap-northeast-1
```
The behavior was the same (correct account, but wrong region).

**Attempt 3:**  Working
Looking at @pahud's example, I fixed my configuration as `[profile bug]` instead of just `[bug]` in my ~/.aws/config and it started picking the correct region in both scenarios.
```
[profile bug]
aws_access_key_id=*************
aws_secret_access_key=*************
region=ap-northeast-1
```

**Attempt 4:** Working
Next I tried splitting the configuration between config and credentials similar to example one. But it only works when I specify it as `[profile bug]` in ~/.aws/config but as `[bug]` in ~/.aws/credentials.
~/.aws/config:
```
[profile bug]
region=ap-northeast-1
```
~/.aws/credentials:
```
[bug]
aws_access_key_id=*************
aws_secret_access_key=*************
```

**Conclusion:** Based on the above, I believe the syntax for declaring profiles is different for `~/.aws/credentials` and `~/.aws/config` and chances are you might have mixed them up while setting up your environment. Would suggest checking for this to confirm whether it is just a typo or an actual issue.

**Comment by rix0rrr** [comment]
The fact that you have to write `[prof]` in one file and `[profile prof]` in the other is the standard across all of the AWS CLI and other tools, and though weird probably has a reason (that I'm not aware of) and is probably impossible to fix by now: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

So that's just what it is.

**Comment by pahud** [comment]
Hi @jashgala 

According to [Named profiles for the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html), you must specify `[profile bug]` in your ~/.aws/config as "config profile" rather than just `[bug]` while in ~/.aws/credentials you should use `[bug]` as "credentials profile" instead. You should not define credentials in ~/.aws/config.

That being said, Attempt 1 and 2 are all invalid and Attempt 3 defining `aws_access_key_id` and `aws_secret_access_key` is not encouraged. I believe only Attempt 4 is the way to go.

I am closing this issue as this is not a bug. Let me know if you have any further feedbacks. Thank you.

**Comment by jashgala** [comment]
Thanks @rix0rrr @pahud. 
My comment was intended for the issue creator as they might have discovered the bug through misconfigured config or credential files. I agree that this might be "too deeply ingrained" syntax, and we just need to live with it.

**Comment by quintonn** [comment]
@jashgala The [profile demo] fixed my issue.
Guess it's a difference between the 2 config files.
Thanks

**Comment by maprohu** [comment]
Hi @pahud !

What I am experiencing is that the "region" setting seems to be ignored, and somehow default to "us-east-1" when the name if the profile (in `.aws/config`) that I am trying to use is "default".

So, if I have something like this in `.aws/config`:

```
[profile default]
...
sso_account_id = 123456789
region = eu-central-1
...
```
 
and then I run something like `cdk bootstrap`, then cdk will happily deploy the bootstrap to `aws://123456789/eu-east-1`, getting the account_id right, but not the region.

However, if rename the same profile to, say, `test`, that is, my `.aws/config` looking like this:

```
[profile test]
...
sso_account_id = 123456789
region = eu-central-1
...
```

and then I run `cdk bootstrap --profile test` then both the account id and the region are detected correctly by cdk.

```
$ cdk --version
2.106.1 (build a2e5f65)
```
