### ISSUE TITLE
(aws-ecs): PortMapping should support ContainerPortRange

### ISSUE THREAD

**Issue by mneirynck** [aws/aws-cdk#23509]
### Describe the feature

This feature would make CDK on par with Cloudformation for the places where PortMapping is used.

### Use Case

We're working on a project that uses an RTPEngine hosted on ECS Fargate, but this needs a specified range of UDP ports to be opened (ie 30000:40000).

### Proposed Solution

Add the ContainerPortRange property to PortMapping, Cloudformation already supports it.

Or give the option to do a property override to add this property yourself.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.57.0

### Environment details (OS name and version, etc.)

Arch, Python 3.10

**Comment by bun913** [comment]
https://github.com/aws/aws-cdk/blob/09f8e9f8f146c19e0c93c1c3edec84bb4281dccd/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L1041

To tell the truth, I would like to create a class called `Port`.

I want the `Port` class to have a validation like 0~65535.

I think it would be best if I could then create a `PortRange` class to hold the Port class.

However, I would not want to do that because the changes would be too large.

**Comment by bun913** [comment]
Sorry.
The problem here is not easy to change the existing system and it is not likely to be started for a while.

**Comment by peterwoodworth** [comment]
Thanks for submitting the new issue @bun913, it's much appreciated and may help us deliver this particular feature faster

**Comment by TristanBarlow** [comment]
I would also like to see this feature implemented

**Comment by ste93cry** [comment]
@peterwoodworth I've opened a PR to move forward, however I need some guidance on the problem I discussed above :pray:
