### ISSUE TITLE
AWS_ECR: Policystatement not applied on imported ecr

### ISSUE THREAD

**Issue by lum-DannyK** [aws/aws-cdk#23616]
### Describe the bug

Hi,

I am trying to add a policystatement to an imported ecr, but when I deploy there are no changes?
I also created a new repository through CDK and added the policystatement to that repository (to test the policystatement), but that works fine.

### Expected Behavior

Be able to add a policystatement to an imported ecr.

### Current Behavior

There are no changes.

### Reproduction Steps

The repository name is: dannytest

```Typescript

const dannytest = ecr.Repository.fromRepositoryName(this, 'dannytest', 'dannytest');

    const ecrAccessPolicyJson = {
      "Sid": "AllowPullFromAWSAccounts",
      "Effect": "Allow",
      "Principal": {
          "AWS": [
              "arn:aws:iam::987654321:root"
          ]
      },
      "Action": [
          "ecr:GetDownloadUrlForLayer",
          "ecr:ListImages"
      ]
  }

  const ecrAccessPolicyStatement = iam.PolicyStatement.fromJson(ecrAccessPolicyJson);
  
  dannytest.addToResourcePolicy(ecrAccessPolicyStatement)
```

### CDK CLI Version

2.59.0

### Node.js Version

16.9.1

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this @lum-DannyK,

This is happening because as a general rule you cannot modify resources which have been imported - see our [documentation here](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_external) for more info on imported resources.

If you need to modify an existing Repository policy not controlled by your CDK app, you could use an AwsCustomResource construct to make the [SetRepositoryPolicy API call](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_SetRepositoryPolicy.html). Though this makes adding a statement to an existing policy a bit difficult, I'm not sure of another way to do this through CDK.

**Comment by lum-DannyK** [comment]
Ah, that explains it, thanks @peterwoodworth!
