### ISSUE TITLE
AWS CDK: State 'XYZ' already has a next state AWS CDK

### ISSUE THREAD

**Issue by noddyStark** [aws/aws-cdk#23660]
### Describe the issue

I'm pretty new to AWS CDK and trying to trigger different steps multiple times in step function depending upon when a certain condition is met.

But when I try to implement the code I get the error  
`State 'step_3' already has a next state`.

I'm basically trying to trigger different lambdas depending upon the condition of 'requestType', if after step_1, the condition `requestType` is equal to `OD3`, `step_2` will be triggered which will end up invoking the lambda, so steps should be triggered in the following manner `step_2 -> step_3 -> step_4` -> 'step_6' but if the condition isn't met, we don't want to invoke the `step_2` lambda and would continue in the order of `step_3 -> step_4 -> step_5 -> step_6`

Every step in step function is invoking some different Lambda which are responsible to perform some different kind of tasks, every steps looks like the below mentioned `step_n`.

```
        const step_n = new LambdaInvoke(this, 'Step_Name', {
            lambdaFunction: stackMap['LambdaName::someMethod()'],
            inputPath: '$',
            outputPath: '$.Payload',
        });
      


const definition = step_1
            .next(new Choice(this, "RequestType", {
                    inputPath: '$'
                })
                    .when(Condition.stringEquals('$.requestType', 'OD3'), step_2
                        .next(step_3)
                        .next(step_4)
                        .next(step_6))
                    .otherwise(step_3
                        .next(step_4)
                        .next(step_5)
                        .next(step_6))
            );


        const stateMachine = new StateMachine(this, 'StateMachine', {
            definition
        });
```

I was able to remove the error by redefining by code like below : 
```

        const choice = new Choice(this, "RequestType", {
            inputPath: '$'
        })
        const isOD3RequestCondition = Condition.stringEquals('$.requestType', 'OD3')

        const definition4 = step_4
            .next(choice.when(Condition.not(isOD3RequestCondition), step_5).afterwards())
            .next(step_6);
        const definition3 = step_1
            .next(choice.when(isOD3RequestCondition, step_2).afterwards())
            .next(step_3);
        const definition = definition3.next(definition4);
```
 but while deploying the stacks I get the below error : 

```
Resource handler returned message: "Invalid State Machine Definition: 'MISSING_END_STATE: Workflow has no terminal state at null' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 208ea192-645a-4ddf-9001-f5fdab0742

```

### Links

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-stepfunctions-tasks.LambdaInvoke.html

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-stepfunctions.Chain.html

**Comment by tim-finnigan** [comment]
Hi @noddyStark thanks for reaching out. I'm not that familiar with this area but saw a couple of related posts that might help. [This one](https://stackoverflow.com/questions/72806518/how-can-i-use-a-task-state-multiple-times-in-aws-step-functions-using-the-cdk) suggests that the first error could be caused by an infinite loop. [And this post](https://stackoverflow.com/questions/70110253/invalid-state-machine-definition) suggests that you are missing an array. These documentation pages may help for reference:
* https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html#error-handling-examples.
* https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-lambda-state-machine-cdk.html

Please let us know if those help or if there are any updates on your end.
