### ISSUE TITLE
(aws-cdk-lib.aws_ecr): (add lifecycle rule)

### ISSUE THREAD

**Issue by Wildhammer** [aws/aws-cdk#23776]
### Describe the feature

Being able to add lifecyle rule to an existing ECR repository from a CDK app

### Use Case

When you use `DockerImageAsset` it's wired up to use the bootstrapped ECR repo. That repo can be obtained by `Repository.fromRepositoryName` utility function which returns an `IRepository`. You can add resource policy to this `IRepository` but there is no way to add lifecycle rules. 

The reason for this the one-repo-for-all approach of CDK and how the size of that repo needs to be controlled. There should be a way to customize this from within an app and add app-specific prefix to lifecycle rules.

### Proposed Solution

Add `addLifecycleRule` method to `IRepository`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.58.1

### Environment details (OS name and version, etc.)

MacOS 13.1

**Comment by indrora** [comment]
Unfortunately, because the repo is already created and not managed by the CDK app, you can't modify it through the `fromRepositoryName` call. This applies to any `from...` call that returns an interface; these interfaces are read-only in nature and only hold information from 

You may find that AWS SSM automations do what you are looking to do.
