### ISSUE TITLE
IWebSocketApi: Unable to add Routes when fetched using WebSocketApi.fromWebSocketApiAttributes

### ISSUE THREAD

**Issue by stevehaneytrailblazer** [aws/aws-cdk#23896]
### Describe the bug

I have a websocket gateway that is built by another team via Terraform.  However, they do not hook up any of the actual websocket routes or handlers.

I was using WebSocketApi.fromWebSocketApiAttributes (via @aws-cdk/aws-apigatewayv2-alpha) which worked great in finding the resource but unfortunately IWebSocketApi doesn't seem to have the same methods WebSocketApi contains.

In particular I wanted to call addResoure.  Is it possible to add this method or is there another recommended way to find an existing websocket API GW and add resources to it?  Thanks!

### Expected Behavior

Ideally any method that exists on WebSocketApi would be exposed on IWebSocketApi so that they can be called the same whether fetching an existing Websocket GW or using new WebSocketApi.

For example on a Rest API Gw I can add methods to an existing GW.

### Current Behavior

addRoute method is not available on IWebSocketApi.

### Reproduction Steps

```
const gw = WebSocketApi.fromWebSocketApiAttributes(scope, `${id}-ws-api`, {
        webSocketId: "xxxxxx"
    });

gw.addResource(...); //Not valid method here
```

### CDK CLI Version

2.62.2 (build c164a49)

### Node.js Version

v16.13.2

### OS

Mac Os Ventura 13.1

### Language

Typescript

**Comment by jankronquist** [comment]
grantManageConnections is also missing

**Comment by peterwoodworth** [comment]
As a general rule, you [cannot modify imported resources in CDK](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_external). This means imported constructs lack methods and properties that constructs created within the stack would otherwise have.

This is because the CDK isn't actually looking up information on your WebSocketApi, so some contextual information that your WebSocketApi has that's necessary for these methods to perform correctly is missing. You'll need to work around this by dropping down to L1 resources, or finding another way to modify your existing resource. Thanks!
