### ISSUE TITLE
RDS Encryption with customer key

### ISSUE THREAD

**Issue by xxCoDeBoX** [aws/aws-cdk#2398]
**Describe the bug**
I am trying to encrypt rds storage using 
.withStorageEncrypted(true)
.withKmsKeyId(xxx)  of CfnDBInstance class.

![image](https://user-images.githubusercontent.com/36667412/56948713-9ac91000-6b4e-11e9-9933-52bb63429603.png)

This is what I see on console after running through cdk
![image](https://user-images.githubusercontent.com/36667412/56948816-ebd90400-6b4e-11e9-968d-fc48cc686d18.png)

**To Reproduce**
N/A

**Expected behavior**
On the console the encryption value should be changed to enabled.

**Version:**
 - Programming Language - JAVA
 - CDK Version - 0.28.0

**Comment by xxCoDeBoX** [comment]
any updates on this ??

**Comment by nija-at** [comment]
I'm not able to reproduce this issue.

I have the same encoded in a typescript app

```ts
import cdk = require('@aws-cdk/core');
import rds = require('@aws-cdk/aws-rds');
import kms = require('@aws-cdk/aws-kms');
import { RemovalPolicy } from '@aws-cdk/core';

class HelloCdkStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
      super(scope, id, props);

      const key = new kms.Key(this, 'kms', {
        removalPolicy: RemovalPolicy.DESTROY,
      });
      
      new rds.CfnDBInstance(this, 'db', {
        dbInstanceClass: 'db.m4.large',
        storageEncrypted: true,
        kmsKeyId: key.keyArn,
        allocatedStorage: '10',
        engine: 'MySQL',
        engineVersion: '5.5.46',
        masterUsername: 'root',
        masterUserPassword: XXXXXXXXX
      });
    }
}
  
const app = new cdk.App();
new HelloCdkStack(app, 'HelloCdkStack');
app.synth();
```

After deploying this with `cdk deploy`, the AWS CLI confirms that that the DB instance is encrypted and is using the specified key.
```shell
$ aws rds describe-db-instances --db-instance-identifier hd8v5kkc6hhvm7
[
  {
    "DBInstanceIdentifier": "hd8v5kkc6hhvm7",
    "DBInstanceClass": "db.m4.large",
    "Engine": "mysql",
    ...
    ...
    "StorageEncrypted": true,
    "KmsKeyId": "arn:aws:kms:eu-west-1:664773442901:key/14486bb4-1fda-4956-90fd-894a2c86d924",
  }
]
```

However, there seems to be a bug in the AWS Console, in that it shows the encryption key as 'None' (see screenshot below) but the associated link (https:\/\/eu-west-1.console.aws.amazon.com/iam/home?region=eu-west-1#encryptionKeys/eu-west-1/14486bb4-1fda-4956-90fd-894a2c86d924) goes to IAM instead of KMS and shows text as 'None'
![image](https://user-images.githubusercontent.com/16217941/63523802-b89df480-c4f2-11e9-9bc1-919fe56cbafd.png)
