### ISSUE TITLE
aws-cdk-lib/aws-kms: Wrong key returned when performing lookup with alias name.

### ISSUE THREAD

**Issue by daverickdunn** [aws/aws-cdk#23992]
### Describe the bug

I was looking up a specific KMS key using `Key.fromLookup(this, 'MyKey', { aliasName: 'alias/my/key' })`, this worked absolutely fine for several stacks (same key, same code snippet, same cdk version), but on one of my stacks it stopped working after a deployment, it **had worked correctly** on this stack for the first few deployments. Upon further inspection it's now returning an old key that doesn't have an alias. I'm actively developing this stack and can't say for sure what I changed before it broke, but I didn't change anything about the lookup.

### Expected Behavior

`kms.Key.fromLookup` returns the key specified by the `aliasName` field, not a different key.

### Current Behavior

`kms.Key.fromLookup` returns a key that has no alias.

### Reproduction Steps

1. Create two KMS keys, one with an alias and one without. 
2. Try lookup the key with an alias using `kms.Key.fromLookup`, you _might_ get the wrong key (as mentioned, identical code is working fine in other stacks).

### Possible Solution

Clearing the key from `context.json` and redeploying resolved the issue.

### Additional Information/Context

`context.json` shows the correct aliasName, account, region, but wrong UUID for the `keyId`
```json
{
  "key-provider:account=111111111111:aliasName=alias/my/key/name:region=eu-west-1": {
    "keyId": "<wrong uuid>"
  }
}
```

### CDK CLI Version

2.63.0

### Framework Version

2.62.1

### Node.js Version

16.18.1

### OS

Windows 11

### Language

Typescript

### Language Version

4.9.4

### Other information

I upgraded from 2.62.1 to 2.63.0 before clearing the `context.json`.

**Comment by tim-finnigan** [comment]
Hi @daverickdunn thanks for reaching out. I attempted to reproduce this issue but wasn't able to. Could you provide more context or information on the steps to reproduce this? Is this something that you can reproduce consistently?

**Comment by daverickdunn** [comment]
HI @tim-finnigan, thanks for looking into it. I understand it's not an easy one to reproduce, I'm not sure I can myself. The one thing that possibly has some significance is that I remember initially forgetting to prefix the name with `alias`, i.e. `Key.fromLookup(this, 'MyKey', { aliasName: 'my/key' })` vs. `Key.fromLookup(this, 'MyKey', { aliasName: 'alias/my/key' })`. But once I realised my mistake and prefixed it correctly, I'm (almost) certain it deployed fine and the key worked as expected. It was a few hours and a few deployments later that it stopped working. However, since I was actively developing there is a chance that I _assumed_ it was working and that this is in fact close to the root cause. It's been a few days so I'm getting hazy on the details.

**Comment by tim-finnigan** [comment]
Thanks for following up, just wanted to check in again. Do you have any updates on your end as far as what you've tried or observed? Please let us know if there is any more information you can provide to help with reproducing the issue if it is still something you are running into.

**Comment by systematicguy** [comment]
I had a very similar issue yesterday.
It is not that hard to reproduce:

I have one stack producing a KMS Key with an alias.
I configure the other stack to look it up by the alias name.
The consumer stack has a lambda that has a role referring to this key.

Then I delete the first stack. Due to company policies the KMS Key will not be removed, but its alias will be removed.
I redeploy the first stack. There will be a new KMS Key created, the alias will point to that.
I was naive enough to just re-run the deployment of the second stack after the first one got recreated.

Eventually it turns out that (like other looked up resources by name), KMS Key aliases get also cached in the `cdk.context.json` file. I removed that file, have run the deployment of the consumer stack again, and it detected the change, everything got correct again.

What grinds my gears is that the recommended practice is to version control or at least cache this file to "keep consistency", while at the same time it is recommended to work with only ci, avoiding manual interventions, but occasionally we need to clean/update this file. 

https://docs.aws.amazon.com/cdk/v2/guide/context.html
