### ISSUE TITLE
bootstrap: fails with bucket "already exists"

### ISSUE THREAD

**Issue by jric** [aws/aws-cdk#24143]
### Describe the bug

A co-worker likely already bootstrapped the account, but I'm getting cdk deploy failures indicating that the account is not properly bootstrapped, so I wanted to bootstrap it myself.  I am logged in as an admin user and getting an error, "CREATE_FAILED |  AWS::S3::Bucket | StagingBucket" and "cdk-xxxxxxxxxx-assets-xxxxxxxxxxxxxxx-us-east-1 already exists".  Could it not be idempotent in this aspect of bootstrapping?

### Expected Behavior

I expected it to tell me that the account/region is already bootstrapped and the command to succeed, unless there is really something missing, in which case I expected the command to fix that.

### Current Behavior

The command fails with the given error messages.

### Reproduction Steps

I do not how to reproduce this, since it likely involves multiple steps by multiple users.

### Possible Solution

Maybe instead of blindly adding the bucket to the CF stack, instead use the API to find out if the bucket already exists (and in the right region) and if so, create the stack without the bucket, or if that's not easy to do, then suggest workarounds such as how to check that all the necessary components are already bootstrapped, how to delete the necessary resources, how to recreate the bootstrapping, etc.

### CDK CLI Version

2.64.0 (build fb67c77)

### Node.js Version

v18.13.0

### OS

macOS 13.1 (22C65)

### Language

Typescript

### Language Version

4.8.4

**Comment by peterwoodworth** [comment]
CloudFormation is throwing an error that the bucket already exists. This means that a bucket with this name exists in some account somewhere - buckets cannot have the same name no matter which account they are in. This doesn't necessarily mean that your environment is bootstrapped either. I can only speculate as to what is going on in your case, but I suspect that if you cannot find a bootstrap stack in your account, that someone else may have tried to create this bootstrap stack at one point and deleted it while retaining the bucket.

Our bootstrap command will deploy a preconfigured CloudFormation template that takes in a limited number of configurations through parameters. For any scenarios where you want to make further modifications to the template, like removing the bucket because you already have a bucket you want to use, [we recommend modifying the template
](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-customizing)
> When you need more customization than the AWS CDK Toolkit switches can provide, you can modify the bootstrap template to suit your needs. Remember that you can obtain the template by using the --show-template flag.

I think your questions and confusion can be answered by viewing the template we deploy, and reading the [full bootstrapping page](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) in the developer guide.

If you have additional troubleshooting needs, feel free to open a [discussion](https://github.com/aws/aws-cdk/discussions)

**Comment by jric** [comment]
FWIW, I had already read the dev guide and do understand that the command as well as the template are configurable.

I also understand that bucket names are globally unique across all accounts, however, since the bucket name contains the account number, this is not likely to be an issue (confirmed in my case.)

Perhaps it is the case that someone deleted the stack or that it was created with an old version of the client.  I will try deleting the bucket and bootstrap again.

I think that the tool would be better if it provided ideas for next steps, rather than just erroring without a diagnosis, so I stand behind this being a bug, or at a minimum, a valid feature request.

**Comment by peterwoodworth** [comment]
Do you have any suggestions for our documentation to clear up some potential confusion? The error that's being thrown by CloudFormation/CDK is doing all that it can do without making any overbearing assumptions, so I'm unsure what "next steps" could be printed here when this error is detected given that the reason for failure is clear

**Comment by jric** [comment]
So in my case, it turned out someone had bootstrapped with cdk v1.

I'm thinking cdk could run some sanity checks (does the bucket already exist, if so, does it contain cdk assets and is it in the same CF stack, if so, do the other named assets already exist) and based on the result of those checks provide some likely scenarios:

1. it looks like there is coincidentally already a bucket with the name, try using a --qualifier flag
2. It looks like this account was bootstrapped with an older version of cdk bootstrap, try deleting the bucket and running bootstrap again

**Comment by tsengia** [comment]
For anyone else stumbling here from Google, I had this same issue because I deleted the CDK Toolkit bootstrap stack, and then later tried to re-bootstrap my environment.

I solved the S3 bucket already exists error by passing in the `-b` command line argument to specify the bucket name:
```
cdk bootstrap -b your-bucket-name-here-lowercase-only
```
