### ISSUE TITLE
(alpha modules): modify semver tagging pattern to allow for ranges

### ISSUE THREAD

**Issue by timcosta** [aws/aws-cdk#24431]
### Describe the feature

Hi all! The alpha modules are currently tagged like `@aws-cdk/aws-redshift-alpha@2.18.0-alpha.0`. This is presenting a problem because it's impossible to set up a peer dependency for an alpha module that doesn't require an exact version match.

I am suggesting that #15581 be re-discussed in order to make the alpha modules usable in libraries, which they currently are not unless you ensure all consumers and other consumed libraries use the exact same version in their peer dependencies.

### Use Case

We are consuming multiple vended libraries that set peer dependencies on `@aws-cdk/aws-redshift-alpha`, one set to `^2.18.0-alpha.0` and the other set to `^2.44.0-alpha.0`. While it would be logical at first glance for `2.44.0-alpha.0` to satisfy `^2.18.0-alpha.0`, due to how semver handles prerelease which you can test out [here](https://semver.npmjs.com/) to verify the issue i am referring to.

It is not currently possible to include two libraries with peer dependencies on the same CDK alpha module, unless the dependencies match exactly. 

### Proposed Solution

I suggest that the `-alpha.0` be dropped altogether, because the package name already specifies that its an alpha package. Having it in the version as well makes it seem like its an alpha release of an alpha package when these versions are the ones that are meant to be consumed, and is creating a lot of issues with `peerDependencies` when packages vend constructs that rely on alpha constructs.

Here's an example in [cdk-monitoring-constructs](https://github.com/cdklabs/cdk-monitoring-constructs/issues/212) of what i mean.

### Other Information

This seems to have been a fun [side effect of NPM v7](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) unfortunately, where it now "will block installations if an upstream dependency conflict is present that cannot be automatically resolved". 

It appears that the decision in #15581 was to use `2.x.y-alpha` as the structure, but when implemented the `.0` was also added in #16043 which led to additional undesirable behavior when NPM v7 was thrown into the mix.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.56.0

### Environment details (OS name and version, etc.)

macos 13, m1, node 16, npm 8

**Comment by cgatt** [comment]
Seconding this issue. The lockstep versioning of the alpha modules makes managing peer dependencies virtually impossible, as semvar ranges cannot be defined.
[#15581 ](https://github.com/aws/aws-cdk/issues/15581) highlights that it's important that it be clear the alpha packages are intended for cdkv2, but this can be done with naming - i.e. @aws-cdk/aws-lambda-python-alpha-v2 - rather than versioning, if still required now that CDK v1 is deprecated.
Following the 0.x.y versioning pattern will drastically improve the ability of CDK alpha modules to be used in libraries, especially JSII libraries where extending the interfaces of the alpha libraries means working around the peer dependency versioning issue with bundling is impossible (as JSII libraries can not export interfaces from bundled dependencies).

**Comment by jesterhazy** [comment]
+1 this is extremely frustrating for anyone providing a construct library and for their downstream users
