### ISSUE TITLE
integ-tests: Response object is too long

### ISSUE THREAD

**Issue by nikovirtala** [aws/aws-cdk#24490]
### Describe the bug

The integration test fails if the expected result object is too long.

### Expected Behavior

The test should return a successful status if the expectation match, regardless of the object size.

### Current Behavior

The test fails with the following error:

```
 ❌  IntegTest/DefaultTest/DeployAssert failed: Error: The stack named IntegTestDefaultTestDeployAssertE3E7D2A4 failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [AwsApiCallDynamoDBquery]. ): Response object is too long.
    at FullCloudFormationDeployment.monitorDeployment (/Users/nikovirtala/src/github.com/nikovirtala/integ-runner-proto/node_modules/aws-cdk/lib/index.js:344:10235)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/Users/nikovirtala/src/github.com/nikovirtala/integ-runner-proto/node_modules/aws-cdk/lib/index.js:347:144797)
    at async /Users/nikovirtala/src/github.com/nikovirtala/integ-runner-proto/node_modules/aws-cdk/lib/index.js:347:130251
    at async run (/Users/nikovirtala/src/github.com/nikovirtala/integ-runner-proto/node_modules/aws-cdk/lib/index.js:347:128257)
```

### Reproduction Steps

Run the test described in: https://github.com/nikovirtala/integ-runner-proto/blob/main/test/integ.object-is-too-long.ts

### Possible Solution

Maybe we shouldn't send full data objects to CloudFormation? — I don't see the data being displayed to the user.

### CDK CLI Version

2.66.1

### Node.js Version

v18.14.2

### OS

macOS Ventura

### Language

Typescript

### Language Version

4.9.5

**Comment by scanlonp** [comment]
Hi @nikovirtala, I have seen this error when doing assertions that request objects that have any significant length. I believe the limit is [4096 bytes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html).

The work around for you is creating specific assertions for singular values. The `assertAtPath()` method described in [our integ test guide](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md#assertions) might be helpful.

I am closing this because it is a CFN limit, and the workaround for the integ test construct would add more complexity than the fix would be worth.
