### ISSUE TITLE
aws-lambda-event-sources: SQS `receiveMessageWaitTime`'s default value is incorrect

### ISSUE THREAD

**Issue by sarisia** [aws/aws-cdk#24795]
### Describe the issue

Docs for `aws-lambda-event-sources` says SQS Queue's `receiveMessageWaitTime` property is default to 20 seconds,
but according to CDK `aws-sqs` docs and CloudFormation `AWS::SQS::Queue docs`, it's 0 seconds by default, not 20 seconds.

### Links

- CDK `aws-lambda-event-sources`
  https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_event_sources-readme.html#sqs

  > receiveMessageWaitTime: Will determine [long poll](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html) duration. The default value is 20 seconds.

- CDK `aws-sqs`
  https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sqs.Queue.html#receivemessagewaittime

  > receiveMessageWaitTime?
  > Type: [Duration](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Duration.html) (optional, default: 0)

- CloudFormation `AWS::SQS::Queue`
  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#aws-resource-sqs-queue-properties

  > ReceiveMessageWaitTimeSeconds
  > ... You can specify an integer from 1 to 20. Short polling is used as the default or when you specify 0 for this property. ...

**Comment by pahud** [comment]
Yes this is confusing. But it's unclear to me what the default duration is from the CFN document while according to [this document](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html), the default value seems to be `0`.

**Comment by pahud** [comment]
@sarisia 

From what I see in the CFN doc

>ReceiveMessageWaitTimeSeconds
Specifies the duration, in seconds, that the ReceiveMessage action call waits until a message is in the queue in order to include it in the response, rather than returning an empty response if a message isn't yet available. You can specify an integer from 1 to 20. Short polling is used as the default or when you specify 0 for this property. For more information, see [Consuming messages using long polling](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html#sqs-long-polling) in the Amazon SQS Developer Guide.

It is unclear to me if the default is `0` but `short polling` is the default behavior if undefined and the effect is just as setting this value to `0`.

In terms of Lambda's internal SQS poller's behavior, we probably need to look up other document but I support to have a PR to update the default from `20` to `0`.

**Comment by sarisia** [comment]
I'll submit a PR later, thanks!
