### ISSUE TITLE
ec2: Available AWS-managed prefix lists

### ISSUE THREAD

**Issue by watany-dev** [aws/aws-cdk#24921]
### Describe the feature

I am currently creating Managed prefix lists, and I think it would be convenient to be able to use AWS Managed prefix lists as well. Please refer to the following link for available AWS Managed prefix lists:
https://docs.aws.amazon.com/vpc/latest/userguide/working-with-aws-managed-prefix-lists.html#available-aws-managed-prefix-lists

Since the identifiers of resources vary for each region, it is assumed that they will be described in the fact-table.ts of the region-info.

### Use Case

```ts
const sg = new ec2.SecurityGroup(this, 'SecurityGroup', {
  vpc,
  allowAllOutbound: false
});
const s3ManagedPrefix = new ec2.ManagedPrefixlist.S3

# sg.addEgressRule(ec2.Peer.prefixList('pl-xxxxxxxx'), ec2.Port.tcp(443), 
sg.addEgressRule(s3ManagedPrefix, ec2.Port.tcp(443), 
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

v2.72.1

### Environment details (OS name and version, etc.)

any

**Comment by pahud** [comment]
Sounds great! Thank you for your PR!

**Comment by jumic** [comment]
@pahud In issue #15115 the same feature was requested using a cdk-lookup method (51 votes, high priority issue). So there are two ways to implement this feature. Which way would you prefer? I would prefer to use the solution described in this issue (`fact-table.ts`) because it is easier to implement and doesn't require a lookup method.

@watany-dev Do you still plan to implement this feature? Or can someone else work on it?

**Comment by pahud** [comment]
We probably need the core team maintainers to chime in here.

**Comment by pahud** [comment]
Hi @watany-dev 

As this is a duplicate issue. Let's move to https://github.com/aws/aws-cdk/issues/15115 and discuss with other folks in the same thread. I am closing this for now.
