### ISSUE TITLE
aws-cdk-lib: Custom resource provider can't exceed 1 hour

### ISSUE THREAD

**Issue by jamiewhit** [aws/aws-cdk#24974]
### Describe the bug

A custom resource provider can be configured to have a totalTimeout of up to 2 hours according to [this documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.Provider.html#totaltimeout). However, in practice the custom resource times out in CloudFormation after 1 hour with this message:

```
CloudFormation did not receive a response from your Custom Resource
```

### Expected Behavior

I expect CloudFormation to allow up to 2 hours for the custom resource to be created.

### Current Behavior

The step function which is created by the provider framework is successfully configured to run up to 2 hours, but CloudFormation fails after 1 hour. Even though CloudFormation fails to create/update the resource, the step function keeps running until the resource is successfully provisioned before the 2 hour timeout.

### Reproduction Steps

I've created a custom resource provider which runs asynchronously. I've followed this documentation to set up the provider with an `isComplete` handler which polls the status of my custom resource: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html#asynchronous-providers-iscomplete.

```
 const provider = new Provider(this, 'DeploymentProvider', {
    onEventHandler: onEvent,
    isCompleteHandler: isComplete,
    totalTimeout: Duration.hours(2),
    queryInterval: Duration.seconds(30)
});
```

### Possible Solution

Either update the custom resource provider to support a max `totalTimeout` of 1 hour or clarify the intention of the timeout value, if it's not meant to represent the timeout supported by CloudFormation.

### CDK CLI Version

2.72.0

### Node.js Version

v14.20.0

### OS

macOS 12.6.1

### Language

Typescript

**Comment by pahud** [comment]
According to [this blog post](https://aws.amazon.com/blogs/devops/implementing-long-running-deployments-with-aws-cloudformation-custom-resources-using-aws-step-functions/),  I am afraid the default custom resource creation timeout is 1 hour, to extend the timeout, we will need to create a wait condition handler and allow custom resource handler callback the wait condition handler but I did find any relevant implementation in CDK.

I'll discuss with the team internally.

**Comment by peterwoodworth** [comment]
@pahud the totalTimeout prop ends up getting used in the WaitConditionHandler stepfunction. We use the totalTimeout to calculate the maxAttempts based on the interval count.

https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts#L52-L62

**Comment by pahud** [comment]
Thank you @peterwoodworth. Correct me if I was wrong but from what I've read in the source code and document, the default timeout of the CFN custom resource is **1 hour** according to [this document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes.html) and the custom resource framework is essentially a custom resource which has to response to CFN within this limitation. Now, in this framework, [if isCompleteHandler is provided](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L173-L188), a state machine will be created with the onEvent handler as its entrypoin followed by isCompleteHandler with backoff invocation. This means:

1. The onEvent handler will be [invoked synchronously with await call](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L32) and is subject to its [15min timeout](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L212), in this case if your onEvent handler can successfully return within 15min, everything is good. 
2. When both onEvent handler and onComplete handler are provided, the framework will [kick off the waiter state machine](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L46-L57) immediately after the onEvent response. By default, the state machine [start execution invocation](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L56) is async. This means it's state machine's responsibility to [send the cfn response](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L86).

Now, let's look at the [totalTimeout](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.Provider.html#totaltimeout) property mentioned above. According to [this](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L156-L159), it's essentially designed for isCompleteHandler only but this seems to be a bug because I didn't see `props.totalTimeout` being used in the [provider](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts).

From above, I think `props.totalTimeout` is not really working and the whole custom resource provider is still subject to and capped by the default 1 hour limitation of the CFN custom resource timeout mentioned in the [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes.html).

However, I probably is wrong and missed something in the source code. Let me know if I missed anything.

**Comment by pahud** [comment]
Thank you @peterwoodworth. Correct me if I was wrong but from what I've observed in the source code and document, the default timeout of the CFN custom resource is **1 hour** according to [this document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes.html) and the custom resource provider is essentially a provider of CfnCustomResource and is responsible to cfn-response to CFN within this limitation. 

Now, in this framework, [if isCompleteHandler is provided](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L173-L188), a waiter state machine will be created and kicked off with the onEvent handler as its entrypoint execution followed by isCompleteHandler with backoff retry invocation. This means:

1. The onEvent handler will be [invoked synchronously with await call](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L32) and is subject to its [15min timeout](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L212), in this case if your onEvent handler can successfully return within 15min, everything is good. 
2. When both onEvent handler and isComplete handler are provided, the framework will [kick off the waiter state machine](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L46-L57) immediately after the onEvent response. By default, the state machine [start execution invocation](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L56) is async. This means it's state machine's responsibility to invoke isCompleteHandler to [send the cfn response](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L86) within the **1 hour**.

Now, let's look at the [totalTimeout](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.Provider.html#totaltimeout) property mentioned above. According to [this](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L156-L159), it's essentially designed for isCompleteHandler and is calculated [here](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L177) in [calculagteRetryPolicy()](https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/custom-resources/lib/provider-framework/util.ts#L6-L20).

With that being said, I think `props.totalTimeout` is designed only to calculate the maxAttempts and the whole custom resource provider is still subject to and capped by the default 1 hour limitation of the CfnCustomResource timeout mentioned in the [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes.html), which I don't think the waiter state machine can break, even not the whole provider framework.

I feel the CfnWaitCondition and CfnWaitConditionHandle might be required as described in [this blog post](https://aws.amazon.com/blogs/devops/implementing-long-running-deployments-with-aws-cloudformation-custom-resources-using-aws-step-functions/) and [this github sample code snippet](https://github.com/aws-samples/aws-cfn-custom-resource-using-step-functions/blob/6f1c536072fc418f126364ef8e7c8aff71dbeb3a/src/step-function/stack-main.ts#L425-L433) or completely handled by the provider framework when `props.totalTimeout` is specified more than 1 hour. This might be a working option to break the 1 hour limitation.

But I could still be wrong and miss something in the source code. Let me know if I missed anything.

**Comment by pahud** [comment]
I can confirm the 2 hours of `totalTimeout` does not work.


```ts
export class Demotack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const handlerCommonConfig = {
      runtime: lambda.Runtime.PYTHON_3_9,
      code: lambda.Code.fromAsset(path.join(__dirname, '../lambda.d')),
    }

    const onEventHandler = new lambda.Function(this, 'OnEvent', {
      ...handlerCommonConfig,
      handler: 'index.on_event',
    })

    const isCompleteHandler = new lambda.Function(this, 'IsComplete', {
      ...handlerCommonConfig,
      handler: 'index.is_complete',
    })

    const provider = new cr.Provider(this, 'Provider', {
      onEventHandler,
      isCompleteHandler,
      queryInterval: Duration.minutes(15),
      totalTimeout: Duration.hours(2),
      logRetention: log.RetentionDays.ONE_DAY,
    }) 

    new CustomResource(this, 'CR', {
      serviceToken: provider.serviceToken,
      properties: {
        startedAt: Math.floor(Date.now() / 1000),
      }
    })
  }
}
```

index.py

```py
import time


def on_event(event, context):
  print(event)
  request_type = event['RequestType']
  if request_type == 'Create': return on_create(event)
  if request_type == 'Update': return on_update(event)
  if request_type == 'Delete': return on_delete(event)
  raise Exception("Invalid request type: %s" % request_type)

def on_create(event):
  props = event["ResourceProperties"]
  print("create new resource with props %s" % props)
  return {}

def on_update(event):
  physical_id = event["PhysicalResourceId"]
  props = event["ResourceProperties"]
  print("update resource %s with props %s" % (physical_id, props))
  # ...

def on_delete(event):
  physical_id = event["PhysicalResourceId"]
  print("delete resource %s" % physical_id)
  # ...
  
def is_complete(event, context):
  print(event)
  resource_props = event["ResourceProperties"]
  started_at = int(resource_props["startedAt"])
  now_ts = int(time.time())
  delta = now_ts - started_at
  print(f'now: {now_ts} started: {started_at} delta: {delta}')
  # 2 hours + 5min
  is_ready = delta > 60*60*2+300

  return { 'IsComplete': is_ready }
```

stack started creation at 8:38am
<img width="743" alt="image" src="https://user-images.githubusercontent.com/278432/231147097-26db1ebb-109a-41e8-89d6-ecfd059ba628.png">

CR started creation at 8:39am
<img width="665" alt="image" src="https://user-images.githubusercontent.com/278432/231147492-8caa3c89-49d1-4c18-b991-52104f864305.png">

CR creation failed at 9:40am
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/278432/231147261-dac61ea5-e8bd-4822-860b-480ae08d44c2.png">

**Comment by BwL1289** [comment]
If CR Provider timeout can't exceed 1 hour, is it possible to implement a workaround by deploying my own state machine to take a wait condition as input? 

For context, I am using CDK Pipelines and one of the stages takes ~6-7 hours. After it completes, I need to start the next stage of the pipeline.

Based on this [blog post](https://aws.amazon.com/blogs/devops/implementing-long-running-deployments-with-aws-cloudformation-custom-resources-using-aws-step-functions/) it should be possible, but would appreciate feedback.

**Comment by AaronZyLee** [comment]
Is there a plan for the fix? The wait condition seems reasonable for over 1 hour resources. I am currently developing a new construct depending on the framework and would like to see the fix is prioritized by team.

**Comment by pahud** [comment]
@BwL1289 

>If CR Provider timeout can't exceed 1 hour, is it possible to implement a workaround by deploying my own state machine to take a wait condition?

Yes, that is exactly what I was thinking but unfortunately I didn't make it.

I noticed this issue has been prioritized as p1 and the team will be looking at it shortly. Meanwhile, we appreciate and welcome any PR to address this issue from the community as well.

**Comment by BwL1289** [comment]
Thanks @pahud.

I'm not sure I have time to submit a PR, but happy to provide you with my pythonic solution for this.

However, a question I do have that is somewhat related. 

With this workaround implemented, if I have an `on_update` event, will previous values be stored in `OldResourceProperties` so that I can compare newer values to older ones (like the CR docs [state](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes-update.html))?

**Comment by evgenyka** [comment]
We are going to fix the documentation to align with AWS CloudFormation 1 hour timeout. For the long running deployments please see https://aws.amazon.com/blogs/devops/implementing-long-running-deployments-with-aws-cloudformation-custom-resources-using-aws-step-functions/
