### ISSUE TITLE
aws-batch-alpha: EcsJobDefinition.jobDefinitionName returns the ARN

### ISSUE THREAD

**Issue by gael-ft** [aws/aws-cdk#25197]
### Describe the bug

In EcsJobDefinition, looks like at the end of the constructor you override the field "jobDefinitionName" with the CfnJobDefinition `ref`.
Meaning if we try to access it later, we'll get a different value of what it has been created with.

### Expected Behavior

EcsJobDefinition.jobDefinitionName to return the CfnJobDefinition.jobDefinitionName and not the ARN of the resource

### Current Behavior

EcsJobDefinition.jobDefinitionNam returns the ARN (+ revision)

### Reproduction Steps

```typescript
const jobDef = new EcsJobDefinition(this, 'Resource', {
  // ...
  jobDefinitionName: 'toto'
  //...
});

jobDef.jobDefinitionName; // a Token which resolves to arn:aws:...:job-definition:toto:1
```

### Possible Solution

Just remove `this.jobDefinitionName = this.getResourceNameAttribute(resource.ref);`

[github link](https://github.com/aws/aws-cdk/blob/c224fc3d05daf1d594d3b9bbdaf476a18c8cc91e/packages/%40aws-cdk/aws-batch-alpha/lib/ecs-job-definition.ts#L100)

### CDK CLI Version

2.74.0 (build 70e2a33)

### Node.js Version

v16.13.0

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Similar to #25093, `ref` returns the arn instead of the name. Here's the actual fix in the linked PR for the similar issue:

```
this.jobQueueName = Stack.of(this).splitArn(this.jobQueueArn, ArnFormat.SLASH_RESOURCE_NAME).resourceName!;
```

We'll want to do the exact same thing, given this is the same exact bug just on a different construct. We don't want to remove this altogether because then customers who don't specify the name cannot reference it. Thanks for reporting!
