### ISSUE TITLE
S3 bucket default removal policy not respected

### ISSUE THREAD

**Issue by digitalsanctum** [aws/aws-cdk#2526]
**Describe the bug**
Documentation states that the `RemovalPolicy.Destroy` is the default but if you don't explicitly set the value, the S3 bucket will not be removed on cdk destroy.

**To Reproduce**
The following code will not destroy the S3 bucket:

```
val buildBucket = Bucket(this, "buildbucket", BucketProps.builder()
            .withBucketName(props.buildBucketName)
            .build()
        )
```

However, explicitly setting RemovalPolicy will destroy the bucket during `cdk destroy`:

```
val buildBucket = Bucket(this, "buildbucket", BucketProps.builder()
            .withBucketName(props.buildBucketName)
            .withRemovalPolicy(RemovalPolicy.Destroy)
            .build()
        )
```

**Expected behavior**
S3 bucket should be destroyed without explicitly defining removal policy.

**Version:**
 - Ubuntu
 - Java/Kotlin
 - 0.31.0

**Comment by schof** [comment]
If there are any files in the bucket, Cloudformation will not delete the S3 bucket, no matter what you say or how you ask. In other words, this is not a CDK-specific issue.

I agree this is a PITA which is why I created [AutoDeleteBucket](https://github.com/mobileposse/auto-delete-bucket) which will do what you want.

Protip: You can specify an`AutoDeleteBucket` anywhere can use `Bucket` which allows you to automatically delete buckets associated with codepipeline, etc.

**Comment by digitalsanctum** [comment]
@schof I understand bucket deletion is not allowed if it's not empty but that's not the case here.

At the very least, the documentation should be updated or behavior changed to match what the docs say.

**Comment by RomainMuller** [comment]
The documentation fairly unambiguously states that the default behavior for [s3.BucketProps.removalPolicy](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#removalpolicy) is to orphan the bucket.

**Comment by nija-at** [comment]
As stated in https://github.com/aws/aws-cdk/issues/3297, this will either be supported by Cloudformation or to incorporate force deletion of S3 buckets into CDK as custom resource.

Recommend continuing the conversation at https://github.com/aws/aws-cdk/issues/3297. Closing this issue.
