### ISSUE TITLE
(ec2): VPC Endpoint is not taggable

### ISSUE THREAD

**Issue by daschaa** [aws/aws-cdk#25336]
### Describe the bug

I tried adding a tag to a VPC endpoint but the tag was not created successfully. According to [https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-vpc-endpoints-now-support-tagging-for-gateway-endpoints-interface-endpoints-and-endpoint-services/](https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-vpc-endpoints-now-support-tagging-for-gateway-endpoints-interface-endpoints-and-endpoint-services/) tagging should work for this resource.

### Expected Behavior

```ts
const endpoint = vpc.addInterfaceEndpoint('MyEndpoint', {
      service: new InterfaceVpcEndpointService(vpcServiceName),
      subnets: { subnetType: SubnetType.PRIVATE_WITH_EGRESS },
      securityGroups: [mySecurityGroup],
});
Tags.of((endpoint.node.defaultChild as CfnVPCEndpoint)).add('Test', 'true');
```

Will result in: 

```json
...
"Properties": {
    "Tags": [
     {
      "Key": "Test",
      "Value": "true"
     }
    ]
   },
...
```

### Current Behavior

The tag is not added in the synthed template.

### Reproduction Steps

```ts
declare const vpcServiceName: string;
declare const mySecurityGroup: SecurityGroup;

const endpoint = vpc.addInterfaceEndpoint('MyEndpoint', {
      service: new InterfaceVpcEndpointService(vpcServiceName),
      subnets: { subnetType: SubnetType.PRIVATE_WITH_EGRESS },
      securityGroups: [mySecurityGroup],
});
Tags.of((endpoint.node.defaultChild as CfnVPCEndpoint)).add('Test', 'true');
```

### CDK CLI Version

2.76.0 (build 78c411b)

### Node.js Version

v18.12.1

### OS

Mac

### Language

Typescript

**Comment by pahud** [comment]
I believe its because the CFN resource does not support Tag property yet so it will be considered as not Tagable by the TagManager. This is a block on CFN.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html

Please vote up on this issue to help CFN team prioritize it.
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/196

I will leave this issue open until it's supported from CFN.

**Comment by pahud** [comment]
related https://github.com/aws/aws-cdk/issues/19332
