### ISSUE TITLE
aws_rds: add support for RotateImmediatelyOnUpdate to secret rotation

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#25365]
### Describe the feature

In CloudFormation, AWS::SecretsManager::RotationSchedule contains an optional property `RotateImmediatelyOnUpdate`, which controls whether the secret gets rotated as part of the stack update.

When creating a rotation schedule via `add_rotation_single_user` in CDK, there is no way to set this property, so CloudFormation ends up defaulting to `true`.

Add an optional parameter to `add_rotation_single_user` to control this property. Probably should be added to `add_rotation_multi_user` as well.

### Use Case

We don't want the secret to rotate immediately.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.60.0

### Environment details (OS name and version, etc.)

Alpine

**Comment by khushail** [comment]
Hi @rittneje , thanks for reaching out. since Cloudformation provides the [RotateImmediatelyOnUpdate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html#aws-resource-secretsmanager-rotationschedule-syntax) property, addition of parameter like `add_rotation_single_user ` or `add_rotation_multi_user`  might be helpful.

However you could use [Escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html#cfn_layer_cfn) for now, to set `RotateImmediatelyOnUpdate` to false. I am marking this feature request as P2 till it gets worked upon.

**Comment by pahud** [comment]
Hi @rittneje 

[addRotationSingleUser()](https://github.com/aws/aws-cdk/blob/1dbae20bdc633ce580cab8f758a43bfba763c4f6/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L520) literally instantiate [SecretRotation](https://github.com/aws/aws-cdk/blob/1dbae20bdc633ce580cab8f758a43bfba763c4f6/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L549) class, in which the secret addRotateSchedule() [here](https://github.com/aws/aws-cdk/blob/75967e17b8ce3a9d1e0068a3aa210abb247191e6/packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts#L340).

[addRotationSchedule()](https://github.com/aws/aws-cdk/blob/75967e17b8ce3a9d1e0068a3aa210abb247191e6/packages/aws-cdk-lib/aws-secretsmanager/lib/secret.ts#L418) accepts RotationScheduleOptions which is defined [here](https://github.com/aws/aws-cdk/blob/75967e17b8ce3a9d1e0068a3aa210abb247191e6/packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts#L21-L45).

So I believe we should add [RotateImmediatelyOnUpdate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html#cfn-secretsmanager-rotationschedule-rotateimmediatelyonupdate) into the RotationScheduleOptions. Before that, [Escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html#cfn_layer_cfn) as mentioned by @khushail  is a quick hack but we definitely welcome all PR for it.
