### ISSUE TITLE
(AWS Backup): Don't add AWSBackupServiceRolePolicyForBackup policy to role automatically

### ISSUE THREAD

**Issue by delenamalan** [aws/aws-cdk#25669]
### Describe the feature

There should be an option to prevent `BackupSelection` from adding the `AWSBackupServiceRolePolicyForBackup` policy to the provided `role`.

### Use Case

I'm enabling AWS Backup in multiple AWS accounts using [cdk-stacksets](https://github.com/cdklabs/cdk-stacksets/). 

First, I'm creating a role in each account for backup and attaching the `AWSBackupServiceRolePolicyForBackup` and `AWSBackupServiceRolePolicyForS3Backup` policies.

Then, I'm importing this role using `Role.from_role_name`.

```
role = iam.Role.from_role_name("DailyBackupsRole")
```

Then I'm passing the role to `add_selection`:

```
        plan.add_selection(
            "DailyBackupsSelection",
            resources=[backup.BackupResource(resource="*")],  # all resources
            backup_selection_name="DailyBackupsSelection",
            role=role,
        )
```

When I run `cdk synth`, I get this error:

```
RuntimeError: TypeError: role.addManagedPolicy is not a function
```

The above error is caused by https://github.com/aws/aws-cdk/issues/8307.

### Proposed Solution

Add a parameter to `BackupSelection` to make it optional for policies to be attached to a provided role. For example, `attach_backup_policies=False`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.79.1

### Environment details (OS name and version, etc.)

Mac OS 13.3.1 Python 3.7.13

**Comment by peterwoodworth** [comment]
> role = iam.Role.from_role_name("DailyBackupsRole")

Is this how you've specified this in your code? If so, I'm surprised this is compiling since you also need to define the scope and id of the construct. You should just be receiving a warning if `addManagedPolicy` is called on an imported role

https://github.com/aws/aws-cdk/blob/bbdb16ad65b1217901f92782a74a6f13222cd684/packages/aws-cdk-lib/aws-iam/lib/private/imported-role.ts#L70-L72

> Add a parameter to BackupSelection to make it optional for policies to be attached to a provided role. For example, attach_backup_policies=False.

There's already an option you can enable on your role when importing it: [`mutable`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.FromRoleNameOptions.html#mutable)
