### ISSUE TITLE
aws-cdk: cannot spawn node shell if path has spaces

### ISSUE THREAD

**Issue by kahlstrm** [aws/aws-cdk#25729]
### Describe the bug

If you have node installed to e.g. `~/Library/Application Support/fnm/..`, the subprocess fails with
`/bin/sh: /Users/example/Library/Application: No such file or directory`.

### Expected Behavior

running e.g. `cdk diff` should work properly

### Current Behavior

```shell
~ » cdk diff
/bin/sh: /Users/example/Library/Application: No such file or directory

Subprocess exited with code 127
```

### Reproduction Steps

- Have node installed in path that contains space somewhere
- Run some command that uses `execProgram` (e.g. `cdk diff`)
- should fail.

### Possible Solution

This problem occurring has been discussed [here](https://github.com/nodejs/node/issues/38490) quite extensively.

Solution for this is to either do `shell: false` which of the effects I'm unsure of, or wrap the first argument of the execution arguments with quotes.

### CDK CLI Version

2.80.0 (build bbdb16a)

### Node.js Version

v18.16.0

### OS

macOS Ventura 13.3.1 (a)

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this and linking to the relevant thread, we'll take a look at this

**Comment by cufarvid** [comment]
As a workaround, if you're using `fnm`, you can change the default installation directory to something like `~/.fnm` by setting the `FNM_DIR` evironment variable.

**Comment by vinayak-kukreja** [comment]
Hey, thank you for reporting this issue.

This issue as mentioned is being caused by a space being present in the path for node executable. Looking at node github repository issues, it looks like this is a known issue with how node handles spaces in paths. And for CDK, this occurs [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/cxapp/exec.ts#L105-L113).

We currently do not have any plans to fix this on our end. Our recommendation for a workaround here would be to install node at a path which does not have spaces in it.
