### ISSUE TITLE
core: automatic nested stacks

### ISSUE THREAD

**Issue by alibetterup** [aws/aws-cdk#25766]
### Describe the feature

As a developer I do not care about how my resources get deployed, all I care about is that they are.

It would be a great to have CDK create nested stacks automatically when the number of resources per main stacks goes above 500 so the end users does not have to deal with creating new nested stacks or new stacks(apps).

### Use Case

dealing with 500 resources per CF stack

### Proposed Solution

automatic nested stacks by CDK

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.64.0

### Environment details (OS name and version, etc.)

osx ventura

**Comment by pahud** [comment]
This makes sense to me but there's a lot to consider. I am making it a p2 feature request. Please help us prioritize by upvotes.

**Comment by comcalvi** [comment]
CDK should not create nested stacks automatically for you if you exceed the resource limit in a stack. Stack names are permanently part of a resource ID, and if stateful resources (buckets, dynamo tables) are automagically put in a nested stack, you will never be able to refactor them out without losing data. Stack dependencies are already painful to manage, and this feature will increase that pain. CDK has taken the stance that users should be very explicit when defining which resources go into which stacks, since the consequences of that architecture are hard to work around.
