### ISSUE TITLE
(aws-ec2): (ec2.Instance should delete the Instance policies from the Instance role it builds out)

### ISSUE THREAD

**Issue by arbeiterz** [aws/aws-cdk#26594]
### Describe the feature

On attempting to perform a "cdk destroy" against a stack which deployed an instance with ec2.Instance, CDK refuses to destroy it and complains about the fact that the policies must first be removed from the role.  With this feature in place, CDK would recognize that CDK itself had built the role and take steps to remove the policies and delete the role along with the instance.

### Use Case

I would like to be able to simply call, "cdk destroy" against a stack that deployed an EC2 instance with ec2.Instance() and have the instance destroyed without having to do manual clean up.  This is why I want to use CDK to begin with - so I don't have go manually cleaning up a bunch of stuff.

### Proposed Solution

Have CDK recognize the fact that ec2.Instance is contained in the stack and therefore it should expect to have to clean up the role properly on instance deletion.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.89

### Environment details (OS name and version, etc.)

Linux, CDK v2.89

**Comment by khushail** [comment]
@arbeiterz , CDK creates a default role when creating a stack. This role is used to grant permissions to the stack's resources. The default role is not deleted when the stack is destroyed. However, you can override this behavior by setting the role property of the stack to a custom role. This will tell CDK to use the custom role instead of the default role. If you want to delete the default role when the stack is destroyed, you can do so by adding a listener to the destroy event for the stack. The listener can then delete the role.
