### ISSUE TITLE
[Question] Roadmap, out of preview plans

### ISSUE THREAD

**Issue by ali-habibzadeh** [aws/aws-cdk#2666]
Hi,

Do you guys have some roadmap / out of preview dates you can share with the community? 

Mainly around when can we realistically expect to use this in production?

Thanks

**Comment by NGL321** [comment]
Hi Ali!

Sorry it has taken us so long to get back to you. We do not currently have a public roadmap or public dates for going out of preview.
We will certainly put out a roadmap at some point, but for now the dev team is really busy on API stabilization. I will update this issue once we have something online. In the interim, please feel free to watch out for announcements [here](https://aws.amazon.com/new/).

**Comment by ali-habibzadeh** [comment]
But you guys are serious about the project right? I mean it's awesome and makes life so much easier. If we follow and keep ourselves up to date, this will make it to production?

**Comment by eladb** [comment]
Yes, definitely.

**Comment by ali-habibzadeh** [comment]
Thanks for clarifying. I would keep this post. Assuming traction is high on CDK but we just don't know when we can get it. So would be useful for people to see at least commitment is there.

**Comment by digitalsanctum** [comment]
I'm attempting to socialize CDK as a solid option for infrastructure as code at my employer. I work at a very large, multinational company and having an open roadmap similar to how the container team has it setup (see https://github.com/aws/containers-roadmap) would go a long way towards "selling" CDK. There's a wide variety of similar tools in use including hand-written CF, Terraform, etc. Thanks!

**Comment by cpmech** [comment]
We're using CDK for production (start-up project) here!---It's awesome! :smile:

**Comment by IMBurbank** [comment]
I'm going to jump in here instead of creating a new issue.

My company needs to choose an IAC framework by this fall, and we're taking a hard look at adopting CDK. We really like the approach, and have been impressed at how quickly stable construct libraries are being rolled out. 

But to effectively use this project, we would need stable support for a few more constructs:
- Batch
- Cloudfront
- DynamoDB-Global
- RDS

I know it's not currently possible to put a date on when these will be stable. But I am hoping someone can provide guidance about how likely it is for these libraries to be stable this fall.

**Comment by NGL321** [comment]
@IMBurbank I highly recommend checking out our Gitter channel for more regular updates and direct communication with the team. We cant really give dates, but you should be able to get better info there!

@digitalsanctum Sorry we took so long to respond, but ironically, a roadmap is still in the pipeline.

**Comment by NGL321** [comment]
_I am closing issue for now. When available, a roadmap will be pinned to the issue list_

😸

**Comment by IMBurbank** [comment]
Will do, thanks!
