### ISSUE TITLE
(cli-lib-alpha): Missing hotswap option in the deploy command

### ISSUE THREAD

**Issue by amine-mf** [aws/aws-cdk#26785]
### Describe the feature

I'm missing the `hotswap` deployment option in the CDK CLI that is mandatory for our use case.

### Use Case

We use a lambda to deploy state machines, without the `hotswap` it is way too slow for our use.
We are currently using an older version of CDK and trying to upgrade. So we are adapting our code to use `cli-lib-alpha` instead of using `SdkProvider` and `CloudFormationDeployments`.

### Proposed Solution

#26786

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.92.0

### Environment details (OS name and version, etc.)

macOS Ventura

**Comment by peterwoodworth** [comment]
Thanks for the request and PR 🙂

**Comment by fab-mindflow** [comment]
Our team has intensively used internal API to run CDK in lambdas. We are in the process to move to `cli-lib` because we need to stick with latest CDK version. Hence the work by @amine-mf because this is blocking for us. We will continue to provide feedback as needed on this module as we migrate. Do you think this can be merged pretty soon in upcoming release so that we don't fork meanwhile?

**Comment by amine-mf** [comment]
@peterwoodworth A gentle reminder. Thanks a lot. (Sorry to insist, but we really need it)

**Comment by amine-mf** [comment]
I have no idea on your release process, is there a way to know when is the next release?
🙏

**Comment by mrgrain** [comment]
> @mrgrain I have no idea on your release process, is there a way to know when is the next release? 🙏

We release weekly, usually Wednesdays. But various things can affect this.
For this week we seem to be on track.

**Comment by mrgrain** [comment]
I spoke too soon. Looks like it will be Friday this week. @amine-mf
