### ISSUE TITLE
cdk synth returns exit code 0 despite policy validation failures

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#26844]
### Describe the bug

If a custom policy validation reports a failure, `cdk synth` still exits successfully (exit code 0).

### Expected Behavior

A policy validation failure should result in a non-zero exit code.

### Current Behavior

It reports the failure on stdout/stderr but still exits successfully.

### Reproduction Steps

```python
@jsii.implements(aws_cdk.IPolicyValidationPluginBeta1)
class MyPlugin:
    def validate(self, context):
        return aws_cdk.PolicyValidationPluginReportBeta1(success=False)

def main():
    app = aws_cdk.App(policy_validation_beta1=[MyPlugin()])
    env = aws_cdk.Environment(region="us-east-1", account="...")
    stack = aws_cdk.Stack(app, "test-stack", env=env)
    app.synth()

if __name__ == "__main__":
    main()
```

```bash
cdk synth
echo $?
```

### CDK CLI Version

2.85.0 (build 4e0d726)

### Node.js Version

v18.16.1

### OS

Alpine 3.18

### Language

Python

### Language Version

Python 3.11.4

**Comment by peterwoodworth** [comment]
We are setting the exitCode to 1 here https://github.com/aws/aws-cdk/blob/9ccab735b99d1cdc95e7f9483ee62ef940ce91d7/packages/aws-cdk-lib/core/lib/private/synthesis.ts#L162

We know that the code is getting to here because the message right above it is printing in the console before succeeding
<img width="481" alt="Screenshot 2023-08-29 at 2 44 23 PM" src="https://github.com/aws/aws-cdk/assets/44349620/26d7a64d-de1c-474a-a42d-c8aed439d205">

So I tried this on TypeScript, and the process successfully failed. So this would be an issue or limitation of JSII
<img width="472" alt="Screenshot 2023-08-29 at 2 42 37 PM" src="https://github.com/aws/aws-cdk/assets/44349620/8ca23104-24c6-4e86-8e4c-29f21f9edb68">

It's also interesting that the `Performing Policy Validations` loggings statement seems to appear late in Python compared to TypeScript

**Comment by peterwoodworth** [comment]
Hey, we're going to keep the design this way. Thanks for bringing this up still 🙂 

The reason for that is that policy validation plugin is not an enforcement tool. As a developer, you need to opt in for the plugin, you also have an option to skip some rules. There is nothing that stops you from deploying the generated template, despite of policies violations. So, we decided that there is no point to return different values, since this can be confusing (return non-zero exit code can be trggered by other issues)

**Comment by rittneje** [comment]
@peterwoodworth Then the plugin is completely worthless. Please re-open this issue until it is properly resolved.
