### ISSUE TITLE
(kinesisfirehose): DeliveryStream creates useless role

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#26927]
### Describe the bug

The DeliveryStream construct always creates a role https://github.com/aws/aws-cdk/blob/724bd01b8870888ed45783fc952b71cd89408c4e/packages/%40aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts#L325

However, this role ends up with no permissions, and no reason to exist if no source stream or encryption key are used:

```json
  "DeliveryStreamServiceRole0CF4E414": {
   "Type": "AWS::IAM::Role",
   "Properties": {
    "AssumeRolePolicyDocument": {
     "Statement": [
      {
       "Action": "sts:AssumeRole",
       "Effect": "Allow",
       "Principal": {
        "Service": "firehose.amazonaws.com"
       }
      }
     ],
     "Version": "2012-10-17"
    }
   },
   "Metadata": {
    "aws:cdk:path": "EipFailTagsStack/DeliveryStream/Service Role/Resource"
   }
  },
```

### Expected Behavior

I expect no role to be created

### Current Behavior

An unnecessary role is created

### Reproduction Steps

Create a DeliveryStream without an `encryptionKey`, `encryption`, or `sourceStream` prop.

```ts
    new firehose.DeliveryStream(this, 'DeliveryStream', { 
      destinations: [new destinations.S3Bucket(new s3.Bucket(this, 'Bucket'))]
    });
```

### Possible Solution

In this case, will need to check for appropriate props before creating the role

### CDK CLI Version

current

### Node.js Version

16

### OS

mac

### Language

Typescript

### Other information

Can workaround for now with the following escape hatch:
```ts
stream.node.tryRemoveChild('Service Role')
```

**Comment by msambol** [comment]
@peterwoodworth I'll take this.

**Comment by peterwoodworth** [comment]
Thanks!

**Comment by SimardeepSingh-zsh** [comment]
const deliveryStream = new firehose.DeliveryStream(this, 'DeliveryStream', {
  destinations: [new destinations.S3Bucket(new s3.Bucket(this, 'Bucket'))],
});

// Check if encryptionKey, encryption, or sourceStream props are specified
if (!deliveryStream.encryptionKey && !deliveryStream.encryption && !deliveryStream.sourceStream) {
  // If none of these props are specified, do not create the IAM role
  deliveryStream.node.tryRemoveChild('ServiceRole');
}

**Comment by rehanvdm** [comment]
This introduces a new error for existing components: `Error: There is already a Construct with name 'Service Role' in DeliveryStream`

It is because the role is being created again [here](https://github.com/aws/aws-cdk/blob/993ee48a2dfa0732aaa5384220c4e12957f7dd13/packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts#L321) while it was already created in the constructor [here](https://github.com/aws/aws-cdk/blob/993ee48a2dfa0732aaa5384220c4e12957f7dd13/packages/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts#L338). The solution for now is to just specify the role explicitly, like: 

```ts
    const deliveryStream = new kdfAlpha.DeliveryStream(this, idPrefix + 'Firehose', {
      deliveryStreamName,
      destinations: [destinationBucket],
      role: new iam.Role(this, 'Service Role', {
        assumedBy: new iam.ServicePrincipal('firehose.amazonaws.com'),
      })
    })
``` 

This workaround works for the current logic in the component. Just commenting for when others also experience it. Don't think it is high priority since no one has picked it up. Just happens that we do the logic paths that create the role twice.
