### ISSUE TITLE
Error: Resource's path part only allow [a-zA-Z0-9:._-], an optional trailing '+'(module name)

### ISSUE THREAD

**Issue by fd008** [aws/aws-cdk#27083]
### Describe the bug

CDK v2 api gateway won't allow "$" sign in the url, but it "$" is allows using AWS CLI and Console

Error: Resource's path part only allow [a-zA-Z0-9:._-], an optional trailing '+'
      and curly braces at the beginning and the end: $test
    at validateResourcePathPart

### Expected Behavior

No error when using $ in the api path just like AWS CLI or Console

### Current Behavior

Error: Resource's path part only allow [a-zA-Z0-9:._-], an optional trailing '+'
      and curly braces at the beginning and the end: $process-message
    at validateResourcePathPart

### Reproduction Steps

const restApi = new RestApi(this, 'restApi', {
      deploy: true,
})

restApi.root?.addResource("$test")

### CDK CLI Version

2.95.1 (build ae455d8)

### Node.js Version

v18.16.1

### OS

Ubuntu 22.04.2 LTS

### Language

Typescript

### Language Version

5.2.2

**Comment by indrora** [comment]
If I understand this right, this is a CloudFormation limitation, not a CDK limitation at its heart. 

The CLI and Console do not interact with CloudFormation, thus are not subject to its limitations.

**Comment by peterwoodworth** [comment]
@indrora are there any docs from CloudFormation stating this limitation? Have we tried working around this with escape hatches to confirm?

**Comment by indrora** [comment]
* Logical IDs can only have alphanumeric characters: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
* the Name type must be only ASCII letters, digits, and hyphens: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html
* $ is part of `Fn::Sub` and has Weird rules: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html

**Comment by peterwoodworth** [comment]
I see, the issue is that we are taking whatever is passed into `addResource()` and are directly adding it to the logical ID. There isn't any issue with setting the `pathPart` to be accurate with an escape hatch:

```ts
    const restApi = new apigw.RestApi(this, 'restApi', {
      deploy: true,
    });
      
    const apiResource = restApi.root?.addResource("testwithoutdollar");
    (apiResource.node.defaultChild as apigw.CfnResource).addPropertyOverride('PathPart', '$testwithoutdollar');
    restApi.root.addMethod('GET');
```
Deploying this results in the following:
<img width="513" alt="Screenshot 2023-09-11 at 1 07 54 PM" src="https://github.com/aws/aws-cdk/assets/44349620/35187eaf-0a7e-4e0b-8f46-77495d235281">

I think it should work fine if we sanitize the value passed into logical ID here https://github.com/aws/aws-cdk/blob/ae455d822c9da2e4a1b23c548e9d220d8e95a346/packages/aws-cdk-lib/aws-apigateway/lib/resource.ts#L182-L184
