### ISSUE TITLE
(core): delete should be done prioritized over create for the same resource type in the same context 

### ISSUE THREAD

**Issue by JonWallsten** [aws/aws-cdk#27094]
### Describe the bug

I had to change the logical ID for an IP-RecordSet but it failed to create it because the A-Record already exists.
![image](https://github.com/aws/aws-cdk/assets/5993909/4e141d5c-3fdb-4c5b-a346-31425517db23)

![image](https://github.com/aws/aws-cdk/assets/5993909/4bcf2944-5658-4ca0-b986-a38e60103d18)
Checking the diff we can see that one will be destroyed and one will be created.

But they are executed in the opposite order.

### Expected Behavior

I expect the delete to take place before the destroy, since if you have one create and one destroy, the created one should always be the end result. You cannot get a destroy action if you don't have an existing one. So there's only one logical outcome. If I'm not mistaken.
I understand that these are two different resources with no connections and I'm not trying to make it sound like an easy thing to fix.. But if they belong to the same service, and a called from the same context, it should be possible to analyze this scenario. 

### Current Behavior

The process tried to create the new resource before removing the old one causing an error.

### Reproduction Steps

1. Create an IP-RecordSet (A)
2. Rename the logical ID but keep the same values

### Possible Solution

In the cases where it's possible, prioritize the delete actions.

### CDK CLI Version

2.95.0

### Node.js Version

18.14.1

### OS

Windows 10 x64

### Language

Typescript

### Language Version

5.1.6

**Comment by indrora** [comment]
Curious if this is because the created resource and the resource to destroy are of different types.

**Comment by JonWallsten** [comment]
> Curious if this is because the created resource and the resource to destroy are of different types.

They are both AWS::Route53::RecordSet in the same construct. They only change I did was removing the word Public from the ID. Everything else is exactly the same. This I just one example, but I've seen this before with other resources as well.

**Comment by peterwoodworth** [comment]
This is just how CloudFormation works, we call this out in [our docs](https://docs.aws.amazon.com/cdk/v2/guide/identifiers.html#identifiers_logical_ids):

> Logical ID stability
Avoid changing the logical ID of a resource after it has been created. AWS CloudFormation identifies resources by their logical ID. Therefore, if you change the logical ID of a resource, AWS CloudFormation creates a new resource with the new logical ID, then deletes the existing one. Depending on the type of resource, this might cause service interruption, data loss, or both.

Any sort of feature request on this isn't something we could consider, since we don't own CloudFormation and as such cannot do anything about this behavior. All we can do is document the behavior and recommend how to avoid the situation in the first place
