### ISSUE TITLE
s3|ecr: auto-delete-[objects|images] breaks on cloudformation rollback (suspected)

### ISSUE THREAD

**Issue by kaizencc** [aws/aws-cdk#27199]
Based on the way the custom resource is implemented, it is likely that unexpected behavior happens on Cloudformation rollback, i.e. the custom resource will prematurely delete the objects.

Consider the following scenario:

    UPDATE target resource (replacement, creates a new resource)
    UPDATE custom resource (old -> new, objects in old bucket are deleted)
    (...stuff happens...)
    ERROR, triggers a rollback
    UPDATE custom resource (new -> old)
    DELETE target resource (deletes the new resource, remembers the existing one)

We will have deleted objects in the bucket that has been rolled back to in this scenario.

---

The correct way to handle this is what was done in synthetics: 

https://github.com/aws/aws-cdk/blob/3d6d042ec62135627a42ffeae94b13782d78d1cb/packages/%40aws-cdk/custom-resource-handlers/lib/aws-synthetics-alpha/auto-delete-underlying-resources-handler/index.ts#L26-L36

As opposed to

https://github.com/aws/aws-cdk/blob/3d6d042ec62135627a42ffeae94b13782d78d1cb/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/auto-delete-objects-handler/index.ts#L23-L35

**Comment by GavinZZ** [comment]
I can confirm that this is a reproducible issue. Here's the cdk code I used
```
const bucket = new s3.Bucket(this, 'Bucket', {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      bucketName: <a bucket name that's not used>,
      autoDeleteObjects: true,
    });

    // Intentionally failure since `mybucket-1` exists
    const bucket2 = new s3.Bucket(this, 'Bucket2', {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      bucketName: <a bucket name that's not used>,
    });

    bucket2.node.addDependency(bucket);
```

Once the deployment is successful, add some random content to the bucket, then update the code so that the first bucket's `bucketName` is updated to another valid name. Update the second bucket's `bucketName` to be an existing bucket name, which will trigger a deployment failure hence roll back. 

The stack is rolled back, but the content is the bucket is not deleted.
