### ISSUE TITLE
Wrong SAM container image architecture when trying to build NodeJS lambda

### ISSUE THREAD

**Issue by r007** [aws/aws-cdk#27370]
### Describe the bug

Hello guys,

After recent changes, my `cdk deploy` stopped working. I have a few lambdas declared as following:

```ts
const myLambda = new NodejsFunction(this, 'Example', {
  entry: join(__dirname, `/../../some/path.ts`),
  runtime: Runtime.NODEJS_18_X,
  architecture: Architecture.ARM_64,
  memorySize: 256,
  bundling: {
    minify: true,
    externalModules: ['@aws-sdk/client-dynamodb']
  }
})
```

I use `architecture: Architecture.ARM_64` to save some costs. On my desktop machine I have Ubuntu Linux (amd64 architecture). So when I type `cdk deploy MyStack` it launches sam build command for every lambda function. Docker images are starting to download, I see the following line:

```
--> Command: docker build -t cdk-e46d15a7662e461d1d19a3c4b3874cda9ae1d1d3f77bb3e2068a7e2c5d164204 --platform "linux/arm64" --build-arg "IMAGE=public.ecr.aws/sam/build-nodejs18.x" --build-arg "ESBUILD_VERSION=0" "/home/r007/Projects/my-project/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib"
```

Notice the `--platform "linux/arm64"` flag.

It fails on the very first command:

```
 > [ 2/10] RUN npm install --global yarn@1.22.5:
0.333 exec /bin/sh: exec format error
```

Because of the incompatibility of ARM64 architecture with AMD64.

### Expected Behavior

It should not use target architecture for building JavaScript code. It worked just fine before I updated cdk dependency.

### Current Behavior

It fails with error message `exec /bin/sh: exec format error`

### Reproduction Steps

1. Create `NodejsFunction` with any content.
2. Use `architecture: Architecture.ARM_64`.
3. Do `cdk deploy`.

### CDK CLI Version

2.99.1 (build b2a895e)

### Node.js Version

v18.17.1

### OS

Ubuntu 22.04.3 LTS

### Language

Typescript

**Comment by indrora** [comment]
Part of the process for build and deployment of the NodeJsLambdaFunction construct involves pulling down an appropriate runtime to compile any typescript. This means that we're pulling an ARM64 Node runtime (since that's the runtime that you've asked for). 

If you can compile your typescript beforehand in a reasonable manner, the typical Lambda L2 construct will work fine, as the Asset system can be made to simply bundle the local content for the far runtime on AWS Lambda rather than compiling it inside a container. 

**HOWEVER**, if that's not an option, there is one, I must stress **very not-supported but somewhat useful workaround**: the `multiarch` container. Details at https://github.com/multiarch/qemu-user-static

The short form is, you launch a special, *privileged* container:

```
$ docker run --rm --privileged multiarch/qemu-user-static:register
```

and this will register a series of QEMU backends as available to run different architectures. You must do this every time you start the Docker daemon.  

I will stress this again, **This is not officially supported in any way by AWS, Caveat Emptor.** An explanation of what is going on is in this StackOverflow post: https://stackoverflow.com/questions/72444103/what-does-running-the-multiarch-qemu-user-static-does-before-building-a-containe
