### ISSUE TITLE
importedRoleStackSafeDefaultPolicyName feature flag results in excessively long IAM policy names

### ISSUE THREAD

**Issue by DharmSonariya** [aws/aws-cdk#27409]
### Describe the bug

When using the @aws-cdk/aws-iam:importedRoleStackSafeDefaultPolicyName feature flag with the CDK pipeline, the CDK generates exceedingly long IAM policy names that exceed AWS's character limits.

### Expected Behavior

The CDK should generate names that respect AWS's character limits regardless of feature flag settings.

### Current Behavior

When this feature flag is enabled, I get an error indicating that the policy name has exceeded the maximum allowed length (128 characters). The error message is as follows:

CREATE_FAILED Properties validation failed for resource Route53CrossAccountZoneDelegationRecordcrossaccountzonedelegationhandlerrolePolicyCadPlatformtoolboxDevToolchainCdkPipelineDevCadPlatformDevRoute53CrossAccountZoneDelegationRecordcrossaccountzonedelegationhandlerrole195BFE8B8FD65C38 with message: #/PolicyName: expected maxLength: 128, actual: 148

### Reproduction Steps

Enable the @aws-cdk/aws-iam:importedRoleStackSafeDefaultPolicyName feature flag with the CDK pipeline,
Define a stack that imports an IAM role and attach policies to it.
Deploy the stack.

### CDK CLI Version

2.99.1 (build b2a895e)

### Node.js Version

v18.18.0

### OS

Ubuntu 23.04

### Language

Python

### Language Version

Python 3.11.5

**Comment by peterwoodworth** [comment]
Can you please share a minimal code sample? I'm not exactly sure how you're using the role

**Comment by DharmSonariya** [comment]
Certainly, please find the code below:

>         route53.CrossAccountZoneDelegationRecord(
>             self,
>             "CrossAccountZoneDelegationRecord",
>             delegated_zone=self._public_hosted_zone,
>             parent_hosted_zone_name=constants.MY_PUBLIC_DOMAIN,
>             delegation_role=self.delegation_role,
>         )

**Comment by peterwoodworth** [comment]
Thanks, I see what's going on here.

The feature flag makes use of `Names.uniqueId()`. The max length when using this method is 256 https://github.com/aws/aws-cdk/blob/495dafa2a1f4d7efc6aaddd217df3535dd940d52/packages/aws-cdk-lib/core/lib/private/uniqueid.ts#L30

I wonder if it would have been better to use `Names.uniqueResoureName()` instead, it allows for setting the max length option directly. https://github.com/aws/aws-cdk/blob/495dafa2a1f4d7efc6aaddd217df3535dd940d52/packages/aws-cdk-lib/core/lib/names.ts#L83

It may be a better call to truncate the result returned from `Names.uniqueId()` here since we're already using this method https://github.com/aws/aws-cdk/blob/495dafa2a1f4d7efc6aaddd217df3535dd940d52/packages/aws-cdk-lib/aws-iam/lib/private/imported-role.ts#L49

**Comment by isacaraujo** [comment]
There's an older issue: https://github.com/aws/aws-cdk/issues/24441
