### ISSUE TITLE
AssetImage.fromAsset() not rebuilding docker images

### ISSUE THREAD

**Issue by vaugenwake** [aws/aws-cdk#27492]
### Describe the bug

I was using `AssetImage.fromAsset()` to build and push my docker images into ECR for an ECS cluster.

This works find on the first run but if I try to "redeploy" my application without any code changes a new images is not built and tagged and therefore my tasks are not stopped and restarted with the new images.

This used to work perfectly fine until recently.

### Expected Behavior

A new image is tagged, built and pushed on each deployment regardless of if there are any code changes.

### Current Behavior

Deployment/Redeployment is skipped and no changes are pushed to Cloudformation.

### Reproduction Steps

- Create a new ECS cluster using CDK
- Create a task definition and build the container images using `AssetImage.fromAsset()`
- Deploy the application
- Deploy the application again, the docker images are not rebuilt and the deployment is skipped.

### CDK CLI Version

2.99.1

### Node.js Version

18.x

### OS

Ubuntu

### Language

TypeScript

**Comment by vaugenwake** [comment]
Any update on this???

**Comment by indrora** [comment]
If there are no code changes, this is done by design. 

If there is a change in some upstream Docker container that you depend on, use `docker pull [name]` to fetch the current version; this will cause the checksumming that the CDK uses to make sure that the docker image hasn't changed identifies a new version.
