### ISSUE TITLE
(cli): cdk watch does not recover if there is an error in cdk stack/app

### ISSUE THREAD

**Issue by ssingh-01** [aws/aws-cdk#27864]
### Describe the bug

If I made an error that does not resolve into a valid cloudformation, cdk watch throws the error on console. However, if I fix that issue, I would expect cdk to detect the issue to resolve and deploy the correct cloudformation template. CDK watch gets hung instead.

### Expected Behavior

Expect cdk watch to redeploy once the error has been fixed.

### Current Behavior

If I made an error that does not resolve into a valid cloudformation, cdk watch throws the error on console. However, if I fix that issue,  CDK watch gets hung. It detects the change but does not deploy.

### Reproduction Steps

This is a valid stack and app : 
```
app = App()
ApiEventBridgeLambdaStack(app, "ApiEventBridgeLambdaStack")
```
If I update it to the following while cdk watch is running, cdk watch will throw the error but stays hung after I fix the error (remove a mistyped N in this case): 
```
app = App()
ApiEventBridgeLambdaStack(appN, "ApiEventBridgeLambdaStack")
```

This happens with stack level changes as well.

Detects change but does not deploy, stays in hung state  : 

![image](https://github.com/aws/aws-cdk/assets/97851237/bff23c44-089e-4924-bd90-4b07e2364111)

### CDK CLI Version

v2.100.0

### Node.js Version

v18.16.0

### OS

MAC

### Language

Python

### Language Version

3.10.6

### Other information

Reproducible with typescript too
Workaround is to interrupt the terminal and re run cdk watch.

**Comment by khushail** [comment]
thanks @ssingh-01 for reporting this.

**Comment by misterjoshua** [comment]
I'm running into this issue as well. I've been working around the issue with ctrl c and re-running cdk watch.

I think the issue is that the cdk cli isn't releasing the outdir lock when a synth fails. The problem is here: https://github.com/aws/aws-cdk/blob/40a8e610f3bf538ce9105e7c092fedbe115e30f6/packages/aws-cdk/lib/api/cxapp/exec.ts#L62

I think the lines that follow should live in a try/catch - when the exec fails, I think the catch should probably release the lock and rethrow the error.
