### ISSUE TITLE
s3.Bucket.import Type Error

### ISSUE THREAD

**Issue by southpolesteve** [aws/aws-cdk#2802]
**Describe the bug**
s3.Bucket.import is throwing a type error. Did something change? All the docs I can find including the source code docs make it seem like this should work.

**To Reproduce**
```
import * as s3 from '@aws-cdk/aws-s3'

export class AppStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    const bucket = s3.Bucket.import(this, {
      bucketArn: `arn:aws:s3:::bucket-name`
    })
  }
}
const app = new cdk.App()
```
**Expected behavior**
No type error

**Version:**
 - OS OSX
 - Programming Language Node.JS+Typescript
 - CDK Version 0.33.0

**Comment by rileylyman** [comment]
Did you mean `const bucket = s3.Bucket.fromBucketAttributes(...)`? Or could you point me to the source code / documentation you are referring to that defines `import` on `Bucket`?

**Comment by southpolesteve** [comment]
https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/aws-s3/lib/bucket.ts#L245-L261
https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/aws-s3/README.md#importing-existing-buckets

**Comment by rileylyman** [comment]
I see. My Bad!

**Comment by RomainMuller** [comment]
The inline doc is clearly outdated/incorrect here.

**Comment by ConradMearns** [comment]
Is there a quick way around this issue as it gets worked on? Downgrading perhaps?

**Comment by rmichaelb** [comment]
Should it be:
`const bucket: Bucket = s3.Bucket.fromBucketArn(this, 'importedBucketFromARN', 'someBucketArn')`

Rather in reality its:
`const bucket: IBucket = s3.Bucket.fromBucketArn(this, 'importedBucketFromARN', 'someBucketArn')`

Why wouldn't `fromBucketArn` return the Class rather than the Interface?
With it returning the IBucket Interface it makes it impossible to "import" a bucket from another nested stack, thus creating circular dependencies.

Does anyone have a workaround for this?

**Comment by lisp-ceo** [comment]
Having the same issue with importing buckets that have KMS keys defined. The encryption keys are coming back undefined.

**Comment by SteffenLanger** [comment]
@rmichaelb, did you ever find a solution/workaround?

I'm trying to add CORS rules to an existing bucket:
```
const existingBucket: IBucket = Bucket.fromBucketName(this, bucketResourceId, bucketName);
existingBucket.addCorsRule({
    allowedHeaders : [
        "*"
    ],
    allowedMethods : [
        HttpMethods.PUT
    ],
    allowedOrigins : [
        "https://www.example.com"
    ],
})
```

But the AWS CDK throw an error `existingBucket.addCorsRule is not a function` because the bucket is not an instance but only this incomplete IBucket interface.
Adding CORS headers works for buckets created with `new Bucket(...)`.

**Comment by iliapolo** [comment]
@SteffenLanger `Bucket.fromBucketName` creates an `IBucket` as opposed to a `Bucket` because it represents a *reference* to an existing bucket. 

It is only a reference, it doesn't actually query the bucket configuration or have the ability to mutate it. Nor does it translate into a `Bucket` resource in your template, and sense [CORS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-crossoriginconfig) can only be configured on the `AWS::S3::Bucket` resource, the `addCorsRule` method does not exist on `IBucket`.
