### ISSUE TITLE
sagemaker: Create L2 construct for Amazon SageMaker

### ISSUE THREAD

**Issue by mattmcclean** [aws/aws-cdk#2809]
There is currently only L1 support for Amazon SageMaker. Would be nice to have an L2 construct to support SageMaker notebook instances, models and endpoints.

This is being actively worked on in three phases 🚀:

- [x]  feat(sagemaker): add Model L2 construct
- [ ] feat(sagemaker): add EndpointConfig L2 construct
- [ ] feat(sagemaker): add Endpoint L2 construct

**Comment by petermeansrock** [comment]
@kaizencc Even though only the first of three model hosting PRs have been merged, this issue was auto-closed due to (I assume) the presence of `fixes #2809` in my first commit.

1. Will you please reopen this issue so that we can continue tracking L2 deliverables against it (or if you'd prefer issues per L2 construct, could you reframe this one to align against the `Model` construct and I can create additional issues)?
2. Assuming you'd like to continue shipping PRs as part of this issue, would it be possible for you to adjust Matt's description to align with the scope of the RFC, including these three deliverables?
    - feat(sagemaker): add Model L2 construct
    - feat(sagemaker): add EndpointConfig L2 construct
    - feat(sagemaker): add Endpoint L2 construct
3. Should I avoid using `fixes #2809` in the next two PRs?

**Comment by kaizencc** [comment]
@petermeansrock done :). Let's just say something like `related to #2809` for the second PR and then we can say `closes #2809` for the last one. So they'll still get linked to the issue. Thanks for getting the first part in!
