### ISSUE TITLE
Amazon.CDK.AWS.Apigatewayv2.Integrations namespace still missing with 2.114.1.

### ISSUE THREAD

**Issue by icelava** [aws/aws-cdk#28348]
### Describe the bug

https://github.com/aws/aws-cdk/issues/28255 closed so reporting new one.

Apparently 2.114.0 is supposed to include the missing Amazon.CDK.AWS.Apigatewayv2 sub-modules and namespaces, but they are still regarded as non-existent by Visual Studio.

### Expected Behavior

Amazon.CDK.AWS.Apigatewayv2.Integrations namespace (and HttpAlbIntegration) available from Amazon.CDK.Lib package.

### Current Behavior

Amazon.CDK.AWS.Apigatewayv2.Integrations namespace does not exist.

### Reproduction Steps

- Update VS project to Amazon.CDK.Lib 2.114.1 (from 2.111.0).
- Drop Amazon.CDK.AWS.APIGatewayv2.Alpha, Amazon.CDK.AWS.APIGatewayv2.Alpha.Integrations packages.

### CDK CLI Version

2.111.0

### Framework Version

.NET 6.0

### Node.js Version

18.9.0

### OS

Windows 11

### Language

.NET

### Language Version

C# 10

**Comment by pahud** [comment]
I was able to import that from VSCode with cdk 2.114.1




```ts
import { 
  aws_apigatewayv2 as apigwv2,
  aws_apigatewayv2_authorizers as apigwv2_authorizers,
  aws_apigatewayv2_integrations as apigwv2_integrations,
} from 'aws-cdk-lib';

export class DemoStack extends Stack {
  readonly fn: lambda.IFunction;
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const fn = lambda.Function.fromFunctionName(this, 'LambdaFunc', 'dummy');
    const defaultIntegration = new apigwv2_integrations.HttpLambdaIntegration('LambdaInteg', fn)
    new apigwv2.HttpApi(this, 'Api', {
      defaultIntegration,
    });

  }
}
```

```
% npx cdk --version
2.114.1 (build 02bbb1d)
```

**Comment by icelava** [comment]
It working for npm package does not mean it will work for NuGet package.

**Comment by icelava** [comment]
Trying out 2.118.0 and still the namespace and classes are missing. Is anybody verifying the NuGet packages?

![Amazon CDK AWS Apigatewayv2 Integrations missing](https://github.com/aws/aws-cdk/assets/1930886/4e7f61a1-e434-434e-807c-6c33ba335268)

**Comment by icelava** [comment]
Ouch so it turns out the official Integrations module has been renamed to a very un-.NET namespace of `Amazon.CDK.AwsApigatewayv2Integrations`. I don't know why there's this sudden break from convention but at least some mention in the documentation would have been highly appreciated.

**Comment by ashishdhingra** [comment]
Issue appears to be reproducible:
- For API Gateway v2 Integrations, looks like the new namespace is `Amazon.CDK.AwsApigatewayv2Integrations` instead of expected `Amazon.CDK.AWS.Apigatewayv2.Integrations`.
- For API Gateway v2 Authorizers, looks like the new namespace is `Amazon.CDK.AwsApigatewayv2Authorizers` instead of expected `Amazon.CDK.AWS.Apigatewayv2.Authorizers`.

These namespaces should have followed consistent namespace after experimental construct was promoted to publicly supported L2 construct. Could be the issue with .NET package release process where it might have taken input from TypeScript packages `aws-apigatewayv2-authorizers` and `aws-apigatewayv2-integrations`, and might have simply concatenating the elements separated with `-`, in sentence case.
