### ISSUE TITLE
SSM: StringParameter.ValueFromLookup returns old value

### ISSUE THREAD

**Issue by werebear73-tritelph** [aws/aws-cdk#28956]
### Describe the bug

The function StringParameter.ValueFromLookup doesn't return the newest value of the of the SSM Parameter.

### Expected Behavior

That the StringParameter.ValueFromLookup function returns the most recent value of the SSM Parameter.

### Current Behavior

StringParameter.ValueFromLookup returns an older value even though you even destroy the Parameter and recreate it.  I even tried deleting the cdk.out folder but the original value of the Parameter is returned.

### Reproduction Steps

Create a StringParameter in a separate stack and project.  Read the value in a different Project.  Go back to the original project and destroy the stack and recreate.  Return to the second project and the value with still be the original value.

### CDK CLI Version

2.124.0 (build 4b6724c)

### Node.js Version

v20.10.0

### OS

Wiindows 11

### Language

.NET

### Language Version

8.0.101

**Comment by pahud** [comment]
This is because the value was cached in your `cdk.context.json` and will not return the newer value unless the cache is reset.

For example if I lookup the `foo` parameter for the first time

```ts
const stringValue = ssm.StringParameter.valueFromLookup(this, 'foo');
```

and check `cdk.context.json` I will see the cache with the key `"ssm:account=ACCOUNT_ID:parameterName=foo:region=us-east-1"` 

I can reset it with

```sh
npx cdk context --reset ssm:account=ACCOUNT_ID:parameterName=foo:region=us-east-1
```

See the document about cdk context for more details
https://docs.aws.amazon.com/cdk/v2/guide/context.html

Let me know if it works for you.
