### ISSUE TITLE
codepipeline: Add Branches and File Paths to CodePipeline pipeline GitPushFilter configuration

### ISSUE THREAD

**Issue by einstein-aws** [aws/aws-cdk#29124]
### Describe the feature

Currently, as it seems, only tag-based filters are available (or exposed) in CodePipeline pipeline GitPushFilter configuration via  ```tagsExcludes``` and ```tagsIncludes``` parameters. However, both ```Branches``` and ```FilePaths``` options exist in CloudFormation spec https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-gitpushfilter.html Can you please add the two missing configuration parameters? Thanks!

### Use Case

Branch-based pipeline trigger.

### Proposed Solution

Add ```branchesExclude```, ```branchesInclude```, ```filePathsExclude``` and ```filePathsInclude``` parameters to match CloudFormation spec.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.128.0 (TypeScript)

### Environment details (OS name and version, etc.)

MacOS Sonoma 14.3.1

**Comment by go-to-k** [comment]
I will take this issue.

**Comment by vumdao** [comment]
@go-to-k Can you please update for `packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts` either? Thanks.

**Comment by go-to-k** [comment]
@vumdao 

The `pipelines` module already seems to be quite different in structure from `aws-codepipeline`. It might be better if you could create a separate issue with specific use cases.
In the meantime, we can pass existing pipelines to props, so that might help us meet the requirements even before we have to deal with that.

https://github.com/go-to-k/aws-cdk/blob/a21731c9b1f34525433fbee668ebb2321debf5b8/packages/aws-cdk-lib/pipelines/README.md#using-an-existing-aws-codepipeline

**Comment by pahud** [comment]
Awesome! Thank you for picking this up with a PR. @go-to-k

**Comment by jmihalich** [comment]
+1 for adding this to the cdk CodePipeline construct.  I've been waiting for this.

Joe

**Comment by mostafafarzaneh** [comment]
+1 for this feature. Is there any update?

**Comment by go-to-k** [comment]
[The PR](https://github.com/aws/aws-cdk/pull/29127) is awaiting review, so please be patient.

If the number of reactions (👍) to this issue is high, it will be given priority for review. So please do.

**Comment by mglubb** [comment]
For those still needing this, pending the PR being merged, you can use the [cdk escape hatch](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html). E.g.

```
const cfnPipeline = pipeline.node.defaultChild as CfnPipeline;
cfnPipeline.addPropertyOverride('Triggers', [
  {
    GitConfiguration: {
      Push: [
        {
          Branches: {
            Includes: ['main'],
          },
        },
      ],
      SourceActionName: 'MySourceName',
    },
    ProviderType: 'CodeStarSourceConnection',
  }
]);
```

**Comment by wilhen01** [comment]
Can we reopen this issue since the fix was reverted?

**Comment by dguisinger** [comment]
> Can we reopen this issue since the fix was reverted?

@go-to-k see @wilhen01's message above.  It looks like this change was reverted.

**Comment by go-to-k** [comment]
Perhaps the reopening can only be done by maintainers. Therefore, creating a new issue is a good.

**Comment by wilhen01** [comment]
Raised as #31009

**Comment by dguisinger** [comment]
> Re-raised as #31009

@wilhen01 there appear to be a tangled mess of cross-referencing issues and pull requests I was digging through last night while trying to figure out how to get this to work on my project.  It appears this was rejected because it didn't meet the standards of how the CDK team wants to do things, and there has been a draft pull request sitting out there since June 10th:  https://github.com/aws/aws-cdk/pull/30516

However there has been no movement for 45 days

**Comment by wilhen01** [comment]
Thanks @dguisinger - I've mentioned that in the new issue.

**Comment by jamierbower** [comment]
@mglubb Thanks for posting the work around using escape hatches. 

I have tried implementing that fix, however when I try to deploy I am getting the following error: "Triggers for connections must reference a CodeStarSourceConnection action." 

Am I right in thinking the value for "SourceActionName" should be the same as the "Name" property of the Source stage in my pipeline?

**Comment by moltar** [comment]
> Am I right in thinking the value for "SourceActionName" should be the same as the "Name" property of the Source stage in my pipeline?

Omg, spent hours banging my head, but it was so simple. Thank you!
