### ISSUE TITLE
iam: addManagedPolicy is not implemented

### ISSUE THREAD

**Issue by github-anis-snoussi** [aws/aws-cdk#29195]
### Describe the issue

Running the current latest version on aws-cdk-lib (2.128.0), the Group construct static method `addManagedPolicy` is not implemented (as can be seen [here](https://github.com/aws/aws-cdk/blob/v2.80.0/packages/aws-cdk-lib/aws-iam/lib/group.ts#L95)).

This is not mentioned in the documentation [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Group.html#addwbrmanagedwbrpolicypolicy) and it just fails silently which is unexpected behaviour.

**Proposed (temporary) solution** : it should be mentioned clearly in the documentation that this method isn't implemented yet, to prevent other people banging their heads on the wall like I did 😅.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Group.html#addwbrmanagedwbrpolicypolicy
https://github.com/aws/aws-cdk/blob/v2.80.0/packages/aws-cdk-lib/aws-iam/lib/group.ts#L95

**Comment by pahud** [comment]
Yes, thank you for the callout. We should get it fixed.

**Comment by xazhao** [comment]
As @GavinZZ mentioned, `addManagedPolicy` is not implemented because it's in the abstract class. In the extended `Group` class, the function is implemented.
https://github.com/aws/aws-cdk/blob/v2.80.0/packages/aws-cdk-lib/aws-iam/lib/group.ts#L213

Close the issue for now. Feel free to re-open if you have any other questions.
