### ISSUE TITLE
AutoScaling construct has no launch configuration parameter

### ISSUE THREAD

**Issue by lkoniecz** [aws/aws-cdk#2925]
According to cloudformation documentation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html

I should be able to pass a launchconfiguration to the ASG constructor, but it's not supported.
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/AutoScalingGroup.html

In particular, I am interested in setting EKS managed worker nodes IAM profile so that my pods have necessary permissions to execute AWS API. Launch configuration is created behind the scenes with auto-generated instance profile, but I have no clue whatsoever how to add policies to it.

**Comment by NGL321** [comment]
https://github.com/awslabs/aws-cdk/blob/c75d245b229f8c88f890fc51597319d217896ddd/packages/%40aws-cdk/aws-autoscaling/test/test.auto-scaling-group.ts#L362-L371

Is this what you were looking for? (I realize its typescript rather than python)
I'm wondering if this is simply missing in documentation, or if it is actually missing from the codebase.

I am seeing it as a L1 CfnResource here:
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/CfnLaunchConfiguration.html

If this isnt what you are looking for, a more concrete example of what you are trying to do would be super helpful!

**Comment by lkoniecz** [comment]
I am sorry, but I don't know what the expect --> to statement does.

**Comment by NGL321** [comment]
Sorry for the long delay. The code I commented was a test bank for the L1 at the time. The expect statement was an assertion of the JSON that should be output.

The long and short of it is that the L1 construct has the field you were looking for, but the L2 just skips it and all launch configuration parameters are segregated out.

I'm not sure if this is still relevant, but I hope it helps.

😸

**Comment by lkoniecz** [comment]
My can can be escape-hatched. I am fine with closing this.
