### ISSUE TITLE
(custom-resources): After failed update of AwsCustomResource, log stream ID is passed to onDelete, causing it to get stuck

### ISSUE THREAD

**Issue by Booligoosh** [aws/aws-cdk#30012]
### Describe the bug

I am creating an AWS custom resource that requires replacement every time, meaning the onCreate & onUpdate both return a physicalResourceId and don't require one as input, however the onDelete does require one as input using `new cr.PhysicalResourceIdReference()`:

```typescript
new cr.AwsCustomResource(this, 'aws-custom', {
  onCreate: {
    service: '...',
    action: '...',
    parameters: {
      text: '...',
    },
    physicalResourceId: cr.PhysicalResourceId.fromResponse('...'),
  },
  onUpdate: {
    service: '...',
    action: '...',
    parameters: {
      text: '...',
    },
    physicalResourceId: cr.PhysicalResourceId.fromResponse('...'),
  },
  onDelete: {
    service: '...',
    action: '...',
    parameters: {
      text: '...',
      resourceId: new cr.PhysicalResourceIdReference(),
    },
  },
  policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
    resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE,
  }),
})
```

When an update fails, the physical ID is changed to a log stream ID, eg. `2024/04/30/[$LATEST]xxxxxxxx`. CFN then tries to call onDelete with this log stream ID as the resource ID, which obviously fails, meaning onDelete gets stuck.

### Expected Behavior

When an update fails, the physical resource ID is not changed, and onDelete is called with the existing physical resource ID.

### Current Behavior

When an update fails, the physical resource ID is changed to be the ID of a log stream, and onDelete is called with that log stream ID as the physical resource ID, causing it to fail.

### Reproduction Steps

1. Create an AWS Custom Resource like the example above, with `new cr.PhysicalResourceIdReference()` passed to onDelete.
2. Deploy the resource
3. Trigger an update of the resource that fails for some reason (eg. invalid format of parameter)
4. Observe that onDelete is called with a log stream ID rather than the physical ID of the resource

### Possible Solution

The bug comes from this line in the SDK v2 handler:
https://github.com/aws/aws-cdk/blob/fd3a5e30a3a140a106ee1f0b97fb40f18ab7e681/packages/%40aws-cdk/custom-resource-handlers/lib/custom-resources/aws-custom-resource-handler/aws-sdk-v2-handler.ts#L175

And this line in the SDK v3 handler:
https://github.com/aws/aws-cdk/blob/fd3a5e30a3a140a106ee1f0b97fb40f18ab7e681/packages/%40aws-cdk/custom-resource-handlers/lib/custom-resources/aws-custom-resource-handler/aws-sdk-v3-handler.ts#L171

When sending a FAILED event, `context.logStreamName` is passed as the physical resource ID to `respond()`, rather than passing `physicalResourceId`. I've been trying to work out the reasoning behind why it's like this and nothing has come to mind, I can't see any scenario where you want a failure log stream as the physical ID, so it could just be an accidental error.

The fix would be to pass `physicalResourceId` as the 4th parameter to `respond()` rather than passing `context.logStreamName`.

### CDK CLI Version

2.115.0

### Node.js Version

20.11.1

### OS

Windows 10 Enterprise

### Language

TypeScript

**Comment by pahud** [comment]
Thank you. We'll check this with the team.

**Comment by pahud** [comment]
By the way

I would highly recommend not using for both onCreate and onUpdate because you can't guarantee they are always the same.

```ts
physicalResourceId: cr.PhysicalResourceId.fromResponse('...'),
```

Let's consider this scenario:

1. Your onCreate was successful and you got the API response hence `physicalResourceId` was assigned.
2. Now you try to update that custom resource and failed. Because it was failed and no expected response field returned, you ended up having different physicalResourceId assigned.
3. Because now you have different physicalResourceId between onUpdate and onCreate, CFN would consider you are trying to replace the old resource with a new resource but failed. Now `onDelete` would be invoked trying to delete that failed `onUpdate` resource.
4. This ended up always trying to create a new one to replace the created one and invoking the onDelete again.

With that being said, I would suggest to make the physicalResourceId decoupled with the API response like

```ts
physicalResourceId: cr.PhysicalResourceId.of('some-static-id');
```

I guess this would not trigger the unexpected loop as I presume above.

Let me know if it works for you.
