### ISSUE TITLE
MAKE CLOUDFORMATION ROLLBACKS FASTER AND DONT BLOCK SUBSEQUENTIAL DEPLOYMENTS

### ISSUE THREAD

**Issue by AllanOricil** [aws/aws-cdk#30029]
### Describe the feature

3 minutes to deploy and end up with an error, then a rollback initialized. This rollback took longer than the deploy? why? Is it done manually by an engineer? 

<img width="1091" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/5810b563-c0ba-42bf-8e7b-9b2e7cf6a974">

### Use Case

NOT GET PISSED OFF WITH THE AMOUNT OF TIME IT TAKES TO RETRY A CDK DEPLOYMENT

### Proposed Solution

ROLLBACKS could be done instantly if all resources were put on a "trash bin" and later handled by AWS internal services. Why make us wait for you to purge them? Put them on a separate place and handle the deleting afterwards. Consider user initiated deleteion events as the a proof the User agrees to have those resources deleted. I'm extremelly irritaded right now because a simple stack that takes 3 minutes to be deployed took more than 20 minutes to be rolledback. This is a horrible DX.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.139

### Environment details (OS name and version, etc.)

macos

**Comment by pahud** [comment]
Thank you for your feedback and we appreciate. This is actually not something CDK can do but cloudformation and we suggest submit your feedback to cloudformation. I still have some suggestions for you though to help you accelerate your development cycle from CDK's perspective.

1. Incremental deploy for large stacks - if you have a lot of resources in a single stack, instead of deploy them all at once, try deploy part of them every single time. This would avoid rolling back all deployed resources that could take a long time.
2. Use `cdk deploy -R` to [stop rolling back](https://aws.amazon.com/blogs/aws/new-for-aws-cloudformation-quickly-retry-stack-operations-from-the-point-of-failure/) and continue your deployment from where it failed.  This allows you to inspect the failure description and resume at where it failed.
3. If the failed stack has to rollback and it takes a lot of time, instead of waiting for the rollback complete, you can simply change a new stack name in your `app.ts` and redeploy it as a new stack. For example:

```ts
const app = new cdk.App();
new MySampleStack(app, 'my-stack'); // <== change `my-stack` to `my-stack2` and deploy
```

This allows you to have a separate stack deploying for a very quick inspection while the old one would eventually complete its rollback and stop.

4. Last but not least, we are implementing the [cloudformation optimistic stabilization strategy](https://aws.amazon.com/blogs/devops/how-we-sped-up-aws-cloudformation-deployments-with-optimistic-stabilization/#:~:text=To%20improve%20stack%20provisioning%20times,to%20be%20created%20in%20parallel.) support in CDK CLI and hopefully you will see a huge improvement from the perspective of CDK. See this [PR](https://github.com/aws/aws-cdk/pull/29536) for more details and we welcome your feedback.


I hope you find the tips above useful and enjoy your CDK journey.
