### ISSUE TITLE
When creating a role allow multiple conditioned roles in assumeby property   

### ISSUE THREAD

**Issue by NetaNir** [aws/aws-cdk#3006]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

When creating an IAM Role the assumeby property only allows a single role or multiple roles via the CompositePrincipal but the CompositePrincipal doesn't allow conditions and throws: 
```
Components of a CompositePrincipal must not have conditions
```
This can be accomplished by using the L1 CfnRole assumeRolePolicyDocument property which accepts a policy statement that allows multiple roles

* **What is the expected behavior (or behavior of feature suggested)?**

could be nice to have assumeby accept an array of principals roles or have CompositePrincipal allow conditions 

* **What is the motivation / use case for changing the behavior or adding this feature?**
I can add all of the principals roles in the Role creation 

* **Please tell us about your environment:**
  
  - CDK CLI Version:0.35
  - Module Version: 0.35
  - OS: OSX 
  - Language: TS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by NGL321** [comment]
I believe this is a duplicate of issue #1578. I am marking this for closing, please add a "+1" to the other issue to bump it. Otherwise let me know here if you think your issue is distinct and I will keep this open!

Please bear in mind however, we are working hard to stabilize the CDK APIs and tuning them to meet our consistency guidelines. While we work on getting the APIs aligned with our guidelines, we are pausing work on most community PRs and feature-requests. Please continue to report issues and submit feature requests, of course. We expect to get back to work on community input within a few weeks.
