### ISSUE TITLE
(batch): missing JobStateTimeLimitActions in the JobQueue Construct

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30142]
### Describe the feature

Missing JobStateTimeLimitActions in the JobQueue Construct.

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobqueue.html#cfn-batch-jobqueue-jobstatetimelimitactions

### Use Case

To react to blocked job queues.

It has been added at 2024/3.

https://aws.amazon.com/jp/blogs/hpc/introducing-new-alerts-to-help-users-detect-and-react-to-blocked-job-queues-in-aws-batch/

### Proposed Solution

Add JobStateTimeLimitActions property the JobQueue Construct.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.141.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
Hey @mazyu36  I am looking forward to all your PRs. Feel free to submit for that. Thank you.

**Comment by sandeepkumar2810** [comment]
Hello
Could you please provide an estimated timeframe for when this feature will be incorporated? Additionally, I am curious if there are alternative methods available within the AWS CDK codebase to address this issue seems this is also not supported with batch.CfnJobQueue

Looking forward to your response and appreciate your assistance.

**Comment by mazyu36** [comment]
I'm implementing it now. It seems to be already supported in the CfnJobQueue.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_batch.CfnJobQueue.html#jobstatetimelimitactions
