### ISSUE TITLE
AWS IAM: Unable to add AWSBackupServiceRolePolicyForBackup

### ISSUE THREAD

**Issue by Roedy13** [aws/aws-cdk#30363]
### Describe the bug

I'm trying to create a backup role with the policies "AWSBackupServiceRolePolicyForBackup" and "AWSBackupServiceRolePolicyForS3Backup"

```
  backup_role = aws_iam.Role(
      scope=self,
      id="backup_role",
      role_name=BACKUP_ROLE_NAME,
      assumed_by=aws_iam.ServicePrincipal("backup.amazonaws.com"),
      managed_policies=[
          aws_iam.ManagedPolicy.from_aws_managed_policy_name(
              "AWSBackupServiceRolePolicyForBackup"
          ),
          aws_iam.ManagedPolicy.from_aws_managed_policy_name(
              "AWSBackupServiceRolePolicyForS3Backup"
          ),
      ],
  )
```

### Expected Behavior

I expect a role to be created with the attached permissions

### Current Behavior

When I run this code, I get a CDK error:

```
Resource handler returned message: "Policy arn:aws:iam::aws:policy/AWSBackupServiceRolePolicyForBackup does not exist or is not attachable. (Service: Iam, Status Code: 404, Request ID: a76f50aa-3a8e-45d1-824f-
6ab1e3212290)" (RequestToken: 0bf40c12-6daf-14eb-4005-29c3c8ddedbd, HandlerErrorCode: NotFound)
```

Notice the the ARN listed for this role is NOT the same as the arn from the IAM webconsole, which is 

`
arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
`

### Reproduction Steps

Try to deploy the code above

### Possible Solution

I'm assuming that the ARN isn't being generated correctly from "aws_iam.ManagedPolicy.from_aws_managed_policy_name"

When I change the above code to

```

  # Create a role for Backup
  backup_role = aws_iam.Role(
      scope=self,
      id="backup_role",
      role_name=BACKUP_ROLE_NAME,
      assumed_by=aws_iam.ServicePrincipal("backup.amazonaws.com"),
      managed_policies=[
          aws_iam.ManagedPolicy.from_managed_policy_arn(
              scope=self,
              id="service_backup_policy",
              managed_policy_arn="arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup",
          ),
          aws_iam.ManagedPolicy.from_aws_managed_policy_name(
              "AWSBackupServiceRolePolicyForS3Backup"
          ),
      ],
  )
```

It works as expected

### CDK CLI Version

2.142.1 (build ed4e152)

### Framework Version

aws-cdk@2.142.1

### Node.js Version

v18.18.2

### OS

Debian 12

### Language

Python

### Language Version

3.12.1

**Comment by khushail** [comment]
Hi @Roedy13 , thanks for reaching out.

I see that the 2 roles mentioned generate diff arns -
- for [AWSBackupServiceRolePolicyForBackup](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AWSBackupServiceRolePolicyForBackup.html) , the generated  ARN: arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup

- for [AWSBackupServiceRolePolicyForS3Backup](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AWSBackupServiceRolePolicyForS3Backup.html), the generated ARN: arn:aws:iam::aws:policy/AWSBackupServiceRolePolicyForS3Backup


Issue happens when the first policy arn is not generated correctly. In the CDK Docs, I found that for policies which have arn preceded by `service-role` or `job-function`, one has to specify that explicitly while passing the policy name, something this-

https://github.com/aws/aws-cdk/blob/8c39e8161970705c76f93ec99934f9b3b76da294/packages/aws-cdk-lib/aws-iam/lib/managed-policy.ts#L155

So changing the code -

```ts
      managedPolicies: [
        aws_iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSBackupServiceRolePolicyForBackup'),
```

which is deployed successfully. Please let me know if this works for you.

**Comment by Roedy13** [comment]
That seems to work.  Thanks!
