### ISSUE TITLE
cloudformation stack termination protection is ignored when deployed through pipelines (L3) module

### ISSUE THREAD

**Issue by andreprawira** [aws/aws-cdk#30405]
### Describe the bug

i'm deploying just a simple s3 stack that creates an s3 bucket, here is the code
```
class S3(Stack):
    def __init__(
        self, scope: Construct, construct_id: str, props: S3StackProps, **kwargs
    ) -> None:
        super().__init__(scope, construct_id, termination_protection=True, **kwargs)
        
frontend_bucket = s3.Bucket(
            self,
            "frontend-bucket",
            removal_policy=cdk.RemovalPolicy.DESTROY,
            auto_delete_objects=True,
            object_ownership=s3.ObjectOwnership.BUCKET_OWNER_ENFORCED,
            bucket_name="my-frontend-bucket",
        )
```
**If** i deploy this stack locally (cdk deploy s3 stack), the stack and the bucket got created succesfully **AND** the stack itself has termination protection **activated**. **However**, if I deploy this stack using this pipelines L3 [module ](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.pipelines/README.html) (i have to define the stage and instantiate the S3Stack)
```
class ApplicationStage(Stage):
    def __init__(
        self, scope: Construct, id: str, props: ApplicationStageProps, **kwargs
    ):
        super().__init__(scope, id, **kwargs)

        S3Stack(
            self,
            "s3-stack",
            props=CloudfrontStackProps(
                customer=props.customer,
            ),
        )
```
then if i destroy the previously existing S3 stack first, then if i release the pipeline, it works, the stage is created, and the stack got created. However, the stack itself doesnt have termination protection enabled. 

### Expected Behavior

termination protection on the stack created by codepipeline should also be activated

### Current Behavior

termination protection on the stack created by codepipeline is deactivated

### Reproduction Steps

please view my code

### CDK CLI Version

2.117.0 (build 59d9b23)

### Node.js Version

v18.18.0

### OS

Windows

### Language

Python

### Language Version

Python 3.11.5

**Comment by andreprawira** [comment]
@khushail can you help pls

**Comment by khushail** [comment]
@andreprawira , I see that a request have been added on the [cloudformation coverage roadmap ](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1127)and also team decided in [putting out a warning ](https://github.com/aws/aws-cdk/issues/17871#issuecomment-1003980845)for the pipeline based deployment. CDK Team has already filed internal ticket (Ticket -D36476047) with Cloudformation team to provide support for this. I would check the ticket and see if we can get any traction on that.

Since this is a duplicate issue, I would be closing this one and will post further updates on previous issue. Thanks!
