### ISSUE TITLE
IAM: Python show error of type ServicePrincipal

### ISSUE THREAD

**Issue by canle1404** [aws/aws-cdk#30431]
### Describe the bug

I'm using pyright and it shows this error message. However, my stack is still able to be deployed.

```
Argument of type "ServicePrincipal" cannot be assigned to parameter "assumed_by" of type "IPrincipal" in function "__init__" Pyright (reportArgumentType) [33, 24]
     "ServicePrincipal" is incompatible with protocol "IPrincipal" 
       "IPrincipal" is incompatible with "ServicePrincipal" 
       "IPrincipal" is incompatible with "ServicePrincipal" 
       "IPrincipal" is incompatible with "ServicePrincipal" 
       "add_to_principal_policy" is an incompatible type 
         Type "(_statement: PolicyStatement) -> AddToPrincipalPolicyResult" is incompatible with type "(statement: PolicyStatement) -> AddToPrincipalPolicyResult" 
           Parameter name mismatch: "statement" versus "_statement" 
       "IGrantable" is incompatible with "ServicePrincipal" 
```

### Expected Behavior

No error message

### Current Behavior

error message

### Reproduction Steps

* Install pyright
* Init a Python CDK project
* Create a role, e.g
```python
from aws_cdk import Stack, aws_iam as iam
from constructs import Construct

class PycdkStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        role = iam.Role(
            self, "Role", assumed_by=iam.ServicePrincipal("ec2.amazonaws.com")
        )
```
* Run `pyright ./stack.py`

### CDK CLI Version

2.144.0 (build 5fb15bc)

### Node.js Version

v20.12.1

### OS

Ubuntu 22.04

### Language

Python

### Language Version

3.10.12

### Other information

pyright 1.1.365

**Comment by ashishdhingra** [comment]
@canle1404 Good morning. The above code synthesizes successfully using `cdk synth` giving below output:
```YAML
Resources:
  Role1ABCC5F0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PythonStack/Role/Resource
...
...
```

Running `pyright <<stack.py>>` returns the below error:
```
error: Argument of type "ServicePrincipal" cannot be assigned to parameter "assumed_by" of type "IPrincipal" in function "__init__"
    "ServicePrincipal" is incompatible with protocol "IPrincipal"
      "IPrincipal" is incompatible with "ServicePrincipal"
      "IPrincipal" is incompatible with "ServicePrincipal"
      "IPrincipal" is incompatible with "ServicePrincipal"
      "add_to_principal_policy" is an incompatible type
        Type "(_statement: PolicyStatement) -> AddToPrincipalPolicyResult" is incompatible with type "(statement: PolicyStatement) -> AddToPrincipalPolicyResult"
          Parameter name mismatch: "statement" versus "_statement"
      "IGrantable" is incompatible with "ServicePrincipal" (reportArgumentType)
```

However,
- [iam.assumedBy](https://github.com/aws/aws-cdk/blob/2a00ddd43fe5b718488292296cf5d8b8677b6e32/packages/aws-cdk-lib/aws-iam/lib/role.ts#L34C12-L34C21) is of type [IPrincipal](https://github.com/aws/aws-cdk/blob/2a00ddd43fe5b718488292296cf5d8b8677b6e32/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L39)
- [ServicePrincipal](https://github.com/aws/aws-cdk/blob/2a00ddd43fe5b718488292296cf5d8b8677b6e32/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L532) extends [PrincipalBase](https://github.com/aws/aws-cdk/blob/2a00ddd43fe5b718488292296cf5d8b8677b6e32/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L148), which further implements [IAssumeRolePrincipal](https://github.com/aws/aws-cdk/blob/2a00ddd43fe5b718488292296cf5d8b8677b6e32/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L117) > [IPrincipal](https://github.com/aws/aws-cdk/blob/2a00ddd43fe5b718488292296cf5d8b8677b6e32/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L39).

Per inheritance and polymorphism rules, it should be possible to assign `ServicePrincipal` concrete type to interface type `IPrincipal` (not vice versa).

The `pyright` static type checker is also checking the parameter names like `Parameter name mismatch: "statement" versus "_statement"`. I'm unsure if it is possible to limit the scope of the `pyright` to the current code stack, rather than installed libraries. Perhaps, you could try opening discussion in https://github.com/microsoft/pyright repository for guidance.

Thanks,
Ashish

**Comment by shea-parkes** [comment]
I suppose it's too much to ask Amazon devs and Microsoft devs to work together to fix this one?  (Amazon devs on this CDK and Microsoft devs on `pyright`...)
