### ISSUE TITLE
Feat (CLI): Addition of a flag to override the context json file path

### ISSUE THREAD

**Issue by karmabadger** [aws/aws-cdk#30494]
### Describe the feature

# Feat (CLI): Addition of a flag to override the context json file path.
Often times, you may have different environments and deployment strategies. Being able to switch the cdk.json context file easily helps keeping commands constant but easily switch the context which is used to run them.

For instance package.json can have a script `deploy` which uses `cdk.json` and then a `deploy:dev` which reads `cdk.dev.json`.

### Use Case

I'm always frustrated when I want a quick dev stack for development purposes but my prod stack has to compile all the TS files into JS, run tests, and then deploy whereas the dev stack should just quickly transpile into JS using something like SWC for quicker iteration. But since I need to make sure my prod environment run correctly from the built JS files instead of SWC, I have to keep everything consistent to the slower path.

### Proposed Solution

adding the flag `--context-json` (or any other alternative to this if this is too confusing compared to the other context flag) to override the default `cdk.json` file.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.144.0 (build 5fb15bc)

### Environment details (OS name and version, etc.)

MacOS Sonoma 14.5

**Comment by khushail** [comment]
Hi @karmabadger , thanks for reaching out. I see your usecase could be worked upon by the solution suggested here -
https://github.com/aws/aws-cdk/issues/23911#issuecomment-1420124264

However we have this open issue and few similar requests in the past as well -
Currently opened issue - https://github.com/aws/aws-cdk/issues/23911 (quite similar to your request)
Past issue - https://github.com/aws/aws-cdk/issues/14948

Please confirm if you feel the issue is similar to open issue  and I could mark it appropriately for further assistance.

**Comment by karmabadger** [comment]
it is similar, but also those are long due
@khushail.
I really need isolated prod vs dev.

**Comment by virajkanwade** [comment]
@khushail I had also submitted a PR implementing the feature.
https://github.com/aws/aws-cdk/pull/23912

But since I am no TypeScript expert, I could not figure out the tests. So it was not merged.

For a feature that was requested exactly 3 years ago, with a potential solution shared 1.5 years ago, it is still open because nobody wants to take up updating the unit tests.

**Comment by khushail** [comment]
@karmabadger , thanks for the response. I have marked the issue as P1 for team's input and attention.

@virajkanwade , appreciate your work on PR submission. Apologies, you were not able to get the needed help. Here are few resources you could use to get the required help -

1. official CDK contribution guide - https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md
2. YT video walkthrough on a real pull request - https://www.youtube.com/watch?v=ZRxDwAvyQGc
3. [cdk.dev](http://cdk.dev/) community slack #contributing channel. Please feel free to post here and someone from the community might be able to help you out.

Generally the PR review would first go through [community review ](https://github.com/aws/aws-cdk/wiki/CDK-Community-PR-Reviews)and then maintainers review, but if you complete the PR with CI pass I think you can cut an internal ticket to escalate the review directly to the core team. Let me know if you need anything.

**Comment by comcalvi** [comment]
It would be helpful if you could clarify all the keys in `cdk.json` that you would like to specify different values for, depending on the environment. The use case you gave above suggests that you want to change the compilation command used to build your application. This is the `app` key in `cdk.json`, but you can override the value with `--app` on the command line. 

Does that address your use case, or is there other keys you'd like to change?
