### ISSUE TITLE
stepfunctions-tasks: CallAwsServiceCrossRegion uses wrong casing for ECS

### ISSUE THREAD

**Issue by ADringer** [aws/aws-cdk#30799]
### Describe the bug

Hi, I'm using the new task `CallAwsServiceCrossRegion` from #30061  to update an ECS service in a different region. In the task I have to pass in parameters as PascalCase but the actual call fails in the client ecs saying the service identifier has not been provided as it's expecting camelCase.

### Expected Behavior

The parameters passed from the task successfully invoke the aws service. Maybe mapping the casing accordingly.

### Current Behavior

The parameters are entered into the task as PascalCase:
```
"parameters": {
                "Cluster.$": "$.cluster",
                "Service.$": "$.service",
                "ForceNewDeployment": true
}
```

And this fails with the error `InvalidParameterException: Service Identifier cannot be empty`.

### Reproduction Steps

Create a task that calls ECS e.g:
```
new tasks.CallAwsServiceCrossRegion(this, "ecs-update-service", {
          service: 'ecs',
          action: 'updateService',
          iamResources: ['*'],
          region: 'us-east-2',
          parameters: {
            "Cluster.$": "myCluster",
            "Service.$": "myService",
            "ForceNewDeployment": true
          },
        })
```

### Possible Solution

Looking at the code, if `ecs` cdk expects all camelCase parameters, we could update this that's causing the issue:

```
if (props.parameters) {
      const invalidKeys = Object.keys(props.parameters).filter((key) => !key.startsWith(key[0]?.toUpperCase()));
      if (invalidKeys.length) {
        throw new Error(`parameter names must be PascalCase, got: ${invalidKeys.join(', ')}`);
      }
    }
```

to be something like 
```
const camelCaseServices: String[] = ['ecs'];

if (props.parameters) {
      const invalidKeys = Object.keys(props.parameters).filter((key) => !key.startsWith(key[0]?.toUpperCase()));
      if (invalidKeys.length && !camelCaseServices.include(props.service)) {
        throw new Error(`parameter names must be PascalCase, got: ${invalidKeys.join(', ')}`);
      }
    }
``` 

So this ignores the check for the ecs service, and can add other services that require camelCase

### CDK CLI Version

2.147.3

### Node.js Version

20

### OS

Linux

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@ADringer Good morning. I think your issue is similar to https://github.com/aws/aws-cdk/issues/30662#issuecomment-2190107842. CDK internally uses JavaScript SDK to invoke service operation for this scenario. If you refer [ECS API Reference::UpdateService](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html), the parameters [cluster](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#API_UpdateService_RequestSyntax), [service](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#API_UpdateService_RequestSyntax) and [forceNewDeployment](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#API_UpdateService_RequestSyntax) are in camel case. 

So the parameter name casing appears to be dependent on service API, Pascal case might not be true for all the service.

The validation [here](https://github.com/aws/aws-cdk/blob/f48becb4fcb8e2f4076f00bd5a2c53edce639fed/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/lambda/call-aws-service-cross-region.ts#L115) appears to be incorrect and should be possibly removed.

Thanks,
Ashish

**Comment by xazhao** [comment]
Hi, I think this issue exists not only in the new `CallAwsServiceCrossRegion` but also in the original `CallAwsService` because the code is the same.

**Comment by tmokmss** [comment]
@xazhao Actually, no, because `CallAwsService` uses Step Functions' native AWS SDK integration, it seems it actually only accepts PascalCase parameters. (I tried that in bedrock-runtime API.)
