### ISSUE TITLE
EKS data plane cannot be created

### ISSUE THREAD

**Issue by arun-gupta** [aws/aws-cdk#3100]
The current docs at https://docs.aws.amazon.com/cdk/api/latest/docs/aws-eks-readme.html indicate that CDK only creates EKS Control Plane and Data Plane needs to be created following the user guide.

Without a Data Plane API, CDK's use for creating EKS cluster is very restrictive.

**Comment by NGL321** [comment]
Hi Arun!

Thank you for bringing this up. This is an important gap in our EKS coverage.
At the moment Cloudformation [doesn't support explicit Data Planes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html), and since we are focused on ECS and Fargate for containers right now, it may be a little while before this sees support. 

You should still be able to create useful EKS clusters with the current setup, but if you want to expedite the process, creating a post in the [CFN forums](https://forums.aws.amazon.com/forum.jspa?forumID=92&start=0) could nudge them to work on this feature!

I am going to close this issue for the moment, but I will reopen it when there is Cloudformation coverage of this feature!

**Comment by arun-gupta** [comment]
Can we open this issue for tracking purpose?

eksctl and Pulumi allows data planes to be created seamlessly and would love to see the support here.

**Comment by eladb** [comment]
Yes, let's keep this open. We can totally provide a solution based on custom resources in the CDK without explicit CloudFormation support, and I personally think it would be a great investment for the project.

**Comment by eladb** [comment]
Resolved by #3510
