### ISSUE TITLE
Add support for UDP protocol in NLB

### ISSUE THREAD

**Issue by vinayselvaraj** [aws/aws-cdk#3107]
The NLB now supports the UDP protocol: https://aws.amazon.com/about-aws/whats-new/2019/06/network-load-balancer-now-supports-udp-protocol/.  Please add support for it in the CDK.

**Comment by NGL321** [comment]
Hi Vinay!

Thank you for sharing the link and the info!
Doing a quick scan of their documentation, it looks like Cloudformation does not yet support UDP for the Elastic Load Balancer. Until they have support, we are not able to add coverage to the CDK.

If you would like to expedite the process, please feel free to make a post on the [Cloudformation forums](https://forums.aws.amazon.com/forum.jspa?forumID=92) to let them know that this should go in the pipeline.
I am going to close this issue for now since there is nothing we can do at the moment, however, I will reopen it once there is CFN coverage.!

**Comment by vinayselvaraj** [comment]
CloudFormation was updated to support UDP on the NLB: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-protocol

**Comment by NGL321** [comment]
@vinayselvaraj 
Thank you for the catch! I have updated the status, and we will look into adding this as soon as we have time.

**Comment by jdiamond** [comment]
If anybody needs a workaround until this is implemented, this worked for me:

```
const listener = nlb.addListener('Listener', {
  port: 1234
});

const targets = listener.addTargets('Targets', {
  port: 1234,
  targets: [asg]
});

const cfnListener = listener.node.findChild('Resource') as elbv2.CfnListener;
cfnListener.addPropertyOverride('Protocol', 'UDP');

const cfnTargets = targets.node.findChild('Resource') as elbv2.CfnTargetGroup;
cfnTargets.addPropertyOverride('Protocol', 'UDP');
```
