### ISSUE TITLE
aws-cognito: "Resource of type 'AWS::Cognito::LogDeliveryConfiguration' with identifier '' already exists.

### ISSUE THREAD

**Issue by AllanOricil** [aws/aws-cdk#31242]
### Describe the bug

After updating the logConfigurations array, from  cognit.CfnLogDeliveryConfiguration, with a new LogConfiguration and updating and older one to point to new log group, I got this error

![image](https://github.com/user-attachments/assets/9f8167de-b878-4f7f-868b-d9939d5350da)

- The ERROR log group is the one I updated the log arn
- The INFO log group is the one I added

The ARN is built by hand because of this other issue I [discovered](https://github.com/aws/aws-cdk/issues/31241). It works, don't worry. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

never worked

### Expected Behavior

- old LogConfiguration should have had its logs group updated without throw any errors

### Current Behavior

- can't update LogConfiguration entries

### Reproduction Steps

1. create CfnLogDeliveryConfiguration with 1 LogConfiguration of ERROR and eventSource UserNotification
2. deploy
3. update the LogGroup and its ARN in this LogConfiguration you just deployed
4. deploy
5. verify that it wont be updated and the same error will be thrown

### Possible Solution

Log group configuration has to be deleted before new one can be created.

### CDK CLI Version

2.154.0

### Framework Version

2.154.0

### Node.js Version

18.19

### OS

macos

### Language

TypeScript

### Language Version

5.0.4

**Comment by ashishdhingra** [comment]
@AllanOricil Good afternoon. Could you please share the following:
- Minimal reproducible code along with steps which updates the LogGroup Arn? (I understand you are affected by issue https://github.com/aws/aws-cdk/issues/31241, for which we have opened ticket with the CloudFormation team)
- Output of `cdk synth`, before and after 1st and 3rd step.
- Textual content of error (instead of screenshot) so that is's more readable.

Thanks,
Ashish
