### ISSUE TITLE
aws_ec2: New construct - CfnSubnetCidrReservation 

### ISSUE THREAD

**Issue by williwlwilliwll** [aws/aws-cdk#31341]
### Describe the feature

(Unless I'm going crazy) I don't think there is a way to create subnet CIDR reservations through the CDK like there is through the SDK, API, or CLI (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSubnetCidrReservation.html).  I propose a new L1 construct - CfnSubnetCidrReservation - to fill this gap. 

### Use Case

After deploying my beautiful CDK stacks I then have to manually create the CIDR reservations myself. I would love to have the process fully automated.

### Proposed Solution

Create a new L1 construct - CfnSubnetCidrReservation

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.156

### Environment details (OS name and version, etc.)

MacOS Sonoma 14.6.1

**Comment by khushail** [comment]
Hi @williwlwilliwll , thanks for reaching out. I checked [cloudformation resource specification docs](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) and found that there is no such L1 construct for SubnetCidrReservation, the only available construct for Cidr is-

[AWS:EC2:SubnetCidrBlock](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnetcidrblock.html) - [CfnSubnetCidrBlock](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnSubnetCidrBlock.html)

Since this needs support from Cloudformation first, I would recommend you to create a FR with Cloudformation team, on their [Coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues). 

Let me know if you need any further help! Thanks

**Comment by williwlwilliwll** [comment]
Thanks @khushail, have created one now - https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/2127
