### ISSUE TITLE
aws-servicediscovery: hostedZone NameServers undefined behaviour

### ISSUE THREAD

**Issue by adminy** [aws/aws-cdk#31391]
### Describe the bug

```javascript
const namespace = new PublicDnsNamespace(
  stack,
  'ServiceDiscoveryDnsNamespace',
  {
    vpc, name: process.env.PUBLIC_DNS
  }
)
const hostedZone = PublicHostedZone.fromPublicHostedZoneId(
  stack,
  'ServiceDiscoveryNs',
  namespace.namespaceHostedZoneId
)
console.log(">>>>>>>", hostedZone.hostedZoneNameServers, 'should not be undefined!!! but it is ...')

const certificate = new acm.Certificate(stack,  'SSL', {
    domainName: process.env.PUBLIC_DNS,
    hostedZone: hostedZone,
    subjectAlternativeNames: ['*.' + process.env.PUBLIC_DNS],
    transparencyLoggingEnabled: false,
    validation: acm.CertificateValidation.fromDns(hostedZone),
})
```

![image](https://github.com/user-attachments/assets/07cde88d-805b-4a1e-b902-a9b6e5de0339)

- its not a private hosted zone, its public, coming from a public Dns Namespace.
- Its within the same stack.

also errors:
```javascript
API: certificatemanager:changeResourceRecordSets
The resource hostedzone/XYZ... can only be managed through AWS CloudMap 
(arn:aws:servicediscovery:eu-west-1:${accountId}:namespace/ns-xyz...)
```
### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Its an array of NS records instead of undefined.

### Current Behavior

undefined is returned

### Reproduction Steps

code above ^

### CDK CLI Version

2.153.0 (build 2bccd85)

### Node.js Version

v20.16.0

### OS

NixOS 24.11.20240906.645018b (Vicuna) x86_64 

### Language

TypeScript

**Comment by khushail** [comment]
Hi @adminy , thanks for reaching out. 
I found a similar issue that was reported long time back -https://github.com/aws/aws-cdk/issues/11108
Since [hostedzonenameservers](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_route53.HostedZone.html#hostedzonenameservers) is an String array, you could try out this suggestions- 
https://github.com/aws/aws-cdk/issues/11108#issuecomment-716944888
https://github.com/aws/aws-cdk/issues/11108#issuecomment-753526964

Let me know if this works for you!
