### ISSUE TITLE
[apigateway] Using CfnParameter as stagename

### ISSUE THREAD

**Issue by mutescu-marius** [aws/aws-cdk#3157]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

```
  const apiStage = new cdk.CfnParameter(this, "my-api-stage", {
             default: "beta",
             type: "String",
             allowedValues: ['beta', 'gamma', 'prod'],
             description: "Api stage."
         })

new apigateway.RestApi(this, 'MyApi', {
            endpointTypes: [EndpointType.Private],
            policy: this.createResourcePolicy(),
            deployOptions: {
                tracingEnabled: true,
                metricsEnabled: true,
                loggingLevel: MethodLoggingLevel.Error,
                dataTraceEnabled: true,
                stageName: apiStage.ref
            }
        })
```
```
Error: Cannot use tokens in construct ID: DeploymentStage.${Token[MyApiApiStage.Ref.130]}
```

* **What is the expected behavior (or behavior of feature suggested)?**
StageName should not be used for generating Stage ID and the construct should be valid.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Deploying the api on multiple stages and passing the stage as input. 

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.34.xx
  - OS: [all ]
  - Language: [TypeScript]

**Comment by SomayaB** [comment]
Hi @mutescu-marius, I'm sorry for the late reply. Are you still experiencing this issue?

**Comment by nija-at** [comment]
Hi @mutescu-marius - Unfortunately, this is an intentional design choice of the CDK. 

When we build our construct tree, we do not allow certain values to be tokens (Documentation on tokens can be found [here](https://docs.aws.amazon.com/cdk/latest/guide/tokens.html)). 

In particular, the ids of the nodes in our construct tree are not allowed to be tokens. In order to generate reliable and repeatable CloudFormation templates from a CDK app, we need these values to be concrete at the time of synthesis.

By looking at your code snippet, it seems like you want to synthesize a single CloudFormation template and use it across multiple stages, by passing the stage as a CloudFormation parameter.
When it comes to modeling a CDK app, this is generally discouraged. A better way to do this is to model all of your environments within the app itself. 

This translates into modeling your infrastructure as a subclass of `Stack` (say `MyStack`) and having multiple instances of these register into a single `App` instance as so - 

```ts
interface MyStackProps extends StackProps {
  readonly stageName: string;
}

class MyStack extends Stack {
  constructor(scope: string, id: string, props: MyStackProps) {
    super(scope, id, props);
  }

  ...
  ...
}

const app = new cdk.App();
new MyStack(this, { stageName: 'beta', env: { account: '8373873873', region: 'us-east-1' } });
new MyStack(this, { stageName: 'gamma', env: { account: '2383838383', region: 'eu-west-1' } });
...
```

Hope that helps.

**Comment by nija-at** [comment]
Closing this for now. Re-open if you have more questions or need more guidance.
