### ISSUE TITLE
rds: support for local write forwarding for an Aurora PostgreSQL cluster

### ISSUE THREAD

**Issue by go-to-k** [aws/aws-cdk#31802]
### Describe the feature

Amazon Aurora PostgreSQL now supports local write forwarding:

Whats new: https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-aurora-postgresql-local-write-forwarding/

Reference: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-postgresql-write-forwarding.html

### Use Case

The current CDK L2 construct only supports the feature for MySQL, but PostgreSQL needs to be supported as well.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.162.1

### Environment details (OS name and version, etc.)

Mac

**Comment by ashishdhingra** [comment]
- Confirmed from [Local write forwarding in Aurora PostgreSQL](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-postgresql-write-forwarding.html) that Amazon Aurora PostgreSQL now supports local write forwarding. This support was added recently. 
- [AWS::RDS::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html) supports [EnableLocalWriteForwarding](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enablelocalwriteforwarding) property.

@go-to-k Unsure if CloudFormation yet supports this for Aurora PostgreSQL since it takes time for CF to support it. Please check if using escape hatch works for Aurora PostgreSQL and CF doesn't throw any error.

**Comment by go-to-k** [comment]
@ashishdhingra 

I haven't tried escape hatch, but I was able to deploy cfn with integ test, so I guess it meets the requirements?
