### ISSUE TITLE
Bedrock: PROMPT_ATTACK inside of contentPolicyConfig is not accepting NONE in CfnGuardrail

### ISSUE THREAD

**Issue by noahsdonaldson** [aws/aws-cdk#31919]
### Describe the bug

Using CDK CfnGuardrail in Bedrock I set the contentPolicyConfig filterConfig settings.  PROMPT_ATTACK should be set to "NONE" but when doing a cdk synth or cdk build the values for inputStrength and outputStrength are set to "HIGH".  The deployment to CloudFormation fails because the only value that should be set for PROMPT_ATTACK is "NONE".

Here is the CDK CfnGuardrail definition
```TypeScript
// Gaurdrail above graphqlapi def
    const myGuardrail = new CfnGuardrail(this, 'myBedrockGuardrail', {
      blockedInputMessaging: 'Input message blocked by Bedrock guardrail.',
      blockedOutputsMessaging: 'Output messages blocked by Bedrock guardrail.',
      name: `Guardrail-${envName}`,
      // Optional properties
      contentPolicyConfig: {
        filtersConfig: [
          {
            inputStrength: 'HIGH',
            outputStrength: 'HIGH',
            type: 'SEXUAL',
          },
          {
            inputStrength: 'HIGH',
            outputStrength: 'HIGH',
            type: 'VIOLENCE',
          },
          {
            inputStrength: 'HIGH',
            outputStrength: 'HIGH',
            type: 'HATE',
          },
          {
            inputStrength: 'HIGH',
            outputStrength: 'HIGH',
            type: 'INSULTS',
          },
          {
            inputStrength: 'HIGH',
            outputStrength: 'HIGH',
            type: 'MISCONDUCT',
          },
          {
            inputStrength: 'NONE',
            outputStrength: 'NONE',
            type: 'PROMPT_ATTACK'
          }
        ],
      },
    });
```

Here is the cdk.out template that is generated
```JSON
  "myBedrockGuardrail": {
   "Type": "AWS::Bedrock::Guardrail",
   "Properties": {
    "BlockedInputMessaging": "Input message blocked by Bedrock guardrail.",
    "BlockedOutputsMessaging": "Output messages blocked by Bedrock guardrail.",
    "ContentPolicyConfig": {
     "FiltersConfig": [
      {
       "InputStrength": "HIGH",
       "OutputStrength": "HIGH",
       "Type": "SEXUAL"
      },
      {
       "InputStrength": "HIGH",
       "OutputStrength": "HIGH",
       "Type": "VIOLENCE"
      },
      {
       "InputStrength": "HIGH",
       "OutputStrength": "HIGH",
       "Type": "HATE"
      },
      {
       "InputStrength": "HIGH",
       "OutputStrength": "HIGH",
       "Type": "INSULTS"
      },
      {
       "InputStrength": "HIGH",
       "OutputStrength": "HIGH",
       "Type": "MISCONDUCT"
      },
      {
       "InputStrength": "HIGH",
       "OutputStrength": "HIGH",
       "Type": "PROMPT_ATTACK"
      }
     ]
    },
    "Name": "Guardrail-beta"
   },
   "Metadata": {
    "aws:cdk:path": "beta-APIStack/myBedrockGuardrail"
   }
  },
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

none

### Expected Behavior

When setting `PROMPT_ATTACK` to `NONE`, the cdk.out for `PROMPT_ATTACK` is set to `NONE`, not `HIGH`.

### Current Behavior

The cloud formation output file has `PROMPT_ATTACK` set to `HIGH` regardless of the value set in in the CDK.

### Reproduction Steps

Create a CDK, import CfnGuardrail, set contentPolicyConfig, filtersConfig PROMPT_ATTACK inputStrength and outputStrength to "NONE" and run a cdk synth to check the cdk.out file.

### CDK CLI Version

2.162.1 (build 10aa526)

### Node.js Version

Node.js v18.18.2

### OS

Amazon Linux 2 x86_64 5.10 Kernel

### Language

TypeScript

### Language Version

5.4.5

**Comment by ashishdhingra** [comment]
@noahsdonaldson Good morning. Somehow I'm unable to reproduce the issue using the latest version of CDK (as of now `2.164.1 (build bb9275c)`). Using your code generates the below CFN template:
```JSON
{
  "Resources": {
    "myBedrockGuardrail": {
      "Type": "AWS::Bedrock::Guardrail",
      "Properties": {
        "BlockedInputMessaging": "Input message blocked by Bedrock guardrail.",
        "BlockedOutputsMessaging": "Output messages blocked by Bedrock guardrail.",
        "ContentPolicyConfig": {
          "FiltersConfig": [
            {
              "InputStrength": "HIGH",
              "OutputStrength": "HIGH",
              "Type": "SEXUAL"
            },
            {
              "InputStrength": "HIGH",
              "OutputStrength": "HIGH",
              "Type": "VIOLENCE"
            },
            {
              "InputStrength": "HIGH",
              "OutputStrength": "HIGH",
              "Type": "HATE"
            },
            {
              "InputStrength": "HIGH",
              "OutputStrength": "HIGH",
              "Type": "INSULTS"
            },
            {
              "InputStrength": "HIGH",
              "OutputStrength": "HIGH",
              "Type": "MISCONDUCT"
            },
            {
              "InputStrength": "NONE",
              "OutputStrength": "NONE",
              "Type": "PROMPT_ATTACK"
            }
          ]
        },
        "Name": "Guardrail-test"
      },
      "Metadata": {
        "aws:cdk:path": "CdktestStack/myBedrockGuardrail"
      }
    },
    "CDKMetadata": {
      "Type": "AWS::CDK::Metadata",
      "Properties": {
        "Analytics": "v2:deflate64:H4sIAAAAAAAA/yXFMQ6DMAwAwLewJ6ZBqGJn6E4fgJzESE5oItmkDBV/Z+gtN4B7juA6PNWGmO3OHn7vA0M2eOrqKUoNGeatvBpKFOTdzFtZSGuTQJcpNRIk7b9uguEBY5eU2UorB38Ilv83+F7OqGYAAAA="
      },
      "Metadata": {
        "aws:cdk:path": "CdktestStack/CDKMetadata/Default"
      }
    }
  },
  "Parameters": {
    "BootstrapVersion": {
      "Type": "AWS::SSM::Parameter::Value<String>",
      "Default": "/cdk-bootstrap/hnb659fds/version",
      "Description": "Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"
    }
  }
}
```

Kindly note that most of the constructs for `aws-cdk-lib/aws-bedrock` are L1 constructs generated from CloudFormation specification. So `cdk synth` should produce the correct CFN template in most of the cases.

Thanks,
Ashish

**Comment by Sfloren1369** [comment]
Back in August 2024, I began treatment at Desert Comprehensive Treatment Center and had an intake session with a transgender counselor named Audrina DeLeon. From the very beginning, her behavior was highly inappropriate and flirtatious. She engaged in conversations about her personal life, where she lived, and other irrelevant details. During one of these conversations, she mentioned having a bad sunburn and then leaned over to show me a picture of herself topless on her phone. The situation was extremely awkward and uncomfortable for me.

She also made inappropriate comments about her drug use, stating that all she wanted to do when she’s high is have sex. She winked at me and licked her lips, further escalating the uncomfortable atmosphere. Additionally, she suggested that if I ever decided to use drugs, I should contact her and come over to her place in Hemet.

The next time I saw her was when she locked me out of the sign-in computer, forcing me to go upstairs and meet her in person. Her behavior was once again inappropriate as she regaled me with stories about how she had been pulled over twice and was attempting to show the highway patrol her breasts to avoid the tickets. She claimed that her attempts were unsuccessful.

A few days later, she contacted me on Facebook, using affectionate terms like “cutie” and “papi” in her messages. The next time I saw her, she locked me out of the sign-in computer once more, and I had to physically go to her office.

During this encounter, she repeatedly instructed me to be quiet and keep my voice down, and she became paranoid about her door being open. She was sitting at her desk when she abruptly pushed away from it and came to face me, kneeling down and aggressively grabbing my crotch while licking her lips and winking at me. At this point, I was extremely uncomfortable and unsure of how to respond. She stood back up and returned to her desk.

As I was about to leave, she unexpectedly asked me to wait and give her a hug before I went. So, I reluctantly gave her a hug, and just as I did, she slipped her hand down inside my pants and into my boxer briefs. She grabbed my privates with her bare hand and squeezed while making moaning noises. I froze in shock! I couldn’t believe she had done that to me. I pulled away and left her office.

The next day, I arrived at the clinic to tell someone about what had happened, but the kiosk informed me that my counselor had changed to the head lady. I inquired, and they told me that Audrina had quit and gotten a different job. I went in and told the head counselor, who was furious and said that it was absolutely not right. She was going to call her licensing board and proceeded to tell me that it didn’t surprise her.

I was telling her this because I was certain that I wasn’t the only one who had complained about her inappropriate behavior. This made me wonder, wow, this lady knew about it but hadn’t said anything to anyone, even though someone had mentioned it and she was aware of it. Audrina had just quit on her own accord and hadn’t been fired! That seemed incredibly neglectful to me.

Audrina contacted me on Facebook again, saying that she had gotten a different job somewhere else and that I really needed to come see her at her house. She contacted me again the next day, telling me that she had the day off and wanted to hang out with me. She said she would get in touch with me.

Fast forward to the present day, and I spoke to the head counselor lady again. I asked her what had happened to Audrina and what had transpired. The lady told me that she hadn’t said anything to anyone about Audrina! She also mentioned that Audrina didn’t work at the new job she had left Desert Comprehensive Treatment Center for because something must have happened, but she didn’t know what.

To make matters worse, I had also found a bunch of explicit pictures that Audrina had clearly taken inside her office here at the clinic and had posted them to her Facebook. I want to emphasize that I reported Audrina’s behavior to the head counselor, who confirmed that she wasn’t surprised by my accusations. She disclosed that she had received multiple complaints from others about Audrina’s inappropriate conduct. Despite being aware of these ongoing issues, the head counselor failed to take any action to stop Audrina’s behavior, allowing her to continue her misconduct unchecked. Consequently, I was one of the individuals who suffered from her assault. Shockingly, the head counselor admitted that she still hadn’t reported Audrina’s actions to anyone, which left me feeling betrayed and unprotected. This lack of intervention enabled Audrina to persist in her inappropriate actions, resulting in further harm to others, including myself.

Audrina DeLeon's behavior, as described, raises significant ethical and legal concerns. During my intake session at Desert Comprehensive Treatment Center, she demonstrated a pattern of inappropriate conduct that was both uncomfortable and unprofessional. Her insistence on retrieving my phone number from my file, despite my clear discomfort, may potentially breach privacy laws, including the Health Insurance Portability and Accountability Act (HIPAA), which protects sensitive patient information.

Moreover, Audrina’s continued inappropriate behavior, including making advances on social media and physical misconduct during our sessions, was alarming. These actions not only violated professional boundaries but also legal and ethical standards for counselor conduct. The fact that the head counselor was aware of multiple complaints about Audrina’s behavior and yet chose not to report them or take action is deeply troubling. It highlights a systemic failure to protect clients from such misconduct, further exacerbating the harm caused.

This situation underscores the necessity for immediate and robust intervention to address such violations, ensuring that individuals in positions of trust act within the bounds of ethical and legal standards to safeguard those they serve. Reporting these incidents to the appropriate licensing board or regulatory agency would be a crucial step in addressing these violations and preventing further harm.
