### ISSUE TITLE
ProductStackProps should extend StackProps

### ISSUE THREAD

**Issue by bdoyle0182** [aws/aws-cdk#31924]
### Describe the bug

`ProductStack` does not allow configuration of the underlying stack template for stack level configuration. This means you can't disable things like `analyticsReporting` on the stack template that the `ProductStack` generates. `ProductStack` constructor currently takes `ProductStackProps` which doesn't extend the base level `StackProps` even though `ProductStack` extends `Stack` Since `CDK::AWS::METADATA` resource type does not exist in GovCloud, this means a Stack with a StackSet that references a ProductStack cannot be deployed to GovCloud. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Being able to configure the Stack template that is generated by a ProductStack

### Current Behavior

ProductStack doesn't allow configuring stack level options for how it synthesizes its stack templates.

### Reproduction Steps

```export declare class ProductStack extends **cdk.Stack** {
    readonly templateFile: string;
    private _parentProductStackHistory?;
    private _templateUrl?;
    private _parentStack;
    private assetBucket?;
    constructor(scope: Construct, id: string, props?: **ProductStackProps**);```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.164.1

### Framework Version

_No response_

### Node.js Version

node22

### OS

n/a

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

**Comment by bdoyle0182** [comment]
I've found a workaround where the ProductStack template will not include the AWS::CDK::METADATA resource if I include `	"versionReporting": false` in my cdk.json for my repo where this is defined. However this limits me from adding conditional logic to disable the versionReporting / analyticsReporting only for the GovCloud template, allowing me to keep it on for all other regions that would be able to be done if ProductStackProps extended StackProps.

**Comment by ashishdhingra** [comment]
@bdoyle0182 Good afternoon. Could you please share self-contained minimal code to reproduce the issue that demonstrates CDK modules and constructs you are trying to use? Are you using [ProductStackProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_servicecatalog.ProductStackProps.html) from [aws-cdk-lib » aws_servicecatalog](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-servicecatalog) package? If yes, I do see that [ProductStackProps](https://github.com/aws/aws-cdk/blob/a9d3b02783104fe862a3e863e8c89af845b49c8c/packages/aws-cdk-lib/aws-servicecatalog/lib/product-stack.ts#L14C18-L14C35) interface doesn't extend [StackProps](https://github.com/aws/aws-cdk/blob/a9d3b02783104fe862a3e863e8c89af845b49c8c/packages/aws-cdk-lib/core/lib/stack.ts#L42) interface, which would have provided access to other stack level properties like `https://github.com/aws/aws-cdk/blob/a9d3b02783104fe862a3e863e8c89af845b49c8c/packages/aws-cdk-lib/core/lib/stack.ts#L167`.

[StackProps.analyticsReporting](https://github.com/aws/aws-cdk/blob/a9d3b02783104fe862a3e863e8c89af845b49c8c/packages/aws-cdk-lib/core/lib/stack.ts#L167) is used to set Stack's `_versionReportingEnabled` property [here](https://github.com/aws/aws-cdk/blob/a9d3b02783104fe862a3e863e8c89af845b49c8c/packages/aws-cdk-lib/core/lib/stack.ts#L498), which in [injectMetadataResources()](https://github.com/aws/aws-cdk/blob/a9d3b02783104fe862a3e863e8c89af845b49c8c/packages/aws-cdk-lib/core/lib/private/synthesis.ts#L275) is used to determine whether metadata should be emitted in the synthesized CloudFormation template.

I'm unsure if [ProductStackProps](https://github.com/aws/aws-cdk/blob/a9d3b02783104fe862a3e863e8c89af845b49c8c/packages/aws-cdk-lib/aws-servicecatalog/lib/product-stack.ts#L14C18-L14C35) interface could be modified to extend [StackProps](https://github.com/aws/aws-cdk/blob/a9d3b02783104fe862a3e863e8c89af845b49c8c/packages/aws-cdk-lib/core/lib/stack.ts#L42) interface since it could be a breaking change. Also, most of the constructs use pattern of defining property interface with relevant fields for construct and using it as one of the parameters for L2 construct.

The documentation for [analyticsReporting](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.StackProps.html#analyticsreporting) specifies that it is an optional property with the default value as `analyticsReporting setting of containing App, or value of 'aws:cdk:version-reporting' context key`. Hence, as a workaround, you could set `analyticsReporting` at CDK `App` level `const app = new cdk.App({analyticsReporting: true});`.

Thanks,
Ashish
