### ISSUE TITLE
aws-cdk-lib/custom-resources: error TS2503: Cannot find namespace 'AWSLambda'

### ISSUE THREAD

**Issue by mfatihaktas** [aws/aws-cdk#31981]
### Describe the bug

```
import { OnEventRequest } from 'aws-cdk-lib/custom-resources/lib/provider-framework/types';
```
causes

```
node_modules/aws-cdk-lib/custom-resources/lib/provider-framework/types.d.ts:27:41 - error TS2503: Cannot find namespace 'AWSLambda'.

27 export interface OnEventRequest extends AWSLambda.CloudFormationCustomResourceEventCommon {
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Import should work.

### Current Behavior

```
node_modules/aws-cdk-lib/custom-resources/lib/provider-framework/types.d.ts:27:41 - error TS2503: Cannot find namespace 'AWSLambda'.

27 export interface OnEventRequest extends AWSLambda.CloudFormationCustomResourceEventCommon {
```

### Reproduction Steps

```
import { OnEventRequest } from 'aws-cdk-lib/custom-resources/lib/provider-framework/types';
```

### CDK CLI Version

Latest

### Node.js Version

v18.20.2

### OS

MacOS Version 14.7

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@mfatihaktas Good morning. Thanks for opening the issue. Somehow, using the latest version 2.165.0` of `aws-cdk-lib`, the issue is not reproducible. Could you try using the latest version, ensuring that you run `npm install` to update the modules locally? If error still persists, please share minimal reproducible CDK project to reproduce the issue.

Thanks,
Ashish

**Comment by Armadillidiid** [comment]
Can this issue please be reopened @ashishdhingra? I just ran into the same issue today. Rather than importing as a module, I'm referencing the declaration file and it still throws the same error when I run `tsc --noEmit` to type check my project. I followed the [custom resource example](
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/framework-integ/test/custom-resources/test/provider-framework/integration-test-fixtures/s3-file-handler/index.ts) on this exact repo. 

```bash
> tsc --noEmit

node_modules/aws-cdk-lib/custom-resources/lib/provider-framework/types.d.ts:27:41 - error TS2503: Cannot find namespace 'AWSLambda'.

27 export interface OnEventRequest extends AWSLambda.CloudFormationCustomResourceEventCommon {
                                           ~~~~~~~~~


Found 1 error in node_modules/aws-cdk-lib/custom-resources/lib/provider-framework/types.d.ts:27
```

Here is a [reproducible example](https://github.com/Armadillidiid/wireguard-cdk/tree/debug/awslambda-namespace-not-found)

Lib version: `2.207.0`
