### ISSUE TITLE
core: cdk deploy wiping stack notification ARNs property

### ISSUE THREAD

**Issue by wilhen01** [aws/aws-cdk#32153]
### Describe the bug

A [change](https://github.com/aws/aws-cdk/pull/31107/files#diff-42aae8684cf5bf4a2d9423f8c019979b497494a591f8fbc17f3b003bc0bdb4e4R166) was introduced in [v2.160.0](https://github.com/aws/aws-cdk/releases/tag/v2.160.0) which appears to be wiping the `notificationARNs` property on a CloudFormation stack when `cdk deploy` is run against an existing stack with that property set. This represents a regression on previous behaviour. 

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.159.1

### Expected Behavior

`cdk deploy` does not modify the `notificationARNs` property on existing deployed stacks

### Current Behavior

`cdk deploy` wipes the `notificationARNs` property where it is set on existing deployed stacks

### Reproduction Steps

Deploy a stack. Modify the `notificationARNs` property outside of CDK. Then deploy a subsequent update via `cdk deploy`

### Additional Information/Context

We have an internal tooling platform which stacks can be registered with in order to provide deployment updates. In order to do this, the tool sets the `notificationARNs` property on the stack to listen to stack updates via SNS. Previously updating these stacks via `cdk deploy` did not conflict with that, but it does in recent versions.

### CDK CLI Version

v2.167.1

### Node.js Version

18

### OS

Mac OS

### Language

TypeScript

### Language Version

5.x

**Comment by pahud** [comment]
Hi

Looks like [the PR you mentioned](https://github.com/aws/aws-cdk/pull/31107/files#diff-42aae8684cf5bf4a2d9423f8c019979b497494a591f8fbc17f3b003bc0bdb4e4R166) essentially added a new `notificationArns` attribute which didn't exist prior to that PR.

Did you mean you actually had `notificationArns` attribute before 2.160.0 but it was wiped out since then?

**Comment by mrgrain** [comment]
If I read this correctly, the scenario is:

1. deploy stack with v2.159.1, do not set `notificationArns`, do not use `--notification-arns`
2. manually add Notification ARNs via the CFN console
3. deploy stack with v2.160.0, still do not set `notificationArns`, still do not use `--notification-arns`
4. see how the manually added Notification ARNs are removed

Or in other words, with v2.159.1 and before you could "tell" the CDK to just not care about Notification ARNs at all.
But since v2.160.0, the CDK got greedy and wants to always own Notification ARNs even if they are empty.

---

If this is confirmed, the code bug is probably the difference between not setting a parameter (old) and passing an empty array to the parameter (new).

**Comment by wilhen01** [comment]
@mrgrain's summary is accurate @pahud  - the stacks we're experiencing this problem with don't specify noticationArns at all. Basically the flow is:

- Deploy stack via `cdk deploy` with no specification of `NotificationARNs`
- Register stack with my organisation's internal tooling - this populates `NotificationARNs` in order to listen to stack updates
- Deploy updates to stack via `cdk deploy`, again with no specification of `NotificationARNs`

prior to 2.160.0, the notification ARNs added by the internal tooling platform would be maintained across subsequent stack updates via `cdk deploy`. From 2.160.0 onwards, that is no longer the case.
