### ISSUE TITLE
aws-sdk: Increase in TimeoutErrors in Amplify hotswap builds

### ISSUE THREAD

**Issue by ShadowCat567** [aws/aws-cdk#32219]
### Describe the bug

Starting from 11/14, we have started seeing `TimeoutError: Resource is not in the expected state due to waiter status: TIMEOUT`, with a frequency we have never seen before. This error was added [here](https://github.com/aws/aws-cdk/blob/8746e44c0ac57035308cc401f70012f735b047b5/packages/aws-cdk/lib/api/hotswap-deployments.ts#L428) in version 2.167.0.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.166.0

### Expected Behavior

Very few to none `TimeoutError: Resource is not in the expected state due to waiter status: TIMEOUT` appearing to our customers. 

### Current Behavior

`TimeoutError: Resource is not in the expected state due to waiter status: TIMEOUT` has become one of the most common error messages our customers are receiving.

### Reproduction Steps

1. Setup amplify (Gen2) https://docs.amplify.aws/react/start/manual-installation/
2. Setup a function https://docs.amplify.aws/react/build-a-backend/functions/set-up-function/
3. Make a change in lambda code

### Possible Solution

Roll back this PR: https://github.com/aws/aws-cdk/pull/31702/ 

### CDK CLI Version

2.167.0

### Node.js Version

>=Node18

### OS

Linux/Mac/Windows

### Language

TypeScript

**Comment by pahud** [comment]
Can't reproduce this using 2.168.0. The lambda func hot swapping looks good to me. Please provide more reproducible details as well as any screenshots if possible. Thank you.

**Comment by pahud** [comment]
Also, our latest version is 2.168.0 now. Can you verify with this version?

**Comment by ShadowCat567** [comment]
I have edited the description to provide some additional info about repro instructions, but this issue is very fickle and is hard to reproduce consistently. It does appear in the most recent cdk version.

**Comment by pahud** [comment]
Though I can't reproduce it but this is the potential root cause:


The timeout occurs because AWS Lambda requires the function to be in an `Active` state and have `LastUpdateStatus=Successful` before it can be updated again. CDK waits for this state before proceeding, but has different wait times depending on the Lambda configuration:

https://github.com/aws/aws-cdk/blob/27babe66d750454a82bbcca9bd4b584e88e2ace8/packages/aws-cdk/lib/api/hotswap/lambda-functions.ts#L333-L336

AWS SDK v3 has a different waiter implementation, timeout handling and delay strategy that handle requests differently from v2. This could affect how timeouts are processed.

I guess we should either increase the timeout somehow from [here](https://github.com/aws/aws-cdk/blob/27babe66d750454a82bbcca9bd4b584e88e2ace8/packages/aws-cdk/lib/api/hotswap/lambda-functions.ts#L333-L336) or add status checking like

```ts
const response = await lambda.getFunctionConfiguration({
  FunctionName: functionName
});
if (response.State === 'Active' && response.LastUpdateStatus === 'Successful') {
  // Proceed with hotswap
}
```

**Comment by otaviomacedo** [comment]
Just to be clear, this message was introduced in version 2.167.0. Previously, the same error would result in a generic error message. So, the fact that we are now seeing it in the wild, by itself, doesn't imply that there is anything wrong there. Indeed, it would be surprising if this message didn't start appearing.

To establish that there is an issue, we need to find a case in which this error message is shown in version 2.167.0 or later, and no error happens at all in earlier versions. Given that it's hard to reproduce it consistently, we would need to run each version a few times and compare the error rates.

**Comment by sobolk** [comment]
It has consistently failed in 5/6 runs.
From E2E test logs, It seems this is affected by:
1. Growing number of resources being hot-swapped
2. Hotswapps are executed couple of times in a row (they may trigger throttling and new code might be less tolerant to that then before.).
