### ISSUE TITLE
aws-stepfunctions-tasks: workerType not dynamic from payload

### ISSUE THREAD

**Issue by ElearG** [aws/aws-cdk#32359]
### Describe the bug

I want to implement a state machine that invokes a glue job synchronously and that at the time of invoking it, the type of worker and the number of workers are passed as parameters from the input (payload). It is verified that the implementation can be achieved at the console level, however, if I want to deploy it through CDK, it is not possible, because the value of "WorkerType" is a class of the WorkerType type and does not allow it to be placed dynamically from the input. A capture of the implementation in the console and the attempt at implementation in CDK are attached. 

- Only can set the workers' number dynamic from payload

![CDK Repository Implementation](https://github.com/user-attachments/assets/bbc7df44-048b-468c-ae1c-da7614891db0)
![image](https://github.com/user-attachments/assets/dc1f3763-0fef-4e7f-8371-82ef63956aab)

- To make dynamic the workerType the workerType should look something like this:

![image](https://github.com/user-attachments/assets/9f458310-1ade-41d4-a6f3-51e474525924)

**- But here the error:**

![image](https://github.com/user-attachments/assets/552d3d78-fdc7-4136-82c4-c1fbb5445aa2)

- When implenet by console looks likes :

![image](https://github.com/user-attachments/assets/177e2ee7-8202-4a8b-a0a1-1db73131e531)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Define in CDK the workerType to be dynamic from the payload input in the state machine, in other words, achieve the image but doing it with cdk.
I need that the argument "worker_type" not only accept a WorkerType Class that is a enum and only can put the define workers type insted of i need that also accept strings to pass "_sfn.JsonPath.string_at('$.glue_jobs_configs.executor_type')"in that argument

![image](https://github.com/user-attachments/assets/177e2ee7-8202-4a8b-a0a1-1db73131e531)

### Current Behavior

Now, I can't put the workers type dynamic from payload input in the state machine because it only accept a class workerType that its a enum and only accepts the define workers. 
If i pass a string that references the payload input it shows an error.

![image](https://github.com/user-attachments/assets/2155b2c4-3a5c-4c15-b7c7-21e514e9931f)
![image](https://github.com/user-attachments/assets/3caad19a-33b4-4de3-931b-4044048f6104)

### Reproduction Steps

In the step function task: GlueStartJobRun
Put the argument worker_type the value _sfn.JsonPath.string_at('$.glue_jobs_configs.executor_type')
`worker_type= _sfn.JsonPath.string_at('$.glue_jobs_configs.executor_type')`
![image](https://github.com/user-attachments/assets/b6fb1185-6b74-40a7-bc95-858906984033)

### Possible Solution

The argument worker_type accept also strings and dont validate that its only a class WorkerType

### CDK CLI Version

2.171.1

### Node.js Version

20.11.1

### OS

Windows 11

### Language

Python

### Language Version

3.11

**Comment by ashishdhingra** [comment]
The code comment for [WorkerType](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/glue/start-job-run.ts#L174) enum from [aws-cdk-lib.aws_stepfunctions_tasks.WorkerConfigurationProperty](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.WorkerConfigurationProperty.html#workertype) states that `If you need to use a WorkerType that doesn't exist as a static member, you can instantiate a `WorkerType` object, e.g: `WorkerType.of('other type')`.`. However, this is incorrect since `WorkerType` is a enum, not a class. Perhaps this is an overlook or a copy/paste error with excerpt taken from `@aws-cdk/aws-glue-alpha` > [WorkerType](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/%40aws-cdk/aws-glue-alpha/lib/job.ts#L20C14-L20C25) class.

Changing the type of property `workerType` in [WorkerConfigurationProperty](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/glue/start-job-run.ts#L68) interface would be a breaking change. This property is used [here](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/glue/start-job-run.ts#L127) in call to `sfn.FieldUtils.renderObject()`, which renders `Parameters` definition which is outputted in `DefinitionString` for `AWS::StepFunctions::StateMachine` resource in generated CFN template as something like `- :states:::glue:startJobRun.sync","Parameters":{"JobName":"Test","WorkerType":"G.025X","NumberOfWorkers":3}}}}`.

Unsure if there is a way to use escape hatch here. Perhaps introducing another property named `workerTypeV2` which uses newly defined `Worker Type` class and deprecating old property `workerType` would be a feasible solution.

Needs review with the team.

**Comment by ElearG** [comment]
Thanks for the reply. So I understand that a change must be made at the CDK level to make the workerType dynamic, right?

**Is there another way to perform this operation?**

I tried with the CallAwsService , Glue service, however I have problems with the integration_pattern, it does not accept synchronously (_sfn.IntegrationPattern.RUN_JOB)

Thanks for the support!

> The code comment for [WorkerType](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/glue/start-job-run.ts#L174) enum from [aws-cdk-lib.aws_stepfunctions_tasks.WorkerConfigurationProperty](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.WorkerConfigurationProperty.html#workertype) states that `If you need to use a WorkerType that doesn't exist as a static member, you can instantiate a `WorkerType`object, e.g:`WorkerType.of('other type')`.`. However, this is incorrect since `WorkerType` is a enum, not a class. This might not be an overlook since per [AWS Glue > Job runs](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-jobs-runs.html#aws-glue-api-jobs-runs-StartJobRun), `WorkerType` accepts limited set of values. It might be a copy/paste error with excerpt taken from `@aws-cdk/aws-glue-alpha` > [WorkerType](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/%40aws-cdk/aws-glue-alpha/lib/job.ts#L20C14-L20C25) class, which might be defined to support dynamic values (it's an experimental module).
> 
> Changing the type of property `workerType` in [WorkerConfigurationProperty](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/glue/start-job-run.ts#L68) interface would be a breaking change and unsure if this should be done. Also, this property is used [here](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/glue/start-job-run.ts#L127) in call to `sfn.FieldUtils.renderObject()`, which renders `Parameters` definition which is outputted in `DefinitionString` for `AWS::StepFunctions::StateMachine` resource in generated CFN template as something like `- :states:::glue:startJobRun.sync","Parameters":{"JobName":"Test","WorkerType":"G.025X","NumberOfWorkers":3}}}}`. There might not be a way to use escape hatch here. Perhaps introducing another property named `workerTypeV2` which uses newly defined `Worker Type` class and deprecating old property `workerType` would be a feasible solution.
> 
> Needs review with the team.

**Comment by GavinZZ** [comment]
Hello, thanks for creating this issue. I want to double check with you that you are able to workaround the `NumberOfWorkers` field and it's only the `WorkerType` property that doesn't work. If you have something like this class where you can use `WorkerType.of(...)`, would that help solve your issue?

**Comment by ElearG** [comment]
Hello, thanks, yeah the problem is only with WorkerType it's a enum not a class so "`WorkerType.of`" doesn't work. In the other hand `NumberOfWorkers`  it's  an integer type and its accept `JsonPath.number_at ` normally so it works correct. 
I think that if I can have a WorkerType that can accept "JsonPath.StringAt" it could solve my problem.
Thanks!
