### ISSUE TITLE
CfnMaintenanceWindowTarget is missing

### ISSUE THREAD

**Issue by ScOut3R** [aws/aws-cdk#3265]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
The aws-ssm package does not include the CfnMaintenanceWindowTarget generated class.

* **What is the expected behavior (or behavior of feature suggested)?**
The aws-ssm package should include the CfnMaintenanceWindowTarget generated class to enable the creation of AWS::SSM::MaintenanceWindowTarget resources.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Without a CfnMaintenanceWindowTarget it is not possible to define tag based CfnMaintenanceWindowTask targets.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.2
  - Module Version: 0.36.2
  - OS: Linux
  - Language: TypeScript

**Comment by ScOut3R** [comment]
Looks like it is missing from the official specification at https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

**Comment by NGL321** [comment]
Hey @ScOut3R , thank you for bringing this to our attention. It appears that it is missing from generation and so I am going to reach out to the Cloudformation team. In the interim, I have marked this as a feature-request, since it is currently not a supported feature.
 
For reference moving forward, [here is the cfn doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindowtarget.html).

I will update this issue as they get back to me.

**Comment by ScOut3R** [comment]
FYI I raised an AWS support request via a Business subscription in the hopes of expediting a resolution to this issue.

**Comment by ScOut3R** [comment]
AWS Support confirmed that for this issue the published CFN specification is wrong in us-east-1 and ap-northeast-1. All the other regions are correct, but again, only for this specific issue.

**Comment by ScOut3R** [comment]
#3710 fixed this issue
