### ISSUE TITLE
CustomOriginConfig fills in with values not specified

### ISSUE THREAD

**Issue by McDoit** [aws/aws-cdk#3281]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Creating a CloudFrontWebDistribution with a SourceConfiguration with the following CustomOriginConfig sets values for properties not specified

````
new CustomOriginConfig
{
    DomainName = "web.example.com",
    HttpPort = 80,
    OriginProtocolPolicy = OriginProtocolPolicy.HTTP_ONLY,
}
````
becomes
````
"CustomOriginConfig": {
  "HTTPPort": 80,
  "HTTPSPort": 443,
  "OriginKeepaliveTimeout": 5,
  "OriginProtocolPolicy": "http-only",
  "OriginReadTimeout": 30,
  "OriginSSLProtocols": []
}
````
in the synthed output

And i dont find any way to override that without overiding the entire `Origins` property

* **What is the expected behavior (or behavior of feature suggested)?**
A output more like this:

````
"CustomOriginConfig": {
  "HTTPPort": 80,
  "OriginProtocolPolicy": "http-only"
}
````

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.39
  - Module Version: 0.39
  - OS: [Windows 10]
  - Language: [C#]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by RomainMuller** [comment]
The defaults are applied at the Javascript layer. What's the reason why you want the defaults to NOT be applied here?

**Comment by eladb** [comment]
The synthesized outputs are functionally equivalent since the default values of the construct are aligned with the defaults of the service/CloudFormation:

- `OriginKeepaliveTimeout` default is 5s ([ref]https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-customoriginconfig.html#cfn-cloudfront-distribution-customoriginconfig-originkeepalivetimeout)
- `OriginReadTimeout` default is 30s (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-customoriginconfig.html#cfn-cloudfront-distribution-customoriginconfig-originreadtimeout)
- `OriginSSLProtocols` empty list is equivalent to not specifying the value
- `HTTPSPort` is ignored since `http-only` is set.

Resolving for now.
