### ISSUE TITLE
Use classic load balancer (ELB) as a Route53 target

### ISSUE THREAD

**Issue by SanderKnape** [aws/aws-cdk#3306]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [X] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the expected behavior (or behavior of feature suggested)?**

The Classic load balancer (ELB) is currently not supported as a Route53 Target.

* **What is the motivation / use case for changing the behavior or adding this feature?**

I'm using the Kubernetes Nginx Ingress, which currently only supports the use of the classic load balancer.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all]
  - Language: [all ]

**Comment by NGL321** [comment]
Hi @SanderKnape,

Thank you for reaching out! I think what you are looking for this:
https://github.com/aws/aws-cdk/blob/d89592e1e3ff52a4c46fe9fc597787feb3c1f566/packages/%40aws-cdk/aws-route53-targets/README.md#L28

If this is the case, I will close out the issue. Otherwise let me know, and I will keep it open as a feature request!

**Comment by SanderKnape** [comment]
Hey @NGL321 . That target is for v2 load balancers (ALB, NLB). It doesn't work with the classic load balancers (ELB).

**Comment by NGL321** [comment]
Ah, I see. The problem is that ELBv2 is supported, but not base ELB.

Marking as a feature-request. We will look into it as soon as we are able!
