### ISSUE TITLE
CodePipeline LambdaInvokeAction never stops even though the underline lambda ends immediately 

### ISSUE THREAD

**Issue by byabrik** [aws/aws-cdk#3332]
I use CDK CLI version 1.0.0 with aws-cdk version 1.0.0 on Windows 10 with TypeScript.

* **What is the current behavior?**
Creating a codepipeline with 2 stages
1. source from codecommit 
2. lambda 

CodePipeline Lambda action stage never stops.
If I try running the underline lambda function directly, it stops immediately.

* **What is the expected behavior (or behavior of feature suggested)?**
CodePipeline Lambda action stage should stop.

```

        const pipelineName = `${props.service.serviceName}_${props.sourceTrigger}`;
        this.pipeline = new Pipeline(this, pipelineName, {
            pipelineName,
            restartExecutionOnUpdate : true
        });

        // Source 
        const sourceOutput = new codepipeline.Artifact();
        const repo = codecommit.Repository.fromRepositoryName(this, "Repo", props.service.repo.name);
        const sourceAction = new codepipeline_actions.CodeCommitSourceAction({
            actionName: 'CodeCommit',
            repository: repo,
            branch: props.service.repo.branch,
            output: sourceOutput
        });

        this.pipeline.addStage({
            stageName: 'Source',
            actions: [sourceAction]
        });

        const fn = new lambda.Function(this, 'LambdaFun', {
            code: new lambda.InlineCode(`
              exports.handler = function () {
                console.log("Hello, world!");
              };
            `),
            handler: 'index.handler',
            runtime: lambda.Runtime.NODEJS_8_10,
          });
        
        const lambdaAction  = new codepipeline_actions.LambdaInvokeAction({
            lambda:  fn,
            actionName: 'IncrementBuildNumber',
            userParameters: {"ssmParamProjectBuildPath": '/CodeBuild/build-versions/nextGen-api-authProvider/test-build'}
        });

        this.pipeline.addStage({
            stageName: 'IncrementBuildNumber',
            actions: [lambdaAction]
        });
```

**Comment by byabrik** [comment]
The Action stopped with an error:

> The AWS Lambda function AuthProviderStack-LambdaFun98622869-8FFHL6MMJZR0 failed to return a result. Check the function to verify that it has permission to call the PutJobSuccessResult action and that it made a call to PutJobSuccessResult.

**Comment by skinny85** [comment]
@byabrik thanks for opening the issue. As the error message says, you need to call the CodePipeline's `PutJobSuccessResult ` or `PutJobFailureResult` API from your Lambda. Something like this:


```js
code: new lambda.InlineCode(`
  exports.handler = function (event, context) {
    var AWS = require('aws-sdk');
    var codepipeline = new AWS.CodePipeline();
    var jobId = event['CodePipeline.job'].id;
    codepipeline.putJobSuccessResult({ jobId });
    context.succeed('Hello world!');
  }`),
// ...
```

**Comment by byabrik** [comment]
Thank you @skinny85, I'll try that.
I used serverless before to work with lambdas, and I guess it takes care of that automatically.

**Comment by byabrik** [comment]
@skinny85, it works with the addition of the PutJobSuccessResult, but it makes the lambda not reusable. 
What If I have a lambda that could be run in the end of the pipeline or in the middle? In that case we would have to pass some kind of parameter into the lambda to understand if I need to call PutJobSuccessResult or not. 
Would be nice if cdk would just do something automatically. For example grab the result of the last job in the pipeline and submit PutJobSuccessResult/PutJobFailureResult on behalf of the user.

**Comment by skinny85** [comment]
Hey @byabrik ,

I think there's been a little misunderstanding.

The example I've shown is just a trivial Lambda that doesn't actually do anything, just immediately succeeds the Action. Of course, in reality, the purpose of putting a Lambda in your pipeline is for it to do something. Now, depending whether that "something" was a success or not, you would call either the `putJobSuccessResult` or the `putJobFailureResult` API in your Lambda, which either succeeds or fails the execution of the Action, respectively. You always have to call one of those 2 APIs -- otherwise, the Action will never stop executing, and finally time out after an hour.

This "something" is not a thing the CDK can do for you - it's specific to your use case, whatever it is that you need a Lambda for in the first place. The CDK is for infrastructure, your custom business logic is still up to you to write :).

As for customizing the behavior of your Lambda - you can use input & output artifacts for that. If you need further customizations, there is a field called [userParameters](https://github.com/aws/aws-cdk/blob/63455f61dd687ec131d307e1875938acdba4fd08/packages/%40aws-cdk/aws-codepipeline-actions/lib/lambda/invoke-action.ts#L42) that you can pass when creating the Action, and then read as a field of `event` in your Lambda. This way you can re-use the same Lambda in multiple parts of the Pipeline, and customize it at every spot it's used.

Hope this helps.

Thanks,
Adam
