### ISSUE TITLE
certificatemanager: Route 53 records not cleaned up after removing DNS Validated Certificate

### ISSUE THREAD

**Issue by rubenfonseca** [aws/aws-cdk#3333]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

Following this code:

```
const zone = new route53.HostedZone(this, 'zone', { zoneName: 'bar.com' })

new certificateManager.DnsValidatedCertificate(this, 'cert', {
  hostedZone: zone,
  domainName: `foo.bar.com`,
})
```

An ACM certificate is created and validated via DNS. However, when you destroy the stack, it fails with the following error `(Service: AmazonRoute53; Status Code: 400; Error Code : HostedZoneNotEmpty ...`

* **What is the expected behavior (or behavior of feature suggested)?**

The stack was destroyed cleanly.

* **What is the motivation / use case for changing the behavior or adding this feature?**

A stack created by CDK should naturally be destroyable. Checking the lambda resource that handles the validation, I can see that when the resource is destroyed, no attempt is made to clean up the route53 record. This explains why it fails.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all]
  - Language: [TypeScript ]

**Comment by jimfum** [comment]
What's the state of this issue now? In my case, the cdk destroy command finishes without an error but still the certificate isn't removed.

**Comment by njlynch** [comment]
@jimfum - What version of the CDK are you using? Did you have other resources associated/attached to the certificate at the time of deletion? Do you have the logs from the Lambda job showing an errors? For example, the Lambda job will [throw an error](https://github.com/netroy/aws-cdk/blob/master/packages/@aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L183-L198) if the certificate still is in use and can't be deleted.

**Comment by jimfum** [comment]
Sorry @njlynch, it's a while back and I stopped looking into that now focusing on the incoming Certificate construct. The version used was 1.38 but as I was testing various things I don't remember if the certificate was attached to anything (if it was, it was only in the same CDK script).

**Comment by njlynch** [comment]
Just circling back around - this is definitely still valid. There is no code to clean up the Route 53 records with this custom resource.

That being said, I would encourage anyone using the `DnsValidatedCertificate` to switch over to using the `Certificate` with the new built-in (CloudFormation-based) DNS validation. This has been committed and will go out with the next release. 

This bug may still be fixed for those who must -- for now -- use the `DnsValidatedCertificate` because they need to request certificates cross-region. I think that the work done in #6309 is still valid, although I would recommend adding a flag to trigger clean-up or not, given the concerns about multiple certificates using the same validation record.
