### ISSUE TITLE
Attaching Managed Policy to Role failing

### ISSUE THREAD

**Issue by nicksbrandon** [aws/aws-cdk#3379]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

### Attaching a managed policy to a Role.

In 1.1.0 there is a method `fromAwsManagedPolicyName`.  It takes a single parameter: the managed policy name.  In previous versions there was a method `attachManagedPolicy` which took the ARN of the managed policy.  

in 1.1.0:

```
// attach managed policy to role
const managedPolicy = ManagedPolicy.fromAwsManagedPolicyName("MyManagedPolicy")
buildRole.addManagedPolicy(managedPolicy);
```

I get the following error:

```
Policy arn:aws:iam::aws:policy/MyManagedPolicy does not exist or is not attachable.
(Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 7c2ebbde-ac71-11e9-89dd-879d24923f1f)
```

I can see that the arn for the managed policy is constructed in this method - and is missing the account reference.

In the CDK code:

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-iam/lib/managed-policy.ts

```
  public static fromAwsManagedPolicyName(managedPolicyName: string): IManagedPolicy {
    class AwsManagedPolicy implements IManagedPolicy {
      public readonly managedPolicyArn = Lazy.stringValue({
        produce(ctx: IResolveContext) {
          return Stack.of(ctx.scope).formatArn({
            service: "iam",
            region: "", // no region for managed policy
            account: "aws", // the account for a managed policy is 'aws'
            resource: "policy",
            resourceName: managedPolicyName
          });
        }
      });
    }
    return new AwsManagedPolicy();
  }
```

I can see from the error message and reading the CDK code that the `account` in the arn is set to `aws` - not the correct account number:

* **What is the expected behavior (or behavior of feature suggested)?**

Using the example above:

`managedPolicyArn` should be set to 

`arn:aws:iam::12345678987654:policy/MyManagedPolicy`

not

`arn:aws:iam::aws:policy/MyManagedPolicy`   (current behaviour)

In this way the Managed Policy will be correctly identified.

* **What is the motivation / use case for changing the behavior or adding this feature?**

To allow managed policies to be assigned to a role.  This is a feature we have previously used to manage our codebuild projects.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0
  - Module Version: 1.1.0
  - OS: Windows 10 , Ubuntu
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by RomainMuller** [comment]
It appears you are tying to use the method with a user-managed policy. The [documentation](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-iam/managedpolicy.html#aws_iam_ManagedPolicy) (and method name) explains that currently, this only supports **AWS-managed** policies, which have ARNs that do not include account IDs.

**Comment by RomainMuller** [comment]
In order to get your code to work "right now", you can use [Escape Hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to override the property.

**Comment by nicksbrandon** [comment]
Many thanks

**Comment by fimbulvetr** [comment]
I don't understand why there isn't a fromArn static method? Are we just looking for a PR, or is this some design decision? Customer-created Managed policies aren't that rare IMO; because CDK is lacking this, we actually have to do more work than if we just stuck with a Cfn construct.

AWS labels both AWS Managed policies and Customer Managed polices as "Managed Policies" in most forms of documentation and operations. If CDK must only allow *blessed* AWS Managed policies, this class should perhaps be named "AWSManagedPolicy"?

**Comment by enocom** [comment]
Support for customer managed policies looks like it's [available in v1.4.0](https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md#features) (under iam).

**Comment by SomayaB** [comment]
Closing since v1.4.0 seems to be addressing this. Feel free to reopen if that's not the case.

**Comment by michael-barker** [comment]
I had a similar issue but mine was caused by not adding the `service-role/` prefix.

**Comment by mattiamazzari** [comment]
I confirm that the problem is the  `service-role` prefix, but not every policy has it. For instance in "IAM" > "Policies", if you search and click on:

- "AmazonEC2RoleforSSM", you can see that its ARN is `arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM`
- "AmazonSSMManagedInstanceCore", you can see that its arn is `arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore`


So in Terraform I had:

`resource "aws_iam_policy_attachment" "ec2_attach_1" {
  name = "ec2-iam-attachment"
  roles = [ aws_iam_role.ec2_iam_role.id ]
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_policy_attachment" "ec2_attach_2" {
  name = "ec2-iam-attachment"
  roles = [ aws_iam_role.ec2_iam_role.id ]
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
}`
