### ISSUE TITLE
CodeBuild project does not update ImagePullCredentialsRole from SERVICE_ROLE to CODEBUILD

### ISSUE THREAD

**Issue by strax** [aws/aws-cdk#3429]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
When a CodeBuild project is synthesized to CloudFormation, it will include the `ImagePullCredentialsType` if and only if the used build image has `ImagePullPrincipalType` of `SERVICE_ROLE`. In other words, if the principal is `CODEBUILD` the property is not present.

  This caused an issue for us with a deployed CloudFormation stack where a deployed project had its `ImagePullCredentialsType` set to `SERVICE_ROLE`, and when we changed its build image to one that requires the `CODEBUILD` principal the property would get entirely removed from the synthesized template. As a consequence, updating the stack failed to change the `ImagePullCredentialsType` property from `SERVICE_ROLE` to `CODEBUILD`.

* **What is the expected behavior (or behavior of feature suggested)?**
Using a build image with the image pull principal type of `CODEBUILD` will lead to the project's `Environment.ImagePullCredentialsType` property to be present and have the value `CODEBUILD`. This is consistent with the current behavior of using the `SERVICE_ROLE` principal.

* **Please tell us about your environment:**
  - CDK CLI Version: 1.1.0
  - Module Version: 1.1.0
  - OS: OSX Mojave
  - Language: TypeScript

* **Other information**
Looking at the source of `@aws-cdk/aws-codebuild`, it seems that the issue is caused by https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-codebuild/lib/project.ts#L801 setting the image pull credentials type to `undefined` if the build image's pull principal is `CODEBUILD`, and set to `SERVICE_ROLE` otherwise.

**Comment by skinny85** [comment]
Hey @strax ,

thanks for opening the issue, but I don't really understand the problem here.

If `ImagePullCredentialsType` is not present, that means the default takes over, and the default is `CODEBUILD`. So not specifying it and specifying `CODEBUILD` are exactly the same.

What am I missing here?

Thanks,
Adam

**Comment by strax** [comment]
@skinny85 So the sequence of events is the following:

1. A CloudFormation stack is deployed, which contains a declaration for `AWS::CodeBuild::Project` with the property `Environment.ImagePullCredentialsType` set to `SERVICE_ROLE`.
2. A new template is synthesized that does not contain the aforementioned property at all.
3. The stack deployed in (1) is updated with the template synthesized in (2), and since the property is missing the underlying resource is not actually updated to its default value.

This seems like it might be an upstream issue in CloudFormation, but I was able to work around it by manually overriding the `Environment.ImagePullCredentialsType` property for the underlying `CfnProject` construct to `CODEBUILD`. This suggests the issue could be fixed by always having the property present instead of relying on the default value, but if you think this should be fixed upstream instead I can open an AWS support case instead.

**Comment by skinny85** [comment]
Hmm. This is very interesting.

This pattern ("if you give us something, we'll fill it, but if not, we'll just leave it as `undefined` so that the default takes over") is used quite pervasively in the CDK (an example off the top of my head: [`s3.Bucket.versioninConfiguration`](https://github.com/aws/aws-cdk/blob/6c0bf4ac1b21116d94e26d740a0302f92207b3b1/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L938)). 

So, this raises an interesting question: is the behavior you observed (the actual resource not being updated after changing the value in the template to `undefined` from something different than `undefined`) a general CloudFormation issue, or something specific to CodeBuild?

If it's the former, then we have a big problem on our hands, much bigger than just `ImagePullCredentialsRole`. If it's the latter, then probably opening an issue to CodeBuild about their CloudFormation support (it's also possible the bug is in the service itself, rather than in CloudFormation) seems like the way to go.

Let me test that with the S3 Bucket, and I'll report back.

**Comment by skinny85** [comment]
Just tried it with the Bucket, and it works exactly like expected (setting the property to `undefined` changes it to the default).

I think you need to contact CodeBuild about this @strax .

**Comment by strax** [comment]
Will do – closing this as it doesn't seem to be directly CDK-related.
