### ISSUE TITLE
Guidance on provisioning services that don't have CloudFormation support

### ISSUE THREAD

**Issue by j--wong** [aws/aws-cdk#3460]
Hi, 

Is there an official guidance on provisioning resources such as organization service control policies (which does not have CFN support) within a CDK app.

I am thinking of using AWS SDK organization API to create/attach SCPs, but doesn't feel "right" about having dependency on aws-sdk (even though I know that cdk itself has dependency on sdk).  Would custom resource be a better approach?

Any thoughts?

Thanks,
Josh

**Comment by NGL321** [comment]
Hi Josh,

There is no official recommendation for this. As you mentioned, it is not supported in Cloudformation and we do not have any immediate plans of implementing AWS Organizations.
That said, you could absolutely use a custom resource to accomplish this, however decoupling entirely from the SDK seems unlikely (there is no problem using the SDK  for this).

As far as official support, if you would like to track progress, issue #2877 addresses this.

For future reference, we try to redirect more general guidance questions like this to our Stack Overflow, as is indicated in the issue template. This is so that we can keep the issue queue dedicated to bug reports and feature-requests as much as possible.
Please do continue to post here if you see something missing that you would like to see, or you happen across a bug!

Thanks!
