### ISSUE TITLE
Support for mustache templates in names

### ISSUE THREAD

**Issue by rbs392** [aws/aws-cdk#3489]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [*] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Validation errors are thrown when the name contains Mustache templates 
Ex forecast-pipeline-{{ENV}}

* **What is the expected behavior (or behavior of feature suggested)?**
No errors are thrown when mustache templates are provided in name

* **What is the motivation / use case for changing the behavior or adding this feature?**
Allow the cloudformation stack generated to have mustache template variable that can be updated on deployment

* **Please tell us about your environment:**

  - CDK CLI Version: 0.36.0
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

jsii.errors.JSIIError: Stack name must match the regular expression: /^[A-Za-z][A-Za-z0-9-]*$/, got 'forecast-pipeline-{{ENVIRONMENT}}'

**Comment by rbs392** [comment]
@eladb Can you please let me know if this is possible?

**Comment by eladb** [comment]
Hi, thanks for brining this up. It’s an interesting use case, but I am afraid it’s out of scope for a framework like the CDK. The main goal of the CDK is to allow you to use programming language primitives to define logic, APIs and models. We think of the output of CDK apps as “assembly language” and intentionally not optimize for neither aesthetic, humans readability or post processing of this “cloud executable” (formally called “cloud assembly”).

I’ll close this for now since I really don’t see this as something we will likely want to design for in the near future. Happy to help and consult on how to leverage “native CDK” for your use case. Maybe you can get rid of some downstream tools and extra processes?

**Comment by rbs392** [comment]
Cool, thanks for the response!!
