### ISSUE TITLE
cdk.json seems to ignore various options

### ISSUE THREAD

**Issue by fchorney** [aws/aws-cdk#3573]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
When I add various settings options to the `cdk.json` file, they don't seem to be applied when running `cdk synth`. Specifically `pathMetadata` and `assetMetadata`

To reproduce: make some very basic cdk app (I am currently using python). 
cdk.json
```json
{
    "app": "python3 app.py",
    "pathMetadata": false,
    "assetMetadata": false,
    "versionReporting": false
}
```

When I run `cdk -v synth` I get the following:

```
cdk.json: {
  "app": "python3 app.py",
  "pathMetadata": false,
  "assetMetadata": false,
  "versionReporting": false,
  "staging": false
}
merged settings: {
  versionReporting: false,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'python3 app.py',
  assetMetadata: true,
  staging: true,
  context: {},
  tags: []
}
```

Clearly you can see the `pathMetadata` and `assetMetadata` in the `cdk.json` but it doesn't merge into the settings

* **What is the expected behavior (or behavior of feature suggested)?**
That the `cdk.json` settings be merged into the settings

* **What is the motivation / use case for changing the behavior or adding this feature?**
This is how it should work already

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0
  - OS: macOS Mojave
  - Language: Python

**Comment by eladb** [comment]
Yes, we currently don't have support for all switches in `cdk.json` and we should!

**Comment by mithun** [comment]
The [toolkit reference](https://docs.aws.amazon.com/cdk/latest/guide/cli.html#cli-ref) as well as `cdk --help` says:

>If one of cdk.json or ~/.cdk.json exists, options specified there will be used as defaults. Settings in cdk.json take precedence.

This message is misleading since not all CLI options have a `cdk.json` equivalent. The CLI ux can use improvements in allowing various options to be stored in configuration files (for e.g., [this is how SAM does it](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html). This will help ensure that each builder that uses interacts with a _cdk application_ uses the same set of configurations.

**Comment by zradlo1984** [comment]
The reason is that in cdk.js all options that has defaults specified (excluding undefined value) will be set after command line arguments. And in settings.js (class Configuration) is this code:
```
        this.settings = this.defaultConfig
            .merge(userConfig)
            .merge(this.projectConfig)
            .merge(this.commandLineArguments)
            .makeReadOnly();

```
so defaultConfig is overriden by userConfig (~/cdk.json) then by projectConfig(cdk.json) and then with commandLineArguments (which includes all defaults specified in cdk.js function parseCommandLineArguments so command line defaults overrides all options specified earlier).

**Comment by maximillianus** [comment]
Hi I am encountering this issue as well. Basically command line defaults override all the `cdk.json` options. I happened to see that pathMetadata is specified as true. Can it be specified as `undefined` so it capture cdk.json parameter without us having to write a long command line?

Here is example of my CLI default:
```
Command line arguments: {
  _: [ 'synth' ],
  v: 1,
  verbose: 1,
  defaultAccount: 123456789012,
  defaultRegion: 'some-region',
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  ci: false,
  validation: true,
  quiet: false,
  q: false,
  '$0': 'some/path/to/bin/cdk'
}
```

**Comment by berenddeboer** [comment]
[The documentation](https://docs.aws.amazon.com/cdk/v2/guide/cli.html) clearly states you can set command-line options in cdk.json. But this does not work. [Lots of reports](https://stackoverflow.com/a/70268158/843898), including here obviously.

**Comment by ggallo** [comment]
Still broken as of 2.56.0 (build 1485f48)

**Comment by jbschooley** [comment]
And still broken in 2.56.1. Very frustrating as I don't like having to type `--path-metadata false` every time I diff or deploy.

**Comment by brianalexander** [comment]
Any update on this?  I use a tool that's calling cdk synth for me, so I cannot add --path-metadata false to my calls.  It's not being respected in the cdk.json either.  

Thanks!
