### ISSUE TITLE
Inconsistent Python API defining CFN Security Group Ingress/Egress Property rules

### ISSUE THREAD

**Issue by evmin** [aws/aws-cdk#3647]
* **I'm submitting a ...**
  - [x ] :beetle: bug report

* **What is the current behavior?**

I observe what I understand as an inconsistent API around defining Security Group Ingress and Egress rules using CFN* stack.
 
Example:

```python
ingress_ssh = ec2.CfnSecurityGroupIngressProps(ip_protocol="tcp",
                                               from_port=22,
                                               to_port=22,
                                               cidr_ip="0.0.0.0/0")

egress_all = ec2.CfnSecurityGroupEgressProps(group_id="aa",
                                             ip_protocol="tcp",
                                             from_port=0,
                                             to_port=65535,
                                             cidr_ip="0.0.0.0/0")

sg = ec2.CfnSecurityGroup(stack,
                         id="sg-ssh",
                         vpc_id=vpc.ref,
                         group_description="Default Group",
                         security_group_ingress=[ingress_ssh],
                         security_group_egress=[egress_all])
```

Please observe the mandatory `group_id` parameter.
My understanding is that the parameter is ignored - everything is operational.

* **Suggested fix**

I suspect the parameter `group_id` can be removed from the CfnSecurityGroupEgressProps constructor.

Am I missing something?

* **Environment**

  - CDK CLI Version: 1.30
  - Module Version: 0.36.1
  - OS: OSX Mojave 
  - Language: Python

**Comment by rix0rrr** [comment]
It is interesting that this happens to work, and it's probably by accident because these classes happen to share some attributes of the same name.

`CfnSecurityGroupEgressProps` defines the construct properties for a new [`CfnSecurityGroupEgress`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnSecurityGroupEgress.html) resource.

A `CfnSecurityGroup` takes as its `security_group_egress` property a list of [`CfnSecurityGroup.EgressProperty`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnSecurityGroup.EgressProperty.html) objects.

Hope that answers it for you.

**Comment by evmin** [comment]
Thank you. 

I understood your response as that

* CfnSecurityGroupIngressProps
* CfnSecurityGroupEgressProps

Have a slightly different purpose, yet a similar name pattern. Is it correct?

If so and they indeed serve a slightly different purpose (or rather being a part of a different compositions), would it be beneficial for them to follow slightly different naming standard - just to keep up with a general principle of self documenting names?

Just a thought though.
