### ISSUE TITLE
[apigateway] Allow customizing the name of the CfnOutput containing the API endpoint

### ISSUE THREAD

**Issue by badaldavda** [aws/aws-cdk#3662]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
Currently rest api creation automatically creates an Output value. But it does not create an export for this output. Also, there does not seem to be any way to export this output by overriding the output property to add an export in any way. If I add something like -

`core.CfnOutput(self, id="Test", value=topic.topic_arn, export_name="Test")`

This will add a duplicate output 

* **What is the expected behavior (or behavior of feature suggested)?**
I expect that if there is an output for this, then it should also support in some way to add an export for it.

* **What is the motivation / use case for changing the behavior or adding this feature?**
If we are still doing an auto-output for rest api, then why not even add auto-exporting?

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

https://github.com/aws/aws-cdk/issues/1611 disabled exports by default. But output is still added by default for REST API. How/Why can't I add an export to it too? 

And by the sense of it, why is output still added by default too? What if I had a resource count of 61 and all of them are rest api, wouldn't it exceed the limit?

Also, any example to address cross stack reference by using export import using python would really help since this is something that i was not able to find in the documentation.

**Comment by RomainMuller** [comment]
Yup - I think the `RestApi` construct should just not provision a `CfnOutput` at all. Let the user decide whether they want an output or not (it's trivial for them to create one if they need it), and decide whether it's exported or not.

**Comment by jthornbrue** [comment]
Thanks. I submitted this question to AWS support because it wasn't well documented. I found the default output for the REST API but couldn't find a way to export it. Instead, I had to create a separate output and export it. Disabling the default output is an acceptable solution, since you're right, it's trivial to add if needed and could cause resource count issues if not.

**Comment by hervenivon** [comment]
Hey,

I agree with @RomainMuller. As the user cannot rename the `CfnOutput` provisioned by the `RestApi` construct and as several other constructs don't provision `CfnOutput` it seems legitimate to align the `RestApi` construct behavior: remove the `CfnOutput` generation from `RestApi` and let the user choose.

**Comment by eladb** [comment]
We can still add an `exportName` option to allow users to opt-in for exporting this output under some name.

**Comment by wimzyLive** [comment]
@eladb @RomainMuller  I am looking into this and these are changes that I think are required:
- update `RestApiProps` to accept optional `exportName` parameter
- update `configureDeployment` to handle provided `exportName`
- add test demonstrating changes 

Since this is my first time contributing, can you please advise if these are the changes required.
Thanks.😀

**Comment by eladb** [comment]
Makes sense. One thing that I don't think we can support is specifying an explicit name for an export (it will always be rendered based on the path of the Output construct in the tree). This means that even if you specify an exportName, you will only be able to control the relative construct ID o the `Output` and not the full ID. Might be worth adding support for specifying an explicit name for `Output` in @aws-cdk/core (can be done as part of this change or another PR).

**Comment by wimzyLive** [comment]
@eladb I am not sure what you mean by "even if you specify an exportName, you will only be able to control the relative construct ID o the Output and not the full ID", because `CfnOutput` does except `exportName` in props, so when I pass exportName as a prop like:
`new CfnOutput(this, 'Endpoint', { exportName: ''my-export-name", value: some-value });`
it should create output `with my-export-name`?
