### ISSUE TITLE
[Feature Request]: Query Results Cloudwatch dashboard

### ISSUE THREAD

**Issue by ayang-629** [aws/aws-cdk#3681]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

Currently, the CDK just supports 4 of the 5 existing dashboard widgets: `line`, `stacked`, `number`, `text`.

* **What is the expected behavior (or behavior of feature suggested)?**

There is a `Query Results` widget that allows us to put cloudwatch insights visualizations into dashboards

* **What is the motivation / use case for changing the behavior or adding this feature?**

It's currently possible to hack a way to create that Widget via a call to `CfnDashboard` instead, but there should be a Class defined to handle this like there is for the other 4 widgets. 

* **Please tell us about your environment:**

  - CDK CLI Version: 1.13
  - Module Version: 1.13
  - OS: all
  - Language: Typescript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by ninahaack** [comment]
Hi, do you have any idea when this feature will be released?

**Comment by dhumeniuk** [comment]
You can extend the ConcreteWidget class to define your own custom widget implemntation where you define the JSON. Here's an example for a widget with an expression metric:

```scala
class ExpressionMetricWidget(construct: Construct, props: ExpressionMetricWidgetProps) extends ConcreteWidget(props.width, props.height) {
  val stack = Stack.of(construct)

  override def toJson = {
    jList(
      Map(
        "type" -> "metric",
        "width" -> getWidth,
        "height" -> getHeight,
        "x" -> getX,
        "y" -> getY,
        "period" -> "300",
        "properties" -> Map(
          "view" -> "timeSeries",
          "title" -> props.title,
          "region" -> stack.getRegion,
          "metrics" -> List(
            List(
              Map("expression" -> props.expression.getExpression)
            )
          )
        )
      )
    )
  }
}
```

**Comment by NGL321** [comment]
Hey @ayang-629,
Thanks for submitting this feature request!

@ninahaack unfortunately we have long list of features to implement, so I cant give you a timeline on working on this one.

If someone would like to work on this and put in a PR, we can review and merge it into the codebase, otherwise one of us will update this issue when there is an update to this.

😸

**Comment by rix0rrr** [comment]
Don't exactly know what support for this feature entails, but if is Math Expressions, that is being worked on in https://github.com/aws/aws-cdk/pull/5582

**Comment by MarcelloLins** [comment]
Adding more context to this feature request, because I think it may have been misinterpreted. 

CloudWatch Dashboards contain widgets of various types, out of which CDK supports a few ([alarm](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.AlarmWidget.html), [graph](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.GraphWidget.html), [text](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.TextWidget.html) etc). Currently CDK does not support the widget used to plot results of "CloudWatch Insight Queries".

Here's an example of how one of these widgets is represented by CloudWatch on a dashboard:

`{
            "type": "log",  <--- Important
            "x": 0,
            "y": 36,
            "width": 9,
            "height": 9,
            "properties": {
                "query": "SOURCE '/aws/lambda/<LogGroupName>' | filter level=\"ERROR\" and message = \"EXCEPTION\"\n|stats count(*) as Count by message",
                "region": "us-east-1",
                "stacked": false,
                "title": "Count of Service Exceptions",
                "view": "table"
            }
        }
`
There is no current way to create a widget like this without extending an existing widget and overriding it's `toJson` method to generate a Json similar to the one above. The only two noteworthy changes to the JSON above (compared to existing ones) are the "type: log" and the new property called "query" which contains a log group followed by the CW Insights query itself.

I'm happy to provide more details if needed.
