### ISSUE TITLE
aws-eks module: error: You must be logged in to the server (Unauthorized) on v1.5.0

### ISSUE THREAD

**Issue by wistonk** [aws/aws-cdk#3752]
## :bug: Bug Report
`$ kubectl get svc`
`error: You must be logged in to the server (Unauthorized) `
### What is the problem?

I created an EKS CLuster with below sample code, However when i execute `kubectl get svc` the result is `error: You must be logged in to the server (Unauthorized)`. This is not the expected result. Below is the codebase
```
const clusterAdmin = new iam.Role(this, 'AdminRole', {
            assumedBy: new iam.AccountRootPrincipal()
   });
const clusterProps = {
            vpc: 'my vpc',
            mastersRole: clusterAdmin,
            clusterName: 'eks cluster name',
            vpcSubnets: [
                {subnetType: ec2.SubnetType.PUBLIC}
            ]
        };
const cluster = new eks.Cluster(this, 'eks cluster name', clusterProps);

```
The same codebase worked in v1.3.0, however when i do downgrade to v1.3.0 still its not working now.

### Reproduction Steps

I deploy as below
`cdk deploy myStackName  --profile <MyProfile>`
- **NOTE:** <**MyProfile**> is an Iam User with admin privileges
then 

`$ kubectl get svc`
`error: You must be logged in to the server (Unauthorized)`

### Environment

  - **CDK CLI Version:** 
   `cdk --version 1.5.0 (build c020efa)`
  - **Module Version:** 
   `aws-eks`
  - **OS:** 
   `MacOs`
  - **Language:** 
   `TypeScript`

**Comment by dstroppa** [comment]
@wistonk This might be due to the fact that you are using different IAM credentials to create your EKS cluster and to run the `kubectl` command, see https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html#unauthorized.

Could you run the `cdk deploy` and `kubectl` command using the same set of credentials and confirm if the issue still shows up?

**Comment by wistonk** [comment]
@dstroppa 
I can very the identity of the user. This is the same user who `cdk deploy myStackName --profile <MyProfile>`

If I do
```
$ export AWS_PROFILE= <MyProfile>
$ aws sts get-caller-identity
{
    "UserId": "B78GS72NSH292PCORO2",
    "Account": "7xxxxxxxxxxxx0",
    "Arn": "arn:aws:iam::7xxxxxxxxxxxx0:user/<MyProfile>"
}

$ kubectl get svc
error: You must be logged in to the server (Unauthorized)
```

**Comment by eladb** [comment]
Since v1.4.0 the role that's used to create the cluster is no longer the user who deployed the CloudFormation stack but rather a role maintained by the CDK. This is why you now have the ability to specify a masters role, but you will have to use it when you log int to your cluster.

See [Interacting with your Cluster](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-eks-readme.html#interacting-with-your-cluster) in the docs.

I am closing for now. Reopen if this persists.

**Comment by rafalkrupinski** [comment]
I made a mistake, got the same error and ended up here.

The current solution is to read the output of `cdk deploy`, which tells you exactly how to configure kubectl for EKS.
