### ISSUE TITLE
ecs service discovery: should the namespace be tied to the cluster?

### ISSUE THREAD

**Issue by bgdnlp** [aws/aws-cdk#3898]
### The Question
When using `aws_ecs.FargateService()` and `aws_ecs.Ec2Service()` it is possible to pass `cloud_map_options` (Python) to the method to create a new service for service discovery. The namespace for Cloud Map seems to be tied to the ECS cluster, instead of the ECS service. Which is surprising, because it's a requirement that is only enforced by the CDK.

Is that intended? Because it could interfere with existing tools/infrastructure/policies. For example, a company could use one cluster per team/department, but a team might be allowed to use different namespaces.

### Environment

  - **CDK CLI Version:** 1.6.1
  - **Module Version:** 1.6.1
  - **OS:** all
  - **Language:** all

**Comment by SoManyHs** [comment]
Generally, we envisioned clusters having a single namespace, so that services created with cloudmap in that cluster would inherit that name automatically for easier communication. However, it sounds like the CDK should allow specifying a namespace on a given service that overrides retrieving it from the cluster. We can open a feature request for this-- thanks for bringing it up!

**Comment by pkandasamy91** [comment]
Closing this issue as https://github.com/aws/aws-cdk/issues/4677 looks to resolve this issue. Feel free to reopen if it does not.
