### ISSUE TITLE
Can't specify subnet_ids for lambda Function

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#3923]
We have an existing vpc with many subnets.  I want to deploy a lambda function to 2 specific subnet ids.  However, there is no way to specify a list of specific subnets with the CDK.

At best, there is a ec2.SubnetSelection https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/SubnetSelection.html#aws_cdk.aws_ec2.SubnetSelection that doesn't do what I want, and doesn't look like it's exposing the actual Lambda API.

We previously deployed using yaml cloudformation and I found it easy to just specify security group, vpc, and subnet IDs (as strings) without hassle.   By contrast, the CDK causes me a lot of hassle having to lookup and require "objects" for *everything*, and requiring a stack context as well for all lookups, which is just unnecessary when we're deploying to one region.

**Comment by kjpgit** [comment]
Actually I found a workaround: You just override the *entire vpc object*

```
    # NB: "foo" is actually fine here, nothing reads it
     vpc = aws_ec2.Vpc.from_vpc_attributes(self, "vpc",
                availability_zones=["foo"],
                vpc_id="foo",
                private_subnet_ids=["subnet-0fa7c0c317ed17544", "subnet-07c9ad705779cd9ce"],
                )

   lambdaFn = aws_lambda.Function(self,
            "MyLambda",
            vpc=vpc,
            ...
        )


```

**Comment by kjpgit** [comment]
It took a while for me to find this workaround because the docs are misleading / wrong.

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Vpc.html#aws_cdk.aws_ec2.Vpc.from_vpc_attributes

Merely says "Import an exported VPC."

That is wrong; "exported" means something very specific with cloudformation (exported outputs), and that is NOT required here.  Any manually created vpc works AFAIKT, it just uses what strings you provide to conjure a new object - no exports are happening.

**Comment by NGL321** [comment]
Hi @kjpgit,

After brief investigation, I found in the [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#vpcsubnets) that there is a prop for Lambda functions that allows you to specify subnets. It requires a VPC object to be associated with the function, but that is also a prop that can be specified.

Your workaround is actually a good way to structure the code here, and until the issue of assigning subnets by id in SubnetSelection is addressed, this seems like the best way to assign without a subnet name.

With regard to the "export" language, please bear in mind that the CDK uses its own terminology and that may not always be 1 to 1 with Cloudformation. That being said, we will take the confusion under advisement and consider the implications for documentation.

Moving forward, it will be easier for us to quickly get a handle on the problem you are having if you follow our issue template. This will allow us to more quickly identify and address the issue.

If you have any other problems, please reach out, otherwise I will close this issue for now.
😸
