### ISSUE TITLE
LoadBalanced Fargate Service does not expose deregistrationDelay attribute

### ISSUE THREAD

**Issue by sebsto** [aws/aws-cdk#4015]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description

Pre GA, the LoadBalancer Target Group object exposed by LoadBalancedFargateService construct used to expose the property "deregistrationDelay' 

Since GA, this property seems to be readonly.  It is not modifiable anymore.

Pre GA code : 
```
const lbfs = new ecsp.LoadBalancedFargateService(...)
lbfs.targetGroup.deregistrationDelaySecs = 10;
```

Post GA workaround 
```
lbfs.targetGroup.setAttribute('deregistration_delay.timeout_seconds', '10');
```
It woud be nice to be allowed to set this value without using `setAttribute`

Reference : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.LoadBalancedFargateService.html
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationTargetGroup.html 
### Environment

  - **CDK CLI Version:** 
```
$ cdk --version
1.7.0 (build 8870695)
```
  - **Module Version:** 
```
    "@aws-cdk/aws-ecs": "^1.7.0",
```
  - **OS:** MacOS Mojave 
  - **Language:** : TypeScript

**Comment by stephenh** [comment]
+1. The current default of 10 minutes is safe, but overly so, and several times has made me think "crap, `AWS::ECS::Service` is locked up again".

... ... actually, it _is_ locked up again, but for something else.

Still, would be nice to have this.

**Comment by pkandasamy91** [comment]
@stephenh I believe you could still do `lbfs.targetGroup.setAttribute('deregistration_delay.timeout_seconds', '10');` to allow you to override the default value.

**Comment by bvtujo** [comment]
Hi @sebsto, our current recommendation is to use the workaround in Piradeep's comment above. 

> `lbfs.targetGroup.setAttribute('deregistration_delay.timeout_seconds', '10');`

Because this attribute is accessible after construction, we don't see it as a priority to add to the constructor properties, as we have to strike a balance between useful succinctness and configurability. In this case, since there is a way to address it after the L3 construct is created, we feel that it's best to omit from the LBFargateServiceProperties. 

I'm closing this for now, but please feel free to discuss this further.
