### ISSUE TITLE
Blank page in TypeScript API Reference for some CfnXxxxx constructs

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#4046]
### What is the problem?
The TypeScript API reference page for aws-apigateway/CfnRestApi is blank.

https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-apigateway/cfnrestapi.html#aws_apigateway_CfnRestApi

Looks fine in other versions of the API reference.

**Comment by rix0rrr** [comment]
Yep, this is true. It's because we have classes and namespaces with the same name, and the doc generator gets confused. I told @fulghum about this in the past, but the work to fix it is substantial (replace the TypeScript doc extractor with a different one). 

There are more things wrong with the TypeScript type extract, one of them being it doesn't seem to include inheritance information.
