### ISSUE TITLE
WAF construct library

### ISSUE THREAD

**Issue by adamsipos** [aws/aws-cdk#4071]
### The Question

I'd like to write my WAF rules separately from the actual deployment so I can dynamically update them during development. Therefore I'd need a functionality like Bucket.fromBucketName() that'd give me a cross-stack reference to WAF.

### Environment

  - **CDK CLI Version:** 1.8.0
  - **Module Version:** 1.8.0
  - **OS:** all
  - **Language:** TypeScript

**Comment by NGL321** [comment]
Hey @adamsipos,

I apologize for the slow response. This seems like a very reasonable feature to request.

If you would like to see this feature fast, the quickest way would be to write the fix and put in a PR for it! Otherwise, someone will update this issue once there is a change of status, or something requires discussion.

Cheers!
😸

**Comment by nija-at** [comment]
Unfortunately, we still don't have L2 support on WAF which means that this isn't an easy addition to it.

We don't yet have a plan yet to add L2s to WAF, so this is going to take longer than expected.
