### ISSUE TITLE
Cannot run cdk deploy without setting AdministratorAccess policy

### ISSUE THREAD

**Issue by andrealascola-docebo** [aws/aws-cdk#4115]
### The Question

We are currently using aws cdk in our release pipeline(we are using `cdk deploy` command inside an aws codebuid project) but i am struggling to find a way to deploy without giving **administratorAccess** to the policy attached to the codebuild project.
It also would be useful for us to have a more fine grained policy to limit the change on stacks that are not supposed to change and so on...

I tried to attach this policy to give permissions on cloudformation changes but it seems that is not enough:

```
{
    "Sid": "VisualEditor1",
    "Effect": "Allow",
    "Action": "cloudformation:*",
    "Resource": "*"
}
```

This is the output of the `cdk deploy` command in this case:

```
dev-MyStack 
dev-MyStack: deploying... 

 ❌  dev-MyStack failed: Forbidden: null 
null 
```

 
### Environment

  - **CDK CLI Version:** 
1.6.0
  - **Module Version:** 
  - **OS:** 
aws codebuild ubuntu
  - **Language:** 
typescript

### Other information

There is a related stackoverflow question open:

https://stackoverflow.com/questions/57118082/what-iam-permissions-are-needed-to-use-cdk-deploy

**Comment by RomainMuller** [comment]
I reckon the way the `cdk` currently calls CloudFormation will result in the ChangeSet being applied with the caller's permissions... So it'd need permissions to invoke CloudFormation, **and** to perform any change your template requires.

If I am correct, we might be able to allow you to have a better permission assignment model by allowing you to specify a ChangeSet Execution Role, so that your CodeBuild project only needs permissions make CloudFormation calls and to pass that role to CloudFormation. And the execution role would only need the permissions required by CloudFormation to deploy your infrastructure.

**Comment by skinny85** [comment]
This (and other concerns) are discussed extensively in our "CI/CD for CDK apps" design issue: #3437 .

**Comment by NGL321** [comment]
@andrealascola-docebo,

I was wondering if we answered your question? Please let us know so we can close the issue, or understand what might be lacking in the documentation.

😸

**Comment by jokoso** [comment]
I ran into this issue yesterday, wanting to follow least privilege on our CI server, and stumbled upon #4039. The CDK needing access to the `cdktoolkit-stagingbucket-*` bucket on S3 seems to be what was causing the `Forbidden: null` error.

**Comment by skinny85** [comment]
This is possible by using the `--role-arn` switch to `cdk deploy`.

I'm resolving this one, feel free to re-open if you have any more questions.
