### ISSUE TITLE
Stability of CloudFormation Only packages

### ISSUE THREAD

**Issue by azatoth** [aws/aws-cdk#4439]
I notice that many packages that are for the moment only contains cloudformation mappings (like iot, amplify, athena, etc...) are marked as **Experimental** instead of **CloudFormation Only**, which is defined in https://docs.aws.amazon.com/cdk/latest/guide/reference.html. 

My suggestion is that unless they are to be actively implemented in the near future, they are to be retagged as  **CloudFormation Only**.

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @azatoth, thanks for submitting a feature request! We will look into this and someone will update this issue when there is movement.

**Comment by ccfife** [comment]
The labeling scheme in the AWS Construct Library API ref was updated so that CloudFormation only resources are marked as "stable", and the "experimental" label is reserved only for modules that are under active development to add higher-level abstractions. See [aws-athena](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-athena-readme.html) for an example. This documentation change closes this issue.
