### ISSUE TITLE
Feature: Add ability to set stack description

### ISSUE THREAD

**Issue by tom98784** [aws/aws-cdk#4457]
Cloudformation stacks have a description field. This should be setable through the CDK.
There is currently no [documented](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html) way to set it.

### Use Case
Descriptions provide a more human-friendly form of documentation. In my case, I have stacks in a shared environment and I'd like it to be clear to others what they are and who they belong to.

### Proposed Solution
A 'description' stack property would fulfill this requirement.

### Other
Description field as viewed in the console:
![Image of description field in the console](https://user-images.githubusercontent.com/12998351/66588275-02ff3180-eb84-11e9-9cae-5b874ca5267b.png)

Current documentation - no description property: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hey @tom98784,

Thank you for submitting this request! This seems totally reasonable, and not too difficult to implement.

If you would like to submit a PR one of us will review it, otherwise someone will update this issue when there is further information!

**Comment by nmussy** [comment]
From what I can see, the change set description isn't set when calling `createChangeSet` (there's a Description field there too), but in the [template body](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html).

The most appropriate I can see to implement this feature would be in [`CdkToolkit.deploy`](https://github.com/aws/aws-cdk/blob/7d6b4748176db300ecb323bc03a7eb7032f55a09/packages/aws-cdk/lib/cdk-toolkit.ts#L131).

@tom98784 Tell me if you'd like to give it a shot, otherwise I'd be happy to make a PR.

**Comment by tom98784** [comment]
@nmussy I've never done any TS so I'm not that confident, but it's a relatively straightforward change so I'll give it a go. If I've got nowhere in a few days/end up not having time to do it, I'll let you know.
