### ISSUE TITLE
elbv2: ApplicationTargetGroup should validate that port is specified (when required)

### ISSUE THREAD

**Issue by fogfish** [aws/aws-cdk#4628]
`ApplicationTargetGroupProps` defines all properties optional. However, it fails at runtime if `port` property is not defined.

### Reproduction Steps

```
import * as alb from '@aws-cdk/aws-elasticloadbalancingv2'

new alb.ApplicationTargetGroup(this, 'DefaultTarget', {});
```

### Error Log

```
A port must be specified (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: xxx)
```

### Environment

  - **CLI Version      :1.13.1 (build 96cfc63)**
  - **Framework Version:1.13.1 (build 96cfc63)**
  - **OS               :MacOS**
  - **Language         :TypeScript**

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
Hello @fogfish,

The `port` parameter not being required is due to the following, as described in [the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-port):

> If the target is a Lambda function, this parameter does not apply.

Same with `Protocol` and `VpcId`.

We could add some client-side checks (with exceptions being thrown), but I'm not sure it's possible to do it with types given the current API.

**Comment by fogfish** [comment]
Yes, this is definitely make sense. May be similar statement shall be applied to CDK docs
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationTargetGroup.html

Feel free to close the issue!

One side comment. I've notice that similar issue is reflected to other `Props`. I know it would not be closed as part of this bug report. However, have you considered to declare a narrow `Props` that concern a particular use-case. It would make API a typesafe good for developers but of course it would require maintenance from your side. In typescript, this is called 'Discriminated Unions'.

**Comment by rix0rrr** [comment]
Unfortunately we're not currently allowing type unions, since not all languages we're targeting with jsii support them natively and we haven't narrowed down a way to represent them in those languages.

We can still keep this issue open, even if there is no static checking, there should be runtime validation in the construct so you don't need to wait for a CloudFormation deployment to detect this situation.

**Comment by fogfish** [comment]
Oh... True... TypeScript is not a central language for AWS CDK. I'll wish it will be the only one ;-)

Thank you for feedback!

**Comment by nmussy** [comment]
I can take the PR if no one wants it 👍

**Comment by kaizen3031593** [comment]
I took a look into this, and it looks like the validation method is already there, introduced in #3348:

https://github.com/aws/aws-cdk/blob/7ec598eff0cbdc88c6a80d5d23d533e892f868e8/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts#L313-L330

Since `targetType` is not required by the resource, I don't think we can do any additional validation if `targetType` is undefined, which is why this becomes an error only when deployed.

Outside of the fact that I'm pretty sure the error message ought to read "Both port and protocol is required" based on the logic, I don't think there's much to do here.

@rix0rrr perhaps you can double check but I think this can just be closed.

**Comment by madeline-k** [comment]
Please re-open if you are experiencing this issue
