### ISSUE TITLE
java: cloudwatch ENUM values do not synthesize correctly

### ISSUE THREAD

**Issue by curtiseinsmann** [aws/aws-cdk#4629]
When creating CloudWatch alarms, many of the enums brought in by the CDK do not synthesize into usable values.

### Reproduction Steps
```java
import software.amazon.awscdk.services.cloudwatch.ComparisonOperator;
import software.amazon.awscdk.services.cloudwatch.CfnAlarmProps;

CfnAlarmProps.builder()
    // other properties
    .comparisonOperator(ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD.toString())
    .build();

```

### Error Log
The synthesized CloudFormation template is this:

"ComparisonOperator": "GREATER_THAN_OR_EQUAL_TO_THRESHOLD"

when it should be

"ComparisonOperator": "GreaterThanOrEqualToThreshold"

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I am confused by this line:

```  .comparisonOperator(ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD.toString())
```

Why is not just just

```
    .comparisonOperator(ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD)
```
?

**Comment by rix0rrr** [comment]
Oh I see what the issue is. You are using an L1 construct with an L2 enum. read this; https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_lib

Either use `Alarm` instead of `CfnAlarm`, or just put the same string into the property that you would use when writing CloudFormation directly.
