### ISSUE TITLE
Requesting guidance for cross account features 

### ISSUE THREAD

**Issue by ArendAMZN** [aws/aws-cdk#4633]
We're planning to build our cdk stacks across several accounts

In particular these are the features we'll need

A. cloudwatch events in account A trigger lambdas in account B (this is the next priority for us)
B. codecommit repos in account A used in codepipelines in account B (I got this working in v1.13.1 )
C. lambdas in account A are built used code from s3 buckets in account B (I've hit issues, they're defined here, https://github.com/aws/aws-cdk/issues/4632)
D. lambdas in account A call sqs queues in account B
E. codepipeline in account A builds a cloudformation in account B

I haven't started experimenting with all of these yet, but I wanted to double check whether all of these are possible before I spend too much time iterating through it

If the features aren't available yet, is there a roadmap I can follow to see the progress?

If the features are available, I'd be happy to provide code examples so that other CDK users can have an easier time with building cross account services. Would this be the right place to do it? https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript

**Comment by NGL321** [comment]
For future reference we typically try to keep the issue queue clear for technical guidance questions, bugs, and feature requests only. This seems like a question that might get asked frequently though, so I will leave an answer here too.
For future guidance, please refer to StackOverflow, or our [Gitter](https://gitter.im/awslabs/aws-cdk) room.

**A.** This is an available feature, please see the [APIReference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-readme.html)
B. As long as permissions are configured correctly, this shouldnt be a problem. [See here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html#aws-codecommit)
C. The bug has been seen, and should be looked into. Otherwise this seems doable.
D. That shouldnt be a problem so long as you have the right ARN and account number
E. Yes. See [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CloudFormationCreateUpdateStackAction.html)

If you are interested in submitting code samples to the examples repo that would be really helpful! You have the correct repo for it.

I hope that helps!
