### ISSUE TITLE
HostedZone.fromlookup not working in nested stacks

### ISSUE THREAD

**Issue by AlexRex** [aws/aws-cdk#4651]
When using HostedZone.fromLookUp in a nested stack is not able to find out the hostedzone and keeps the DUMMY id value. Also it does not creates the entry in the context file. 

### Reproduction Steps

Create a hosted zone in route 53. Then create a stack, inside this stack create a nested stack that just gets a zone based in a domain name:

```typescript
const zone = HostedZone.fromLookup(this, `zoneId`, {
      domainName: domain
    });
```

### Error Log

No hosted zone found with ID: DUMMY (Service: AmazonRoute53; Status Code: 404; Error Code: NoSuchHostedZone; Request ID: 9868b6a0-6109-48e6-b475-c31c6041778f)

### Environment

  - **CLI Version      :** v.1.12.0
  - **Framework Version:** v.1.12.0
  - **OS               :** mac
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by flashflexpro** [comment]
For me, the same error is from
`
        new r53.ARecord(this, id + 'phpadminARecord', {
            recordName: 'phpadmin',
            zone: phpadminHostzone,
            target: r53.RecordTarget.fromAlias(new r53Targets.LoadBalancerTarget(loadBalancerFromOtherStack))
        });
`
Template is

`{
  "Resources": {
    "??????????ARecordE5EA89BC": {
      "Type": "AWS::Route53::RecordSet",
      "Properties": {
        "Name": "recordName.hostzonename",
        "Type": "A",
        "AliasTarget": {
          "DNSName": {
            "Fn::Join": [
              "",
              [
                "dualstack.",
                {
                  "Fn::ImportValue": "phpAdmin-FargateAlb:ExportsOutputFnGetAttphpadminfargateserviceLB1A2C75E2DNSNameA1C77413"
                }
              ]
            ]
          },
          "HostedZoneId": {
            "Fn::ImportValue": "phpAdmin-FargateAlb:ExportsOutputFnGetAttphpadminfargateserviceLB1A2C75E2CanonicalHostedZoneID5377D125"
          }
        },
        "HostedZoneId": "PHYSICAL-HOSTEDZONEID"
      },
      "Metadata": {
        "aws:cdk:path": "phpAdmin-FargateAlbDNS/phpAdmin-FargateAlbDNSphpadminARecord/Resource"
      }
    }
  }
}`


It seems to be the `     "HostedZoneId": "PHYSICAL-HOSTEDZONEID"   ` is causing the problem, but only when running inside codepipeline.

**Comment by gyang-vonage** [comment]
Still happening, won't happen with command "cdk deploy",  only happens when using CloudFormationCreateUpdateStackAction.

**Comment by ilia-luk** [comment]
anyone managed to work around this?

**Comment by flashflexpro** [comment]
I figured it out, you need to add cdk.context.json into repo to
give CloudFormationCreateUpdateStackAction the context to load host zone.

**Comment by corymhall** [comment]
@AlexRex is this still an issue for you? I tried reproducing this issue on a recent version of the CDK and the `fromLookup` method was able to correctly populate the hosted zone id in a nested stack.

@AbendGithub it should work as long as you have AWS credentials with access to perform the lookup during synth. So in your case if you are performing synth as part of a CodeBuild action, the CodeBuild role must have access to perform the lookup. 

Alternatively, the recommended approach to handling lookups is to perform `synth` locally with credentials which will populate the `cdk.context.json` which should then be commited. Then during the pipeline execution, the synth CodeBuild action will use the value in `cdk.context.json` instead of performing a lookup. See the section on committing `cdk.context.json` in the [developer guide](https://docs.aws.amazon.com/cdk/latest/guide/best-practices.html#best-practices-apps)
