### ISSUE TITLE
BucketDeployment: unable to set cacheControl

### ISSUE THREAD

**Issue by sbstjn** [aws/aws-cdk#4665]
Using `cacheControl` for `BucketDeployment` in `@aws-cdk/aws-s3-deployment` does not work.

### Reproduction Steps

```ts
new BucketDeployment(this, 'deployment', {
  sources: [Source.asset(path.resolve(__dirname, '../build'))],
  destinationBucket: assets,
  distribution: cdn.distribution,
  cacheControl: [CacheControl.fromString(`max-age=600`)]
})
```

```ts
new BucketDeployment(this, 'deployment', {
  sources: [Source.asset(path.resolve(__dirname, '../build'))],
  destinationBucket: assets,
  distribution: cdn.distribution,
  cacheControl: [CacheControl.maxAge(Duration.minutes(10))]
})
```

### Error Log

Lambda error log for `/aws/lambda/…CustomCDKBucketDeployment…`:

```
aws s3 sync --delete /tmp/…/contents s3://foobar/ --cache-control 'max-age=600' --metadata-directive REPLACE

Unknown options: --cache-control 'max-age=600'
```

### Environment

  - **CLI Version      :** `1.14.0`
  - **Framework Version:** `@aws-cdk/aws-s3-deployment@1.14.0`
  - **Language         :** `typescript`

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@AlexCheema can you take a look please?

**Comment by iliapolo** [comment]
This problem is actually not strictly related to `cache-control`. It will happen for every property that eventually translates to [`SystemMetadata`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts#L257). The fix proposed in the mentioned [PR](https://github.com/aws/aws-cdk/pull/6086) address that problem as a whole.
