### ISSUE TITLE
Add support for us-iso partitions and regions

### ISSUE THREAD

**Issue by troyaws** [aws/aws-cdk#4669]
Add support for us-iso and us-iso-b partitions and all included regions.

### Use Case

Customers in these partitions/regions want the ability to utilize CDK for their workloads.

### Proposed Solution

update https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/region-info/build-tools/generate-static-data.ts

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by RomainMuller** [comment]
Hey,

In order to proceed, we will need the following:
- The list of region IDs (pretty sure we can find those ourselves somewhat easily, but if you have them handy...)
- The correct name of the Service Principals at least for the following services (unless of course they're not available in `us-iso` and `us-iso-b`):
  + application-autoscaling
  + autoscaling
  + codedeploy
  + ec2
  + events
  + lambda
  + logs
  + s3
  + sns
  + sqs
  + states
- If Route53 is available (I have doubts, but 🤷🏻‍♂️), the Route53 hosted zone IDs for the S3 static websites & API Gateway edge-optimized endpoints

Also, if you have a know set of things that does _not_ currently work, it would help if you can provide some information on those, so we can make sure that the above information actually covers the entire gap, and not just a part of it (the isolated regions are... peculiar enough to possibly trigger scenarios we haven't encountered yet).

**Comment by nmussy** [comment]
The publicly available documentation on the secret regions are a bit sparse.

The only useful info I could find was [aws-sdk-go endpoints.json's file](https://github.com/aws/aws-sdk-go/blob/master/models/endpoints/endpoints.json#L4877)

**Comment by awsjoe** [comment]
That's as good a place to start as any, what more would be required for the fulfillment of this issue?
