### ISSUE TITLE
QueueProcessingFargateService unable to set desiredCount to zero

### ISSUE THREAD

**Issue by eliasdraexler** [aws/aws-cdk#4719]
I was trying to create a QueueProcessingFargateService using the ecs-patterns construct library. 
I only want to start a Fargate Service if there is something waiting in the SQS queue.

Using the QueueProcessingServiceBaseProps it is not possible to create a Fargate Service that has a desiredTaskCount of 0, therefore, there will always be one service running even if no messages are in the queue.

I checked and the value 0 is overwritten and the desiredCount is always set to 1. 

Line 35 in queue-processing-service-base.js
`this.desiredCount = props.desiredTaskCount || 1;` 

Is this the desired effect?

### Environment

  - **CDK CLI Version:** 1.14.0 (build 261a1bf) 
  - **Module Version:**   "@aws-cdk/aws-ecs-patterns": "^1.14.0",
  - **OS:**  OSX Mojave
  - **Language:** TypeScript

**Comment by pkandasamy91** [comment]
@eliasdraexler @nmussy, This was actually intented behaviour. SQS metrics are usually published with a slight delay (If I remember correctly), and this could lead to a potentially large backlog and it's not something we recommend. 

That being said, for the case of a queue processing service specifically, I do understand the use case, but don't believe this will provide a good experience in the long run.

**Comment by nmussy** [comment]
@pkandasamy91 It's also currently impossible to set `desiredCount: 0` for ALB/NLB EC2/Fargate services. I've changed all 3 in my PR, but we could also add a warning for the SQS queues?

**Comment by pkandasamy91** [comment]
> @pkandasamy91 It's also currently impossible to set `desiredCount: 0` for ALB/NLB EC2/Fargate services. I've changed all 3 in my PR, but we could also add a warning for the SQS queues?

That's intentional, most Load Balanced services scale on memory or cpu usage (which won't apply if 0 tasks are started). I wouldn't recommend providing a desired count of 0 for load balanced services.

**Comment by eliasdraexler** [comment]
@pkandasamy91 Thanks for the explanation!
I just tried it out for a presentation, if this is intended behaviour maybe it should at least be documented? 
I was just confused as it is possible to set a `desiredCount` of 0 using cloudformation and couldn't get it to work using the CDK.

**Comment by pkandasamy91** [comment]
@eliasdraexler, I completely understand, and we should support the option to accept a desired task count of 0 for a queue processing service. 

The idea behind the ecs-patterns module is to provide users with constructs which build highly integrated applications with aws best practices kept in mind. Based on your use-case, it would make sense to allow the queue processing service to accept a desired task count of 0, but it's not something we would recommend, due to what i mentioned previously (in a production environment).

**Comment by mbruning24** [comment]
@pkandasamy91 my team and I have a testing workload where we're using fargate containers to run selenium test suites in parallel (at least until we can figure out how to run firefox in lambda 👍 ). I'm trying to develop a fan-out architecture using this queue processing fargate pattern to make the workload entirely asynchronous, and when no tests are being run (queue being empty) it makes total sense to not have any tasks running. Also, the delay in metric logging is acceptable for our use case as well.

Is there some compromise where the cdk allows setting desiredTaskCount to 0 for QueueProcessing constructs but then the CDK warns on cdk synth or something that says (like when you are about to deploy IAM changes) "Hey there! Setting desired tasks to 0 is not recommended because of x, y, z..."?

**Comment by pkandasamy91** [comment]
@mbruning24 sorry to be clear, I do understand that users would want a desiredTaskCount of 0 and will merge in the changes to address the issue for the queueprocessingservice. 

I don't think it makes sense for the other patterns though (such as the application/network load balanced services), unless someone can provide a use case.
