### ISSUE TITLE
EKS --use-max-pods=false not working

### ISSUE THREAD

**Issue by tomkivlin** [aws/aws-cdk#4805]
I am using a CF template to manage EKS Node Groups.  When I pass `--use-max-pods=false` into the `BootstrapArguments` parameter, it appears to be ignored by the bootstrap.sh script, or some other component as there is still a limit being applied to each node.

### Reproduction Steps

Pass `--use-max-pods=false` into the `BootstrapArguments` parameter of a CF template.

### Error Log

No error. The nodes still have a `pods` entry in the `allocatable` section of their configuration when I interrogate with `kubectl get nodes -o yaml`.

### Environment

  - **CLI Version      :     1.16.188**
  - **Framework Version: not sure - which framework?**
  - **OS               : MacOS**
  - **Language         : of what?**

### Other

Looks to be a duplicate of #4752 which should have been fixed in #4753?

--- 

This is :bug: Bug Report

**Comment by tomkivlin** [comment]
Other potentially useful information:
- I am attempting this in eu-west-3 (Paris)
- I am attempting this using t3.micro instances (my current workaround is to use t3.small to provide a larger allocatable value)

**Comment by SomayaB** [comment]
Hi @tomkivlin, you are right this is a duplicate and the issue was fixed and merged yesterday. There hasn't been a new release yet with those changes so that's why you're still experiencing this issue unfortunately. The new release should be out in a few days.
I will close this issue. Feel free to reopen if once you get the new release you still encounter some problems.

**Comment by tomkivlin** [comment]
Ah gotcha - thanks @SomayaB, sorry for the impatience!
