### ISSUE TITLE
ResolverEndpoint fails creation because of create requestor id

### ISSUE THREAD

**Issue by giovannidegani** [aws/aws-cdk#5012]
Hi, I'm trying to crate an inbound resolver endpoint using the following:

`new CfnResolverEndpoint(this, 'inbound-endpoint', {
      direction: 'INBOUND',
      ipAddresses: [{
       ip: 'ip-address-from-my-vpc',
       subnetId: 'id-of-the-subnet'
      }],
      name: 'enterprise-sap-dns',
      securityGroupIds: [ securityGroupPreviouslyCreated ],
    });`

### Reproduction Steps

Apply cdk deploy for a app that contains one stack with the above;

### Error Log
I get the following everytime I try to run it, but I get with different IDs
Resolver Endpoint with creator request id d7f51869-6cd1-4705-af5c-d3e2d967eba3 already exists

### Environment

  - **CLI Version      : 1.16.2
  - **Framework Version: 1.16.2
  - **OS               : Mac OS 10.14.6 Mojave
  - **Language         : Typescript

### Other

The API documention mentions an option for CreatorRequestId
https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverEndpoint.html

But it seems that is not exposed in the CloudFormation, so it seems that its handled internally in cloudformation, is a cloud formation bug ?

--- 

This is :bug: Bug Report

**Comment by giovannidegani** [comment]
I think the issue might be on specifying IP and subnetId at the same time, even though the IP is optional in the type CfnResolverEndpoint.IpAddressRequestProperty and subnetId is not.

It worked by specifying only subnetId

**Comment by shivlaks** [comment]
@giovannidegani can you confirm that this is not an issue for you anymore?

This doesn't seem like an issue with the CDK. Typically the `creatorRequestId` is an idempotency token so that you can make requests with your inputs and ensures that retries don't result in repeated service calls.

CloudFormation resources sometimes fill this in so that retries and subsequent attempts can be identified. You shouldn't require it, but in cases of retries, it's useful. Since CloudFormation retries on your behalf, it was likely provided by CloudFormation.

**Comment by shivlaks** [comment]
dropping the bug label as I don't think this is a bug. I'm able to create resolver endpoints without any issues.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a little while. Feel free to reopen if your issue hasn't been solved.

**Comment by ccqw** [comment]
Hopefully I can comment without reopening. I had this issue myself and discovered that the cause in my case was this:

I already had a resolver of a different type (inbound vs outbound) in my target VPC that was using the IP addresses I explicitly specified. When I explicitly specified different, unused IPs, I was able to successfully provision the endpoint.

I hope that helps someone!

**Comment by AbhilashPM** [comment]
Hello Everyone. Sorry to re-initiate an old thread, however, I believe the bug still exists. I am facing this issue when I try to create a Route53 Inbound Endpoint (possibly applicable for outbound endpoint also) from CloudFormation Template through the AWS console as well. I tried multiple times, however, I get the same error with different creator request ID. The same cloudformation template, with almost identical values worked on a different account. 

**What I tried:**

1. Tried to create Inbound Resolver Endpoint using AWS CloudFormation Web Console
2. I am explicitly providing both subnetId and IP Address
3. Tried to create Inbound Resolver Endpoint multiple times with the same value through CloudFormation Web Console in an AWS account
4. Tried to create Inbound Resolver Endpoint with almost similar values through CloudFormation Web Console but in a different AWS account (It worked)

I believe this is because of a bug when cloudformation tries calling the CreateResolverEndpoint API. This API requires a field CreatorRequestId which should be a unique value. 

**My Guess**:

1. Either CloudFormation/SDK is not generating unique creator request ids in the UUID format (as per the uniqueness criteria expected by the API) prior to calling the API. OR
2. The API is not evaluating the uniqueness correctly. I am guessing the uniqueness should be evaluated at a regional level for a specific Account which may not be currently happening. 

**Attaching Screengrabs from my CloudFormation Console:**

![image](https://user-images.githubusercontent.com/52920004/119361890-c422de80-bcc9-11eb-8cbd-c1e00ac13b53.png)

![image](https://user-images.githubusercontent.com/52920004/119364370-73f94b80-bccc-11eb-9bd4-4e7db37bb798.png)

**Comment by AbhilashPM** [comment]
Apologies for my earlier comment. One of the IPs that I was specifying was in use as a Secondary IP. I had failed to notice it before. Providing unused IP addresses solved the issue. However, I feel that the error message was a bit deceiving as it did not correctly state the cause of the error. May be if it could tell if the IP address(s) specified is already in use, then it could have been better.

Thanks to @ccqw for the pointer.
