### ISSUE TITLE
getApplicationName produces null value for CfnApplicationV2

### ISSUE THREAD

**Issue by Jason-liujc** [aws/aws-cdk#5136]
As the title says, the getApplicationName from the CfnApplicationV2 returns null value. 

### Reproduction Steps

1. Use CDK java v1.15 on MacOS
2. Declare a CfnApplicationV2 object 
3. Use the getApplicationName method of the object in an immutable map
4. gets null value error.

I was able to unblock myself by using the getRef method

### Code
```java
    // getApplicationName for CfnApplicationV2 is not working.
  final CfnApplicationV2 flinkApp =
            new CfnApplicationV2(
                    this,
                    "FlinkApplication",
                    CfnApplicationV2Props.builder()
                    .serviceExecutionRole(createKdaRole().getRoleArn())
                    .runtimeEnvironment("FLINK-1_6")
                    .build());

    // CloudWatch related infrastructure
    final Map<String, String> logGroupNameSub =
        ImmutableMap.of("FlinkApplication", flinkApp.getApplicationName());

```

I omitted some of the more detailed configurations I did in between.

### Error Log

```
Exception in thread "main" java.lang.NullPointerException: null value in entry: FlinkApplication=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(Unknown Source)
	at com.google.common.collect.SingletonImmutableBiMap.<init>(Unknown Source)
	at com.google.common.collect.ImmutableBiMap.of(Unknown Source)
	at com.google.common.collect.ImmutableMap.of(Unknown Source)
	at com.amazon.cpstream.kda.cdk.SampleStack.<init>(SampleStack.java:118)
	at com.amazon.cpstream.kda.cdk.SampleApp.main(SampleApp.java:12)
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :*1.15*
  - **Framework Version:*1.15*
  - **OS               :*MacOS*
  - **Language         :*Java*

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @Jason-liujc ,

thanks for opening the issue. The property is `null`, because you haven't passed anything in the `applicationName` creation property. If you will, it will not be `null`, for example:

```java
        Role createKdaRole = Role.Builder.create(this, "Role")
                .assumedBy(new AnyPrincipal())
                .build();

        CfnApplicationV2 flinkApp = CfnApplicationV2.Builder.create(this, "FlinkApplication")
                .serviceExecutionRole(createKdaRole.getRoleArn())
                .applicationName("my-app-name")
                .runtimeEnvironment("FLINK-1_6")
                .build();

        Map<String, String> logGroupNameSub =
                ImmutableMap.of("FlinkApplication", flinkApp.getApplicationName());
```

Hope this helps!

Thanks,
Adam

**Comment by Jason-liujc** [comment]
Thanks for responding Adam, it make sense now! Just wondering, would it make more sense to have the getApplicationName return a token here so the name would get resolved later? Sort of similar to what's happening here: https://docs.aws.amazon.com/cdk/latest/guide/tokens.html with the s3 bucket.

**Comment by skinny85** [comment]
Yes it would :) However, on the L1 layer (which the `CfnApplicationV2` class belongs to), we are 1:1 with the CloudFormation schema. In order for `applicationName` to be a Token, it would need to be an attribute of the `ApplicationV2` CloudFormation resource. If you look at the [bucket schema](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#aws-properties-s3-bucket-return-values-fn--getatt), that you mentioned as an example to follow, you see it has a bunch of attributes we can make the tokens resolve to; however, the same page [for `CfnApplicationV2`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisanalyticsv2-application.html) does not have any outputs, and that's why we can't late-bind to them like we can in bucket.

Does this make sense?

Thanks,
Adam

**Comment by Jason-liujc** [comment]
Thanks. Yea this make sense.
