### ISSUE TITLE
AWS ECS: Ec2Service too many resources

### ISSUE THREAD

**Issue by peterdeme** [aws/aws-cdk#5168]
## Problem

Current ECS design is close to unusable when one wants to re-use an ECS Cluster across multiple ECS services (across multiple git repos) because there is too much going on under the hood.

Please make the flow less strict so that the CDK can have greater ECS adoption.

## Description

Hey Guys,

So a couple of months ago year ago I tried CDK but realized it wants to create too many unwanted resources (https://github.com/aws/aws-cdk/issues/2234). Today, I gave it another chance.

I tied to create an ECS [Ec2Service](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/ec2/ec2-service.ts#L114) but I'm failing at the point where I need to provide the cluster. So we (I guess other companies, too) have a single cluster where we host a lot of services. These services live in different Git repos.

As you can see in [the official documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-cluster), the cluster parameter of EcsService is a string where `aws-cdk` [asks](https://github.com/aws/aws-cdk/blob/06caf4f2b9165337bdcb6042e5cd03b08cc9a37b/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L71) for a goddamn `ICluster`.

I guess it's needless to say how unconvenient this is when you only know the name of the cluster. Well, if I want to import my existing cluster with `Cluster.fromClusterAttributes` ([ref](https://github.com/aws/aws-cdk/blob/06caf4f2b9165337bdcb6042e5cd03b08cc9a37b/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L52)), I **must** know it's `VpcId` and `SecurityGroups` which I really don't want to provide, it's too low-level information. (My company has a raw cloudformation template right now where we only provide the cluster name.) Also: why? In the [official CF docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html), nothing is required.

So I took a look at why `Ec2Service`  needs a full-fledged `ICluster`. When looking at the [constructor](https://github.com/aws/aws-cdk/blob/caa007751bf0ce88b2e21705cb675988ec957531/packages/%40aws-cdk/aws-ecs/lib/ec2/ec2-service.ts#L114) I sadly realized that once again the CDK wants to create all kinds of resources [here](https://github.com/aws/aws-cdk/blob/caa007751bf0ce88b2e21705cb675988ec957531/packages/%40aws-cdk/aws-ecs/lib/ec2/ec2-service.ts#L161) and [here](https://github.com/aws/aws-cdk/blob/caa007751bf0ce88b2e21705cb675988ec957531/packages/%40aws-cdk/aws-ecs/lib/ec2/ec2-service.ts#L165). Needless to say that Troposphere [only requires a string](https://github.com/cloudtools/troposphere/blob/master/troposphere/ecs.py#L112).

Now, I'm genuinely confused about the general philosophy of the CDK. We have [ecs-patterns module](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-ecs-patterns) and I thought that one is for providing really high-level constructs and if someone is a fan of creating unwanted resouces, it's for those people. Now, looks like we can't even create an ECS `Ec2Service` conveniently.

So, let me ask: what's the goal of CDK? It's for companies who don't want to control all their AWS resources and only care about higher level abstractions? It's supposed to serve every use case? By looking at the constructor of `Ec2Service`, I can't really decide. It feels like it dances around the edge of high and low level abstractions.

## Recommendations
- In `Cluster` nothing should be required, maximum `clusterName`. Dumb down `Cluster.fromClusterAttributes` to only require a `clusterName`, this means `vpc` and `securityGroups` should be optional.
- In the constructor of `Ec2Cluster`, if the`ICluster` does not have `vpc` and `securityGroups` defined, do not create additional resources [like a new security group](https://github.com/aws/aws-cdk/blob/caa007751bf0ce88b2e21705cb675988ec957531/packages/%40aws-cdk/aws-ecs/lib/ec2/ec2-service.ts#L160-#L166). I think this part of the code is too magical anyway.

edit.: I think I solved it with a nasty workaround.

```typescript
import { CfnService } from '@aws-cdk/aws-ecs';

new CfnService(scope, "MobileService", {
    taskDefinition: taskDefinition.taskDefinitionArn,
    cluster: "clusterName-as-a-string"
});
```
This gets the job done but attaching a load balancer is not easy...

edit2: never mind guys, load balancer also require importing an existing Vpc instead of VpcId. I guess if I want to keep use CDK I'll need to use raw `Cfn*` sources. :(

**Comment by peterdeme** [comment]
FYI @SomayaB I got it figured out in a funky way, haha. It's a bit risky, because there's multiple fake values provided that are not used in the CF template (and I can just hope it stays that way).

Here it is:

```typescript
const cluster = Cluster.fromClusterAttributes(scope, "Cluster", {
        clusterName: cfParameter(scope, ParameterName.ClusterName).toString(),
        securityGroups: [],
        vpc: {} as IVpc
    });
```

And the fact that this works **perfectly** makes my point even stronger:
- either `securityGroups` and `vpc` should be optional in `Cluster.fromClusterAttributes`
- or we need a new method called: `Cluster.fromClusterName(scope, clusterName)`

_(Disclaimer: `cfParameter` is a helper method that wrapps `CfnParameter`)_

I also figured out how to create a load balancer if you only know the VpcId and the subnets. This one also uses a couple of fake inputs which is a bit risky. :/

The whole thing:

```typescript
import cdk = require('@aws-cdk/core');
import { TaskDefinition, Compatibility,  ContainerImage, Cluster, Ec2Service } from '@aws-cdk/aws-ecs';
import { GenericLogDriver } from "@aws-cdk/aws-ecs/lib/log-drivers/generic-log-driver"
import { Repository, IRepository } from '@aws-cdk/aws-ecr';
import { PolicyStatement, Effect } from '@aws-cdk/aws-iam';
import { cfParameter } from "../../parameters/parameters"
import { ParameterName } from '../../parameters/parametername';
import { ApplicationLoadBalancer, ApplicationProtocol, ApplicationTargetGroup, ApplicationListener, IApplicationLoadBalancer, TargetType } from '@aws-cdk/aws-elasticloadbalancingv2';
import { queue } from "./sqs"
import { Vpc, IVpc, SecurityGroup } from '@aws-cdk/aws-ec2';
import { Fn } from '@aws-cdk/core';

export function createEcsService(scope: cdk.Stack) {
    const svc = setupEcsService(scope);   

    setupLoadBalancer(scope, svc);
}

function setupEcsService(scope: cdk.Stack) {
    const taskDefinition = new TaskDefinition(scope, "mobile-taskdefinition", {
        compatibility: Compatibility.EC2
    });

    const role = taskDefinition.obtainExecutionRole();

    role.addToPolicy(new PolicyStatement({
        effect: Effect.ALLOW,
        actions: ["sqs:*"],
        resources: [queue.queueArn]
    }));

    const appVersion = cfParameter(scope, ParameterName.AppVersion);

    const container = taskDefinition.addContainer("MobileContainer", {
        image: ContainerImage.fromEcrRepository(getRepository(scope), appVersion.toString()),
        memoryReservationMiB: 512,
        environment: {
            "EnvironmentName": cfParameter(scope, ParameterName.EnvironmentName).toString()
        },
        logging: new GenericLogDriver({
            logDriver: 'sumologic',
            options: {
                "sumo-source-category": 'example-tag',
                "sumo-url": "https://my-sumo-url.com"
            }
        })
    });

    container.addPortMappings({ containerPort: 5000});
    
    const cluster = Cluster.fromClusterAttributes(scope, "Cluster", {
        clusterName: cfParameter(scope, ParameterName.ClusterName).toString(),
        securityGroups: [],
        vpc: {} as IVpc
    });

    const svc = new Ec2Service(scope, "Service", {
        cluster: cluster,
        taskDefinition: taskDefinition
    })

    return svc;
}

function setupLoadBalancer(scope: cdk.Stack, ecsService: Ec2Service) {    
    const vpc = Vpc.fromVpcAttributes(scope, "EnvVpc", {                
        vpcId: cfParameter(scope, ParameterName.VpcId).toString(),
        publicSubnetIds: [
            cfParameter(scope, ParameterName.EnvironmentName) + Fn.importValue("PublicASubnet"),
            cfParameter(scope, ParameterName.EnvironmentName) + Fn.importValue("PublicBSubnet")
        ],
        // The following values are mandatory to provide
        // but they won't be present in the CF template because the loadbalancer is public, not private
	// so don't worry about them
        availabilityZones: ['not_used1', 'not_used2'],        
        privateSubnetIds: ["not_used1", "not_used2"],
        isolatedSubnetIds: ["not_used1", "not_used2"],
        isolatedSubnetRouteTableIds: ["not_used1", "not_used2"],
        privateSubnetRouteTableIds: ["not_used1", "not_used2"],
        publicSubnetRouteTableIds: ["not_used1", "not_used2"]
    });

    const lb = new ApplicationLoadBalancer(scope, 'LB', {
        vpc: vpc,
        internetFacing: true,
        securityGroup: SecurityGroup.fromSecurityGroupId(scope, "SecurityGroup", "sg-434")
      });

    const targetGroup = new ApplicationTargetGroup(scope, "TargetGroup", {
        vpc: vpc,
        protocol: ApplicationProtocol.HTTPS,
        targetType: TargetType.INSTANCE     
    });

    new ApplicationListener(scope, "Listener", {
        loadBalancer: lb,
        protocol: ApplicationProtocol.HTTPS,
        certificateArns: ["certificateArn"],
        defaultTargetGroups: [targetGroup]
    });
    
    ecsService
        .loadBalancerTarget({
            containerName: "MobileContainer",
            containerPort: 5000
        })
        .attachToApplicationTargetGroup(targetGroup);
}

function getRepository(scope: cdk.Stack): IRepository {    
    return Repository.fromRepositoryAttributes(scope, "existingrepo", {
        "repositoryName": "mobilerepository",
        "repositoryArn": "arn:aws:ecr:eu-central-1:123456789012:repository/mobilerepository"
    });
}
```

**Comment by hencrice** [comment]
@peterdeme Really appreciate the detailed feedback and providing your workarounds! I will bring this back to the team to discuss.

**Comment by geof2001** [comment]
First off let me apologize if this sounds a bit ranty.  I was looking for this error explicitly though regarding setting up ECS services with existing resources.  I'm just not sure CDK is intended for shops that have already heavily invested in cloudformation.   Importing and using existing resources seems to be as much or more code than is necessary.  Especially with all the required ITypes.  We export a lot of string values already using Cfn exports like sgs, vpcs, subnets, azs, lb's, log groups, clusters, roles and so on.  All of these are just either resource id's or ARN's and I'm finding I have to practically reconstruct resources which were just referable directly in the property as a Fn::ImportValue.  Complex workarounds to essentially refer a property to an IType instead of just a string is bulky to say the least.

I really want to use this tool I'm just finding it hard to justify the learning curve right now when everyone is already familiar with yaml and their pre-existing stack resources.

**Comment by peterdeme** [comment]
Yeah, absolutely, I have similar experience.

**Comment by SomayaB** [comment]
@geof2001 @peterdeme I'm so sorry that has been your experience. This issue is on our radar and we are currently gathering customer feedback so that we can improve the overall experience of migrating from Cloudformation to CDK. Thank you for sharing some of the pain points you've experienced and if you have any more feedback please let us know.

**Comment by nbhirud** [comment]
We use CloudFormation and AWS CLI for creation of resources (CloudFormation when there are multiple things interacting and/or when we need to run a user script or cfn init script to run. CLI when it's a one-off resource which does something and then gets deleted).

Our code is written in Python. We have some shell scripts that get called from the gitlab-ci.yml that create some resources, and some get called from python which trigger creation of these resources. It isn't very intuitive to debug or work with shell scripts along with Python code just for the sake of creating resources in AWS. So I started looking into CDK. Following is my first attempt at creating an RDS instance:

`from aws_cdk import (
    aws_rds as rds,
    aws_ec2 as ec2,
    core as cdk,
    aws_secretsmanager as secretsmanager,
    
)
import datetime

class RDSStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        datetime_postfix = datetime.datetime.now().strftime("%m%d%Y-%H%M%S")
        db_param_group_name = f"parameter-group-postgres13-nik-{datetime_postfix}"

        vpc = ec2.Vpc(self, "TheVPC",
            cidr="10.0.0.0/16",
            
        )
        db_parameter_group = rds.ParameterGroup(
            scope=self,
            id=db_param_group_name,
            engine=rds.DatabaseInstanceEngine.postgres(version=rds.PostgresEngineVersion.VER_13_3),
            description="Postgres13 Parameter Group created using CDK 01",
            parameters={
                "autovacuum": "off",
                "max_wal_senders": "5",
            }
        )
        db_id = "input_db_name"
        user= "imput_dbusername"
        password = "input_dbpassword"
        db_instance_name = f"postgres13-db-instance-nik-{datetime_postfix}"
        db_instance = rds.DatabaseInstance(
            scope=self, 
            vpc=vpc,
            id=db_instance_name, 
            engine=rds.DatabaseInstanceEngine.postgres(version=rds.PostgresEngineVersion.VER_13_3),
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.STANDARD5,
                ec2.InstanceSize.XLARGE4
            ),

            allocated_storage=1000,
            multi_az=False,
            backup_retention=cdk.Duration.days(0),
            removal_policy=cdk.RemovalPolicy.DESTROY,
            parameter_group=db_parameter_group,
            publicly_accessible=True,

            database_name=db_id,
            credentials=rds.Credentials.from_password(username=user, password=cdk.SecretValue(password))
        )
`

And the result was this:

`CDKMetadata	afe746f0-fc38-11eb-ac9d-0a0faac5843d	AWS::CDK::Metadata	CREATE_COMPLETE	-	-
TheVPC92636AB0	vpc-09d71b0c699bd40c5	AWS::EC2::VPC	CREATE_COMPLETE	-	-
TheVPCIGWFA25CC08	igw-0306cd6932324a499	AWS::EC2::InternetGateway	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet1DefaultRouteD1B9E467	rds-s-TheVP-1AQ66MQTZU2G8	AWS::EC2::Route	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet1RouteTableAssociation46F1FFFC	rtbassoc-0244c56a17daf93fb	AWS::EC2::SubnetRouteTableAssociation	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet1RouteTableF6513BC2	rtb-061001c2a37b15acc	AWS::EC2::RouteTable	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet1Subnet571D3690	subnet-0bcb042f0769c4be5	AWS::EC2::Subnet	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet2DefaultRoute52A1F245	rds-s-TheVP-1HP8W6VKD2RKU	AWS::EC2::Route	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet2RouteTable9AC81FAC	rtb-077429c90390b1f91	AWS::EC2::RouteTable	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet2RouteTableAssociation336D47D1	rtbassoc-045c71f05b7b7b8a7	AWS::EC2::SubnetRouteTableAssociation	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet2SubnetCC3D7013	subnet-0c4f784792efa66c0	AWS::EC2::Subnet	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet3DefaultRoute990F9A2A	rds-s-TheVP-1AB68OXHPT9UV	AWS::EC2::Route	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet3RouteTable1A0D1274	rtb-0d4d994e81fef8990	AWS::EC2::RouteTable	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet3RouteTableAssociation50EE5E34	rtbassoc-0a24bafe836c4d6c8	AWS::EC2::SubnetRouteTableAssociation	CREATE_COMPLETE	-	-
TheVPCPrivateSubnet3Subnet69CC2C6F	subnet-0a4717f63299764cc	AWS::EC2::Subnet	CREATE_COMPLETE	-	-
TheVPCPublicSubnet1DefaultRoute6D26543F	rds-s-TheVP-18LR479UF4986	AWS::EC2::Route	CREATE_COMPLETE	-	-
TheVPCPublicSubnet1EIP4412F690	54.234.246.37	AWS::EC2::EIP	CREATE_COMPLETE	-	-
TheVPCPublicSubnet1NATGatewayC61D892B	nat-0e1f8fd9bffe5e5ef	AWS::EC2::NatGateway	CREATE_COMPLETE	-	-
TheVPCPublicSubnet1RouteTable17DA183D	rtb-04445ac815a92b07a	AWS::EC2::RouteTable	CREATE_COMPLETE	-	-
TheVPCPublicSubnet1RouteTableAssociationE5186D77	rtbassoc-08c898cea306d0cce	AWS::EC2::SubnetRouteTableAssociation	CREATE_COMPLETE	-	-
TheVPCPublicSubnet1Subnet770D4FF2	subnet-0892536d0c44c1389	AWS::EC2::Subnet	CREATE_COMPLETE	-	-
TheVPCPublicSubnet2DefaultRouteFEB062B2	rds-s-TheVP-3943IVG2YOR1	AWS::EC2::Route	CREATE_COMPLETE	-	-
TheVPCPublicSubnet2EIP5AAFF9FA	35.171.75.58	AWS::EC2::EIP	CREATE_COMPLETE	-	-
TheVPCPublicSubnet2NATGatewayB437CFAF	nat-0f2f93f2721b2431a	AWS::EC2::NatGateway	CREATE_COMPLETE	-	-
TheVPCPublicSubnet2RouteTable3609F42C	rtb-0d9097975da1f8279	AWS::EC2::RouteTable	CREATE_COMPLETE	-	-
TheVPCPublicSubnet2RouteTableAssociationB4B0A733	rtbassoc-067f84e15bc6f2c55	AWS::EC2::SubnetRouteTableAssociation	CREATE_COMPLETE	-	-
TheVPCPublicSubnet2Subnet73F96DA9	subnet-0738cad998193e4fc	AWS::EC2::Subnet	CREATE_COMPLETE	-	-
TheVPCPublicSubnet3DefaultRoute326CE968	rds-s-TheVP-1HAUQGJQ68X4A	AWS::EC2::Route	CREATE_COMPLETE	-	-
TheVPCPublicSubnet3EIPE3930834	44.197.140.86	AWS::EC2::EIP	CREATE_COMPLETE	-	-
TheVPCPublicSubnet3NATGateway3A4A718F	nat-0c8cc56547f682b62	AWS::EC2::NatGateway	CREATE_COMPLETE	-	-
TheVPCPublicSubnet3RouteTable679ADB47	rtb-0205489cd25202144	AWS::EC2::RouteTable	CREATE_COMPLETE	-	-
TheVPCPublicSubnet3RouteTableAssociationACA3F606	rtbassoc-079adbf3f4081630f	AWS::EC2::SubnetRouteTableAssociation	CREATE_COMPLETE	-	-
TheVPCPublicSubnet3Subnet7C1E748F	subnet-038de04efd2ebeccf	AWS::EC2::Subnet	CREATE_COMPLETE	-	-
TheVPCVPCGWC9B93E30	rds-s-TheVP-LB0I6408JIV7	AWS::EC2::VPCGatewayAttachment	CREATE_COMPLETE	-	-
parametergrouppostgres13nik081320211845413431CB28	rds-stack-new-parametergrouppostgres13nik081320211845413431cb28-byv4i0yo5jtk	AWS::RDS::DBParameterGroup	CREATE_COMPLETE	-	-
postgres13dbinstancenik08132021184541A519B439	rp18nwqrv76ogr8	AWS::RDS::DBInstance	CREATE_COMPLETE	-	-
postgres13dbinstancenik08132021184541SecurityGroup25F305C9	sg-0b037fe2c1ce2a4b7	AWS::EC2::SecurityGroup	CREATE_COMPLETE	-	-
postgres13dbinstancenik08132021184541SubnetGroup0DA12D6E	rds-stack-new-postgres13dbinstancenik08132021184541subnetgroup0da12d6e-1ha114z16qoa	AWS::RDS::DBSubnetGroup	CREATE_COMPLETE	-	-`

The idea of moving to CDK just got tossed out of the window for now because it created 38 resources when what I really wanted was just an RDS instance with a security group. Why can't CDK be as intuitive and smart like Cloudformation? When I watch tutorials about CDK, it is portrayed as a smarter and better way of creating resources over CloudFormation. Well, Cloudformation is precise, and does what it is told to do unlike CDK which thinks it is doing us a favor by being "smart"but it is not.
