### ISSUE TITLE
Add Glue Job and Glue Connection Constructs

### ISSUE THREAD

**Issue by wulfmann** [aws/aws-cdk#5172]
I would like to have glue job and connection constructs added.

### Use Case

I'd like to be able to create glue jobs with cdk using higher level constructs. I would also like to be able to pass references of jobs into other constructs like step functions.

### Proposed Solution

https://github.com/aws/aws-cdk/pull/6948

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @wulfmann, thanks for submitting a feature request and opening a PR, much appreciated! 👍

**Comment by cfrazier91** [comment]
I'd like to second this request! Connections/Jobs are core to Glue and would be great to add  these higher level constructs.

**Comment by wulfmann** [comment]
Sorry this went stale! I've updated a new pr here: #6948 as I deleted the original PR's fork.

**Comment by iliapolo** [comment]
@skinny85 Since you started reviewing the PR a while back, i'm assigning this to you. Feel free to hit it back to me if you need to.

**Comment by humanzz** [comment]
Hello CDK team,

Since the progress on this issue has been slow, I'll attempt to contribute some work here.
As such, I've broken this down into 2 feature requests so that they can be addressed separately. I'll start working on the first one since the PR for Connection has gone stale https://github.com/aws/aws-cdk/pull/6948
1. (aws-glue): Add L2 Connection construct #12442
2. (aws-glue): Add Job L2 construct #12443

**Comment by iliapolo** [comment]
@humanzz Thats awesome, i'm closing this issue in favor of the ones you opened 👍
