### ISSUE TITLE
Config: integ test no longer deploys

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#5181]
The integ test `integ.rule.lit.js` no longer deploys, with the following error:

```
 6/10 | 12:05:07 PM | CREATE_FAILED        | AWS::Config::ConfigRule | Drift (Drift34D3210F) You must create a configuration recorder before yo
u can create or update a Config rule. (Service: AmazonConfig; Status Code: 400; Error Code: NoAvailableConfigurationRecorderException; Request 
ID: 91298256-df71-4409-8d1c-de9de169c5a3)
```

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
@rix0rrr @eladb I think this has always been like that. 

As I did not implement the `AWS::Config::ConfigurationRecorder` and `AWS::Config::DeliveryChannel` (required to enable AWS Config), it can only deploy in an account where this is already setup (which is the case for my account).

(note: this is tricky because those resources are unique per region in an account).

How would you suggest fixing this?

**Comment by eladb** [comment]
Maybe this just means that for now this should only be tested as a unit test and not through an integ test.

As for ConfigRecorder and DeliveryChannel, that's an interesting use case. What happens if you try to deploy two CFN stacks with these resources? Does it fail? 

If these are indeed singletons per environment, maybe we can devise some pattern for such resources. 

Here's a sketch:

1. We expose a construct derived from `Stack` that includes these resources (e.g. `@aws-cdk/aws-config.EnablementStack` <-- really bad name).
2. This stack exports these resource attributes via well known CloudFormation export names.
3. We expose a bunch of constructs that basically just wrap the exports.

The only issue here is how do we print a useful error message to users if these exports are not found. Perhaps we can add something like a context provider that verifies that an export indeed exists in an environment and prints a nice error?

**Comment by rix0rrr** [comment]
This is a recurring pattern that crops up multiple times.

Something similar happens for ServiceLinkedRoles. Sometimes, a ServiceLinkedRole needs to be created to do something (AutoScaling is a prime example, but there are others). 

Sometimes the SLR is automatically created as part of the `CreateXxx` call that needs it, sometimes it's created as part of the `CreateXxx` call if you specify the ARN of the IAM role that the SLR would have gotten, had it existed, sometimes a user needs to create the SLR yourself as a one-time action.

The catch here is that `CreateServiceLinkedRole` is not idempotent: calling it a second time will fail. Calling `DeleteServiceLinkedRole` is potentially not safe because there might be stacks running that still rely on it.

Maybe rolling this kind of "one-time account setup" into `cdk bootstrap` is something that could work.
