### ISSUE TITLE
Generate Class objects from configuration files, json/yaml

### ISSUE THREAD

**Issue by mannickutd** [aws/aws-cdk#5260]
General Information
For the class https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/PolicyDocument.html#aws_cdk.aws_iam.PolicyDocument
There is a way to generate the json for a policy document from an object.
What I am looking for is a way to go the other way.
Eg. I have the json for a policy
```
{
"Version": "2012-10-17",
"Statement": [{"Effect": "Allow", "Action": ":", "Resource":"*"}]
}
```
I want to create the PolicyDocument object from the json.
I find that I am writing boilerplate code for converting from configuration files (yaml) to cdk Classes. Is there already a library out there that does this for me?

 👋 I may be able to implement this feature request
 ⚠️ This feature might incur a breaking change
Proposed Solution
A suitable yaml or json converter for cdk classes where this makes sense. It would also be good to inject string or key value replacements inside the yaml or json configuration files.

Environment
I am looking at the current 1.18.0 version of the library.

**Comment by rix0rrr** [comment]
I'm interested in your use case. Where are the policy documents coming from, and why do you still have to deal with them? In the ideal world, CDK would handle all IAM permissions for you, and I'd like to figure out where the gaps are.

In the mean time, I don't think this is a facility that we will incorporate into the CDK proper. That doesn't mean that someone on the internet (or maybe yourself) couldn't write the code to do what you were asking and share it around for other people to use.

**Comment by michaelmoussa** [comment]
I have a similar need. In my case, the policy JSON already exists (https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.4/docs/examples/iam-policy.json). 

I don't want to have to reproduce that in CDK, nor do I want to add a manual step where it needs to be created ahead of time before running `cdk deploy`. Ideally, I'd like to be able to do something like this:

```typescript
new ManagedPolicy(this, 'AlbIngressControllerPolicy', {
  document: PolicyDocument.fromJson(
    fs.readFileSync('/path/to/local-copy-of-policy.json')
  )}
)
```

That would allow IAM Policy JSON files to be tucked away in a separate directory out of sight, rather than occupying hundreds of lines of the CDK script.
