### ISSUE TITLE
(assertions): Implement getResourcesWithParameter helper function

### ISSUE THREAD

**Issue by ilya-v-trofimov** [aws/aws-cdk#5399]
Implement a helper method `getResourcesWithParameter` which would extract a resource with specific parameter value from the stack being tested

### Use Case

1. When testing stack outputs (being implemented in #1906), one would want to assert an output value. In order to do that, logicalId of resource would need to be obtained from generated stack and provided to `haveOutput` function for evaluation
2. Custom fine grained assertions (other than `haveResource`) would require extracting resource details from the stack and asserting against those. E.g. I extract PolicyDocument of generated IAM role and run it trough `IAM.simulateCustomPolicy()` aws sdk method to validate permissions of that role

### Proposed Solution

Implement `getResourcesWithParameter` helper function which would have:
`@param stackInspector: StackInspector` - to get stack value from
`@param resourceType?: string` - type of cfn resource to search for
`@param paramKey?: string` - resource parameter name to search for
`@param paramValue?: string` - resource parameter value to search for
`@returns ResourceCfn[]` - array of `ResourceCfn` objects (see below)

Implement `ResourceCfn` interface with following parameters:
`@property name: string` - logicalId of resource in cfn stack template
`@property value: any` - resource value in cfn stack template

### Other

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hi @ilya-v-trofimov - 

We have moved our active development from the 'assert' module to the new 'assertions' module, with the intent to deprecate the former in the coming months.

For your second use case, the 'assertions' module provides a `findResources()` method that you can use to find matching resources and extract the properties you need.

For your first use case, since the logical id of the resource is stable in the cdk as long as the construct id and path remain the same, it should be just fine to hard code the logical id in the assertion.

If you still require the logical id, you can use [`stack.resolve`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#resolveobj)`(`[`resource.logicalId`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnResource.html#logicalid)`);`

To get the CfnResource for a higher level construct, you can use the escape hatches as so -

```ts
const cfnresource = resouce.node.defaultChild as CfnResource;
```

Let me know if that satisfies your queries.

**Comment by ilya-v-trofimov** [comment]
Thanks, @nija-at for the update. Yes, looks like `findResources` should cover this feature request.
