### ISSUE TITLE
Can't use CF template generated for EKS cluster using CDK

### ISSUE THREAD

**Issue by tamizharasanr** [aws/aws-cdk#5403]
### The Question

I am working on a CDK app where I have to generate a CF template for an EKS cluster with worker nodes. But when I tried to generate a template it has the asset parameters so I couldn't run the template in cloudformation console. How do I need to solve this issue? In my EKS cluster provisioning pipeline I can't run the CDK CLI directly I have generated cloudformation and run it in the console. 

### Environment

  - **CDK CLI Version:** 1.18.0
  - **Module Version:** ^1.15.0
  - **OS:** Windows 10
  - **Language:** TypeScript

### Other information
Even if i just create bare minimum EKS cluster cloudformation using CDK, It has the asset parameters. Is there any workaround to solve this.
```
new eks.Cluster(this, eksClusterName, {
  clusterName: "test"
})
```

**Comment by eladb** [comment]
We generally do not optimize CDK constructs to be used as stand-alone templates. Assets are a very fundamental part of the CDK and require quite a lot of heavy lifting outside of CloudFormation during deployment

**Comment by XuejiaoZhang** [comment]
@eladb Hi, I have a relevant question to ask. 

We would like to setup an EKS cluster and other resources, in order to implement as Infrastructure-As-a-Code, we built a pipeline using CodeBuild to do `cdk synth` template, and using CloudFormationCreateUpdateStackAction to deploy the entire infrastructure including EKS cluster. We saw the following complaints during the deployment
```
[AssetParameters...ArtifactHash..., AssetParameters...VersionKey...., ...] must have values (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: b2fbf2e8-bea5-4b2e-9a65-32ae5d860005)
```
Do you have any clue to deal with this? And what is the best practice to implement IaC in the above scenario？

Thanks in advance.
