### ISSUE TITLE
Multiple Stack - Reference Lambda function in Stack1 from Stack2

### ISSUE THREAD

**Issue by sacag** [aws/aws-cdk#5467]
This is in regards to .NET CDK. Say if I have 2 stacks(Stack1 and Stack2) defined in my App. If I have to reference a Lambda Function defined in Stack1 from Stack2. How is that possible? Did not find much documentation on it. Any example in C# or explanation on how to solve it would be helpful.

Also, what if the 2 stacks are not really related anyhow? What if Stack2 inherits from Stack1?

**Comment by NGL321** [comment]
Hi @sacag!

Typically we like to keep our issue queue free for bugs/feature-requests, and other issues that must be addressed by the core team rather than community. We direct most other questions to our Gitter and StackOverflow as suggested in the issue template.

However, with regard to your question, I will break the answer down into two parts:
### Cross Stack Resources
Resources can be shared between stacks using custom `StackProps`. These have to be explicitly declared. Below is a codesample demonstrating passing a Lambda function.

- CustProps.cs
``` cs
public class CustProps : IStackProps
{
    public IFunction Function { get; set; }
}
```

- StackOne.cs
``` cs
public class StackOne : Stack
{
    public IFunction CrossStackFunc { get; set; }

    internal StackOne(Construct scope, string id, IStackProps props = null) : base(scope, id)
    {
        CrossStackFunc = new Function(this, "CSFunc", new FunctionProps
        {
            //...
        });
    }
}
```

- StackTwo.cs
``` cs
...
public class StackTwo : Stack
{
    internal StackTwo(Construct scope, string id, CustProps props) : base(scope, id)
    {
...
```

- Program.cs
``` cs
...
var stackOne = new StackOne(app, "StackOne");
new StackTwo(app, "StackTwo", new CustProps 
{
    Function = stackOne.CrossStackFunc
});
...
```

### Nested Stacks
It is possible to nest stacks in the CDK, however it does require you to directly use the Cloudformation construct. There is a good description (in typescript) in the [README](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudformation/README.md), and [here](https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.CloudFormation.NestedStack.html) is the docs link for the C# version.

Hope that helps!
😸

**Comment by sacag** [comment]
Thank you @NGL321 That helps.
