### ISSUE TITLE
Java: unable to import "autoscaling" dependency

### ISSUE THREAD

**Issue by andybirenzi** [aws/aws-cdk#5493]
In the documentation (https://docs.aws.amazon.com/cdk/api/latest/docs/aws-autoscaling-readme.html) they documented how to use the autoscaling but when I add it to pom.xml, I get an error. Following is the synthax :
``` java
<dependency>
            <groupId>software.amazon.awscdk</groupId>
            <artifactId>autoscaling</artifactId>
            <version>1.19.0</version>
</dependency>
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @andybirenzi, thanks for submitting a bug report. Can you fill out the template above so that we can understand the issue better. Thank you!

**Comment by andybirenzi** [comment]
Reproduction Steps:
add following dependency to your pom.xml file 
<dependency>
            <groupId>software.amazon.awscdk</groupId>
            <artifactId>autoscaling</artifactId>
            <version>1.19.0</version>
</dependency>

Error Log:
The container 'Maven Dependencies' references non existing library 'XXXXX\.m2\repository\software\amazon\awscdk\AutoScaling\1.19.0\autoscaling-1.19.0.jar'
Environment: DEV
CLI Version : CDK 11.19.0
Framework Version:
OS :Windows
Language :Java

**Comment by rix0rrr** [comment]
It definitely exists: https://search.maven.org/artifact/software.amazon.awscdk/autoscaling/1.19.0/jar

I don't know why you are getting this error, but it seems to be something on your machine, and not a problem with the CDK. It might be a Maven bug caused by you being on Windows, I see an uppercase character `Autoscaling` in the path you pasted.

Try deleting the entire Maven directory `.m2` and then try it again. Otherwise ask for support on the Maven forum.
