### ISSUE TITLE
Why doesn't ContainerDefinitionProps have port mappings?

### ISSUE THREAD

**Issue by timurista** [aws/aws-cdk#5591]
I would like the ContainerDefinitionProps to optionally expose `portMappings` for use in task definition configuration. this field exists in `ContainerDefinition`

### Use Case

I want to do this
```
    taskDefinition.addContainer(`${DEFAULT_SERVICE_NAME}_container`, {
      image: ecs.ContainerImage.fromRegistry("openpolicyagent/opa"),
      command,
      memoryLimitMiB: 512,
      portMappings: [8181, 8181] // can't do this yet
    });
```
following the example on `@aws-cdk/aws-ecs` page.
It seems like if I create a task definition with container props it should support passing all props needed to create the container. If this already exists would appreciate an example.
Thanks

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hencrice** [comment]
Hey @timurista 
It does look like `ContainerDefinitionProps` only support a subset of the configurations while the rest can be set through a series of `add*` method calls. More specifically, what you were looking for is probably this: https://github.com/aws/aws-cdk/blob/c0a7192c7a3b4a69a0415af679c684f7783c95c8/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L415

Nevertheless, let me check with the team on whether this was intentional.

**Comment by timurista** [comment]
Thanks! Yes I did realize this @hencrice thank you

**Comment by hencrice** [comment]
Perfect! Closing now.
