### ISSUE TITLE
jsii.errors.JSIIError: Cannot read property 'addIncoming' of undefined

### ISSUE THREAD

**Issue by maxsap** [aws/aws-cdk#5598]
While adding a catch clause to a step of a step function state machine, I am getting this message.

### Reproduction Steps
``` py
some_step = stepfunctions.Task(
            self,
            "STEP",
            comment="ANY STEP",
            task=stepfunctions_tasks.InvokeFunction(some_function.handler),
            result_path="$.step_result")

some_step.add_retry(interval=core.Duration.seconds(5), max_attempts=10)
some_step.add_catch(alert_error)
```

### Error Log
```
  File "venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 113, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 288, in invoke
    args=_make_reference_for_native(self, args),
  File "venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 348, in invoke
    return self._process.send(request, InvokeResponse)
  File "venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot read property 'addIncoming' of undefined
```

### Environment

  - **CLI Version      :1.19.0 (build 5597bbe)**
  - **Framework Version:**
  - **OS               :macos**
  - **Language         :Python3.7**

### Other
I have tried passing a Task in the catch clause, I have tried passing a Lambda function, I have tried googling the error but it seems pretty cryptic.

--- 

This is :bug: Bug Report

**Comment by netroy** [comment]
@maxsap can you try changing `.InvokeFunction(some_function.handler)` to `.InvokeFunction(some_function)` ?

**Comment by RomainMuller** [comment]
I believe @netroy is correct here - the argument to `InvokeFunction` is expected to be an `IFunction`, but you're passing it's handler (which is a `string`) instead.

However, since `@aws-cdk/aws-lambda.Function` has no `handler` property, I think you may be using the cloud-formation layer function (or it's `@aws-cdk/aws-sam` counterpart?), so you may not have an `@aws-cdk/aws-lambda.IFunction` instance available...

You can either switch your function to use `aws_lambda.Function(self, 'SomeFunction', ...)` (which implements `IFunction`) -- this is what I'd recommend as if you don't have a reason to do otherwise, or wrap your current function using `aws_lambda.Function.from_function_attributes`.

**Comment by maxsap** [comment]
Hello @RomainMuller, @netroy ,

Thank you for the suggestions, I guess my naming was not accurate as the some_function.handler is an aws_lambda Function.
I have checked again and this still persists even in the latest CDK version (1.21.1 (build 842cc5f))

**Comment by alex9311** [comment]
I'm having the same issue even when passing it as `aws_lambda.Function(self, 'SomeFunction', ...)`
