### ISSUE TITLE
[apigateway] support cognito user pool authorizer

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#5618]
Add support for cognito user pool authorizer - https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html

Upvote this issue if you'd like this feature in the CDK.

----

This is a :rocket: Feature Request

**Comment by 0xdevalias** [comment]
May be worth checking out and subscribing to https://github.com/aws/aws-cdk-rfcs/issues/95 as well.

**Comment by meleksomai** [comment]
Any progress on this feature? Any workaround in the meantime?

Thanks!

**Comment by nija-at** [comment]
@meleksomai - you can use the the construct at the CFN layer - `CfnAuthorizer` - to work around this. However, you will need to configure all of the properties correctly yourself.

**Comment by meleksomai** [comment]
@nija-at , thanks. I have tried without much success.

I am following the current approach which was suggested in the following comment: https://github.com/aws/aws-cdk/issues/723#issuecomment-504753280 and it works. 

I am sharing a sample of the python code which might be helpful to others.

```python
from aws_cdk import (
    core,
    aws_lambda,
    aws_apigateway,
    aws_cognito
)

class CustomStack(core.NestedStack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        
        super().__init__(scope, id, **kwargs)

        #--------------------------------
        # API Gateway
        #--------------------------------
        custom_api = aws_apigateway.RestApi(self, "CustomRestApi",
            rest_api_name='CustomApiGateway'
            )

        # Defines the AWS Lambda resources
        custom_lambda = aws_lambda.Function(
            self, 'CustomHandler',
            runtime=aws_lambda.Runtime.PYTHON_3_8,
            code=aws_lambda.Code.asset('lambda/'),
            handler='post-handler.handler',
        )
        
        # Adding the resource
        custom_api_resource = custom_api.root.add_resource('management')
        
        # Adding the lambda to the resources
        custom_api_method_post = custom_api_resource.add_method('POST', 
            aws_apigateway.LambdaIntegration(custom_lambda, proxy=True)
        )
        
        # API Gateway Cognito Authorizer
        cognito_authorizer = aws_apigateway.CfnAuthorizer(
            scope=self,
            id='CustomCognitoAuthorizer',
            rest_api_id=custom_api.rest_api_id,
            name='CustomCognitoAuth',
            type='COGNITO_USER_POOLS',
            identity_source='method.request.header.Authorization',
            identity_validation_expression="Bearer (.*)",
            provider_arns=[
                'arn:aws:cognito-idp:us-XXXX-X:XXXXXXXXXX:userpool/'
                'us-XXXX-X_XXXXXXXX']
        )
        post_method_resource = custom_api_method_post.node.find_child('Resource')
        post_method_resource.add_property_override('AuthorizationType', 'COGNITO_USER_POOLS')
        post_method_resource.add_property_override( 'AuthorizerId', {"Ref": cognito_authorizer.logical_id})

```

The configuration is deployed but the authorization is not triggered. I am not sure if this is because I have to provide an Oauth scope when using Cognito Authorizer.

**Comment by 0xdevalias** [comment]
Just ran into this need myself, and since native support doesn't seem to exist yet, here was my attempted workaround for JavaScript/TypeScript using `CfnAuthorizer` as suggested above:

References:

- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.CfnAuthorizer.html
  - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.CfnAuthorizerProps.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html
- https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html#apigateway-enable-cognito-user-pool
  - https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html

```typescript
import { AuthorizationType, CfnAuthorizer } from '@aws-cdk/aws-apigateway'
import { UserPool } from '@aws-cdk/aws-cognito'

const userPool = UserPool.fromUserPoolId(this, 'UserPool', userPoolId)

// ..snip..

const cognitoAuthorizer = new CfnAuthorizer(this, 'CognitoAuthorizer', {
      type: AuthorizationType.COGNITO,
      providerArns: [userPool.userPoolArn],
      identitySource: 'method.request.header.Authorization',
      restApiId: api.restApiId,
    })

// ..snip..
```

Unfortunately, when trying to use this in the `authorizer` field of the `MethodOptions` (later in my code, not shown above), I get the following error:

```
TS2741: Property 'authorizerId' is missing in type 'CfnAuthorizer' but required in type 'IAuthorizer'.
```

I noticed that @rrix also provided a more thorough TypeScript-based solution in https://github.com/aws/aws-cdk/issues/9023#issuecomment-658309644 which seems to to implement `authorizerId` / support `IAuthorizer`.

@nija-at Since there seems to be a decently solid looking implementation for this, I'm wondering if we could get an official version of it merged into CDK to save having to use these hacks/workarounds?

**Comment by nija-at** [comment]
> @nija-at Since there seems to be a decently solid looking implementation for this, I'm wondering if we could get an official version of it merged into CDK to save having to use these hacks/workarounds?

@0xdevalias - we absolutely can. This isn't prioritized on our end at the moment, but contributions are welcome :)

**Comment by NukaCody** [comment]
The documentation for API Gateway may need updated or at least reference this issue.

```typescript
books.addMethod('GET', new apigateway.HttpIntegration('http://amazon.com'), {
  authorizationType: AuthorizationType.COGNITO,
  authorizationScopes: ['Scope1','Scope2']
});
```

This doesn't refer to any authorizer id and fails deployment:

```bash
Invalid authorizer ID specified. Setting the authorization type to CUSTOM or COGNITO_USER_POOLS requires a valid authorizer.
```

But with 0xdevalias solution. I was able to get it running.

```typescript
    const userPool = cognito.UserPool.fromUserPoolId(this, 'UserPool', '<user pool id>');
    const cognitoAuthorizer = new CognitoApiGatewayAuthorizer(this, 'CognitoAuthorizer', {
      name: 'CognitoAuthorizer',
      type: apigateway.AuthorizationType.COGNITO,
      providerArns: [userPool.userPoolArn],
      identitySource: 'method.request.header.Authorization',
      restApiId: api.restApiId,
    });

    const authDebug = debug.addResource('auth');
    authDebug.addMethod('GET', new apigateway.HttpIntegration('http://amazon.com'), {
      authorizer: {
        authorizerId: cognitoAuthorizer.authorizerId,
        authorizationType: apigateway.AuthorizationType.COGNITO,
      },
    });
```

**Comment by nija-at** [comment]
@lielran -  https://github.com/aws/aws-cdk/pull/10972
