### ISSUE TITLE
Lambda cannot subscribe to SNS Topic in different region

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#5734]
Déjà-vu. I had this issue already in #4298 but this time I'm using a lambda which should subscribe to a SNS Topic in a different region. This also results in Cloudformation giving me a `Invalid parameter: TopicArn`

This is also discussed here: https://github.com/serverless/serverless/issues/3676

### Use Case

Unfortunately there are quite some use cases since aws provides some "own" topics where users can subscribe to get certain updates about new amis, bounces or in my case new ip address ranges.

```typescript

const amazonIpSpaceChangedTopic = Topic.fromTopicArn(this, 'AmazonIpSpaceChangedTopic', 'arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged')
        const amazonIpSpaceChangedFunction = new Function(this, 'AmazonIpSpaceChangedFunction', {
            runtime: Runtime.PYTHON_3_8,
            code: AssetCode.fromAsset('app/lambda/'),
            handler: 'update_security_groups.lambda_handler',
            vpc: vpc,
            logRetention: RetentionDays.TWO_WEEKS,
            allowAllOutbound: true,
        })
        amazonIpSpaceChangedFunction.addEventSource(new SnsEventSource(amazonIpSpaceChangedTopic))

        const statement = new PolicyStatement()
        statement.addActions('lambda:InvokeFunction')
        statement.addActions('ec2:DescribeSecurityGroups')
        statement.addActions('ec2:AuthorizeSecurityGroupIngress')
        statement.addActions('ec2:RevokeSecurityGroupIngress')
        statement.addResources('*')
        amazonIpSpaceChangedFunction.addToRolePolicy(statement)

```
Just fyi, it's using this lambda function: https://github.com/aws-samples/aws-cloudfront-samples/tree/master/update_security_groups_lambda

But the problem can't be solved within this lambda. It's the lambda making the connection to the SNS topic.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
The workaround for this is to create the [`Subscription`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sns.Subscription.html) class and specify the `region` property as the region of the SNS topic. The values to be passed for the other properties should be similar to what the [`LambdaSubscription` class does](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-sns-subscriptions/lib/lambda.ts#L32-L38).

The fix is to do something similar to what was done for SQS - https://github.com/aws/aws-cdk/commit/3dd194d47b40bd4779b8b242810d3a01ebef9623 - if the topic is imported, the region needs to be extracted and specified as the region for the `Subscription` construct.
