### ISSUE TITLE
CDK typescript dose not  have "ssh-access" feature?

### ISSUE THREAD

**Issue by jialechan** [aws/aws-cdk#5745]
### The Question

```shell
eksctl create cluster \
--name myeks \
--ssh-access \
--ssh-public-key xxx
```
```typescript
const eksCluster = new eks.Cluster(this, 'myeks', {
	clusterName: 'myeks',
	???
}
```
I'm trying to change the eksctl command to TypeScript's cdk code. But it seems that it does not support the ssh-access feature? Is there any solution?
### Environment

  - **CDK CLI Version:** 1.20
  - **Module Version:** 1.20
  - **OS:** Ubuntu
  - **Language:** TypeScript

**Comment by netroy** [comment]
@jialechan 

Since [Cloudformation doesn't support managing EC2 key-pairs yet](https://github.com/aws/aws-cdk/issues/5252), [`eksctl` manages your ssh keys internally](https://github.com/weaveworks/eksctl/blob/c26be94d5fc1c86a0ade9335bc41f49bd24ba439/pkg/ssh/client/ssh.go#L44).

If you can provision a key-pair manually (cli or console), [here is the CDk documentaion](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/README.md#node-ssh-access) on how to use that key-pair to SSH into your worker nodes.

**Comment by jialechan** [comment]
Great! Thanks a lots :)
