### ISSUE TITLE
Integration with java.time.Duration

### ISSUE THREAD

**Issue by ivoanjo** [aws/aws-cdk#5840]
Hello there, dear CDK devs!

### Use Case

In Java 8 the [`java.time.Duration`](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html) class was introduced. Beyond representing an amount of time, it also supports doing math, useful conversions, etc.

But when using the CDK Java api, the CDK provides its own [`software.amazon.awscdk.core.Duration`](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/core/Duration.html) that is extremely anemic, and is very awkward to operate with, e.g. `Duration.seconds(foo.toSeconds().longValue() + bar.toSeconds().longValue()))`.

### A few options for proposed Solution

There's several ways of making this a bit nicer:

* Add overloads to every method that takes a `software.amazon.awscdk.core.Duration` to also support `java.time.Duration`, and mark the former as `@Deprecated`. Java users can just use the native `Duration` class. **I think this would be the nicest.**

* Duplicate a bit more of what  `java.time.Duration` does into `software.amazon.awscdk.core.Duration`, using an api as close as possible. This would at least make it so familiar and featured that it would be less of a pain to use.

* Have an extra constructor of `software.amazon.awscdk.core.Duration` that takes a `java.time.Duration`. This at least allows delaying the conversion into the CDK class to the last possible moment. A bit meh, but would be better than how it is right now.

Thoughts?

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by RomainMuller** [comment]
The class is generated from its TypeScript counterpart, which is blissfully unaware of the Java Time APIs.

I however generally agree with you in principle (with the exception that I would *not* `@Deprecate` the other APIs.

This is however dependent on our ability to declare those other Java methods together with the TypeScript codebase, so that [jsii](https://github.com/aws/jsii) is able to use those when code-generating -- which we happen to have a feature request for already -- aws/jsii#498 -- which I invite you to upvote 😅.
