### ISSUE TITLE
Cognito authorizer support for ecs-patterns/ApplicationLoadBalanced*Service

### ISSUE THREAD

**Issue by schoeneu** [aws/aws-cdk#5849]
ALB supports authentication with Cognito: https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/

But the ApplicationLoadBalanced*Service in ecs-patterns has no easy way to configure a Cognito authorizer. I also could find a way to extract the rule from the construct in order to attach a cognito action as the first action.

### Use Case

Cognito auth is very useful for ALB deployments.

### Proposed Solution

to be honest, I'm not quite sure how to implement this.

### Other

I would also be very happy if there was a workaround, i.e. a way to use the constructed ApplicationLoadBalancedFargateService and then modify it in my stack code to use Cognito auth.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
[This](https://github.com/aws/aws-cdk/pull/5461) should allow you to pass in a load balancer with whatever configuration, but that is dependent on the ELB library supporting Cognito configuration.

**Comment by MrArnoldPalmer** [comment]
@schoeneu let us know if passing your own pre configured load balancer to the constructs works for this case.

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.

**Comment by chelproc** [comment]
@MrArnoldPalmer

Custom load balancers do not work for this use case, because `ApplicationLoadBalancedServiceBase` constructor always adds a listener.
https://github.com/aws/aws-cdk/blob/d38a9e44af184e6e7fa8cde14a84ff2c72cec5f9/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L447

Also, `ApplicationListener` does not allow a change of its default action once it is created, making it impossible to add an authentication rule.

The only way to solve this without modifying outside `aws_ecs_patterns` module seems to quit using `addTargets` in favor of `ApplicationListener#addAction`, which allows full customization of listener rules.

https://github.com/aws/aws-cdk/blob/d38a9e44af184e6e7fa8cde14a84ff2c72cec5f9/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L453

**Comment by vipetrul** [comment]
It is possible to add additional listeners after `const ecsService = new ecs_patterns.ApplicationLoadBalancedFargateService(...)` statement:

```
new elb.ApplicationListenerRule(this, `new-rule`, {
        listener: ecsService.listener,
        priority: 10,
        action: elb.ListenerAction.forward([ecsService.targetGroup]),
        conditions: [elb.ListenerCondition.pathPatterns(...)],
      });
```

**Comment by deuscapturus** [comment]
Escape hatch workaround:

```typescript
    // escape hatch to add Cognito authentication to the listener of ecs-patterns ApplicationLoadBalancedService
    const listener443Cfn = fargateService.loadBalancer.listeners[0].node.defaultChild as CfnListener
    const defaultAction = new AuthenticateCognitoAction({
        next: ListenerAction.forward([fargateService.targetGroup]),
        userPool,
        userPoolClient,
        userPoolDomain,
    })
    listener443Cfn.defaultActions =  defaultAction.renderActions()
```
