### ISSUE TITLE
Route53 updating existing record set

### ISSUE THREAD

**Issue by ivanskof** [aws/aws-cdk#5904]
## :question: General Issue

Is there a way to update existing cname? I'm getting this error 

[Tried to create resource record set [name='xxxx.', type='CNAME'] but it already exists]

This record does indeed exist and it was created manually but I want to update its value using cdk.
Is there a way to  import record sets in cdk?

### Environment

  - **CDK CLI Version:** 1.21.0 (build bf6ab14)
  - **Module Version:** Amazon.CDK.AWS.Route53, Version=1.0.0.0,
  - **OS:** Windows 10
  - **Language:** c#

**Comment by shivlaks** [comment]
@ivanskof - CloudFormation can only manage the lifecycle of resources that are in a stack. Since this resource was created manually outside of CloudFormation, it isn't governed by any stack. The CDK leverages CloudFormation and does not support the use case of modifying resources that were created manually.

We have a [story](https://github.com/aws/aws-cdk-rfcs/issues/84) for adding support for the recently introduced Import feature in CloudFormation that would adopt a resource into a stack. Please be sure to add your use case and upvote it to help us prioritize!

**Comment by shivlaks** [comment]
please reopen if there are any outstanding questions or issues.

**Comment by alramalho** [comment]
What about being able to edit records of a hosted zone that was created within the stack? 
Is there an API to do it?

My use case is basically forcing the `Ns` records to always be the same, even after stack deletion and re-creation (conversely Hosted Zone deletion and recreation)

**Comment by jdavidbakr** [comment]
@alramalho that would work with delegation sets which sets the nameservers to consistent values, but the last I checked (about 2 months ago) CF didn't work with delegation sets.

**Comment by daveharig** [comment]
Same use case here.  FWIW - CF/CDK still does not work with delegation sets.

**Comment by visdxebia** [comment]
I do not get why this issue is marked as closed. Any conclusion?

**Comment by rosmcmahon** [comment]
conclusion is that you cannot modify items created externally to the stack. 

fix: delete the item, recreate in stack
