### ISSUE TITLE
Is deploying to the same AWS account using different CDK versions dangerous?

### ISSUE THREAD

**Issue by joyofdata** [aws/aws-cdk#5909]
Let's assume a situation where multiple developers deploy various stacks from one CDK project to the same AWS account using different CDK versions. Could that break a deployment or even break roll-back-ability in case of an issue?

**Comment by NGL321** [comment]
Hey @joyofdata,

Your scenario is a little too vague to give a comprehensive answer, however I don't think there should be a problem so long as the stacks don't need to share resources.
Since the CDK generates Cloudformation JSON and that output is what is deployed, in the end all the deployed stacks should not be so different from each other. The main difference versions will cause, would come with how non-cfn resources are handled. If those are not shared between stacks, there shouldn't be any issue (it is also possible that shared resources would be fine, but there are scenarios where it COULD break).

Let me know if this is what you were looking for! If your question is more specific, @eladb might be able to offer another perspective.

😸

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
