### ISSUE TITLE
Sort CDK cloudformation output

### ISSUE THREAD

**Issue by ivoanjo** [aws/aws-cdk#5926]
Hello there!

I would like to request that CDK output be sorted.

### Use Case

My team actively looks at the diffs for generated cloudformation JSON for CDK changes as a double-check that our changes are as intended.

Because the CDK output is currently not sorted, small changes between CDK versions or in the order that things are defined in code mean that the output is generated with a different order.

Having the output be sorted means that only real changes would show up on the diffs.

### Proposed Solution

Sort the keys of every object before serializing it.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by richardhboyd** [comment]
Do you want the CFN JSON sorted or do you want the output of `cdk diff` sorted? I can see the value in the latter, the former I am less convinced of.

**Comment by ivoanjo** [comment]
The value of the latter for us is that we don't deploy directly with CDK. I'm from the Amazon CodeGuru Profiler team, and we still need to integrate with a lot of other tooling for our deployment, which means that we end up generating a cloudformation JSON file, which is then handed over to those tools for deployment (aka CDK is not used to deploy, only to define).

But we still very much value diff functionality -- we always include the diff for any CDK changes in our PRs, so that we can doublecheck our changes are as expected.

Of course, our use case may be "weird enough" that you may not want to support it, but since it seems a rather simple change (sort keys before serialize), I gave it a shot and decided to open the feature request.

Feel free to also reach out to me directly if you'd like more details of our use case :)

**Comment by memark** [comment]
I would also like to see the CfnOutputs sorted. Either by default or by some option. We usually output a few URLs (with identical prefixes, e.g. "url1", "url2" etc). Sometimes they're displayed in order, sometimes intermingled with other output.

(It feels almost like a race condition with the outputs order, is that what's going on?)

**Comment by alehatsman** [comment]
I am currently experiencing a bit of frustration with the current diff implementation, it shows for example that the key is removed and added in another position, even when the key name and value didn't change. 

Would be nice if the difference is semantic to avoid cases like on the screenshot. Example of semantic diff app (http://www.jsondiff.com). 

![image](https://user-images.githubusercontent.com/3405704/102788541-0f476700-43a3-11eb-9e41-84800f3b5519.png)

**Comment by ivoanjo** [comment]
Would still be nice to have this...

**Comment by madeline-k** [comment]
Thank you for submitting this feature request, @ivoanjo! After closer examination of the issue by CDK product and development team, there are no plans to implement this in the near feature. This could be a good candidate for a separate tool. If you are still interested in discussing this with the CDK team and community, please open a [discussion](https://github.com/aws/aws-cdk/discussions).

**Comment by madeline-k** [comment]
Hey @aolkin, I was thinking one could build a tool that performs operations on the CDK CLI output. It is possible that wouldn't work or is more trouble than its worth, I haven't fully thought it through.

One of the reasons behind closing this issue is that using the CDK to generate cloudformation templates, and then deploying with a different tool (not CDK CLI or CDK pipelines) is not one of the primary use-cases we are working to support. With such a large volume of feature requests, and potential features, we are closing this one so that we can focus our efforts elsewhere. 

If you want to keep discussing, please open a new issue or discussion. We don't have good visibility on comments on closed issues (we are actually planning to automatically lock comments on closed issues soon to make that more clear).

**Comment by madeline-k** [comment]
Actually, I am seeing now that I didn't fully understand the request here. It's not just to enable the use-case of deploying through a separate tool. We haven't had any reports of the order of output changing in a template like this since 2020, so I'm not sure that that's still happening. If anyone is still seeing this, please open a new issue and we can re-evaluate.
