### ISSUE TITLE
QueueProcessingFargateService does not grant task access to the SQS queue

### ISSUE THREAD

**Issue by wcauchois** [aws/aws-cdk#6051]
### The Question

I recently tried using the QueueProcessingFargateService to create a queue worker, and when my worker started up and I tried to access the queue I got some permission errors. I think it looks like maybe the construct doesn't grant access to the queue to the task that it creates. Intuitively, I would expect it to do this. Should this be fixed or is this desired behavior? As a workaround, I'm calling `processorService.sqsQueue.grantConsumeMessages(processorService.taskDefinition.taskRole)` manually.

### Environment

  - **CDK CLI Version:** 1.19.0 (build 5597bbe) 
  - **Module Version:** @aws-cdk/aws-ecs-patterns@1.19.0 
  - **OS:** OSX Mojave 
  - **Language:** TypeScript

**Comment by iamhopaul123** [comment]
@wcauchois does the issue come up when synthesizing or deploying? Trying to reproduce the issue, could you please attach your code snippet as well?

**Comment by iamhopaul123** [comment]
@wcauchois I reproduced the exception. I think we should fix it by automatically granting the sender task role permission to the queue, so that the queue can have access to the task and can receive messages. Nice catch!

Another follow up question is: do you also expect the pattern to automatically grant the send messages permission and receiver's task role to the queue as well?

**Comment by wcauchois** [comment]
Thanks for looking @iamhopaul123! I mean for my use case right now I'm not granting sendMessage access to my queue processing service, and I think I would not expect that permission -- but I don't feel super strongly about it.
