### ISSUE TITLE
Use Yarn to simplify developer onboarding

### ISSUE THREAD

**Issue by hassankhan** [aws/aws-cdk#611]
Yarn takes care of creating symlinks and bootstrapping the project with its [workspaces functionality](https://yarnpkg.com/lang/en/docs/workspaces/). This should simplify (and hopefully speed up) installing dependencies and getting up and running. It also works well with Lerna - IIRC `lerna.json` just needs a [few additional options](https://github.com/Quramy/lerna-yarn-workspaces-example/blob/master/lerna.json) to get set up.

**Comment by rix0rrr** [comment]
Right now, we are using npm+lerna. In your proposed scenario, would be be using yarn+lerna or only yarn?

What would the advantages of switching be?

**Comment by rix0rrr** [comment]
`link-all.sh` is actually intended for *consuming* the directory tree from other packages--it sets up symlinks so that you can develop on the CDK and consume the modified packages in another project. But it's not very reliable, and some sort of `npm install` or `npm link`-based workflow would probably be better.

It's not part of normal development operation, in any case. And you're right, we're using lerna to manage the intra-repo symlinks right now.

**Comment by eladb** [comment]
I think we should consider yarn

**Comment by amcdnl** [comment]
@eladb - Was this completed?
