### ISSUE TITLE
API Gateway ModelOptions interface should require contentType

### ISSUE THREAD

**Issue by Townsheriff** [aws/aws-cdk#6161]
Cloudformation requires `contentType` to be defined in `ModelOptions`, but in API it is marked as optional.

### Reproduction Steps
```
    const model = new gateway.Model(this, 'Model', {
      restApi: props.resource.restApi,
      schema: {
        schema: gateway.JsonSchemaVersion.DRAFT4,
        type: gateway.JsonSchemaType.OBJECT,
        properties: {
          name: {
            type: gateway.JsonSchemaType.STRING,
          }
        }
      }
    });
```

### Environment

  - **CLI Version      :** 1.22.0 (build 309ac1b)
  - **Framework Version:** 1.22.0
  - **OS               :** MacOS
  - **Language         :** Typescript

### Other

Adding contentType property everything works fine.

--- 

This is :bug: Bug Report

**Comment by richardhboyd** [comment]
I was just independently exposed to this same bug.

**Comment by nija-at** [comment]
Thanks for filing this issue.

It seems that this is because CF has also [marked this property as optional](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-model.html#aws-resource-apigateway-model-properties). Internal reference: i/CFN-30792.

@richardhboyd & @Townsheriff - I think we should keep this property as optional in the CDK and set the default to `application/json` as per what I see in their [API documentation](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/model-create/#contentType). 
What do you both think?

**Comment by richardhboyd** [comment]
I agree with that plan. I am about 84% certain that the Content Type on Models is never enforced/checked anywhere else.
