### ISSUE TITLE
aws-applicationautoscaling - support suspend/resume scaling

### ISSUE THREAD

**Issue by jungseoklee** [aws/aws-cdk#6188]
[Application Auto Scaling supports suspending/resuming scaling](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalabletarget.html)  through `SuspendedState` attribute.

### Use Case

This feature is needed to manage scalable targets through CDK, not CFN.

### Proposed Solution

This feature can be supported by adding `SuspendState` to [`ScalableTargetProps`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-applicationautoscaling/lib/scalable-target.ts#L18-L67) in scalable target.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
@jungseoklee Sounds great!
Want to take a shot at this?

**Comment by kaizen3031593** [comment]
I think we have an opportunity to make this look even better than having to specify `suspendedState` in the constructor. From the [docs](https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-suspend-resume-scaling.html), `suspendedState` is mostly for "making a change or investigating a configuration issue,” which makes me think users will want to have the option to turn on/off this property. Rather than having to specify the suspension in the constructor, I think it would look nice if users could have something like this:

  - `target.SuspendSchedule()`
  - `target.SuspendDynamicScalingIn()`
  - `target.SuspendDynamicScalingOut()`

In the implementation, we could lazily determine what is suspended at `synth` time similar to the `scaleOnSchedule()` implementation. Are there any downsides to this approach?

Also, would customers want to suspend ONLY scaling in or scaling out? Or would it be safe to just have one `target.SuspendDynamicScaling()`?

I'm not sold on this being the better option than exposing `suspendedState` as a property in the constructor but wanted to offer my $0.02.

**Comment by jungseoklee** [comment]
> Are there any downsides to this approach?

No. The approach makes more sense.

> Also, would customers want to suspend ONLY scaling in or scaling out? Or would it be safe to just have one `target.SuspendDynamicScaling()`?

It depends on situation. For example, if a customer tries to avoid availability issue caused by under-provisioning, she might want to suspend scale in only. Hence, it is better to take scaling direction as an input parameter as you did.
