### ISSUE TITLE
Set container's command when using ApplicationLoadBalancedTaskImageOptions

### ISSUE THREAD

**Issue by metametadata** [aws/aws-cdk#6210]
It should be possible to set container's `command` when using `ApplicationLoadBalancedEc2Service` with `taskImageOptions`.

### Use Case

I need this feature because I dislike passing data to container via env vars (as possible with `environment` property of `ApplicationLoadBalancedTaskImageOptions`) and/or hardcode the app execution script in Dockerfile. 

Specifically, I'd like to keep default `CMD ["bash"]` in Dockerfile and then have a flexibility to pass the explicit command programmatically (e.g. `["dumb-init", "/app.sh", <app args>]`).

As a workaround, I can construct `taskDefinition` by hand, but it mostly duplicates the existing code from `ecs-patterns` (setting up logging, port mapping, etc.).

### Proposed Solution

I see 2 solutions:

1) Simply expose the new `command` property in `ApplicationLoadBalancedTaskImageOptions`. Similarly to https://github.com/aws/aws-cdk/issues/4414 where `family` property was added..
2) Redesign the API so that it's possible to change _any_ container property (say, after `ecs.patterns.ApplicationLoadBalancedEc2Service` is instantiated). Otherwise, eventually almost all the properties of `ContainerDefinitionOptions` will need to be duplicated in `ApplicationLoadBalancedTaskImageOptions` as more people will bump into edge cases and issue feature requests similar to the current one.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pkandasamy91** [comment]
@metametadata this was an intentional decision that was made when the construct was defined. As you mentioned, adding every ContainerDefinitionOptions property to the taskImageOptions just doesn't scale, and it makes the creation of the construct much more confusing.

The solution is to create your own TaskDefinition and pass it to the construct with the properties you require specified (any property that is not supported in TaskImageOptions should be passed in this way).

**Comment by pkandasamy91** [comment]
@metametadata I understand how this could be tedious, but this was a conscious decision that was made when the construct was designed. 

As you mention, it doesn't scale to add every `ContainerDefinitionOptions` property to `TaskImageOptions`, and as such, the only way around it is to pass in your own task definitions with the ports configured and logging enabled. Most properties cannot be defined after the construct is created due to the complex nature in which constructs are rendered.

**Comment by metametadata** [comment]
I see, thanks. Too bad 🤷
