### ISSUE TITLE
How to create the resources across aws regions in one stack ? 

### ISSUE THREAD

**Issue by Kiddinglife** [aws/aws-cdk#6242]
Hey friend,
I have a aws pipeline that will deploy stuffs to the regions other than where it locates, which requires the creation of cross-region s3 buckets. Below is the code snippet:
```typescript
    export interface PipelineProps extends CDK.StackProps {
     deploy: {stage: 'dev' | 'qa' | 'uat' | 'prod', regions:string[]},
     github: { owner: string, repository: string, tokenName: string }
    }

    let myCrossRegionReplicationBuckets: { [region: string]: S3.IBucket; } = {}
    for (const reg of props.deploy.regions) {
      myCrossRegionReplicationBuckets.reg = new S3.Bucket(this, `${reg}-pipeline-bucket`, {
        versioned: true, 
        encryption: S3.BucketEncryption.S3_MANAGED
      })
    }
    const pipeline = new CodePipeline.Pipeline(this, id, {
      crossRegionReplicationBuckets: myCrossRegionReplicationBuckets,
      restartExecutionOnUpdate: true,
    })
```
I noticed CDK.StackProps has a filed of env that includes one accountId and **one region**. 
My question is: Is there a way to create the buckets in the regions defined in `props.deploy.regions` instead of that defined in `props.env.region`? 

thanks.

**Comment by richardhboyd** [comment]
short answer: you can't. 

long answer: when you deploy a stack it is deployed to CloudFormation in a specific region, that region is where resources are created.

**Comment by deleugpn** [comment]
@richardhboyd would you mind expanding on that? 

- AWS CodePipeline supports cross-region deployment
- AWS StackSets offer cross region deployment of CloudFormation
- Recently AWS announced AWS Organization StackSet (cross-account & cross region)

I may be completely off base here since I'm not using CDK yet, but I get the impression that CDK is an abstraction layer on top of CloudFormation to make it easier and OOP-driven. Why would CDK be against building a cross-region deployment pipeline since CloudFormation itself supports creating an AWS CodePipeline that does exactly that?

**Comment by richardhboyd** [comment]
AWS CodePipeline supports cross-region deployment by deploying a specific stack in a specific region. If you wanted to deploy the same stack to multiple regions in CodePipeline, you would have to create 1 deployment action per region you wanted to deploy to.

AWS CloudFormation StackSets deploy a copy of each stack to each region, therefore each region has its own stack.

AWS Organization StackSets operate on the same principle as CloudFormation StackSets, just with some additional automation built in at the account creation process.

It is not possible to update resources across multiple regions with a single stack. I think its important to note the difference between "updating RegionA from RegionB" (well supported) and "updating RegionA and RegionC as an atomic transaction fromRegionB" (actively discouraged)

**Comment by deleugpn** [comment]
@richardhboyd thanks for that, I know understand and agree with what is discouraged!!

**Comment by SomayaB** [comment]
Closing this issue since it seems to have been resolved. Feel free to reopen if that's not the case.

**Comment by riesje007** [comment]
Hello, I truly believe that creating resources in multiple AWS regions is not an anti-pattern. I think one should look from AWS architecture viewpoint and it is perfectly plausible to have two buckets in different regions for which you want to implement for example Cross Region Replication. This can currently not be done, because it is called an 'anti-pattern'.
And what if you want to create a multi access point together with a few buckets in different regions? For this kind of cross region functionality that is supported by AWS, the CDK is unfortunately lacking.

**Comment by jeromevdl** [comment]
Just a simple example, try to deploy CloudFront / Waf / Lambda@edge... Unless you deploy everything in us-east-1, it's a mess to do.

**Comment by riesje007** [comment]
I see.

**Comment by timothy-cloudopsguy** [comment]
Exactly @jeromevdl ... I just got hit by this error when trying to create an S3 bucket and throw it behind CloudFront in Ohio (us-east-2) region. Why on earth does CloudFront force you to use a specific region for SSL certs?  But anyways, this is a case where it's utterly foolish to be forced to create a new stack and deploy that stack into a different region for a single resource to play nicely with CloudFront....

```
AWS::CloudFront::Distribution: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.
```
