### ISSUE TITLE
Add indexes to dynamodb.Table.fromTableAttributes

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#6392]
Right now, we don't allow passing indexes to [`dynamodb.Table.fromTableAttributes()`](https://github.com/aws/aws-cdk/blob/bb68f7c3f694e1be2d6f6ed7ab6ebc3704a4e0d1/packages/%40aws-cdk/aws-glue/lib/table.ts#L168-L168). This means that methods like `grantRead` do not include the stream ARN for these Tables, even if in reality they have streams enabled.

We should add optional properties `localIndexes?: string[]` and `globalIndexes?: string[]` to [`TableAttributes`](https://github.com/aws/aws-cdk/blob/bb68f7c3f694e1be2d6f6ed7ab6ebc3704a4e0d1/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L303-L303). This should also allow us to add a bunch of methods to the `ITable` interface that were thus far only available on `Table`, like [`autoScalReadCapacity()`](https://github.com/aws/aws-cdk/blob/bb68f7c3f694e1be2d6f6ed7ab6ebc3704a4e0d1/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L772-L772).

See [this comment and below](https://github.com/aws/aws-cdk/pull/1564#issuecomment-572381796) for more context why is this needed.

**Comment by balkat** [comment]
The ITable grant thing is also causing us problems.    We are instantiating an ITable via Table.fromTableArn().   When we do this, permission grants to lambda functions do not include the extra entry for the indexes in the Resource:

Using the Table construct we get e.g.:
```
            "Resource": [
                "arn:aws:dynamodb:us-east-1:REDACTED:table/VCS-UserData-vc-dev-Sea88E64FB3-TID62DP6LMCV",
                "arn:aws:dynamodb:us-east-1:REDACTED:table/VCS-UserData-vc-dev-Sea88E64FB3-TID62DP6LMCV/index/*"
            ],
```

When using Table.fromTableArn() we do not get the second line and any operations on the indexes are denied.

We also had to make changes elsewhere because ITable does not offer the grantFullAccess() method.

**Comment by ben-p-n** [comment]
This is a bit of a blocker for us also - are there any plans to get this added?
