### ISSUE TITLE
Multi-/Cross-Account support

### ISSUE THREAD

**Issue by Pinny3** [aws/aws-cdk#6470]
I wonder if there is a way to support cross-account cross-reference stacks with cdk.

### Use Case

- Create a route53-hosted zone in one account (Account A)
- Reference the route53-hosted-zone from Account A in the hosted zone in a second account (Account B ) using a ZoneDelegationRecord.

Example in Account B:

>         new route53.ZoneDelegationRecord(this, 'delegation', {
>             nameServers: subRoute53Zone.hostedZoneNameServers || defaultNS,
>             zone: route53Zone
>         })

subRoute53Zone is the Hosted Zone from the stack in Account A.

### Proposed Solution

If there is a way to do this, may you please provide me with an example. If not, is it planned to support this in the near future.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by philippkanne** [comment]
+1

**Comment by skinny85** [comment]
@Pinny3 thanks for opening the issue. There is actually a mechanism to do this in the CDK, and it uses physical names of the resources to establish the cross-account link. Unfortunately, since the physical name of a Hosted Zone cannot be determined before it's deployed (it has an auto-generated identifier assigned to it), we cannot perform this sort of reference easily. Sorry about that.

**Comment by Pinny3** [comment]
@skinny85 Thanks for the fast answer.

One additional question to clarify: 

What do you mean with "There is actually a mechanism to do this in the CDK, and it uses physical names of the resources to establish the cross-account link"?

Maybe you have an example for this so we can try it with another example.....

Thank you in advance for your help.

**Comment by skinny85** [comment]
Sure. A good example is CodePipeline.

Actions in CodePipeline can span AWS accounts. So, we have logic that allows you to do something like this (the example will be an Action that deploys to an S3 Bucket that is in a different account than the CodePipeline itself):

```ts
const bucketStack = new Stack(app, 'BucketStack', { account: 'bucket-account' });
const bucketToDeploy = new s3.Bucket(bucketStack, 'DeployBucket', {
  bucketName: 'my-bucket', // this is the physical name, and it is required in this case
});

const pipelineStack = new Stack(app, 'PipelineStack', { account: 'pipeline-account' });
const pipeline = new codepipeline.Pipeline(pipelineStack, 'Pipeline', { ... });
const deployStage = pipeline.addStage('Deploy');
deployStage.addAction(new codepipeline_actions.S3DeployAction({
  actionName: 'S3Deploy',
  input: someOutput,
  bucket: bucketToDeploy, // this is a Bucket from a different account!
});
```

The CodePipeline construct has some logic inside of it that detects the fact that the bucket used in the `S3DeployAction` is from a different account, and adds some resources needed for this case to work correctly.

The key part here is that we require `bucketToDeploy` to have a physical name (the `bucketName` property in case of S3 buckets). This is what allows the CodePipeline construct to correctly wire everything together across the 2 accounts (were things like CloudFormation outputs and imports do not work across accounts)

However, since that's not possible for `HostedZone` (its physical name cannot be set, it's autogenerated when it's deployed), we cannot use the same mechanism in the case that you're asking.

Does this make sense @Pinny3 ?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.

**Comment by mark-ashton** [comment]
The use-case by pinny is actually exactly what I'm trying to solve right now:
We have Route 53 in one (production) account which manages the DNS for the apex domain (example.com), and in another account (sandbox) we are creating new subdomains for our service (dev.example.com).
Currently using the CDK I can create a new HostedZone for dev.example.com, and on an `ApplicationLoadBalancedFargateService` set the DomainZone to that new HostedZone to add the records needed to route to the ELB on api1.dev.example.com.
The missing step for me is how to set NS records on the production account for the new HostedZone of dev.example.com using the CDK and ZoneDelegationRecord looked like it was the tool for the job, apart from the cross-account problem.

**Comment by jackgraves** [comment]
Hi, we also require the capability of using a HostedZone from another Organisation Account, but this doesn't seem to currently be supported by the current implementation.

Is there a workaround or solution to this - moving the HostedZone to the other Organisation Account is not an option for us.

Would adding a 'fromHostedZoneArn' be possible?

**Comment by OperationalFallacy** [comment]
@skinny85 do you think it would be possible to use Codepipeline variables for this?
There is ~128kb total space available for all vars combined according to pp limits docs.
Should be enough to pass around stacks outputs. I'm trying to find an example of how to do it in the pipeline without too much customization. Has anybody done something like this with pp variables?

**Comment by skinny85** [comment]
@OperationalFallacy  Not straightforwardly - you can see [in the documentation](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html#reference-variables-list-defined) that none of the CloudFormation actions produce varaibles.

_However_, you can do a similar trick by using files - you can write out the [Outputs of the Stack into a file](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CloudFormationCreateUpdateStackActionProps.html#outputfilename), and then pass an CodePipeline Artifact containing the file to a different Action, and read it from there.

Here's an example you can use for a jumping-off point: https://github.com/NetaNir/meerkats/blob/9c7a66d99db9b650f1fc22d97340d0c9d072877a/lib/pipeline-stack.ts#L93-L111

**Comment by OperationalFallacy** [comment]
@skilbjo Thanks for the example, that's exactly where I got so far with my experiments. I got a stage producing multiple outputs from multiple CF deployed in parallel, this is because route53 subdomains gets creates in multiple accounts.

Just need to figure out how programmatically get these outputs in an action, without specifying list or output names in advance. Then massage outputs, get zones, pass it to the next cdk synth and it is done...

**Comment by girotomas** [comment]
Why is this issue closed ? I am experiencing this problem with the CDK. 

I am using a hosted zone for which I know the address in one account and I want to deploy a Api gateway on another which references the Hosted Zone in another.

**Comment by fr-an-k** [comment]
I have the same issue; how do I tie API gateway with a custom domain (in another account's hosted zone) without increasing cost/complexity?
I could update the records separately to point to the endpoints of the other account, but would that work?
And is it possible to create a free custom domain certificate for API gateway using the hosted zone in another account?

**Comment by MaxTran96** [comment]
i have the same issue, i would like multiple account to share a hosted zone resource. i.e api.example.com and api-beta.example.com. I'm reopening this
