### ISSUE TITLE
Lambda function is not grantable

### ISSUE THREAD

**Issue by aflinton** [aws/aws-cdk#6744]
cdk --version
1.28.0 (build 5f2bbc6)

Lambda function does not seem to be grantable any more 
e.g. 
``` ts
MailboxesTable = dynamodb table

const GenerateCheckLambda = new lambda.Function(stack, 'GenerateCheckLambda', {
```
Grant Read data to it:
```console
error TS2345: Argument of type 'Function' is not assignable to parameter of type 'IGrantable'.

625   MailboxesTable.grantReadData(GenerateCheckLambda);
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
`Function` implements `IFunction` and `IFunction` extends `IGrantable`.

I would guess that something is wrong with your set up. Check if all of the CDK dependencies you have taken are the exact same version by looking at `yarn.lock` or `package-lock.json` files.

**Comment by nija-at** [comment]
If you still have this issue, please provide a full CDK app that generates this error.

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.

**Comment by benchislett** [comment]
Ran into this issue today.
As it turns out, I had a version mismatch; I was using `1.81.0` for all packages except `@aws-cdk/aws-dynamodb`, which was `1.82.0`. The error message was something along the lines of:

```
The types of 'grantPrincipal.addToPolicy' are incompatible between these types.
...
Types of parameters 'statement' and 'statement' are incompatible.
...
```

For those in the future, double-check your `package.json` and/or `package-lock.json` to make sure you're using the same version across the board.
