### ISSUE TITLE
AppSync: additionalAuthorizationModes property type documentation

### ISSUE THREAD

**Issue by oleh-kolinko** [aws/aws-cdk#6773]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-appsync.AuthorizationConfig.html

property: additionalAuthorizationModes?
**type: json**

In [typescript implementation ](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-appsync/authorizationconfig.html) type is not json
property: additionalAuthorizationModes?
**type: [AuthMode]**

---

This is a 📕 documentation issue

**Comment by 0xdevalias** [comment]
Similar/related to this, `AuthMode` doesn't actually list any of the relevant modes:

- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-appsync.AuthMode.html

Looking at the source:

- [`export interface UserPoolConfig extends AuthMode {`](https://github.com/aws/aws-cdk/blob/v1.31.0/packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts#L31)
- [`export interface ApiKeyConfig extends AuthMode {`](https://github.com/aws/aws-cdk/blob/v1.31.0/packages/@aws-cdk/aws-appsync/lib/graphqlapi.ts#L58)

Though they do have their own pages:

- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-appsync.ApiKeyConfig.html
- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-appsync.UserPoolConfig.html

It would be nice if they were linked from the main [`AuthMode`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-appsync.AuthMode.html) page though, for easier discoverability.

**Comment by AbdoNile** [comment]
Hi , Any Updates or solution for this ?

**Comment by MrArnoldPalmer** [comment]
@AbdoNile since AppSync is currently an experimental module, most of the contributions have been from the community. This one should be pretty simple if you're inclined to submit a PR. Otherwise someone from the core team will get to it when the AppSync module gets prioritized for stabilization, along with other issues in the module.

**Comment by andreascasen** [comment]
Specifying a different default auth mode doesn't seem to work. It somehow still defaults to API KEY.

**Comment by BryanPan342** [comment]
I believe this has been fixed? I dont see any discrepancies between the source code and the docs anymore unless I'm missing something.

I believe the disucssion on AuthMode is deprecated because implementation is now that `UserPoolConfig` and `ApiKeyConfig` are standalone interfaces. 
https://github.com/aws/aws-cdk/blob/d30fa9dda0726230f077c181833fddd40450d6ae/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L86
https://github.com/aws/aws-cdk/blob/d30fa9dda0726230f077c181833fddd40450d6ae/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L108

@andreascasen what error are you getting? If you could open up an issue and tag @aws-cdk/aws-appsync that would be great!
