### ISSUE TITLE
Need support for autoscaling for NetworkTargetGroup on Fargate Service

### ISSUE THREAD

**Issue by jefersonlopessage** [aws/aws-cdk#6887]
## :question: General Issue

I am currently using the network load balance together with my ECS Cluster, but when trying to add the auto scaling rule to a **ForgateService** using **ScaleOnRequestCount**, the target group **NetworkTargetGroup** is not supported in the **RequestCountScalingProps.TargetGroup** property, only the **ApplicationTargetGroup** is supported.

My doubt is, it is a limitation of the CDK or ECS architecture.

```
FargateService.AutoScaleTaskCount.ScaleOnRequestCount('serviceName-scaling-count', new RequestCountScalingProps
{
   DisableScaleIn = true,
   RequestsPerTarget = 100,
   ScaleInCooldown = Duration.Seconds(5),
   ScaleOutCooldown = Duration.Seconds(5),
   PolicyName = $"{service.Name}-scaling-count-policy",
   TargetGroup = <NetworkTargetGroup>
});

```

### Environment

  - **CDK CLI Version:** 1.28.0
  - **Module Version:** 
  - **OS:** Windows 10
  - **Language:** C#

**Comment by kohidave** [comment]
Well your doubt is mostly right - this is an architectural limitation - but not of ECS or the CDK - but just of the types of metrics NLBs emit. Here's a [list](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html) of metrics. Since the NLB runs at the TCP layer, there's not as clear of an analog for requests. 

In the short term, I think the `ActiveFlowCount` matches closest with Request Count - so you can use the [scaleOnMetric](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.AutoScalingGroup.html#scale-wbr-on-wbr-metricid-props) method to scale on `ActiveFlowCounit`. 

In the medium term, I'll try to get a consensus on the best metrics to create a function like `ScaleOnRequestType` for NLBs.

**Comment by jefersonlopessage** [comment]
Thanks @kohidave i'll be waiting.

**Comment by aorinevo** [comment]
Any updates on this issue?
