### ISSUE TITLE
Add ability to add to existing dashboard

### ISSUE THREAD

**Issue by michaelwiles** [aws/aws-cdk#6890]
Firstly, if this is possible please let me know how.

I want to be able to allow other stacks add to an existing dashboard.

I have tried the usual approach of exporting name (all I've got to export is the dashboard's toString.

I do this but then in the dependent stack I can't see the ability to acquire a reference to a stack via the familiar: from method (Topic.from_topic_arn for example).

### Use Case

I want to create a main dashboard in my "parent" stack - and then let other stacks register metrics on it.

I guess this is not supported by cloudformation so cdk won't be able to support it either.

### Proposed Solution

Add the ability for stacks to garner a reference to an existing dashboard.

I guess the alternative is to have one stack that creates the various metrics. Problem is that this stack needs to know about all the other stacks... and that would be quite challenging.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Adding to an existing dashboard outside your CDK application will never be possible, simply because CloudFormation does not support it (nor is it likely to).

If the dashboard is created inside your application, you can pass the `Dashboard` object around and have constructs add themselves to it. Be aware this will imply a stack dependency.

----

We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.

**Comment by michaelwiles** [comment]
yes, that is what I was worried about.
