### ISSUE TITLE
"template-deps-to-dot" doesn't recognize "Fn::Sub" tags

### ISSUE THREAD

**Issue by miparnisari** [aws/aws-cdk#6956]
https://github.com/aws/aws-cdk/blob/c298a7c424cc47f94da043bc8a785afb149fc4b6/scripts/template-deps-to-dot#L139-L142

The code should also take into account `Fn::Sub` tags.

BTW: In [cfn-lint](https://github.com/aws-cloudformation/cfn-python-lint/pull/1411) we're [working towards exposing a ` --build-graph` option](https://github.com/aws-cloudformation/cfn-python-lint/pull/1411) that would create a DOT file like this script is doing :)

**Comment by rix0rrr** [comment]
You are correct, and it doesn't do that since we weren't emitting `{ Fn::Sub }` tags anyway so I didn't see any point in supporting them. We could add it, but the script was a tool for investigating some issues in some generated templates at the early stages of CDK.

It's not really part of the product, as such, and the only guarantee you get is that it will take up space on your disk :).

Thanks for the report and the interest, but I'm going to close this bug as not actionable.

**Comment by miparnisari** [comment]
FYI [cfn-lint 0.29.4](https://github.com/aws-cloudformation/cfn-python-lint/releases/tag/v0.29.4) now supports exporting the template to a DOT file :)
