### ISSUE TITLE
software.amazon.awscdk.core.Tokenization.reverseString(String) throwing exception

### ISSUE THREAD

**Issue by com-tr-sitzman-lyle** [aws/aws-cdk#6978]
When I upgrade from 1.28.0 to 1.30.0 and the java method software.amazon.awscdk.core.Tokenization.reverseString(String) method started throwing the following exception.

```
Exception in thread "main" java.lang.ClassCastException: class software.constructs.TokenizedStringFragments cannot be cast to class software.amazon.awscdk.core.TokenizedStringFragments (software.constructs.TokenizedStringFragments and software.amazon.awscdk.core.TokenizedStringFragments are in unnamed module of loader 'app')
        at software.amazon.awscdk.core.Tokenization.reverseString(Tokenization.java:73)
```

The value that is a logical id reference such as the following.

```
${Token[org-main-dev.AssetInsightId.LogicalID.10]}
```

### Reproduction Steps

```
String tokenizedLogicalId = cfnElement.getLogicalId();
TokenizedStringFragments tokenizedStringFragments = Tokenization.reverseString(tokenizedLogicalId);
```

### Error Log

```
Exception in thread "main" java.lang.ClassCastException: class software.constructs.TokenizedStringFragments cannot be cast to class software.amazon.awscdk.core.TokenizedStringFragments (software.constructs.TokenizedStringFragments and software.amazon.awscdk.core.TokenizedStringFragments are in unnamed module of loader 'app')
        at software.amazon.awscdk.core.Tokenization.reverseString(Tokenization.java:73)
```

### Environment

  - **CLI Version      :** 1.30.0
  - **Framework Version:** 1.30.0
  - **OS               :** Windows 10
  - **Language         :** Java

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@RomainMuller can you take a look? (jsii?)

**Comment by RomainMuller** [comment]
It does look like multiple different versions of the CDK library coexist in this runtime. Can you check your class path to identify the exact versions of CDK libraries in your runtime?

**Comment by RomainMuller** [comment]
Ho wait no - it appears to be an issue caused by a clash between `constructs` and `@aws-cdk/core`

**Comment by eladb** [comment]
@RomainMuller yes I see that there is a clash but what should @com-tr-sitzman-lyle do?

**Comment by RomainMuller** [comment]
There is no user land fix that will make Java happy. The problem is there are two versions of `global.__cdkTokenMap` conflicting with each other... The one that'll be effectively in use is the one from `constructs`, but the one that will be shown statically is the one from `@aws-cdk/core`.

Unfortunately, we'll need to fix this in a subsequent release before Java (and likely C#) can enjoy this feature again.

**Comment by RomainMuller** [comment]
The offending code basically comes from these contexts:

https://github.com/aws/aws-cdk/blob/497f63e1884885c5647f08438199c38a89668e24/packages/%40aws-cdk/core/lib/private/token-map.ts#L7

https://github.com/aws/constructs/blob/aa181929a1ca5d72350ee621ca69827113772a80/lib/private/token-map.ts#L7

Use of `global` and the fact the `__cdkTokenMap` key is "shared" between the two modules create the situation where the first loaded library "wins" over the other.

It works okay in TypeScript because the types are structurally equivalent (so TypeScript is happy with one signature satisfying the other). But Java and C# disagree with this as they don't do structural typing.
