### ISSUE TITLE
The use of replacement variables like '#{var}' is not possible in the cdk to use with resource identifiers, making it impossible to use one single template for a deployment pipeline. 

### ISSUE THREAD

**Issue by begoloz** [aws/aws-cdk#7000]
### The Question

How to use variable replacement on the output templates from the stacks of the cdk, when the resource identifiers or fields like the dashboardName do not allow or remove characters like #{ }, necessary  for tools like [octopus ](https://octopus.com/docs/projects/variables/variable-substitutions)to reference variables assigned during pipeline deployment, which are specific to the stage/environment of delivery, like dev, test or prod ?
E.g. 
DashboardName = 'Dashboard-#{environmentVariable}'
and in the deployment pipeline:
#{environmentVariable} would be replaced for values like  'dev', 'test', 'prod'. 
      
### Environment

  - **CDK CLI Version:**  1.22.0
  - **Module Version:**  1.31.0
  - **OS:** Windows
  - **Language:**  TypeScript

### Other information

I think being able to assign identifiers to the resourses at the moment of deployment is important for a pipeline delivery, and using a single template that can be deployed in different stages.

With changes like [Fixes #2976 ](https://github.com/aws/aws-cdk/issues/2976), it is not possible to assign the DashboardName a replacement variable for pipeline deployment. 
I think the name should be able to accept characters like #{ }, for cases when its necessary to add a reference to things like deployment-environment variables to name the construct. 
The current DashboardName string validation forces the deployment of multiple static Cloud Formation templates, each one specific to a deployment-environment, only to be able to have names that are environment specific. Instead a better approach would be to have a single template that can be deployed in each environment resulting in dashboards that can be created with names that reference their deployment-environment.

**Comment by eladb** [comment]
Is this specifically about dashboard names? Can you provide a minimal repro please?

**Comment by rix0rrr** [comment]
Looks like you are planning to use CDK as a template generator which you intend to run through a template processor, am I getting the use case right?

I'm not sure we want to go to disabling our validations for the minority of people who intend to run the template through a processor, rather than deploy it directly.

We expect the CDK program itself to fill the function of the template processor. 

> and using a single template that can be deployed in different stages

We generally don't recommend doing this. Instead, trust the CDK app to generate 10 templates for 10 stages that only differ in the way you expect them to differ. If you must use a single template, use CFN parameters.

If you really want to use your own template preprocessor, I recommend using magic strings that pass through the CDK validators unharmed (`xxxVARxxx`) and using text substitution to replace those with `#{var}` so that your template processor will interpret them as you desire.

**Comment by rix0rrr** [comment]
Closing
