### ISSUE TITLE
Why is package.json version set to 0.0.0????

### ISSUE THREAD

**Issue by mikegwhit** [aws/aws-cdk#7030]
### The Question

Just was checking that we are on latest CDK version and find that your package.json lists version 0.0.0???  This can't be intended can it?

If for some reason this is intended, where do we find latest version information?

**Comment by MrArnoldPalmer** [comment]
hey @mikegwhit. All of package.json files in the source code have the version "0.0.0" to help reduce noise in release bump PRs and when merging the release branch back to master. We have [a script that changes all of these to the new version number](https://github.com/aws/aws-cdk/blob/master/scripts/align-version.sh) before we publish. Because of the number of packages within the repo and dependencies between modules within the repo, a PR to bump the version number involved hundreds of file changes and often merge conflicts.

You can see the difference between PRs in [one of the older releases](https://github.com/aws/aws-cdk/pull/6384) and [one after changing to this strategy](https://github.com/aws/aws-cdk/pull/6986/files).

When looking at the source code, you can see the current version in [lerna.json](https://github.com/aws/aws-cdk/blob/master/lerna.json#L13). The published artifacts should also have the current versions in their package.json. For example, [the v1.31.0 package.json on npm.](https://unpkg.com/aws-cdk@1.31.0/package.json)

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
