### ISSUE TITLE
Consolidated cross-account resource stack

### ISSUE THREAD

**Issue by CaerusKaru** [aws/aws-cdk#7080]
Currently `aws-codepipeline-actions` has a utility that enables generating resources for cross-account deployments. It does this by creating a stack in the necessary account that the CDK can deploy to setup the resources for later use.

However, if people writing other constructs wish to take on likewise actions, for say cross-account DNS delegation, they are stuck needing to duplicate the logic for that package, leading to two separate stacks for the same account (with the same goal in mind – cross-account resources).

I'm proposing creating a utility, possibly a static method on the `Stack` class that can return the resource stack for cross-account/cross-region purposes.

### Use Case

I'm writing a cross-account DNS domain delegation construct that would benefit from not duplicating this logic.

### Proposed Solution

Something like this:
```ts
public static external(app: App, accountNumber: string, region: string): Stack;
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by CaerusKaru** [comment]
cc @skinny85 @eladb

**Comment by eladb** [comment]
I am trying to wrap my head around the proposed API. Can you provide a more complete example?

**Comment by CaerusKaru** [comment]
Something like this:
```ts
const otherAccountStack = Stack.external(this.node.root, '12345678', 'us-west-2');

const roleId = 'DelegateHostRole';
const hostRole: Role = otherAccountStack.node.tryFindChild(roleId) as Role | undefined || new Role(otherAccountStack, roleId, {...});
```

**Comment by workeitel** [comment]
Some ideas for the interface.

# 1. Same CFN stack (already works)

    const parentZone = new route53.PublicHostedZone(this, "TopZone", {
      zoneName: "someexample.com"
    });

    parentZone.addDelegation(new route53.PublicHostedZone(this, "SubZone", {
      zoneName: "sub.someexample.com"
    }));

# 2. Same account and region (already works)

It uses CFN import/export to pass route53 zone id

stack 1

    zone = new route53.PublicHostedZone(this, "TopZone", {
      zoneName: "someexample.com"
    });

stack 2

    const subZone = new route53.PublicHostedZone(this, "SubZone", {
      zoneName: "sub.someexample.com"
    });

    new route53.ZoneDelegationRecord(this, "delegate", {
      nameServers: subZone.hostedZoneNameServers!,
      zone
    });

# 3. Same account different region (already works)

zone id passed via cdk context

stack 2

    const subZone = new route53.PublicHostedZone(this, "SubZone", {
      zoneName: "sub.someexample.com"
    });

    new route53.ZoneDelegationRecord(this, "delegate", {
      nameServers: subZone.hostedZoneNameServers!,
      recordName: "sub.someexample.com",
      zone: route53.PublicHostedZone.fromLookup(this,
        "TopZone",
        { domainName: "someexample.com" },
      )
    });

# Variant 4.1. Different account - delegation by parent zone (New)

Hosted zone name servers needs to be passed from stack 2 to stack 1. Stack 1 puts delegation in place.

Downside: First Stack 2 needs to be synth but the hosted zone does not work yet because it can't be resolved (like for ACM DNS validation). Then Stack 1 needs to be deployed to put delegation in place. That creates an annoying dependency.

stack 1

    const parentZone = new route53.PublicHostedZone(this, "TopZone", {
      zoneName: "someexample.com"
    });

    new route53.ZoneDelegationRecord(this, "delegate", {
      nameServers: [...], // Needs to get the nameServers from stack 2 somehow
      zone
    });

stack 2

    new route53.ZoneDelegationRecord(this, "delegate", {
      nameServers: subZone.hostedZoneNameServers!,
      zone
    });

# Variant 4.2 Different account - delegation by child zone (New)

Stack 1 creates a role which is allowed to be assumed by Stack 2 to put the delegation in place. Stack 2 requires a custom resource with a lambda function to assume the role and create delegation.

Downside is a custom CloudFormation resource is required to put the delegation in place. Also in case the un-delegate fails on delete a dangling delegation record would be left behind which can be a security problem.

stack 1

    const parentZone = new route53.PublicHostedZone(this, "TopZone", {
      zoneName: "someexample.com"
    });

    role = new iam.Role(this, "CrossAccoundZoneDelegationRole", {
      assumedBy: new iam.AccountPrincipal("STACK2ACCOUNTID"),
      inlinePolicies: {
        "delegation": new iam.PolicyDocument({
          statements: [new iam.PolicyStatement({
            actions: ["route53:ChangeResourceRecordSets"],
            resources: [parentZone.hostedZoneArn]
          })]
        })
      }
    });

    // maybe with a helper like:
    // parentZone.enableCrossAccountDelegation(["STACK2ACCOUNTID"]);

stack 2 - uses new `CrossAccountZoneDelegationRecord` construct

    new route53.CrossAccountZoneDelegationRecord(this, "delegate", {
      nameServers: subZone.hostedZoneNameServers!,
      recordName: "sub.someexample.com",
      roleArn: "arn:...",
      zoneId: "1234"
    });

---

I think 4.2 has clear advantages from usage perspective but is more difficult to implement because the custom resource is required.

I'm not super familiar if there is already a mechanism to pass references cross account/region. It looks like the existing system is restricted to same account/region?
