### ISSUE TITLE
Unable to use CfnParameter valueAsNumber in SQS Queue

### ISSUE THREAD

**Issue by amwill04** [aws/aws-cdk#7126]
If trying to use a `CfnParameter` with a `SQS` `Queue` you end up with the following error:

```
message retention period must be 60 seconds or more, but -1.8881545897087585e+289 was provided
```
### Reproduction Steps

```typescript
        const redemptionPeriod = new CfnParameter(this, 'RedendtionPeriod', {
            description: 'SQS redention period in seconds 60 - 1209600 [14400]',
            type: 'Number',
            default: 14400,
            minValue: 60,
            maxValue: 1209600,
            constraintDescription: 'Must be between 60 and 1209600',
        });

        return new Queue(this, 'Queue', {
            queueName: 'queue',
            retentionPeriod: Duration.seconds(redemptionPeriod.valueAsNumber), // This pass typechecking but will at best fail and at worst pass with the incorrect number.
            deliveryDelay: Duration.seconds(0),
            maxMessageSizeBytes: 1024,
            receiveMessageWaitTime: Duration.seconds(20),
            visibilityTimeout: Duration.seconds(60),
        });
```
### Error Log

```
message retention period must be 60 seconds or more, but -1.8881545897087585e+289 was provided
```

### Environment

  - **CLI Version      :1.31.0
  - **Framework Version:1.31.0
  - **OS               :MacOS
  - **Language         :Typescript

This is :bug: Bug Report

**Comment by amwill04** [comment]
@eladb it only seems to fail only with SQS. It seems to work fine with other resources such as Lambda.

**Comment by shivlaks** [comment]
@amwill04 I think it works for Lambda because of an oversight where the `retry` parameter doesn't seem to have any validation for it.

i.e. the range for `retry` should be between 3 and 900 seconds, but the following will build and synth successfully (although it will fail during deployment because it's an invalid timeout value)
```ts
const handler = new lambda.Function(stack, 'handler', {
      handler: 'index.handler',
      code: lambda.Code.fromInline('boom'),
      runtime: lambda.Runtime.NODEJS_10_X,
      timeout: 901
    });
```

SQS on the other hand [validates](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-sqs/lib/validate-props.ts#L3-L10) the props that are set (which contain a token) and it's erroring out there

**Comment by amwill04** [comment]
@shivlaks does that mean with the way `token` are encoded when using `valueAsNumber` it means we lose the ability to validate at synthesis? As the example you provide shows?
