### ISSUE TITLE
API Gateway method Authorizer not overriding defaultMethodOptions when set to NONE

### ISSUE THREAD

**Issue by novaca-code** [aws/aws-cdk#7184]
### The Question
Should there be functionality to Override the RestApi defaultMethodOptions Authorizer with a Method specific specific Authorizer which is AuthorizerType.NONE

### Use Case
An Authorizer be specified for all methods of a RestApi except for the Options preflight method.

### Proposed Solution
In the case where an API methodOptions has AuthorizationType = NONE and Authorizer = undefined -> This will result in overridding any defaultMethodOptions Authorizer

API/cdk/node_modules/@aws-cdk/aws-apigateway/lib/method.js Constructor

Existing:
authorizer = options.authorizer || defaultMethodOptions.authorizer;
Proposed:
authorizer = (options.authorizationType === AuthorizationType.NONE ? void 0 : options.authorizer || defaultMethodOptions.authorizer)

### Environment

  - **CDK CLI Version:** 
  - **Framework Version:** 1.31.0
  - **OS:** all
  - **Language:** TypeScript

**Comment by nija-at** [comment]
Thanks for filing this issue, but I'm not sure I follow the bug that you are reporting.

Could you explain what it is that isn't working, with respect to `methodOptions` and `defaultMethodOptions`?

**Comment by jeremypearson** [comment]
I'd just like to say, for all of those who come across this issue who are trying to create an `@aws-cdk/aws-sam.CfnApi` instance instead of an `@aws-cdk/aws-apigateway.LambdaRestApi` instance, who would like to disable the adding of the default authorizer to CORS Preflight requests using the [`AddDefaultAuthorizerToCorsPreflight` property](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api-auth-object) which at the time of writing is not natively supported by the AWS CDK (see: https://github.com/aws/aws-cdk/issues/7493#issuecomment-617762189), you can set the `AddDefaultAuthorizerToCorsPreflight` property to `false` by performing a raw override using the [addPropertyOverride method](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw). I haven't yet tested this, but I think something along these lines should achieve it:
```ts
import { CfnApi } from '@aws-cdk/aws-sam';

const myApi = new CfnApi(this, 'MyApi', {
  stageName: 'MyStage',
  auth: {
    defaultAuthorizer: 'MyAuthorizer',
    authorizers: {
        MyAuthorizer: {
          UserPoolArn: '<user pool arn>',
          Identity: {
              Header: '<name of header to use for identity>',
              // ...
          }
          // ...
        }
    }
});
(myApi.node.defaultChild as CfnApi).addPropertyOverride('Auth.AddDefaultAuthorizerToCorsPreflight', false);
```

**Comment by nija-at** [comment]
Closing since there has not been any updates from the requester about the original issue.

Feel free to re-open when there are more details.

**Comment by wasa-ism** [comment]
@nija-at I think the issue pertains to what is discussed in this thread - https://github.com/aws/serverless-application-model/issues/2136

While SAM has `AddDefaultAuthorizerToCorsPreflight` property that can be set to False in order to avoid attaching the Authorizer to Option (CORS PreFlight), I am yet to find how to do it in CDK. So if I have a Lambda proxy like this-

```
new apigateway.LambdaRestApi(this,         
        'service-api', 
        { 
          handler: apiServiceFunction,
          description: 'Service API',
          deployOptions: {
            loggingLevel: apigateway.MethodLoggingLevel.INFO,
            dataTraceEnabled: true,
          },
          cloudWatchRole: true,
          defaultMethodOptions:{
            authorizer,
            authorizationType: apigateway.AuthorizationType.COGNITO,            
          },
          defaultCorsPreflightOptions:{
            allowOrigins: Cors.ALL_ORIGINS,      
            allowMethods: apigateway.Cors.ALL_METHODS, 
            statusCode: 200,   
            allowHeaders:['Content-Type','X-Amz-Date','Authorization','X-Api-Key','X-Amz-Security-Token'],                        
          },
        }
    );
```

I am not entirely sure how to NOT attach the default Authorizer to the CORS preflight. This causes issue in the browser since browsers do not pass Authorization header to pre-flight requests. I can easily re-produce is issue simply by manually enabling/disabling Authorization for `OPTIONS` using the API Gateway Console and redeploying the API.

**Comment by telpochyaotl** [comment]
@wasa-ism I am having the same issue... For me it is optional to set the defaultAuthorizer if I can figure out a way to set an authorizer for the default catch all route, but as soon as I use the defaultAuthorizer then all CORS preflight requests fail... Any luck on your end?
