### ISSUE TITLE
Fails to delete security group

### ISSUE THREAD

**Issue by satyamkondle** [aws/aws-cdk#7323]
When a security group is created and applied for mounting targets to efs, it gets deployed fine but deletion fails.

### Reproduction Steps
1. Create EFS
2. Create security group for mount targets
3. Create mount targets
4. Deploy
5. Destroy

### Code to reproduce (update account and cidr)
```
import os
import logging

from aws_cdk import (
    core,
    aws_ec2 as ec2,
    aws_efs as efs
)

AWS_REGION="us-west-2"
AWS_ACCOUNT="<account>"

class MyStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc(
            self, "my-vpc",
            cidr="<cidr>",
            max_azs=2,
            nat_gateways=1
        )

        efs_mt_sg = ec2.SecurityGroup(
            self, "efs_mt_sg",
            vpc=vpc,
            allow_all_outbound=True
        )

        efs_fs = efs.EfsFileSystem(self, "efs",
            vpc=vpc,
            security_group=efs_mt_sg)

        efs.CfnMountTarget(self, "mount_target1",
            file_system_id=efs_fs.file_system_id,
            security_groups=[efs_mt_sg.security_group_id],
            subnet_id=vpc.private_subnets[0].subnet_id)

        efs.CfnMountTarget(self, "mount_target2",
            file_system_id=efs_fs.file_system_id,
            security_groups=[efs_mt_sg.security_group_id],
            subnet_id=vpc.private_subnets[1].subnet_id)

        self.output_props=dict()

    # pass objects to another stack
    @property
    def outputs(self):
        return self.output_props

app = core.App()

stack = MyStack(
    app,
    "my-stack",
    description="Creates the Stack",
    env=core.Environment(region=AWS_REGION, account=AWS_ACCOUNT)
)

app.synth()
```

### Error Log
resource sg-09c4efe115ae38094 has a dependent object (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: 05e5f8c0-cab2-4acf-a68b-bed7ba34ddb7)

### Environment

  - **CLI Version      :1.31.0**
  - **Framework Version:<What is this? not sure>**
  - **OS               : Mac OS Catalina**
  - **Language         : Python3**

### Other

This could be related but happens in a different scenario: https://github.com/aws/aws-cdk/issues/6701

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I believe the following are unnecessary, as I think EFS will create the mountpoints itself:

```
        efs.CfnMountTarget(self, "mount_target1",
            file_system_id=efs_fs.file_system_id,
            security_groups=[efs_mt_sg.security_group_id],
            subnet_id=vpc.private_subnets[0].subnet_id)

        efs.CfnMountTarget(self, "mount_target2",
            file_system_id=efs_fs.file_system_id,
            security_groups=[efs_mt_sg.security_group_id],
            subnet_id=vpc.private_subnets[1].subnet_id)
```

Nevertheless, this error should not be happening.

But also, CDK doesn't really orchestrate the deletion of resources, that is all CloudFormation. I'm struggling to think what could be causing this. I'd need to see the full CFN template and the history of CFN events of the stack deletion in order to be able to debug this.

**Comment by machender1** [comment]
I am seeing the same problem ... the cdk destroy fails to delete the ENI attached to EFS. 

Appreciate any help to clear this.

**Comment by rix0rrr** [comment]
Smells like a CloudFormation bug in that case.

**Comment by corymhall** [comment]
@satyamkondle It's been a while since this was reported and I wasn't able to reproduce the issue when I tried today. Can you let me know if this is still an issue for you?

**Comment by ford-at-aws** [comment]
This is still an issue.

**Comment by himahimahima** [comment]
Hey,

My cdk stack will not destroy because of dependent Elastic Netwrok Interface (ENIs). The stack includes a Lamda function and a security group, and even through the lambda function is deleted correctly, the security group deletion fails due to these lingering ENIs.

I beleve there is a related issue in terrafrom that was resolved but no such luck in cdk. https://github.com/hashicorp/terraform-provider-aws/issues/10329

It only happens sometimes but once it happens retrying the delete never works. The only workaround I have at the moment is to manually delete the ENIs after the stack is done deleting my lambda and ends up in a failed state.
