### ISSUE TITLE
Implementation of ec2.IConnectable disjoint from underlying resource in ec2.Instance and others

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-cdk#7373]
While doing some spelunking into the CDK implementation of `aws-ec2.Instance()` to try to understand the `aws-ec2.IConnectable` interface I spotted what appears to be a bug.

The `aws-ec2.Instance` maintains an internal `securityGroups` list that is lazy evaluated to populate the `CfnInstance`'s `securityGroupIds` property:
 https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-ec2/lib/instance.ts#L285 

 This internal `securityGroups` is a separate object from the `securityGroups` contained in the `aws-ec2.Instance.connections` object:
https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-ec2/lib/instance.ts#L268

It's subtle, but notice that the `Connections` constructor is being given a new array comprised of a single security group.

The result is that we have two different ways to add a security group to an Instance, but only one of them will result in the security group actually being added to the instance:
  1. aws-ec2.Instance.addSecurityGroup() -- adds to the internal `securityGroups` list, and will end up on the instance.
  2. aws-ec2.Instance.connections.addSecurityGroup() -- adds to the connections object, but not to the underlying instance.

From a quick grep, it looks like similar issues exist in other Construct's implementation of `IConnectable`:

1. ASG is identical to Instance: https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts#L426
2. Additions through Connection.addSecurityGroup() don't affect the EKS cluster:
https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L381
3. EKS-legacy cluster is the same as the EKS cluster.
4. LoadBalancer additions to Connection do not make it to the LoadBalancer: https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-elasticloadbalancing/lib/load-balancer.ts#L237
5. ApplicationLoadBalancer is the same: https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts#L73
& 
https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts#L64
6. RDS appears to be the same:
https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L533
& https://github.com/aws/aws-cdk/blob/b7ddf5badeadb27e59f987aafa8c2a30660b828e/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L442

### Reproduction Steps

No reproducer. Based on code reading.

### Error Log

N/A

### Environment

  - **CLI Version      :** 1.32.2+, at least
  - **Framework Version:** 1.32.2+, at least
  - **OS               :** All
  - **Language         :** All

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by nathanpeck** [comment]
@eladb Looking into this I noticed that the underlying reactive list resource inside `Connections` appears to have the concept of listeners. 

I'm wondering if the intent is that there should be subscribed listeners that will then update the list of security groups on the construct if you add a new security group to the `Connections` object attached to an object.

Either way though if you add a security group using that constructs own `addSecurityGroup()` method I feel it should definitely be updating the list of SG's inside the `connections`

Right now it appears that they are getting out of sync with each other.

**Comment by rix0rrr** [comment]
That is a fair point. As a note, you shouldn't really be calling `instance.connections.addSecurityGroup()`, that thing is there for internal use, but hasn't been properly marked as such.

I think we may have gotten more things wrong about multiple security groups, mostly because I don't really understand the use cases. Can you please enlighten me?

The core of it is this:

## It seems to me that multiple security groups don't mix well with security group mutation.

For example, what happens today is if you do:

```ts
instance.connections.allowFrom(...);
```

It will add the rule to ALL security groups inside the connections object. But that's silly, isn't it? It only needs to be on one, so why add it to all?

And if you're going to be mutating security groups inside the CDK anyway, you'd probably add all rules to a single security group. You would model multiple instances using the same result by using a function:

```ts
function configureFirewall(connectable: IConnectable) {
  connectable.connections.allowFrom(...);
  connectable.connections.allowTo(...);
  connectable.connections.allowTo(...);
}

configureFirewall(instance1);
configureFirewall(instance2);
```

There's no real need for making a single preconfigured security group and passing it to 2 different instances.

So it seems to me the only use case for multiple security groups is:

* They already exist, and have been precreated by a blessed part of my organization (security, ops, ...). Each group covers a couple of ports so that I can mix and match them.
* I need to import them and stick combinations of them onto my instances.

In that world I don't get to do mutation anymore, so the whole `connections` object drops by the wayside.

-----------

What use case am I missing here?

**Comment by ddneilson** [comment]
> I think we may have gotten more things wrong about multiple security groups, mostly because I don't really understand the use cases. Can you please enlighten me?

Honestly, I'm not sure what it is either. My context on this ticket is that I'm working on a construct and looking at whether to implement the `IConnectable` interface; trying to understand its purpose from the implementation & uses in the CDK. On the surface, I think that you're on the right track -- a lot of the functionality in `IConnectable` doesn't really make sense.

Any idea what the original motivation was for creating it in its current form? The oldest commit in the file's history is a rename from 2018 that severed the history: https://github.com/aws/aws-cdk/commit/4c9cead36cf580e1581264b53439fa91eea20c36#diff-632a0f27b9388651dc698409cfaa0186

**Comment by rix0rrr** [comment]
It's to mutate security groups using a higher level API. (This assumes the security groups are mutable in the first place).

It allows you to say:

```ts
instance1.connections.allowFrom(instance2);
```

And this will add rules to both `instance1` to allow incoming connections and to `instance2` to allow the outgoing connections (if required).

The idea is you express your intent that these two resources should be allowed to connect to each other, without worrying about how you need to represent that in AWS. To use this, you don't even need to know what a security group is (of course, it introduces the problem that if you DO know what a security group is, you will now be confused because you just want to add some rules to some tables like you've always been doing, and there are now 2 ways to achieve the same thing).

**Comment by ddneilson** [comment]
Right. So, it satisfies that requirement. `IConnectable` and the implementations around it just start to get confusing when you start considering adding security groups through it; which is, basically, the original ticket.

**Comment by rix0rrr** [comment]
If you are just writing a new construct and need advice on what to do, I would just mimic what other constructs are doing. That is, take optional security group (or groups) in the construct, create a Connections object with those in the constructor, and that's it.

If users go to mutate the list of SGs, they need to mutate both. That's not ideal, but it's also not horrible.

If you want to do one step better, keep the list of SGs in the Connections object as source of truth, and forward the `construct.addSecurityGroup()` call to `this.connections.addSecurityGroup()`, then at least there is no ambiguity.

**Comment by nathanpeck** [comment]
Are you worried about it being a breaking change to make the constructs
keep these two lists of SGs in sync automatically? Right now the behavior
is confusing and will feel buggy especially if the user adds a SG manually
after the fact using the constructs method and then tries to create a SG
rule using the connections method.

Personally I feel like for correctness the two lists of SGs should always
be in sync with all mutations, not just synced a single time in the
constructor

I would recommend that we make a bigger underlying architectural change to
existing constructs to have only one source of truth and make the other
method be merely a vanity method that passes off responsibility. Maybe that
means making connections the source of truth and make the construct pull
its list of SGs from connections at synthesis time or maybe that means
making the construct the source of truth and have connections just utilize
the SG list on the construct

**Comment by corymhall** [comment]
I'm going to close this in favor of #7472.
