### ISSUE TITLE
Support For HostedZoneTags

### ISSUE THREAD

**Issue by kferrone** [aws/aws-cdk#7445]
The [HostedZone Construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53.HostedZone.html) does not support the [HostedZoneTags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-hostedzonetags). Please add support for these. In the mean time I had to make my hosted zone from CfnResource which did work and create the tags. 

### Use Case

Differentiate between numerous hosted zones with same name. Also useful for the [external-dns project](https://github.com/kubernetes-sigs/external-dns). 

### Proposed Solution

Add new field to the HostedZone props for the tags. 

This is a :rocket: Feature Request

**Comment by san28** [comment]
Will Tag.add also add tags under HostedZoneTags ?

https://docs.aws.amazon.com/cdk/latest/guide/tagging.html

**Comment by shivlaks** [comment]
@san28 - that's how it should work but I suspect that because the `Tag` attribute is not named similar to tags for other resources, our logic is not identifying this as "taggable resource"

We had to add similar exemptions for Cognito `UserPoolTags` and EFS `FileSystemTags` [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cfnspec/lib/schema/property.ts#L228) 

We will need to add a similar property for `HostedZoneTags`
marking this as a bug.

**Comment by shivlaks** [comment]
bug for the missing property in Cfn* construct (L1)
feature for adding in in the `HostedZone` construct L2

**Comment by kferrone** [comment]
@san28 I can confirm that Tag.add did not work. This is what I expected as well.

**Comment by shivlaks** [comment]
@kferrone it should work with 1.35.0. give it a try and let me how it goes!
