### ISSUE TITLE
Using Fn.importValue and Fn.Split to import VPC with Codebuild will cause Resolution Error

### ISSUE THREAD

**Issue by ookangzheng** [aws/aws-cdk#7506]
### The Question

I want to attach existed `vpc` to `codebuild` project by importing VPC with following code:
 
```javascript
// Import vpc
const vpcID = Fn.importValue(`Vpc-v1`);
const zones = Fn.split(',', Fn.importValue(`VpcZones-v1`));
const vpcArn = Fn.importValue(`VpcARN-${TagENV}-v1`);
const PrivateSubId = Fn.split(',', Fn.importValue(`VpcPrivateSubnetId-${TagENV}-v1`));
const PrivateRouteTableId = Fn.split(
  ',',
  Fn.importValue(`VpcPrivateRouteTableId-${TagENV}-v1`),
);
const PublicSubId = Fn.split(',', Fn.importValue(`VpcPrivateRouteTableId-${TagENV}-v1`));
const PublicRouteTableId = Fn.split(',', Fn.importValue(`VpcPublicRouteTableId-${TagENV}-v1`));


const vpc = ec2.Vpc.fromVpcAttributes(this, `vpc`, {
      vpcId: environment.vpcId,
      availabilityZones: environment.zones,
      privateSubnetIds: environment.PrivateSubId,
      publicSubnetIds: environment.PublicSubId,
      privateSubnetRouteTableIds: environment.PrivateRouteTableId,
      publicSubnetRouteTableIds: environment.PublicRouteTableId,
    });

  new codebuild.PipelineProject(this, `codebuildProject`, {
      projectName: `Codebuild-${environment.ENV}`,
      description: `Bof - ${environment.ENV} Codebuild`,
      vpc,
})

```
I got this error

```
/frontend-codebuild/node_modules/@aws-cdk/core/lib/resolvable.ts:168
      throw new Error(`Cannot concatenate strings in a tokenized string array, got: ${xs[0]}`);
            ^
Error: Resolution error: Resolution error: Resolution error: Cannot concatenate strings in a tokenized string array, got: arn:aws:ec2:${Token[AWS::Region.4]}:${Token[AWS::AccountId.0]}:subnet/#{Token[TOKEN.14]}.
```

But same code does work with `apigateway` though.

Work around method, I have to remove `Fn.split()` or this method 

```javascript
const vpc = ec2.Vpc.fromVpcAttributes(this, `vpc-${environment.testStage}-v1`, {
      vpcId: environment.vpcId,
      availabilityZones: [
        Fn.select(0, environment.availabilityZones),
        Fn.select(1, environment.availabilityZones),
      ],
      publicSubnetIds: [
        Fn.select(0, environment.publicSubnetIds),
        Fn.select(1, environment.publicSubnetIds),
      ],
      privateSubnetIds: [
        Fn.select(0, environment.privateSubnetIds),
        Fn.select(1, environment.privateSubnetIds),
      ],
      privateSubnetRouteTableIds: [
        Fn.select(0, environment.privateSubnetRouteTableIds),
        Fn.select(1, environment.privateSubnetRouteTableIds),
      ],
      publicSubnetRouteTableIds: [
        Fn.select(0, environment.publicSubnetRouteTableIds),
        Fn.select(1, environment.publicSubnetRouteTableIds),
      ],
    });

```

### Environment

  - **CDK CLI Version:** 1.34.1
  - **OS:** OSX Catalina
  - **Language:** Typescript

**Comment by ookangzheng** [comment]
Any thought?

**Comment by skinny85** [comment]
Hey @ookangzheng ,

unfortunately, you ran into a corner-case of how CloudFormation works, and there's nothing we can do to make that first code of yours execute correctly. Let me explain.

When you `Fn::Split` a value that you got from `Fn::ImportValue`, you get something like this in CFN:

```json
{
  "Resources": {
    "Vpc": {
      "Properties": {
        "SubnetIds": {
          "Fn::Split": [
            ",",
            {
              "Fn::ImportValue": "VpcPrivateSubnetId"
            }
          ]
        }
      }
    }
  }
}
```

The problem is that the CodeBuild Project construct needs the Subnets ARNs, not its IDs, to [grant the correct permissions to the project's role to access the VPC](https://github.com/aws/aws-cdk/blob/b0a65c1b7bb4532722adf20a10f653fff88d152a/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L996-L1007). However, since the array returned from `Fn::Split` is only known at deploy time, there's no way for us to go from the Subnet IDs to the Subnet ARNs ([this line](https://github.com/aws/aws-cdk/blob/b0a65c1b7bb4532722adf20a10f653fff88d152a/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1003-L1003) in the CodeBuild Project construct) - there's no `Fn::Map` function, or anything like that! For that reason, it's not possible to write a CloudFormation template that will go from the Subnet IDs to Subnet ARNs.

Notice in your second code, that you got working, you did something completely different:

```ts
      publicSubnetIds: [
        Fn.select(0, environment.publicSubnetIds),
        Fn.select(1, environment.publicSubnetIds),
      ],
```

You've explicitly said that you're only interested in the first 2 elements of the imported value! This, as opposed to saying "I want all parts of the imported value", makes this representable in CloudFormation, and that's why CDK allows it.

Sorry I don't have better news, but this is quite a complicated scenario.

Let me know if you need any more help from our side on this issue.

Thanks,
Adam
