### ISSUE TITLE
DescribeTable in dynamobDB grantReadWriteData and grantReadData

### ISSUE THREAD

**Issue by jkar32** [aws/aws-cdk#7633]
Table.grantReadWriteData and Table.grantReadData should add the permission `dynamodb:DescribeTable`

### Use Case

Packages such as pyamodb use `DescribeTable` and due to that lack of permission in `grantReadWriteData` and `grantReadData` it is not as simple to configure.

Currently to add the `DescribeTable` you have to do 

```typescripe
table.grantReadWriteData(postConfirmationLambdaTrigger);

postConfirmationLambdaTrigger.addToRolePolicy(
    new iam.PolicyStatement({
        resources: [table.tableArn],
        actions: ["dynamodb:DescribeTable"],
    })
);
```

### Proposed Solution

Add the dynamodb:DescribeTable as a default in `grantReadWriteData` and `grantReadData`

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@jkar32 you can use the `grant` API to add permissions that are needed

something like:
```ts
  table.grant(postConfirmationLambdaTrigger, 'dynamodb:DescribeTable');
```

[Documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#grantgrantee-actions-)

**Comment by jkar32** [comment]
@shivlaks I should o been more specific.

That is only possible right now if the table and lambda is in the same stack. 

If the table is being referenced by ‘getByArn’ in another stack grant is not function (Shown in another issue)

**Comment by shivlaks** [comment]
@jkar32 I believe we exposed `grant` through `ITable` as of [`1.36.0`](https://github.com/aws/aws-cdk/releases/tag/v1.36.0) 

Does that limitation still exist?

**Comment by jkar32** [comment]
@shivlaks 
Yes, I was still on `1.35.0`. You are updating faster than I can code!

I am still wondering whether DescribeTable should be under `grantReadWriteData` and `grantReadData` methods?

If you don't think so I would be curious why.

**Comment by shivlaks** [comment]
@jkar32 I don't know about the  background rationale behind the current API (@RomainMuller would know)

I can take a guess though. Since the API signature is `grantReadData` and it's documented as follows: 
> Permits an IAM principal all data read operations from this table
I would expect it to only contain the minimal set of permissions needed to read table `data`.

We also have an API called `grantStream` that provides permissions for a table's stream.
The APIs are specific to what they operate on.

`DescribeTable` is really an operation on the table and not it's data. If we did want read operations on a table, I'd expect it to be a different API but also one that would include:
- `DescribeBackup`
- `DescribeContinuousBackups`
- `DescribeTimeToLive`
- `DescribeContributorInsights`

**Comment by jkar32** [comment]
Makes sense

Cheers
