### ISSUE TITLE
Add support for AWS::CloudFormation::Init

### ISSUE THREAD

**Issue by taichi** [aws/aws-cdk#777]
TypeScript CDK 0.9.2

How to write `AWS::CloudFormation::Init` metadata with AWS Construct Library for `cfn-init` ?
I want to add  `AWS::CloudFormation::Init` metadata to `AutoScalingGroup`.

**Comment by rix0rrr** [comment]
We don't have this modeled as an L2 right now.

You can instantiate a `cdk.Resource` and pass in the properties that make up an `Init` resource, and add the appropriate call to the ASGs userData yourself.

**Comment by rix0rrr** [comment]
It should include support for environment variables, by writing them to a script in `/etc/profile.d`.

Need to do research to see if all ways of starting a program source the files there well enough.

**Comment by taichi** [comment]
I'm trying to convert this template with cdk.
[atlassian-aws-deployment / templates / JiraDataCenter.template.yaml
](https://bitbucket.org/atlassian/atlassian-aws-deployment/src/23e74d98755b99e3f1f287ca5bae71781d61f4dc/templates/JiraDataCenter.template.yaml?at=master&fileviewer=file-view-default)

environment variables are in [l.1008](https://bitbucket.org/atlassian/atlassian-aws-deployment/src/23e74d98755b99e3f1f287ca5bae71781d61f4dc/templates/JiraDataCenter.template.yaml?at=master&fileviewer=file-view-default#JiraDataCenter.template.yaml-1008)

**Comment by eladb** [comment]
Closed [PR](https://github.com/awslabs/aws-cdk/pull/792) for now. Reopen as needed.

**Comment by 0xdevalias** [comment]
Sad that that PR didn’t land.. :(

**Comment by eladb** [comment]
We'll get there. It's an important feature... Just got too much on our table RN...
Happy to take contributions of course if you are interested to pick it up

**Comment by eladb** [comment]
Still releavnt

**Comment by brettswift** [comment]
I haven't taken a stab at a construct, but I put together a template with the assumption I needed a shell script to be put onto the machine and be executed.  The construct for `Init` will hopefully make it easier to "just execute this script at launch time".     So I have scoped my solution to just the file / command resources,  and a little bit of a fairly robust userdata script (that requires the ASG and Launch config for both cfn-init and cfn-signal). 

I put it up on a gist instead of here.   Hopefully this is helpful if someone writes the L2, to see how I tackled this use case.  I'd like to spend time on an L2 but not sure I'll have the time for a while. 

https://gist.github.com/brettswift/6e48a70d808a28614438520682459f0c

**Comment by brettswift** [comment]
I updated the gist above adding in a builder class to help us reduce code re-use.   Definitely not feature complete for cfn-init,  however it's one take to solve just our use case still.   If this is a strategy that people like, I might have time to contribute to  a PR into CDK.

**Comment by ywauto83** [comment]
any update on this? @rix0rrr

**Comment by robertd** [comment]
Yeah, I'd really like to see this feature ship soon. Using escape hatches to accomplish this task is very cumbersome.

**Comment by Zirkonium88** [comment]
Please, keep things going on this @rix0rrr

**Comment by Zirkonium88** [comment]
With regard to another issue about adding metadata, this seems to be a work around at the moment: [Modifying the AWS CloudFormation resource behind AWS constructs](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource)

**Comment by felipeloha** [comment]
i tried to use this and got When applying CloudFormationInit, you must also configure signals by supplying 'signals' at instantiation time.
