### ISSUE TITLE
How get the brokers URL from AWS_MSK

### ISSUE THREAD

**Issue by mostafafarzane** [aws/aws-cdk#7904]
I am usign `CfnCluster` to create Kafka cluster.
How can I get and pass the Kafka cluster brokers' URL from the CfnCluster resource?

**Comment by iliapolo** [comment]
Hi @mostafafarzane.

By default, the runtime information that is exposed from CDK constructs rely on the CloudFormation attributes of the underlying resource. The CFN resource for an [`MKS::Cluster`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-cluster.html) does not expose the broker URL unfortunately. 

In order to get this information, you can use a special [custom resource](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsCustomResource.html) that performs AWS SDK calls and fetches specific properties from the response. 

Hope this helps.

For future reference, we usually reserve GitHub issues for bug reporting and feature requests. Guidance type question are better asked, and answered, in our other community channels:

- [Gitter](https://gitter.im/awslabs/aws-cdk)
- [StackOverflow](https://stackoverflow.com/questions/tagged/aws-cdk)

Thanks
