### ISSUE TITLE
DnsValidatedCertificate - Failed to create CertificateRequestorResource

### ISSUE THREAD

**Issue by jamiepmullan** [aws/aws-cdk#7905]
When running CDK Deploy, I keep getting the error:
"Failed to create resource. Cannot read property 'Name' of undefined"
From:
"CertificateRequestorResource/Default"

`10/14 | 13:59:06 | CREATE_FAILED        | AWS::CloudFormation::CustomResource             | Cert/webCert/CertificateRequestorResource/Default (CertwebCertCertificateRequestorResourceXXXXX) Failed to create resource. Cannot read property 'Name' of undefined
	new CustomResource (/...../node_modules/@aws-cdk/core/lib/custom-resource.js:23:25)`

--- 

This is :bug: Bug Report

**Comment by asterikx** [comment]
@jamiepmullan How did you resolve the issue? Facing the same problem.

**Comment by asterikx** [comment]
I could get it solved.

I had two hosted zones, `example.com` and `dev.example.com`. I was deploying two stacks, one of which issued a certificate for the apex domain and one for the subdomain.
I was issuing a certificate for the subdomain before I had one for the apex domain.

Since there was no explicit dependency between the two stacks the CLI deployed the stacks in alphabetical order.
Deploying first the stack for the apex domain and then the one for the subdomain fixed the issue for me. Adding an explicit dependency in the code , e.g. `devDnsStack.addDependency(rootDnsStack)`) should do so too.

**Comment by lusentis** [comment]
Same issue, single stack with just a couple of resources. Deploys fine sometimes, while other times it fails (4/5 approx).
Didn't find a solution so far, except repeating the deploy until it succeeds - definitely looks like a concurrency issue, but cannot figure out what's causing it.
