### ISSUE TITLE
aws codepipeline and chatbot integration

### ISSUE THREAD

**Issue by JustasVersekys** [aws/aws-cdk#7983]
### Reproduction Steps
```
    const notificationTopic = new sns.Topic(this, 'Topic', {});

    new chatbot.CfnSlackChannelConfiguration(this, 'jvSlackChannel', {
      loggingLevel: 'INFO',
      configurationName: 'someConfiguration',
      iamRoleArn: cdkBuild.role?.roleArn || '',
      slackChannelId: 'censored',
      slackWorkspaceId: 'censored',
      snsTopicArns: [notificationTopic.topicArn],
    });

    const pipeline = new codepipeline.Pipeline(this, 'Pipeline-' + branch);

    pipeline.onStateChange('stateChangeTarget').addTarget(new targets.SnsTopic(notificationTopic));
```

### Error Log
I see errors in cloudwatch logs:

> Event received is not supported (see https://docs.aws.amazon.com/chatbot/latest/adminguide/related-services.html ): 

### Environment

  - "@aws-cdk/aws-chatbot": "^1.38.0"
  - "@aws-cdk/aws-events-targets": "^1.38.0"

### Other

It was configured using CDK to create aws-chatbot to post codepipeline notifications to slack channel.
If notification rule is created in client via pipeline settings - everything works. The problem is - this needed to be configured via CDK.

--- 

This is :bug: Bug Report

**Comment by jumi-dev** [comment]
Instead of using package @aws-cdk/aws-events-targets, you can configure the notifications for your CodePipeline with @aws-cdk/aws-codestarnotifications:
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codestarnotifications-readme.html
The configuration is done in class CfnNotificationRule. Unfortunately, it's only an CFN resource. However, it's possible to configure the CodePipeline to send notifications to Chatbot/Slack.

**Comment by skinny85** [comment]
Hi @JustasVersekys ,

thanks for opening the issue. Like @jumi-dev mentioned (thanks!), I think what you're looking for are CodeStar Notifications, not CloudWatch Events here. Sorry for the confusion.

Let me know if this helps.

Thanks,
Adam
