### ISSUE TITLE
RestApi construct does not automatically create new deployments when policy changes

### ISSUE THREAD

**Issue by marcogrcr** [aws/aws-cdk#8024]
The `RestApi` construct does not automatically create a new deployment when nothing **but** the policy changes.

### Reproduction Steps

```ts
import { RestApi } from "@aws-cdk/aws-apigateway";
import { AnyPrincipal } from "@aws-cdk/aws-iam";
import { Token } from "@aws-cdk/core";

// if just this changes, RestApi does not trigger a new deployment automatically
const apiPolicy = new PolicyDocument({
  statements: [
    new PolicyStatement({
      actions: ["execute-api:Invoke"],
      resources: ["execute-api:/prod/*/public/*"],
      principals: [new AnyPrincipal()]
    })
  ]
});

const api = new RestApi(this, "Api", {
  // ...
  policy: apiPolicy
});
```

You can workaround the bug with the following:

```ts
api.latestDeployment?.addToLogicalId(Token.asAny(apiPolicy));
```

I believe this could be fixed by adding the following code to [packages/@aws-cdk/aws-apigateway/lib/restapi.ts:341](https://github.com/aws/aws-cdk/blob/be1dd1be81eafda8d8f66f39c75a42817b7b654c/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L341):

```ts
if (props.policy) {
  this._latestDeployment.addToLogicalId(Token.asAny(props.policy));
}
```

My plan was to actually submit a pull-request with the fix, but I'm unable to build `aws-cdk` locally (probably due to my local config) and the Docker build is currently broken (see #7785).

### Environment

  - **CLI Version:** `1.38.0`
  - **Framework Version:** `1.38.0`
  - **OS:** Mac OS 10.14.6
  - **Language:** English

### Other

This bug was indirectly mentioned in #2387.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hello @marcogrcr -

Thanks for filing this issue.

This was an issue prior to v1.35.0. [A fix](https://github.com/aws/aws-cdk/pull/7115) has since been applied and released for this. 
Can you check that the CDK framework you are using is a version >=1.35.0?You can find this by running `npm list` or `yarn list` in your project and checking the version of the CDK packages being listed.

I re-checked this with this latest version and I was able to confirm that the [logical Id](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html) of the `AWS::ApiGateway::Deployment` in the generated CloudFormation template changes when the policy is updated.
This should automatically trigger a new deployment in ApiGateway when the template with a new logical id for the Deployment resource is deployed.
If you still see this issue, can you check if the logical id changes or remains the same when the `policy` property of `RestApi` is modified?

**Comment by marcogrcr** [comment]
Hi @nija-at:

Apologies for the misunderstanding. Turns out I was looking at the wrong project which was using version `1.32.0`. I can confirm that this works after updating to `1.38.0`.
