### ISSUE TITLE
[TS] domainName and domainZone missing from ApplicationMultipleTargetGroupsServiceBaseProps

### ISSUE THREAD

**Issue by logemann** [aws/aws-cdk#8230]
While playing around with **ApplicationMultipleTargetGroupsFargateService** i noticed that two properties (_domainName_ and _domainZone_) available in **ApplicationLoadBalancedServiceBaseProps** are not available in **ApplicationMultipleTargetGroupsServiceBaseProps**

I wondered how the zone entry could be created,  so i checked **ApplicationMultipleTargetGroupsServiceBase** where this line should do it:

`const domainName = this.createDomainName(this.loadBalancer);`

But the createDomainName() just gets the LB instance because there are no other props, resulting in the default DNS name of the LB getting returned which makes the method pretty useless. 

### Proposal

add those two properties and supply them to the method which will in turn create the ARecord entries in Route53.

### Reproduction Steps

nothing to reproduce here.

### Environment

  - **Framework Version: 1.41.0 (build 9e071d2)**

--- 

This is :bug: Bug Report

**Comment by hencrice** [comment]
Hey @logemann 

For `ApplicationLoadBalancedService`, since there's only one LB, for simplicity and ease-of-use, we exposed `domainName` and `domainZone` through `ApplicationLoadBalancedServiceBaseProps`.

For `ApplicationLoadBalancedServiceBaseProps` however, since it supports multiple LBs, we left `domainName` and `domainZone` to be configured on each LB in:

https://github.com/aws/aws-cdk/blob/986e2814e072f0334d8470a2d60ea73dcceadfe4/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-multiple-target-groups-service-base.ts#L273

**Comment by logemann** [comment]
makes sense. Didnt get that ApplicationMultipleTargetGroupsFargateService can create several LBs.
