### ISSUE TITLE
Incorrect synthesis when using the escape hatch `CfnSecurityConfiguration` in python.

### ISSUE THREAD

**Issue by dvedhire** [aws/aws-cdk#8363]
Trying to deploy an application that synthesizes an `AWS::Glue::SecurityConfiguration` resource and the synthesized template generates an empty object `{}` for the property `EncryptionConfiguration`. Here is the code-snippet being used:

```
from aws_cdk import aws_glue as glue, aws_kms as kms, core


class GlueSecConfigStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        key = kms.Key(self, "key", trust_account_identities=True)

        glue.CfnSecurityConfiguration(
            self,
            "sec_config",
            encryption_configuration={
                'S3Encryptions': [{
                    'S3EncryptionMode': "SSE-KMS",
                    'KmsKeyArn': key.key_arn,
                }],
                'CloudWatchEncryption': {
                    'CloudWatchEncryptionMode': "SSE-KMS",
                    'KmsKeyArn': key.key_arn,
                }
            },
            name="glue_sec_config",
        )


app = core.App()
GlueSecConfigStack(app, "glue-sec-config")

app.synth()
```

This application on synthesis generates the following resource:

```
  secconfig:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      EncryptionConfiguration: {}
      Name: glue_sec_config
    Metadata:
      aws:cdk:path: glue-sec-config/sec_config
```

**NOTE:** *This issue is not reproducible when using JavaScript or Typescript, which makes me believe it's an issue with JSII.* *Also, since the property being deployed is {} the resource creation in CloudFormation fails with an `Internal Failure`.*

### Environment

  - **CLI Version      :** 1.41.0 (build 9e071d2)
  - **Framework Version:** 1.41.0
  - **OS               :** MacOS Catalina 10.15.5
  - **Language         :** Python

--- 

This is a :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @dvedhire.

Its definitely a bit tricky, but you actually didn't supply the correct type to the `encryption_configuration` property. 

Here is what it should look like:

```python
glue.CfnSecurityConfiguration(
    self,
    "sec_config",
    encryption_configuration=glue.CfnSecurityConfiguration.EncryptionConfigurationProperty(
      s3_encryptions=[
        glue.CfnSecurityConfiguration.S3EncryptionProperty(
          s3_encryption_mode='SSE-KMS',
          kms_key_arn=key.key_arn
        )
      ],
      cloud_watch_encryption=glue.CfnSecurityConfiguration.CloudWatchEncryptionProperty(
        cloud_watch_encryption_mode='SSE-KMS',
        kms_key_arn=key.key_arn
      )
    ),
    name="glue_sec_config",
)
```

A good rule of thumb would be that if you find yourself writing raw dictionaries, you're probably going the wrong way. Notice how everything in the definition above is declared using specific types.

We have plenty of issues around runtime type validation and doc improvements for dynamic languages so stay tuned. But for now, just make sure you always use types, rather than raw JSON structures. 

Closing this issue, but feel free to re-open if you feel its needed.

Thanks
