### ISSUE TITLE
Unable configure ApplicationProperty in EMR using conditions

### ISSUE THREAD

**Issue by k-jjmartinez** [aws/aws-cdk#8371]
### Reproduction Steps
Generate (synth) this template https://github.com/aws-samples/aws-service-catalog-reference-architectures/blob/master/emr/sc-emr-SparkHbase.json with AWS CDK

### Error Log

[ticket.zip](https://github.com/aws/aws-cdk/files/4730352/ticket.zip)

### Environment
  aws-cli/1.17.9 Python/3.7.5 Linux/4.15.0-1043-oem botocore/1.14.9
  CDK version 1.36.0
  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @k-jjmartinez - Unfortunately I don't understand the issue. 

In the `Reproduction Steps` section you link to an already synthesized template, rather than a code snippet that reproduces the issue.

In the `Error Log` section you link to a zip file that doesn't actually contain an error. It contains a source code file with **400** lines of code, and a synthesized template, which I assume is somehow misconfigured.

For us to properly diagnose the problem, the issue needs to be more specific. Please, consider the following:

- Create a short (as possible) code snippet that reproduces the problem.
- If there is no error, specify the output you expected to see *vs* the output you are getting.

Thanks
