### ISSUE TITLE
Use default/STS credentials/account

### ISSUE THREAD

**Issue by OlegBoulanov** [aws/aws-cdk#8605]
There is --profile option of CDK command. It's strange that profile info is not used by default by the app code for Stack Env, and I have to write it.

### Use Case

To simplify coding

### Proposed Solution

A simple call to STS (get-caller-identity) could yield account number, and region is often already provided along with credentials in the profile.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@OlegBoulanov The CLI will use environment variables to determine the credentials, and otherwise will use the credentials from the `default` profile.

Are you talking about the `env` configuration in the code itself? you can point it to read [environment variables](https://docs.aws.amazon.com/cdk/latest/guide/environments.html) supported by the CLI `CDK_DEFAULT_ACCOUNT` and `CDK_DEFAULT_REGION` which will read from your default profile if they are not established. 

Is your use case different from what's supported today?
