### ISSUE TITLE
Is there a way to reattach resource after CloudFormation stack deleted?

### ISSUE THREAD

**Issue by yanshengjia** [aws/aws-cdk#8611]
I used CDK to deploy a SQS (with deletion policy RETAIN) and manully deleted CF stack in console, when I cdk deploy again, is there a way to reattach CDK stack to previous existing SQS?
I guess deletion policy Snapshot is a go. But AWS::SQS::Queue does not support deletion policy Snapshot.

### Use Case

If someone accidently deletes CF stack and I cdk deploy again, I want my cdk stack can reattach to existing SQS service.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@yanshengjia the ability to import a resource into a stack is not available through the CDK yet.
Would you mind adding your use case / details to aws/aws-cdk-rfcs#52 if it's not captured there already.

I'm resolving this as the RFC is the starting point to support this feature. 
Feel free to reopen if I've interpreted your use case incorrectly!

**Comment by yanshengjia** [comment]
Sure.

For now, the workaround is mapping ARN in cdk.CfnMapping?

**Comment by shivlaks** [comment]
@yanshengjia you can reference your SQS Queue through the [`fromQueueArn`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.Queue.html#static-from-wbr-queue-wbr-arnscope-id-queuearn) and [`fromQueueAttributes`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.Queue.html#static-from-wbr-queue-wbr-attributesscope-id-attrs) APIs

These will import the resource that is no longer governed by the stack into your app so that it can be referenced.
Note that this is not the same as importing the resource into the *stack*. You will not be able to modify any properties of the queue, but you can reference it and use it in your application.

Hope that helps!

**Comment by yanshengjia** [comment]
@shivlaks Very helpful! Thanks!
