### ISSUE TITLE
(aws-ecs-patterns): ScheduledFargateTask fails to teardown cluster if tasks are running

### ISSUE THREAD

**Issue by jonathanmorley** [aws/aws-cdk#8654]
Cluster deletions fail while the cluster has tasks running

### Reproduction Steps

Create a stack containing a `ScheduledFargateTask`, and then try to delete it while a task is running. The stack deletion will fail

### Environment

  - **CLI Version      :** 1.44
  - **Framework Version:**
  - **Node.js Version:**  12.17
  - **OS               :** macos 10.15.5
  - **Language (Version):**  TS 3.9.5

### Other

I have worked around this by having a custom resource that will find all tasks running on the cluster, stop them, and then wait for them to be stopped.

--- 

This is :bug: Bug Report

**Comment by bvtujo** [comment]
Hi @jonathanmorley, thanks for reaching out about this. It's currently expected behavior that cluster deletions fail while tasks are running, unfortunately--I think that's a tradeoff made in CF, not necessarily the CDK construct. 

I think your options here are the following:
* Your custom resources solution
* Use a combination of `aws ecs list-clusters`, `aws ecs list-tasks --cluster <yourCLuster>`, and `aws ecs stop-task --task <yourTask>` to programmatically kill tasks 

I apologize for the inconvenience, but there's nothing we can do on the cdk side of things to automate this as the CDK uses CF under the hood. I hope this helps. Please feel free to reopen if you have further questions.
