### ISSUE TITLE
Core: consistent way of giving names, even if those are implemented using Tags

### ISSUE THREAD

**Issue by logemann** [aws/aws-cdk#8661]
The way how **resourceNames** are currently defined is wildly different from construct to construct and quite confusing to be honest. Lets take a VPC. Here you need to create a **"Name" Tag** to get the name you want. (otherwise its derived from stackname and id). Other constructs have easy to select attributes like **logGroupName** (for LogGroups) and some cant be changed at all via the constructs like AutoScalingGroup.

I assume it's because constructs still are somewhat designed from Cloudformation way of doing things.

### Use Case

CDK would be easier to approach when there would be some kind of standard to define names for constructs. 

### Proposed Solution

```
new Vpc(...., {
   vpcName: "MyVpc"
});

new WhateverResource(...., {
   whateverResourceName: "MyWhateverResource"
}
```

Most likely when a user hears about **Tags**, he thinks of custom literals he can attach to an object and not something that is a 1st class property shown in the AWS Console for a resource. It's like designing the customerName as Tag in a CRM system. 

Of course Cfn expects a tag for a VPC but this should be hidden from a CDK developer then (as it is now with an opinionated name tag being constructed). 

_Opinions appreciated._  

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I concur.

The discrepancy mostly comes from whether the "name" shown in the console comes from a resource attribute or a tag, I think. If the resource doesn't have a field "name", that is less obvious and likely to be missed when implementing the L2.

I think it's mostly an oversight if it's not possible or hard to do. Since this ticket is not currently very actionable, the best way to turn this into action is to make new tickets on a case-by-case basis where there is no currently good way to name resources.

**Comment by gliptak** [comment]
some constructs already mapping
for example https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-ec2/lib/instance.ts#L338

**Comment by MrArnoldPalmer** [comment]
As @rix0rrr mentioned, tracking this as individual construct issues will be better. Closing this in favor of that strategy, please open issues for constructs with unwieldy naming and we can evaluate the APIs individually.
