### ISSUE TITLE
CLI: support for Stages/nested Cloud Assemblies

### ISSUE THREAD

**Issue by neg3ntropy** [aws/aws-cdk#8676]
Using core Stage, the stage's stacks are not available when running cdk .

### Reproduction Steps

```typescript
#!/usr/bin/env node
import "source-map-support/register";
import * as cdk from "@aws-cdk/core";

class MyStage extends cdk.Stage {

    constructor(scope: cdk.App, id: string, props: cdk.StageProps) {
        super(scope, id);
        new cdk.Stack(this, "stack");
    }
}

const app = new cdk.App();
new MyStage(app, "stage", {})
```

### Error Log

```bash
$ cdk list
This app contains no stacks
```

### Environment

  - **CLI Version      :** aws-cli/1.18.77 Python/3.8.3 Linux/5.6.16-300.fc32.x86_64 botocore/1.17.5
  - **Framework Version:** 1.46.0
  - **Node.js Version:**  12.16.1
  - **OS               :** Fedora 32
  - **Language (Version):**  TypeScript (3.9.3)

### Other

I figure the Stage is either broken or supposed to be used in a specific context, but I could not find examples. From the docs it seems to do exactly what I want, that is to group some stacks and instantiate them multiple times with different names/environments. 
The App is a Stage (which is strange by itself IMHO) but it does not accept an Environment, so one has to do this with a custom construct, ending up with crappy Stack ids...
So if it's not a bug, it's at least very confusing.

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Yes, this feature is not complete yet.

I'm assuming your example code meant to inherit from `Stage` instead of `Construct`.

Either do:

```
$ cdk synth
$ cdk -a cdk.out/stage-stage deploy
```

Or inherit from `Construct` for now. If you dislike the default stack names that are generated for you when you use `Construct` to do your stack grouping, you can always override them by passing the `stackName` property.

**Comment by eladb** [comment]
Assigning to @rix0rrr

**Comment by neg3ntropy** [comment]
@rix0rrr Yes, sorry I meant to extend Stage in the example, but I did a couple of experiments and ended up copying the wrong code. Updated now.

**Comment by rix0rrr** [comment]
Don't forget warnings/errors: https://github.com/aws/aws-cdk/issues/9799

**Comment by blimmer** [comment]
This causes the issue where stages defined in the CDK pipelines module do not appear when you try to run `cdk diff`. Instead, you'll just see the Pipeline and not the nested Stacks within the Stage.

(I'm adding this comment because I didn't find this ticket with a GitHub issue search. I ended up finding it via this [cdk.dev thread](https://cdk-dev.slack.com/archives/C018XT6REKT/p1604315198168500), so I'm adding this comment to hopefully help future folks discover this thread. The word "pipeline"/"pipelines" should trigger this to show up in search.)

**Comment by rix0rrr** [comment]
When we tackle this, we have to think real hard about how we identify stages and stacks on the command line.

Right now it's a vague distinction whether we use stack NAMES or stack ARTIFACT IDs (I can't even tell). Maybe the answer is both with some formatting sigils (`#StackName`, `@ArtifactId`, unqualified is okay if it's unambiguous), or what have you.

Something of that sort.

**Comment by tomaszdudek7** [comment]
I am quite confused.

CDK Pipelines tutorial https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/ uses Stage concept. I followed the tutorial but wanted to deploy the Stage on my own first (before proceeding to CI/CD pipeline creation) - and then I hit this issue.

Do I get it correctly:
-  Stages are containers for multiple Stacks (so that for example you have various resources grouped as separate Stacks, Stage is a cointainer for them(that makes a Stage kinda like a topology of your system) and then you create `new Stage("qa0"), new Stage("preprod")` to have various environments of your system) 
- ...but they are not ready to use (without CDK Pipelines) yet?

**Comment by rix0rrr** [comment]
Fixed in #https://github.com/aws/aws-cdk/pull/14379
