### ISSUE TITLE
[dynamodb] aws-dynamodb fromTableName not returning tableStreamArn

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws/aws-cdk#8903]
When using the CDK's `Table.fromTableName` I expected to get the arn of my Table Sream
However, the Arn is not returned in general by this function, but it does return the `tableStreamArn` with an undefined value.
So either, add the stream in the return or remove the key from the response?

![image](https://user-images.githubusercontent.com/5285035/86571405-adda3a00-bfb4-11ea-9e33-f3c66bf85dd3.png)

### Environment

  - **CLI Version      : 1.49.1**
  - **Node.js Version:** 12.16.1
  - **OS               :**  OSX
  - **Language (Version):** Typscript 3.9.4

**Comment by skinny85** [comment]
Hi @mattiLeBlanc ,

`tableStreamArn` is undefined, because we can't fill it just from the Table name that you provide in `fromTableName`.

If you want to provide it, feel free to use the [`fromTableAttributes` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#static-from-wbr-table-wbr-attributesscope-id-attrs).

**Comment by mattiLeBlanc** [comment]
@skinny85 I did try `fromTableAttributes` but then I also need to add the StreamArn as an Output in our dynamo table stack.
We use separate stacks and using Outputs links those stacks together, creates problems if you have to remove one of the stacks.
It would have been nice if the `fromTableName` could have offered that info, it is getting all the other Table details, why couldn't it fetch the StreamArn if it is enabled?

Right now I have a work around by using the SDK to get the table details so that I can setup my eventSourceMapping in the Lambda.

**Comment by skinny85** [comment]
In those cases, just pass the Table from one Stack to the other. The CDK will automatically create the Export in the producing Stack, and then the `Fn::ImportValue` in the consuming Stack. No need to use `fromTableAttributes`.

**Comment by mattiLeBlanc** [comment]
I am not sure if I understand: Our stacks are separate, Appsync API, DynamoDB, ApiGateway etc. They all live in separate repos and are separate stacks with no coupling.
The Appsync stack can deploy without the DynamoDB stack being deployed, it would just not create a datasource. If you deploy the DynamoDb and then redeploy the Appsync stack it would create the datasource etc.

With this context, how should I read ` just pass the Table from one Stack to the other.` ?

**Comment by RomainMuller** [comment]
There is no way the `tableStreamArn` can be determined from the `tableName` alone, since those include a GUID of some form that changes every time the stream is re-created. So there is no way to have a `tableStreamArn` on an imported table (i.e: created by `Table.from*`) other than actually providing the value (which in your case means exporting it from your DynamoDB stack, and importing it into the other one.
