### ISSUE TITLE
[WIP] Migration guide from CDK v1.x to v2.0

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#8909]
### Nothing to see here (yet)

This issue has been created as part of devising our plan for CDK v2.0 - it is intended to collect the various migration activities users would need in order to move to the new version.

-----

**Comment by michanto** [comment]
I am using onSynthesize to output multiple templates for the same stack to perform a stack refactor.  See [CloudFormationController ](https://github.com/aws/aws-cdk-rfcs/issues/348) RFC.

**Comment by michanto** [comment]
I am using onSynthesize to output multiple templates for the same stack to perform a stack refactor.  See [CloudFormationController ](https://github.com/aws/aws-cdk-rfcs/issues/348) RFC.

**Comment by michanto** [comment]
I am using onSynthesize to output multiple templates for the same stack to perform a stack refactor.  I am wrapping and modifying the Cfn output of Stack classes, so I need to write out the templates myself.  See [CloudFormationController ](https://github.com/aws/aws-cdk-rfcs/issues/348) RFC.  Currently, I use Construct.onSynthesize for this:

class CustomSynthesis {

**Comment by michanto** [comment]
I am using onSynthesize to output multiple templates for the same stack to perform a stack refactor.  See [CloudFormationController ](https://github.com/aws/aws-cdk-rfcs/issues/348) RFC.

**Comment by michanto** [comment]
I am using onSynthesize to output multiple templates for a source stack and target stack to perform a stack refactor. See [CloudFormationController issue](https://github.com/aws/aws-cdk-rfcs/issues/348).

Pseudocode:

```typescript
interface ICfnProducer {
  readonly env: Required<Environment>
  readonly artifactId: string
  readonly artifactFileName: string // Contains the refactor step number as part of the file name
  readonly artifactDirectory: string
  _toCloudFormation(): object
}

class CustomSynthesis extends Construct {
  readonly cfnp: ICfnProducer // Passed to constructor
  
  onSynthesize(s: ISynthesisSession) {
     writeJson(`${s.assembly.outdir}/${this.cfnp.artifactDirectory}`,
               `${this.cfnp.artifactFileName}`,
               Stack.of(this).resolve(this.cfnp._toCloudFormation())
     s.assembly.addArtifact(artifactId, {
       type: AWS_CLOUDFORMATION_STACK,
       environment: envUri(this.cfnp.env),
       properties: {
         templateFile: '${this.cfnp.artifactDirectory}/${this.cfnp.artifactFileName}`
       }
  }
}
```

I use an Aspect to add these CustomSynthesis constructs to the stack, and everything works great.  I get a fully-resolved template in cdk.out, the user uploads the templates to a known S3 location that they can pass to my CustomResource, and my CustomResource can deploy the stack refactor (eventually I would like to use CDK Pipelines to deploy, but that is for another day).

How will I accomplish this without onSynthesize?  I see two options, neither of which are very appealing:

1) Hack the CDK.  Copy the ICustomSynthesis symbol and attachCustomSynthesis method. Create my CustomSynthesis construct under the App instead of under the Stack (giving it a pointer to the stack so it can call resolve), and write away. This is basically what CDK Pipelines does, but they are inside the box, not outside.
2) Wrap the stacks synthesizer with my own and call my custom synthesis code at the end of IStackSynthesizer.synthesize().  I don't like this option because now I am deciding what IStackSynthesizer class to wrap, rather than just being able to use the one the Stack provides.

What do you recommend?

My preference would be for ICustomSynthesis to be public.  It seems like the easiest choice.
