### ISSUE TITLE
[StepFunctions] Lambda task does not support RUN_JOB integration

### ISSUE THREAD

**Issue by john-tipper** [aws/aws-cdk#8943]
I want to pass just the output of a StepFunction Lambda function downstream to another task, as per [here](https://stackoverflow.com/questions/60398436/aws-step-functions-combine-task-input-with-partial-task-output).  The `REQUEST_RESPONSE` will include HTTP headers in the result object, which I do not want.  I therefore used the `RUN_JOB` integration, but get an error on synthesis.

### Reproduction Steps

```
LambdaInvoke myLambdaTask= LambdaInvoke.Builder.create(this, "myLambdaTask")
								.lambdaFunction(myLambdaFunction)
								.integrationPattern(IntegrationPattern.RUN_JOB)
								.resultPath("$.lambdaOut")
								.build();

```

### Error Log

Exception occurs on synthesis:

```
software.amazon.jsii.JsiiException: Unsupported service integration pattern. Supported Patterns: REQUEST_RESPONSE,WAIT_FOR_TASK_TOKEN. Received: RUN_JOB
Error: Unsupported service integration pattern. Supported Patterns: REQUEST_RESPONSE,WAIT_FOR_TASK_TOKEN. Received: RUN_JOB

```

### Environment

  - **CLI Version      :** 1.50.0
  - **Framework Version:** 1.50.0
  - **Node.js Version:**  v12.16.0
  - **OS               :** Windows
  - **Language (Version):**  Java

### Other

I think it should be possible to pass only the output of a Lambda function downstream, otherwise the data object that is passed downstream gets very dirty, very quickly, if you wish to pass some of the input to a task downstream as well as the output.

--- 

This is :bug: Bug Report

**Comment by john-tipper** [comment]
I've filed as a bug, as I think this functionality should be supported as a matter of routine, but I can see that RUN_JOB integration is explicitly not supported in the codebase (there are tests to check that the exception is thrown when RUN_JOB is specified), so perhaps this is a feature request? Not sure, I feel pretty strongly that I should be able to just mutate and shape data as it flows through a StepFunction state machine, without having to worry about parsing HTTP response metadata in my processing steps.

**Comment by shivlaks** [comment]
@john-tipper 

can you expand on the use case so I can better understand the behaviour you're not able to achieve? The [supported service integrations](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-service-integrations.html) check correlates to this table.

are you just trying to pass the result of the `Lambda` forward, or are you trying to use it as a part of `resultPath` ?

If you're just passing the result forward, you can set an `outputPath` of `$.Payload` and it will provide the Lambda result forward. If you're using `resultPath`, you're likely running into the limitation where a *part* of output (presumably the `$.Payload` field) cannot be appended to the task input. If that's the case, a workaround is discussed in this [comment](https://github.com/aws/aws-cdk/issues/7709#issuecomment-622529104)

**Comment by jstrunk** [comment]
I'm also interested in merging the input and output of my Lambda Tasks using `resultPath`. I can make it work using the deprecated `InvokeFunction`.

It makes sense to me that `LambdaInvoke` would support the three different ways to invoke Lambda functions with Step Functions in the [documentation](https://docs.aws.amazon.com/step-functions/latest/dg/connect-lambda.html). This behavior is the third listed by putting the function ARN in the `Resource` parameter.

It seems like this should be an additional [InvocationType](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.LambdaInvocationType.html) instead of an IntegrationPattern.

Requiring a `Pass` state is not a good pattern as that is an additional and unnecessary state transition that would add to the cost of state machines run at scale.

Another possible workaround is to move the merging of input and output into the Lambda handler. I would prefer to keep my Lambda functions simple and dedicated to their specific tasks instead of strongly coupling them with Step Functions tasks.

Using a deprecated method,
`const myLambdaTask = new sfn.Task(this, "myLambdaTask", {
      task: new tasks.InvokeFunction(myLambda),
      resultPath: "$.myLambda",
    });`

I can get the following snippet in the resulting Cloudformation:

`{\"myLambdaTask\":{\"Next\":\"nextLambdaTask\",\"Type\":\"Task\",\"Resource\":\"",
              {
                "Fn::GetAtt": [
                  "myLambda1B1B3BCA",
                  "Arn"
                ]
              },
              "\",\"ResultPath\":\"$.myLambda\"}`

I propose that we keep this behavior by adding a new `InvocationType` to the `LambdaInvoke` task construct.

**Comment by jstrunk** [comment]
After reviewing documentation, I realized that neither `InvocationType` nor `IntegrationPattern` were correct. I created a new prop called `resourceType`.

**Comment by vishalkmr1395** [comment]
@shivlaks The issue pointed out by @john-tipper was redirected some how. Here are a few insights on what he had to say. 

We have IntegrationPatterns(REQUEST_RESPONSE, RUN_JOB, WAIT_FOR_TASK_TOKEN) in Step functions. The default is REQUEST_RESPONSE. **RUN_JOB** will wait until a state completes what it was intended for (In other words until a Job (Lambda/Glue) completes execution). 

1. When we have a simple state machine where we have many lambdas to execute sequentially, we will not require RUN_JOB as the state machine will proceed to the next state only upon completion of the current state. 

2. When we have nested state machines, this problem will come into existence as if the inner stateMachine has a lambda, it does not wait for the lambda to complete but it moves on to other states as (REQUEST_RESPONSE will return successful if it is able to execute the lambda alone).

[AWS-CDK-DOCS](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.IntegrationPattern.html)

AWS Docs say they support all the patterns but unfortunately RUN_JOB isn't supported according to the error message we receive when we use it. 

Error Message -  Unsupported service integration pattern. Supported Patterns: REQUEST_RESPONSE,WAIT_FOR_TASK_TOKEN. Received: RUN_JOB
Error: Unsupported service integration pattern. Supported Patterns: REQUEST_RESPONSE,WAIT_FOR_TASK_TOKEN. Received: RUN_JOB

Please let me know if you need more details.
