### ISSUE TITLE
[apigateway] Not option to auto-deploy API Endpoints through IRestAPI construct (like RestAPI does)

### ISSUE THREAD

**Issue by zubairzahoor** [aws/aws-cdk#8951]
On adding basePathMapping to the main Rest API, the APIs created through IRestApi that is derived from main API is not accessible through root domain.
The APIs that were deployed before on the main RestApi are accessible even though they are deployed through the IRestApi later. 
Those APIs that are directly deployed through IRestApi's are not accessible from the public domain.
```
domain = new apigateway.DomainName(this, 'apiDomain', {
            domainName: this.apiDomain,
            certificate: this.certificateArn,
            endpointType: apigateway.EndpointType.REGIONAL
        })
```
`api = new apigateway.RestApi(...)`
`domain.addBasePathMapping(this.api, {basePath: v1})`

```
this.iApi = RestApi.fromRestApiAttributes(this, 'RestApiOther', {
      restApiId: api.restApiId,
      rootResourceId: api.restApiRootResourceId
    });
```

`api.root.addResource('XTestMain');`  //publicly **accessible** through domain name
`iApi.root.addResource('XTestImported');` //publicly **not accessible** though domain name

But once the API is deployed through mainAPI and then using step-deployment deployed to Imported API, it (strangely enough) **works**.

Please look into why this is happening.

**Comment by zubairzahoor** [comment]
@nija-at Any comments on this one, please?

**Comment by zubairzahoor** [comment]
I think the question needs to be rephrased. The API Endpoints are getting created but not deployed, so the deploy options are not inherited from the mainAPI. Any way to setup deploy: true and deployOptions in IRestApi for automatic deployment of endpoints?  @nija-at

**Comment by nija-at** [comment]
@zubairzahoor - this is currently not possible with `IRestApi`. You will need to manually create a new [`Deployment` construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.Deployment.html) here.

The idea for the import API (i.e., `fromRestApiAttributes()`) is that there may be a deployment defined elsewhere in a different stack, so it chooses not to create any deployments automatically.

**Comment by zubairzahoor** [comment]
@nija-at I pass the reference of the IRestAPI to another stack and add resources/methods from there just like I did for the RestAPI. I think there should be an option to let it deploy automatically like RestAPI (although in this case we can keep it 'off' by default). Otherwise using a lot of API Gateway Stacks could be a little messy while deploying manually.

**Comment by nija-at** [comment]
Unfortunately, this is quite tricky to get done right. Because the `fromRestApiAttributes()` is imported and it's possible to define Methods and Resources across multiple stacks, it's impossible for the CDK to correctly keep track of all `Method`s and `Resource`s which should trigger a re-deployment for the automatically configured deployment.

Taking a dependency on these `Method`s and `Resource`s would result in the old dependency cycles problems that this solution is trying to avoid.

Either you can use `RestApi` with deployments automatically configured or you use `fromRestApiAttributes()` to split Methods and Resources across stacks but have to manually set up a new deployment.

**Comment by zubairzahoor** [comment]
The API Resources and Methods are created in the right stack, only 'Deploy API' needs to be manually triggered. Can't we configure it to deploy it in that same stack along with the creation? I may be missing something here, but I don't see how that could not be implemented without having a dependency cycle problem. 
Do you mean this will never be done?

**Comment by nija-at** [comment]
In order to correctly configure the [Deployment resource's](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-deployment.html), physical id is [computed/modified](https://github.com/aws/aws-cdk/blob/5e087e5f3d59f931ceabebb290536a93b170522c/packages/%40aws-cdk/aws-apigateway/lib/deployment.ts#L169) based on the Methods and Resources associated with the RestApi.

This would mean that the `Deployment` CDK construct will need to depend on `Method` and `Resource` constructs, thereby creating a dependency across the stacks.

Without this logic, a new deployment will not be triggered when the Method or Resource is modified, i.e., the modification will not be reflected in the APIGateway deployment after `cdk deploy`.

> Do you mean this will never be done?

Unlikely to be done anytime soon.

The recommended way here is to define your own deployment.
