### ISSUE TITLE
[@aws-cdk/aws-sqs] Add "QueueWithDLQ" construct

### ISSUE THREAD

**Issue by mike24zl** [aws/aws-cdk#9025]
I would like to contribute a "QueueWithDLQ" construct.

### Use Case
Queue + DLQ is a very common practice and I think it is almost always desired.
This construct will reduce boiler plate code in most cases and standardise this common practice.

### Proposed Solution

A (fairly simple) extension to the Queue construct

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
For now, I think this is best suited for a third party library, or potentially the [aws solutions constructs lib](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-constructs/aws-apigateway-sqs). Since we are in the process of consolidating all of the @aws-cdk modules into a single package, we are also thinking about where higher level constructs (anything above L2) should live.

Will keep this issue open so we can revisit it while we go through this process, but I'd encourage you to publish your own construct library with the ergonomics you think are appropriate for this construct in the meantime.
