### ISSUE TITLE
[cli]: check construct module version consistency in cdk doctor

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#9071]
Mismatches of the AWS construct module versions can cause type incompatibilities and other error messages. `cdk doctor` should check for this issue. Just check that all the installed versions are the same. Optionally check that this single version is compatible with the version of the CLI currently installed (this is trickier because compatibility depends on the cloud assembly schema; also Java's pom.xml uses a variable for the module version, which would need to be resolved).

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by Jerry-AWS** [comment]
I think I can do this myself; I'll see about working it in over the next month or so.

**Comment by shivlaks** [comment]
`doctor` seems appropriate as it's meant to be the mechanism to use some checks for *symptoms* and check the set-up for potential problems

**Comment by Jerry-AWS** [comment]
What would you think about running `cdk doctor` before any synth, making it a sort of `cdk preflight` instead?

**Comment by SomayaB** [comment]
Related comment from @0xdabbad00 on #9770: 
"It sounds like you are wanting people to run another command (`cdk doctor`), whereas I would want a sanity check built right in, because for the casual or new CDK user, these error messages are misleading and if someone knew to run `cdk doctor`, they would probably know about the root cause issue in the first place."
