### ISSUE TITLE
[aws-batch] compute-environment builds spot fleet role incorrectly

### ISSUE THREAD

**Issue by damonmaria** [aws/aws-cdk#9073]
After #6706 getting fixed I still can't use the default role created by CDK. I still get `Status INVALID
CLIENT_ERROR - Parameter: SpotFleetRequestConfig.IamFleetRole is invalid.` on the compute environment when it is first used. 

If I manually create a role it works. The difference is that policy attached to the default spot fleet role by CDK is `AWSEC2SpotFleetServiceRolePolicy`, but my role (which I must have copied from AWS docs somewhere) uses `AmazonEC2SpotFleetTaggingRole`. 

When I view the CDK created role in the console it shows a warning next to it, an expanding that shows:
```
Unrecognized resource types
 arn:aws:ec2:*:*:spot-fleet-request/*
```

So it appears the AWS managed policy that CDK uses (`arn:aws:iam::aws:policy/aws-service-role/AWSEC2SpotFleetServiceRolePolicy`) is broken? 

### Reproduction Steps

As per #6706, create a compute environment without specifying a `spotFleetRole`. But, the error will not show until you actually try and run a job on that environment. 

### Error Log

`Status INVALID 
CLIENT_ERROR - Parameter: SpotFleetRequestConfig.IamFleetRole is invalid.`

### Environment

  - **CLI Version      :** 1.51.0
  - **Framework Version:** 1.51.0
  - **Node.js Version:**  v12.18.2
  - **OS               :** MacOS 10.15.5
  - **Language (Version):**  Typescript 3.8.3

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @damonmaria - Thanks for reporting this. 

Looks like it needs some more work. Filing it.

**Comment by ArielPrevu3D** [comment]
I'm not sure the bug is on CDK's side. I tried using the service-role `arn:aws:iam::114137092123:role/aws-service-role/spotfleet.amazonaws.com/AWSServiceRoleForEC2SpotFleet` (which exists on my account) and Batch sent a strange ARN when creating the Spot Fleet.

![image](https://user-images.githubusercontent.com/77351275/127054839-25cba569-de93-4821-90ef-dbb269736b06.png)

This is a screenshot of CloudTrail where `aws-batch` sends a `RequestSpotFleet` request. The template CDK generated has the correct ARN.
