### ISSUE TITLE
[aws-logs] Subscription Filter causing Asset Parameter Error in CodePipeline

### ISSUE THREAD

**Issue by parker-ballner** [aws/aws-cdk#9104]
Trying to add a new a new subscription filter to our cdk stack for a custom lambda within the same account but managed by terraform, not cdk. Adding a subscription filter object to our cdk code causing errors during the CDK deploy in CodePipeline, a 400 validation error reporting a number of asset parameters "must have values"

### Reproduction Steps
```
new logs.CfnSubscriptionFilter(this, `new_subscription_filter`, {
      logGroupName: lambdaProcessor.logGroup.logGroupName,

      filterPattern: 'NR_LAMBDA_MONITORING',
      destinationArn: `arn:aws:lambda:${AWS_REGION}:${ACCOUNT_ID}:function:newrelic-log-collector-${process.env.environment}`,
    `})
```

### Error Log

Parameters: [AssetParameters8bef7b1944e840489ef981ee3a30a860d3908d87e672b2e241724f7967272722S3Bucket31E35585, AssetParameters8bef7b1944e840489ef981ee3a30a860d3908d87e672b2e241724f7967272722S3VersionKeyCB986FAC, AssetParameters8bef7b1944e840489ef981ee3a30a860d3908d87e672b2e241724f7967272722ArtifactHash3DDB380B] must have values (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: aab09773-4ae5-4754-9ee3-53171c285e8f)

### Environment

  - **CLI Version      :**  1.47.0
  - **Framework Version:** 1.24.0
  - **Node.js Version:** v10.4.1
  - **OS               :** macOS 10.14.6
  - **Language (Version):** TypeScript (3.8.3)

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @parker-ballner ,

thanks for opening the issue. Are you saying just adding this code:

```ts
    new logs.CfnSubscriptionFilter(this, `new_subscription_filter`, {
      logGroupName: lambdaProcessor.logGroup.logGroupName,
      filterPattern: 'NR_LAMBDA_MONITORING',
      destinationArn: `arn:aws:lambda:${AWS_REGION}:${ACCOUNT_ID}:function:newrelic-log-collector-${process.env.environment}`,
    })
```

is enough to cause this error?

Thanks,
Adam

**Comment by ndrshrzg** [comment]
Hi, just chiming in:

we are experiencing a similar problem where creating a SubcriptionFilter is causing "AssetParameter must have values" error in CodePipeline.

In our case it seems that the problem is due to the CloudFormation templates being synthesized with CDK synth in a CodeBuild step which creates resources such as:

```
[...]
"LogRetention[...]BFC8A": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Handler": "index.handler",
        "Runtime": "nodejs10.x",
        "Code": {
          "S3Bucket": {
            "Ref": "AssetParameters[...]S3Bucket[...]70D8A"
          },
[...]
```

in the CloudFormation template of the stack with the LogGroup to which the SubscriptionFilter is pointing.

The problem then arises when deploying the template using CloudFormation deploy actions. A bootstrap part is missing which would probably create the necessary assets in the destination account and fill the AssetParameters with correct values.

Maybe this helps, 
Andreas

**Comment by musacibik** [comment]
+1
Is there any way to pass a CfnParameter while setting log retention or to access the created parameter from somewhere? Controlling the created parameters would be sufficient.
