### ISSUE TITLE
[@aws-cdk/assets] docs issue - Negate exclude pattern doesn't work

### ISSUE THREAD

**Issue by aecollver** [aws/aws-cdk#9146]
I'm unable to use a negated exclude glob to create an asset for a Lambda function with a single source code file.

### Reproduction Steps

    new Function(this, "DeployAction", {
      runtime: Runtime.NODEJS_12_X,
      code: new AssetCode(__dirname, {
        exclude: ["!deploy.js"]
      }),
      handler: "deploy.handler",
    });

### Error Log

No error - the asset ZIP doesn't respect the negated exclude (it contains deploy.js + the files I was trying to exclude).

The same exclude, but without negation (`deploy.js`) does work (deploy.js is excluded from the asset zip).

### Environment

  - **CLI Version      :** N/A (I don't have a global CDK installation)
  - **Framework Version:** 1.39.0 (build 5d727c1)
  - **Node.js Version:** v12.13.1
  - **OS               :** Mac OS 10.13.6
  - **Language (Version):** TypeScript 3.7.5

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Shouldn't it be `exclude: ['*', '!deploy.js']`?

**Comment by eladb** [comment]
Reopen if @jogold's solution does not work.

**Comment by aecollver** [comment]
> Reopen if @jogold's solution does not work.

My understanding from the documentation is that `exclude` is a glob. `['*', '!deploy.js']` is not a glob. Please fix the documentation if that's how you expect `exclude` to work.

**Comment by eladb** [comment]
Isn't this an array of glob patterns?

**Comment by aecollver** [comment]
* is not an exclude glob (the property name is *exclude*).

**Comment by eladb** [comment]
I am confused:

```ts
exclude: [ '*' ]
```

Means exclude all files.

**Comment by aecollver** [comment]
And !deploy.js means exclude everything not named deploy.js, right? Why
would I exclude everything and then exclude everything again (except the
file I want to include)?

**Comment by eladb** [comment]
We will add some clarification in the docs. 

Thanks for the report

**Comment by Tehnix** [comment]
The following pattern `['*', '!deploy.js']` will not work when targeting nested files.

Take the following directory structure:

```
processed/s3
├── 404
│   └── index.html
├── 404.html
├── index
│   └── index.html
├── index.html
├── manifest.json
├── _next
│   ├── mtDcbvtsiSWTu49u1CPen
│   └── static
│       ├── chunks
│       │   ├── 008e81f0d1d52809c7f07d83b45d7c061ea8668f.e69a5773cae2e55e1929.js
│       │   ├── 008e81f0d1d52809c7f07d83b45d7c061ea8668f.e69a5773cae2e55e1929.js.map
│       │   ├── 0501cb6fac2ef5204d72fbc573e6b96e1652b1c0.212ab0304221f4b971bd.js
│       │   ├── 0501cb6fac2ef5204d72fbc573e6b96e1652b1c0.212ab0304221f4b971bd.js.map
│       │   ├── 05681842d2ed34f3f6263c3960f185312550fc1f.8dd9c07e20c83c84709d.js
```

The goal is then to only include `.html` files, also the nested ones. A glob pattern of  `['*', '!*.html', '!**/*.html']` will actually exclude all nested HTML files because it excludes every directory it meets.

The output of the assets is then:

```
processed/s3
├── 404.html
├── index.html
```

whereas the expected output is:

```
processed/s3
├── 404
│   └── index.html
├── 404.html
├── index
│   └── index.html
├── index.html
```

A workaround we are currently using is to do `['*.*', '!*.html']` because `*.*` does not match the directories (which `*` will do), and then will proceed the matching down the directories to find all HTML files.

**Comment by Js-Brecht** [comment]
I don't know if I would say this is necessarily a "docs issue".  The file matching makes it rather difficult to match globs recursively.  It's great that we can use `*.*` to try to match files but not directories, but what happens if you have a folder that has a dot in it?  As uncommon as that is, that's a pretty big caveat to recursive pattern matching.

Perhaps you could use a trailing `/` as an indicator that you're trying to match against directories, and otherwise only match files?  So, I could use `["*", "!*.html"]` to match only `*.html` files recursively; if I did `["*/", "!*.html"]`, it would only match `*.html` files in the root directory.  This way, you could even exclude lists of specific folders: `["(folder1|folder2)/"]`

The array configuration is misleading, as well.  For example, you wouldn't want to do `["*.*", "!*.html", "!*.css"]`, because it would only ever match `*.css` files, since that's the last one in the array.  A couple possibilities that I could see for handling that:
1. short-circuit the `shouldExclude()` loop when a negated match is found
    https://github.com/aws/aws-cdk/blob/cc2600f4f2e43ebe8cc7b57e58e9ed75a210dfc4/packages/%40aws-cdk/core/lib/fs/utils.ts#L18-L29
2. indicate somewhere that `minimatch` is used for glob matching.  That way, people know they can do `!*(.html|.css)`, or something similar.  That still isn't perfect, but it adds more flexibility, especially if combined with short-circuiting based on negated matches.

**Comment by danielsharvey** [comment]
Just a note that the CDK now supports [IgnoreMode](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.IgnoreMode.html) as part of [Source.asset()](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-deployment.Source.html#static-assetpath-optionsspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan).

You get more standard behaviour with gitignore or dockerignore.

**Comment by iDVB** [comment]
@danielsharvey We've been trying with both `GLOB` and `GIT` with almost exactly the same outcomes.
We still come up against the issue @Tehnix [points out](https://github.com/aws/aws-cdk/issues/9146#issuecomment-667108920). `['*.*', '!*.html']`

The closest we've come is using that method but with two issues:
1) It doesn't exclude files WITHOUT an extension (files that appear to be like directories since they have no ext)
2) It leaves all the empty directories intact. Not sure if this would even be an issue or would S3 just ignore since there is no such thing as a directory in s3?

REALLY, need some direction here. More than willing to help work thru testing and troubleshooting if anyone has any ideas.

**Comment by l0b0** [comment]
@iDVB `*.*` matches files containing a dot, so it makes sense that it doesn't match files without an extension. Use `*` instead.

**Comment by iDVB** [comment]
@l0b0 As [mentioned above](https://github.com/aws/aws-cdk/issues/9146#issuecomment-667108920), using `*` doesn't work as it removes all directories. 
Would love to see a working config if anyone thinks they have the solution.

**Comment by l0b0** [comment]
You might be able to use `!*/` to include directories.

**Comment by RichiCoder1** [comment]
I'm currently running into this, but with docker. The I'd expect `['packages', '!packages/my-package']` to work (it does in docker and git), but it just stops at packages.

**Comment by iyioio** [comment]
I created a workaround that reads a `.dockerignore` file and merges all negating and regular statements. The result is fully supported by CDK and can be passed the DockerImageAsset construct using the exclude prop. 

Below is an example of using the `getCdkContainerIgnorePaths` function to convert the `.dockerignore` file in a project of mine. I'm using it in a large mono repo and my build content is set to the root of my repo.

If your Dockerfile is a the root of your build context you may need to use different name other than Dockerfile since by default CDK will read any .dockerignore file at the root of the build context and doing so will override the values returned by `getCdkContainerIgnorePaths`

``` dockerignore
# Source .dockerignore file
# packages/convo-embeddings-py/.dockerignore

*
!packages/ai-models/all-mpnet-base-v2/**
!packages/iyio-common-py/src/**
!packages/convo-embeddings-py/src/**
!packages/convo-embeddings-py/requirements.txt
**/.git
**/.DS_Store
**/venv
**/__pycache__
**/node_modules
```

``` ts
import { getCdkContainerIgnorePaths } from '@iyio/cdk-common';
import * as ecsAssets from 'aws-cdk-lib/aws-ecr-assets';

const dockerFile='packages/convo-embeddings-py/Dockerfile';
const contextDir='../..';

const ignore=getCdkContainerIgnorePaths(dockerFile,contextDir);

console.info('Ignore',JSON.stringify(ignore,null,4))

const dockerAsset=new ecsAssets.DockerImageAsset(this,'DockerImage',{
    directory:contextDir,
    file:dockerFile,
    exclude:ignore,
    ignoreMode:IgnoreMode.DOCKER,
})
```

``` js
// Converted
[
    ".DS_Store",
    ".editorconfig",
    ".env",
    ".env.cdk",
    ".env.e2e",
    ".env.local",
    ".env.run",
    ".env.serve",
    ".env.storybook",
    ".env.test",
    ".eslintrc.json",
    ".git",
    ".gitignore",
    ".nx",
    ".nxignore",
    ".pkij-bk-package-lock.json",
    ".pkij-bk-package.json",
    ".prettierignore",
    ".prettierrc",
    ".vscode",
    "CHANGELOG.md",
    "Documents",
    "README.md",
    "babel.config.json",
    "convos",
    "dist",
    "email-templates",
    "http",
    "inject-paths.json",
    "jest.config.ts",
    "jest.preset.js",
    "liirn.convo",
    "media-bucket-defaults",
    "node_modules",
    "nx.json",
    "output-cache",
    "package-lock.json",
    "package.json",
    "packages/.DS_Store",
    "packages/.gitignore",
    "packages/.gitkeep",
    "packages/.pkij.json",
    "packages/ai-complete",
    "packages/ai-complete-lambda",
    "packages/ai-complete-openai",
    "packages/ai-complete-openai-cdk",
    "packages/ai-models/all-mpnet-base-v2/.DS_Store",
    "packages/ai-models/all-mpnet-base-v2/.git",
    "packages/any-comp",
    "packages/any-comp-cli",
    "packages/at-dot-css",
    "packages/aws",
    "packages/aws-credential-providers",
    "packages/aws-dynamo",
    "packages/aws-lambda",
    "packages/aws-rds",
    "packages/aws-s3",
    "packages/aws-secrets",
    "packages/aws-sqs",
    "packages/aws-tests",
    "packages/backend",
    "packages/browser-mocks",
    "packages/cdk",
    "packages/cdk-common",
    "packages/components",
    "packages/convo-embeddings-py/.dockerignore",
    "packages/convo-embeddings-py/build-image.sh",
    "packages/convo-embeddings-py/project.json",
    "packages/convo-embeddings-py/setup.sh",
    "packages/convo-embeddings-py/test-image.sh",
    "packages/convo-embeddings-py/test.http",
    "packages/convo-embeddings-py/test.py",
    "packages/convo-lang",
    "packages/convo-lang-cli",
    "packages/convo-lang-react",
    "packages/domain-functions",
    "packages/fn-clients",
    "packages/fns",
    "packages/frontend",
    "packages/iyio-common",
    "packages/iyio-common-py/.gitignore",
    "packages/iyio-common-py/LICENSE",
    "packages/iyio-common-py/README.md",
    "packages/iyio-common-py/pyproject.toml",
    "packages/iyio-common-py/requirements.txt",
    "packages/iyio-common-py/setup.sh",
    "packages/iyio-util-fns",
    "packages/liirn-common",
    "packages/media",
    "packages/media-common",
    "packages/nextjs-common",
    "packages/node-common",
    "packages/nx-common",
    "packages/obj-sync",
    "packages/obj-sync-cdk",
    "packages/params",
    "packages/proto-nodes",
    "packages/protogen",
    "packages/protogen-runtime",
    "packages/react-common",
    "packages/rtxt",
    "packages/scripts",
    "packages/session",
    "packages/sql-migrations",
    "packages/sql-tables",
    "packages/static-sites",
    "packages/svg-charts",
    "packages/svg-charts-react",
    "packages/syn-taxi",
    "packages/tables",
    "packages/tmpl-gen",
    "packages/twilio-video",
    "packages/types",
    "packages/web-app",
    "protogen-config.json",
    "protogen.md",
    "scripts",
    "svgs",
    "tmp",
    "tools",
    "tsconfig.base.json"
]
```

Here is the code for `getCdkContainerIgnorePaths` to give you an idea of how it works.

https://github.com/iyioio/common/blob/main/packages/cdk-common/src/lib/getCdkContainerIgnorePaths.ts
``` ts

/**
 * Returns an array of paths that should be ignored based on the .dockerignore file of the given
 * docker file. The returned array is compatible with CDKs image exclusion, git ignore and docker ignore files.
 * @note Due to the way CDK handles the default docker ignore file you should use a name other than Dockerfile
 *       For you docker file. Otherwise docker will load the default docker ignore file and override
 *       the values returned getCdkContainerIgnorePaths.
 * @param dockerFilePath Docker file to search dockerignore files for
 * @param contextDir Build context directory. default = directory of dockerfile
 * @param ignoreOverrides An array of additional file or folder names to ignore. The paths can not have slashes.
 *                        default = ['node_modules','venv','__pycache__','bin','cdk.out','.git','.nx','.next']
 * @returns
 */
export const getCdkContainerIgnorePaths=(
    dockerFilePath:string,
    contextDir=getDirectoryName(dockerFilePath),
    ignoreOverrides=defaultContainerIgnoreOverrides
):string[]=>{


    contextDir=getDirectoryName(joinPaths(contextDir,dockerFilePath));

    const ignoreRules:string[]=[];

    const addPath=(path:string)=>{
        if(pathExistsSync(path)){
            const lines=readFileSync(path).toString().split('\n').map(l=>l.trim()).filter(l=>l && !l.startsWith('#'));
            ignoreRules.push(...lines);
        }
    }

    let ignoreFile=joinPaths(contextDir,'.dockerignore');
    addPath(ignoreFile);

    const dockerFileName=getFileName(dockerFilePath);
    if(dockerFileName.includes('.')){
        ignoreFile=dockerFileName.split('.')[0]+'.dockerignore';
        addPath(ignoreFile);
    }

    ignoreRules.push(`!${dockerFilePath.startsWith('/')?dockerFilePath.substring(1):''}${dockerFilePath}`);

    const ig=dockerIgnore();
    ig.add(ignoreRules);

    const {ignore}=scanContainerPaths(ig,'../..','',ignoreOverrides);

    return ignore;

}



const scanContainerPaths=(
    ig:DockerIgnore,
    baseDir:string,
    dir:string,
    ignoreOverrides:string[]
):{ignore:string[],allIgnored:boolean}=>{

    const fullDir=joinPaths(baseDir,dir);
    const items=readdirSync(fullDir);
    let allIgnored=true;
    const ignore:string[]=[];
    for(const p of items){
        const path=dir?joinPaths(dir,p):p;
        if(ignoreOverrides.includes(p)){
            ignore.push(path);
            continue;
        }


        if(ig.ignores(path)){
            const isDir=isDirSync(joinPaths(baseDir,path));
            if(isDir){
                const r=scanContainerPaths(ig,baseDir,path,ignoreOverrides);
                if(r.allIgnored){
                    ignore.push(path);
                }else{
                    allIgnored=false;
                    ignore.push(...r.ignore);
                }
            }else{
                ignore.push(path);
            }

        }else{
            allIgnored=false;
            continue;
        }
    }

    return {
        ignore,
        allIgnored,
    }
}

```

**Comment by gscpw** [comment]
This is somewhat unexpected behavior, and I was scratching my head for a while on this one as well.

One would expect that an array of GLOB patterns in a property called `exclude` are cumulative. Eg. the more GLOBs you append to the `exclude` array, the more files are excluded. So, a value like `['*', '!index.html']` might appear to exclude everything because of the GLOB `*`, then exclude everything again except `index.html` because of the GLOB `!index.html`, so the result appears to be: everything is excluded.

But this not how it works. Instead, negated patterns (the ones with a leading `!`) subtract matches from the final ignore list. So, the GLOB `*` excludes everything, but if it is followed by a negated GLOB `!index.html` then those matches are "un-excluded".

This should be clearly documented, because the intuition here points towards the first explanation rather than the second one.

**Comment by Tehnix** [comment]
> But this not how it works. Instead, negated patterns (the ones with a leading `!`) subtract matches from the final ignore list. So, the GLOB `*` excludes everything, but if it is followed by a negated GLOB `!index.html` then those matches are "un-excluded".

Isn't that also how `.gitignore` works?

If I do:

```
some-folder/*
!some-folder/.gitkeep
```

That's at least a common pattern to check-in an empty folder by excluding everything in the folder *except* the `.gitkeep` file.
