### ISSUE TITLE
[aws-s3-deployment] : Not able to use KMS key per folder, as does not add the CDK  bucket deployment Role to the KMS Policy.

### ISSUE THREAD

**Issue by ygoodmn** [aws/aws-cdk#9201]
Not able to encrypt KMS key per folder when using s3 bucket deployment.

### Reproduction Steps

1. Create Bucket
    No KMS Key
3.  Create KMS Key
4. Create KMS Alias
5. Create Bucket Deployment with 

```
let bucketDeployment = new s3deploy.BucketDeployment(this, 'DeployConfigFiles' + props.taskName, {
            sources: [s3deploy.Source.asset('dev/' +'/' + props.taskName)],
            destinationBucket: props.configBucket,
            destinationKeyPrefix:  props.taskName.toLowerCase(),
            serverSideEncryptionAwsKmsKeyId: s3ConfigKmsKey.keyId,
            serverSideEncryption: ServerSideEncryption.AWS_KMS,
        });
```

Note: It does work if you encrypt the S3 bucket with only 1 KMS key

### Error Log

Lambda Function returns

2020-07-15T19:36:13.938+05:30
upload failed: ../../tmp/tmpozte8ro9/contents/sample.txt to s3://<bucketname>//app/sample.txt An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
2020-07-15T19:36:15.078+05:30
[ERROR]	2020-07-15T14:06:15.59Z	Command '['python3', '/var/task/aws', 's3', 'sync', '--delete', '/tmp/tmpozte8ro9/contents', 's3://<bucketname>//app', '--sse', 'aws:kms', '--sse-kms-key-id', 'b82828j-5387-44ab-be4d-718299211', '--metadata-directive', 'REPLACE']' returned non-zero exit status 1.

Cloudtrail shows: 
 CDK Bucket Deployment Role       "GenerateDataKey" API was failing with "AccessDenied"

KMS Policy : 
        Does not include CDK bucket deployment role in it's statements.

### Environment

  - **CLI Version      : 1.52.0**
  - **Framework Version: 1.52.0 **
  - **Node.js Version: 12.13.1** 
  - **OS               : Windows 10**
  - **Language (Version): Typescript 3.8.3** 

### Expected
To be able to use a separate KMS key on a folder level of an S3 Bucket
CDK deployment bucket role to be added to KMS Policy:
(Example below from when KMS on bucket(creation) level in Cloudformation , which works)

```
CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
   "KeyPolicy": {
          "Statement": [
... other Statements
 {
              "Action": [
                "kms:Decrypt",
                "kms:DescribeKey",
                "kms:Encrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*"
              ],
              "Effect": "Allow",
              "Principal": {
                "AWS": {
                  "Fn::GetAtt": [
                    "CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265",
                    "Arn"
                  ]
                }
              },
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        },
```

### WorkAround
Create an S3 Bucket per KMS key (no separate folder, just separate buckets)
--- 

This is :bug: Bug Report

**Comment by ygoodmn** [comment]
Will try to build the 'role' and add it as BucketDeploymentProps,  then add it to the KMS Key Policy, to see if this works.

**Comment by ygoodmn** [comment]
FAILED: As when added another Folder, CDK did not add another CDK Deployment Bucket Function. Or perhaps I implemented it incorrectly.

**Comment by iliapolo** [comment]
Hi @ygoodmn. It kind of seems there are two issues here:

1. `BucketDeployment` doesn't create the necessary permissions for its role in order to use the KMS key inside the lambda in the first place. This responsibility falls on the user.

2. Even if the user properly configures one `BuketDeployment` to use a specific key, one cannot configure a second `BucketDeployment` to use a different key, because the underlying lambda function is reused from the first `BucketDeployment`, and therefore its role isn't updated with a new policy. 

Did I correctly capture this? 

Thanks

**Comment by iliapolo** [comment]
Dont close

**Comment by peterwoodworth** [comment]
You still want to keep this open @iliapolo? going through oldest feature requests

**Comment by iliapolo** [comment]
@peterwoodworth I think we can de-prioritize as `p2` and leave it open.

**Comment by nikovirtala** [comment]
@iliapolo @peterwoodworth I'm quite sure whether my issue belongs here, or should I open a separate issue for it, but it comes:

In case the "FileAssetsBucket" created by CDK bootstrap is encrypted with the KMS key created by CDK bootstrap, "BucketDeployment" is not able to read the "FileAssetsBucket" which it is using as a source for the deployment. This happens because the role used by the custom resource Lambda function is not allowed to decrypt the file – sounds logical.

But how should that be fixed? 

Currently, the BucketDeployment construct doesn't expose the role it creates, so that it could be easily granted with "kms:decrypt" privileges. Also, finding the corresponding KMS key ARN or Alias is a bit of an issue – I think there is no method to find it easily, in a way that works with any bootstrap?

Ideally, the "BucketDeployment" construct should know whether the bucket it is using as a source bucket is encrypted or not and grant the required privileges to the custom resource role automatically behind the scenes, so that the user doesn't need to worry about 'em.

I think I could use some of my time to contribute to fixing at the least the case I described above :)

**Comment by taabrcr** [comment]
Please reopen and fix this. The error is quite cryptic and took us hours to land here.
