### ISSUE TITLE
[cli] bootstrap with Permissions Boundary

### ISSUE THREAD

**Issue by woodstock3368** [aws/aws-cdk#9256]
### The Question
Trying to use the new developer preview for cdk-pipelines I needed to run the bootstrap process again.  [Tutorial steps here](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/).  When I ran the process it failed with IAM CreateRole errors.  It took some amount of digging to find that the root cause is related to the use of Boundary Permissions.  The new bootstrap cloudformation template creates 4 IAM Roles, all of which need a PermissionsBoundary property to be set.  Obviously, this is account specific.  As my ORG does not allow just random role creation, but will allow the role creation if the PermissionsBoundary is configured properly.  

So is it possible to have an option like `--cloudformation-execution-policies <policy>` wherein the PermissionsBoundary is provided and subsequently applied to roles being created in the bootstrap?

Please note that this is in the context of the bootstrap.  However, this question quickly applies to any CDK app.  How can one configure as an aspect for a CDK App that all roles be generated with the provided PermissionsBoundary?   

### Environment

  - **CDK CLI Version:** 1.54.0 (build c01b9b9)
  - **Node.js Version:** v12.18.3
  - **OS:** OSX 10.15.6
  - **Language (Version):** all

**Comment by njlynch** [comment]
This is a general feature request for the CLI, I believe. Motivated by, but not specific to, pipelines.

**Comment by rix0rrr** [comment]
It is. And the requests with tweaks to the bootstrapping stack are endless. I've heard 2 already in this week alone, each of them "just one more flag" to add.

We should add CLI parameters to dump the template to stdout and to use the template from a given file, and then tell people to do their org-specific customizations that way. Otherwise there will be no end to this and we'll end up with a 100-flag monstrosity.
