### ISSUE TITLE
[efs] The default policy retains a resource 

### ISSUE THREAD

**Issue by fogfish** [aws/aws-cdk#9270]
EFS uses inconsistent approach (with other modules) on the default removal policy. It retain the resource while other storage related modules removes them (e.g. RDS, S3, ...). 

### Reproduction Steps

```
new efs.FileSystem(this, 'Efs', {
      vpc,
      securityGroup: sg,
      vpcSubnets: {subnetType: ec2.SubnetType.PRIVATE}
    })
```

### Environment

  - **CLI Version      :** 1.50
  - **Framework Version:** 1.50
  - **Node.js Version:** 12.12
  - **Language (Version):** TypeScript (3.8.3)

**Comment by rix0rrr** [comment]
Do you mean that you see `"RemovalPolicy": "RETAIN"` in the final template?

Fairly sure that the default retention period for S3 is also RETAIN, and I think for RDS as well. I think we do this for most stateful resources.

Do you mean there is no way to opt out of the retain behavior?

**Comment by fogfish** [comment]
Fortunately, you can opt out the default retain behaviour. What I notice (was under strong impression), that CF removes RDS, S3, etc when resource is created with default retain policy. Only, EFS requires manual clean-up or explicit definition of retain policy.

**Comment by rix0rrr** [comment]
> CF removes RDS, S3, 

It does, but CDK changes the default for these resources, for two reasons:

* Since these are stateful resources, you'd be sad if you accidentally lost them. We want to keep your data safe.
* S3 buckets can't even be deleted if they are not empty, so deleting a stack with an S3 bucket in it will most likely fail.

As for EFS resources, do you have qualms with the CDK default or the CFN default? Although for consistency's sake, we are most likely to keep the defaults the same as other stateful resources.

**Comment by fogfish** [comment]
When I said "CF removes" I mean if they are created via CDK.
* RDS is removed only snapshots remains
* S3 I strongly believe, the removal attempt is made but it fails if it is not empty like you said.

but now, I see you point. yes, it is CfnFileSystem default one.
 
I do not think we should do anything about it.
