### ISSUE TITLE
[dynamodb] Conditionally add autoscaling for DynamoDB

### ISSUE THREAD

**Issue by ruchidesai** [aws/aws-cdk#9297]
### The Question

I am using `software.amazon.awscdk.services.dynamodb.Table` to create DynamoDB table. It has `autoScaleReadCapacity()` and `autoScaleWriteCapacity()` methods using which we can enable autoscaling. However, the construct that is passed to these methods (`EnableScalingProps`) does not have a way of specifying `CfnCondition` so that it can be conditionally created. Due to this, even though the table can be conditionally created by casting it to `CfnTable` and then setting a `CfnCondition` on it, it does not get passed on to the resources created by `EnableScalingProps`. Calling `autoScaleReadCapacity()` and `autoScaleWriteCapacity()` inside `Fn.conditionIf` does not work either. So, we have to write all [this](https://github.com/aws/aws-cdk/files/4990477/AutoScalingCode.txt) code. Is there a better way to set the condition?

Also, will there always be a divide between the abstractions and lower level Cfn resources? It would be great if we were able to set condition and logical ids on the higher level abstractions themselves, instead of having to cast them each time to lower level constructs.

### Environment

  - **CDK CLI Version:**  1.27.0
  - **Module Version:**  1.32.2
  - **Node.js Version:**  13.10.1 is installed, but I think I am using 10.x through my package manager
  - **OS:**  macOS High Sierra 10.13.6
  - **Language:**  Java

### Other information

Link to current code: [AutoScalingCode.txt](https://github.com/aws/aws-cdk/files/4990499/AutoScalingCode.txt)
What I thought would work but doesn't: [UsingEnableScalingProps.txt](https://github.com/aws/aws-cdk/files/4990544/UsingEnableScalingProps.txt) - This only sets the condition on the table and not on autoscaling resources and causes stack update to fail in the account where the table creation needs to be skipped because it still tries to create the autoscaling resources.

**Comment by peterwoodworth** [comment]
I'm very this issue has been silent @ruchidesai, you are asking a great question.

> Also, will there always be a divide between the abstractions and lower level Cfn resources?

The L1 resources are automatically generated using CloudFormation's [resource spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). So they come with pretty much exactly the functionality of CloudFormation resources, which includes supporting CfnConditions. These are the basic building blocks of any higher level Construct

L2 resources offer a level of abstraction from these direct L1 resources. Since the CDK is based in a programmatic language, some CloudFormation functionality becomes obsolete. `CfnCondition` is one of these obsolete functionalities, since we can wrap logic *around* the constructs created in our code. 

That isn't to say that there aren't any use cases for `CfnCondition` - there certainly are. But if you need to set a condition on all children of a construct, I think it would make more sense if the logic for your use case in the CDK code rather than the CloudFormation template. Is this not possible for you?

That said, if you do need to set a condition for all resources created by a construct it would be a bit ugly. You can view `cdk.out/tree.json` to view the construct tree generated by your application. This will help you successfully identify all children you do or don't want to modify. Then after that, you will do what you've done to your `CfnTable` in `UsingEnableScalingProps.txt` to all children you want to modify.

Let me know if there's anything more I can help with, and I'd be interested to hear your use case for why you want to do this as well 🙂

**Comment by ruchidesai** [comment]
Thanks for looking into this, Peter!

My use case for adding a condition was to create DynamoDB table only in beta and one prod account (out of 3 prod accounts), and enable autoscaling only in prod stage. At the time of asking the question, I was not very familiar with CDK and had recently switched from using YAML for Cloudformation. Also, I was working on a code base that had a mix of CDK and YAML and the code for defining the AWS accounts for the resource creation was elsewhere. So, I thought I should be passing a "CDK condition construct" to conditionally create resources in the CDK code as well. That was incorrect understanding. What I should instead be doing (after moving everything to CDK) is having a set of parameters for each account and region in which the stack is being created, one of the params being a boolean flag which tells whether to create a resource. And then instead of using `cfnTable.getCfnOptions().setCondition(condition);`, I can do (as you have suggested):

```
if (createTable) {
       final Table table = new Table(scope, resourceName, TableProps.builder()
                .tableName(tableName)
                .partitionKey(Attribute.builder()
                        .name(partitionKey)
                        .type(partitionKeyType).build())
                .sortKey(Attribute.builder()
                        .name(sortKey)
                        .type(sortKeyType).build())
                .removalPolicy(RemovalPolicy.RETAIN).build());
 
        if (addAutoscaling) {
            table.autoScaleReadCapacity(EnableScalingProps.builder()
                .minCapacity(minRcu)
                .maxCapacity(maxRcu).build())
                .scaleOnUtilization(UtilizationScalingProps.builder()
                        .targetUtilizationPercent(70).build());
            table.autoScaleWriteCapacity(EnableScalingProps.builder()
                .minCapacity(minWcu)
                .maxCapacity(maxWcu).build())
                .scaleOnUtilization(UtilizationScalingProps.builder()
                        .targetUtilizationPercent(70).build());
       }
}
```

Thank you for following up on this! You can close the issue.

**Comment by peterwoodworth** [comment]
Thank you for explaining your thought process, I appreciate it, and I'm happy to hear you've been able to move on with this successfully!
