### ISSUE TITLE
[aws-lambda] add support to Pipenv

### ISSUE THREAD

**Issue by noam-stein** [aws/aws-cdk#9324]
Atm if there is a `requirements.txt` file lambda-python will install the dependencies automatically,
I will like to add support to Pipenv

### Use Case
My project uses CDK to deploy python lambda, it will be great if I can use CDK to package the code.
Today I am doing manually

### Proposed Solution
If `Pipfile` and `Pipfile.lock` exist at the entry path, the construct will handle installing all required modules in a Lambda compatible Docker container according to the runtime. 
using the command `pipenv sync`

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
There are many different ways out there to compile and package code. Even within a single programming language like Python, there are several different ways.

Instead of supporting each one of these, we have introduced a generic ability for packaging - https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#bundling-asset-code.

You can plug in pipenv commands for packaging and a docker image of your choice to achieve this.

Does this satisfy?
