### ISSUE TITLE
[aws-eventschemas] TypeScript type of CfnSchema type too general

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-cdk#9366]
I've just lost a couple hours because I set the `type` of a `CfnSchema` to `OpenAPI3` instead of `OpenApi3` and got the non-descript error message "TestEvent Internal Error". It would be great if you could either
1. set the TypeScript type of `type` to `'OpenApi3`, as no other values are allowed at the moment if I'm not mistaken
2. Choose a better error message like `Invalid type "OpenAPI3"`, or at least
3. document the available values here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eventschemas-schema.html

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
I understand your frustration.

This issue is currently not actionable for CDK, as we have no hand-written code in that module, so you are effectively writing CloudFormation using a typed programming language. Please report this issue on [CloudFormation's issue tracker](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap) instead.

----

As a general debugging tip, 80% of what CloudFormation does is simply call the underling `CreateSchema` or `UpdateSchema` call (or whatever the resource case may be), so you can occasionally get more information by reading the service documentation for those particular API calls.

In this particular case, the [CreateSchema docs of the service](https://docs.aws.amazon.com/eventbridge/latest/schema-reference/v1-registries-name-registryname-schemas-name-schemaname.html#CreateSchema) show under **CreateSchemaInput** that `Type` only has one allowed value.
