### ISSUE TITLE
[aws-apigateway] overrideLogicalId does not work properly

### ISSUE THREAD

**Issue by beomseoklee** [aws/aws-cdk#9419]
### The Question

I'm using another library which creates a lot of CDK resources automatically. In that library, API Gateway is created using ```@aws-cdk/aws-apigateway/LambdaRestApi```.  As I don't need every resource created by the library, I used ```tryRemoveChild``` function to delete unnecessary resources and ```overrideLogicalId``` function to change the logical ID of the resource. Everything worked fine except API Gateway deployment.

Even though I deleted ```Default``` child (it contains {proxy+} and ANY resources) from API Gateway, ```Deployment``` tries to create dependencies on that resources, and the ```Deployment``` logical ID does not change after ```cdk synth```.

On the same environment, it worked, and when I reinstalled npm packages, it never works again. Please see the code snippet in other information section.

### Environment

  - **CDK CLI Version:** 1.54.0
  - **Module Version:** 1.54.0
  - **Node.js Version:** 12.13.1
  - **OS:** OSX Mojave / Ubuntu 
  - **Language (Version):** TypeScript (3.9.6) 

### Other information

```javascript
// API Gateway
this.removeAllChildren(apiGateway.node.findChild('Default'));  // Adding this one throws an error when cdk synth because Deployment tries to add deleted resources to dependencies.
this.removeChildren(apiGateway, [ 'Endpoint', 'UsagePlan', 'Deployment', 'Default', 'DeploymentStage.prod' ]);
const cfnApiGateway = apiGateway.node.defaultChild as cdkApiGateway.CfnRestApi;
cfnApiGateway.body = apiBody;
cfnApiGateway.overrideLogicalId('API');  // This one changes AWS::ApiGateway::RestAPI to API

// Deployment
const apiGatewayDeployment = new cdkApiGateway.Deployment(this, 'Deployment', { api: apiGateway });
cfnApiGatewayDeployment.overrideLogicalId('Deployment');
```

```javascript
// removeChildren function
removeChildren(resource: cdk.IConstruct, children: string[]) {
  for (let child of children) {
    resource.node.tryRemoveChild(child);
  }
}

// removeAllChildren function
removeAllChildren(resource: cdk.IConstruct) {
  let children = resource.node.children;
  for (let child of children) {
    this.removeAllChildren(child);
    resource.node.tryRemoveChild(child.node.id);
  }
}
```

And the CDK synth returns the below logical ID and deleted dependencies.
```json
"StackDeployment723D10CB114a334f9f94a41d7f78d0c17480e9c5": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "RestApiId": {
          "Ref": "API"
        },
      "DependsOn": [        
        "THIS_SHOULD_BE_DELETED_proxyANYF3004F7A",
        "THIS_SHOULD_BE_DELETED_ANY4B5FECCB"
      ]
}
```

**Comment by nija-at** [comment]
This is likely because `Deployment` resource has [its own logic](https://github.com/aws/aws-cdk/blob/v1.54.0/packages/@aws-cdk/aws-apigateway/lib/deployment.ts#L172) on computing the logical id.

Nevertheless, your approach on deleting the underlying resources is not recommended and is going to lead you into deeper problems and unexpected behaviour. 

What are you trying to achieve, and why are you deleting the underlying resources? The CDK looks to create resources that are needed for the infrastructure to function, and properties for each of these constructs provides control over them.

If you would like low level control over the resources created by the CDK, use the low level constructs (they start with `Cfn`), such as, `CfnRestApi`.

**Comment by beomseoklee** [comment]
@nija-at Thanks for your reply. Using ```CfnDeployment``` instead of ```Deployment``` seemed to resolve the issue.
