### ISSUE TITLE
CDK best practices for multiple regions and shared infrastructure

### ISSUE THREAD

**Issue by frank69m** [aws/aws-cdk#9421]
So, for my typescript CDK, I've built out an ECS microservice. Within there, I create the service, iam roles, task definition, etc.

everything works great. the idea behind putting the iam roles in there is to destroy them once I'm done with the microservice

When I try to deploy this out to another region, I get the error that the iam role already exists... Well, because it's a shared service...  

How have you other guys handled such a case where your CDK code can build out on any environment.

**Comment by rix0rrr** [comment]
The problem here is that you are giving your roles physical names, and there can not be 2 roles with the same name.

Just have names automatically generated for your roles, and stop worrying about how many there are.

If you really REALLY must share roles between applications, create them in some other way (by hand, using a separate CDK app) and import them by using `Role.fromRoleArn()`. But I would recommend against that.
