### ISSUE TITLE
[pipelines] why new style Toolkit creates an ECR registry for storing the images deployed by the toolkit stack?

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#9422]
### The Question

The CDK toolkit stack has been updated to version 3 for using CDK pipelines. I observe there is an ECR repository created by new version CDK toolkit with non user friendly name. And the ECR images deployed by CDK apps will be pushed to this repo with hash tag. I think this behavior introduces below drawbacks,

- The prop 'repoName' of ECR asset is useless any more. All ECR images managed by CDK apps are pushed into same ECR repository.
- Different ECR images are pushed into same repo, CDK uses the hash of image to distinguish them. It's very hard to use and maintain those images outside CDK world. Also the history versions of ECR images can not be managed by CDK itself.

Could you pls point out the doc to elaborate more information why introducing those changes in new version of CDK toolkit?

### Environment

  - **CDK CLI Version:**  1.56.0
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by rix0rrr** [comment]
The CDK CLI was never a method to build and publish your ECR image for later consumption by other means. It was always intended to  get a Docker image into ECR in order to deploy a stack that needs that image, right here and right now. As such, you shouldn't need to care where the image lives or what it's called. 

If you need the image in a certain repo, I suggest you write a custom resource that pulls the image from the shared ECR repo and pushes it to the target repo.

The design of the feature and the need for the single repo is described here: https://github.com/aws/aws-cdk-rfcs/blob/master/text/0049-continuous-delivery.md
