### ISSUE TITLE
[aws-efs] Upload files to EFS 

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#9496]
Create a construct that allows you to upload files to EFS, similar to the aws-s3-assets package.

### Use Case

I want to have configuration files available in my Fargate container. By using an EFS mount, I don't have to create a custom docker image that runs a script to download a few config files from an s3 bucket.

### Proposed Solution

One way to do this would be to upload the files to the CDKToolkit bucket first. Then use a custom lambda that mounts the same EFS and streams the files from S3 directly to the EFS. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I think this is a great idea, but I'm not sure this makes sense in the core library just yet.

I would encourage you to build and distribute a 3rd party package that does exactly this yourself. 

If it turns out that it is supremely useful (let's say, >70% of CDK applications that use EFS also use your package) we can always have another talk about including it in the core CDK distribution.

**Comment by y4nnick** [comment]
For future reference: [cdk-efs-assets](https://github.com/pahud/cdk-efs-assets#readme) should work for this use case.

**Comment by Mejato** [comment]
Here is a elegant workflow to achieve this without further construct development:

* Use the aws_s3_deployment construct to unzip files into a S3 bucket
* Use the aws_datasync constructs to setup a data sync job from S3 to EFS.
