### ISSUE TITLE
[aws-lambda-python] Unify `entry` field betwen aws-lambda-nodejs and aws-lambda-python 

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#9518]
I love the new PythonFunction support in aws-cdk! I did, however, notice a difference between how the `entry` property works between `aws-lambda-nodejs` and `aws-lambda-python`.

In `aws-lambda-nodejs`, the `entry` field is a fully qualified path to the index file. From the docs:

https://github.com/aws/aws-cdk/blob/9fbeec3d7fe73ec870fe2de0e122b7714165f70e/packages/%40aws-cdk/aws-lambda-nodejs/README.md#L34-L40

However, the `entry` and `index` are broken into two distinct properties in `aws-lambda-python`. From the docs:

https://github.com/aws/aws-cdk/blob/9fbeec3d7fe73ec870fe2de0e122b7714165f70e/packages/%40aws-cdk/aws-lambda-python/README.md#L19-L22

So, when I was converting a function over to `PythonFunction`, I fully specified the `entry`, like I would with `NodejsFunction`:

```ts
new PythonFunction(this, 'MyFunc', {
  entry: path.join(__dirname, 'lambda', 'my_lambda.py')
}
```

But I received this error, which surprised me.

```
Cannot find index file at /Users/blimmer/my-project/foo/src/my-func/lambda/my_lambda.py/index.py
```

I fixed the problem by using `entry` and `index` like this:

```ts
new PythonFunction(this, 'MyFunc', {
  entry: path.join(__dirname, 'lambda'),
  index: 'my_lambda.py',
}
```

However, I believe that `entry` should work the same between python and nodejs for consistency.

### Use Case

Unifying the `entry` property between `PythonFunction` and `NodejsFunction` will make it easier for developers to define both types of functions.

### Proposed Solution

I propose that `index` be removed from `PythonFunction` and for `entry` to be the fully qualified path to the index file, like it is in `NodejsFunction`.

### Other

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by adamelmore** [comment]
Fwiw, my first implementation of `PythonFunction` took the approach you describe here; however, it was pointed out in review that this wouldn't allow for an index file in a subdirectory and required that it be adjacent to `requirements.txt`.

@eladb have any additional thoughts on this?

**Comment by eladb** [comment]
I think the python API makes more sense given it's more flexible. @jogold can we change the -nodejs version?

**Comment by jogold** [comment]
> I think the python API makes more sense given it's more flexible. @jogold can we change the -nodejs version?

Why is it more flexible? Also for the `nodejs` version we have automatic entry file lookup...

**Comment by adamelmore** [comment]
@jogold @eladb let me know what direction you'd like to take here; I'm happy to do the grunt work in either case once there's a consensus.

**Comment by ztane** [comment]
Please do not unify anything. In fact the current implementation does not work with all Python lambda code where it would make sense. In Python lambda it would make sense to have *only* the current meaning of `entry` *and* the `handler` parameter with `index` gone altogether.

How the AWS Lambda Runtime for Python is realized is that it will unpack the source files into a directory that is in Python module search path. One specifies the handler in format `foo.bar.baz`. The Lambda runtime will decode this as `from foo.bar import baz` and thereinafter use `baz` as the handler function. Now the problem is that we need to rewrite all of our lambda code that was inside modules *just* that we can have one `.py` file in a suitable place so that it works. 

There are no ["index files"](https://github.com/aws/aws-cdk/blob/9fbeec3d7fe73ec870fe2de0e122b7714165f70e/packages/%40aws-cdk/aws-lambda-python/lib/function.ts#L56) in Python, so looking for one is misguided. In fact I've been writing a library that would have the handler *inside it* - a small framework setting up logging and such, and then calling the the actual handler function that resides in the installed source code. The handler need not even be in a *file*, it is just sufficient that it is something that Python can import.

The fix could be as simple as removing the index parameter and specifying that the entry must be a directory, and then just:

```
    const handler = props.handler ?? 'index.handler';
    const runtime = props.runtime ?? lambda.Runtime.PYTHON_3_7;

    super(scope, id, {
      ...props,
      runtime,
      code: bundle({
        ...props,
        entry,
        runtime,
      }),
      handler: handler,
   }
```

It is of course possible to make it work with the `index` parameter as well, if specified, but the default value is tricky.

**Comment by michaelbrewer** [comment]
`PythonFunction` does not seem to work for me when there are subdirectories ie:

```kotlin
        val function = PythonFunction(
            this,
            "loanFunction",
            PythonFunctionProps
                .builder()
                .entry("../../src/")   // dir with lambda code
                .index("loan/app.py") // lambda 
                .handler("handler")
                .runtime(Runtime.PYTHON_3_8)
                .build()
        )
```

```
./loan
./loan/__init__.py
./loan/app.py
./loan/clients.py
./loan/exceptions.py
./requirements.txt
./__init__.py
```

So i would expect: `loan.app.handler` to be the handler, but CDK wants `loan/app.handler` which does not work for Python

**Comment by michaelbrewer** [comment]
FYI, end up not using the PythonFunction, and used Code.fromAsset

```kotlin
val function = Function(
    this,
    "loanFunction",
    FunctionProps
        .builder()
        .handler("loan.app.handler")
        .runtime(Runtime.PYTHON_3_8)
        .code(
            Code.fromAsset(
                "../../src/",
                AssetOptions
                    .builder()
                    .bundling(
                        BundlingOptions
                            .builder()
                            .image(Runtime.PYTHON_3_8.bundlingDockerImage)
                            .command(
                                mutableListOf(
                                    "bash", "-c",
                                    "pip install -r requirements.txt -t /asset-output && cp -au . /asset-output"
                                )
                            )
                            .build()
                    )
                    .build()
            )
        )
        .build()
)
```

**Comment by ztane** [comment]
@michaelbrewer  yes, and the unification they're after in this bug would make it even more difficult to get anything like that working.

**Comment by michaelbrewer** [comment]
> @michaelbrewer yes, and the unification they're after in this bug would make it even more difficult to get anything like that working.

Based on the limitations of `PythonFunction`, i would just stick to using `Code.fromAsset(`
