### ISSUE TITLE
[eks] Cluster creation failure not detected 

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#9529]
If an EKS Cluster creation fails (of type `Custom::AWSCDK-EKS-Cluster`), the Custom Resource does not notice it, causing stack creation to time out.

### Reproduction Steps

Create an EKS cluster and pass it an invalid subnet ID (e.g., an Outposts subnet).

### What did you expect to happen?

Expected Custom Resource to post failure and rollback as soon as EKS cluster creation failure state was detected.

### What actually happened?

Custom Resource was stuck in provisioning state.

### Environment

  - **CLI Version:** 1.56.0
  - **Framework Version:** 1.56.0
  - **Node.js Version:**  12.18.2
  - **OS:** MacOS 10.15.6
  - **Language (Version):**  all

### Other

--- 

This is :bug: Bug Report

**Comment by otterley** [comment]
I think the issue can be found [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts#L199-L202):

```
    if (cluster?.status !== 'ACTIVE') {
      return {
        IsComplete: false,
      };
```

There are no short circuits for `FAILED` state as per the [API documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_Cluster.html#AmazonEKS-Type-Cluster-status).

**Comment by iliapolo** [comment]
@otterley Could you please provide a reproduction snippet? How exactly did you bring the cluster to a `FAILED` state? Not sure what you mean by Outpost subnet.

Im trying to recreate this by passing invalid subnet id's or insufficient role permissions, but in never reaches that state because the request to create the cluster itself fail in validation, so it never even starts provisioning.
