### ISSUE TITLE
[aws-cloudtrail] Custom log delivery role 

### ISSUE THREAD

**Issue by Wenzil** [aws/aws-cdk#9583]
Hello. Can you add a CloudTrail Trail prop for passing in the role to use for CloudWatch logs delivery ? As it is, CDK creates the role for us.

### Use Case

To support our permission strucutre, we namespace all the service roles we pass to AWS services in a particular way. The role name that CDK chooses on our behalf doesn't satisfy our naming convention.

### Proposed Solution

Add an optional `role: IRole` prop to the Trail constructor. If present, have the trail use this role for cloudwatch log delivery (if enabled)

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can use CFN overrides in the mean time

**Comment by Jay1305** [comment]
As a new user of cdk who stumbled upon the same issue mentioned in the subject, I saw this ticket today. Someone just said to use CFN overrides. It would have been beneficial if they included some simple example or url to look for. 

This issue was closed due to inactivity but moreover, this issue was mentioned in some feature pull request which was also abandoned!
