### ISSUE TITLE
[aws-s3-deployment] Support for copying zipped assets

### ISSUE THREAD

**Issue by sridevi1302** [aws/aws-cdk#9586]
## :question: General Issue

I'm using aws-s3-deployment to copy an asset into a specified S3 bucket. But as my asset itself is a zip file, it automatically gets unzipped while being copied to the destination S3 bucket. Is there a way to avoid unzipping of files into destination bucket? 

### The Question
Is there any flag which can prevent unzipping of files into the destination S3 bucket?

### Environment

  - **CDK CLI Version:** 1.32.2
  - **Node.js Version:** v10.21.0
  - **OS:** macOS Mojave 10.14.6
  - **Language (Version):** Java (8)

**Comment by iliapolo** [comment]
@sridevi1302 You need to put the zip file in a directory, and use that directory as the asset.

We've seen a few requests to treat zip files as is, without needing this wrapper directory, so we are considering adding such support. But in the meantime, just put it inside a directory.

**Comment by iliapolo** [comment]
@sridevi1302 You can track this issue for more details: https://github.com/aws/aws-cdk/issues/8065

**Comment by sridevi1302** [comment]
@iliapolo In my usecase, I have the zip files present in S3 bucket. So putting the zip files in a folder will not be of great use as BucketDeployment construct doesn't support copying remote S3 directories.

**Comment by iliapolo** [comment]
@sridevi1302 Unfortunately there is no way to flag `BucketDeployment` so that it treats remote assets as regular files. It assumes the object in the bucket is "an already zipped" CDK asset, so it unzipps it.

I'm going to mark this as a feature request for adding a flag on the `Source` configuration, instructing that that file should not be extracted.

We would happily accept a contribution for this :)

**Comment by markcarroll** [comment]
The problem I am trying to solve is that I want to use the s3-deployment module to get some documentation files into an S3 bucket on deployment.  The in a different (website) project I want to use s3-deployment to copy those files from that S3 bucket to a web site bucket that is being deployed. However, the s3-deployment "upload" insists on unzipping them into the S3 bucket and when passing an s3 bucket to s3-deployment as a source, it expects a zip file. This results in a no-win situation.  

I would either like to tell s3-deployment not to unzip on copy, or to take a folder name as the source and do an `s3 sync` instead of an `s3 cp` on deployment.  Make sense?

**Comment by iliapolo** [comment]
@markcarroll Sure. This also sounds like additional `Source` types for bucket deployment. Perhaps a `Source.bucketDirectory` or something like that.

**Comment by markcarroll** [comment]
@iliapolo that would certainly work, yes.

**Comment by IngussNeilands** [comment]
Would be nice to be able to copy zip file from s3 bucket to another s3 bucket without unzipping it, or upload directory into s3 bucket as zip archive - it would help with lambda creation

**Comment by mvoitko** [comment]
Is there a way to upload a zip file?
