### ISSUE TITLE
software.amazon.awscdk.services.codedeploy.LoadBalancer.application construct seems to be wrong

### ISSUE THREAD

**Issue by mohdarshad** [aws/aws-cdk#9677]
software.amazon.awscdk.services.codedeploy.LoadBalancer.application(**ApplicationTargetGroup**) should be Like LoadBalancer.application(**IApplicationTargetGroup**). It should accept the instance of IApplicationTargetGroup instead of ApplicationTargetGroup

**Comment by skinny85** [comment]
Hey @mohdarshad ,

the issue is that CodeDeploy uses the [`targetGroupName` property of `ApplicationTargetGroup`](https://github.com/aws/aws-cdk/blob/0ea4ea3734c4fb136515d85f9b0a791649aa51f2/packages/%40aws-cdk/aws-codedeploy/lib/server/load-balancer.ts#L47-L47), which is not currently available for `IApplicationTargetGroup`.

We would have to research whether the name of the target group can be derived from its ARN (as that's what would be required to do this for imported Target Groups).
