### ISSUE TITLE
[aws-ecs] Ephemeral port range is wider than expected on AL2 ARM

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#9778]
AL2 aarch64 has a larger ephemeral range configured:

```
-bash-4.2# sysctl -a | grep range 
net.ipv4.ip_local_port_range = 1025     65000
```

This causes issues because in CDK we use this hardcoded port range to open ports on the EC2 instances to the LB: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L505-L508

Also see the ECS docs on the ephemeral range: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html

Currently on ARM instances runnin AL2 aarch64 the ephemeral port range is much wider, and as a result containers can be assigned ephemeral ports in the 1025 - 32767 range as well. Then the LB can not communicate to the service on these lower ports which are outside the hard coded ephemeral range, resulting in hung services which can not pass healthchecks.

**Comment by jahkeup** [comment]
The configured ephemeral range can vary on hosts. In fact 32768 (which is the current low end of the range) sits in the ["registered ports" range according to RFC6056](https://tools.ietf.org/html/rfc6056#section-2.1), so technically its a departure from the recommendation already. 

An administrator may find it more appropriate to have a system's applications use a significantly larger range that uses a lower port number to start (eg: 1025-65535). If these admins do, then the CDK should allow these hosts to communicate correct with the LBs. Especially since the ECS agent is usable on other platforms, the CDK's range should be widened to allow alternative ephemeral range configurations.
