### ISSUE TITLE
 [aws-eks] How to get reference to CdkStackclusterKubectlProviderSecurityGroupXYZ?

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#9780]
This was posted by @acim over at the CDK Developer Guide repo https://github.com/awsdocs/aws-cdk-guide/issues/256. It's not immediately clear to me whether this information is even available through the API, in which case this is a feature request. Otherwise it's an API Reference doc issue.

When I create EKS cluster using TS CDK, two security groups`with the following descriptions get created. 

```
EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.
```
and
```
EKS Control Plane Security Group
```
The first one can be referenced by cluster.clusterSecurityGroupId, where cluster is a constant referencing the created cluster itself. However, I can't find any reference to the second one. In AWS Console, the first one can be found under "Cluster security group" and the second one under "Additional security groups". I need to modify the second one, to add a rule.

**Comment by iliapolo** [comment]
Hi @acim (and @Jerry-AWS).

Im a little confused, the issue title mentions gaining access to a security group called`CdkStackclusterKubectlProviderSecurityGroupXYZ`. However, the PR body refers to a security group with the *EKS Control Plane Security Group* description. Those two are different.

#### CdkStackclusterKubectlProviderSecurityGroupXYZ

This is a security that is created internally so that we can run `kubectl` commands against the cluster from custom resources. It is **not** attached to the cluster itself, only to the lambda that runs the `kubectl` handler. 

This one indeed cannot be accessed currently, do you need to access it? if so, can you explain the use case?

#### EKS Control Plane Security Group

This security group is created by CDK and is indeed attached as an *Additional Security Group* of the cluster. You can actually access this by doing

```typescript
cluster.connections.securityGroups
```

Also note that `cluster.connections` actually returns an `ec2.Connections` class, which has a rich API for creating security group rules. See https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-ec2#allowing-connections.

**Comment by acim** [comment]
Thank you @iliapolo, I have tried cluster.securityGroups which is undefined so obviously I should have used cluster.connections.securityGroups. Thank you, this is what I want, this can be closed.
