### ISSUE TITLE
[cloudfront] [lambda] Cross-region Lambda construct for Lambda@Edge 

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#9862]
Create a construct (e.g., `EdgeLambda`) which facilitates defining Lambda functions cross-region.

### Use Case

CloudFront is a "global" service, but requires that both certificates and Lambda@Edge functions be defined in `us-east-1` (N Virginia) to use them with a distribution. This creates a lot of overhead for users who have stacks that include CloudFront in different regions.

Customers must have separate stacks to host the Lambda function, then use SSM (or another alternative) to communicate the ARN between stacks. See https://github.com/aws/aws-cdk/issues/1575#issuecomment-674767075 for a detailed explanation of the process as it exists today.

### Proposed Solution

The other CloudFront-constrained service (AWS Certificate Manager) has a custom resource for this purpose: `DnsValidationCertificate`. Stealing ideas from that pattern may be useful. One of the complications for Lambda (vs ACM) is that Lambda functions often require assets, which is more heavy-weight than just passing the defining parameters/props.

CodePipeline has a mechanism for cross-region deployments (see the README section titled 'Cross-region CodePipelines'). This relies on creating sub-stacks in the target region with defined buckets for replicating the assets:

https://github.com/aws/aws-cdk/blob/b5f2f75128e156c04bcd4b4f3513d7387515be1d/packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts#L467

---

This is a :rocket: Feature Request

**Comment by robertd** [comment]
@njlynch This might be premature to ask right now, but would it be possible to handle Lambda@Edge scenarios where experimenting with it (especially renaming/deleting) causes stack deployments to fail due to the nature of lambda@edge versioning? Due to this we've elected to move out L@E into separate stack/repo (that and region issue of course)... Same goes for ACM :).

![image](https://user-images.githubusercontent.com/31543/90790370-368f0a00-e2c5-11ea-8439-35143066165a.png)

Note: I've noticed this by using aws-solutions-construct library which currently uses older version of the aws-cloudfront constructs (https://github.com/awslabs/aws-solutions-constructs/issues/39). Also, aws-solutions-constructs doesn't do multi-region deployments for their aws-cloudfront-s3 solution (everything goes into us-east-1). Thus, this issue is something I'm excited to see in action (and it hopefully trickles down to aws-cloudfront-solutions repo at some point). 👍

**Comment by jbaileyashe** [comment]
@robertd did you ever find a workaround for dealing with Lambda@Edge functions? Waiting 24 hours to try and destroy again is pretty painful.

A hack that would work is for the Lambda@Edge API to return a 200/204 when you try to delete a replicated function. CloudFront is going to delete it automatically anyways, so why give the user a spurious error? 

I posted a forum thread, if anyone would like to show support for the idea: https://forums.aws.amazon.com/thread.jspa?threadID=331402

**Comment by robertd** [comment]
@jbaileyashe Unfortunately no. We have name suffix randomizer component added to our Lambda@Edge functions so that each time we make change new function is deployed (rather than changed/deleted) and associated to our CF distro. Then we clean them up later on through scheduled task thru Gitlab CI/CD.

**Comment by nihakue** [comment]
Our teams have also had success with a custom resource provider that creates the source code s3 bucket and lambda function using the aws sdk. It's a bit ick, but it lets you keep everything in one stack. I can't share code, but basically:

1. create a bucket in the region to want to deploy to and put the lambda source code in it (can be done with normal constructs)
2. Create a custom resource that:
  a. create a bucket in us-east-1
  b. copies source from bucket in your region to us-east-1
  c. creates lambda in us-east-1
  d. returns created lambda version/arn
