### ISSUE TITLE
[cdk-pipelines] Specifying a VPC for the pipelines.CdkPipeline?

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#9982]
Is there a way to specify a VPC where to run the `pipelines.CdkPipeline`? We need to run some internal tools as part of the pipelines which would require a VPC that has access via a VPN connection to the tooling.

I tried to look into configuring a VPC in `SimpleSynthOptions` and `CdkPipelineProps` but could not find the option.

### Environment

  - **CLI Version      :**  1.60.0
  - **Framework Version:** 1.60.0
  - **Node.js Version:** v14.8.0
  - **OS               :** macOs
  - **Language (Version):** 4.0.2

--- 

This is a :rocket: Feature Request

**Comment by markusl** [comment]
It would also be important to be able to run the actions within stages in a specific VPC:

```ts
    const devService = new InfraStack(...);
    const devAppStage = pipeline.addApplicationStage(devStage);
    devAppStage.addActions(new pipelines.ShellScriptAction({
      actionName: 'IntegrationTests',
      vpc, // Should be able to specify a VPC here to have proper connectivity
      useOutputs: {
        SERVICE_URL: pipeline.stackOutput(devService.loadBalancerDnsName)
      },
      commands: [
        'curl -v $SERVICE_URL',
      ],
    }));

```

**Comment by blaenk** [comment]
I'm interested in this too. I wonder if it's done by using a [`CodeBuildAction`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CodeBuildAction.html) and passing to it a `Project` that has been [configured with a VPC](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codebuild-readme.html#definition-of-vpc-configuration-in-codebuild-project). Of course, that means we can't use the higher level constructs like `ShellScriptAction`.

I do see that `ShellScriptAction` has a [`project` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.ShellScriptAction.html#project-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span) so maybe  the same thing can be done there? It would probably have to be cast to a [`PipelineProject`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.PipelineProject.html) though in order to set its `vpc` property.

Alternatively, it can probably be done through 'raw' CloudFormation variables in CDK. I'll probably try the above approaches first.

**Comment by rix0rrr** [comment]
If SimpleSynthAction and ShellScriptAction don't satisfy your needs, I recommend you setup a CodeBuild Project directly instead.

**Comment by rix0rrr** [comment]
I guess I will accept a PR that adds a VPC property though. I see the use.
