### ISSUE TITLE
[rds] CDK Deletes DB Secrets before DB Instance 

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#9999]
I'm not sure if this is a bug or feature. I've got a DB instance with an auto-generated secret for its master credentials. Now when I try to delete the stack it first delete its secrets and then goes for the DB instance (which might fail if the deletion protection is enabled) or at least it does all at the same time. Doesn't it make sense to first try to delete the DB instance first and then go for secrets?

### Reproduction Steps
```typescript
// Create a DB instance
      const instance = new rds.DatabaseInstance(this, 'WebApiPostgres', {
        engine: whatever, // I used postgres if that matters.
        masterUsername: 'postgres',
        vpc: vpc,
      });
```

### What did you expect to happen?
I expect secrets to be deleted after successful deletion of the DB instance.

### What actually happened?
It first delete all secrets and the DB instance together.

### Environment

  - **CLI Version      :** aws-cli/2.0.24 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev28
  - **Framework Version:** 1.54.0 (build c01b9b9)
  - **Node.js Version:** v14.5.0
  - **OS               :** Mac OS X 10.15.6
  - **Language (Version):** typescript ~3.7.2

### Other
Even if it's not possible to do this, can we have a way to specify the RemovalPolicy for the auto-generated master credentials?

--- 

This is :bug: Bug Report

**Comment by davidmckenzie** [comment]
This still affects us when I last checked, would like the issue kept open.

**Comment by comcalvi** [comment]
This requires us to create a dependency from the instance -> secrets. I'm not sure if that's possible (it won't be if the secrets -> instance), but in general all resources that use secrets could potentially fix this here: https://github.com/aws/aws-cdk/blob/0b25265e5105d03fe6290e24462e45398695a11e/packages/%40aws-cdk/aws-ec2/lib/cfn-init.ts#L92.

**Comment by colifran** [comment]
@davidmckenzie @akefirad I worked through replicating this issue on my end using a vpc with a private and a public subnet. I provisioned an ec2 instance in the public subnet and a rds database instance in the private subnet. I created the rds instance using credentials based on a secret managed by AWS secrets manager.

I reviewed the template created after running cdk synth and the database instance has a dependency on the secret. CloudFormation creates resources based on their dependencies meaning the secret was created before the database instance was created. During deletion, CloudFormation will delete resources in reverse order. I went through cdk deploy and cdk destroy multiple times and monitored the events in CloudFormation and it appears to be working as expected - the database instance is deleted before the secret is deleted.

Are you both still experiencing the secret being deleted before the database instance? If so, could you provide any code we could use to better replicate your cdk app?

**Comment by davidmckenzie** [comment]
I haven't replicated this in a while, but from memory the issue was that it wouldn't wait for completion of the deletion before moving onto the secret, so it would start to delete DB, then start to delete secret, then complete deleting secret, then fail deleting DB. Did you try this with deletion protection enabled on the DB cluster?

**Comment by colifran** [comment]
I ran this with deletion protection enabled and it correctly fails to delete the DB instance, but then moves on and deletes the secret. I think this may be something more on the CloudFormation side, but I'm wondering if we might be able to throw some kind of warning about manually disabling deletion protection before moving on to deleting the stack. I'll investigate some more and see what our options are.

**Comment by colifran** [comment]
I investigated this some more with the team internally and this sounds like a problem on the CloudFormation side rather than a CDK bug. I've created a ticket with the CloudFormation team explaining the problem and provided them with a sample CloudFormation template that can be used to recreate the issue.

**Comment by BalmungSan** [comment]
@colifran Sorry to bother but I think we are facing either this issue or something similar.
Currently, we are doing some PoC related to **Aurora** so we have been creating and deleting a couple of clusters during the past weeks. Whenever we delete the `Stack` it fails because the `Secret` was deleted before the `Cluster` which leaves it in an inconsistent state. We then need to ask administrators to help us delete the resources manually.

I understand that according to you this is not a **CDK** issue but rather a **CloudFormation** one, but is there any way to check if that ticket you created was resolved? If it hasn't been resolved, is there any way for us to track its progress and mention that we are also affected by it
